--[[
This is the HostelBar spells table.
--]]
HostelBar.SpellsDB = {

			-- items and racials
			["Brittle Armor"] = 		{time=20,  school="Shadow",	class="warlock"}, 
			["Unstable Power"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Restless Strength"] = 	{time=20,  school="Shadow",	class="warlock"}, 
			["Ephemeral Power"] = 		{time=15,  school="Genmagic",	class="general"}, 
			["Massive Destruction"] = 	{time=20,  school="Genmagic",	class="general"}, 
			["Arcane Potency"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Energized Shield"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Brilliant Light"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Will of the Forsaken"] = 	{time=5,   school="Shadow",	class="general"}, 
			["Perception"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Mar'li's Brain Boost"] = 	{time=30,  school="Genmagic",	class="general"}, 
			["War Stomp"] = 		{time=0.5, school="Genmagic",	class="general"},
			["Stoneform"] = 		{time=8,   school="Genmagic",	class="general"},
			["Shadowguard"] = 		{time=1.5, school="Genmagic",	class="general"},
			["Earthstrike"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Gift of Life"] = 		{time=20,  school="Genmagic",	class="general"}, 
			["Nature Aligned"] = 		{time=20,  school="Genmagic",	class="general"}, 

			-- general
			["Hearthstone"] =		{time=10,  school="Genmagic", class="general"},
			
			-- engineering
			["Frost Reflector"] = 		{time=5, school="Genmagic", class="general"}, 
			["Shadow Reflector"] = 		{time=5, school="Genmagic", class="general"}, 
			["Fire Reflector"] = 		{time=5, school="Genmagic", class="general"}, 
			
			-- First Aid
			["First Aid"] = 		{time=8, school="Genmagic", class="general"}, 
			["Linen Bandage"] = 		{time=3, school="Genmagic", class="general"},
			["Heavy Linen Bandage"] = 	{time=3, school="Genmagic", class="general"},
			["Wool Bandage"] = 		{time=3, school="Genmagic", class="general"},
			["Heavy Wool Bandage"] = 	{time=3, school="Genmagic", class="general"},
			["Silk Bandage"] = 		{time=3, school="Genmagic", class="general"},
			["Heavy Silk Bandage"] = 	{time=3, school="Genmagic", class="general"},
			["Mageweave Bandage"] = 	{time=3, school="Genmagic", class="general"},
			["Heavy Mageweave Bandage"] = 	{time=3, school="Genmagic", class="general"},
			["Runecloth Bandage"] = 	{time=3, school="Genmagic", class="general"},
			["Heavy Runecloth Bandage"] = 	{time=3, school="Genmagic", class="general"},
			
			-- mage
			["Blink"] =			{time=15,  school="Arcane",	class="mage"},
			["Frost Nova"] =		{time=21,  school="Frost",	class="mage"},
			["Ice Block"] =			{time=10,  cd=300, school="Frost",	class="mage"},
			["Frostbolt"] =			{time=2.5, school="Frost",	class="mage"},
			["Fireball"] =			{time=3,   school="Fire",	class="mage"},
			["Flamestrike"] =		{time=3,   school="Fire",	class="mage"},
			["Polymorph"] =			{time=1.5, school="Arcane",	class="mage"},
			["Polymorph: Pig"] =		{time=1.5, school="Arcane",	class="mage"},
			["Polymorph: Turtle"] =		{time=1.5, school="Arcane",	class="mage"},
			["Pyroblast"] =			{time=6,   school="Fire",	class="mage"},
			["Scorch"] =			{time=1.5, school="Fire",	class="mage"},
			["Evocation"] =			{time=8,   school="Arcane",	class="mage"},
			["Arcane Power"] =		{time=15,  school="Arcane",	class="mage"},
			["Conjure Water"] =		{time=3,   school="Genmagic",   class="mage"},
			["Conjure Food"] =		{time=3,   school="Genmagic",   class="mage"},
			["Conjure Mana Ruby"] =		{time=3,   school="Genmagic",   class="mage"},
			["Conjure Mana Citrine"] =      {time=3,   school="Genmagic",   class="mage"},
			["Conjure Mana Jade"] =		{time=3,   school="Genmagic",   class="mage"},
			["Conjure Mana Agate"] =	{time=3,   school="Genmagic",   class="mage"},
			["Slow Fall"] =			{time=30,  school="Genmagic",   class="mage"}, 
			["Portal: Darnassus"] =		{time=10,  school="Genmagic",   class="mage"},
			["Portal: Thunder Bluff"] =	{time=10,  school="Genmagic",   class="mage"},
			["Portal: Ironforge"] =		{time=10,  school="Genmagic",   class="mage"},
			["Portal: Orgrimmar"] =		{time=10,  school="Genmagic",   class="mage"},
			["Portal: Stormwind"] =		{time=10,  school="Genmagic",   class="mage"},
			["Portal: Undercity"] =		{time=10,  school="Genmagic",   class="mage"},
			["Teleport: Darnassus"] =	{time=10,  school="Genmagic",   class="mage"},
			["Teleport: Thunder Bluff"] =	{time=10,  school="Genmagic",   class="mage"},
			["Teleport: Ironforge"] =	{time=10,  school="Genmagic",   class="mage"},
			["Teleport: Orgrimmar"] =	{time=10,  school="Genmagic",   class="mage"},
			["Teleport: Stormwind"] =	{time=10,  school="Genmagic",   class="mage"},
			["Teleport: Undercity"] =	{time=10,  school="Genmagic",   class="mage"},
			["Fire Ward"] =			{time=30,  school="Fire",       class="mage"}, 
			["Frost Ward"] =		{time=30,  school="Frost",      class="mage"}, 

			-- paladin
			["Divine Shield"] =		{time=12,  school="Holy", class="paladin"},
			["Blessing of Protection"] =    {time=10,  school="Holy", class="paladin"},
			["Holy Light"] =		{time=2.5, school="Holy", class="paladin"},
			["Flash of Light"] =		{time=1.5, school="Holy", class="paladin"},
			["Blessing of Freedom"] =	{time=16,  school="Holy", class="paladin"},
			["Summon Charger"] =		{time=3,   school="Holy", class="paladin"},
			["Summon Warhorse"] =		{time=3,   school="Holy", class="paladin"},
			["Hammer of Wrath"] =		{time=1,   school="Holy", class="paladin"},
			["Holy Wrath"] =		{time=2,   school="Holy", class="paladin"},
			["Turn Undead"] =		{time=1.5, school="Holy", class="paladin"},
			["Redemption"] =		{time=10,  school="Holy", class="paladin"},
			["Divine Protection"] =		{time=8,   school="Holy", class="paladin"}, 
			["Blessing of Sacrifice"] =	{time=30,  school="Holy", class="paladin"}, 
			
			-- warlock
			["Shadow Bolt"] =		{time=2.5, school="Shadow",class="warlock"},
			["Immolate"] =			{time=1.5, school="Fire",  class="warlock"},
			["Soul Fire"] =			{time=4,   school="Fire",  class="warlock"},
			["Searing Pain"] =		{time=1.5, school="Fire",  class="warlock"},
			["Fear"] =			{time=1.5, school="Shadow",class="warlock"},
			["Howl of Terror"] =		{time=2,   school="Shadow",class="warlock"},
			["Summon Dreadsteed"] =		{time=3,   school="Shadow",        class="warlock"},
			["Summon Felsteed"] =		{time=3,   school="Shadow",        class="warlock"},
			["Summon Imp"] =		{time=6,   school="Shadow",        class="warlock"},
			["Summon Succubus"] =		{time=6,   school="Shadow",        class="warlock"},
			["Summon Voidwalker"] =		{time=6,   school="Shadow",        class="warlock"},
			["Summon Felhunter"] =		{time=6,   school="Shadow",        class="warlock"},
			["Banish"] =			{time=1.5, school="Shadow",        class="warlock"},
			["Ritual of Summoning"] =	{time=5,   school="Shadow",        class="warlock"},
			["Ritual of Doom"] =		{time=10,  school="Shadow",        class="warlock"},
			["Create Spellstone"] =		{time=5,   school="Genmagic",      class="warlock"},
			["Create Soulstone"] =		{time=3,   school="Genmagic",      class="warlock"},
			["Create Healthstone"] =	{time=3,   school="Genmagic",      class="warlock"},
			["Create Major Healthstone"] =	{time=3,   school="Genmagic",      class="warlock"},
			["Create Firestone"] =		{time=3,   school="Genmagic",      class="warlock"},
			["Enslave Demon"] =		{time=3,   school="Shadow",        class="warlock"},
			["Inferno"] =			{time=2,   school="Shadow",        class="warlock" },
			["Shadow Ward"] =		{time=30,  school="Shadow",        class="warlock"}, 
			["Amplify Curse"] =		{time=30,  school="Shadow",        class="warlock"}, 

			-- succubus
			["Seduction"] =		{time=1.5,school="Shadow",class="warlock"},
			["Soothing Kiss"] =	{time=4,  school="Shadow",class="warlock"},
			
			-- Voidwalker
			["Consume Shadows"] =	{time=10, school="Shadow",class="warlock"}, 
		
			-- priest
			["Power Word: Shield"] =	{time=30,  school="Holy",    class="priest"},
			["Greater Heal"] =		{time=2.5, school="Holy",    class="priest"},
			["Flash Heal"] =		{time=1.5, school="Holy",    class="priest"},
			["Heal"] =			{time=2.5, school="Holy",    class="priest"},
			["Resurrection"] =		{time=10,  school="Holy",    class="priest"},
			["Smite"] =			{time=2,   school="Holy",    class="priest"},
			["Mind Blast"] =		{time=1.5, school="Shadow",  class="priest"},
			["Mind Control"] =		{time=3,   school="Shadow",  class="priest"},
			["Mana Burn"] =			{time=3,   school="Shadow",  class="priest"},
			["Holy Fire"] =			{time=3,   school="Holy",    class="priest"},
			["Prayer of Healing"] =		{time=3,   school="Holy",    class="priest"},
			["Fade"] =			{time=10,  school="Shadow",  class="priest"},
			["Renew"] =			{time=15,  school="Holy",    class="priest"},
			["Feedback"] =			{time=15,  school="Shadow",  class="priest"},
			["Psychic Scream"] =		{time=26,  school="Shadow",  class="priest"},
			["Inspiration"] =		{time=15,  school="Holy",    class="priest"}, 
			["Power Infusion"] =		{time=15,  school="Genmagic",class="priest"},
			["Focused Casting"] =		{time=6,   school="Genmagic",class="priest"},
			["Mind Soothe"] =		{time=1.5, school="Holy",    class="priest"},
			["Shackle Undead"] =		{time=1.5, school="Nature",  class="priest"},
			["Abolish Disease"] =		{time=20,  school="Nature",  class="priest"}, 
			["Inspiration"] =		{time=15,  school="Holy",    class="priest"},

			-- warrior
			["Bloodrage"] =			{time=10,  cd=30, school="Physical", class="warrior"},
			["Bloodthirst"] =		{time=8,   school="Physical", class="warrior"},
			["Shield Wall"] =		{time=10,  school="Physical", class="warrior"},
			["Recklessness"] =		{time=15,  school="Physical", class="warrior"},
			["Retaliation"] =		{time=15,  school="Physical", class="warrior"},
			["Berserker Rage"] =		{time=10,  school="Physical", class="warrior"},
			["Last Stand"] =		{time=20,  school="Physical", class="warrior"},
			["Death Wish"] =		{time=30,  school="Physical", class="warrior"},
			["Shield Block"] =		{time=5.5, school="Physical", class="warrior"},
			["Enrage"] =			{time=12,  school="Physical", class="warrior"}, 
		
			-- rogue
			["Sprint"] =			{time=15,  school="Physical", class="rogue"},
			["Evasion"] =			{time=15,  school="Physical", class="rogue"},
			["Blade Flurry"] =		{time=15,  school="Physical", class="rogue"},
			["Adrenaline Rush"] =		{time=15,  school="Physical", class="rogue"},
			["Disarm Trap"] =		{time=2,   school="Physical", class="rogue"},
			["Pick Lock"] =			{time=5,   school="Physical", class="rogue"},

			-- hunter
			["Rapid Fire"] = 		{time=15,  school="Physical", class="hunter"},
			["Deterrence"] = 		{time=10,  school="Physical", class="hunter"},
			["Multi-Shot"] = 		{time=10,  school="Physical", class="hunter"},
			["Aimed Shot"] = 		{time=3,   school="Physical", class="hunter"},
			["Scare Beast"] = 		{time=1,   school="Physical", class="hunter"},
			["Volley"] = 			{time=6,   school="Physical", class="hunter"},
			["Dismiss Pet"] = 		{time=5,   school="Nature",   class="hunter"},
			["Revive Pet"] = 		{time=10,  school="Physical", class="hunter"},
			["Eyes of the Beast"] = 	{time=2,   school="Physical", class="hunter"},

			-- druid
			["Healing Touch"] = 		{time=3,   school="Nature",  class="druid"},
			["Regrowth"] = 			{time=2,   school="Nature",  class="druid"},
			["Dash"] = 			{time=15,  school="Physical",class="druid"},
			["Rebirth"] = 			{time=2,   school="Nature",  class="druid"},
			["StarFire"] = 			{time=3.5, school="Nature",  class="druid"},
			["Wrath"] = 			{time=2,   school="Nature",  class="druid"},
			["Entangling Roots"] = 		{time=1.5, school="Nature",  class="druid"},
			["Barkskin"] = 			{time=15,  school="Nature",  class="druid"},
			["Innervate"] = 		{time=20,  school="Nature",  class="druid"},
			["Tiger's Fury"] = 		{time=6,   school="Physical",class="druid"},
			["Frenzied Regeneration"] = 	{time=10,  school="Nature",  class="druid"},
			["Rejuvenation"] = 		{time=12,  school="Nature",  class="druid"},
			["Abolish Poison"] = 		{time=8,   school="Nature",  class="druid"},
			["Hibernate"] = 		{time=1.5, school="Nature",  class="druid"},
			["Soothe Animal"] = 		{time=1.5, school="Physical",class="druid"},
			["Teleport: Moonglade"] = 	{time=10,  school="Arcane",  class="druid"},
			["Frenzied Regeneration"] = 	{time=10,  school="Genmagic",class="druid"}, 
			["Rejuvenation"] = 		{time=12,  school="Nature",  class="druid"}, 
			["Tranquility"] = 		{time=10,  school="Nature",  class="druid"},
		
			-- shaman
			["Lesser Healing Wave"] =	{time=1.5, school="Nature",  class="shaman"},
			["Healing Wave"] =		{time=2.5, school="Nature",  class="shaman"},
			["Chain Lightning"] =		{time=2.5, school="Nature",  class="shaman"},
			["Ghost Wolf"] =		{time=3,   school="Nature",  class="shaman"},
			["Chain Heal"] =		{time=2.5, school="Nature",  class="shaman"},
			["Lightning Bolt"] =		{time=3,   school="Nature",  class="shaman"},
			["Stormstrike"] =		{time=12,  school="Nature",  class="shaman"},
			["Ancestral Spirit"] =		{time=10,  school="Nature",  class="shaman"},
			["Astral Recall"] =		{time=10,  school="Nature",  class="shaman"},
			["Chain Heal"] =		{time=2.5, school="Nature",  class="shaman"},
			["Lightning Bolt"] =		{time=3,   school="Nature",  class="shaman"},
			["Far Sight"] =			{time=2,   school="Nature",  class="shaman"},
			["Stoneclaw Totem"] =		{time=15,  school="Nature",  class="shaman"},
			["Mana Tide Totem"] =		{time=15,  school="Nature",  class="shaman"},
			["Fire Nova Totem"] =		{time=5,   school="Nature",  class="shaman"},
	}

HostelBar.DurationsDB = {
		-- general
		["War Stomp"] =			{time=2,   school="Physical", class="general"},
	
		-- priest
		["Renew"] =			{time=15,  school="Holy",  class="priest"},
		["Shadow Word: Pain"] =		{time=18,  school="Shadow",class="priest"},
		["Blackout"] =			{time=3,   school="Shadow",class="priest"},
		["Devouring Plague"] =		{time=24,  school="Shadow",class="priest"},
		["Silence"] =			{time=5,   school="Shadow",class="priest"},
		["Holy Fire"] =			{time=10,  school="Holy",  class="priest"},
		["Psychic Scream"] =		{time=8,   school="Shadow",class="priest"},
		["Shackle Undead"] =		{time=50,  school="Holy",  class="priest"},
		["Inspiration"] =		{time=15,  school="Holy",  class="priest"},

		-- warrior
		["Hamstring"] =			{time=15,  school="Physical", class="warrior"},
		["Improved Hamstring"] =	{time=4,   school="Physical", class="warrior"},
		["Rend"] =			{time=15,  school="Physical", class="warrior"},
		["Disarm"] =			{time=10,  school="Physical", class="warrior"},
		["Taunt"] =			{time=3,   school="Physical", class="warrior"},
		["Mocking Blow"] =		{time=6,   school="Physical", class="warrior"},
		["Challenging Shout"] =		{time=6,   school="Physical", class="warrior"},
		["Piercing Howl"] =		{time=6,   school="Physical", class="warrior"},
		["Shield Bash - Silenced"] =	{time=4,   school="Physical", class="warrior"},
		["Concussion Blow"] =		{time=5,   school="Physical", class="warrior"},
		["Charge Stun"] =		{time=1,   school="Physical", class="warrior"},
		["Intercept Stun"] =		{time=3,   school="Physical", class="warrior"},
		["Revenge Stun"] =		{time=3,   school="Physical", class="warrior"},
		["Mace Specialization"] =	{time=3,   school="Physical", class="warrior"},
		["Intimidating Shout"] =	{time=8,   school="Physical", class="warrior"},
		["Mortal Strike"] =		{time=10,  school="Physical", class="warrior"},
		["Sunder Armor"] =		{time=30,  school="Physical", class="warrior"},
		["Demoralizing Shout"] =	{time=30,  school="Physical", class="warrior"},
		
		-- mage
		["Blast Wave"] =		{time=6,  school="Fire",  class="mage"},
		["Frost Nova"] =		{time=8,  school="Frost", class="mage"},
		["Frostbite"] =			{time=5,  school="Frost", class="mage"},
		["Chilled"] =			{time=5,  school="Frost", class="mage"},
		["Cone of Cold"] =		{time=8,  school="Frost", class="mage"},
		["Counterspell - Silenced"] =	{time=4,  school="Arcane",class="mage", icon="Interface\\Icons\\Spell_Frost_IceShock"},
		["Impact"] =			{time=2,  school="Fire",  class="mage"},
		["Ignite"] =			{time=4,  school="Fire",  class="mage"},
		["Fire Vulnerability"] =	{time=30, school="Fire",  class="mage"},
		["Polymorph"] =			{time=50, school="Arcane",class="mage",	drtable="Polymorph"},
		["Polymorph: Pig"] =		{time=50, school="Arcane",class="mage",	drtable="Polymorph"},
		["Polymorph: Turtle"] =		{time=50, school="Arcane",class="mage",	drtable="Polymorph"},
		
		-- rogue
		["Sap"] =			{time=45,  school="Physical", class="rogue"},
		["Cheap Shot"] =		{time=4,   school="Physical", class="rogue"},
		["Kidney Shot"] =		{time=1,   school="Physical", class="rogue",	drtable="Stun", cp=1},
		["Gouge"] =			{time=5.5, school="Physical", class="rogue",	drtable="Gouge"},
		["Garrote"] =			{time=18,  school="Physical", class="rogue"},
		["Blind"] =			{time=10,  school="Physical", class="rogue"},
		["Kick - Silenced"] =		{time=2,   school="Physical", class="rogue", icon="Interface\\Icons\\Ability_Kick"},
		["Riposte"] =			{time=6,   school="Physical", class="rogue"},
		["Rupture"] =			{time=6,   school="Physical", class="rogue", cp=2},
		["Expose Armor"] =		{time=30,  school="Physical", class="rogue"},
		["Mace Specialization"] =	{time=3,   school="Physical", class="rogue"},
		["Crippling Poison"] =		{time=12,  school="Nature",   class="rogue"},
		["Deadly Poison"] =		{time=12,  school="Nature",   class="rogue"},
		["Wound Poison"] =		{time=12,  school="Nature",   class="rogue"},
	
		-- warlock
		["Corruption"] =		{time=18,  school="Shadow",  class="warlock"},
		["Immolate"] =			{time=15,  school="Fire",    class="warlock"},
		["Curse of Agony"] =		{time=24,  school="Fire",    class="warlock", curse=true},
		["Curse of Tongues"] =		{time=30,  school="Shadow",  class="warlock", curse=true},
		["Curse of Exhaustion"] =	{time=12,  school="Shadow",  class="warlock", curse=true},
		["Curse of Weakness"] =		{time=120, school="Shadow",  class="warlock", curse=true},
		["Curse of Doom"] =		{time=60,  school="Shadow",  class="warlock", curse=true},
		["Curse of the Elements"] =	{time=300, school="Shadow",  class="warlock", curse=true},
		["Curse of Shadow"] =		{time=300, school="Shadow",  class="warlock", curse=true},
		["Curse of Recklessness"] =	{time=120, school="Shadow",  class="warlock", curse=true},
		["Siphon Life"] =		{time=30,  school="Shadow",  class="warlock"},
		["Death Coil"] =		{time=3,   school="Shadow",  class="warlock"},
		["Howl of Terror"] =		{time=15,  school="Shadow",  class="warlock",   drtable="Fear/Seduce"},
		["Fear"] =			{time=15,  school="Shadow",  class="warlock",	drtable="Fear/Seduce"},
		["Seduction"] =			{time=30,  school="Shadow",  class="warlock",	drtable="Fear/Seduce"},
		["Banish"] =			{time=30,  school="Shadow",  class="warlock"},
		
		-- shaman
		["Frost Shock"] =		{time=8,   school="Frost",class="shaman",	drtable="Frost Shock"},
		["Flame Shock"] =               {time=12,  school="Fire", class="shaman"},
	
		-- druid
		["Feral Charge Effect"] =	{time=4,   school="Physical", class="druid"},
		["Bash"] =			{time=4,   school="Physical", class="druid"},
		["Pounce"] =			{time=18,  school="Physical", class="druid"},
		["Rake"] =			{time=9,   school="Physical", class="druid"},
		["Rip"] =			{time=12,  school="Physical", class="druid"},
		["Insect Swarm"] =		{time=12,  school="Nature",   class="druid"},
		["Soothe Animal"] =		{time=15,  school="Nature",   class="druid"},
		["Improved StarFire"] =		{time=3,   school="Nature",   class="druid"},
		["Faerie Fire"] =		{time=40,  school="Nature",   class="druid"},
		["Faerie Fire (Feral)"] =	{time=40,  school="Nature",   class="druid", icon="Spell_Nature_FaerieFire"},
		
		-- hunter
		["Concussive Shot"] =		{time=4,   school="Physical",class="hunter"},
		["Improved Concussive Shot"] =  {time=3,   school="Physical",class="hunter"},
		["Serpent Sting"] =		{time=15,  school="Nature",  class="hunter"},
		["Viper Sting"] =		{time=8,   school="Nature",  class="hunter"},
		["Wyvern Sting"] =		{time=12,  school="Nature",  class="hunter"},
		["Scorpid Sting"] =		{time=20,  school="Nature",  class="hunter"},
		["Entrapment"] =		{time=5,   school="Nature",  class="hunter"},
		["Wing Clip"] =			{time=10,  school="Physical",class="hunter"},
		["Improved Wing Clip"] =	{time=5,   school="Physical",class="hunter"},
		["Expose Weakness"] =		{time=7,   school="Arcane",  class="hunter"},
		["Scatter Shot"] =		{time=4,   school="Physical",class="hunter"},
		["Intimidation"] =		{time=3,   school="Physical",class="hunter"},
		["Counterattack"] =		{time=5,   school="Physical",class="hunter"},
		["Bestial Wrath"] =		{time=18,  school="Physical",class="hunter"},
		["Explosive Trap"] =		{time=60,  school="Physical",class="hunter"},
		["Immolation Trap"] =		{time=60,  school="Physical",class="hunter"},
		["Freezing Trap"] =	        {time=60,  school="Physical",class="hunter"},
		["Frost Trap"] =		{time=60,  school="Physical",class="hunter"},
		["Flare"] =			{time=30,  school="Physical",class="hunter"},
		["Hunter's Mark"] =		{time=120, school="Physical",class="hunter"},
		["Rapid Fire"] =		{time=10,  school="Physical",class="hunter"},
		["Scare Beast"] =		{time=10,  school="Physical",class="hunter"},

		-- paladin
		["Hammer of Justice"] =		{time=6,   school="Holy", class="paladin"},
		["Repentance"] =		{time=6,   school="Holy", class="paladin"},
		["Vengeance"] =			{time=8,   school="Holy", class="paladin"},
		["Turn Undead"] =		{time=20,  school="Holy", class="paladin"},
}
HostelBar.MobSpellsDB = {
      ["Shrink"] =			{time=3, icon="Spell_Ice_MagicDamage",          class="general", school="shadow"},
      ["Banshee Curse"] =	        {time=2, icon="Spell_Nature_Drowsy",            class="general", school="shadow"},
      ["Shadow Bolt Volley"] =		{time=3, icon="Spell_Shadow_ShadowBolt",        class="general", school="shadow"},
      ["Shadow Bolt"] =			{time=2.5, 			                class="warlock", school="Shadow"},
      ["Cripple"] =			{time=3, icon="Spell_Shadow_Cripple",           class="general", school="shadow"},
      ["Dark Mending"] =		{time=3.5, icon="Spell_Shadow_ChillTouch",      class="general", school="shadow"}, 
      ["Spirit Decay"] =		{time=2, icon="Spell_Holy_HarmUndeadAura",      class="general", school="shadow"},
      ["Gust of Wind"] =		{time=2, icon="Spell_Nature_EarthBind",         class="general", school="nature"},
      ["Black Sludge"] =		{time=3, icon="Spell_Shadow_CallofBone",        class="general", school="shadow"},
      ["Toxic Bolt"] =			{time=2, icon="Spell_Nature_CorrosiveBreath",   class="general", school="nature"},
      ["Poisonous Spit"] =		{time=2, icon="Spell_Nature_CorrosiveBreath",   class="general", school="nature"},
      ["Wild Regeneration"] =		{time=3, icon="Spell_Nature_Rejuvenation",      class="general", school="nature"},
      ["Curse of the Deadwood"] =	{time=2, icon="Spell_Shadow_GatherShadows",     class="general", school="shadow"},
      ["Curse of Blood"] =		{time=2, icon="Spell_Shadow_RitualOfSacrifice", class="general", school="shadow"},
      ["Dark Sludge"] =			{time=5, icon="Spell_Shadow_CreepingPlague",    class="general", school="shadow"},
      ["Plague Cloud"] =		{time=2, icon="Spell_Shadow_CallofBone",        class="general", school="shadow"},
      ["Wandering Plague"] =		{time=2, icon="Spell_Shadow_CallofBone",        class="general", school="shadow"},
      ["Wither Touch"] =		{time=2, icon="Spell_Nature_Drowsy",            class="general", school="shadow"},
      ["Fevered Fatigue"] =		{time=3, icon="Spell_Nature_NullifyDisease",    class="general", school="shadow"},
      ["Encasing Webs"] =		{time=2, icon="Spell_Nature_EarthBind",         class="general", school="shadow"},
      ["Crystal Gaze"] =		{time=2, icon="Ability_GolemThunderClap",       class="general", school="shadow"},
}
HostelBar.InterruptTimes = {
	["Kick"] =		{time=5},
	["Counterspell"] =	{time=10},
	["Shield Bash"] =	{time=6},
	["Spelllock"] =		{time=8},
	["Pummel"] =		{time=4},
	["Earth Shock"] =	{time=2},
}
