-- HealRotation is desigend to help healers hold tanks alife ;-)

RAIDHEALER_VERSION			= GetAddOnMetadata("RaidHealer", "Version");
RAIDHEALER_MAX_HEALER		= 40;
RAIDHEALER_MAX_BUFFER		= 12;
RAIDHEALER_MAX_TANKS		= 10;
RAIDHEALER_MAX_GROUPS		= 8;
RAIDHEALER_MAX_NAME_LEN		= 8;

RAIDHEALER_DEFAULT_MINIMAP_POS = 16;

RAIDHEALER_CLASS_WARRIOR	= "WARRIOR";
RAIDHEALER_CLASS_PRIEST		= "PRIEST";
RAIDHEALER_CLASS_PALADIN	= "PALADIN";
RAIDHEALER_CLASS_DRUID		= "DRUID";
RAIDHEALER_CLASS_SHAMAN		= "SHAMAN";
RAIDHEALER_CLASS_WARLOCK	= "WARLOCK";
RAIDHEALER_CLASS_MAGE		= "MAGE";
RAIDHEALER_CLASS_ROGUE		= "ROGUE";
RAIDHEALER_CLASS_HUNTER		= "HUNTER";

RAIDHEALER_TEXTURE_PATH		= "Interface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes";

-- left,right,top,bottom
RAID_HEALER_TEXTURE_COORDS = {
	[RAIDHEALER_CLASS_WARRIOR] = {0, 0.25, 0, 0.25},
	[RAIDHEALER_CLASS_MAGE] = {0.25, 0.5, 0, 0.25},
	[RAIDHEALER_CLASS_ROGUE] = {0.5, 0.75, 0, 0.25},
	[RAIDHEALER_CLASS_DRUID] = {0.75, 1, 0, 0.25},
	[RAIDHEALER_CLASS_HUNTER] = {0, 0.25, 0.25, 0.5},
	[RAIDHEALER_CLASS_SHAMAN] = {0.25, 0.5, 0.25, 0.5},
	[RAIDHEALER_CLASS_PRIEST] = {0.5, 0.75, 0.25, 0.5},
	[RAIDHEALER_CLASS_WARLOCK] = {0.75, 1, 0.25, 0.5},
	[RAIDHEALER_CLASS_PALADIN] = {0, 0.25, 0.5, 0.75}
};

RAIDHEALER_HEALCLASSES	= { 
	RAIDHEALER_CLASS_PRIEST, 
	RAIDHEALER_CLASS_DRUID, 
	RAIDHEALER_CLASS_PALADIN, 
	RAIDHEALER_CLASS_SHAMAN
};

RAIDHEALER_TANKCLASSES		= {
	RAIDHEALER_CLASS_WARRIOR,
	RAIDHEALER_CLASS_MAGE,
	RAIDHEALER_CLASS_DRUID,
	RAIDHEALER_CLASS_ROGUE,
	RAIDHEALER_CLASS_HUNTER,
	RAIDHEALER_CLASS_WARLOCK
};

RAIDHEALER_BUFFCLASSES		= {
	RAIDHEALER_CLASS_PRIEST,
	RAIDHEALER_CLASS_PALADIN,
	RAIDHEALER_CLASS_DRUID,
	RAIDHEALER_CLASS_MAGE
};

RAIDHEALER_BUFFS = {
	{ ["BUFF"] = "STAMINA" , ["CLASS"] = RAIDHEALER_CLASS_PRIEST },
	{ ["BUFF"] = "SPIRIT" , ["CLASS"] = RAIDHEALER_CLASS_PRIEST },
	{ ["BUFF"] = "SHADOW" , ["CLASS"] = RAIDHEALER_CLASS_PRIEST },
	{ ["BUFF"] = "MOTW" , ["CLASS"] = RAIDHEALER_CLASS_DRUID },
	{ ["BUFF"] = "THORNS" , ["CLASS"] = RAIDHEALER_CLASS_DRUID },
	{ ["BUFF"] = "INTELLECT" , ["CLASS"] = RAIDHEALER_CLASS_MAGE }
}
