-- Version : English - sarf
-- Translation by : None

ONEHITWONDER_RESURRECTION_SICKNESS_EFFECT			= "Resurrection Sickness";

ONEHITWONDER_SPELL_LESSER_INVISIBILITY_NAME			= "Lesser Invisibility";
ONEHITWONDER_SPELL_LESSER_INVISIBILITY_EFFECT		= "Lesser Invisibility";
ONEHITWONDER_SPELL_INVISIBILITY_NAME				= "Invisibility";
ONEHITWONDER_SPELL_INVISIBILITY_EFFECT				= "Invisibility";
ONEHITWONDER_SPELL_GREATER_INVISIBILITY_NAME		= "Greater Invisibility";
ONEHITWONDER_SPELL_GREATER_INVISIBILITY_EFFECT		= "Greater Invisibility";


-- debuff names

ONEHITWONDER_EFFECT_SPELL_BOMB_NAME					= "Spell Bomb";
ONEHITWONDER_DEBUFF_DARK_PLAGUE_NAME		 		= "Dark Plague";

-- Buffnames

ONEHITWONDER_BUFF_GHOST								= "Ghost";
ONEHITWONDER_ABILITY_SHADOWMELD_NAME				= "Shadowmeld";
ONEHITWONDER_ABILITY_SHADOWMELD_EFFECT				= "Shadowmeld";

-- Mount stuff

ONEHITWONDER_BUFF_PALADIN_TEXTURE_MOUNT				= "Interface\\Icons\\Spell_Nature_Swiftness";
ONEHITWONDER_BUFF_TEXTURE_MOUNT						= "Interface\\Icons\\Ability_Mount_";



OneHitWonder_MountColorNames = {
};

OneHitWonder_MountTypeNames = {
};

OneHitWonder_SpecialMountNames = {
	"Summon Dreadsteed",
	"Summon Warhorse",
	"Summon Charger",
	"Summon Felsteed",
	"Black Ram",
	"Brown Ram",
	"Frost Ram",
	"Gray Ram",
	"Swift Brown Ram",
	"Swift Gray Ram",
	"Swift White Ram",
	"White Ram",
	"Blue Mechanostrider",
	"Green Mechanostrider",
	"Icy Blue Mechanostrider Mod A",
	"Red Mechanostrider",
	"Swift Green Mechanostrider",
	"Swift White Mechanostrider",
	"Swift Yellow Mechanostrider",
	"Unpainted Mechanostrider",
	"White Mechanostrider Mod A",
	"Black Stallion",
	"Brown Horse",
	"Chestnut Mare",
	"Palomino",
	"Pinto",
	"White Stallion",
	"Frostsaber",
	"Nightsaber",
	"Spotted Frostsaber",
	"Striped Frostsaber",
	"Striped Nightsaber",
	"Swift Frostsaber",
	"Swift Mistsaber",
	"Swift Stormsaber",
	"Winterspring Frostsaber",
	"Bengal Tiger",
	"Leopard",
	"Night Saber",
	"Spotted Panther",
	"Deathcharger's Reins",
	"Blue Skeletal Horse",
	"Brown Skeletal Horse",
	"Green Skeletal Warhorse",
	"Red Skeletal Horse",
	"Brown Kodo",
	"Gray Kodo",
	"Great Brown Kodo",
	"Great Gray Kodo",
	"Great White Kodo",
	"Green Kodo",
	"Teal Kodo",
	"Swift Blue Raptor",
	"Swift Green Raptor",
	"Swift Orange Raptor",
	"Emerald Raptor",
	"Ivory Raptor",
	"Mottled Red Raptor",
	"Turquoise Raptor",
	"Violet Raptor",
	"Arctic Wolf",
	"Brown Wolf",
	"Dire Wolf",
	"Red Wolf",
	"Swift Brown Wolf",
	"Swift Gray Wolf",
	"Swift Timber Wolf",
	"Timber Wolf",
	"Winter Wolf",
	"Black Wolf",
	"Gray Wolf",
	"Summon Felsteed",
	"Summon Warhorse",
	"Nightsaber",
	"Crimson Raptor",
	"Spotted Frost Saber",
};



OneHitWonder_MountEffectTextures = {
	ONEHITWONDER_BUFF_PALADIN_TEXTURE_MOUNT,
	"Interface\\Icons\\Ability_Mount_BlackDireWolf",
	"Interface\\Icons\\Ability_Mount_BlackPanther",
	"Interface\\Icons\\Ability_Mount_JungleTiger",
	"Interface\\Icons\\Ability_Mount_MechaStrider",
	"Interface\\Icons\\Ability_Mount_MountainRam",
	"Interface\\Icons\\Ability_Mount_NightmareHorse",
	"Interface\\Icons\\Ability_Mount_PinkTiger",
	"Interface\\Icons\\Ability_Mount_Raptor",
	"Interface\\Icons\\Ability_Mount_RidingHorse",
	"Interface\\Icons\\Ability_Mount_UndeadHorse",
	"Interface\\Icons\\Ability_Mount_WhiteDireWolf",
	"Interface\\Icons\\Ability_Mount_WhiteTiger",
};

-- Tracking Spells

ONEHITWONDER_ABILITY_FIND_NO_STUFF_NAME				= "No tracking";
ONEHITWONDER_SPELL_NO_ASPECT_NAME					= "No aspect";

ONEHITWONDER_ABILITY_FIND_HERBS_NAME				= "Find Herbs";
ONEHITWONDER_ABILITY_FIND_MINERALS_NAME				= "Find Minerals";
ONEHITWONDER_ABILITY_FIND_TREASURE_NAME				= "Find Treasure";
ONEHITWONDER_ABILITY_SENSE_DEMONS_NAME				= "Sense Demons";
ONEHITWONDER_ABILITY_SENSE_UNDEAD_NAME				= "Sense Undead";
ONEHITWONDER_ABILITY_TRACK_BEASTS_NAME				= "Track Beasts";
ONEHITWONDER_ABILITY_TRACK_HUMANOIDS_NAME			= "Track Humanoids";
ONEHITWONDER_ABILITY_TRACK_UNDEAD_NAME				= "Track Undead";
ONEHITWONDER_ABILITY_TRACK_HIDDEN_NAME				= "Track Hidden";
ONEHITWONDER_ABILITY_TRACK_ELEMENTALS_NAME			= "Track Elementals";
ONEHITWONDER_ABILITY_TRACK_HUMANOID_NAME			= "Track Humanoid";
ONEHITWONDER_ABILITY_TRACK_DEMONS_NAME				= "Track Demons";
ONEHITWONDER_ABILITY_TRACK_GIANTS_NAME				= "Track Giants";
ONEHITWONDER_ABILITY_TRACK_DRAGONKIN_NAME			= "Track Dragonkin";


-- Druid Spells

ONEHITWONDER_SPELL_SHAPESHIFT_AQUATIC_FORM_EFFECT	= "Aquatic Form (Shapeshift)";
ONEHITWONDER_SPELL_SHAPESHIFT_BEAR_FORM_EFFECT		= "Bear Form (Shapeshift)";
ONEHITWONDER_SPELL_SHAPESHIFT_CAT_FORM_EFFECT		= "Cat Form (Shapeshift)";
ONEHITWONDER_SPELL_SHAPESHIFT_DIRE_BEAR_FORM_EFFECT	= "Dire Bear Form (Shapeshift)";
ONEHITWONDER_SPELL_SHAPESHIFT_MOONKIN_FORM_EFFECT	= "Moonkin Form (Shapeshift)";
ONEHITWONDER_SPELL_SHAPESHIFT_TRAVEL_FORM_EFFECT	= "Travel Form (Shapeshift)";

ONEHITWONDER_SPELL_OMEN_OF_CLARITY_NAME 			= "Omen of Clarity";
ONEHITWONDER_SPELL_OMEN_OF_CLARITY_EFFECT 			= "Omen of Clarity";

ONEHITWONDER_SPELL_MARK_OF_THE_WILD_NAME 			= "Mark of the Wild";
ONEHITWONDER_SPELL_MARK_OF_THE_WILD_EFFECT 			= "Mark of the Wild";
ONEHITWONDER_SPELL_GIFT_OF_THE_WILD_NAME 			= "Gift of the Wild";
ONEHITWONDER_SPELL_GIFT_OF_THE_WILD_EFFECT 			= "Gift of the Wild";
ONEHITWONDER_SPELL_THORNS_NAME 						= "Thorns";
ONEHITWONDER_SPELL_REJUVENATION_NAME 				= "Rejuvenation";

ONEHITWONDER_SPELL_NATURES_GRASP_NAME 				= "Nature's Grasp";
ONEHITWONDER_SPELL_REGROWTH_NAME 					= "Regrowth";

ONEHITWONDER_SPELL_ABOLISH_POISON_NAME 				= "Abolish Poison";
ONEHITWONDER_SPELL_ABOLISH_POISON_EFFECT 			= "Abolish Poison";

ONEHITWONDER_SPELL_REMOVE_CURSE_NAME 				= "Remove Curse";

ONEHITWONDER_SPELL_FAERIE_FIRE_NAME					= "Faerie Fire";
ONEHITWONDER_SPELL_FAERIE_FIRE_BEAR_NAME			= "Faerie Fire (Bear)";
ONEHITWONDER_SPELL_FAERIE_FIRE_CAT_NAME				= "Faerie Fire (Cat)";

ONEHITWONDER_DRUID_SHAPESHIFT_FORM_BEAR				= "Bear Form";
ONEHITWONDER_DRUID_SHAPESHIFT_FORM_DIRE_BEAR		= "Dire Bear Form";
ONEHITWONDER_DRUID_SHAPESHIFT_FORM_CAT				= "Cat Form";
ONEHITWONDER_DRUID_SHAPESHIFT_FORM_MOONKIN			= "Moonkin Form";


-- Hunter Spells

ONEHITWONDER_SPELL_ASPECT_SUBSTRING					= "aspect";

ONEHITWONDER_SPELL_TRUESHOT_AURA_NAME				= "Trueshot Aura";
ONEHITWONDER_SPELL_SCARE_BEAST_NAME					= "Scare Beast";

ONEHITWONDER_ABILITY_AUTOSHOT_NAME 					= "Auto Shot";

ONEHITWONDER_SPELL_MULTI_SHOT_NAME 					= "Multi-Shot";

ONEHITWONDER_ABILITY_COUNTERATTACK_NAME 			= "Counterattack";
ONEHITWONDER_ABILITY_MONGOOSE_BITE_NAME		 		= "Mongoose Bite";

ONEHITWONDER_SPELL_AIMED_SHOT_NAME 					= "Aimed Shot";
ONEHITWONDER_SPELL_ARCANE_SHOT_NAME 				= "Arcane Shot";
ONEHITWONDER_SPELL_CONCUSSIVE_SHOT_NAME				= "Concussive Shot";
ONEHITWONDER_SPELL_CONCUSSIVE_SHOT_EFFECT			= "Concussive Shot";
ONEHITWONDER_SPELL_IMPROVED_CONCUSSIVE_SHOT_EFFECT	= "Improved Concussive Shot";

ONEHITWONDER_SPELL_WING_CLIP_NAME					= "Wing Clip";
ONEHITWONDER_SPELL_WING_CLIP_EFFECT					= "Wing Clip";

ONEHITWONDER_SPELL_RAPTOR_STRIKE_NAME 				= "Raptor Strike";

ONEHITWONDER_SPELL_SERPENT_STING_NAME 				= "Serpent Sting";
ONEHITWONDER_SPELL_SERPENT_STING_EFFECT				= "Serpent Sting";

ONEHITWONDER_SPELL_VIPER_STING_NAME 				= "Viper Sting";
ONEHITWONDER_SPELL_VIPER_STING_EFFECT				= "Viper Sting";

ONEHITWONDER_SPELL_SCORPID_STING_NAME 				= "Scorpid Sting";
ONEHITWONDER_SPELL_SCORPID_STING_EFFECT				= "Scorpid Sting";

ONEHITWONDER_SPELL_HUNTERS_MARK_NAME 				= "Hunter's Mark";
ONEHITWONDER_SPELL_HUNTERS_MARK_EFFECT 				= "Hunter's Mark";

ONEHITWONDER_SPELL_ASPECT_OF_THE_HAWK_NAME 			= "Aspect of the Hawk";
ONEHITWONDER_SPELL_ASPECT_OF_THE_MONKEY_NAME 		= "Aspect of the Monkey";
ONEHITWONDER_SPELL_ASPECT_OF_THE_CHEETAH_NAME 		= "Aspect of the Cheetah";
ONEHITWONDER_SPELL_ASPECT_OF_THE_BEAST_NAME 		= "Aspect of the Beast";
ONEHITWONDER_SPELL_ASPECT_OF_THE_PACK_NAME 			= "Aspect of the Pack";
ONEHITWONDER_SPELL_ASPECT_OF_THE_WILD_NAME 			= "Aspect of the Wild";

OneHitWonder_HunterAspects = {
	ONEHITWONDER_SPELL_ASPECT_OF_THE_HAWK_NAME,
	ONEHITWONDER_SPELL_ASPECT_OF_THE_MONKEY_NAME,
	ONEHITWONDER_SPELL_ASPECT_OF_THE_CHEETAH_NAME,
	ONEHITWONDER_SPELL_ASPECT_OF_THE_BEAST_NAME,
	ONEHITWONDER_SPELL_ASPECT_OF_THE_PACK_NAME,
	ONEHITWONDER_SPELL_ASPECT_OF_THE_WILD_NAME
};

-- Mage Spells

ONEHITWONDER_SPELL_COUNTERSPELL_NAME	= "Counterspell";

ONEHITWONDER_SPELL_MAGE_ARMOR_NAME		= "Mage Armor";
ONEHITWONDER_SPELL_MAGE_ARMOR_EFFECT	= "Mage Armor";

ONEHITWONDER_SPELL_IMPACT_EFFECT		= "Impact";
ONEHITWONDER_SPELL_REMOVE_LESSER_CURSE_NAME = "Remove Lesser Curse";

ONEHITWONDER_SPELL_MANA_SHIELD_NAME = "Mana Shield";
ONEHITWONDER_SPELL_MANA_SHIELD_EFFECT = "Mana Shield";
ONEHITWONDER_SPELL_FROST_WARD_NAME = "Frost Ward";
ONEHITWONDER_SPELL_FIRE_WARD_NAME = "Fire Ward";

ONEHITWONDER_SPELL_ICE_BARRIER_NAME = "Ice Barrier";
ONEHITWONDER_SPELL_DAMPEN_MAGIC_NAME = "Dampen Magic";
ONEHITWONDER_SPELL_DAMPEN_MAGIC_EFFECT = "Dampen Magic";
ONEHITWONDER_SPELL_AMPLIFY_MAGIC_NAME = "Amplify Magic";
ONEHITWONDER_SPELL_AMPLIFY_MAGIC_EFFECT = "Amplify Magic";

ONEHITWONDER_SPELL_ARCANE_INTELLECT_NAME = "Arcane Intellect";
ONEHITWONDER_SPELL_ARCANE_INTELLECT_EFFECT = "Arcane Intellect";
ONEHITWONDER_SPELL_ARCANE_BRILLIANCE_NAME = "Arcane Brilliance";
ONEHITWONDER_SPELL_ARCANE_BRILLIANCE_EFFECT = "Arcane Brilliance";
ONEHITWONDER_SPELL_FROST_ARMOR_NAME = "Frost Armor";
ONEHITWONDER_SPELL_FROST_ARMOR_EFFECT = "Frost Armor";
ONEHITWONDER_SPELL_ICE_ARMOR_NAME = "Ice Armor";
ONEHITWONDER_SPELL_ICE_ARMOR_EFFECT = "Ice Armor";

ONEHITWONDER_LESSER_CURSE_NAMES = {
	"Haunted",
	"Arugal's Gift"
};

-- Paladin Spells

ONEHITWONDER_SPELL_DIVINE_INTERVENTION_NAME = "Divine Intervention";
ONEHITWONDER_SPELL_HOLY_SHIELD_NAME = "Holy Shield";
ONEHITWONDER_SPELL_CLEANSE_NAME = "Cleanse";
ONEHITWONDER_SPELL_PURIFY_NAME = "Purify";
ONEHITWONDER_SPELL_EXORCISM_NAME = "Exorcism";
ONEHITWONDER_SPELL_LAY_ON_HANDS_NAME = "Lay on Hands";
ONEHITWONDER_SPELL_CONSECRATION_NAME = "Consecration";

ONEHITWONDER_SPELL_SHADOW_RESISTANCE_AURA_NAME = "Shadow Resistance Aura";

ONEHITWONDER_SPELL_AURA_SUBSTRING = "Aura";
ONEHITWONDER_SPELL_BLESSING_SUBSTRING = "Blessing";
ONEHITWONDER_SPELL_GREATER_BLESSING_SUBSTRING = "Greater Blessing";

ONEHITWONDER_SPELL_DEVOTION_AURA_NAME = "Devotion Aura";
ONEHITWONDER_SPELL_DEVOTION_AURA_EFFECT = "Devotion Aura";
ONEHITWONDER_SPELL_CONCENTRATION_AURA_NAME = "Concentration Aura";
ONEHITWONDER_SPELL_CONCENTRATION_AURA_EFFECT = "Concentration Aura";
ONEHITWONDER_SPELL_RETRIBUTION_AURA_NAME = "Retribution Aura";
ONEHITWONDER_SPELL_RETRIBUTION_AURA_EFFECT = "Retribution Aura";
ONEHITWONDER_SPELL_SANCTITY_AURA_NAME = "Sanctity Aura";
ONEHITWONDER_SPELL_SANCTITY_AURA_EFFECT = "Sanctity Aura";
ONEHITWONDER_SPELL_FROST_RESISTANCE_AURA_NAME = "Frost Resistance Aura";
ONEHITWONDER_SPELL_FROST_RESISTANCE_AURA_EFFECT = "Frost Resistance Aura";
ONEHITWONDER_SPELL_FIRE_RESISTANCE_AURA_NAME = "Fire Resistance Aura";
ONEHITWONDER_SPELL_FIRE_RESISTANCE_AURA_EFFECT = "Fire Resistance Aura";
ONEHITWONDER_SPELL_SHADOW_RESISTANCE_AURA_NAME = "Shadow Resistance Aura";
ONEHITWONDER_SPELL_SHADOW_RESISTANCE_AURA_EFFECT = "Shadow Resistance Aura";

ONEHITWONDER_SPELL_HAMMER_OF_JUSTICE_NAME = "Hammer of Justice";
ONEHITWONDER_SPELL_HAMMER_OF_JUSTICE_EFFECT = "Hammer of Justice";
ONEHITWONDER_SPELL_HAMMER_OF_WRATH_NAME = "Hammer of Wrath";

ONEHITWONDER_SPELL_BLESSING_OF_KINGS_NAME = "Blessing of Kings";
ONEHITWONDER_SPELL_BLESSING_OF_LIGHT_NAME = "Blessing of Light";
ONEHITWONDER_SPELL_BLESSING_OF_MIGHT_NAME = "Blessing of Might";
ONEHITWONDER_SPELL_BLESSING_OF_FREEDOM_NAME = "Blessing of Freedom";
ONEHITWONDER_SPELL_BLESSING_OF_PROTECTION_NAME = "Blessing of Protection";
ONEHITWONDER_SPELL_BLESSING_OF_SANCTUARY_NAME = "Blessing of Sanctuary";
ONEHITWONDER_SPELL_BLESSING_OF_SALVATION_NAME = "Blessing of Salvation";
ONEHITWONDER_SPELL_BLESSING_OF_SACRIFICE_NAME = "Blessing of Sacrifice";
ONEHITWONDER_SPELL_BLESSING_OF_WISDOM_NAME = "Blessing of Wisdom";

ONEHITWONDER_SPELL_JUDGEMENT_NAME = "Judgement";

ONEHITWONDER_SPELL_SEAL_OF_COMMAND_NAME = "Seal of Command";
ONEHITWONDER_SPELL_SEAL_OF_JUSTICE_NAME = "Seal of Justice";
ONEHITWONDER_SPELL_SEAL_OF_RIGHTEOUSNESS_NAME = "Seal of Righteousness";
ONEHITWONDER_SPELL_SEAL_OF_THE_CRUSADER_NAME = "Seal of the Crusader";
ONEHITWONDER_SPELL_SEAL_OF_LIGHT_NAME = "Seal of Light";
ONEHITWONDER_SPELL_SEAL_OF_WISDOM_NAME = "Seal of Wisdom";

ONEHITWONDER_SPELL_SEAL_OF_COMMAND_JUDGEMENT_EFFECT = "Judgement of Command";
ONEHITWONDER_SPELL_SEAL_OF_JUSTICE_JUDGEMENT_EFFECT = "Judgement of Justice";
ONEHITWONDER_SPELL_SEAL_OF_RIGHTEOUSNESS_JUDGEMENT_EFFECT = "Judgement of Righteousness";
ONEHITWONDER_SPELL_SEAL_OF_THE_CRUSADER_JUDGEMENT_EFFECT = "Judgement of the Crusader";
ONEHITWONDER_SPELL_SEAL_OF_LIGHT_JUDGEMENT_EFFECT = "Judgement of Light";
ONEHITWONDER_SPELL_SEAL_OF_WISDOM_JUDGEMENT_EFFECT = "Judgement of Wisdom";

ONEHITWONDER_SPELL_RIGHTEOUS_FURY = "Righteous Fury";


ONEHITWONDER_SPELL_POLYMORPH_NAME 							= "Polymorph";
ONEHITWONDER_SPELL_POLYMORPH_EFFECT							= "Polymorph";

-- Priest Spells

ONEHITWONDER_SPELL_HOLY_FIRE_NAME		 					= "Holy Fire";
ONEHITWONDER_SPELL_HOLY_FIRE_EFFECT							= "Holy Fire";

ONEHITWONDER_SPELL_MIND_BLAST_NAME		 					= "Mind Blast";

ONEHITWONDER_SPELL_MIND_FLAY_NAME		 					= "Mind Flay";
ONEHITWONDER_SPELL_VAMPIRIC_EMBRACE_NAME					= "Vampiric Embrace";
ONEHITWONDER_SPELL_VAMPIRIC_EMBRACE_EFFECT					= "Vampiric Embrace";

ONEHITWONDER_SPELL_FEAR_WARD_NAME		 					= "Fear Ward";
ONEHITWONDER_SPELL_FEAR_WARD_EFFECT 						= "Fear Ward";


ONEHITWONDER_SPELL_INNER_FOCUS_NAME		 					= "Inner Focus";
ONEHITWONDER_SPELL_INNER_FOCUS_EFFECT 						= "Inner Focus";

ONEHITWONDER_SPELL_SHADOW_WORD_PAIN_NAME 					= "Shadow Word: Pain";
ONEHITWONDER_SPELL_SHADOW_WORD_PAIN_EFFECT 					= "Shadow Word: Pain";
ONEHITWONDER_SPELL_SMITE_NAME								= "Smite";
ONEHITWONDER_SPELL_FEEDBACK_NAME							= "Feedback";
ONEHITWONDER_SPELL_FEEDBACK_EFFECT							= "Feedback";

ONEHITWONDER_SPELL_DIVINE_SPIRIT_NAME 						= "Divine Spirit";
ONEHITWONDER_SPELL_PRAYER_OF_SPIRIT_NAME					= "Prayer of Spirit";
ONEHITWONDER_SPELL_POWER_WORD_FORTITUDE_NAME 				= "Power Word: Fortitude";
ONEHITWONDER_SPELL_POWER_WORD_FORTITUDE_EFFECT 				= "Power Word: Fortitude";
ONEHITWONDER_SPELL_PRAYER_OF_FORTITUDE_NAME 				= "Prayer of Fortitude";
ONEHITWONDER_SPELL_PRAYER_OF_FORTITUDE_EFFECT 				= "Prayer of Fortitude";
ONEHITWONDER_SPELL_INNER_FIRE_NAME 							= "Inner Fire";
ONEHITWONDER_SPELL_RENEW_NAME	 							= "Renew";
ONEHITWONDER_SPELL_POWER_WORD_SHIELD_NAME 					= "Power Word: Shield";
ONEHITWONDER_SPELL_POWER_WORD_SHIELD_EFFECT 				= "Weakened Soul";

ONEHITWONDER_SPELL_TOUCH_OF_WEAKNESS_NAME 					= "Touch of Weakness";
ONEHITWONDER_SPELL_SHADOWGUARD_NAME							= "Shadowguard";
ONEHITWONDER_SPELL_SHADOW_PROTECTION_NAME					= "Shadow Protection";
ONEHITWONDER_SPELL_PRAYER_OF_SHADOW_PROTECTION_NAME			= "Prayer of Shadow Protection";
ONEHITWONDER_SPELL_VAMPIRIC_EMBRACE_NAME					= "Vampiric Embrace";

ONEHITWONDER_SPELL_ELUNES_GRACE_NAME						= "Elune's Grace";
ONEHITWONDER_SPELL_DEVOURING_PLAGUE_NAME					= "Devouring Plague";
ONEHITWONDER_SPELL_TOUCH_OF_WEAKNESS_NAME					= "Touch of Weakness";
ONEHITWONDER_SPELL_HEX_OF_WEAKNESS_NAME						= "Hex of Weakness";


ONEHITWONDER_SPELL_CURE_DISEASE_NAME 						= "Cure Disease";
ONEHITWONDER_SPELL_ABOLISH_DISEASE_NAME 					= "Abolish Disease";
ONEHITWONDER_SPELL_DISPEL_MAGIC_NAME 						= "Dispel Magic";

ONEHITWONDER_SPELL_ABOLISH_DISEASE_EFFECT 					= "Abolish Disease";


-- Rogue Spells

ONEHITWONDER_ABILITY_SILENCE_EFFECT							= "Silenced";

ONEHITWONDER_ABILITY_SAP_NAME								= "Sap";
ONEHITWONDER_ABILITY_SAP_EFFECT								= "Sapped";

ONEHITWONDER_ABILITY_ADRENALINE_RUSH_NAME 					= "Adrenaline Rush";
ONEHITWONDER_ABILITY_ADRENALINE_RUSH_EFFECT 				= "Adrenaline Rush";

ONEHITWONDER_ABILITY_DETECT_TRAPS_NAME 						= "Detect Traps";
ONEHITWONDER_ABILITY_DETECT_TRAPS_EFFECT 					= "Detect Traps";

ONEHITWONDER_ABILITY_EVASION_NAME 							= "Evasion";
ONEHITWONDER_ABILITY_SPRINT_NAME 							= "Sprint";


ONEHITWONDER_ABILITY_STEALTH_NAME 							= "Stealth";
ONEHITWONDER_ABILITY_STEALTH_EFFECT 						= "Stealth";
ONEHITWONDER_ABILITY_VANISH_NAME 							= "Vanish";
ONEHITWONDER_ABILITY_VANISH_EFFECT 							= "Vanish";
ONEHITWONDER_ABILITY_SLICEDICE_NAME 						= "Slice and Dice";
ONEHITWONDER_ABILITY_SLICEDICE_EFFECT 						= "Slice and Dice";
ONEHITWONDER_ABILITY_EXPOSEARMOR_EFFECT 					= "Expose Armor";


ONEHITWONDER_ABILITY_EXPOSEARMOR_NAME 						= "Expose Armor";
ONEHITWONDER_ABILITY_AMBUSH_NAME 							= "Ambush";
ONEHITWONDER_ABILITY_GOUGE_NAME 							= "Gouge";
ONEHITWONDER_ABILITY_GOUGE_EFFECT 							= "Gouge";
ONEHITWONDER_ABILITY_BACKSTAB_NAME 							= "Backstab";
ONEHITWONDER_ABILITY_EVISCERATE_NAME 						= "Eviscerate";
ONEHITWONDER_ABILITY_SINISTERSTRIKE_NAME 					= "Sinister Strike";
ONEHITWONDER_ABILITY_PICKPOCKET_NAME 						= "Pick Pocket";
ONEHITWONDER_ABILITY_KICK_NAME 								= "Kick";
ONEHITWONDER_ABILITY_FEINT_NAME 							= "Feint";
ONEHITWONDER_ABILITY_RUPTURE_NAME 							= "Rupture";
ONEHITWONDER_ABILITY_RUPTURE_EFFECT 						= "Rupture";
ONEHITWONDER_ABILITY_DISTRACT_NAME 							= "Distract";
ONEHITWONDER_ABILITY_GARROTE_NAME 							= "Garrote";
ONEHITWONDER_ABILITY_GARROTE_EFFECT							= "Garrote";
ONEHITWONDER_ABILITY_CHEAPSHOT_NAME 						= "Cheap Shot";
ONEHITWONDER_ABILITY_CHEAPSHOT_EFFECT 						= "Cheap Shot";

ONEHITWONDER_ABILITY_KIDNEYSHOT_NAME 						= "Kidney Shot";
ONEHITWONDER_ABILITY_KIDNEYSHOT_EFFECT 						= "Kidney Shot";

ONEHITWONDER_TALENT_HEMORRHAGE_NAME 						= "Hemorrhage";
ONEHITWONDER_TALENT_HEMORRHAGE_EFFECT 						= "Hemorrhage";

ONEHITWONDER_TALENT_RIPOSTE_NAME 							= "Riposte";
ONEHITWONDER_TALENT_RIPOSTE_EFFECT 							= "Riposte";
ONEHITWONDER_TALENT_GHOSTLY_STRIKE_NAME 					= "Ghostly Strike";
ONEHITWONDER_TALENT_GHOSTLY_STRIKE_EFFECT 					= "Ghostly Strike";
ONEHITWONDER_TALENT_COLD_BLOOD_NAME 						= "Cold Blood";
ONEHITWONDER_TALENT_COLD_BLOOD_EFFECT 						= "Cold Blood";


-- Shaman Spells

ONEHITWONDER_SPELL_PURGE_NAME 								= "Purge";
ONEHITWONDER_SPELL_LIGHTNING_SHIELD_NAME 					= "Lightning Shield";
ONEHITWONDER_SPELL_EARTHSHOCK_NAME 							= "Earth Shock";
ONEHITWONDER_SPELL_GROUNDING_TOTEM_NAME 					= "Grounding Totem";

ONEHITWONDER_SPELL_WINDFURY_WEAPON_NAME 					= "Windfury Weapon";
ONEHITWONDER_SPELL_ROCKBITER_WEAPON_NAME 					= "Rockbiter Weapon";
ONEHITWONDER_SPELL_FLAMETONGUE_WEAPON_NAME 					= "Flametongue Weapon";
ONEHITWONDER_SPELL_FROSTBRAND_WEAPON_NAME 					= "Frostbrand Weapon";

ONEHITWONDER_SPELL_WINDFURY_WEAPON_EFFECT 					= "Windfury";
ONEHITWONDER_SPELL_ROCKBITER_WEAPON_EFFECT 					= "Rockbiter";
ONEHITWONDER_SPELL_FLAMETONGUE_WEAPON_EFFECT 				= "Flametongue";
ONEHITWONDER_SPELL_FROSTBRAND_WEAPON_EFFECT 				= "Frostbrand";

ONEHITWONDER_SPELL_CURE_POISON_NAME 						= "Cure Poison";

ONEHITWONDER_SPELL_GHOST_WOLF_NAME 							= "Ghost Wolf";
ONEHITWONDER_SPELL_GHOST_WOLF_EFFECT 						= "Ghost Wolf";

ONEHITWONDER_SPELL_SHAMAN_CLEARCAST_EFFECT					= "Clearcasting";

-- Warlock Pet Spells

OneHitWonder_Devour_Magic_Exclusion_List = {
	ONEHITWONDER_RESURRECTION_SICKNESS_EFFECT,
};

ONEHITWONDER_FELHUNTER_DEVOUR_MAGIC_NAME					= "Devour Magic";
ONEHITWONDER_FELHUNTER_SPELL_LOCK_NAME						= "Spell Lock";

-- Warlock Spells

ONEHITWONDER_SPELL_FEAR_NAME								= "Fear";

-- Kinesia
ONEHITWONDER_SPELL_BANISHED_EFFECT							= "Banish";

ONEHITWONDER_SPELL_NIGHTFALL_NAME							= "Nightfall";
ONEHITWONDER_SPELL_NIGHTFALL_EFFECT							= "Nightfall";

ONEHITWONDER_SPELL_SIPHON_LIFE_NAME							= "Siphon Life";
ONEHITWONDER_SPELL_SIPHON_LIFE_EFFECT						= "Siphon Life";

ONEHITWONDER_SPELL_UNENDING_BREATH_NAME						= "Unending Breath";

ONEHITWONDER_SPELL_SHADOW_WARD_NAME = "Shadow Ward";

ONEHITWONDER_SPELL_DEMON_SKIN_NAME = "Demon Skin";
ONEHITWONDER_SPELL_DEMON_ARMOR_NAME = "Demon Armor";

ONEHITWONDER_SPELL_DETECT_LESSER_INVISIBILITY_NAME = "Detect Lesser Invisibility";
ONEHITWONDER_SPELL_DETECT_INVISIBILITY_NAME = "Detect Invisibility";
ONEHITWONDER_SPELL_DETECT_GREATER_INVISIBILITY_NAME = "Detect Greater Invisibility";


ONEHITWONDER_SPELL_DRAIN_SOUL_NAME = "Drain Soul";

ONEHITWONDER_SPELL_IMMOLATE_NAME = "Immolate";
ONEHITWONDER_EFFECT_IMMOLATE = "Immolate";

ONEHITWONDER_SPELL_CONFLAGRATE_NAME = "Conflagrate";

ONEHITWONDER_SPELL_CORRUPTION_NAME = "Corruption";
ONEHITWONDER_EFFECT_CORRUPTION = "Corruption";

ONEHITWONDER_SPELL_SHADOW_BOLT_NAME = "Shadow Bolt";
ONEHITWONDER_SPELL_SEARING_PAIN_NAME = "Searing Pain";

ONEHITWONDER_SPELL_SHADOWBURN = "Shadowburn";

ONEHITWONDER_SPELL_SOUL_FIRE = "Soul Fire";

ONEHITWONDER_SPELL_CURSE_AGONY = "Curse of Agony";
ONEHITWONDER_SPELL_CURSE_DOOM = "Curse of Doom";
ONEHITWONDER_SPELL_CURSE_ELEMENTS = "Curse of the Elements";
ONEHITWONDER_SPELL_CURSE_RECKLESSNESS = "Curse of Recklessness";
ONEHITWONDER_SPELL_CURSE_SHADOW = "Curse of Shadow";
ONEHITWONDER_SPELL_CURSE_TONGUES = "Curse of Tongues";
ONEHITWONDER_SPELL_CURSE_WEAKNESS = "Curse of Weakness";

ONEHITWONDER_EFFECT_CURSE_AGONY = "Curse of Agony";
ONEHITWONDER_EFFECT_CURSE_TONGUES = "Curse of Tongues";
ONEHITWONDER_EFFECT_CURSE_RECKLESSNESS = "Curse of Recklessness";
ONEHITWONDER_EFFECT_CURSE_WEAKNESS = "Curse of Weakness";

-- Warrior Spells

ONEHITWONDER_WARRIOR_STANCE_BATTLE_NAME				= "Battle Stance";
ONEHITWONDER_WARRIOR_STANCE_DEFENSIVE_NAME			= "Defensive Stance";
ONEHITWONDER_WARRIOR_STANCE_AGGRESSIVE_NAME			= "Berserker Stance";
ONEHITWONDER_WARRIOR_STANCE_BERZERK_NAME			= "Unknown Stance";

ONEHITWONDER_ABILITY_INTERCEPT_NAME					= "Intercept";
ONEHITWONDER_ABILITY_DEMORALIZING_SHOUT_NAME		= "Demoralizing Shout";
ONEHITWONDER_ABILITY_DEMORALIZING_SHOUT_EFFECT		= "Demoralizing Shout";

ONEHITWONDER_ABILITY_THUNDER_CLAP_NAME				= "Thunder Clap";
ONEHITWONDER_ABILITY_THUNDER_CLAP_EFFECT			= "Thunder Clap";

ONEHITWONDER_ABILITY_MORTAL_STRIKE_NAME				= "Mortal Strike";
ONEHITWONDER_ABILITY_MORTAL_STRIKE_EFFECT			= "Mortal Strike";

ONEHITWONDER_ABILITY_BLOODTHIRST_NAME				= "Bloodthirst";
ONEHITWONDER_ABILITY_BLOODTHIRST_EFFECT			= "Bloodthirst";

ONEHITWONDER_ABILITY_WHIRL_STRIKE_NAME				= "Whirlwind";

ONEHITWONDER_ABILITY_SLAM_NAME						= "Slam";
ONEHITWONDER_ABILITY_PUMMEL_NAME					= "Pummel";
ONEHITWONDER_ABILITY_SHIELDBASH_NAME				= "Shield Bash";
ONEHITWONDER_ABILITY_REVENGE_NAME					= "Revenge";
ONEHITWONDER_ABILITY_HEROICSTRIKE_NAME				= "Heroic Strike";
ONEHITWONDER_ABILITY_REND_NAME						= "Rend";
ONEHITWONDER_ABILITY_REND_EFFECT					= "Rend";
ONEHITWONDER_ABILITY_CHARGE_NAME					= "Charge";
ONEHITWONDER_ABILITY_CHARGE_EFFECT					= "Stunned";
ONEHITWONDER_ABILITY_BATTLESHOUT_NAME				= "Battle Shout";
ONEHITWONDER_ABILITY_BERSRAGE_NAME					= "Berserker Rage";
ONEHITWONDER_ABILITY_HAMSTRING_NAME					= "Hamstring";
ONEHITWONDER_ABILITY_HAMSTRING_EFFECT				= "Hamstring";
ONEHITWONDER_ABILITY_MOCKINGBLOW_NAME				= "Mocking Blow";
ONEHITWONDER_ABILITY_OVERPOWER_NAME					= "Overpower";
ONEHITWONDER_ABILITY_EXECUTE_NAME					= "Execute";
ONEHITWONDER_ABILITY_SUNDER_ARMOR_NAME				= "Sunder Armor";
ONEHITWONDER_ABILITY_SUNDER_ARMOR_EFFECT			= "Sunder Armor";

ONEHITWONDER_ABILITY_SUNDER_ARMOR_TOOLTIP			= " by ";
ONEHITWONDER_ABILITY_SUNDER_ARMOR_NUMBER_STRING		= "%d+";

-- Miscellaneous Spells

ONEHITWONDER_ABILITY_SHOOT_NAME 					= "Shoot";
ONEHITWONDER_ABILITY_SHOOT_EFFECT 					= "Shoot"; -- ?

-- Race Spells

ONEHITWONDER_ABILITY_BERSERK_NAME					= "Berserking";
ONEHITWONDER_RACIAL_WILL_OF_THE_FORSAKEN_NAME		= "Will of the Forsaken";
ONEHITWONDER_RACIAL_STONEFORM_NAME					= "Stoneform";


-- Debuff Types

ONEHITWONDER_DEBUFF_TYPE_CURSE_LESSER				= "Lesser";

ONEHITWONDER_DEBUFF_TYPE_CURSE						= "Curse";
ONEHITWONDER_DEBUFF_TYPE_POISON						= "Poison";
ONEHITWONDER_DEBUFF_TYPE_DISEASE					= "Disease";
ONEHITWONDER_DEBUFF_TYPE_MAGIC						= "Magic";

-- Spell lists

OneHitWonder_ShadowSpells = {
	"shadow bolt",
	"shadowburn",
	"mind blast",
	"touch of weakness",
	"devouring plague",
	"shadow word: pain",
	"mind flay"
};

OneHitWonder_ShadowSpellKeyWords = {
	"shadow",
	"dark",
	"consuming"
};

OneHitWonder_NotShadowSpells = {
	"shadow resistance aura", -- once again... not truly correct
	"shadow protection",
	"shadow ward",
	"shadowguard", -- debatable
	"curse of shadow", -- also debatable
	"dark pact",
	"mind soothe",
	"mind-numbing poison",
	"mind control", -- not entirely true
	"mind vision"
};

OneHitWonder_FireSpells = {
	"fireball",
	"fire blast",
	"fire nova totem",
	"rain of fire",
	"holy fire",
	"hellfire",
	"searing pain",
	"soul fire",
	"pyroblast",
	"scorch",
	"immolate",
	"torch burst",
	"torch toss"
};

OneHitWonder_NotFireSpells = {
	"moonfire",
	"faerie fire",
	"fire ward", -- not really true, but used in the context it will be...
	"starfire",
	"rapid fire",
	"fire resistance totem",
	"inner fire",
	"searing totem"
};

OneHitWonder_FireSpellKeyWords = {
	"pyro",
	"fire",
	"searing",
	"scorch"
};

OneHitWonder_FrostSpells = {
	"frostbolt",
	"frost nova", -- should this be here or in not frost spells? we can't do anything, so...
	"frostbrand weapon",
	"cone of cold",
	"blizzard"
};

OneHitWonder_FrostSpellKeyWords = {
	"frost",
	"cold",
	"ice"
};

OneHitWonder_NotFrostSpells = {
	--"frost nova", -- should this be here or in frost spells? we can't do anything, so...
	"frost armor",
	"frost shock", -- thottbot says nothing about frost damage, so...
	"frost ward",
	"ice armor", -- not entirely true
	"ice barrier", -- not entirely true
	"frost resistance totem",
	"frost resistance aura"
};

-- spells that should not be cured due to all kinds of factor, but mostly that they have a low duration or are immediately re-applied.
OneHitWonder_DoNotCountTheseDebuffSpells = {
	
	[ONEHITWONDER_DEBUFF_TYPE_CURSE] = {
	},
	[ONEHITWONDER_DEBUFF_TYPE_DISEASE] = {
		"Corrupted Agility",
		"Corrupted Strength",
	},
	[ONEHITWONDER_DEBUFF_TYPE_MAGIC] = {
	},
	[ONEHITWONDER_DEBUFF_TYPE_POISON] = {
	},
	
};


OneHitWonder_DoNotDispelSpells = {
	"Berserk",
	"Battle Shout",
	"Rushing Charge",
	"Devotion Aura",
	"Battle Fury",
	"Defensive Stance",
	"Improved Blocking",
	"Bloodlust",
	"2 extra attacks through Thrash",
	"Enrage",
	"Adrenaline Rush",
	"Evasion",
	"Summon Shardlings",
	"Dust Field",
	"Goblin Dragon Gun",
};


OneHitWonder_DispelSpells = {
	-- Druid spells
	ONEHITWONDER_SPELL_THORNS_NAME,
	ONEHITWONDER_SPELL_REJUVENATION_NAME,
	ONEHITWONDER_SPELL_NATURES_GRASP_NAME,
	ONEHITWONDER_SPELL_REGROWTH_NAME,
	ONEHITWONDER_SPELL_MARK_OF_THE_WILD_NAME,
	ONEHITWONDER_SPELL_ABOLISH_POISON_NAME,
	-- Mage spells
	ONEHITWONDER_SPELL_AMPLIFY_MAGIC_NAME,
	ONEHITWONDER_SPELL_ARCANE_INTELLECT_NAME,
	ONEHITWONDER_SPELL_DAMPEN_MAGIC_NAME,
	ONEHITWONDER_SPELL_FIRE_WARD_NAME,
	ONEHITWONDER_SPELL_FROST_ARMOR_NAME,
	ONEHITWONDER_SPELL_FROST_WARD_NAME,
	ONEHITWONDER_SPELL_ICE_ARMOR_NAME,
	ONEHITWONDER_SPELL_ICE_BARRIER_NAME,
	ONEHITWONDER_SPELL_MANA_SHIELD_NAME,
	-- Paladin spells
	ONEHITWONDER_SPELL_BLESSING_OF_KINGS_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_LIGHT_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_MIGHT_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_FREEDOM_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_PROTECTION_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_SANCTUARY_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_SALVATION_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_SACRIFICE_NAME,
	ONEHITWONDER_SPELL_BLESSING_OF_WISDOM_NAME,

	ONEHITWONDER_SPELL_SEAL_OF_COMMAND_NAME, 
	ONEHITWONDER_SPELL_SEAL_OF_FURY_NAME, 
	ONEHITWONDER_SPELL_SEAL_OF_JUSTICE_NAME, 
	ONEHITWONDER_SPELL_SEAL_OF_LIGHT_NAME, 
	ONEHITWONDER_SPELL_SEAL_OF_RIGHTEOUSNESS_NAME, 
	ONEHITWONDER_SPELL_SEAL_OF_THE_CRUSADER_NAME, 
	ONEHITWONDER_SPELL_SEAL_OF_WISDOM_NAME, 

	--hmm
	ONEHITWONDER_SPELL_HOLY_SHIELD_NAME,
	-- Priest spells
	ONEHITWONDER_SPELL_ABOLISH_DISEASE_NAME,
	ONEHITWONDER_SPELL_DIVINE_SPIRIT_NAME,
	ONEHITWONDER_SPELL_INNER_FIRE_NAME,
	ONEHITWONDER_SPELL_POWER_WORD_FORTITUDE_NAME,
	ONEHITWONDER_SPELL_POWER_WORD_SHIELD_NAME,
	ONEHITWONDER_SPELL_RENEW_NAME,
	ONEHITWONDER_SPELL_SHADOW_PROTECTION_NAME,
	ONEHITWONDER_SPELL_SHADOWGUARD_NAME,
	ONEHITWONDER_SPELL_VAMPIRIC_EMBRACE_NAME,
	ONEHITWONDER_SPELL_FEAR_WARD_NAME,
	-- Shaman spells
	ONEHITWONDER_SPELL_LIGHTNING_SHIELD_NAME,
	ONEHITWONDER_SPELL_WINDFURY_WEAPON_EFFECT,
	ONEHITWONDER_SPELL_ROCKBITER_WEAPON_EFFECT,
	ONEHITWONDER_SPELL_FLAMETONGUE_WEAPON_EFFECT,
	ONEHITWONDER_SPELL_FROSTBRAND_WEAPON_EFFECT,
	-- Warlock spells
	ONEHITWONDER_SPELL_DEMON_SKIN_NAME,
	ONEHITWONDER_SPELL_DEMON_ARMOR_NAME,
	ONEHITWONDER_SPELL_SHADOW_WARD_NAME,
	-- Mob Spells
	"Fire Shield", -- Comes in varieties - like Fire Shield I, Fire Shield II and so on
	"Fire Shield II",
	--"Improved Blocking", -- I don't think this spell can be dispelled.
};

ONEHITWONDER_ABILITY_CLOAK_EFFECTS = {
	ONEHITWONDER_ABILITY_SHADOWMELD_EFFECT,
	ONEHITWONDER_ABILITY_STEALTH_EFFECT,
	ONEHITWONDER_ABILITY_VANISH_EFFECT,
	ONEHITWONDER_SPELL_LESSER_INVISIBILITY_EFFECT,
	ONEHITWONDER_SPELL_INVISIBILITY_EFFECT,
	ONEHITWONDER_SPELL_GREATER_INVISIBILITY_EFFECT,
};

OneHitWonder_SpellsThatShouldNotBeInterrupted = {
	"Shoot",
	"Shoot Gun",
	"Shoot Bow",
	"Shoot Crossbow",
	"Hearthstone",
};

OneHitWonder_SpellsThatCanNotBeKickInterrupted = {
	"Black Sludge",
	"Clone",
	"Dire Growl",
	"Encasing Webs",
	"Frost Breath",
	"Healing Ward",
	"Melt Ore",
	"Summon Remote-Controlled Golem", 
};

OneHitWonder_FearSpells = {
	ONEHITWONDER_SPELL_FEAR_NAME,
};

OneHitWonder_ExposeArmorEffects = {
	ONEHITWONDER_ABILITY_EXPOSEARMOR_EFFECT,
	ONEHITWONDER_ABILITY_SUNDER_ARMOR_EFFECT,
};

OneHitWonder_Rogue_StealthOpeningAbilities = {
	ONEHITWONDER_ABILITY_BACKSTAB_NAME,
	ONEHITWONDER_ABILITY_GARROTE_NAME,
	ONEHITWONDER_ABILITY_AMBUSH_NAME,
	ONEHITWONDER_ABILITY_CHEAPSHOT_NAME,
};

OneHitWonder_Rogue_DaggerRequiringSkills = {
	ONEHITWONDER_ABILITY_BACKSTAB_NAME,
	ONEHITWONDER_ABILITY_AMBUSH_NAME
};

ONEHITWONDER_ABILITY_STEALTH_EFFECTS = {
	ONEHITWONDER_ABILITY_STEALTH_EFFECT,
	ONEHITWONDER_ABILITY_VANISH_EFFECT
};

ONEHITWONDER_STUN_EFFECTS = {
	ONEHITWONDER_SPELL_HAMMER_OF_JUSTICE_EFFECT,
	ONEHITWONDER_ABILITY_KIDNEYSHOT_EFFECT,
	ONEHITWONDER_ABILITY_CHARGE_EFFECT,
	ONEHITWONDER_SPELL_IMPROVED_CONCUSSIVE_SHOT_EFFECT,
	ONEHITWONDER_SPELL_IMPACT_EFFECT,
	-- ... ... ... 
};

ONEHITWONDER_SLEEP_EFFECTS = {
	"Sleep",
	ONEHITWONDER_SPELL_POLYMORPH_EFFECT,
	ONEHITWONDER_ABILITY_SAP_EFFECT,
	ONEHITWONDER_ABILITY_GOUGE_EFFECT,
};


ONEHITWONDER_SLOW_EFFECTS = {
	"Frost Shock",
	ONEHITWONDER_SPELL_CONCUSSIVE_SHOT_EFFECT,
	ONEHITWONDER_SPELL_WING_CLIP_EFFECT,
	ONEHITWONDER_ABILITY_HAMSTRING_EFFECT,
	"Crippling Poison",
	"Crippling Poison II",
	"Slowed",
};

ONEHITWONDER_DO_NOT_CAST_SPELLS_EFFECT = {
	ONEHITWONDER_EFFECT_SPELL_BOMB_NAME,
};

ONEHITWONDER_SILENCE_EFFECTS = {
	ONEHITWONDER_ABILITY_SILENCE_EFFECT,
};

ONEHITWONDER_DISARM_EFFECTS = {
	"Disarmed!",
	ONEHITWONDER_TALENT_RIPOSTE_EFFECT,
};



OneHitWonder_Druid_Shapeshift_Effects = {
	ONEHITWONDER_SPELL_SHAPESHIFT_AQUATIC_FORM_EFFECT,
	ONEHITWONDER_SPELL_SHAPESHIFT_BEAR_FORM_EFFECT,
	ONEHITWONDER_SPELL_SHAPESHIFT_CAT_FORM_EFFECT,
	ONEHITWONDER_SPELL_SHAPESHIFT_DIRE_BEAR_FORM_EFFECT,
	ONEHITWONDER_SPELL_SHAPESHIFT_TRAVEL_FORM_EFFECT
};
