-- Version : English - sarf
-- Translation by : None

ONEHITWONDER_MAIN_HAND_NAME				= "Main Hand";

ONEHITWONDER_WARLOCK_ITEM_SOUL_SHARD	= "Soul Shard";
ONEHITWONDER_ITEM_FISHING_POLE			= "Fishing Pole";

OneHitWonder_FishingItems = {
	ONEHITWONDER_ITEM_FISHING_POLE,
	"Big Iron Fishing Pole",
};

OneHitWonder_FishingItemSubStrings = {
	ONEHITWONDER_ITEM_FISHING_POLE,
};


ONEHITWONDER_ITEM_TYPE_MACE				= "Sword";
ONEHITWONDER_ITEM_TYPE_DAGGER			= "Dagger";
ONEHITWONDER_ITEM_TYPE_SWORD			= "Sword";
ONEHITWONDER_ITEM_TYPE_SHIELD			= "Shield";
ONEHITWONDER_ITEM_TYPE_STAFF			= "Staff";
ONEHITWONDER_ITEM_TYPE_POLEARM			= "Polearm";
ONEHITWONDER_ITEM_TYPE_AXE				= "Axe";

ONEHITWONDER_ITEM_TYPE_WEAPONS_LIST		= {
	ONEHITWONDER_ITEM_TYPE_MACE,
	ONEHITWONDER_ITEM_TYPE_DAGGER,
	ONEHITWONDER_ITEM_TYPE_SWORD,
	ONEHITWONDER_ITEM_TYPE_STAFF,
	ONEHITWONDER_ITEM_TYPE_AXE,
	ONEHITWONDER_ITEM_TYPE_POLEARM,
};

if ( GetLocale() == "frFR" ) then
elseif ( GetLocale() == "deDE" ) then
end
