----------------------------------------------------------------------------------------------------
-- Chinese Simplified Localizable Strings
----------------------------------------------------------------------------------------------------

if ( GetLocale() == "zhCN" ) then
-- translated by: Diablohu
-- a member of DiamondForce
-- http://www.dreamgen.net

-- For Binding.xml
BINDING_HEADER_QUESTHISTORY = "QuestHistory[任务历史]";
BINDING_NAME_QUESTHISTORYTOGGLE = "打开/关闭";

-- Displayed when QuestHistory is loaded
QUESTHISTORY_LOAD_TEXT = "Jasters\226\128\153 QuestHistory v%0.2f 插件已加载 (由 Dsanai 更新)";

-- QuestHistoryFrame text strings
QUESTHISTORY_FRAME_TITLE = "QuestHistory[任务历史]";
QUESTHISTORY_TITLE = "";
QUESTHISTORY_TITLE_FORMAT_SINGULAR = "%s - 总计1个任务";
QUESTHISTORY_TITLE_FORMAT_PLURAL = "%s - 总计%d个任务";
QUESTHISTORY_SORT_DROPDOWN_TEXT = "排序:";
QUESTHISTORY_ACCEPTEDSORT_TEXT = "#";
QUESTHISTORY_TITLESORT_TEXT = "任务名";
QUESTHISTORY_LEVELSORT_TEXT = "等级";
QUESTHISTORY_CATEGORYSORT_TEXT = "类别";
QUESTHISTORY_TAGSORT_TEXT = "标记";
QUESTHISTORY_COMPLETEDSORT_TEXT = "是否完成";
QUESTHISTORY_CANCEL_TEXT = "取消";
QUESTHISTORY_OPTIONS_TEXT = "设置";
QUESTHISTORY_CLEAR_TEXT = "清空";
QUESTHISTORY_SEARCH_TEXT = "搜索";
QUESTHISTORY_SUBMIT_TEXT = "开始搜索";

-- For the Sort Dropdown list
SORT_ACCEPTED = "接受任务时间";
SORT_TITLE = "任务名";
SORT_LEVEL = "等级";
SORT_CATEGORY = "类别";
SORT_COMPLETED = "完成任务时间";
SORT_TAG = "标记";
SORT_XP = "经验值奖励";
SORT_MONEY = "金钱奖励";
SORT_GIVER = "任务给予者";
SORT_COMPLETER = "任务完成者";

-- QuestHistoryDetailFrame text strings
QUESTHISTORY_DETAIL_TITLE = "";
QUESTHISTORY_DETAIL_TITLE_FORMAT = "%s - 等级 %s%s";
QUESTHISTORY_LEVEL_ACCEPTED_TITLE = "接受等级:";
QUESTHISTORY_LEVEL_LOGGED_TITLE = "记录时等级:";
QUESTHISTORY_LEVEL_COMPLETED_TITLE = "完成时等级:";
QUESTHISTORY_XP_REWARDED_TITLE = "经验值奖励:";
QUESTHISTORY_MONEY_REWARDED_TITLE = "金钱奖励:";
QUESTHISTORY_DETAIL_NOTES_TITLE = "备注:";
QUESTHISTORY_QUEST_GIVER_TITLE = "给予者:";
QUESTHISTORY_QUEST_COMPLETER_TITLE = "任务完成者:";
QUESTHISTORY_ACCEPTED_LOCATION_TITLE = "接受地点:";
QUESTHISTORY_COMPLETED_LOCATION_TITLE = "完成地点:";
QUESTHISTORY_TIME_ACCEPTED_TITLE = "接受时间:";
QUESTHISTORY_TIME_LOGGED_TITLE = "记录时间:";
QUESTHISTORY_TIME_COMPLETED_TITLE = "完成的时间:";
QUESTHISTORY_TIME_FORMAT = "%02d:%02d:%02d:%02d";
QUESTHISTORY_TIMES_ABANDONED_TITLE = "放弃次数:";
QUESTHISTORY_TIMES_FAILED_TITLE = "失败次数:";
QUESTHISTORY_EDIT_TEXT = "编辑";
QUESTHISTORY_SAVE_TEXT = "保存";
QUESTHISTORY_EXIT_TEXT = "退出";
QUESTHISTORY_NEXT_TEXT = "下一个";
QUESTHISTORY_PREVIOUS_TEXT = "上一个";

-- QuestHistoryOptionsFrame text strings
QUESTHISTORY_OPTIONS_MENU = "QuestHistory 选项";
QUESTHISTORY_OKAY_TEXT = "确定";
QUESTHISTORY_SHOW = "显示";
QUESTHISTORY_SHOW_ABANDONED = "放弃的";
QUESTHISTORY_SHOW_CURRENT = "当前的";
QUESTHISTORY_SHOW_COMPLETED = "完成的";
QUESTHISTORY_CHARACTER_DROPDOWN_TEXT = "角色:";
QUESTHISTORY_LOG = "记录";
QUESTHISTORY_LOG_LEVEL = "任务等级";
QUESTHISTORY_LOG_CATEGORY = "任务类别";
QUESTHISTORY_LOG_TAG = "任务标记";
QUESTHISTORY_LOG_COMPLETED_ORDER = "任务完成顺序";
QUESTHISTORY_LOG_DESCRIPTION = "任务描述";
QUESTHISTORY_LOG_OBJECTIVES = "任务目标";
QUESTHISTORY_LOG_OBJECTIVES_STATUS = "任务目标完成情况";
QUESTHISTORY_LOG_REWARDS = "任务奖励";
QUESTHISTORY_LOG_CHOICES = "任务奖励选择";
QUESTHISTORY_LOG_SPELLS = "任务奖励技能";
QUESTHISTORY_LOG_REWARD_MONEY = "任务金钱奖励";
QUESTHISTORY_LOG_BACKGROUND_MATERIAL = "背景图片";
QUESTHISTORY_LOG_REQUIRED_MONEY = "任务所需金钱";
QUESTHISTORY_LOG_XP_REWARD = "任务经验值奖励";
QUESTHISTORY_LOG_QUEST_GIVER = "任务给予者";
QUESTHISTORY_LOG_QUEST_COMPLETER = "任务完成者";
QUESTHISTORY_LOG_ACCEPTED_LEVEL = "接受任务时玩家等级";
QUESTHISTORY_LOG_COMPLETED_LEVEL = "完成任务时玩家等级";
QUESTHISTORY_LOG_ACCEPTED_TIME = "接受任务时游戏时间";
QUESTHISTORY_LOG_COMPLETED_TIME = "完成任务时游戏时间";
QUESTHISTORY_LOG_ACCEPTED_LOCATION = "任务接受地点";
QUESTHISTORY_LOG_COMPLETED_LOCATION = "任务完成地点";
QUESTHISTORY_ADD_TEXT = "添加";
QUESTHISTORY_PURGE_TEXT = "净化";
QUESTHISTORY_DELETE_TEXT = "删除";
QUESTHISTORY_REPAIR = "修复";
QUESTHISTORY_REMOVE_PORT_QUESTS = "删除港口任务";
QUESTHISTORY_REMOVE_DUPLICATES = "删除重复的任务";
QUESTHISTORY_OTHER = "其他";
QUESTHISTORY_ALLOW_EDITING = "允许编辑";
QUESTHISTORY_ALLOW_DELETING = "允许删除";
QUESTHISTORY_LOG_PORT_QUESTS = "记录港口任务";
QUESTHISTORY_OPTION_TOOLTIP_SHOW_ABANDONED = "在QuestHistory中显示放弃的任务";
QUESTHISTORY_OPTION_TOOLTIP_SHOW_CURRENT = "在QuestHistory中显示当前的任务";
QUESTHISTORY_OPTION_TOOLTIP_SHOW_COMPLETED = "在QuestHistory中显示完成的任务";
QUESTHISTORY_OPTION_TOOLTIP_SELECT_CHARACTER = "选择显示哪一位角色的任务历史";
QUESTHISTORY_OPTION_TOOLTIP_SELECT_COLOR = "设置这个任务状态的颜色";
QUESTHISTORY_OPTION_TOOLTIP_LOG_LEVEL = "记录任务难度等级";
QUESTHISTORY_OPTION_TOOLTIP_LOG_CATEGORY = "记录任务类别";
QUESTHISTORY_OPTION_TOOLTIP_LOG_TAG = "记录任务标记（如：精英任务）";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_ORDER = "记录任务接受顺序\n\n注：取消此选项将会导致任务无法被标记为完成";
QUESTHISTORY_OPTION_TOOLTIP_LOG_DESCRIPTION = "记录任务描述";
QUESTHISTORY_OPTION_TOOLTIP_LOG_OBJECTIVES = "记录任务目标";
QUESTHISTORY_OPTION_TOOLTIP_LOG_OBJECTIVES_STATUS = "记录任务目标完成情况（如：0/1 已完成）";
QUESTHISTORY_OPTION_TOOLTIP_LOG_REWARDS = "记录任务物品奖励\n\n这些物品是在你完成任务时获得的";
QUESTHISTORY_OPTION_TOOLTIP_LOG_CHOICES = "记录任务选择物品奖励\n\n这些物品是在你完成任务时选择的";
QUESTHISTORY_OPTION_TOOLTIP_LOG_SPELLS = "记录任务技能奖励";
QUESTHISTORY_OPTION_TOOLTIP_LOG_REWARD_MONEY = "记录任务金钱奖励";
QUESTHISTORY_OPTION_TOOLTIP_LOG_BACKGROUND_MATERIAL = "记录任务背景图片（通常是空的）";
QUESTHISTORY_OPTION_TOOLTIP_LOG_REQUIRED_MONEY = "记录完成任务所需的金钱";
QUESTHISTORY_OPTION_TOOLTIP_LOG_XP_REWARD = "记录完成任务所奖励的经验值";
QUESTHISTORY_OPTION_TOOLTIP_LOG_QUEST_GIVER = "记录给予任务的NPC";
QUESTHISTORY_OPTION_TOOLTIP_LOG_QUEST_COMPLETER = "记录完成任务的NPC";
QUESTHISTORY_OPTION_TOOLTIP_LOG_ACCEPTED_LEVEL = "记录接受任务时玩家的等级";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_LEVEL = "记录完成任务时玩家的等级";
QUESTHISTORY_OPTION_TOOLTIP_LOG_ACCEPTED_TIME = "记录接受任务时的游戏时间";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_TIME = "记录完成任务时的游戏时间";
QUESTHISTORY_OPTION_TOOLTIP_LOG_ACCEPTED_LOCATION = "记录接受任务的地点";
QUESTHISTORY_OPTION_TOOLTIP_LOG_COMPLETED_LOCATION = "记录完成任务的地点";
QUESTHISTORY_OPTION_TOOLTIP_ADD_QUEST = "打开一个编辑窗口以手动添加一个新任务"
QUESTHISTORY_OPTION_TOOLTIP_PURGE = "清楚目前显示的角色的记录中未选择的数据";
QUESTHISTORY_OPTION_TOOLTIP_DELETE_CHARACTER = "完全删除现在目前显示的记录\n\n不能删除目前所游戏的角色";
QUESTHISTORY_OPTION_TOOLTIP_REMOVE_PORT_QUESTS = "如果选择，修复命令将会删除奥伯丁和米奈希尔港之间的港口任务";
QUESTHISTORY_OPTION_TOOLTIP_REMOVE_DUPLICATES = "如果选择，修复命令将会删除那些有重复标题和描述的任务";
QUESTHISTORY_OPTION_TOOLTIP_REPAIR = "为所有角色修复任务历史";
QUESTHISTORY_OPTION_TOOLTIP_ALLOW_EDITING = "允许编辑任务\n\n右键点击一个任务即可进行编辑";
QUESTHISTORY_OPTION_TOOLTIP_ALLOW_DELETING = "允许删除任务\n\nShift+右键点击一个任务即可进行删除";
QUESTHISTORY_OPTION_TOOLTIP_LOG_PORT_QUESTS = "允许记录奥伯丁和米奈希尔港之间的港口任务";

-- QuestHistoryConfirmFrame text strings
QUESTHISTORY_CONFIRM_TEXT = "是否确定？";
QUESTHISTORY_PURGE_CONFIRM_EXPLANATION = "继续这个操作将会清除目前显示的角色的记录\n\n在前一个窗口中任何未选择的数据都将从 SavedVariables.lua 中删除\n\n这些数据将无法恢复，所以建议您在继续操作前备份 SavedVariables.lua";
QUESTHISTORY_DELETE_CONFIRM_EXPLANATION = "继续这个操作将会完全删除目前显示的角色的记录\n\n这些数据将无法恢复，所以建议您在继续操作前备份 SavedVariables.lua";
QUESTHISTORY_REPAIR_CONFIRM_EXPLANATION = "继续这个操作将会尝试修复所有角色的记录，有时可以解决一些错误\n\n另外，如果在前一个窗口中选择的话，这个操作将会清除重复的任务及奥伯丁和米奈希尔港之间的港口任务\n\n因为这个操作会清除一部分数据，所以建议您在继续操作前备份 SavedVariables.lua";

-- QuestHistoryEditFrame text strings
QUESTHISTORY_EDIT_TITLE_TEXT = "任务名:";
QUESTHISTORY_EDIT_OBJECTIVES_TEXT = "任务目标:";
QUESTHISTORY_EDIT_DESCRIPTION_TEXT = QUEST_DESCRIPTION..":";
QUESTHISTORY_ACCEPTED_TITLE = "接受:";
QUESTHISTORY_LEVEL_TITLE = "等级:";
QUESTHISTORY_COMPLETED_TITLE = "完成:";
QUESTHISTORY_CATEGORY_TITLE = "类别:";
QUESTHISTORY_TAG_TITLE = "标记:";
QUESTHISTORY_ZONE_TITLE = "地点:";
QUESTHISTORY_X_TITLE = "X:";
QUESTHISTORY_Y_TITLE = "Y:";

end
