AtlasLootRepItems = {
    Argent1 = {
        { 22689, "INV_Helmet_13", "=q3=Sanctified Leather Helm", "=ds=#a2# #s1#" },
        { 22690, "INV_Pants_03", "=q3=Leggings of the Plague Hunter", "=ds=#a3# #s11#" },
        { 22681, "INV_Jewelry_Ring_33", "=q3=Band of Piety", "=ds=#s13#" },
        { 22680, "INV_Jewelry_Ring_01", "=q3=Band of Resolution", "=ds=#s13#" },
        { 22688, "INV_Weapon_ShortBlade_03", "=q3=Verimonde's Last Resort", "=ds=#h3# #w4#" },
        { 22679, "INV_Misc_Bag_17", "=q3=Supply Bag", "=ds=#e10#" },
        { 0, "", "", "" },
        { 22523, "INV_Misc_Token_ArgentDawn", "=q2=Insignia of the Dawn", "=ds=#e22#" },
        { 0, "", "", "" },
        { 0, "", "", "" },        
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 22667, "INV_Bracer_12", "=q4=Bracers of Hope", "=ds=#a1# #s8#" },
        { 22668, "INV_Bracer_04", "=q4=Bracers of Subterfuge", "=ds=#a2# #s8#" },
        { 22657, "INV_Jewelry_Amulet_04", "=q4=Amulet of the Dawn", "=ds=#s2#" },
        { 22659, "INV_Jewelry_Amulet_04", "=q4=Medallion of the Dawn", "=ds=#s2#" },
        { 22678, "INV_Misc_Gem_Pearl_04", "=q4=Talisman of Ascendance", "=ds=#s14#" },
        { 22656, "INV_Weapon_Rifle_06", "=q4=The Purifier", "=ds=#w5#" },
        { 0, "", "", "" },
        { 22524, "INV_Misc_Token_ScarletCrusade", "=q2=Insignia of the Crusade", "=ds=#e22#" },
        };

    Argent2 = {
        { 0, "INV_Jewelry_Talisman_08", "=q6=#r2#", "" },
        { 13724, "INV_Misc_Food_33", "=q1=Enriched Manna Biscuit", "=ds=#e2#" },
        { 0, "", "", "" },
        { 0, "INV_Jewelry_Talisman_08", "=q6=#r3#", "" },
        { 19216, "INV_Scroll_03", "=q1=Pattern: Argent Boots", "=ds=#p8#" },
        { 19328, "INV_Scroll_03", "=q1=Pattern: Dawn Treaders", "=ds=#p7#" },
        { 19203, "INV_Scroll_03", "=q1=Plans: Girdle of the Dawn", "=ds=#p2#" },
        { 19442, "INV_Scroll_03", "=q1=Formula: Powerful Anti-Venom", "=ds=#p6#" },
        { 19446, "INV_Misc_Note_01", "=q1=Formula: Enchant Bracer - Mana Regeneration", "=ds=#p4#" },
        { 13482, "INV_Scroll_06", "=q2=Recipe: Transmute Air to Fire", "=ds=#p1#" },
        };

    Argent3 = {
        { 0, "INV_Jewelry_Talisman_08", "=q6=#r4#", "" },
        { 19217, "INV_Scroll_03", "=q1=Pattern: Argent Shoulders", "=ds=#p8#" },
        { 19329, "INV_Scroll_03", "=q1=Pattern: Golden Mantle of the Dawn", "=ds=#p7#" },
        { 19205, "INV_Scroll_03", "=q1=Plans: Gloves of the Dawn", "=ds=#p2#" },
        { 19447, "INV_Scroll_03", "=q1=Formula: Enchant Bracer - Healing", "=ds=#p4#" },
        { 18171, "Spell_Holy_WordFortitude", "=q2=Arcane Mantle of the Dawn", "=ds=#s3# #e11#" },
        { 18169, "Spell_Fire_FlameShock", "=q2=Flame Mantle of the Dawn", "=ds=#s3# #e11#" },
        { 18170, "Spell_Frost_FrostShock", "=q2=Frost Mantle of the Dawn", "=ds=#s3# #e11#" },
        { 18172, "Spell_Nature_ProtectionformNature", "=q2=Nature Mantle of the Dawn", "=ds=#s3# #e11#" },
        { 18173, "Spell_Shadow_RagingScream", "=q2=Shadow Mantle of the Dawn", "=ds=#s3# #e11#" },
        { 13810, "INV_Misc_Food_41", "=q1=Blessed Sunfruit", "=ds=#e2#" },
        { 13813, "INV_Drink_16", "=q1=Blessed Sunfruit Juice", "=ds=#e3#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "INV_Jewelry_Talisman_08", "=q6=#r5#", "" },
        { 18182, "INV_Misc_Gem_Variety_02", "=q2=Chromatic Mantle of the Dawn", "=ds=#s3# #e11#" },
        };
        
    Timbermaw = {
        { 0, "INV_Misc_Horn_01", "=q6=#r2#", "" },
        { 13484, "INV_Scroll_03", "=q2=Recipe: Transmute Earth to Water","=ds=#p1#" },
        { 15754, "INV_Scroll_03", "=q1=Pattern: Warbear Woolies","=ds=#p7#" },   		 
   		{ 15742, "INV_Scroll_03", "=q1=Pattern: Warbear Harness","=ds=#p7#" },
        { 22392, "INV_Misc_Note_01", "=q1=Formula: Enchant 2H Weapon - Agility","=ds=#p4#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Horn_01", "=q6=#r3#", "" },
        { 16768, "INV_Misc_Bag_11", "=q2=Furbolg Medicine Pouch", "=ds=#s15#" },
        { 16769, "INV_Mace_11", "=q2=Furbolg Medicine Totem", "=ds=#h3# #w6#" },
        { 19202, "INV_Scroll_03", "=q1=Plans: Heavy Timbermaw Belt","=ds=#p2#" },
        { 19326, "INV_Scroll_03", "=q1=Pattern: Might of the Timbermaw","=ds=#p7#" },
        { 19215, "INV_Scroll_03", "=q1=Pattern: Wisdom of the Timbermaw","=ds=#p8#" },
        { 19445, "INV_Misc_Note_01", "=q1=Formula: Enchant Weapon - Agility","=ds=#p4#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Horn_01", "=q6=#r4#", "" },
   		{ 19218, "INV_Scroll_03", "=q1=Pattern: Mantle of the Timbermaw","=ds=#p8#" },  
   		{ 19327, "INV_Scroll_03", "=q1=Pattern: Timbermaw Brawlers","=ds=#p7#" },  
   		{ 19204, "INV_Scroll_03", "=q1=Plans: Heavy Timbermaw Boots","=ds=#p2#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Horn_01", "=q6=#r5#", "" },        
        { 21326, "INV_Misc_Horn_01", "=q4=Defender of the Timbermaw", "=ds=#s14#"},
        };
           
    Thorium1 = {
        { 17018, "INV_Scroll_03", "=q1=Pattern: Flarecore Gloves", "=ds=#p8#" },
        { 17023, "INV_Scroll_03", "=q1=Pattern: Molten Helm", "=ds=#p11# #p7#" },
        { 17022, "INV_Scroll_03", "=q1=Pattern: Corehound Boots", "=ds=#p10# #p7#" },
        { 17051, "INV_Scroll_03", "=q3=Plans: Dark Iron Bracers", "=ds=#p2#" },
        { 20761, "INV_Scroll_03", "=q1=Recipe: Transmute Elemental Fire", "=ds=#p1#" },
        { 19444, "INV_Misc_Note_01", "=q1=Formula: Enchant Weapon - Strength", "=ds=#p4#" },
    };
    
    Thorium2 = {
        { 17017, "INV_Scroll_03", "=q1=Pattern: Flarecore Mantle", "=ds=#p8#" },
        { 19219, "INV_Scroll_03", "=q1=Pattern: Flarecore Robe", "=ds=#p8#" },
        { 19330, "INV_Scroll_03", "=q1=Pattern: Lava Belt", "=ds=#p7#" },
        { 17049, "INV_Scroll_03", "=q1=Plans: Fiery Chain Girdle", "=ds=#p2#" },
        { 17025, "INV_Scroll_03", "=q1=Pattern: Black Dragonscale Boots", "=ds=#p9# #p7#" },
        { 19206, "INV_Scroll_03", "=q1=Plans: Dark Iron Helm", "=ds=#p2#" },
        { 17059, "INV_Scroll_03", "=q3=Plans: Dark Iron Reaver", "=ds=#p2#" },
        { 17060, "INV_Scroll_03", "=q1=Plans: Dark Iron Destroyer", "=ds=#p2#" },
        { 19448, "INV_Misc_Note_01", "=q1=Formula: Enchant Weapon - Mighty Spirit", "=ds=#p4#" },  
    };
    
    Thorium3 = {
        { 19220, "INV_Scroll_03", "=q1=Pattern: Flarecore Leggings", "=ds=#p8#" },
        { 19333, "INV_Scroll_03", "=q1=Pattern: Molten Belt", "=ds=#p11# #p7#" },
        { 19332, "INV_Scroll_03", "=q1=Pattern: Corehound Belt", "=ds=#p10# #p7#" }, 
        { 17053, "INV_Scroll_03", "=q3=Plans: Fiery Chain Shoulders", "=ds=#p2#" },
        { 19331, "INV_Scroll_03", "=q1=Pattern: Chromatic Gauntlets", "=ds=#p9# #p7#" },
        { 19207, "INV_Scroll_03", "=q1=Plans: Dark Iron Gauntlets", "=ds=#p2#" },
        { 17052, "INV_Scroll_03", "=q3=Plans: Dark Iron Leggings", "=ds=#p2#" },
        { 19208, "INV_Scroll_03", "=q1=Plans: Black Amnesty", "=ds=#p2#" },
        { 19209, "INV_Scroll_03", "=q1=Plans: Blackfury", "=ds=#p2#" },        
        { 19449, "INV_Scroll_03", "=q1=Formula: Enchant Weapon - Mighty Intellect", "=ds=#p4#" }, 
    };
      
    Thorium4 ={
        { 20040, "INV_Scroll_03", "=q1=Plans: Dark Iron Boots", "=ds=#p2#" },    
        { 19210, "INV_Scroll_03", "=q1=Plans: Ebon Hand", "=ds=#p2#" },  
        { 19211, "INV_Scroll_03", "=q1=Plans: Blackguard", "=ds=#p2#" }, 
        { 19212, "INV_Scroll_03", "=q1=Plans: Nightfall", "=ds=#p2#" },
        }; 
          
    Cenarion1 = {
        { 22772, "INV_Scroll_03", "=q1=Pattern: Sylvan Shoulders", "=ds=#p8#" },
        { 22769, "INV_Scroll_03", "=q1=Pattern: Bramblewood Belt", "=ds=#p7#" },
        { 20506, "INV_Scroll_03", "=q1=Pattern: Spitfire Bracers", "=ds=#p7#" },
        { 20509, "INV_Scroll_03", "=q1=Pattern: Sandstalker Bracers", "=ds=#p7#" },
        { 22768, "INV_Scroll_03", "=q1=Plans: Ironvine Belt", "=ds=#p2#" },
        { 22209, "INV_Scroll_03", "=q1=Plans: Heavy Obsidian Belt", "=ds=#p2#" },
        { 22310, "INV_Scroll_03", "=q1=Pattern: Cenarion Herb Bag", "=ds=#p8#" },
        { 20732, "INV_Misc_Note_01", "=q1=Formula: Enchant Cloak - Greater Fire Resistance", "=ds=#p4#" },
    };
    
    Cenarion2 = {
        { 22773, "INV_Scroll_03", "=q1=Pattern: Sylvan Crown", "=ds=#p8#" },
        { 22770, "INV_Scroll_03", "=q1=Pattern: Bramblewood Boots", "=ds=#p7#" },
        { 20507, "INV_Scroll_03", "=q1=Pattern: Spitfire Gauntlets", "=ds=#p7#" },
        { 20510, "INV_Scroll_03", "=q1=Pattern: Sandstalker Gauntlets", "=ds=#p7#" }, 
        { 22767, "INV_Scroll_03", "=q1=Plans: Ironvine Gloves", "=ds=#p2#" },
        { 22214, "INV_Scroll_03", "=q1=Plans: Light Obsidian Belt", "=ds=#p2#" },
        { 20733, "INV_Misc_Note_01", "=q1=Formula: Enchant Cloak - Greater Nature Resistance", "=ds=#p4#" },
    };
    
    Cenarion3 = {
        { 22683, "INV_Scroll_03", "=q1=Pattern: Gaea's Embrace", "=ds=#p8#" },
        { 22774, "INV_Scroll_03", "=q1=Pattern: Sylvan Vest", "=ds=#p8#" },
        { 22771, "INV_Scroll_03", "=q1=Pattern: Bramblewood Helm", "=ds=#p7#" },
        { 20508, "INV_Scroll_03", "=q1=Pattern: Spitfire Breastplate", "=ds=#p7#" },
        { 20511, "INV_Scroll_03", "=q1=Pattern: Sandstalker Breastplate", "=ds=#p7#" },
        { 22766, "INV_Scroll_03", "=q1=Plans: Ironvine Breastplate", "=ds=#p2#" },
        { 22219, "INV_Scroll_03", "=q1=Plans: Jagged Obsidian Shield", "=ds=#p2#" },
        { 22312, "INV_Scroll_03", "=q1=Pattern: Satchel of Cenarius", "=ds=#p8#" },
        };
        
    Cenarion4 = {
        { 20382, "INV_Scroll_03", "=q1=Pattern: Dreamscale Breastplate", "=ds=#p9# #p7#" },        
        };   
         
    Darkmoon = {
        { 19288, "INV_Misc_Ticket_Tarot_BlueDragon_01", "=q4=Darkmoon Card: Blue Dragon", "=ds=#s14#"},
        { 19289, "INV_Misc_Ticket_Tarot_Maelstrom_01", "=q4=Darkmoon Card: Maelstrom", "=ds=#s14#"},
        { 19287, "INV_Misc_Ticket_Tarot_Heroism_01", "=q4=Darkmoon Card: Heroism", "=ds=#s14#"},
        { 19290, "INV_Misc_Ticket_Tarot_TwistingNether_01", "=q4=Darkmoon Card: Twisting Nether", "=ds=#s14#"}, 
        { 19491, "INV_Jewelry_Necklace_14", "=q4=Amulet of the Darkmoon", "=ds=#s2#"},   
        { 19426, "INV_Jewelry_Necklace_16", "=q4=Orb of the Darkmoon", "=ds=#s2#"},                 
        };
        
    Zandalar1 = {
        { 19766, "INV_Scroll_03", "=q1=Pattern: Bloodvine Boots", "=ds=#p8#" },
        { 19771, "INV_Scroll_03", "=q1=Pattern: Primal Batskin Bracers", "=ds=#p7#" },
        { 20001, "INV_Scroll_03", "=q1=Schematic: Bloodvine Lens", "=ds=#p5#" },
        { 19778, "INV_Scroll_03", "=q1=Plans: Bloodsoul Gauntlets", "=ds=#p2#" },
        { 19781, "INV_Scroll_03", "=q1=Plans: Darksoul Shoulders", "=ds=#p2#" },
        { 20012, "INV_Scroll_03", "=q1=Recipe: Greater Dreamless Sleep", "=ds=#p1#" },
        { 20757, "INV_Misc_Note_01", "=q1=Formula: Brilliant Mana Oil", "=ds=#p4#" },
        };
        
    Zandalar2 = {
        { 19765, "INV_Scroll_03", "=q1=Pattern: Bloodvine Leggings", "=ds=#p8#" },
        { 20000, "INV_Scroll_03", "=q1=Schematic: Bloodvine Goggles", "=ds=#p5#" },
        { 19770, "INV_Scroll_03", "=q1=Pattern: Primal Batskin Gloves", "=ds=#p7#" },
        { 19773, "INV_Scroll_03", "=q1=Pattern: Blood Tiger Shoulders", "=ds=#p7#" },
        { 19777, "INV_Scroll_03", "=q1=Plans: Bloodsoul Shoulders", "=ds=#p2#" },
        { 19780, "INV_Scroll_03", "=q1=Plans: Darksoul Leggings", "=ds=#p2#" },
        { 20014, "INV_Scroll_03", "=q1=Recipe: Major Troll's Blood Potion", "=ds=#p1#" },
        { 20756, "INV_Misc_Note_01", "=q1=Formula: Brilliant Wizard Oil", "=ds=#p4#" },
        { 20031, "INV_Misc_Food_42", "=q1=Essence Mango", "=ds=#e2#" },
        };
        
    Zandalar3 = {
        { 19764, "INV_Scroll_03", "=q1=Pattern: Bloodvine Vest", "=ds=#p8#" },
        { 19769, "INV_Scroll_03", "=q1=Pattern: Primal Batskin Jerkin", "=ds=#p7#" },
        { 19772, "INV_Scroll_03", "=q1=Pattern: Blood Tiger Breastplate", "=ds=#p7#" },
        { 19776, "INV_Scroll_03", "=q1=Plans: Bloodsoul Breastplate", "=ds=#p2#" },
        { 19779, "INV_Scroll_03", "=q1=Plans: Darksoul Breastplate", "=ds=#p2#" },
        { 20011, "INV_Scroll_03", "=q1=Recipe: Mageblood Potion", "=ds=#p1#" },
        { 20080, "INV_Potion_29", "=q2=Sheen of Zanza", "=ds=#e1#" },
        { 20079, "INV_Potion_30", "=q2=Spirit of Zanza", "=ds=#e1#" },
        { 20081, "INV_Potion_31", "=q2=Swiftness of Zanza", "=ds=#e1#" },
        };
        
    Zandalar4 = {
        { 20013, "INV_Scroll_03", "=q1=Recipe: Living Action Potion", "=ds=#p1#" },
        { 20077, "INV_Misc_ArmorKit_08", "=q3=Zandalar Signet of Might", "=ds=#s3# #e11#" },
        { 20076, "INV_Jewelry_Ring_46", "=q3=Zandalar Signet of Mojo", "=ds=#s3# #e11#" },
        { 20078, "Spell_Holy_PowerWordShield", "=q3=Zandalar Signet of Serenity", "=ds=#s3# #e11#" },
        };
        
    CExpedition1 = {
        { 0, "INV_Misc_Ammo_Arrow_02", "=q6=#r2#", "" },
        { 25737, "INV_Scroll_05", "=q3=Pattern: Heavy Clefthoof Boots", "=ds=#p7#" },
        { 23814, "INV_Scroll_03", "=q1=Schematic: Green Smoke Flare", "=ds=#p5#" },
        { 24315, "INV_Scroll_03", "=q1=Pattern: Heavy Netherweave Net", "=ds=#p8#" },
        { 24429, "INV_Enchant_EssenceAstralSmall", "=q1=Expedition Flare", "" },
        { 0, "INV_Misc_Ammo_Arrow_02", "=q6=#r3#", "" },
        { 25838, "INV_Chest_Leather_08", "=q3=Warden's Hauberk", "=ds=#a2# #s5#" },
        { 25835, "INV_Staff_31", "=q3=Explorer's Walking Stick", "=ds=#w9#" },
        { 25836, "INV_Mace_11", "=q3=Preserver's Cudgel", "=ds=#h3# #w6#" },
        { 24183, "INV_Scroll_05", "=q3=Design: Nightseye Panther", "=ds=#p12#" },
        { 25735, "INV_Scroll_05", "=q3=Pattern: Heavy Clefthoof Vest", "=ds=#p7#" },
        { 25736, "INV_Scroll_05", "=q3=Pattern: Heavy Clefthoof Leggings", "=ds=#p7#" },
        { 24417, "INV_Misc_Ammo_Arrow_05", "=q2=Scout's Arrow", "=ds=#e5#" },
        { 23618, "INV_Scroll_03", "=q1=Plans: Adamantite Sharpening Stone", "=ds=#p2#" },
        { 28632, "INV_Scroll_03", "=q1=Plans: Adamantite Weightstone", "=ds=#p2#" },
        { 0, "INV_Misc_Ammo_Arrow_02", "=q6=#r4#", "" },
        { 24412, "INV_Misc_Ammo_Arrow_02", "=q3=Warden's Arrow", "=ds=#e5#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Ammo_Arrow_02", "=q6=#r5#", "" },
        { 22922, "INV_Scroll_06", "=q1=Recipe: Major Nature Protection Potion", "=ds=#p1#" },
        };
        
    Sporeggar1 = {
        { 0, "INV_Mushroom_10", "=q6=#r2#", "" },
        { 25548, "INV_Mushroom_10", "=q1=Tallstalk Mushroom", "=ds=#e2#" },
        { 0, "", "", "" },
        { 0, "INV_Mushroom_10", "=q6=#r3#", "" },
        { 25827, "INV_Misc_Cape_17", "=q3=Muck-Covered Drape", "=ds=#s4#" },
        { 25828, "INV_Shield_21", "=q3=Petrified Lichen Guard", "=ds=#w8#" },
        { 25550, "INV_Mushroom_07", "=q1=Redcap Toadstool", "=ds=#e2#" },
        { 0, "", "", "" },
        { 0, "INV_Mushroom_10", "=q6=#r4#", "" },
        { 22916, "INV_Scroll_06", "=q2=Recipe: Transmute Primal Earth to Water", "=ds=#p1#" },
        { 0, "", "", "" },
        { 0, "INV_Mushroom_10", "=q6=#r5#", "" },
        { 22906, "INV_Scroll_06", "=q2=Recipe: Shrouding Potion", "=ds=#p1#" },
        };
        
    Kurenai1 = {
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r2#", "" },
        { 29217, "INV_Scroll_05", "=q3=Netherfury Belt", "=ds=#p7#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r3#", "" },
        { 29219, "INV_Scroll_05", "=q3=Netherfury Leggings", "=ds=#p7#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r4#", "" },
        { 29218, "INV_Scroll_05", "=q3=Netherfury Boots", "=ds=#p7#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r5#", "" },
        { 29227, "INV_Misc_Foot_Centaur", "=q4=Reins of the Cobalt Riding Talbuk", "=ds=#e7#" },
        { 29228, "INV_Misc_Foot_Centaur", "=q4=Reins of the Dark Riding Talbuk", "=ds=#e7#" },
        { 29229, "INV_Misc_Foot_Centaur", "=q4=Reins of the Silver Riding Talbuk", "=ds=#e7#" },
        { 29230, "INV_Misc_Foot_Centaur", "=q4=Reins of the Tan Riding Talbuk", "=ds=#e7#" },
        { 29231, "INV_Misc_Foot_Centaur", "=q4=Reins of the White Riding Talbuk", "=ds=#e7#" },
        };
        
    Scryer1 = {
        { 0, "Spell_Holy_ChampionsBond", "=q6=#r2#", "" },
        { 23133, "INV_Scroll_06", "=q2=Design: Runed Blood Garnet", "=ds=#p12#" },
        { 0, "", "", "" },
        { 0, "Spell_Holy_ChampionsBond", "=q6=#r3#", "" },
        { 28907, "Ability_DualWield", "=q2=Inscription of the Blade", "=ds=#s3# #e11#" },
        { 28908, "Spell_Holy_ChampionsBond", "=q2=Inscription of the Knight", "=ds=#s3# #e11#" },
        { 28904, "Spell_Holy_SpiritualGuidence", "=q2=Inscription of the Oracle", "=ds=#s3# #e11#" },
        { 28903, "INV_Misc_Orb_04", "=q2=Inscription of the Orb", "=ds=#s3# #e11#" },
        { 23143, "INV_Scroll_06", "=q2=Design: Dazzling Deep Peridot", "=ds=#p12#" },
        { 24293, "INV_Scroll_03", "=q1=Pattern: Silver Spellthread", "=ds=#p8#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "Spell_Holy_ChampionsBond", "=q6=#r4#", "" },
        { 29131, "INV_Pants_Leather_18", "=q3=Retainer's Leggings", "=ds=#a2# #s11#" },
        { 29134, "INV_Gauntlets_26", "=q3=Gauntlets of the Chosen", "=ds=#a4# #s9#" },
        { 29132, "INV_Misc_Gem_Bloodstone_02", "=q3=Scryer's Bloodgem", "=ds=#s14#" },
        { 29133, "INV_Staff_38", "=q3=Seer's Cane", "=ds=#w9#" },
        { 24176, "INV_Scroll_05", "=q3=Design: Pendant of Withering", "=ds=#p12#" },
        { 25722, "INV_Scroll_03", "=q1=Pattern: Magister's Armor Kit", "=ds=#p8#" },
        { 0, "Spell_Holy_ChampionsBond", "=q6=#r5#", "" },
        { 29126, "INV_Jewelry_Ring_52Naxxramas", "=q4=Seer's Signet", "=ds=#s13#" },
        { 29125, "INV_Weapon_Shortblade_29", "=q4=Retainer's Blade", "=ds=#h1# #w4#" },
        { 28910, "Spell_Holy_WeaponMastery", "=q3=Greater Inscription of the Blade", "=ds=#s3# #e11#" },
        { 28911, "Spell_Holy_ChampionsGrace", "=q3=Greater Inscription of the Knight", "=ds=#s3# #e11#" },
        { 28912, "Spell_Holy_PowerInfusion", "=q3=Greater Inscription of the Oracle", "=ds=#s3# #e11#" },
        { 28909, "INV_Misc_Orb_03", "=q3=Greater Inscription of the Orb", "=ds=#s3# #e11#" },
        { 24295, "INV_Scroll_03", "=q1=Pattern: Golden Spellthread", "=ds=#p8#" },
        };

    Aldor1 = {
        { 0, "Spell_Holy_SealOfSalvation", "=q6=#r2#", "" },
        { 23149, "INV_Scroll_06", "=q2=Design: Gleaming Golden Draenite", "=ds=#p12#" },
        { 0, "", "", "" },
        { 0, "Spell_Holy_SealOfSalvation", "=q6=#r3#", "" },
        { 29129, "INV_Chest_Cloth_19", "=q3=Anchorite's Robes", "=ds=#a1# #s5#" },
        { 28881, "Spell_Holy_SealOfWisdom", "=q2=Inscription of Discipline", "=ds=#s3# #e11#" },
        { 28878, "Spell_Holy_SealOfSalvation", "=q2=Inscription of Faith", "=ds=#s3# #e11#" },
        { 28885, "Spell_Holy_FistOfJustice", "=q2=Inscription of Vengence", "=ds=#s3# #e11#" },
        { 28882, "Spell_Holy_GreaterBlessingofSanctuary", "=q2=Inscription of Warding", "=ds=#s3# #e11#" },
        { 23145, "INV_Scroll_06", "=q2=Design: Royal Shadow Draenite", "=ds=#p12#" },
        { 24292, "INV_Scroll_03", "=q1=Pattern: Mystic Spellthread", "=ds=#p8#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "Spell_Holy_SealOfSalvation", "=q6=#r4#", "" },
        { 29127, "INV_Chest_Plate02", "=q3=Vindicator's Hauberk", "=ds=#a4# #s5#" },
        { 29128, "INV_Jewelry_Ring_48Naxxramas", "=q3=Lightwarden's Band", "=ds=#s13#" },
        { 29130, "INV_Staff_14", "=q3=Auchenai Staff", "=ds=#w9#" },
        { 24177, "INV_Scroll_05", "=q3=Design: Pendant of Shadow's End", "=ds=#p12#" },
        { 22908, "INV_Scroll_06", "=q2=Recipe: Elixir of Major Firepower", "=ds=#p1#" },
        { 25721, "INV_Scroll_03", "=q1=Pattern: Vindicator's Armor Kit", "=ds=#p8#" },
        { 0, "Spell_Holy_SealOfSalvation", "=q6=#r5#", "" },
        { 29123, "INV_Jewelry_Amulet_04", "=q4=Medallion of the Lightbearer", "=ds=#s2#" },
        { 29124, "INV_Sword_Draenei_01", "=q4=Vindicator's Brand", "=ds=#h1# #w10#" },
        { 28886, "Spell_Holy_SealOfWisdom", "=q3=Greater Inscription of Discipline", "=ds=#s3# #e11#" },
        { 28887, "Spell_Holy_GreaterBlessingofSalvation", "=q3=Greater Inscription of Faith", "=ds=#s3# #e11#" },
        { 28888, "Spell_Holy_GreaterBlessingofKings", "=q3=Greater Inscription of Vengence", "=ds=#s3# #e11#" },
        { 28889, "Spell_Holy_BlessingOfProtection", "=q3=Greater Inscription of Warding", "=ds=#s3# #e11#" },
        { 24294, "INV_Scroll_03", "=q1=Pattern: Runic Spellthread", "=ds=#p8#" },
        };

    HonorHold1 = {
        { 0, "INV_BannerPVP_02", "=q6=#r2#", "" },
        { 29213, "INV_Scroll_05", "=q3=Pattern: Felstalker Belt", "=ds=#p7#" },
        { 22531, "INV_Misc_Note_01", "=q1=Formula: Enchant Bracer - Superior Healing", "=ds=#p4#" },
        { 24007, "INV_Drink_Waterskin_05", "=q1=Footman's Waterskin", "=ds=#e3#" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#r3#", "" },
        { 25826, "INV_Jewelry_Ring_11", "=q3=Sage's Band", "=ds=#s13#" },
        { 25825, "INV_Sword_20", "=q3=Footman's Longsword", "=ds=#h1# #w10#" },
        { 29214, "INV_Scroll_05", "=q3=Pattern: Felstalker Bracers", "=ds=#p7#" },
        { 29215, "INV_Scroll_05", "=q3=Pattern: Felstalker Breastplate", "=ds=#p7#" },
        { 22905, "INV_Scroll_03", "=q1=Recipe: Elixir of Major Agility", "=ds=#p1#" },
        { 25870, "INV_Scroll_03", "=q1=Recipe: Transmute Skyfire Diamond", "=ds=#p1#" },
        { 24008, "INV_Mushroom_01", "=q1=Dried Mushroom Rations", "=ds=#e2#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#r4#", "" },
        { 22547, "INV_Misc_Note_01", "=q1=Formula: Enchant Chest - Exceptional Stats", "=ds=#p4#" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_02", "=q6=#r5#", "" },
        { 23619, "INV_Scroll_03", "=q1=Plans: Felsteel Shield Spike", "=ds=#p2#" },
        { 23999, "INV_Shirt_GuildTabard_01", "=q1=Honor Hold Tabard", "=ds=#s7#" },
        };

    Thrallmar1 = {
        { 0, "INV_BannerPVP_01", "=q6=#r2#", "" },
        { 29213, "INV_Scroll_05", "=q3=Pattern: Felstalker Belt", "=ds=#p7#" },
        { 22531, "INV_Misc_Note_01", "=q1=Formula: Enchant Bracer - Superior Healing", "=ds=#p4#" },
        { 24006, "INV_Drink_Waterskin_05", "=q1=Grunt's Waterskin", "=ds=#e3#" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#r3#", "" },
        { 25824, "INV_Jewelry_Ring_11", "=q3=Farseer's Band", "=ds=#s13#" },
        { 25823, "INV_Sword_20", "=q3=Grunt's Waraxe", "=ds=#h1# #w1#" },
        { 29214, "INV_Scroll_05", "=q3=Pattern: Felstalker Bracers", "=ds=#p7#" },
        { 29215, "INV_Scroll_05", "=q3=Pattern: Felstalker Breastplate", "=ds=#p7#" },
        { 22905, "INV_Scroll_03", "=q1=Recipe: Elixir of Major Agility", "=ds=#p1#" },
        { 25870, "INV_Scroll_03", "=q1=Recipe: Transmute Skyfire Diamond", "=ds=#p1#" },
        { 24009, "INV_Mushroom_01", "=q1=Dried Fruit Rations", "=ds=#e2#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#r4#", "" },
        { 22547, "INV_Misc_Note_01", "=q1=Formula: Enchant Chest - Exceptional Stats", "=ds=#p4#" },
        { 0, "", "", "" },
        { 0, "INV_BannerPVP_01", "=q6=#r5#", "" },
        { 23619, "INV_Scroll_03", "=q1=Plans: Felsteel Shield Spike", "=ds=#p2#" },
        { 24004, "INV_Shirt_GuildTabard_01", "=q1=Thrallmar Tabard", "=ds=#s7#" },
        }; 

    Tranquillien1 = {
        { 0, "INV_Misc_Bandana_03", "=q6=#r2#", "" },
        { 22991, "INV_Boots_Cloth_05", "=q2=Apprentice Boots", "=ds=#a1# #s12#" },
        { 22992, "INV_Boots_04", "=q2=Bogwalker Boots", "=ds=#a2# #s12#" },
        { 22993, "INV_Boots_01", "=q2=Volunteer's Greaves", "=ds=#a3# #s12#" },
        { 28164, "INV_Sword_07", "=q2=Tranquillien Flamberge", "=ds=#h2# #w10#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Bandana_03", "=q6=#r3#", "" },
        { 28155, "INV_Misc_Bandana_03", "=q2=Apothecary's Waistband", "=ds=#a1# #s10#" },
        { 28158, "INV_Belt_09", "=q2=Batskin Belt", "=ds=#a2# #s10#" },
        { 28162, "INV_Belt_03", "=q2=Tranquillien Defender's Girdle", "=ds=#a3# #s10#" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Bandana_03", "=q6=#r4#", "" },
        { 22986, "INV_Chest_Cloth_19", "=q2=Apothecary's Robe", "=ds=#a1# #s5#" },
        { 22987, "INV_Chest_Leather_01", "=q2=Deathstalker's Vest", "=ds=#a2# #s5#" },
        { 22985, "INV_Chest_Chain", "=q2=Suncrown Hauberk", "=ds=#a3# #s5#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Bandana_03", "=q6=#r5#", "" },
        { 22990, "INV_Misc_Cape_07", "=q3=Tranquillien Champion's Cloak", "=ds=#s4#" },
        };

    Maghar1 = {
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r2#", "" },
        { 29217, "INV_Scroll_05", "=q3=Netherfury Belt", "=ds=#p7#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r3#", "" },
        { 29219, "INV_Scroll_05", "=q3=Netherfury Leggings", "=ds=#p7#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r4#", "" },
        { 29218, "INV_Scroll_05", "=q3=Netherfury Boots", "=ds=#p7#" },
        { 0, "", "", "" },
        { 0, "INV_Misc_Foot_Centaur", "=q6=#r5#", "" },
        { 29227, "INV_Misc_Foot_Centaur", "=q4=Reins of the Cobalt Riding Talbuk", "=ds=#e7#" },
        { 29228, "INV_Misc_Foot_Centaur", "=q4=Reins of the Dark Riding Talbuk", "=ds=#e7#" },
        { 29229, "INV_Misc_Foot_Centaur", "=q4=Reins of the Silver Riding Talbuk", "=ds=#e7#" },
        { 29230, "INV_Misc_Foot_Centaur", "=q4=Reins of the Tan Riding Talbuk", "=ds=#e7#" },
        { 29231, "INV_Misc_Foot_Centaur", "=q4=Reins of the White Riding Talbuk", "=ds=#e7#" },
        };        
    };