local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("frFR", function() return {
	["Keeps track of your reagents for buffing."] = "Compte vos r\195\169actifs pour les am\195\169liorations.",
	
	["Show short names"] = "Montrez les noms courts ",
	["Show short reagent names in FuBar text"] = "Montrer les noms courts de r\195\169actif en texte de FuBar",
	["Reagents"] = "R\195\169actifs",
	
	-- reagents
	--mage	
	["Arcane Powder"] = "Poudre des arcanes",
	["Arcane Powder.SHORT"] = "Poudre: ",
	["Rune of Teleportation"] = "Rune de t\195\169l\195\169portation",
	["Rune of Teleportation.SHORT"] = "T\195\169l\195\169portation: ",
	["Rune of Portals"] = "Rune des portails",
	["Rune of Portals.SHORT"] = "Portail: ",
	["Light Feather"] = "Plume l\195\169g\195\168re",
	["Light Feather.SHORT"] = "Plume: ",
	--priest
	["Holy Candle"] = "Bougie sanctifi\195\169e",
	["Holy Candle.SHORT"] = "Sanctifi\195\169e: ",
	["Sacred Candle"] = "Bougie sacr\195\169e",
	["Sacred Candle.SHORT"] = "Sacr\195\169e: ",
	-- rogue
	["Flash Powder"] = "Poudre \195\169clipsante",
	["Flash Powder.SHORT"] = "\195\169clipsante: ",
	["Blinding Powder"] = "Poudre aveuglante",
	["Blinding Powder.SHORT"] = "Aveuglante: ",
	["Thistle Tea"] = "Th\195\169 de chardon",
	["Thistle Tea.SHORT"] = "Chardon: ",
	["Instant Poison"] = "Poison instantan\195\169",
	["Deadly Poison"] = "Poison mortel",
	["Crippling Poison"] = "Poison affaiblissant",
	["Mind-numbing Poison"] = "Poison de distraction mentale",
	["Wound Poison"] = "Poison douloureux",
	["Poison: "] = "Poison: ",
	--druid
	["Wild Berries"] = "Baie sauvage",
	["Wild Berries.SHORT"] = "Baie: ",
	["Wild Thornroot"] = "Ronceterre sauvage",
	["Wild Thornroot.SHORT"] = "Ronceterre: ",
	["Maple Seed"] = "Graine d'\195\169rable",
	["Maple Seed.SHORT"] = "\195\137rable: ",
	["Stranglethorn Seed"] = "Graine de strangleronce",
	["Stranglethorn Seed.SHORT"] = "Strangleronce: ",
	["Ashwood Seed"] = "Graine de fr\195\170ne",
	["Ashwood Seed.SHORT"] = "Fr\195\170ne: ",
	["Hornbeam Seed"] = "Graine de charme",
	["Hornbeam Seed.SHORT"] = "Charme: ",
	["Ironwood Seed"] = "Graine de bois de fer",
	["Ironwood Seed.SHORT"] = "Bois de fer: ",
	-- Paladin
	["Symbol of Divinity"] = "Symbole de divinit\195\169",
	["Symbol of Divinity.SHORT"] = "Divinit\195\169: ",
	["Symbol of Kings"] = "Symbole des rois",
	["Symbol of Kings.SHORT"] = "Rois: ",
	-- Shaman
	["Ankh"] = "Ankh",
	["Ankh.SHORT"] = "Ankh: ",
	["Shiny Fish Scales"] = "Ecailles de poisson brillantes",
	["Shiny Fish Scales.SHORT"] = "Ecailles: ",
	["Fish Oil"] = "Huile de poisson",
	["Fish Oil.SHORT"] = "Huile: ",
	-- warlock
	["Soul Shard"] = "Fragment d'\195\162me",
	["Soul Shard.SHORT"] = "Fragment: ",
	["Healthstone"] = "Pierre de soins",
	["Healthstone.SHORT"] = "Soins: ",
	["Soulstone"] = "Pierre d'\195\162me",
	["Soulstone.SHORT"] = "\195\162me: ",
	["Spellstone"] = "Pierre de sort",
	["Spellstone.SHORT"] = "Sort: ",
	["Firestone"] = "Pierre de feu",
	["Firestone.SHORT"] = "Feu: ",
	["Infernal Stone"] = "Pierre infernale",
	["Infernal Stone.SHORT"] = "Infernal: ",
} end)