local L = AceLibrary("AceLocale-2.2"):new("ReagentFu");

L:RegisterTranslations("koKR", function() return {
	["Keeps track of your reagents for buffing."] = "소모성 재료의 수량을 표시합니다.",
	
	["Show short names"] = "짧은 이름 보기",
	["Show short reagent names in FuBar text"] = "FuBar 텍스트로 재료의 짧은 이름을 표시합니다",
	["Reagents"] = "재료",
	
	-- reagents
	--mage	
	["Arcane Powder"] = "불가사의한 가루",
	["Arcane Powder.SHORT"] = "가루: ",
	["Rune of Teleportation"] = "순간이동의 룬",
	["Rune of Teleportation.SHORT"] = "순간: ",
	["Rune of Portals"] = "차원이동의 룬",
	["Rune of Portals.SHORT"] = "차원: ",
	["Light Feather"] = "가벼운 깃털",
	["Light Feather.SHORT"] = "깃털: ",
	--priest
	["Holy Candle"] = "신성한 양초",
	["Holy Candle.SHORT"] = "신성: ",
	["Sacred Candle"] = "성스러운 양초",
	["Sacred Candle.SHORT"] = "성: ",
	-- rogue
	["Flash Powder"] = "섬광 화약",
	["Flash Powder.SHORT"] = "섬광: ",
	["Blinding Powder"] = "실명 가루",
	["Blinding Powder.SHORT"] = "실명: ",
	["Thistle Tea"] = "엉겅퀴 차",
	["Thistle Tea.SHORT"] = "엉겅퀴: ",
	["Instant Poison"] = "순간 효과 독",
	["Deadly Poison"] = "맹독",
	["Crippling Poison"] = "신경 마비 독",
	["Mind-numbing Poison"] = "정신 마비 독",
	["Wound Poison"] = "상처 감염 독",
	["Poison: "] = "독: ",
	--druid
	["Wild Berries"] = "야생 가지",
	["Wild Berries.SHORT"] = "가지: ",
	["Wild Thornroot"] = "야생 가시뿌리",
	["Wild Thornroot.SHORT"] = "뿌리: ",
	["Maple Seed"] = "단풍나무 씨앗",
	["Maple Seed.SHORT"] = "단풍: ",
	["Stranglethorn Seed"] = "가시덩굴 씨앗",
	["Stranglethorn Seed.SHORT"] = "가시: ",
	["Ashwood Seed"] = "잿빛나무 씨앗",
	["Ashwood Seed.SHORT"] = "잿빛: ",
	["Hornbeam Seed"] = "자작나무 씨앗",
	["Hornbeam Seed.SHORT"] = "자작: ",
	["Ironwood Seed"] = "강철나무 씨앗",
	["Ironwood Seed.SHORT"] = "강철: ",
	-- Paladin
	["Symbol of Divinity"] = "신앙의 징표",
	["Symbol of Divinity.SHORT"] = "신앙: ",
	["Symbol of Kings"] = "왕의 징표",
	["Symbol of Kings.SHORT"] = "왕: ",
	-- Shaman
	["Ankh"] = "십자가",
	["Ankh.SHORT"] = "십자가: ",
	["Shiny Fish Scales"] = "반짝이는 물고기 비늘",
	["Shiny Fish Scales.SHORT"] = "비늘: ",
	["Fish Oil"] = "물고기 오일",
	["Fish Oil.SHORT"] = "오일: ",
	-- warlock
	["Soul Shard"] = "영혼의 조각",
	["Soul Shard.SHORT"] = "조각: ",
	["Healthstone"] = "생명석",
	["Healthstone.SHORT"] = "생석: ",
	["Soulstone"] = "영혼석",
	["Soulstone.SHORT"] = "영석: ",
	["Spellstone"] = "주문석",
	["Spellstone.SHORT"] = "주문: ",
	["Firestone"] = "화염석",
	["Firestone.SHORT"] = "화염: ",
	["Infernal Stone"] = "Infernal Stone",
	["Infernal Stone.SHORT"] = "Infernal: ",
} end)