--English localization 
-- English by Visionary and Graguk
--Udapte 07/19/2005

-- Localization Strings

ServitudeProp = {};
ServitudeProp.Version = 060519.0;
ServitudeProp.Author = "Graguk";
ServitudeProp.AppName = "Servitude";
ServitudeProp.Label = ServitudeProp.AppName .. " (v" .. ServitudeProp.Version .. ")";
ServitudeProp.LongLabel = ServitudeProp.Label .. " by " .. ServitudeProp.Author;
ServitudeProp.CleanLabel = ServitudeProp.AppName .. " by " .. ServitudeProp.Author;
ServitudeProp.Description = "A warlock pet addon that manages and autocasts your pet skills";

ServitudeConfigMenuTitle = ServitudeProp.Label;

VoidwalkerOptions = "Voidwalker Options";
ImpOptions = "Imp Options";
SuccubusOptions = "Succubus Options";
FelhunterOptions = "Felhunter Options";
GeneralOptions = "General Options";

InCombatDivider = "=== In/Out Combat Line ===";
SpellLockDivider = "=== Spell Lock ===";
ClassDivider = "=== Class Priority ===";
BuffDatabaseTitle = "Debuff Priority";
SpellDatabaseTitle = "Spell Lock";
ClassDatabaseTitle = "Class Priority";
FireShieldClassDatabaseTitle = "FS Class List";

BINDING_HEADER_SERVITUDE = "Servitude";
BINDING_NAME_DOSERVITUDEOPEN = "Open Servitude Config Panel";
BINDING_NAME_DOPRIMARY = "Cast Primary Pet Spell";
BINDING_NAME_DOSECONDARY = "Cast Secondary Pet Spell";

ConfigObjectText =
{
	VWAutoShadow = "Alert Consume Shadows";
	VWAutoShadowRatio = "Consume Shadows Percent";
	VWAutoSacrif = "Alert Sacrifice";
	VWAutoSacrifCombat = "In Combat Only";
	VWAutoSacrifPetRatio = "Sacrifice Percent for Pet";
	VWAutoSacrifPlayerRatio = "Sacrifice Percent for Player";
	VWSacrificeAlert = "Vocal Sacrifice Alert";

	ImpSmartFireshield = "Smart Fire Shield - Party/Raid";
	ImpSmartFireshieldNeutral = "Disable in Neutral Towns";
	ImpSmartFireshieldSolo = "Smart Fire Shield - Solo";
	ImpSmartFireshieldAlways = "Smart Fire Shield Always";
	ImpFireShieldAlert = "Fire Shield Alert";
	
	ScbAutoInvisib = "Alert Invisibility";
	ScbAutoInvisibManaRatio = "Min Mana for Invis";
	ScbInvisDelay = "Delay Invis post Combat";
--	ScbSeduceFollow = "Follow on Seduce break";
	ScbSeduceCOS = "CoS on Seduce";
	ScbSeduceCOE = "CoE on Seduce";
--	ScbAlwaysSeduce = "Re-Seduce on break";
	ScbSeduceAlert = "Seduction Alert";
	ScbSeduceAnnounce = "Report Seduce Party";
	ScbSeduceAnnounceRaid = "Report Seduce Raid";

	FHNonCombatDevour = "Alert Non-Combat Devour";
	FHHungerDevour = "Hungry Felhunter";
	FHHungerDevourRatio = "Hunger Percent";
	FHPartyDevour = "Party Devour";
	FHDevourSelf = "Felhunter First";
	FHDevourPets = "Raid/Party Pets";
	FHDevourIgnoreSelf = "Ignore Felhunter";
	FHRaidDevour = "Raid Devour";
	FHDevourMindVision = "Devour Mind Vision";
	FHSpellLockPVP = "Spell Lock PVP";
	FHSpellLockPVE = "Spell Lock PVE";
	FHDisableNotification = "Disable Spell/Debuff Notification";
	FHClassAsPriority = "Devour by Class";
	FHPriorityUnitOnly = "Only Devour Priority Unit";
	FHDevourAlert = "Devour Magic Alert";
	FHSpellLockAlert = "Spell Lock Alert";
	
	OneButton = "One Button Pets";
	HealthWarning = "Pet Health Warning";
	HealthWarningRatio = "Pet Health Percentage";
	HealthWarningVocal = "Vocal Health Warning";
}

ConfigObjectTooltip =
{
	VWAutoShadow = "Alert player after battle if the Voidwalker's HP is below a specified percentage to cast Consume Shadows.";
	VWAutoSacrif = "Alert the player to Sacrifice the Voidwalker during battle if his or the player's HP drops below a specified percentage. (Note: Will not trigger if massive amount of damage is taken in short duration)";
	VWAutoSacrifCombat = "Sacrifice alert will only trigger if in combat.";
	VWSacrificeAlert = "When the player or Voidwalker's health drops below the configured percent, a vocal alert will be played.";
	
	ImpSmartFireshield = "Imp will cast Fire Shield on tanking classes if in a Party/Raid.";
	ImpSmartFireshieldNeutral = "Imp will not Fire Shield when in Neutral cities. It will also cancel Fire Shield on the player in these locations.";
	ImpSmartFireshieldSolo = "Imp will cast Fire Shield on the Warlock if not in a Party/Raid.";
	ImpSmartFireshieldAlways = "Imp will cast Fire Shield on all party members if they are in range, regardless of Class.";
	ImpFireShieldAlert = "When the Imp detects a unit that needs a Fire Shield based on your configuration, a vocal alert will be played.";
	
	ScbAutoInvisib = "Alert the player if the Succubus can cast Lesser Invisibility after battle if she has no debuff. Minimum Succubus Mana Slider for those who use Dark Pact.";
	ScbInvisDelay = "If checked, the Succubus will wait 10 seconds after combat finishes before Alerting the player that Invisibility is available - this allows for Dark Pact time.";
--	ScbSeduceFollow = "Succubus will follow the player after the target of seduction has been damaged, instead of attacking it.";
--	ScbAlwaysSeduce = "Succubus will re-seduce even when the target is damaged. This option will override the Follow on Seduce Break option.";
	ScbSeduceAlert = "When the Succubus detects that Seduction has faded or been broken from an enemy, a vocal alert will be played.";
	ScbSeduceCOS = "When enabled, the player will cast Curse of Shadow on a target at the same time as commanding the Succubus to Seduce for the first time.";
	ScbSeduceCOE = "When enabled, the player will cast Curse of the Elements on a target at the same time as commanding the Succubus to Seduce for the first time. CoS on Seduce takes priority if enabled.";
	ScbSeduceAnnounce = "When enabled, the player will announce the initial seduction target to Party chat.";
	ScbSeduceAnnounceRaid = "When enabled, the player will announce the initial seduction target to Raid chat.";

	FHNonCombatDevour = "Felhunter will search and devour magical debuffs on himself or the player after battle.";
	FHHungerDevour = "Felhunter will search and devour magical debuffs on himself or the player during combat if his HP drop below a specified percentage.";
	FHPartyDevour = "Party support for Devour features";
	FHDevourSelf = "Devour the Felhunter before all others";
	FHDevourIgnoreSelf = "Never Devour the Felhunter. This option overrides Felhunter First.";
	FHRaidDevour = "Raid support for Devour features";
	FHDevourPets = "If enabled, this will scan raid and party pets if the corresponding Raid/Party scanning option is enabled.";
	FHDevourMindVision = "Mind Vision is often used by friendly players, but shows up as a Debuff. Select this option if you want to devour it anyway.";
	FHSpellLockPVP = "Spell Lock PVP targets if you are PVP flagged.";
	FHSpellLockPVE = "Spell Lock PVE targets. Can get confused if a unit with the same name as your target casts.";
	FHDisableNotification = "This option disables Servitude's notification of learning a new spell or debuff.";
	FHClassAsPriority = "When selected, the Class Priority database will be used to Devour classes in order of preference, rather than whether to ignore that class or not. (more CPU than default)";
	FHPriorityUnitOnly = "Auto-Devour will only scan debuffs on the stored Priority Unit. It will ignore all other raid and party members, including the player and Felhunter.";
	FHDevourAlert = "When the Felhunter detects a unit that needs to be Devoured based on your configuration, a vocal alert will be played.";
	FHSpellLockAlert = "When the Felhunter detects your target starts casting a spell you've told him to Spell Lock, a vocal alert will be played.";
	OneButton = "When enabled, Pet management can be executed with just the Primary Pet Button. The Secondary Pet Button will be used for Seduce/ReSeduce, and Devour Magic on your target.";
	HealthWarning = "When enabled, Servitude will alert you when your pet's health drops below the configured percentage.";
	HealthWarningVocal = "When your pet's health drops below the configured percentage, a vocal alert will be played.";
}

ServitudeChatMsg = 
{
	SoothingKissToggleError = "Soothing Kiss is currently being managed by Servitude. The game's autocast setting will be overwritten during combat.";
	LOPToggleError = "Lash of Pain is currently being managed by Servitude. The game's autocast setting will be overwritten.";
	AutoTauntToggleError = "Taunt is currently being managed by Servitude. The game's autocast setting will be overwritten during combat.";
	ImpSmartFireshieldToggleError = "Fire Shield is currently being managed by Servitude. The game's autocast setting will be overwritten on the next player scan.";
	ImpSmartFireboltToggleError = "Firebolt is currently being managed by Servitude. The game's autocast setting will be overwritten.";
	FHSpellLockToggleError = "Spell Lock is currently being managed by Servitude. The game's autocast setting will be overwritten in combat.";
	LoadDefault = "Loaded default configuration.";
	ObjectLoadFail = "Error! Failed to load object:";
	ObjectSaveFail = "Error! Failed to save object:";
	WelcomeMsg = ServitudeProp.CleanLabel .. " for fellow warlocks (Slash commands: /servitude help or /serv help)";
	NewDebuffObserved = "New magical debuff has been observed:";
	NewSpellObserved = "New Spell has been observed:";
	DebuffDatabaseCorrupted = "Debuff database is corrupted or empty and has been purged. Default Database loaded.";
	SpellDatabaseCorrupted = "Spell Lock database is corrupted or empty. Database cleared.";
	ClassDatabaseCorrupted = "Class Database is corrupted or empty. Default Database loaded.";
	FireShieldClassDatabaseCorrupted = "Fire Shield Class Database is corrupted or empty. Default Database loaded.";
	DebuffDatabaseVerified = "Debuff database entry count:";
	SpellDatabaseVerified = "Spell Lock database entry count:";
	SeductionMessage = " is being Seduced! Avoid the Hearts <3 <3";
}

ServitudeNotificationMsg =
{
	InvisNotification = "Lesser Invisibility";
	SpellLockPVP = "Spell Lock!";
	SpellLockPVE = "Spell Lock!";
	SeductionNotification = "Re-Seduce NOW!";
	Sacrifice = "Sacrifice NOW!";
	ConsumeShadows = "Consume Shadows";
	DebuffsDetected = "Devour NOW!";
	FireShieldRequired = "Fire Shield!";
	ServitudeAlertTest = "This is a test. Move this frame to the area that you can see best.";
	HealthLow = "Your Pet is DYING!";
	Primary = " (Primary)";
	Secondary = " (Secondary)";
}

English_Spell_Lock_Order = {
	[1] = "Arcane Bolt",
	[2] = "Arcane Explosion",
	[3] = "Banish",
	[4] = "Blizzard",
	[5] = "Dominate Mind",
	[6] = "Entangling Roots",
	[7] = "Fear",
	[8] = "Fireball",
	[9] = "Fireball Volley",
	[10] = "Flamestrike",
	[11] = "Flash Heal",
	[12] = "Flash of Light",
	[13] = "Frostbolt",
	[14] = "Greater Heal",
	[15] = "Heal",
	[16] = "Healing Touch",
	[17] = "Healing Wave",
	[18] = "Hibernate",
	[19] = "Holy Light",
	[20] = "Holy Smite",
	[21] = "Howl of Terror",
	[22] = "Immolate",
	[23] = "Mana Burn",
	[24] = "Mind Control",
	[25] = "Polymorph",
	[26] = "Prayer of Healing",
	[27] = "Pyroblast",
	[28] = "Regrowth",
	[29] = "Scorch",
	[30] = "Searing Pain",
	[31] = "Seduction",
	[32] = "Shadow Bolt",
	[33] = "Shadow Bolt Volley",
	[34] = "Silence",
	[35] = "Soul Fire",
	[36] = "Starfire",
	[37] = "Summon Blackhand Dreadweaver",
	[38] = "Summon Blackhand Veteran",
	[39] = "Wrath",
	[40] = "=== Spell Lock ===",
	[41] = "Acid Spit",
	[42] = "Aimed Shot",
	[43] = "Anti-Magic Shield",
	[44] = "Arcane Shot",
	[45] = "Arcane Weakness",
	[46] = "Arygos's Vengeance",
	[47] = "Attack",
	[48] = "Banshee Curse",
	[49] = "Banshee Wail",
	[50] = "Bellowing Roar",
	[51] = "Black Sludge",
	[52] = "Bomb",
	[53] = "Breath",
	[54] = "Buttermilk Delight",
	[55] = "Cannon Fire",
	[56] = "Chain Heal",
	[57] = "Chain Lightning",
	[58] = "Chains of Ice",
	[59] = "Concussive Shot",
	[60] = "Conflagrate",
	[61] = "Conjure Mana Ruby",
	[62] = "Conjure Water",
	[63] = "Corrosive Acid",
	[64] = "Corruption",
	[65] = "Create Healthstone (Greater)",
	[66] = "Create Healthstone (Major)",
	[67] = "Create Shredder",
	[68] = "Cripple",
	[69] = "Crypt Scarabs",
	[70] = "Crystal Gaze",
	[71] = "Cultivate Packet of Seeds",
	[72] = "Curse of Blood",
	[73] = "Curse of the Darkmaster",
	[74] = "Curse of the Firebrand",
	[75] = "Dark Desire",
	[76] = "Dark Mending",
	[77] = "Defibrillate",
	[78] = "Demon Portal",
	[79] = "Dense Dynamite",
	[80] = "Destroy Egg",
	[81] = "Dire Growl",
	[82] = "Diseased Spit",
	[83] = "Domination",
	[84] = "Earthgrab Totem",
	[85] = "Encasing Webs",
	[86] = "Enchanted Quickness",
	[87] = "Enfeeble",
	[88] = "Enslave Demon",
	[89] = "Explosive Shot",
	[90] = "Eye of Immol'thar",
	[91] = "Eyes of the Beast",
	[92] = "Ez-Thro Dynamite",
	[93] = "Faerie Fire",
	[94] = "Fanatic Blade",
	[95] = "Far Sight",
	[96] = "Fiery Burst",
	[97] = "Fire Shield II",
	[98] = "Fire Shield IV",
	[99] = "Fire Storm",
	[100] = "Firebolt",
	[101] = "First Aid",
	[102] = "Flame Breath",
	[103] = "Flame Buffet",
	[104] = "Flame Cannon",
	[105] = "Flamecrack",
	[106] = "Flamespit",
	[107] = "Forked Lightning",
	[108] = "Freeze",
	[109] = "Frost Burn",
	[110] = "Frost Weakness",
	[111] = "Frostbolt Volley",
	[112] = "Furbolg Form",
	[113] = "Gargoyle Strike",
	[114] = "Ghost Wolf",
	[115] = "Goblin Mortar",
	[116] = "Goblin Sapper Charge",
	[117] = "Gordok Green Grog",
	[118] = "Grasping Vines",
	[119] = "Great Heal",
	[120] = "Hammer of Wrath",
	[121] = "Haunting Phantoms",
	[122] = "Healing Circle",
	[123] = "Healing Ward",
	[124] = "Hearthstone",
	[125] = "Heavy Runecloth Bandage",
	[126] = "Hex",
	[127] = "Hi-Explosive Bomb",
	[128] = "Holy Fire",
	[129] = "Holy Wrath",
	[130] = "Honor Points +2388",
	[131] = "Honor Points +398",
	[132] = "Ice Tomb",
	[133] = "Ignite Flesh",
	[134] = "Incinerate",
	[135] = "Inferno",
	[136] = "Iron Grenade",
	[137] = "Lesser Heal",
	[138] = "Lesser Healing Wave",
	[139] = "Lightning Bolt",
	[140] = "Lightning Cloud",
	[141] = "Lightwell",
	[142] = "Linken's Boomerang",
	[143] = "Manastorm",
	[144] = "Mark of Flames",
	[145] = "Massive Geyser",
	[146] = "Mechanical Squirrel",
	[147] = "Merithra's Wake",
	[148] = "Mind Blast",
	[149] = "Mithril Frag Bomb",
	[150] = "Molten Blast",
	[151] = "Molten Rain",
	[152] = "Multi-Shot",
	[153] = "Piercing Shadow",
	[154] = "Poison Bolt",
	[155] = "Poison Cloud",
	[156] = "Purple Hands",
	[157] = "Quick Flame Ward",
	[158] = "Rebirth",
	[159] = "Recall",
	[160] = "Redemption",
	[161] = "Reindeer Dust Effect",
	[162] = "Renew",
	[163] = "Resurrection",
	[164] = "Revive Pet",
	[165] = "Scare Beast",
	[166] = "Scarshield Portal",
	[167] = "Scatter Shot",
	[168] = "Scorpid Sting",
	[169] = "Serpent Sting",
	[170] = "Shackle Undead",
	[171] = "Shadow Flame",
	[172] = "Shadow Portal",
	[173] = "Shadow Shot",
	[174] = "Shadow Weakness",
	[175] = "Shadowblink",
	[176] = "Shadowguard",
	[177] = "Shredder Armor Melt",
	[178] = "Shrink",
	[179] = "Silithid Pox",
	[180] = "Sleep",
	[181] = "Slowing Poison",
	[182] = "Smite",
	[183] = "Solid Dynamite",
	[184] = "Soulstone Resurrection",
	[185] = "Strength of Arko'narin",
	[186] = "Stun Bomb Attack",
	[187] = "Summon",
	[188] = "Summon Atal'ai Skeleton",
	[189] = "Summon Charger",
	[190] = "Summon Dreadsteed",
	[191] = "Summon Felhunter",
	[192] = "Summon Felsteed",
	[193] = "Summon Illusory Wraith",
	[194] = "Summon Imp",
	[195] = "Summon Succubus",
	[196] = "Summon Voidwalker",
	[197] = "Summon Warhorse",
	[198] = "Summon Water Elemental",
	[199] = "Superior Healing Ward",
	[200] = "Teleport: Darnassus",
	[201] = "Teleport: Ironforge",
	[202] = "The Big One",
	[203] = "Thorium Grenade",
	[204] = "Thousand Blades",
	[205] = "Threatening Gaze",
	[206] = "Throw Dynamite",
	[207] = "Time Lapse",
	[208] = "Toxic Saliva",
	[209] = "True Fulfillment",
	[210] = "Unstable Concoction",
	[211] = "Very Berry Cream",
	[212] = "Viper Sting",
	[213] = "Void Bolt",
	[214] = "Volatile Infection",
	[215] = "Volley",
	[216] = "Voodoo",
	[217] = "Wing Buffet",
	[218] = "Wither Touch",
	[219] = "Wyvern Sting",
}

English_Spell_Lock_List = {
	["Flame Cannon"] = "Observed",
	["Flame Breath"] = "Observed",
	["Diseased Spit"] = "Observed",
	["Immolate"] = "Observed",
	["Aimed Shot"] = "Observed",
	["Volatile Infection"] = "Observed",
	["Hibernate"] = "Observed",
	["Create Healthstone (Greater)"] = "Observed",
	["Piercing Shadow"] = "Observed",
	["Merithra's Wake"] = "Observed",
	["Enslave Demon"] = "Observed",
	["Summon"] = "Observed",
	["Mithril Frag Bomb"] = "Observed",
	["Firebolt"] = "Observed",
	["Void Bolt"] = "Observed",
	["Stun Bomb Attack"] = "Observed",
	["Fireball"] = "Observed",
	["Molten Blast"] = "Observed",
	["Manastorm"] = "Observed",
	["Bomb"] = "Observed",
	["Ez-Thro Dynamite"] = "Observed",
	["Mechanical Squirrel"] = "Observed",
	["Scorpid Sting"] = "Observed",
	["Scare Beast"] = "Observed",
	["Lightwell"] = "Observed",
	["Far Sight"] = "Observed",
	["Hex"] = "Observed",
	["Howl of Terror"] = "Observed",
	["Arygos's Vengeance"] = "Observed",
	["First Aid"] = "Observed",
	["Summon Voidwalker"] = "Observed",
	["Summon Succubus"] = "Observed",
	["Strength of Arko'narin"] = "Observed",
	["Cripple"] = "Observed",
	["Summon Imp"] = "Observed",
	["Shadow Flame"] = "Observed",
	["Create Healthstone (Major)"] = "Observed",
	["Serpent Sting"] = "Observed",
	["Entangling Roots"] = "Observed",
	["Pyroblast"] = "Observed",
	["Fire Shield IV"] = "Observed",
	["Crypt Scarabs"] = "Observed",
	["Lightning Cloud"] = "Observed",
	["Frost Weakness"] = "Observed",
	["Summon Felsteed"] = "Observed",
	["Summon Dreadsteed"] = "Observed",
	["Fireball Volley"] = "Observed",
	["Banshee Wail"] = "Observed",
	["Scorch"] = "Observed",
	["Honor Points +398"] = "Observed",
	["Create Shredder"] = "Observed",
	["Conflagrate"] = "Observed",
	["Flamecrack"] = "Observed",
	["Hearthstone"] = "Observed",
	["Forked Lightning"] = "Observed",
	["Teleport: Ironforge"] = "Observed",
	["Grasping Vines"] = "Observed",
	["Enfeeble"] = "Observed",
	["Heavy Runecloth Bandage"] = "Observed",
	["Faerie Fire"] = "Observed",
	["Chains of Ice"] = "Observed",
	["Dense Dynamite"] = "Observed",
	["Fanatic Blade"] = "Observed",
	["Frostbolt"] = "Observed",
	["Frost Burn"] = "Observed",
	["Arcane Shot"] = "Observed",
	["Breath"] = "Observed",
	["Incinerate"] = "Observed",
	["Frostbolt Volley"] = "Observed",
	["Shadowguard"] = "Observed",
	["Furbolg Form"] = "Observed",
	["Wing Buffet"] = "Observed",
	["Multi-Shot"] = "Observed",
	["Fire Shield II"] = "Observed",
	["Starfire"] = "Observed",
	["Haunting Phantoms"] = "Observed",
	["Silithid Pox"] = "Observed",
	["Fiery Burst"] = "Observed",
	["Dominate Mind"] = "Observed",
	["Lesser Heal"] = "Observed",
	["Crystal Gaze"] = "Observed",
	["Summon Charger"] = "Observed",
	["Searing Pain"] = "Observed",
	["Heal"] = "Observed",
	["Corrosive Acid"] = "Observed",
	["Summon Warhorse"] = "Observed",
	["Eye of Immol'thar"] = "Observed",
	["Great Heal"] = "Observed",
	["Toxic Saliva"] = "Observed",
	["Demon Portal"] = "Observed",
	["Corruption"] = "Observed",
	["Holy Light"] = "Observed",
	["Eyes of the Beast"] = "Observed",
	["Healing Wave"] = "Observed",
	["Blizzard"] = "Observed",
	["Redemption"] = "Observed",
	["Fear"] = "Observed",
	["Scatter Shot"] = "Observed",
	["Polymorph"] = "Observed",
	["Shadow Shot"] = "Observed",
	["True Fulfillment"] = "Observed",
	["Teleport: Darnassus"] = "Observed",
	["Flamespit"] = "Observed",
	["Shredder Armor Melt"] = "Observed",
	["Honor Points +2388"] = "Observed",
	["Freeze"] = "Observed",
	["Dark Desire"] = "Observed",
	["Holy Smite"] = "Observed",
	["Enchanted Quickness"] = "Observed",
	["Very Berry Cream"] = "Observed",
	["Summon Blackhand Dreadweaver"] = "Observed",
	["Earthgrab Totem"] = "Observed",
	["Arcane Explosion"] = "Observed",
	["Ice Tomb"] = "Observed",
	["Curse of Blood"] = "Observed",
	["Gordok Green Grog"] = "Observed",
	["Summon Illusory Wraith"] = "Observed",
	["Conjure Mana Ruby"] = "Observed",
	["Hi-Explosive Bomb"] = "Observed",
	["Concussive Shot"] = "Observed",
	["Chain Lightning"] = "Observed",
	["Cannon Fire"] = "Observed",
	["Poison Cloud"] = "Observed",
	["Resurrection"] = "Observed",
	["Shackle Undead"] = "Observed",
	["Regrowth"] = "Observed",
	["Inferno"] = "Observed",
	["Shadow Weakness"] = "Observed",
	["Conjure Water"] = "Observed",
	["Dark Mending"] = "Observed",
	["Summon Blackhand Veteran"] = "Observed",
	["Voodoo"] = "Observed",
	["Goblin Sapper Charge"] = "Observed",
	["Unstable Concoction"] = "Observed",
	["Shadow Bolt Volley"] = "Observed",
	["Revive Pet"] = "Observed",
	["Recall"] = "Observed",
	["Holy Wrath"] = "Observed",
	["Smite"] = "Observed",
	["Threatening Gaze"] = "Observed",
	["Hammer of Wrath"] = "Observed",
	["Ignite Flesh"] = "Observed",
	["Summon Water Elemental"] = "Observed",
	["Soulstone Resurrection"] = "Observed",
	["Goblin Mortar"] = "Observed",
	["Iron Grenade"] = "Observed",
	["Arcane Weakness"] = "Observed",
	["Superior Healing Ward"] = "Observed",
	["Wrath"] = "Observed",
	["Summon Felhunter"] = "Observed",
	["Massive Geyser"] = "Observed",
	["Shadowblink"] = "Observed",
	["Flash Heal"] = "Observed",
	["Molten Rain"] = "Observed",
	["Sleep"] = "Observed",
	["Time Lapse"] = "Observed",
	["Wyvern Sting"] = "Observed",
	["Destroy Egg"] = "Observed",
	["Shrink"] = "Observed",
	["Encasing Webs"] = "Observed",
	["Ghost Wolf"] = "Observed",
	["Arcane Bolt"] = "Observed",
	["Lesser Healing Wave"] = "Observed",
	["Mark of Flames"] = "Observed",
	["Gargoyle Strike"] = "Observed",
	["Fire Storm"] = "Observed",
	["Silence"] = "Observed",
	["Curse of the Darkmaster"] = "Observed",
	["The Big One"] = "Observed",
	["Renew"] = "Observed",
	["Shadow Bolt"] = "Observed",
	["Greater Heal"] = "Observed",
	["Thousand Blades"] = "Observed",
	["Summon Atal'ai Skeleton"] = "Observed",
	["Viper Sting"] = "Observed",
	["Banish"] = "Observed",
	["Rebirth"] = "Observed",
	["Seduction"] = "Observed",
	["Poison Bolt"] = "Observed",
	["Mind Control"] = "Observed",
	["Wither Touch"] = "Observed",
	["Chain Heal"] = "Observed",
	["Flash of Light"] = "Observed",
	["Reindeer Dust Effect"] = "Observed",
	["Shadow Portal"] = "Observed",
	["Banshee Curse"] = "Observed",
	["Healing Touch"] = "Observed",
	["Healing Ward"] = "Observed",
	["Acid Spit"] = "Observed",
	["Mana Burn"] = "Observed",
	["Volley"] = "Observed",
	["Healing Circle"] = "Observed",
	["Curse of the Firebrand"] = "Observed",
	["Black Sludge"] = "Observed",
	["Mind Blast"] = "Observed",
	["Solid Dynamite"] = "Observed",
	["Bellowing Roar"] = "Observed",
	["Soul Fire"] = "Observed",
	["Scarshield Portal"] = "Observed",
	["Buttermilk Delight"] = "Observed",
	["Domination"] = "Observed",
	["Lightning Bolt"] = "Observed",
	["Thorium Grenade"] = "Observed",
	["Holy Fire"] = "Observed",
	["Prayer of Healing"] = "Observed",
	["Throw Dynamite"] = "Observed",
	["Dire Growl"] = "Observed",
	["Quick Flame Ward"] = "Observed",
	["Flame Buffet"] = "Observed",
	["Explosive Shot"] = "Observed",
	["Slowing Poison"] = "Observed",
	["Cultivate Packet of Seeds"] = "Observed",
	["Purple Hands"] = "Observed",
	["Flamestrike"] = "Observed",
	["Defibrillate"] = "Observed",
	["Anti-Magic Shield"] = "Observed",
	["Linken's Boomerang"] = "Observed",
	["Attack"] = "Observed",
}

English_Class_Order = {
				[1] = "Druid",
				[2] = "Hunter",
				[3] = "Mage",
				[4] = "Paladin",
				[5] = "Priest",
				[6] = "Rogue",
				[7] = "Shaman",
				[8] = "Warlock",
				[9] = "Warrior",
				[10] = "=== Class Priority ===",
}

English_Magical_Debuff_List = {
	["Improved Wing Clip"] = "Immobilized.",
	["Brood Power: Blue"] = "Attack speed slowed by 50%.",
	["Sonic Burst"] = "Cannot cast spells.",
	["Blackout"] = "Stunned.",
	["Shadow Word: Pain"] = "112 Shadow damage every 3 seconds.",
	["Brood Power: Bronze"] = "Casting speed reduced by 50%. Attack speed reduced by 25%.",
	["Immolate"] = "102 Fire damage every 3 seconds.",
	["Judgement of the Crusader"] = "Increases Holy damage taken by up to 140.",
	["Crusader's Hammer"] = "Stunned.",
	["Frost Trap Effect"] = "Movement slowed to 40% of normal.",
	["Frostbite"] = "Frozen.",
	["Freeze"] = "Frozen.",
	["Counterspell - Silenced"] = "Silenced.",
	["Slow"] = "Attack speed reduced by 35%. Movement speed reduced to 40% of normal.",
	["Drain Life"] = "Drains 71 health each second to the caster.",
	["Enslave Demon"] = "Enslaved.",
	["Chilled"] = "Movement slowed to 70% and attacks slowed by 20%.",
	["Drain Mana"] = "Drains 139 to 140 mana each second to the caster.",
	["Drowning Death"] = "Swim speed reduced by 20%. Agility reduced by 15%.",
	["Shadowburn"] = "Will grant the caster a Soul Shard upon victim's death.",
	["Befuddlement"] = "Casting speed reduced by 50%.",
	["Power Word: Fortitude"] = "Increases Stamina by 43.",
	["Concussive Shot"] = "Movement slowed to 50% of normal.",
	["Impending Doom"] = "2000 Shadow damage inflicted after 10 sec.",
	["Crystal Flash"] = "Stunned.",
	["Corrosive Acid"] = "Armor reduced by 960.",
	["Mind Control"] = "Charmed.  Attack speed reduced by 20%.",
	["Shackle Undead"] = "Shackled.",
	["Insect Swarm"] = "Chance to hit decreased by 2% and 54 Nature damage every 2 sec.",
	["Aftermath"] = "Movement slowed by 50%.",
	["Unholy Curse"] = "Physical damage done reduced by 15.",
	["Frost Nova"] = "Frozen in place.",
	["Spitelash"] = "Physical damage taken is increased by 43 to 57.",
	["Moonfire"] = "96 Arcane damage every 3 seconds.",
	["Tainted Blood Effect"] = "Attack power reduced by 200.",
	["Smite Demon"] = "Stunned.",
	["Shield Bash - Silenced"] = "Silenced.",
	["Flash Freeze"] = "Stunned.",
	["Banshee Shriek"] = "Cannot cast spells.",
	["Gnomish Mind Control Cap"] = "Charmed.",
	["Fear"] = "Feared.",
	["Hex"] = "Hexed.",
	["Dominate Mind"] = "Charmed.",
	["Howl of Terror"] = "Fleeing in terror.",
	["Soul Tap"] = "350 health leeched every 2 sec. 350 mana leeched every 2 sec.",
	["Phantom Strike"] = "Decreases armor by 100.  Cannot stealth or turn invisible.",
	["Debilitating Touch"] = "Strength reduced by 20. Stamina reduced by 20.",
	["Vindication"] = "Strength and Agility reduced by 15%.",
	["Frostbolt Volley"] = "Movement speed reduced to 50% of normal.",
	["Wither Strike"] = "Attack speed reduced by 33%.",
	["Ink Spray"] = "Chance to hit reduced by 50%.",
	["Mark of Flames"] = "Fire damage dealt is increased by 1000.",
	["Crystallize"] = "Stunned.",
	["Corruption"] = "137 Shadow damage every 3 seconds.",
	["Crusader Strike"] = "Holy damage taken is increased.",
	["Cone of Cold"] = "Movement slowed to 50%.",
	["Terrifying Screech"] = "Fleeing in fear.",
	["Sleep"] = "Asleep.",
	["Soul Burn"] = "4000 Fire damage inflicted over 16 sec. Physical damage dealt is decreased by 50%. Silenced.",
	["Entrapment"] = "Immobile.",
	["Panic"] = "Fleeing in fear.",
	["Death Coil"] = "Horrified.",
	["Shadowed Silence"] = "Cannot cast spells.",
	["Stormstrike"] = "Increases Nature damage taken by 20%.",
	["Flame Shock"] = "58 Fire damage every 3 seconds.",
	["Entangling Roots"] = "Rooted.  Causes 30 Nature damage every 3 seconds.",
	["Chill Nova"] = "Reduced movement speed.",
	["Brood Affliction: Blue"] = "Burns 50 mana every 1 sec. Casting speed reduced by 50%. Movement speed reduced to 70%.",
	["Magma Shackles"] = "Movement speed reduced to 40% of normal.",
	["Silence"] = "Cannot cast spells.",
	["Hunter's Mark"] = "All attackers gain 110 Ranged Attack Power against this target.",
	["Withering Heat"] = "Maximum health reduced by 35%.",
	["Polymorph"] = "Cannot attack or cast spells.  Increased regeneration.",
	["Banish"] = "Invulnerable, but unable to act.",
	["Fire Vulnerability"] = "Increases Fire damage taken by 2%.",
	["Freezing Trap Effect"] = "Frozen.",
	["Chill"] = "Attack speed reduced by 75%. Movement speed reduced to 60%.",
	["Incite Flames"] = "Fire resistance reduced by 100.",
	["Frost Shock"] = "Movement slowed to 50% of normal speed.",
	["Thunderfury"] = "Attack speed reduced by 20%.",
	["Seduction"] = "Charmed.",
	["Ancient Despair"] = "Confused.",
	["Kick - Silenced"] = "Silenced.",
	["Disjunction"] = "Fire, Frost, and Arcane damage taken is increased by 50%.",
	["Immolation Trap Effect"] = "138 Fire damage every 3 seconds.",
	["Terrify"] = "Fleeing in fear.",
	["Brood Power: Green"] = "Stunned.",
	["Reckless Charge"] = "Incapacitated.",
	["Fang of the Crystal Spider"] = "Decreased attack speed and casting speed.",
	["Faerie Fire"] = "Decreases armor by 505.  Cannot stealth or turn invisible.",
	["Consuming Shadows"] = "Movement speed slowed to 70% of normal.",
	["Hibernate"] = "Asleep.",
	["Judgement of Light"] = "Melee attacks made against you have a chance of causing the attacker to be healed for 61.",
	["Holy Fire"] = "17 Holy damage every 2 seconds.",
	["Frostbolt"] = "Movement slowed to 60%.",
	["Cold Eye"] = "Slowed attack speed.",
	["Judgement of Wisdom"] = "Attacks and spells used against you have a chance of restoring 59 of the attacker's mana.",
	["Mind Vision"] = "Sight granted through target's eyes.",
	["Ancient Dread"] = "Casting speed reduced by 50%. Attack speed reduced by 50%.",
	["Explosive Trap Effect"] = "33 Fire damage every 2 seconds.",
	["Slowing Ooze"] = "Attack speed reduced by 20%. Movement speed reduced to 20% of normal.",
	["Chains of Ice"] = "No Text Found",
	["Shadow Vulnerability"] = "Shadow damage increased by 20%.",
	["Earthbind"] = "Movement reduced to 50% of normal.",
	["Hammer of Justice"] = "Stunned.",
	["Frost Shot"] = "Movement speed reduced to 40% of normal.",
	["Greater Polymorph"] = "Cannot attack or cast spells. Health regeneration increased.",
	["Frailty"] = "All attributes reduced by 10.",
	["Cauterizing Flames"] = "Fire resistance reduced by 200.",
	["Mark of Detonation"] = "Deals 657 to 843 damage to self and all allies when hit in melee.",
	["Screams of the Past"] = "Cannot cast spells.",
	["Flame Buffet"] = "Increased Fire damage taken.",
	["Cripple"] = "Movement speed reduced to 50% of normal. Attack speed reduced by 50%. Strength reduced by 50%.",
	["Ignite Mana"] = "400 mana and health burned every 3 sec.",
	["Thunderclap"] = "Attack speed reduced by 25%. Movement speed reduced to 39% of normal.",
	["Detect Magic"] = "Magic detection.",
	["Ignite"] = "Deals fire damage every 2 sec.",
	["Faerie Fire (Feral)"] = "Decreases armor by 505.  Cannot stealth or turn invisible.",
	["Siphon Life"] = "Drains 45 health to the caster every 3 secs.",
	["Scare Beast"] = "Feared.",
	["Repentance"] = "Incapacitated.",
}
		
English_Devour_Order = {
	[1] = "Aftermath",
	[2] = "Ancient Despair",
	[3] = "Ancient Dread",
	[4] = "Banshee Shriek",
	[5] = "Befuddlement",
	[6] = "Blackout",
	[7] = "Brood Affliction: Blue",
	[8] = "Cauterizing Flames",
	[9] = "Chill",
	[10] = "Chill Nova",
	[11] = "Chilled",
	[12] = "Cold Eye",
	[13] = "Concussive Shot",
	[14] = "Cone of Cold",
	[15] = "Consuming Shadows",
	[16] = "Corruption",
	[17] = "Counterspell - Silenced",
	[18] = "Cripple",
	[19] = "Crusader's Hammer",
	[20] = "Crystal Flash",
	[21] = "Crystallize",
	[22] = "Disjunction",
	[23] = "Dominate Mind",
	[24] = "Drain Life",
	[25] = "Drain Mana",
	[26] = "Entangling Roots",
	[27] = "Entrapment",
	[28] = "Fang of the Crystal Spider",
	[29] = "Fear",
	[30] = "Flash Freeze",
	[31] = "Frailty",
	[32] = "Freeze",
	[33] = "Freezing Trap Effect",
	[34] = "Frost Nova",
	[35] = "Frost Shock",
	[36] = "Frost Shot",
	[37] = "Frostbite",
	[38] = "Frostbolt",
	[39] = "Frostbolt Volley",
	[40] = "Hammer of Justice",
	[41] = "Hex",
	[42] = "Hibernate",
	[43] = "Howl of Terror",
	[44] = "Ignite Mana",
	[45] = "Immolate",
	[46] = "Immolation Trap Effect",
	[47] = "Impending Doom",
	[48] = "Improved Wing Clip",
	[49] = "Incite Flames",
	[50] = "Kick - Silenced",
	[51] = "Mark of Flames",
	[52] = "Mind Control",
	[53] = "Moonfire",
	[54] = "Panic",
	[55] = "Polymorph",
	[56] = "Reckless Charge",
	[57] = "Screams of the Past",
	[58] = "Seduction",
	[59] = "Shadow Word: Pain",
	[60] = "Shadowed Silence",
	[61] = "Shield Bash - Silenced",
	[62] = "Silence",
	[63] = "Siphon Life",
	[64] = "Sleep",
	[65] = "Slow",
	[66] = "Slowing Ooze",
	[67] = "Sonic Burst",
	[68] = "Soul Burn",
	[69] = "Soul Tap",
	[70] = "Terrify",
	[71] = "Terrifying Screech",
	[72] = "Thunderclap",
	[73] = "Withering Heat",
	[74] = "=== In/Out Combat Line ===",
	[75] = "Banish",
	[76] = "Brood Power: Blue",
	[77] = "Brood Power: Bronze",
	[78] = "Brood Power: Green",
	[79] = "Chains of Ice",
	[80] = "Corrosive Acid",
	[81] = "Crusader Strike",
	[82] = "Death Coil",
	[83] = "Debilitating Touch",
	[84] = "Detect Magic",
	[85] = "Drowning Death",
	[86] = "Earthbind",
	[87] = "Enslave Demon",
	[88] = "Explosive Trap Effect",
	[89] = "Faerie Fire",
	[90] = "Faerie Fire (Feral)",
	[91] = "Fire Vulnerability",
	[92] = "Flame Buffet",
	[93] = "Flame Shock",
	[94] = "Frost Trap Effect",
	[95] = "Gnomish Mind Control Cap",
	[96] = "Greater Polymorph",
	[97] = "Holy Fire",
	[98] = "Hunter's Mark",
	[99] = "Ignite",
	[100] = "Ink Spray",
	[101] = "Insect Swarm",
	[102] = "Judgement of Light",
	[103] = "Judgement of Wisdom",
	[104] = "Judgement of the Crusader",
	[105] = "Magma Shackles",
	[106] = "Mark of Detonation",
	[107] = "Mind Vision",
	[108] = "Phantom Strike",
	[109] = "Power Word: Fortitude",
	[110] = "Repentance",
	[111] = "Scare Beast",
	[112] = "Shackle Undead",
	[113] = "Shadow Vulnerability",
	[114] = "Shadowburn",
	[115] = "Smite Demon",
	[116] = "Spitelash",
	[117] = "Stormstrike",
	[118] = "Tainted Blood Effect",
	[119] = "Thunderfury",
	[120] = "Unholy Curse",
	[121] = "Vindication",
	[122] = "Wither Strike",
}

	ServitudeLocalization = 
	{
		Class = "Warlock";
		Class2 = "Warrior";
		Class3 = "Shaman";
		Class4 = "Paladin";
		Pet1 = "Imp";
		Pet2 = "Voidwalker";
		Pet3 = "Succubus";
		Pet4 = "Felhunter";
		Pet5 = "Doomguard";
		Magic1 = "Lesser Invisibility";
		Magic2 = "Soothing Kiss";
		Magic3 = "Consume Shadows";
		Magic4 = "Sacrifice";
		Magic5 = "Devour Magic";
		Magic6 = "Torment";
		Magic7 = "Fire Shield";
		Magic8 = "Seduction";
		Magic9 = "Spell Lock";
		Magic10 = "Dispel Magic";
		Magic11 = "Lash of Pain";
		Magic12 = "Banish";
		Magic13 = "Firebolt";
		Magic14 = "Suffering";
		Magic15 = "Curse of Shadow";
		Magic16 = "Curse of the Elements";
		Buff1 = "SacrificialShield";
		Buff2 = "Nature_Swiftness";
		Buff3 = "Spell_Magic_LesserInvisibilty";
		Buff4 = "Mind Vision";
		Buff5 = "Dreamless Sleep";
		Buff6 = "Fire Shield";
		Buff7 = "Thorns";
		Buff8 = "Soul Link";
		Buff9 = "Blood Pact";
		Buff10 = "Retribution Aura";
		Buff11 = "Paranoia";
		Buff12 = "Mind Control";
		Bufftype = "Magic";
		NoDesc = "No Text Found";
		CastString = "(.+) begins to cast (.+).";
		SedString = "(.+) begins to cast Seduction";
		FadeString = "Seduction fades from (.+)%.";
		DarkPactString = "You drain %d+ Mana from";
	}
