
DART_DEFAULT_SETTINGS = {
		[1] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1.25,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["height"] = 138,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 275,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 2",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 114.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -622.5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[2] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1.25,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["height"] = 138,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 275,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 2",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 571,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -622.1,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[3] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\leftframe1",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 266,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 3",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = -672.06,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -479.37,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[4] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\rightframe1",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 266,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 4",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 671.1900000000001,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -479.19,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[5] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\middelleft1",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["height"] = 138,
			["bgalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 522,
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 5",
			["parent"] = "UIParent",
			["xoffset"] = {
				[1] = -321.56,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -448.78,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[6] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\middelright1",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 138,
			["scale"] = 0.75,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["width"] = 522,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 6",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 415.5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -451.31,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[7] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 10,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hide"] = true,
			["height"] = 138,
			["hidebg"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 74,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["scale"] = 0.75,
			["name"] = "Texture 7",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = -365.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -151.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[8] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopleft1",
			["bgalpha"] = 1,
			["height"] = 139,
			["hidebg"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 600,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 1,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightalpha"] = 0,
			["name"] = "Texture 8",
			["parent"] = "UIParent",
			["xoffset"] = {
				[1] = 236.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hide"] = true,
			["yoffset"] = {
				[1] = -682.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[9] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopright1",
			["bgalpha"] = 1,
			["height"] = 106,
			["hidebg"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 0.9686274509803922,
				["r"] = 0.9372549019607843,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 580,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightalpha"] = 0.3,
			["name"] = "Texture 9",
			["parent"] = "UIParent",
			["xoffset"] = {
				[1] = -245.82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = -10,
			["hide"] = true,
			["yoffset"] = {
				[1] = -56.57,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[10] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hidebg"] = 1,
			["highlightalpha"] = 0,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hide"] = true,
			["height"] = 266,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chatbleft1",
			["scale"] = 0.75,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 10",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = -201,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -205.5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[11] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hidebg"] = true,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["hide"] = true,
			["height"] = 266,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chatbright1",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["parent"] = "UIParent",
			["name"] = "Texture 11",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -347,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -207,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[12] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["scale"] = 0.95,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topmiddel1v2",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["height"] = 138,
			["bgalpha"] = 1,
			["parent"] = "UIParent",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["width"] = 266,
			["alpha"] = 1,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 12",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["xoffset"] = {
				[1] = 10.84,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 1,
			["yoffset"] = {
				[1] = -90.14,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[13] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topleft1v2",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["height"] = 74,
			["bgalpha"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 522,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 13",
			["scale"] = 0.95,
			["xoffset"] = {
				[1] = -373.09,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = 446.85,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[14] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topright1v2",
			["height"] = 74,
			["scale"] = 0.95,
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 522,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 14",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 370.82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = 447.16,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[15] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topright1v2extra",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["height"] = 74,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 15",
			["scale"] = 0.95,
			["xoffset"] = {
				[1] = 583.09,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["yoffset"] = {
				[1] = 446.61,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[16] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topleft1v2extra",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["height"] = 74,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 16",
			["scale"] = 0.95,
			["xoffset"] = {
				[1] = -514.96,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["yoffset"] = {
				[1] = 446.58,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[17] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["height"] = 74,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\castingbar",
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 522,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightalpha"] = 0.3,
			["name"] = "Texture 17",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -288.82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hide"] = true,
			["yoffset"] = {
				[1] = -141.79,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[18] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 15,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
				[2] = "",
				[14] = "",
			},
			["hide"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["height"] = 138,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull2",
			["scale"] = 0.75,
			["bgalpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 74,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["name"] = "Texture 18",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["xoffset"] = {
				[1] = -1.999985694885254,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -437.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[19] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 522,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 19",
			["scale"] = 0.75,
			["xoffset"] = {
				[1] = 123,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframeleft",
			["yoffset"] = {
				[1] = -562,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[20] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 522,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 20",
			["scale"] = 0.75,
			["xoffset"] = {
				[1] = -62,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframelright",
			["yoffset"] = {
				[1] = -301.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		["updatespeed"] = 60,
		["INITIALIZED1.0d"] = true,
		["optionsscale"] = 1,
		["autolock"] = 1,
		["INITIALIZED1.1"] = true,
}
