
DART_CUSTOM_SETTINGS = {
		[1] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = -2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 138,
			["scale"] = 1.25,
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 276,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 2",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 375,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["yoffset"] = {
				[1] = -548.5999862670899,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[2] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1.25,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["height"] = 138,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 276,
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 2",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 109,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -548.5999862670899,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[3] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\leftframe1",
			["height"] = 266,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 3",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = -518.9999856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -362.4999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[4] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\rightframe1",
			["height"] = 266,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 4",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 511.5000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -363.2499885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[5] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hide"] = true,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["height"] = 138,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\middelleft1",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["scale"] = 0.75,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["width"] = 522,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 5",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -168.4299856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -336.9099885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[6] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hide"] = true,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["height"] = 138,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\middelright1",
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 522,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 6",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 248.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -333.4999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[7] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 10,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\logo",
			["height"] = 138,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["width"] = 138,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 7",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 18.00001430511475,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -437.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[8] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chattopleft1",
			["height"] = 138,
			["scale"] = 0.75,
			["highlightalpha"] = 0,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 522,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 1,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 8",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 198,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -903.4999771118164,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[9] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 0.9686274509803922,
				["r"] = 0.9372549019607843,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chattopright1",
			["height"] = 108,
			["scale"] = 0.76,
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 492,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 9",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 304.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = -10,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -453.2499885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[10] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 5,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = 1,
			["height"] = 266,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["width"] = 266,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 10",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 134.2500143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chatbleft1",
			["yoffset"] = {
				[1] = -507.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[11] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 5,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["height"] = 266,
			["scale"] = 0.75,
			["parent"] = "UIParent",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 11",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 48.7500143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chatbright1",
			["yoffset"] = {
				[1] = -508.2499885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[12] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 1,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topmiddel1v2",
			["height"] = 138,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["parent"] = "UIParent",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["width"] = 266,
			["alpha"] = 1,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 12",
			["scale"] = 0.75,
			["xoffset"] = {
				[1] = 2.770014305114728,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = "423",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[13] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["scale"] = 0.75,
			["bgalpha"] = 0,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["scripts"] = {
			},
			["hidebg"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topleft1v2",
			["height"] = 74,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 522,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 13",
			["parent"] = "UIParent",
			["xoffset"] = {
				[1] = -381.4099856948852,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = "455",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[14] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 74,
			["scale"] = 0.75,
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 522,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 14",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 368.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topright1v2",
			["yoffset"] = {
				[1] = "455",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[15] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topright1v2extra",
			["height"] = 138,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 15",
			["scale"] = 0.75,
			["xoffset"] = {
				[1] = 514.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = "424",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[16] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topleft1v2extra",
			["height"] = 138,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 16",
			["scale"] = 0.75,
			["xoffset"] = {
				[1] = -516.9999856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = "424",
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[17] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\castingbar",
			["bgalpha"] = 1,
			["height"] = 74,
			["hide"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.75,
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 522,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 17",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 118.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -241.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[18] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 15,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
				[2] = "if param==\"PLAYER_ENTER_COMBAT\" then \
this.attacking = 1; \
DART_Show(ti); \
elseif param==\"PLAYER_LEAVE_COMBAT\" then \
this.attacking = nil; \
if not this.inCombat then DART_Hide(ti); end \
elseif param==\"PLAYER_REGEN_DISABLED\" then \
this.inCombat = 1; \
DART_Show(ti); \
elseif param==\"PLAYER_REGEN_ENABLED\" then \
this.inCombat = nil; \
if not this.attacking then DART_Hide(ti); end \
end\
",
				[14] = "this:RegisterEvent(\"PLAYER_ENTER_COMBAT\"); \
this:RegisterEvent(\"PLAYER_LEAVE_COMBAT\"); \
this:RegisterEvent(\"PLAYER_REGEN_ENABLED\"); \
this:RegisterEvent(\"PLAYER_REGEN_DISABLED\"); \
DART_StartFlashing(ti); \
DART_Hide(ti); \
",
			},
			["hide"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 138,
			["hidebg"] = true,
			["scale"] = 0.75,
			["parent"] = "UIParent",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 74,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["name"] = "Texture 18",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = -1.999985694885254,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull2",
			["yoffset"] = {
				[1] = -437.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[19] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "CT_RAMember1CastFrame",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = -1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframeleft",
			["bgalpha"] = 1,
			["height"] = 522,
			["hide"] = true,
			["scale"] = 0.75,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["width"] = 266,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 19",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -511.9999856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = 28.0000114440918,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[20] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "CT_RAMember21CastFrame",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframelright",
			["bgalpha"] = 1,
			["height"] = 522,
			["hide"] = true,
			["scale"] = 0.75,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["width"] = 266,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 20",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 573,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = 28.0000114440918,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		["updatespeed"] = 60,
		["INITIALIZED1.0d"] = true,
		["optionsscale"] = 0.6,
		["autolock"] = 1,
		["INITIALIZED1.1"] = true,
}
