--<< English Localization >>--
if GetLocale()=="enUS"
or GetLocale()=="enGB" then

TITAN_CLASSTRACKER_MENU_TEXT="Class Tracker";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="Nothing to track";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "Right-click for options";
TITAN_CLASSTRACKER_TOOLTIP = "Tracking";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "Show Class Title";
TITAN_CT_MENU_SHOW_TRACKER = "Show Tracker";

TITAN_WARRIOR_TITLE = "Warrior Tracker";
TITAN_HUNTER_TITLE = "Hunter Tracker";

TITAN_WARLOCK_TITLE = "Warlock Tracker";
TITAN_WARLOCK_BUTTON_LABEL="SoulShards: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "Soul Shards: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "Healthstone: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "Soulstone: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "Spellstone: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "Firestone: %s";

TITAN_SHAMAN_TITLE = "Shaman Tracker";
TITAN_SHAMAN_BUTTON_LABEL="Ankhs: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "Ankhs: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "Shiny Fish Scales: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "Fish Oil: %s";

TITAN_MAGE_TITLE = "Mage Tracker";
TITAN_MAGE_BUTTON_LABELTELE="TeleRunes: ";
TITAN_MAGE_BUTTON_LABELPORTAL="PortalRunes: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "Teleport Runes: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "Portal Runes: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "Arcane Powder: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "Light Feather: %s";

TITAN_ROGUE_TITLE = "Rogue Tracker";
TITAN_ROGUE_BUTTON_LABELFLASH="Flash: ";
TITAN_ROGUE_BUTTON_LABELBLIND="Blinding: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="Poisons: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "Flash Powder: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "Blinding Powder: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "Thistle Tea: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "Instant Poisons: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "Deadly Poisons: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "Crippling Poisons: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "Mind-numbing Poisons: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "Wound Poisons: %s";

TITAN_DRUID_TITLE = "Druid Tracker";
TITAN_DRUID_BUTTON_LABELSEEDS="Seeds: ";
TITAN_DRUID_BUTTON_LABELWILD="Wilds: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "Maple Seed: %s";
TITAN_DRUID_TOOLTIP_SSEED = "Stranglethorn Seed: %s";
TITAN_DRUID_TOOLTIP_ASEED = "Ashwood Seed: %s";
TITAN_DRUID_TOOLTIP_HSEED = "Hornbeam Seed: %s";
TITAN_DRUID_TOOLTIP_ISEED = "Ironwood Seed: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "Wild Berries: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "Wild Thornroot: %s";

TITAN_PRIEST_TITLE = "Priest Tracker";
TITAN_PRIEST_BUTTON_LABELFEATHERS="Feathers: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="Candles: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "Light Feather: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "Holy Candle: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "Sacred Candle: %s";

TITAN_PALADIN_TITLE = "Paladin Tracker";
TITAN_PALADIN_BUTTON_LABELSYMBOL="Symbol: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "Symbol of Divinity: %s";
TITAN_PALADIN_TOOLTIP_KING = "King of Divinity: %s";

return
end

--<< French Localization >>--
if GetLocale()=="frFR" then

TITAN_CLASSTRACKER_MENU_TEXT="Class Tracker";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="Nothing to track";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "Right-click for options";
TITAN_CLASSTRACKER_TOOLTIP = "Tracking";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "Show Class Title";
TITAN_CT_MENU_SHOW_TRACKER = "Show Tracker";

TITAN_WARRIOR_TITLE = "Warrior Tracker";
TITAN_HUNTER_TITLE = "Hunter Tracker";

TITAN_WARLOCK_TITLE = "Warlock Tracker";
TITAN_WARLOCK_BUTTON_LABEL="SoulShards: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "Soul Shards: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "Healthstone: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "Soulstone: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "Spellstone: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "Firestone: %s";

TITAN_SHAMAN_TITLE = "Shaman Tracker";
TITAN_SHAMAN_BUTTON_LABEL="Ankhs: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "Ankhs: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "Shiny Fish Scales: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "Fish Oil: %s";

TITAN_MAGE_TITLE = "Mage Tracker";
TITAN_MAGE_BUTTON_LABELTELE="TeleRunes: ";
TITAN_MAGE_BUTTON_LABELPORTAL="PortalRunes: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "Teleport Runes: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "Portal Runes: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "Arcane Powder: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "Light Feather: %s";

TITAN_ROGUE_TITLE = "Rogue Tracker";
TITAN_ROGUE_BUTTON_LABELFLASH="Flash: ";
TITAN_ROGUE_BUTTON_LABELBLIND="Blinding: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="Poisons: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "Flash Powder: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "Blinding Powder: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "Thistle Tea: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "Instant Poisons: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "Deadly Poisons: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "Crippling Poisons: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "Mind-numbing Poisons: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "Wound Poisons: %s";

TITAN_DRUID_TITLE = "Druid Tracker";
TITAN_DRUID_BUTTON_LABELSEEDS="Seeds: ";
TITAN_DRUID_BUTTON_LABELWILD="Wilds: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "Maple Seed: %s";
TITAN_DRUID_TOOLTIP_SSEED = "Stranglethorn Seed: %s";
TITAN_DRUID_TOOLTIP_ASEED = "Ashwood Seed: %s";
TITAN_DRUID_TOOLTIP_HSEED = "Hornbeam Seed: %s";
TITAN_DRUID_TOOLTIP_ISEED = "Ironwood Seed: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "Wild Berries: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "Wild Thornroot: %s";

TITAN_PRIEST_TITLE = "Priest Tracker";
TITAN_PRIEST_BUTTON_LABELFEATHERS="Feathers: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="Candles: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "Light Feather: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "Holy Candle: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "Sacred Candle: %s";

TITAN_PALADIN_TITLE = "Paladin Tracker";
TITAN_PALADIN_BUTTON_LABELSYMBOL="Symbol: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "Symbol of Divinity: %s";

return
end

--<< German Localization >>--
if GetLocale()=="deDE" then

TITAN_CLASSTRACKER_MENU_TEXT="Class Tracker";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="Nothing to track";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "Right-click for options";
TITAN_CLASSTRACKER_TOOLTIP = "Tracking";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "Show Class Title";
TITAN_CT_MENU_SHOW_TRACKER = "Show Tracker";

TITAN_WARRIOR_TITLE = "Warrior Tracker";
TITAN_HUNTER_TITLE = "Hunter Tracker";

TITAN_WARLOCK_TITLE = "Warlock Tracker";
TITAN_WARLOCK_BUTTON_LABEL="SoulShards: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "Soul Shards: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "Healthstone: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "Soulstone: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "Spellstone: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "Firestone: %s";

TITAN_SHAMAN_TITLE = "Shaman Tracker";
TITAN_SHAMAN_BUTTON_LABEL="Ankhs: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "Ankhs: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "Shiny Fish Scales: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "Fish Oil: %s";

TITAN_MAGE_TITLE = "Mage Tracker";
TITAN_MAGE_BUTTON_LABELTELE="TeleRunes: ";
TITAN_MAGE_BUTTON_LABELPORTAL="PortalRunes: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "Teleport Runes: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "Portal Runes: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "Arcane Powder: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "Light Feather: %s";

TITAN_ROGUE_TITLE = "Rogue Tracker";
TITAN_ROGUE_BUTTON_LABELFLASH="Flash: ";
TITAN_ROGUE_BUTTON_LABELBLIND="Blinding: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="Poisons: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "Flash Powder: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "Blinding Powder: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "Thistle Tea: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "Instant Poisons: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "Deadly Poisons: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "Crippling Poisons: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "Mind-numbing Poisons: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "Wound Poisons: %s";

TITAN_DRUID_TITLE = "Druid Tracker";
TITAN_DRUID_BUTTON_LABELSEEDS="Seeds: ";
TITAN_DRUID_BUTTON_LABELWILD="Wilds: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "Maple Seed: %s";
TITAN_DRUID_TOOLTIP_SSEED = "Stranglethorn Seed: %s";
TITAN_DRUID_TOOLTIP_ASEED = "Ashwood Seed: %s";
TITAN_DRUID_TOOLTIP_HSEED = "Hornbeam Seed: %s";
TITAN_DRUID_TOOLTIP_ISEED = "Ironwood Seed: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "Wild Berries: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "Wild Thornroot: %s";

TITAN_PRIEST_TITLE = "Priest Tracker";
TITAN_PRIEST_BUTTON_LABELFEATHERS="Feathers: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="Candles: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "Light Feather: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "Holy Candle: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "Sacred Candle: %s";

TITAN_PALADIN_TITLE = "Paladin Tracker";
TITAN_PALADIN_BUTTON_LABELSYMBOL="Symbol: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "Symbol of Divinity: %s";

return
end

--<< Korean Localization >>--
if GetLocale()=="koKR" then

TITAN_CLASSTRACKER_MENU_TEXT="직업 아이템";
TITAN_CLASSTRACKER_BUTTON_TEXT="o";
TITAN_CLASSTRACKER_TOOLTIP_NA="없음";
TITAN_CLASSTRACKER_TOOLTIP_CLICK = "설정(오른쪽 마우스 클릭)";
TITAN_CLASSTRACKER_TOOLTIP = "직업아이템";
TITAN_CLASSTRACKER_BUTTON_TINY="CT:";
TITAN_CT_MENU_SHOW_TITLE = "직업 보기";
TITAN_CT_MENU_SHOW_TRACKER = "아이템 보기";

TITAN_WARRIOR_TITLE = "전사 직업아이템";
TITAN_HUNTER_TITLE = "사냥꾼 직업아이템";

TITAN_WARLOCK_TITLE = "흑마법사 직업아이템";
TITAN_WARLOCK_BUTTON_LABEL="영혼의 조각: ";
TITAN_WARLOCK_BUTTON_TEXTSHARDS="%s";
TITAN_WARLOCK_TOOLTIP_SHARDS = "영혼의 조각: %s";
TITAN_WARLOCK_TOOLTIP_HEALTH = "생명석: %s";
TITAN_WARLOCK_TOOLTIP_SOUL = "영혼석: %s";
TITAN_WARLOCK_TOOLTIP_SPELL = "주문석: %s";
TITAN_WARLOCK_TOOLTIP_FIRE = "화염석: %s";

TITAN_SHAMAN_TITLE = "주술사 직업아이템";
TITAN_SHAMAN_BUTTON_LABEL="십자가: ";
TITAN_SHAMAN_BUTTON_TEXTANKHS="%s";
TITAN_SHAMAN_TOOLTIP_ANKHS = "십자가: %s";
TITAN_SHAMAN_TOOLTIP_SCALES = "반짝이는 물고기 비늘: %s";
TITAN_SHAMAN_TOOLTIP_OIL = "물고기 오일: %s";

TITAN_MAGE_TITLE = "마법사 직업아이템";
TITAN_MAGE_BUTTON_LABELTELE="순간이동의 룬: ";
TITAN_MAGE_BUTTON_LABELPORTAL="차원이동의 룬: ";
TITAN_MAGE_BUTTON_TEXTTELE="%s";
TITAN_MAGE_BUTTON_TEXTPORTAL="%s";
TITAN_MAGE_TOOLTIP_TELE = "순간이동의 룬: %s";
TITAN_MAGE_TOOLTIP_PORTAL = "차원이동의 룬: %s";
TITAN_MAGE_TOOLTIP_ARCANE = "불가사의한 가루: %s";
TITAN_MAGE_TOOLTIP_FEATHER = "가벼운 깃털: %s";

TITAN_ROGUE_TITLE = "도적 직업아이템";
TITAN_ROGUE_BUTTON_LABELFLASH="섬광 화약: ";
TITAN_ROGUE_BUTTON_LABELBLIND="실명 가루: ";
TITAN_ROGUE_BUTTON_LABELPOISONS="독: ";
TITAN_ROGUE_BUTTON_TEXTFLASH="%s";
TITAN_ROGUE_BUTTON_TEXTBLIND="%s";
TITAN_ROGUE_BUTTON_TEXTPOISONS="%s";
TITAN_ROGUE_TOOLTIP_FLASH = "섬광 화약: %s";
TITAN_ROGUE_TOOLTIP_BLIND = "실명 가루: %s";
TITAN_ROGUE_TOOLTIP_THISTLE = "엉겅퀴 차: %s";
TITAN_ROGUE_TOOLTIP_INSTANT = "순간 효과 독: %s";
TITAN_ROGUE_TOOLTIP_DEADLY = "맹독: %s";
TITAN_ROGUE_TOOLTIP_CRIPPLING = "신경 마비 독: %s";
TITAN_ROGUE_TOOLTIP_MINDNUMB = "정신 마비 독: %s";
TITAN_ROGUE_TOOLTIP_WOUND = "상처 감염 독: %s";

TITAN_DRUID_TITLE = "드루이드 직업아이템";
TITAN_DRUID_BUTTON_LABELSEEDS="씨앗: ";
TITAN_DRUID_BUTTON_LABELWILD="야생 가지: ";
TITAN_DRUID_BUTTON_TEXTSEEDS="%s";
TITAN_DRUID_BUTTON_TEXTWILD="%s";
TITAN_DRUID_TOOLTIP_MSEED = "단풍나무 씨앗: %s";
TITAN_DRUID_TOOLTIP_SSEED = "가시덩굴 씨앗: %s";
TITAN_DRUID_TOOLTIP_ASEED = "잿빛나무 씨앗: %s";
TITAN_DRUID_TOOLTIP_HSEED = "자작나무 씨앗: %s";
TITAN_DRUID_TOOLTIP_ISEED = "강철나무 씨앗: %s";
TITAN_DRUID_TOOLTIP_BERRIES = "야생 가지: %s";
TITAN_DRUID_TOOLTIP_THORNROOT = "야생 가시뿌리: %s";

TITAN_PRIEST_TITLE = "사제 직업아이템";
TITAN_PRIEST_BUTTON_LABELFEATHERS="깃털: ";
TITAN_PRIEST_BUTTON_LABELCANDLES="양초: ";
TITAN_PRIEST_BUTTON_TEXTFEATHER="%s";
TITAN_PRIEST_BUTTON_TEXTCANDLES="%s";
TITAN_PRIEST_TOOLTIP_FEATHER = "가벼운 깃털: %s";
TITAN_PRIEST_TOOLTIP_HCANDLE = "성스러운 양초: %s";
TITAN_PRIEST_TOOLTIP_SCANDLE = "신성한 양초: %s";

TITAN_PALADIN_TITLE = "성기사 직업아이템";
TITAN_PALADIN_BUTTON_LABELSYMBOL="신앙의 징표: ";
TITAN_PALADIN_BUTTON_TEXTSYMBOL="%s";
TITAN_PALADIN_TOOLTIP_SYMBOL = "신앙의 징표: %s";
TITAN_PALADIN_TOOLTIP_KING = "왕의 징표: %s";

return
end