AtlasLootConstructedTooltips = {
    ["Fists of the Unrelenting"] = {
		[1] = "|cffa335eeFists of the Unrelenting",
		[2] = "",
		[3] = "|cffFFFFFFBinds when picked up",
		[4] = "",
        [5] = "|cffFFFFFFHands",
		[6] = "|cffFFFFFFPlate",
		[7] = "|cffFFFFFF642 Armor",
		[8] = "",
		[9] = "|cffFFFFFF+30 Strength",
		[10] = "",
        [11] = "|cffFFFFFF+20 Stamina",
		[12] = "",
        [13] = "|cffFFFFFFRequires Level 60",
		[14] = "",
		[15] = "|cff1eff00Equip: Immune to Disarm.",
		[16] = "",
        [17] = "|cff1eff00Equip: Improves your chance to get a critical strike by 1%.",
		[18] = "",
	},
};