if (GetLocale() == "esES") then

CCWATCH_VERSION = "11200.3"
CCWATCH_FULLVERSION = "CCWatch v"..CCWATCH_VERSION

-- ES

CCWATCH_DESCRIPTION = "Permite monitorizar el control de muchedumbre, los debuffs y los buffs en enemigos, para todas las clases."

CCWATCH_PROFILE_TEXT = "Perfil: "

CCWATCH_EFFECT = "Efecto"
CCWATCH_NAME = "Nombre"
CCWATCH_DURATION = "Duraci\195\179n"
CCWATCH_RESET = "Nuevo"
CCWATCH_ADD = "A\195\177adir"
CCWATCH_MODIFY = "Modificar"
CCWATCH_EDIT = "Editar"
CCWATCH_DELETE = "Borrar"
CCWATCH_LEARN_DELETE_PROMPT = "Estas seguro de querer eliminar el efecto "
CCWATCH_REMOVED_NOTICE = "Eliminado efecto de habilidad : "
CCWATCH_TYPE = "Tipo"
CCWATCH_GROUP = "Grupo"
CCWATCH_DR = "DR"
CCWATCH_MONITOR = "Monitor"
CCWATCH_WARN = "Advertir"
CCWATCH_ADDEDMODIFIED = " a\195\177adido/modificado."

CCWATCH_OPTIONS_BARS_TAB = "Barras"
CCWATCH_OPTIONS_EFFECTS_TAB = "Monitorizaci\195\179n"
CCWATCH_OPTIONS_LEARN_TAB = "Habilidades"

CCWATCH_OPTIONS_TITLE = "Opciones CCWatch"
CCWATCH_OPTIONS_TRANS = "Transparencia"
CCWATCH_OPTIONS_SCALE = "Escalado"
CCWATCH_OPTIONS_DONE = "Hecho"
CCWATCH_OPTIONS_UNLOCK = "Desbloquear"
CCWATCH_OPTIONS_WIDTH = "Ancho"
CCWATCH_OPTIONS_INVERT = "Invertir"
CCWATCH_OPTIONS_LEADINGTIMER = "Pos. temp. izq."
CCWATCH_OPTIONS_ARCANIST = "Set de Arcanist"

CCWATCH_OPTIONS_WARN_APPLIED = "Aplicado"
CCWATCH_OPTIONS_WARN_FADED = "Desvanecido"
CCWATCH_OPTIONS_WARN_BROKEN = "Roto"
CCWATCH_OPTIONS_WARN_LOWTIME = "Poco Tiempo"

CCWATCH_OPTIONS_MAGE = "Mago"
CCWATCH_OPTIONS_PRIEST = "Sacerdote"
CCWATCH_OPTIONS_DRUID = "Druida"
CCWATCH_OPTIONS_HUNTER = "Cazador"
CCWATCH_OPTIONS_PALADIN = "Palad\195\173n"
CCWATCH_OPTIONS_WARLOCK = "Brujo"
CCWATCH_OPTIONS_WARRIOR = "Guerrero"
CCWATCH_OPTIONS_ROGUE = "P\195\173caro"
CCWATCH_OPTIONS_SHAMAN = "Cham\195\161n"
CCWATCH_OPTIONS_MISC = "Otro"

CCWATCH_OPTION_STYLE_CURRENT = "Objetivo actual"
CCWATCH_OPTION_STYLE_RECENT = "Objetivos recientes"
CCWATCH_OPTION_STYLE_ALL = "Todas las Criaturas/Enemigos"

CCWATCH_OPTION_GROWTH_OFF = "Prioridad Off"
CCWATCH_OPTION_GROWTH_UP = "Prioridad Abajo->Arriba"
CCWATCH_OPTION_GROWTH_DOWN = "Prioridad Arriba->Abajo"

CCWATCH_OPTION_TIMERS_OFF = "Temporiz. Off"
CCWATCH_OPTION_TIMERS_ON = "Temporiz. On"
CCWATCH_OPTION_TIMERS_REVERSE = "Inv. Temporiz.(Cuenta atr\195\161s)"

CCWATCH_OPTION_DR_NEVER = "Nunca"
CCWATCH_OPTION_DR_MOBPLAYERS = "Mob+Jugadores"
CCWATCH_OPTION_DR_PLAYERS = "Jugadores"

CCWATCH_OPTIONS_MONITOR_CC = "Monitoriza Control Muchedumbre"
CCWATCH_OPTIONS_MONITOR_DEBUFF = "Monitoriza Debuffs"
CCWATCH_OPTIONS_MONITOR_BUFF = "Monitoriza Buffs"

CCWATCH_OPTIONS_COLOROVERTIME = "Utiliza coloraci\195\179n en el tiempo"
CCWATCH_OPTIONS_USECOLOR = "Especifica color"

CCWATCH_WARN_EMOTE = "anuncia que ";
CCWATCH_WARN_LOWTIME = "[%s] dejar\195\161 de estar afectado por [%s] en %d segundos."
CCWATCH_WARN_APPLIED = "[%s] est\195\161 afectado por [%s]."
CCWATCH_WARN_FADED = "[%s] ya no est\195\161 afectado por [%s] (desvanecido)."
CCWATCH_WARN_BROKEN = "[%s] ya no est\195\161 afectado por [%s] (roto)."

-- Priest / Sacerdote
CCWATCH_SHACKLE = "Encadenar no-muerto"
CCWATCH_PSYCHICSCREAM = "Alarido ps\195\173quico"
CCWATCH_BLACKOUT = "Desmayo"
CCWATCH_SHADOWWORDPAIN = "Palabra de las Sombras: dolor"
CCWATCH_POWERWORDSHIELD = "Palabra de poder: escudo"
CCWATCH_DEVOURINGPLAGUE = "Peste devoradora"
CCWATCH_WEAKENEDSOUL = "Alma debilitada"
CCWATCH_RENEW ="Renovar"
CCWATCH_HOLYFIRE = "Fuego Sagrado"
CCWATCH_POWERINFUSION = "Infusi\195\179n de poder"

-- Mage / Mago
CCWATCH_POLYMORPH = "Polimorfia"
CCWATCH_FROSTNOVA = "Nova de Escarcha"
CCWATCH_FROSTBITE = "Mordedura de Escarcha"
CCWATCH_ICEBLOCK = "Bloque de hielo"
CCWATCH_FROSTBOLT = "Descarga de Escarcha"
CCWATCH_CONEOFCOLD = "Cono de fr\195\173o"
CCWATCH_COUNTERSPELL = "Contrahechizo: silenciado"
CCWATCH_FIREBALL = "Bola de Fuego"
CCWATCH_PYROBLAST = "Piroexplosi\195\179n"
CCWATCH_IGNITE = "Ignici\195\179n"
CCWATCH_FLAMESTRIKE = "Fogonazo"
CCWATCH_BLASTWAVE = "Ola explosiva"
CCWATCH_FROSTARMOR = "Armadura de Escarcha"
CCWATCH_DETECTMAGIC = "Detectar magia"
CCWATCH_EVOCATION = "Evocaci\195\179n"
CCWATCH_ARCANEPOWER = "Poder Arcano"

-- Paladin
CCWATCH_HOJ = "Martillo de justicia"
CCWATCH_TURNUNDEAD = "Ahuyentar a no-muerto"
CCWATCH_REPENTANCE = "Arrepentimiento"
CCWATCH_DIVINESHIELD = "Escudo divino"
CCWATCH_BOPROTECTION = "Bendici\195\179n de Protecci\195\179n"
CCWATCH_BOFREEDOM = "Bendici\195\179n de Libertad"

-- Warlock / Brujo
CCWATCH_FEAR = "Miedo"
CCWATCH_BANISH = "Desterrar"
CCWATCH_SEDUCE = "Seducci\195\179n"
CCWATCH_HOWLOFTERROR = "Aullido de terror"
CCWATCH_DEATHCOIL = "Espiral mortal"
CCWATCH_IMMOLATE = "Inmolar"
CCWATCH_CORRUPTION = "Corrupci\195\179n"
CCWATCH_CURSEOFRECKLESSNESS = "Maldici\195\179n de Temeridad"
CCWATCH_CURSEOFAGONY = "Maldici\195\179n de Agon\195\173a"
CCWATCH_CURSEOFWEAKNESS = "Maldici\195\179n de debilidad"
CCWATCH_CURSEOFTONGUES = "Maldici\195\179n de la lengua"
CCWATCH_CURSEOFSHADOW = "Maldici\195\179n de las Sombras"
CCWATCH_CURSEOFELEMENTS = "Maldici\195\179n de los Elementos"
CCWATCH_CURSEOFEXHAUSTION = "Maldici\195\179n de agotamiento"
CCWATCH_CURSEOFDOOM = "Maldici\195\179n del Apocalipsis"
CCWATCH_SIPHONLIFE = "Engullir vida"
CCWATCH_IMPROVEDSHADOWBOLT = "Descarga de Sombras mejorada"
CCWATCH_SACRIFICE = "Sacrificio"
CCWATCH_SPELLSTONE = "Piedra de hechizos"
CCWATCH_SPELLLOCK = "Bloqueo de hechizo"

-- Druid / Druida
CCWATCH_HIBERNATE = "Hibernar"
CCWATCH_ROOTS = "Enredaderas"
CCWATCH_POUNCE = "Lanzarse"
CCWATCH_BASH = "Azote"
CCWATCH_FERALCHARGE = "Embestida feral"
CCWATCH_IMPSTARFIRE = "Fuego estelar mejorado"
CCWATCH_MOONFIRE = "Fuego lunar"
CCWATCH_INSECTSWARM = "Enjambre de insectos"
CCWATCH_NATURESGRASP = "Ligaz\195\179n de la Naturaleza"
CCWATCH_REJUVENATION = "Rejuvenecimiento"
CCWATCH_DASH = "Diligencia"
CCWATCH_FAERIEFIRE = "Fuego fe\195\169rico"
CCWATCH_FAERIEFIREFERAL = "Fuego fe\195\169rico (feral)"
-- De esta no estoy seguro 100%
CCWATCH_INNERVATE = "Evocaci\195\179n"
CCWATCH_BARKSKIN = "Pielcorteza"
CCWATCH_REGROWTH = "Recrecimiento"
CCWATCH_FREGEN = "Regeneraci\195\179n fren\195\169tica"

-- Hunter / Cazador
CCWATCH_FREEZINGTRAP = "Efecto de trampa congelante"
CCWATCH_FREEZINGTRAP_SPELL = "Trampa congelante"
CCWATCH_SCAREBEAST = "Bestia temible"
CCWATCH_IMPCS = "Disparo de conmoci\195\179n mejorado"
CCWATCH_SCATTERSHOT = "Disparo disperso"
CCWATCH_INTIMIDATION = "Intimidaci\195\179n"
CCWATCH_COUNTERATTACK = "Contraataque"
CCWATCH_WYVERNSTING = "Aguij\195\179n de dracole\195\179n"
CCWATCH_IMPROVEDWINGCLIP = "Cortar alas mejorado"
CCWATCH_ENTRAPMENT = "Atrapamiento"
CCWATCH_SERPENTSTING = "Aguij\195\179n de serpiente"
CCWATCH_DETERRENCE = "Disuasi\195\179n"
CCWATCH_RAPIDFIRE = "Fuego veloz"

-- Warrior / Guerrero
CCWATCH_INTERCEPT = "Aturdimiento de intercepci\195\179n"
CCWATCH_MACESPE = "Maestr\195\173a con mazas"
CCWATCH_IMPHAMSTRING = "Seccionar mejorado"
CCWATCH_INTIMIDATINGSHOUT = "Grito intimidador"
CCWATCH_IMPREVENGE = "Aturdimiento de revancha"
CCWATCH_CONCUSSIONBLOW = "Arremetida de conmoci\195\179n"
CCWATCH_BERSERKERRAGE = "Ira rabiosa"
CCWATCH_BLOODRAGE = "Ira sangrienta"
CCWATCH_REND = "Desgarrar"
CCWATCH_DISARM = "Desactivar"
CCWATCH_LASTSTAND = "\195\154ltima carga"
CCWATCH_RETALIATION = "Represalias"
CCWATCH_SHIELDWALL = "Muro de escudo"
CCWATCH_DEATHWISH = "Deseo de la Muerte"
CCWATCH_IMPSHIELDBASH = "Azote de escudo: silenciado"
CCWATCH_MORTALSTRIKE = "Golpe mortal"
CCWATCH_RECKLESSNESS = "Temeridad"
CCWATCH_HAMSTRING = "Seccionar"

-- Rogue / Pícaro
CCWATCH_GOUGE = "Incapacitaci\195\179n"
CCWATCH_BLIND = "Ceguera"
CCWATCH_KS = "Golpe en los ri\195\177ones"
CCWATCH_CS = "Golpe bajo"
CCWATCH_SAP = "Zapar"
CCWATCH_RUPTURE = "Ruptura"
CCWATCH_GAROTTE = "Garrote"
CCWATCH_RIPOSTE = "Estocada"
CCWATCH_IMPROVEDKICK = "Patada: silenciado"
CCWATCH_ADRENALINERUSH = "Subid\195\179n de adrenalina"
CCWATCH_EVASION = "Evasi\195\179n"
CCWATCH_ROGUESPRINT = "Correr"
CCWATCH_BLADEFLURRY = "R\195\161faga con espada"
CCWATCH_CRIPPLINGP = "Veneno paralizante"
CCWATCH_DEADLYP = "Veneno mortal"

-- Shaman / Chamán
CCWATCH_FROSTSHOCK = "Choque de Escarcha"
CCWATCH_FLAMESHOCK = "Choque de llamas"
CCWATCH_FROSTBRANDWEAPON = "Arma Estigma de Escarcha"
CCWATCH_STORMSTRIKE = "Golpe de tormenta"

-- Miscellaneous / Micelánea
CCWATCH_WARSTOMP = "Pisot\195\179n de guerra"
CCWATCH_SLEEP = "Dormir"
CCWATCH_NETOMATIC = "Redem\195\161tica"
CCWATCH_ROCKETHELM = "Embestida imprudente"
CCWATCH_WOTF = "Voluntad de los Renegados"
CCWATCH_PERCEPTION = "Percepci\195\179n"

CCWATCH_RANK = "rango"
CCWATCH_DETECTED = "detectado"
CCWATCH_NOTDETECTED = "no detectado"

CCWATCH_ENABLED = "CCWatch habilitado"
CCWATCH_DISABLED = "CCWatch deshabilitado"

CCWATCH_LOCKED = "CCWatch fijado"
CCWATCH_UNLOCKED = "CCWatch liberado"

CCWATCH_INVERSION_ON = "CCWatch inversi\195\179n de barra on"
CCWATCH_INVERSION_OFF = "CCWatch inversi\195\179n de barra off"

CCWATCH_STYLE_CURRENT = "Monitorizando objetivo actual \195\186nicamente"
CCWATCH_STYLE_RECENT = "Monitorizando objetivos recientes"
CCWATCH_STYLE_ALL = "Monitorizando TODOS LOS OBJETIVOS"

CCWATCH_GROW_OFF = "CCWatch prioridad de barra off"
CCWATCH_GROW_UP = "CCWatch prioridad de barra arriba"
CCWATCH_GROW_DOWN = "CCWatch prioridad de barra abajo"

CCWATCH_TIMERS_OFF = "Temporiz. off"
CCWATCH_TIMERS_ON = "Temporiz. on"
CCWATCH_TIMERS_REVERSE = "Temporiz. Inv. (Cuenta atr\195\161s)"

CCWATCH_ARCANIST_ON = "Set Arcanist activado (+15 seg para hechizo "..CCWATCH_POLYMORPH..")"
CCWATCH_ARCANIST_OFF = "Set Arcanist desactivado"

CCWATCH_COLOROVERTIME_ON = "Coloraci\195\179n de Barra en el tiempo activada"
CCWATCH_COLOROVERTIME_OFF = "Coloraci\195\179n de Barra en el tiempo desactivada"
CCWATCH_LEADINGTIMER_ON = "Posici\195\179n Temporiz.: izquierda"
CCWATCH_LEADINGTIMER_OFF = "Posici\195\179n Temporiz.: derecha"
CCWATCH_WARNCC_SETTO = "Modo de Aviso fijado a: "
CCWATCH_WARNCC_CUSTOM = "Control de Multitudes por defecto (control estandar es EMOTE, SAY, PARTY, RAID, YELL): "
CCWATCH_WARN_DISABLED = "Alertas por Chat deshabilitadas"
CCWATCH_WARN_ENABLED = "Alertas por Chat habilitadas"

CCWATCH_SCALE = "CCWatch Escala fijada a "

CCWATCH_WIDTH = "CCWatch Ancho fijado a "

CCWATCH_ALPHA = "CCWatch Alpha fijado a "

CCWATCH_LOADED = "CCWATCH Cargado - Uso: /ccw (c)Elwen&phoenixfire2001 - Traducido por PorkoJones 2006"

CCWATCH_HELP1  = " : Uso - /ccw option"
CCWATCH_HELP2  = "options:"
CCWATCH_HELP3  = " on     : Habilita CCWatch"
CCWATCH_HELP4  = " off    : Deshabilita CCWatch"
CCWATCH_HELP5  = " lock   : Fija y habilita CCWatch"
CCWATCH_HELP6  = " unlock : Permite mover CCWatch"
CCWATCH_HELP7  = " config : Muestra el men\195\186 de configuraci\195\179n!"
CCWATCH_HELP8  = " print  : Reporta la configuraci\195\179n actual"
CCWATCH_HELP9  = " invert : Invierte la direcci\195\179n de la barra de progreso"
CCWATCH_HELP10 = " scale  : Escalado CCWatch, utiliza 0.25 a 3.0"
CCWATCH_HELP11 = " width  : Establece el ancho de la barra, utiliza 50 a 300"
CCWATCH_HELP12 = " alpha  : Establece la transparencia de la barra, utiliza 0 a 1"
CCWATCH_HELP13 = " grow   : Establece el sistema de prioridad de barra: increasing(las barras en el mispo punto se empujan abajo), decreasing(las barras en el mismo punto se empujan arriba) or off(las barras en el mismo punto se sobreescriben)"
CCWATCH_HELP14 = " u      : Actualiza rangos de habilidades mejoradas"
CCWATCH_HELP15 = " timers : Establece la forma de mostrar los temporizadores: off, on(cuenta hacia adelante) o reverted (cuenta atr\195\161s)"
CCWATCH_HELP16 = " warn   : habilita/deshabilita advertencias por chat"
CCWATCH_HELP17 = " warncc : define que canal de comunicaciones usar (EMOTE, SAY, PARTY, RAID, YELL o custom)"

end