---  Variables, don't need translated ---
TITAN_MODMENU_LOC_US = "enUS";
TITAN_MODMENU_LOC_DE = "deDE";
TITAN_MODMENU_LOC_FR = "frFR";
TITAN_MODMENU_SPACER = 42;

---     English     ---
--- by Tekkub (duh) ---
TITAN_MODMENU_MENU_BARTEXT = "WMM";
TITAN_MODMENU_MENU_TEXT = "WoW-Mods Menu";
TITAN_MODMENU_MENU_TEXTRIGHT = "WoW-Mods Menu (right)";
TITAN_MODMENU_MENU_OPENTEXT = "Open Addon";
TITAN_MODMENU_MENU_SETUPTEXT= "Setup Addon";
TITAN_MODMENU_MENU_SYSTEMTEXT = "System Menu";
TITAN_MODMENU_MENU_RELOADUI = "Reload UI";


TITAN_MODMENU_TRADE_SPELLBOOKGENERAL = "General";
TITAN_MODMENU_TRADE_FINDHERB = "Find Herbs";
TITAN_MODMENU_TRADE_FINDORE = "Find Minerals";
TITAN_MODMENU_TRADE_FIRSTAID = "First Aid";
TITAN_MODMENU_TRADE_HERB = "Herbalism";
TITAN_MODMENU_TRADE_MINING = "Mining";
TITAN_MODMENU_TRADE_SMELTING = "Smelting";
TITAN_MODMENU_TRADE_ALCHEMY = "Alchemy";
TITAN_MODMENU_TRADE_TAILOR = "Tailoring";
TITAN_MODMENU_TRADE_BLACKSMITH = "Blacksmithing";
TITAN_MODMENU_TRADE_ENGINEER = "Engineering";
TITAN_MODMENU_TRADE_LEATHER = "Leatherworking";
TITAN_MODMENU_TRADE_SKINNING = "Skinning";
TITAN_MODMENU_TRADE_ENCHANTING = "Enchanting";
TITAN_MODMENU_TRADE_DISENCHANTING = "Disenchant";
TITAN_MODMENU_TRADE_COOKING = "Cooking";
TITAN_MODMENU_TRADE_FISHING = "Fishing";


TITAN_MODMENU_CAT_BAR = "Bar Mods";
TITAN_MODMENU_CAT_INVENTORY = "Inventory Mods";
TITAN_MODMENU_CAT_MAP = "Map Mods";
TITAN_MODMENU_CAT_TRADESKILL = "Tradeskill Mods";
TITAN_MODMENU_CAT_QUEST = "Quest Mods";
TITAN_MODMENU_CAT_COMBAT = "Combat Mods";
TITAN_MODMENU_CAT_CLASS = "Class-Specific Mods";
TITAN_MODMENU_CAT_PVP = "PvP Mods";
TITAN_MODMENU_CAT_CHAT = "Chat Mods";
TITAN_MODMENU_CAT_GUILD = "Guild Mods";
TITAN_MODMENU_CAT_FRIEND = "Friend Mods";
TITAN_MODMENU_CAT_PARTY = "Party Mods";
TITAN_MODMENU_CAT_RAID = "Raid Mods";
TITAN_MODMENU_CAT_COMP = "Compilations";
TITAN_MODMENU_CAT_LIBRARY = "Libraries";
TITAN_MODMENU_CAT_OTHER = "Other UI Mods";
TITAN_MODMENU_CAT_HANDY = "Handy Functions";
TITAN_MODMENU_CAT_TRADESKILLS = "Tradeskills";
TITAN_MODMENU_CAT_EMOTES = "Emotes";
TITAN_MODMENU_CAT_GAMEMENU = "Game Menu";
TITAN_MODMENU_CAT_SYSTEM = "System Menu";
TITAN_MODMENU_CAT_LOADMOD = "Enable/Load Mod";
TITAN_MODMENU_CAT_UNKNOWN = "Unknown Mods";
TITAN_MODMENU_CAT_MMSETTINGS = "ModMenu Settings";
TITAN_MODMENU_CAT_TITAN = "Titan Panel";
TITAN_MODMENU_CAT_TITAN2 = "Titan 2nd Panel";
TITAN_MODMENU_CAT_MODSETS = "Mod Sets";
TITAN_MODMENU_CAT_PORTALS = "Portals";
TITAN_MODMENU_CAT_AUCTION = "Auction House Mods";

TITAN_MODMENU_SETUP = "Setup";
TITAN_MODMENU_TOGGLE = "Toggle";
TITAN_MODMENU_OPEN = "Open";
TITAN_MODMENU_CLOSE = "Close";
TITAN_MODMENU_SHOW = "Show";
TITAN_MODMENU_HIDE = "Hide";
TITAN_MODMENU_LOCK = "Lock";
TITAN_MODMENU_UNLOCK = "Unlock";
TITAN_MODMENU_HELP = "Help";
TITAN_MODMENU_ON = "On";
TITAN_MODMENU_OFF = "Off";
TITAN_MODMENU_ENABLE = "Enable";
TITAN_MODMENU_DISABLE = "Disable";
TITAN_MODMENU_RESET = "Reset";
TITAN_MODMENU_OPTIONS = "Options";
TITAN_MODMENU_BUTTON = "Button";
TITAN_MODMENU_VIEW = "View";
TITAN_MODMENU_AUTOMATIC = "Automatic";
TITAN_MODMENU_STATUS = "Status";
TITAN_MODMENU_DISPLAY = "Display";
TITAN_MODMENU_MINIMAP = "MiniMap";
TITAN_MODMENU_TOGGLEICONTEXT = "Toggle Icon/Text";
TITAN_MODMENU_TOGGLEICON = "Toggle Icon";
TITAN_MODMENU_TOGGLETEXT = "Toggle Text";
TITAN_MODMENU_EXIT1 = "/exit";

---  Français   ---
--- by Xtragedy ---
if ( GetLocale() == "frFR" ) then
	TITAN_MODMENU_MENU_BARTEXT = "WMM";
	TITAN_MODMENU_MENU_TEXT = "WoW-Mods Menu";
	TITAN_MODMENU_MENU_OPENTEXT = "Ouvrir l'Addon";
	TITAN_MODMENU_MENU_SETUPTEXT= "Configuration de l'Addon";
	TITAN_MODMENU_MENU_SYSTEMTEXT = "Menu Syst\195\168me";
	
	TITAN_MODMENU_TRADE_SPELLBOOKGENERAL = "G\195\169n\195\169ral";
	TITAN_MODMENU_TRADE_FINDHERB = "Trouver Herbes";
	TITAN_MODMENU_TRADE_FINDORE = "Trouver Gisements";
	TITAN_MODMENU_TRADE_FIRSTAID = "Secourisme";
	TITAN_MODMENU_TRADE_HERB = "Herboristerie";
	TITAN_MODMENU_TRADE_MINING = "Minage";
	TITAN_MODMENU_TRADE_ALCHEMY = "Alchimie";
	TITAN_MODMENU_TRADE_TAILOR = "Couture";
	TITAN_MODMENU_TRADE_BLACKSMITH = "Forge";
	TITAN_MODMENU_TRADE_ENGINEER = "Ing\195\169nierie";
	TITAN_MODMENU_TRADE_LEATHER = "Travail du cuir";
	TITAN_MODMENU_TRADE_SKINNING = "D\195\169pecage";
	TITAN_MODMENU_TRADE_ENCHANTING = "Enchantement";
	TITAN_MODMENU_TRADE_DISENCHANTING = "D\195\169senchantement";
	TITAN_MODMENU_TRADE_COOKING = "Cuisine";
	TITAN_MODMENU_TRADE_FISHING = "P\195\170che";
	
	TITAN_MODMENU_CAT_BAR = "Mods pour les barres";
	TITAN_MODMENU_CAT_INVENTORY = "Mods pour l'inventaire";
	TITAN_MODMENU_CAT_MAP = "Mods pour les cartes";
	TITAN_MODMENU_CAT_TRADESKILL = "Mods pour les m\195\169tiers";
	TITAN_MODMENU_CAT_QUEST = "Mods pour les qu\195\170tes";
	TITAN_MODMENU_CAT_COMBAT = "Mods pour les combats";
	TITAN_MODMENU_CAT_CLASS = "Mods pour les classes sp\195\169cifiques";
	TITAN_MODMENU_CAT_PVP = "Mods pour le PvP";
	TITAN_MODMENU_CAT_CHAT = "Mods pour le Chat";
	TITAN_MODMENU_CAT_GUILD = "Mods pour la guilde";
	TITAN_MODMENU_CAT_FRIEND = "Mods pour les amis";
	TITAN_MODMENU_CAT_PARTY = "Mods pour le groupe";
	TITAN_MODMENU_CAT_RAID = "Mods pour le raid";
	TITAN_MODMENU_CAT_COMP = "Compilations";
	TITAN_MODMENU_CAT_LIBRARY = "Libraries";
	TITAN_MODMENU_CAT_OTHER = "Autres mods";
	TITAN_MODMENU_CAT_HANDY = "Fonctions manuelles";
	TITAN_MODMENU_CAT_TRADESKILLS = "M\195\169tiers";
	TITAN_MODMENU_CAT_EMOTES = "Emotes";
	TITAN_MODMENU_CAT_GAMEMENU = "Menu du jeu";
	TITAN_MODMENU_CAT_SYSTEM = "Menu syst\195\168me";
	TITAN_MODMENU_CAT_MMSETTINGS = "Param\195\168tres de ModMenu";
	
	TITAN_MODMENU_SETUP = "Configuration";
	TITAN_MODMENU_TOGGLE = "Activer";
	TITAN_MODMENU_OPEN = "Ouvrir";
	TITAN_MODMENU_CLOSE = "Fermer";
	TITAN_MODMENU_SHOW = "Afficher";
	TITAN_MODMENU_HIDE = "Cacher";
	TITAN_MODMENU_LOCK = "Bloquer";
	TITAN_MODMENU_UNLOCK = "D\195\169bloquer";
	TITAN_MODMENU_HELP = "Aide";
	TITAN_MODMENU_ON = "On";
	TITAN_MODMENU_OFF = "Off";
	TITAN_MODMENU_ENABLE = "Valider";
	TITAN_MODMENU_DISABLE = "D\195\169valider";
	TITAN_MODMENU_RESET = "Reset";
	TITAN_MODMENU_OPTIONS = "Options";
	TITAN_MODMENU_BUTTON = "Bouton";
	TITAN_MODMENU_VIEW = "Voir";
	TITAN_MODMENU_AUTOMATIC = "Automatique";
	TITAN_MODMENU_STATUS = "Status";
	TITAN_MODMENU_DISPLAY = "Affichage";
	TITAN_MODMENU_MINIMAP = "MiniCarte";
	TITAN_MODMENU_TOGGLEICONTEXT = "Afficher Icone/Texte";
	TITAN_MODMENU_TOGGLETEXT = "Afficher Texte";
	TITAN_MODMENU_TOGGLEICON = "Afficher Icone";
	TITAN_MODMENU_EXIT1 = "/exit";
end 


---   Deutsch    ---
--- by Chieftain ---
---    ReapeR    ---
---    Crowley   ---
--- and dan2507  ---
if ( GetLocale() == "deDE" ) then
	TITAN_MODMENU_MENU_BARTEXT = "WMM";
	TITAN_MODMENU_MENU_TEXT = "WoW-Mods Men\195\188";
	TITAN_MODMENU_MENU_TEXTRIGHT = "WoW-Mods Men\195\188 (rechts)";
	TITAN_MODMENU_MENU_OPENTEXT = "Addon \195\182ffnen";
	TITAN_MODMENU_MENU_SETUPTEXT= "Addon konfigurieren";
	TITAN_MODMENU_MENU_SYSTEMTEXT = "System Menu";
	
	TITAN_MODMENU_SETUP = "Einstellungen";
	TITAN_MODMENU_TOGGLE = "Aktivieren";
	TITAN_MODMENU_OPEN = "\195\150ffnen";
	TITAN_MODMENU_CLOSE = "Schlie\195\159en";
	TITAN_MODMENU_SHOW = "Zeigen";
	TITAN_MODMENU_HIDE = "Verstecken";
	TITAN_MODMENU_LOCK = "Sperren";
	TITAN_MODMENU_UNLOCK = "Entsperren";
	TITAN_MODMENU_HELP = "Hilfe";
	TITAN_MODMENU_ON = "An";
	TITAN_MODMENU_OFF = "Aus";
	TITAN_MODMENU_ENABLE = "Aktivieren";
	TITAN_MODMENU_DISABLE = "Deaktivieren";
	TITAN_MODMENU_RESET = "Reset";
	TITAN_MODMENU_OPTIONS = "Optionen";
	TITAN_MODMENU_BUTTON = "Schalter";
	TITAN_MODMENU_VIEW = "Ansicht";
	TITAN_MODMENU_AUTOMATIC = "Automatisch";
	TITAN_MODMENU_STATUS = "Status";
	TITAN_MODMENU_DISPLAY = "Anzeigen";
	TITAN_MODMENU_MINIMAP = "MiniMap";
	TITAN_MODMENU_TOGGLEICONTEXT = "Icon/Text Ein-/Ausschalten";
	TITAN_MODMENU_TOGGLETEXT = "Text Ein-/Ausschalten";
	TITAN_MODMENU_TOGGLEICON = "Icon Ein-/Ausschalten";
	TITAN_MODMENU_EXIT1 = "/beenden";
	
	TITAN_MODMENU_CAT_BAR = "Aktionsleisten Addons";
	TITAN_MODMENU_CAT_INVENTORY = "Inventar Addons";
	TITAN_MODMENU_CAT_MAP = "Karten Addons";
	TITAN_MODMENU_CAT_TRADESKILL = "Handwerk Addons";
	TITAN_MODMENU_CAT_QUEST = "Quest Addons";
	TITAN_MODMENU_CAT_COMBAT = "Kampf Addons";
	TITAN_MODMENU_CAT_CLASS = "Klassen spezifische Addons";
	TITAN_MODMENU_CAT_PVP = "PvP Addons";
	TITAN_MODMENU_CAT_CHAT = "Chat Addons";
	TITAN_MODMENU_CAT_GUILD = "Gilden Addons";
	TITAN_MODMENU_CAT_FRIEND = "Freundesliste Addons";
	TITAN_MODMENU_CAT_PARTY = "Gruppen Addons";
	TITAN_MODMENU_CAT_RAID = "Raid Addons";
	TITAN_MODMENU_CAT_HANDY = "Wichtige Funktionen";
	TITAN_MODMENU_CAT_EMOTES = "Emotes";
	TITAN_MODMENU_CAT_OTHER = "Weitere Addons ";
	TITAN_MODMENU_CAT_GAMEMENU = "Spiel Menu";
	TITAN_MODMENU_CAT_SYSTEM = "System Menu";
	TITAN_MODMENU_CAT_MMSETTINGS = "Addons Menu Optionen";
	TITAN_MODMENU_CAT_TITAN = "Titan Panel";
	TITAN_MODMENU_CAT_TITAN2 = "Titan 2nd Panel";
	TITAN_MODMENU_CAT_MODSETS = "Mod Sets";
	TITAN_MODMENU_CAT_PORTALS = "Portale";
	TITAN_MODMENU_CAT_AUCTION = "Auktionshaus Addons";
	
	TITAN_MODMENU_TRADE_SPELLBOOKGENERAL = "Allgemein";
	TITAN_MODMENU_TRADE_FINDHERB = "Kr\195\164utersuche";
	TITAN_MODMENU_TRADE_FINDORE = "Mineraliensuche";
	TITAN_MODMENU_TRADE_FIRSTAID = "Erste Hilfe";
	TITAN_MODMENU_TRADE_HERB = "Kr\195\164uterkunde";
	TITAN_MODMENU_TRADE_MINING = "Bergbau";
	TITAN_MODMENU_TRADE_ALCHEMY = "Alchimie";
	TITAN_MODMENU_TRADE_TAILOR = "Schneiderei";
	TITAN_MODMENU_TRADE_BLACKSMITH = "Schmiedekunst";
	TITAN_MODMENU_TRADE_ENGINEER = "Ingenieurskunst";
	TITAN_MODMENU_TRADE_LEATHER = "Lederverarbeitung";
	TITAN_MODMENU_TRADE_SKINNING = "K\195\188rschnerei";
	TITAN_MODMENU_TRADE_ENCHANTING = "Verzauberkunst";
	TITAN_MODMENU_TRADE_DISENCHANTING = "Entzaubern";
	TITAN_MODMENU_TRADE_COOKING = "Kochkunst";
	TITAN_MODMENU_TRADE_FISHING = "Angeln"; 
end 