local L = AceLibrary("AceLocale-2.2"):new("sRaidFrames")

-------------------------------------------------------------------------------
-- Localization                                                              --
-------------------------------------------------------------------------------

L:RegisterTranslations("koKR", function() return {
	["hidden"] = "숨겨짐",
	["shown"] = "표시됨",

	["Lock"] = "고정",
	["Lock/Unlock the raid frames"] = "공격대창 고정/이동",
	["Unlocked"] = "이동됨",
	["Locked"] = "고정됨",

	["Health text"] = "생명력 글자",
	["Set health display type"] = "생명력 표시 선택",
	["Current and max health"] = "현재와 최대 생명력",
	["Health deficit"] = "생명력 손실",
	["Health percentage"] = "생명력 퍼센트",
	["Current health"] = "현재 생명력",
	["Hide health text"] = "생명력 글자 숨김",
	
	["Invert health bars"] = "생명력 바 반전",
	["Invert the growth of the health bars"] = "생명력 바의 진행 방향을 반전합니다",
	
	["Buff filter"] = "버프 필터",
	["Set buff filter"] = "버프 필터 설정",
	["Add buff"] = "버프 추가",
	["Add a buff"] = "버프를 추가합니다.",
	["<name of buff>"] = "<버프명>",

	["Show group titles"] = "파티 제목 표시",
	["Toggle display of titles above each group frame"] = "각 파티 프레임위에 파티 제목 표시 전환",
	["Member sort order"] = "파티원 정렬 순서",
	["Select how you wish to sort the members of each group"] = "각 파티원 정렬 방법 선택",
	["By name"] = "이름으로",
	["By class"] = "직업으로",
	["Blizzard default"] = "게임 기본값",
	["Group by"] = "파티 구분",
	["Select how you wish to show the groups"] = "파티 표시 방법 선택",
	["By group"] = "파티별",
	["By class"] = "직업별",

	["Buff/Debuff visibility"] = "버프/디버프 표시",
	["Show buffs or debuffs on the raid frames"] = "공격대창에 버프/디버프 표시",
	["Only buffs"] = "버프만",
	["Only debuffs"] = "디버프만",
	["Buffs if not debuffed"] = "디버프가 없으면 버프",
	["Power type visiblity"] = "효과 종류 표시",
	["Toggle the display of certain power types (Mana, Rage, Energy)"] = "특정 효과 종류의 표시 전환(마나, 분노, 기력)",
	["Mana"] = "마나",
	["Toggle the display of mana bars"] = "마나바 표시 전환",
	["Energy & Focus"] = "기력 & 초점",
	["Toggle the display of energy and focus bars"] = "기력과 초점바 표시 전환",
	["Rage"] = "분노",
	["Toggle the display of rage bars"] = "분노바 표시 전환",
	["Filter dispellable debuffs"] = "해제 가능한 디버프 필터",
	["Toggle display of dispellable debuffs only"] = "해제 가능한 디버프만 표시 전환",

	["Bar textures"] = "바 텍스쳐",
	["Set the texture used on health and mana bars"] = "생명력과 마나바에 사용되는 텍스쳐 설정",

	["Scale"] = "크기",
	["Set the scale of the raid frames"] = "공격대창의 크기 설정",
	["Layout"] = "레이아웃",
	["Set the layout of the raid frames"] = "공격대창의 레이아웃 설정",
	["Reset layout"] = "레이아웃 초기화",
	["Reset the position of sRaidFrames"] = "sRaidFrames의 위치 초기화",
	["Predefined Layout"] = "미리 정의된 레이아웃",
	["Set a predefined layout for the raid frames"] = "미리 정의된 레이아웃 설정",
	["CT_RaidAssist"] = "공격대 도우미형",
	["Horizontal"] = "수평형",
	["Vertical"] = "수직형",

	["Background color"] = "배경 색상",
	["Change the background color"] = "배경 색상 변경",
	["Border color"] = "테두리 색상",
	["Change the border color"] = "테두리 색상 변경",
	["Tooltip display"] = "툴팁 표시",
	["Unit tooltips"] = "유니트 툴팁",
	["Debuff tooltips"] = "디버프 툴팁",
	["Buff tooltips"] = "버프 툴팁",
	["Determine when a tooltip is displayed"] = "툴팁 표시할 시점 결정",
	["Never"] = "사용하지 않음",
	["Only when not in combat"] = "전투중이 아닐 때만",
	["Always"] = "항상 사용",

	["Highlight units with aggro"] = "어그로 대상 강조",
	["Turn the border of units who have aggro red"] = "어그로를 가진 대상의 테두리를 빨간색으로 변경",
	["Highlight targetted unit"] = "선택가능 구성원 강조",
	["Turn the border of unit you are targetting orange"] = "선택 범위 내의 구성원의 외곽선을 표시합니다",
	["Range"] = "범위",
	["Set about range"] = "범위에 대한 설정",
	["Enable range check"] = "범위 체크 활성화",
	["Enable range checking"] = "범위 체크를 활성화",

	["Alpha"] = "투명도",
	["The alpha level for units who are out of range"] = "범위 밖인 대상의 투명도",
	["Frequency"] = "주기",
	["The interval between which range checks are performed"] = "범위 체크 간격",

	["Show Group/Class"] = "파티/직업 표시",
	["Toggle the display of certain Groups/Classes"] = "특정 파티/직업의 표시 전환",
	["Classes"] = "직업",
	["Warriors"] = "전사",
	["Toggle the display of Warriors"] = "전사들의 표시 전환",
	["Paladins"] = "성기사",
	["Toggle the display of Paladins"] = "성기사들의 표시 전환",
	["Shamans"] = "주술사",
	["Toggle the display of Shamans"] = "주술사들의 표시 전환",
	["Hunters"] = "사냥꾼",
	["Toggle the display of Hunters"] = "사냥꾼들의 표시 전환",
	["Warlocks"] = "흑마법사",
	["Toggle the display of Warlocks"] = "흑마법사들의 표시 전환",
	["Mages"] = "마법사",
	["Toggle the display of Mages"] = "마법사들의 표시 전환",
	["Druids"] = "드루이드",
	["Toggle the display of Druids"] = "드루이드들의 표시 전환",
	["Rogues"] = "도적",
	["Toggle the display of Rogues"] = "도적들의 표시 전환",
	["Priests"] = "사제",
	["Toggle the display of Priests"] = "사제들의 표시 전환",

	["Groups"] = "파티",
	["Group 1"] = "1 파티",
	["Toggle the display of Group 1"] = "1 파티의 표시 전환",
	["Group 2"] = "2 파티",
	["Toggle the display of Group 2"] = "2 파티의 표시 전환",
	["Group 3"] = "3 파티",
	["Toggle the display of Group 3"] = "3 파티의 표시 전환",
	["Group 4"] = "4 파티",
	["Toggle the display of Group 4"] = "4 파티의 표시 전환",
	["Group 5"] = "5 파티",
	["Toggle the display of Group 5"] = "5 파티의 표시 전환",
	["Group 6"] = "6 파티",
	["Toggle the display of Group 6"] = "6 파티의 표시 전환",
	["Group 7"] = "7 파티",
	["Toggle the display of Group 7"] = "7 파티의 표시 전환",
	["Group 8"] = "8 파티",
	["Toggle the display of Group 8"] = "8 파티의 표시 전환",

	["Growth"] = "생성 방향",
	["Set the growth of the raid frames"] = "공격대창의 생성 방향 설정",
	["Up"] = "위쪽",
	["Down"] = "아래쪽",
	["Left"] = "왼쪽",
	["Right"] = "오른쪽",

	["Border"] = "테두리",
	["Toggle the display of borders around the raid frames"] = "공격대창 주변 테두리의 표시 전환",
	["Frame Spacing"] = "창 간격",
	["Set the spacing between each of the raid frames"] = "공격대창 각각의 사이 간격 설정",

	["Offline"] = "오프라인",
	["Released"] = "유령",
	["Dead"] = "죽음",
	["Resurrected"] = "부활됨",
	["Can Recover"] = "부활가능",
	["Feign Death"] = "죽은척",
	["Unknown"] = "알수없음",

	["Warrior"] = "전사",
	["Mage"] = "마법사",
	["Paladin"] = "성기사",
	["Shaman"] = "주술사",
	["Druid"] = "드루이드",
	["Hunter"] = "사냥꾼",
	["Rogue"] = "도적",
	["Warlock"] = "흑마법사",
	["Priest"] = "사제",

	["Intervened"] = "중재",
	["Innervating"] = "자극",
	["Spirit"] = "구원",
	["Shield Wall"] = "방벽",
	["Last stand"] = "최후의 저항",
	["Gift of Life"] = "생명의 보석",
	["Ice block"] = "얼방",
	["Vanished"] = "소멸",
	["Stealthed"] = "은신",
	["Infused"] = "주입",
	["Fear Ward"] = "수호물",
	["Protection"] = "보축",
	["Divine Shield"] = "무적",
	["Shadowform"] = "형상",

	["Right-click for options."] = "우클릭시 설정창을 표시합니다.",
} end)
