local L = AceLibrary("AceLocale-2.2"):new("sRaidFrames")

-------------------------------------------------------------------------------
-- Localization                                                              --
-------------------------------------------------------------------------------

L:RegisterTranslations("enUS", function() return {
	["hidden"] = true,
	["shown"] = true,

	["Lock"] = true,
	["Lock/Unlock the raid frames"] = true,
	["Unlocked"] = true,
	["Locked"] = true,

	["Health text"] = true,
	["Set health display type"] = true,
	["Current and max health"] = true,
	["Health deficit"] = true,
	["Health percentage"] = true,
	["Current health"] = true,
	["Hide health text"] = true,

	["Invert health bars"] = true,
	["Invert the growth of the health bars"] = true,

	["Buff filter"] = true,
	["Set buff filter"] = true,
	["Add buff"] = true,
	["Add a buff"] = true,
	["<name of buff>"] = true,

	["Show group titles"] = true,
	["Toggle display of titles above each group frame"] = true,
	["Member sort order"] = true,
	["Select how you wish to sort the members of each group"] = true,
	["By name"] = true,
	["By class"] = true,
	["Blizzard default"] = true,
	["Group by"] = true,
	["Select how you wish to show the groups"] = true,
	["By group"] = true,
	["By class"] = true,

	["Buff/Debuff visibility"] = true,
	["Show buffs or debuffs on the raid frames"] = true,
	["Only buffs"] = true,
	["Only debuffs"] = true,
	["Buffs if not debuffed"] = true,
	["Power type visiblity"] = true,
	["Toggle the display of certain power types (Mana, Rage, Energy)"] = true,
	["Mana"] = true,
	["Toggle the display of mana bars"] = true,
	["Energy & Focus"] = true,
	["Toggle the display of energy and focus bars"] = true,
	["Rage"] = true,
	["Toggle the display of rage bars"] = true,
	["Filter dispellable debuffs"] = true,
	["Toggle display of dispellable debuffs only"] = true,

	["Bar textures"] = true,
	["Set the texture used on health and mana bars"] = true,

	["Scale"] = true,
	["Set the scale of the raid frames"] = true,
	["Layout"] = true,
	["Set the layout of the raid frames"] = true,
	["Reset layout"] = true,
	["Reset the position of sRaidFrames"] = true,
	["Predefined Layout"] = true,
	["Set a predefined layout for the raid frames"] = true,
	["CT_RaidAssist"] = true,
	["Horizontal"] = true,
	["Vertical"] = true,

	["Background color"] = true,
	["Change the background color"] = true,
	["Border color"] = true,
	["Change the border color"] = true,
	["Tooltip display"] = true,
	["Unit tooltips"] = true,
	["Debuff tooltips"] = true,
	["Buff tooltips"] = true,
	["Determine when a tooltip is displayed"] = true,
	["Never"] = true,
	["Only when not in combat"] = true,
	["Always"] = true,

	["Highlight units with aggro"] = true,
	["Turn the border of units who have aggro red"] = true,
	["Highlight targetted unit"] = true,
	["Turn the border of unit you are targetting orange"] = true,
	["Range"] = true,
	["Set about range"] = true,
	["Enable range check"] = true,
	["Enable range checking"] = true,

	["Alpha"] = true,
	["The alpha level for units who are out of range"] = true,
	["Frequency"] = true,
	["The interval between which range checks are performed"] = true,

	["Show Group/Class"] = true,
	["Toggle the display of certain Groups/Classes"] = true,
	["Classes"] = true,
	["Warriors"] = true,
	["Toggle the display of Warriors"] = true,
	["Paladins"] = true,
	["Toggle the display of Paladins"] = true,
	["Shamans"] = true,
	["Toggle the display of Shamans"] = true,
	["Hunters"] = true,
	["Toggle the display of Hunters"] = true,
	["Warlocks"] = true,
	["Toggle the display of Warlocks"] = true,
	["Mages"] = true,
	["Toggle the display of Mages"] = true,
	["Druids"] = true,
	["Toggle the display of Druids"] = true,
	["Rogues"] = true,
	["Toggle the display of Rogues"] = true,
	["Priests"] = true,
	["Toggle the display of Priests"] = true,

	["Groups"] = true,
	["Group 1"] = true,
	["Toggle the display of Group 1"] = true,
	["Group 2"] = true,
	["Toggle the display of Group 2"] = true,
	["Group 3"] = true,
	["Toggle the display of Group 3"] = true,
	["Group 4"] = true,
	["Toggle the display of Group 4"] = true,
	["Group 5"] = true,
	["Toggle the display of Group 5"] = true,
	["Group 6"] = true,
	["Toggle the display of Group 6"] = true,
	["Group 7"] = true,
	["Toggle the display of Group 7"] = true,
	["Group 8"] = true,
	["Toggle the display of Group 8"] = true,

	["Growth"] = true,
	["Set the growth of the raid frames"] = true,
	["Up"] = true,
	["Down"] = true,
	["Left"] = true,
	["Right"] = true,

	["Border"] = true,
	["Toggle the display of borders around the raid frames"] = true,
	["Frame Spacing"] = true,
	["Set the spacing between each of the raid frames"] = true,

	["Offline"] = true,
	["Released"] = true,
	["Dead"] = true,
	["Resurrected"] = true,
	["Can Recover"] = true,
	["Feign Death"] = true,
	["Unknown"] = true,

	["Warrior"] = true,
	["Mage"] = true,
	["Paladin"] = true,
	["Shaman"] = true,
	["Druid"] = true,
	["Hunter"] = true,
	["Rogue"] = true,
	["Warlock"] = true,
	["Priest"] = true,

	["Intervened"] = true,
	["Innervating"] = true,
	["Spirit"] = true,
	["Gift of Life"] = true,
	["Vanished"] = true,
	["Stealthed"] = true,
	["Infused"] = true,
	["Protection"] = true,

	["Right-click for options."] = true,
} end)
