local L = AceLibrary("AceLocale-2.2"):new("sRaidFrames")

-------------------------------------------------------------------------------
-- Localization                                                              --
-------------------------------------------------------------------------------

L:RegisterTranslations("frFR", function() return {
	["hidden"] = "cacher",
	["shown"] = "afficher",

	["Lock"] = "V\195\169rouiller",
	["Lock/Unlock the raid frames"] = "V\195\169rouille/d\195\169v\195\169rouille les fen\195\170tre de raid",
	["Unlocked"] = "D\195\169v\195\169rouill\195\169",
	["Locked"] = "V\195\169rouill\195\169",

	["Health text"] = "Point de vie",
	["Set health display type"] = "Type d'affichage pour les points de vie",
	["Current and max health"] = "Point de vie actuel et max",
	["Health deficit"] = "D\195\169ficite de point de vie",
	["Health percentage"] = "Pourcentage de vie",
	["Current health"] = "Point de vie actuel",
	["Hide health text"] = "Cacher les points de vie",

	["Invert health bars"] = "Inversion des barres de vie",
	["Invert the growth of the health bars"] = "Inverse le remplissage des barres de vie",

	["Buff filter"] = "Filtre des buffs",
	["Set buff filter"] = "Placer un filtre",
	["Add buff"] = "Ajouter le buff",
	["Add a buff"] = "Ajouter un buff",
	["<name of buff>"] = "<Nom du buff>",

	["Show group titles"] = "Afficher le titre des groupes",
	["Toggle display of titles above each group frame"] = "Active/d\195\169sactive le titre au dessus de chaque fen\195\170tre de groupe",
	["Member sort order"] = "type de trie sur les membres",
	["Select how you wish to sort the members of each group"] = "S\195\169lectionner le type de trie que vous souhaitez utiliser sur les membres de chaque groupe",
	["By name"] = "Par nom",
	["By class"] = "Par classe",
	["Blizzard default"] = "M\195\169thode Blizzard",
	["Group by"] = "Grouper par",
	["Select how you wish to show the groups"] = "S\195\169lectionner le type d'affichage pour les groupes",
	["By group"] = "Par groupe",
	["By class"] = "Par classe",

	["Buff/Debuff visibility"] = "Visibilit\195\169 des buff/d\195\169buffs",
	["Show buffs or debuffs on the raid frames"] = "Afficher les buffs ou debuffs dans les fen\195\170tre de raid",
	["Only buffs"] = "Que les buffs",
	["Only debuffs"] = "Que les d\195\169buffs",
	["Buffs if not debuffed"] = "Les buffs si pas d\195\169buffer",
	["Power type visiblity"] = "Visibilit\195\169 du type d'\195\169nergie",
	["Toggle the display of certain power types (Mana, Rage, Energy)"] = "Active/d\195\169sactive l'affichage des types d'\195\169nergies (Mana, Rage, Energie)",
	["Mana"] = "Mana",
	["Toggle the display of mana bars"] = "Active/d\195\169sactive l'affichage des barres de mana",
	["Energy & Focus"] = "Energie et Focus",
	["Toggle the display of energy and focus bars"] = "Active/d\195\169sactive l'affichage des barres d'\195\169nergie et de focus",
	["Rage"] = "Rage",
	["Toggle the display of rage bars"] = "Active/d\195\169sactive l'affichage des barres de rage",
	["Filter dispellable debuffs"] = "Filtrer les d\195\169buffs abolissables",
	["Toggle display of dispellable debuffs only"] = "Active/d\195\169sactive l'affichage des d\195\169buffs abolissables",

	["Bar textures"] = "Texture des barres",
	["Set the texture used on health and mana bars"] = "D\195\169finie une texture appliqu\195\169e sur les barres de vie et de mana",

	["Scale"] = "Echelle",
	["Set the scale of the raid frames"] = "D\195\169finie l'echelle des fen\195\170tres de raid",
	["Layout"] = "Disposition",
	["Set the layout of the raid frames"] = "D\195\169finie la dispostion des fen\195\170tres de raid",
	["Reset layout"] = "R\195\169initialise la disposition",
	["Reset the position of sRaidFrames"] = "R\195\169initialise la position de sRaidFrame",
	["Predefined Layout"] = "Disposition pr\195\169d\195\169finie",
	["Set a predefined layout for the raid frames"] = "Utiliser une disposition pr\195\169d\195\169finie pour les fen\195\170tres de raid",
	["CT_RaidAssist"] = "CT_RaidAssist",
	["Horizontal"] = "Horizontale",
	["Vertical"] = "Verticale",

	["Background color"] = "Couleur du fond",
	["Change the background color"] = "Change la couleur du fond",
	["Border color"] = "Couleur de la bordure",
	["Change the border color"] = "Change la couleur de la bordure",
	["Tooltip display"] = "Affichage des bulles d'aide",
	["Unit tooltips"] = "Bulles d'aide des unit\195\169",
	["Debuff tooltips"] = "Bulles d'aide des d\195\169buff",
	["Buff tooltips"] = "Bulles d'aide des buffs",
	["Determine when a tooltip is displayed"] = "D\195\169termine quand une bulle sera affich\195\169e",
	["Never"] = "Jamais",
	["Only when not in combat"] = "Seulement hors combat",
	["Always"] = "Toujours",

	["Highlight units with aggro"] = "Surligne l'unit\195\169 ayant l'aggro",
	["Turn the border of units who have aggro red"] = "Change la couleur de bordure de l'unit\195\169 ayant l'aggro en rouge",
	["Range"] = "Distance",
	["Set about range"] = "D\195\169finie une distance",
	["Enable range check"] = "Active la v\195\169rification de la distance",
	["Enable range checking"] = "Active la v\195\169rification de la distance",

	["Alpha"] = "Transparence",
	["The alpha level for units who are out of range"] = "Niveau de transparence des unit\195\169s hors-de-port\195\169es",
	["Frequency"] = "Fr\195\169quence",
	["The interval between which range checks are performed"] = "Intervalle entre deux v\195\169rification de la distance",

	["Show Group/Class"] = "Afficher les groupes/Classes",
	["Toggle the display of certain Groups/Classes"] = "Active/d\195\169sactive l'affichage de certains groupes ou classes",
	["Classes"] = "Classes",
	["Warriors"] = "Guerriers",
	["Toggle the display of Warriors"] = "Active/d\195\169sactive l'affichage des guerriers",
	["Paladins"] = "Paladins",
	["Toggle the display of Paladins"] = "Active/d\195\169sactive l'affichage des paladins",
	["Shamans"] = "Shamans",
	["Toggle the display of Shamans"] = "Active/d\195\169sactive l'affichage des Shamans",
	["Hunters"] = "Chasseurs",
	["Toggle the display of Hunters"] = "Active/d\195\169sactive l'affichage des chasseurs",
	["Warlocks"] = "D\195\169monistes",
	["Toggle the display of Warlocks"] = "Active/d\195\169sactive l'affichage des d\195\169monsites",
	["Mages"] = "Mages",
	["Toggle the display of Mages"] = "Active/d\195\169sactive l'affichage des mages",
	["Druids"] = "Druides",
	["Toggle the display of Druids"] = "Active/d\195\169sactive l'affichage des  druides",
	["Rogues"] = "Voleurs",
	["Toggle the display of Rogues"] = "Active/d\195\169sactive l'affichage des  voleurs",
	["Priests"] = "Pr\195\170tres",
	["Toggle the display of Priests"] = "Active/d\195\169sactive l'affichage des pr\195\170tres",

	["Groups"] = "Groupes",
	["Group 1"] = "Groupe 1",
	["Toggle the display of Group 1"] = "Active/d\195\169sactive l'affichage du groupe 1",
	["Group 2"] = "Groupe 2",
	["Toggle the display of Group 2"] = "Active/d\195\169sactive l'affichage du groupe 2",
	["Group 3"] = "Groupe 3",
	["Toggle the display of Group 3"] = "Active/d\195\169sactive l'affichage du groupe 3",
	["Group 4"] = "Groupe 4",
	["Toggle the display of Group 4"] = "Active/d\195\169sactive l'affichage du groupe 4",
	["Group 5"] = "Groupe 5",
	["Toggle the display of Group 5"] = "Active/d\195\169sactive l'affichage du groupe 5",
	["Group 6"] = "Groupe 6",
	["Toggle the display of Group 6"] = "Active/d\195\169sactive l'affichage du groupe 6",
	["Group 7"] = "Groupe 7",
	["Toggle the display of Group 7"] = "Active/d\195\169sactive l'affichage du groupe 7",
	["Group 8"] = "Groupe 8",
	["Toggle the display of Group 8"] = "Active/d\195\169sactive l'affichage du groupe 8",

	["Growth"] = "Croissance",
	["Set the growth of the raid frames"] = "D\195\169finie la croissance des fen\195\170tres de raid",
	["Up"] = "Vers le haut",
	["Down"] = "Vers la bas",
	["Left"] = "A gauche",
	["Right"] = "A droite",

	["Border"] = "Bordure",
	["Toggle the display of borders around the raid frames"] = "Active/d\195\169sactive l'affichage de la brodure autours des fen\195\170tres de raid",
	["Frame Spacing"] = "Espacement des fen\195\170tres",
	["Set the spacing between each of the raid frames"] = "D\195\169finie l'espacement entre chaque fen\195\170tre du raid",

	["Offline"] = "Hors-ligne",
	["Released"] = "Lib\195\169r\195\169",
	["Dead"] = "Mort",
	["Resurrected"] = "R\195\169ssucit\195\169",
	["Can Recover"] = "Peut revenir",
	["Feign Death"] = "Feint la mort",
	["Unknown"] = "Inconnu",

	["Warrior"] = "Guerrier",
	["Mage"] = "Mage",
	["Paladin"] = "Paladin",
	["Shaman"] = "Shaman",
	["Druid"] = "Druide",
	["Hunter"] = "Chasseur",
	["Rogue"] = "Voleur",
	["Warlock"] = "D\195\169moniste",
	["Priest"] = "Pr\195\170tre",

	["Intervened"] = "Intervention",
	["Innervating"] = "Innervation",
	["Spirit"] = "Esprit",
	["Shield Wall"] = "Mur protecteur",
	["Last stand"] = "Dernier rempart",
	["Gift of Life"] = "Don de vie",
	["Ice block"] = "Bloc de glace",
	["Vanished"] = "Disparu",
	["Stealthed"] = "Camoufl\195\169",
	["Infused"] = "Infusion",
	["Fear Ward"] = "Gardien de peur",
	["Protection"] = "Protection",
	["Divine Shield"] = "Bouclier divin",

	["Right-click for options."] = "Click-droit pour les options",
} end)
