-- duration are in seconds
-- This file keeps the duration of each sound in default pack
local x = "Interface\\AddOns\\BGSoundAlerts\\DefaultPack\\";

BGSoundAlerts_DefaultPackDurations = { };

BGSoundAlerts_DefaultPackDurations[1] = { dir = x .. "Alliance0Horde1.wav", duration = 2.70 };
BGSoundAlerts_DefaultPackDurations[2] = { dir = x .. "Alliance0Horde2.wav", duration = 2.62 };
BGSoundAlerts_DefaultPackDurations[3] = { dir = x .. "Alliance1Horde0.wav", duration = 2.79 };
BGSoundAlerts_DefaultPackDurations[4] = { dir = x .. "Alliance1Horde1.wav", duration = 2.80 };
BGSoundAlerts_DefaultPackDurations[5] = { dir = x .. "Alliance1Horde2.wav", duration = 2.05 };
BGSoundAlerts_DefaultPackDurations[6] = { dir = x .. "Alliance2Horde0.wav", duration = 2.20 };
BGSoundAlerts_DefaultPackDurations[7] = { dir = x .. "Alliance2Horde1.wav", duration = 2.88 };
BGSoundAlerts_DefaultPackDurations[8] = { dir = x .. "Alliance2Horde2.wav", duration = 2.69 };
BGSoundAlerts_DefaultPackDurations[9] = { dir = x .. "AllianceAirLaunching.wav", duration = 1.89 };
BGSoundAlerts_DefaultPackDurations[10] = { dir = x .. "AllianceAssaultedBlacksmith", duration = 2.17 };
BGSoundAlerts_DefaultPackDurations[11] = { dir = x .. "AllianceAssaultedFarm.wav", duration = 2.13 };
BGSoundAlerts_DefaultPackDurations[12] = { dir = x .. "AllianceAssaultedFrostwolfAidStation.wav", duration = 3.19 };
BGSoundAlerts_DefaultPackDurations[13] = { dir = x .. "AllianceAssaultedFrostwolfGraveyard.wav", duration = 3.12 };
BGSoundAlerts_DefaultPackDurations[14] = { dir = x .. "AllianceAssaultedGoldMine.wav", duration = 2.57 };
BGSoundAlerts_DefaultPackDurations[15] = { dir = x .. "AllianceAssaultedIcebloodGraveyard.wav", duration = 2.99 };
BGSoundAlerts_DefaultPackDurations[16] = { dir = x .. "AllianceAssaultedLumbermill.wav", duration = 2.43 };
BGSoundAlerts_DefaultPackDurations[17] = { dir = x .. "AllianceAssaultedSnowfallGraveyard.wav", duration = 2.95 };
BGSoundAlerts_DefaultPackDurations[18] = { dir = x .. "AllianceAssaultedStables.wav", duration = 2.28 };
BGSoundAlerts_DefaultPackDurations[19] = { dir = x .. "AllianceAssaultedStonehearthGraveyard.wav", duration = 2.91 };
BGSoundAlerts_DefaultPackDurations[20] = { dir = x .. "AllianceAssaultedStormpikeAidStation.wav", duration = 2.71 };
BGSoundAlerts_DefaultPackDurations[21] = { dir = x .. "AllianceAssaultedStormpikeGraveyard.wav", duration = 2.68 };
BGSoundAlerts_DefaultPackDurations[22] = { dir = x .. "AllianceFlagCaptured.wav", duration = 4.38 };
BGSoundAlerts_DefaultPackDurations[23] = { dir = x .. "AllianceFlagReturned.wav", duration = 2.36 };
BGSoundAlerts_DefaultPackDurations[24] = { dir = x .. "AllianceFlagTaken.wav", duration = 1.72 };
BGSoundAlerts_DefaultPackDurations[25] = { dir = x .. "AllianceGeneralUnderAttack.wav", duration = 3.75 };
BGSoundAlerts_DefaultPackDurations[26] = { dir = x .. "AllianceLaunchingRamRiders.wav", duration = 2.51 };
BGSoundAlerts_DefaultPackDurations[27] = { dir = x .. "AllianceLaunchingUltimateUnit.wav", duration = 4.33 };
BGSoundAlerts_DefaultPackDurations[28] = { dir = x .. "AllianceTakenBlacksmith.wav", duration = 2.61 };
BGSoundAlerts_DefaultPackDurations[29] = { dir = x .. "AllianceTakenColdtoothMine.wav", duration = 2.92 };
BGSoundAlerts_DefaultPackDurations[30] = { dir = x .. "AllianceTakenFarm.wav", duration = 2.11 };
BGSoundAlerts_DefaultPackDurations[31] = { dir = x .. "AllianceTakenFrostwolfAidStation.wav", duration = 3.31 };
BGSoundAlerts_DefaultPackDurations[32] = { dir = x .. "AllianceTakenFrostwolfGraveyard.wav", duration = 2.91 };
BGSoundAlerts_DefaultPackDurations[33] = { dir = x .. "AllianceTakenGoldMine.wav", duration = 2.20 };
BGSoundAlerts_DefaultPackDurations[34] = { dir = x .. "AllianceTakenIcebloodGraveyard.wav", duration = 3.09 };
BGSoundAlerts_DefaultPackDurations[35] = { dir = x .. "AllianceTakenIrondeepMine.wav", duration = 2.85 };
BGSoundAlerts_DefaultPackDurations[36] = { dir = x .. "AllianceTakenLumbermill.wav", duration = 2.85 };
BGSoundAlerts_DefaultPackDurations[37] = { dir = x .. "AllianceTakenSnowfallGraveyard.wav", duration = 3.18 };
BGSoundAlerts_DefaultPackDurations[38] = { dir = x .. "AllianceTakenStables.wav", duration = 2.39 };
BGSoundAlerts_DefaultPackDurations[39] = { dir = x .. "AllianceTakenStonehearthGraveyard.wav", duration = 3.28 };
BGSoundAlerts_DefaultPackDurations[40] = { dir = x .. "AllianceTakenStormpikeAidStation.wav", duration = 3.29 };
BGSoundAlerts_DefaultPackDurations[41] = { dir = x .. "AllianceTakenStormpikeGraveyard.wav", duration = 3.33 };
BGSoundAlerts_DefaultPackDurations[42] = { dir = x .. "AllianceUpgradingUnits.wav", duration = 2.49 };
BGSoundAlerts_DefaultPackDurations[43] = { dir = x .. "CaptainBalindaStonehearthUnderAttack.wav", duration = 2.98 };
BGSoundAlerts_DefaultPackDurations[44] = { dir = x .. "CaptainGalvangarUnderAttack.wav", duration = 2.98 };
BGSoundAlerts_DefaultPackDurations[45] = { dir = x .. "Defeat1.wav", duration = 1.50 };
BGSoundAlerts_DefaultPackDurations[46] = { dir = x .. "Defeat3.wav", duration = 1.51 };
BGSoundAlerts_DefaultPackDurations[47] = { dir = x .. "DunBaldarNorthBunkerAssaulted.wav", duration = 3.41 };
BGSoundAlerts_DefaultPackDurations[48] = { dir = x .. "DunBaldarNorthBunkerDestroyed.wav", duration = 2.85 };
BGSoundAlerts_DefaultPackDurations[49] = { dir = x .. "DunBaldarNorthBunkerTaken.wav", duration = 3.62 };
BGSoundAlerts_DefaultPackDurations[50] = { dir = x .. "DunBaldarSouthBunkerAssaulted.wav", duration = 3.45 };
BGSoundAlerts_DefaultPackDurations[51] = { dir = x .. "DunBaldarSouthBunkerDestroyed.wav", duration = 3.31 };
BGSoundAlerts_DefaultPackDurations[52] = { dir = x .. "EastFrostwolfTowerAssaulted.wav", duration = 3.87 };
BGSoundAlerts_DefaultPackDurations[53] = { dir = x .. "EastFrostwolfTowerDestroyed.wav", duration = 3.41 };
BGSoundAlerts_DefaultPackDurations[54] = { dir = x .. "EastFrostwolfTowerTaken.wav", duration = 3.34 };
BGSoundAlerts_DefaultPackDurations[55] = { dir = x .. "HordeAirLaunching.wav", duration = 2.17 };
BGSoundAlerts_DefaultPackDurations[56] = { dir = x .. "HordeAssaultedBlacksmith.wav", duration = 2.41 };
BGSoundAlerts_DefaultPackDurations[57] = { dir = x .. "HordeAssaultedFarm.wav", duration = 2.10 };
BGSoundAlerts_DefaultPackDurations[58] = { dir = x .. "HordeAssaultedFrostwolfAidStation.wav", duration = 3.00 };
BGSoundAlerts_DefaultPackDurations[59] = { dir = x .. "HordeAssaultedFrostwolfGraveyard.wav", duration = 2.92 };
BGSoundAlerts_DefaultPackDurations[60] = { dir = x .. "HordeAssaultedGoldMine.wav", duration = 2.12 };
BGSoundAlerts_DefaultPackDurations[61] = { dir = x .. "HordeAssaultedIcebloodGraveyard.wav", duration = 2.89 };
BGSoundAlerts_DefaultPackDurations[62] = { dir = x .. "HordeAssaultedLumbermill.wav", duration = 2.13 };
BGSoundAlerts_DefaultPackDurations[63] = { dir = x .. "HordeAssaultedSnowfallGraveyard.wav", duration = 2.99 };
BGSoundAlerts_DefaultPackDurations[64] = { dir = x .. "HordeAssaultedStables.wav", duration = 2.08 };
BGSoundAlerts_DefaultPackDurations[65] = { dir = x .. "HordeAssaultedStonehearthGraveyard.wav", duration = 2.86 };
BGSoundAlerts_DefaultPackDurations[66] = { dir = x .. "HordeAssaultedStormpikeAidStation.wav", duration = 3.31 };
BGSoundAlerts_DefaultPackDurations[67] = { dir = x .. "HordeAssaultedStormpikeGraveyard.wav", duration = 3.10 };
BGSoundAlerts_DefaultPackDurations[68] = { dir = x .. "HordeFlagCaptured.wav", duration = 4.09 };
BGSoundAlerts_DefaultPackDurations[69] = { dir = x .. "HordeFlagReturned.wav", duration = 2.12 };
BGSoundAlerts_DefaultPackDurations[70] = { dir = x .. "HordeGeneralUnderAttack.wav", duration = 2.60, cooldown = 10 };
BGSoundAlerts_DefaultPackDurations[71] = { dir = x .. "HordeLaunchingFrostwolfRiders.wav", duration = 2.82 };
BGSoundAlerts_DefaultPackDurations[72] = { dir = x .. "HordeLaunchingUltimateUnit.wav", duration = 3.69 };
BGSoundAlerts_DefaultPackDurations[73] = { dir = x .. "HordeTakenBlacksmith.wav", duration = 2.39 };
BGSoundAlerts_DefaultPackDurations[74] = { dir = x .. "HordeTakenColdtoothMine.wav", duration = 2.55 };
BGSoundAlerts_DefaultPackDurations[75] = { dir = x .. "HordeTakenFarm.wav", duration = 1.78 };
BGSoundAlerts_DefaultPackDurations[76] = { dir = x .. "HordeTakenFrostwolfAidStation.wav", duration = 3.17 };
BGSoundAlerts_DefaultPackDurations[77] = { dir = x .. "HordeTakenFrostwolfGraveyard.wav", duration = 2.88 };
BGSoundAlerts_DefaultPackDurations[78] = { dir = x .. "HordeTakenGoldMine.wav", duration = 1.80 };
BGSoundAlerts_DefaultPackDurations[79] = { dir = x .. "HordeTakenIcebloodGraveyard.wav", duration = 2.71 };
BGSoundAlerts_DefaultPackDurations[80] = { dir = x .. "HordeTakenIrondeepMine.wav", duration = 2.72 };
BGSoundAlerts_DefaultPackDurations[81] = { dir = x .. "HordeTakenLumbermill.wav", duration = 1.90 };
BGSoundAlerts_DefaultPackDurations[82] = { dir = x .. "HordeTakenSnowfallGraveyard.wav", duration = 2.86 };
BGSoundAlerts_DefaultPackDurations[83] = { dir = x .. "HordeTakenStables.wav", duration = 1.62 };
BGSoundAlerts_DefaultPackDurations[84] = { dir = x .. "HordeTakenStonehearthGraveyard.wav", duration = 2.70 };
BGSoundAlerts_DefaultPackDurations[85] = { dir = x .. "HordeTakenStormpikeAidStation.wav", duration = 2.98 };
BGSoundAlerts_DefaultPackDurations[86] = { dir = x .. "HordeTakenStormpikeGraveyard.wav", duration = 2.89 };
BGSoundAlerts_DefaultPackDurations[87] = { dir = x .. "HordeTakenBlacksmith.wav", duration = 2.39 };
BGSoundAlerts_DefaultPackDurations[88] = { dir = x .. "HordeUpgradingUnits.wav", duration = 2.07 };
BGSoundAlerts_DefaultPackDurations[89] = { dir = x .. "IcebloodTowerAssaulted.wav", duration = 3.03 };
BGSoundAlerts_DefaultPackDurations[90] = { dir = x .. "IcebloodTowerDestroyed.wav", duration = 2.75 };
BGSoundAlerts_DefaultPackDurations[91] = { dir = x .. "IcebloodTowerTaken.wav", duration = 3.22 };
BGSoundAlerts_DefaultPackDurations[92] = { dir = x .. "IcewingBunkerAssaulted.wav", duration = 3.04 };
BGSoundAlerts_DefaultPackDurations[93] = { dir = x .. "IcewingBunkerDestroyed.wav", duration = 2.96 };
BGSoundAlerts_DefaultPackDurations[94] = { dir = x .. "IcewingBunkerTaken.wav", duration = 3.52 };
BGSoundAlerts_DefaultPackDurations[95] = { dir = x .. "Incoming.wav", duration = 1.26, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[96] = { dir = x .. "Incoming1.wav", duration = 1.21, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[97] = { dir = x .. "Incoming10.wav", duration = 1.39, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[98] = { dir = x .. "Incoming2.wav", duration = 1.24, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[99] = { dir = x .. "Incoming3.wav", duration = 1.26, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[100] = { dir = x .. "Incoming4.wav", duration = 1.17, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[101] = { dir = x .. "Incoming5.wav", duration = 1.27, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[102] = { dir = x .. "Incoming6.wav", duration = 1.33, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[103] = { dir = x .. "Incoming7.wav", duration = 1.24, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[104] = { dir = x .. "Incoming8.wav", duration = 1.21, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[105] = { dir = x .. "Incoming9.wav", duration = 1.24, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[106] = { dir = x .. "IncomingBase.wav", duration = 1.77, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[107] = { dir = x .. "IncomingBig.wav", duration = 2.31, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[108] = { dir = x .. "IncomingBlacksmith.wav", duration = 2.04, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[109] = { dir = x .. "IncomingCaptain.wav", duration = 0.00, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[110] = { dir = x .. "IncomingDrekThar.wav", duration = 1.80, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[111] = { dir = x .. "IncomingDunBaldarNorthBunker.wav", duration = 3.01, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[112] = { dir = x .. "IncomingDunBaldarSouthBunker.wav", duration = 2.88, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[113] = { dir = x .. "IncomingEastFrostwolfTower.wav", duration = 2.47, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[114] = { dir = x .. "IncomingFarm.wav", duration = 1.77, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[115] = { dir = x .. "IncomingFrostwolfGraveyard.wav", duration = 2.47, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[116] = { dir = x .. "IncomingFrostwolfReliefHut.wav", duration = 2.81, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[117] = { dir = x .. "IncomingGoldMine.wav", duration = 1.89, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[118] = { dir = x .. "IncomingIcebloodGraveyard.wav", duration = 2.31, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[119] = { dir = x .. "IncomingIcebloodTower.wav", duration = 2.19, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[120] = { dir = x .. "IncomingIcewingBunker.wav", duration = 2.01, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[121] = { dir = x .. "IncomingLumbermill.wav", duration = 1.74, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[122] = { dir = x .. "IncomingSnowfallGraveyard.wav", duration = 2.52, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[123] = { dir = x .. "IncomingStables.wav", duration = 1.80, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[124] = { dir = x .. "IncomingStonehearthBunker.wav", duration = 2.22, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[125] = { dir = x .. "IncomingStonehearthGraveyard.wav", duration = 2.40, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[126] = { dir = x .. "IncomingStormpikeAidStation.wav", duration = 2.48, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[127] = { dir = x .. "IncomingStormpikeGraveyard.wav", duration = 2.49, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[128] = { dir = x .. "IncomingTowerPoint.wav", duration = 1.99, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[129] = { dir = x .. "IncomingVanndarStormpike.wav", duration = 2.25, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[130] = { dir = x .. "IncomingWestFrostwolfTower.wav", duration = 2.69, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[131] = { dir = x .. "NeutralTakenColdtoothMine.wav", duration = 3.09 };
BGSoundAlerts_DefaultPackDurations[132] = { dir = x .. "NeutralTakenIrondeepMine.wav", duration = 3.31 };
BGSoundAlerts_DefaultPackDurations[133] = { dir = x .. "StonehearthBunkerAssaulted.wav", duration = 3.12 };
BGSoundAlerts_DefaultPackDurations[134] = { dir = x .. "StonehearthBunkerDestroyed.wav", duration = 2.87 };
BGSoundAlerts_DefaultPackDurations[135] = { dir = x .. "StonehearthBunkerTaken.wav", duration = 3.48 };
BGSoundAlerts_DefaultPackDurations[136] = { dir = x .. "TestSound.wav", duration = 1.61, cooldown = 10 };
BGSoundAlerts_DefaultPackDurations[137] = { dir = x .. "TowerPointAssaulted.wav", duration = 2.69 };
BGSoundAlerts_DefaultPackDurations[138] = { dir = x .. "TowerPointDestroyed.wav", duration = 2.19 };
BGSoundAlerts_DefaultPackDurations[139] = { dir = x .. "TowerPointTaken.wav", duration = 2.43 };
BGSoundAlerts_DefaultPackDurations[140] = { dir = x .. "Victory1.wav", duration = 1.50 };
BGSoundAlerts_DefaultPackDurations[141] = { dir = x .. "Victory3.wav", duration = 1.58 };
BGSoundAlerts_DefaultPackDurations[142] = { dir = x .. "WestFrostwolfTowerDestroyed.wav", duration = 3.33 };
BGSoundAlerts_DefaultPackDurations[143] = { dir = x .. "WestFrostwolfTowerAssaulted.wav", duration = 3.76 };
BGSoundAlerts_DefaultPackDurations[144] = { dir = x .. "WestFrostwolfTowerTaken.wav", duration = 3.90 };
BGSoundAlerts_DefaultPackDurations[145] = { dir = x .. "1.wav", duration = 0.57 };
BGSoundAlerts_DefaultPackDurations[146] = { dir = x .. "2.wav", duration = 0.45 };
BGSoundAlerts_DefaultPackDurations[147] = { dir = x .. "3.wav", duration = 0.44 };
BGSoundAlerts_DefaultPackDurations[148] = { dir = x .. "4.wav", duration = 0.60 };
BGSoundAlerts_DefaultPackDurations[149] = { dir = x .. "5.wav", duration = 0.66 };
BGSoundAlerts_DefaultPackDurations[150] = { dir = x .. "6.wav", duration = 0.81 };
BGSoundAlerts_DefaultPackDurations[151] = { dir = x .. "7.wav", duration = 0.62 };
BGSoundAlerts_DefaultPackDurations[152] = { dir = x .. "8.wav", duration = 0.50 };
BGSoundAlerts_DefaultPackDurations[153] = { dir = x .. "9.wav", duration = 0.57 };
BGSoundAlerts_DefaultPackDurations[154] = { dir = x .. "10.wav", duration = 0.40 };
BGSoundAlerts_DefaultPackDurations[155] = { dir = x .. "20.wav", duration = 0.50 };
BGSoundAlerts_DefaultPackDurations[156] = { dir = x .. "30.wav", duration = 0.46 };
BGSoundAlerts_DefaultPackDurations[157] = { dir = x .. "40.wav", duration = 0.48 };
BGSoundAlerts_DefaultPackDurations[158] = { dir = x .. "50.wav", duration = 0.60 };
BGSoundAlerts_DefaultPackDurations[159] = { dir = x .. "60.wav", duration = 0.70 };
BGSoundAlerts_DefaultPackDurations[160] = { dir = x .. "70.wav", duration = 0.60 };
BGSoundAlerts_DefaultPackDurations[161] = { dir = x .. "80.wav", duration = 0.46 };
BGSoundAlerts_DefaultPackDurations[162] = { dir = x .. "90.wav", duration = 0.48 };
BGSoundAlerts_DefaultPackDurations[163] = { dir = x .. "100.wav", duration = 0.80 };
BGSoundAlerts_DefaultPackDurations[164] = { dir = x .. "200.wav", duration = 0.87 };
BGSoundAlerts_DefaultPackDurations[165] = { dir = x .. "300.wav", duration = 0.93 };
BGSoundAlerts_DefaultPackDurations[166] = { dir = x .. "400.wav", duration = 1.06 };
BGSoundAlerts_DefaultPackDurations[167] = { dir = x .. "500.wav", duration = 1.05 };
BGSoundAlerts_DefaultPackDurations[168] = { dir = x .. "600.wav", duration = 1.06 };
BGSoundAlerts_DefaultPackDurations[169] = { dir = x .. "700.wav", duration = 1.13 };
BGSoundAlerts_DefaultPackDurations[170] = { dir = x .. "800.wav", duration = 0.83 };
BGSoundAlerts_DefaultPackDurations[171] = { dir = x .. "900.wav", duration = 1.03 };
BGSoundAlerts_DefaultPackDurations[172] = { dir = x .. "1000.wav", duration = 1.02 };
BGSoundAlerts_DefaultPackDurations[173] = { dir = x .. "And.wav", duration = 0.47 };
BGSoundAlerts_DefaultPackDurations[174] = { dir = x .. "After.wav", duration = 0.50 };
BGSoundAlerts_DefaultPackDurations[175] = { dir = x .. "Base.wav", duration = 0.58 };
BGSoundAlerts_DefaultPackDurations[176] = { dir = x .. "Bases.wav", duration = 0.77 };
BGSoundAlerts_DefaultPackDurations[177] = { dir = x .. "Resources.wav", duration = 0.98 };
BGSoundAlerts_DefaultPackDurations[178] = { dir = x .. "Horde.wav", duration = 0.80 };
BGSoundAlerts_DefaultPackDurations[179] = { dir = x .. "Alliance.wav", duration = 0.95 };
BGSoundAlerts_DefaultPackDurations[180] = { dir = x .. "InTheLead.wav", duration = 1.291 };
BGSoundAlerts_DefaultPackDurations[181] = { dir = x .. "InTheLeadWith.wav", duration = 1.291 };
BGSoundAlerts_DefaultPackDurations[182] = { dir = x .. "MinutesArathiBasin.wav", duration = 1.51 };
BGSoundAlerts_DefaultPackDurations[183] = { dir = x .. "MinutesWarsongGulch.wav", duration = 1.60 };
BGSoundAlerts_DefaultPackDurations[184] = { dir = x .. "11.wav", duration = 0.70 };
BGSoundAlerts_DefaultPackDurations[185] = { dir = x .. "12.wav", duration = 0.66 };
BGSoundAlerts_DefaultPackDurations[186] = { dir = x .. "13.wav", duration = 0.79 };
BGSoundAlerts_DefaultPackDurations[187] = { dir = x .. "14.wav", duration = 0.77 };
BGSoundAlerts_DefaultPackDurations[188] = { dir = x .. "15.wav", duration = 0.74 };
BGSoundAlerts_DefaultPackDurations[189] = { dir = x .. "16.wav", duration = 0.90 };
BGSoundAlerts_DefaultPackDurations[190] = { dir = x .. "17.wav", duration = 0.90 };
BGSoundAlerts_DefaultPackDurations[191] = { dir = x .. "18.wav", duration = 0.70 };
BGSoundAlerts_DefaultPackDurations[192] = { dir = x .. "19.wav", duration = 0.74 };
BGSoundAlerts_DefaultPackDurations[193] = { dir = x .. "DunBaldarSouthBunkerTaken.wav", duration = 3.96 };
BGSoundAlerts_DefaultPackDurations[194] = { dir = x .. "By.wav", duration = 0.45 };
BGSoundAlerts_DefaultPackDurations[195] = { dir = x .. "2Kill.wav", duration = 1.20 };
BGSoundAlerts_DefaultPackDurations[196] = { dir = x .. "3Kill.wav", duration = 1.61 };
BGSoundAlerts_DefaultPackDurations[197] = { dir = x .. "4Kill.wav", duration = 1.31 };
BGSoundAlerts_DefaultPackDurations[198] = { dir = x .. "5Kill.wav", duration = 1.25 };
BGSoundAlerts_DefaultPackDurations[199] = { dir = x .. "6Kill.wav", duration = 1.14 };
BGSoundAlerts_DefaultPackDurations[200] = { dir = x .. "7Kill.wav", duration = 1.08 };
BGSoundAlerts_DefaultPackDurations[201] = { dir = x .. "HordeTakenWestBeacon.wav", duration = 1.96 };
BGSoundAlerts_DefaultPackDurations[202] = { dir = x .. "AllianceTakenWestBeacon.wav", duration = 2.49 };
BGSoundAlerts_DefaultPackDurations[203] = { dir = x .. "HordeTakenEastBeacon.wav", duration = 1.90 };
BGSoundAlerts_DefaultPackDurations[204] = { dir = x .. "AllianceTakenEastBeacon.wav", duration = 2.39 };
BGSoundAlerts_DefaultPackDurations[205] = { dir = x .. "HordeTakenHalaa.wav", duration = 2.60 };
BGSoundAlerts_DefaultPackDurations[206] = { dir = x .. "AllianceTakenHalaa.wav", duration = 2.70 };
BGSoundAlerts_DefaultPackDurations[207] = { dir = x .. "HordeAreTakingHalaa.wav", duration = 2.51 };
BGSoundAlerts_DefaultPackDurations[208] = { dir = x .. "AllianceAreTakingHalaa.wav", duration = 2.81 };
BGSoundAlerts_DefaultPackDurations[209] = { dir = x .. "HalaaUnderAttack.wav", duration = 1.51 };
BGSoundAlerts_DefaultPackDurations[210] = { dir = x .. "HordeTakenSpiritTower.wav", duration = 2.80 };
BGSoundAlerts_DefaultPackDurations[211] = { dir = x .. "AllianceTakenSpiritTower.wav", duration = 2.93 };
BGSoundAlerts_DefaultPackDurations[212] = { dir = x .. "HordeTakenBoneWastes.wav", duration = 2.88 };
BGSoundAlerts_DefaultPackDurations[213] = { dir = x .. "AllianceTakenBoneWastes.wav", duration = 2.94 };
BGSoundAlerts_DefaultPackDurations[214] = { dir = x .. "SpiritTowersCapturable.wav", duration = 2.20 };
BGSoundAlerts_DefaultPackDurations[215] = { dir = x .. "IsAt.wav", duration = 0.6 };
BGSoundAlerts_DefaultPackDurations[216] = { dir = x .. "IsCriticallyInjured.wav", duration = 1.6 };
BGSoundAlerts_DefaultPackDurations[217] = { dir = x .. "IsSafe.wav", duration = 1.09 };
BGSoundAlerts_DefaultPackDurations[218] = { dir = x .. "PerCent.wav", duration = 0.68 };
BGSoundAlerts_DefaultPackDurations[219] = { dir = x .. "Vanndar.wav", duration = 1.65 };
BGSoundAlerts_DefaultPackDurations[220] = { dir = x .. "DrekThar.wav", duration = 1.21 };
BGSoundAlerts_DefaultPackDurations[221] = { dir = x .. "AllianceLostBloodElfTower.wav", duration = 3.00 };
BGSoundAlerts_DefaultPackDurations[222] = { dir = x .. "AllianceLostDraeneiRuins.wav", duration = 2.18 };
BGSoundAlerts_DefaultPackDurations[223] = { dir = x .. "AllianceLostFelReaverRuins.wav", duration = 1.98 };
BGSoundAlerts_DefaultPackDurations[224] = { dir = x .. "AllianceLostMageTower.wav", duration = 2.00 };
BGSoundAlerts_DefaultPackDurations[225] = { dir = x .. "AllianceTakenBloodElfTower.wav", duration = 2.12 };
BGSoundAlerts_DefaultPackDurations[226] = { dir = x .. "AllianceTakenDraeneiRuins.wav", duration = 1.95 };
BGSoundAlerts_DefaultPackDurations[227] = { dir = x .. "AllianceTakenFelReaverRuins.wav", duration = 2.22 };
BGSoundAlerts_DefaultPackDurations[228] = { dir = x .. "AllianceTakenMageTower.wav", duration = 1.71 };
BGSoundAlerts_DefaultPackDurations[229] = { dir = x .. "HordeLostBloodElfTower.wav", duration = 1.84 };
BGSoundAlerts_DefaultPackDurations[230] = { dir = x .. "HordeLostDraeneiRuins.wav", duration = 2.04 };
BGSoundAlerts_DefaultPackDurations[231] = { dir = x .. "HordeLostFelReaverRuins.wav", duration = 2.12 };
BGSoundAlerts_DefaultPackDurations[232] = { dir = x .. "HordeLostMageTower.wav", duration = 1.53 };
BGSoundAlerts_DefaultPackDurations[233] = { dir = x .. "HordeTakenBloodElfTower.wav", duration = 1.99 };
BGSoundAlerts_DefaultPackDurations[234] = { dir = x .. "HordeTakenDraeneiRuins.wav", duration = 2.05 };
BGSoundAlerts_DefaultPackDurations[235] = { dir = x .. "HordeTakenFelReaverRuins.wav", duration = 2.31 };
BGSoundAlerts_DefaultPackDurations[236] = { dir = x .. "HordeTakenMageTower.wav", duration = 2.08 };
BGSoundAlerts_DefaultPackDurations[237] = { dir = x .. "AllianceTakenEOTSFlag.wav", duration = 1.52 };
BGSoundAlerts_DefaultPackDurations[238] = { dir = x .. "HordeTakenEOTSFlag.wav", duration = 1.27 };
BGSoundAlerts_DefaultPackDurations[239] = { dir = x .. "FlagDropped.wav", duration = 1.01 };
BGSoundAlerts_DefaultPackDurations[240] = { dir = x .. "FlagReset.wav", duration = 1.61 };
BGSoundAlerts_DefaultPackDurations[241] = { dir = x .. "IncomingBloodElfTower.wav", duration = 1.55, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[242] = { dir = x .. "IncomingDraeneiRuins.wav", duration = 1.53, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[243] = { dir = x .. "IncomingFelReaverRuins.wav", duration = 1.78, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[244] = { dir = x .. "IncomingMageTower.wav", duration = 1.38, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[245] = { dir = x .. "MinutesEyeOfTheStorm.wav", duration = 1.29 };
BGSoundAlerts_DefaultPackDurations[246] = { dir = x .. "Points.wav", duration = 0.52 };
BGSoundAlerts_DefaultPackDurations[247] = { dir = x .. "IncomingTunnel.wav", duration = 1.30, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[248] = { dir = x .. "Restoration.wav", duration = 1.01 };
BGSoundAlerts_DefaultPackDurations[249] = { dir = x .. "Speed.wav", duration = 4.89 };
BGSoundAlerts_DefaultPackDurations[250] = { dir = x .. "Berserking.wav", duration = 4.73 };
BGSoundAlerts_DefaultPackDurations[251] = { dir = x .. "FlagCriticallyInjured.wav", duration = 2.23 };
BGSoundAlerts_DefaultPackDurations[252] = { dir = x .. "IncomingBalcony.wav", duration = 1.53, cooldown = 6 };
BGSoundAlerts_DefaultPackDurations[253] = { dir = x .. "HordeCapturedEOTSFlag.wav", duration = 1.99 };
BGSoundAlerts_DefaultPackDurations[254] = { dir = x .. "AllianceCapturedEOTSFlag.wav", duration = 1.99 };
BGSoundAlerts_DefaultPackDurations[255] = { dir = x .. "FirstBlood.wav", duration = 2.13 };