--$Id: deDE.lua 12749 2006-10-03 02:19:17Z kergoth $-- 
-- deDE localization by Gamefaq
AceLibrary("AceLocale-2.1"):RegisterTranslation("OneBag", "deDE", function()
   return {
      ["Frame"]	= "Fenster",
      ["Frame Options"]	= "Fenster Optionen.",
      ["Columns"]	= "Spalten",
      ["Sets the number of columns to use"]	= "Stellt die Menge der Spalten ein.",
      ["Scale"]	= "Skalierung",
      ["Sets the scale of the frame"]	= "Stellt die Gr\195\182\195\159e des Fensters ein.",
      ["Strata"]	= "Schichten",
      ["Sets the strata of the frame"]	= "Stellt die Schichth\195\182he des Fensters ein was ein \195\188berblenden von diesem Fenster mit einem anderen verhindert.",
      ["Alpha"]	= "Transparenz",
      ["Sets the alpha of the frame"]	= "Stellt die Transparenz des Fensters ein.",
      ["Locked"]	= "Fixieren",
      ["Toggles the ability to move the frame"]	= "Bestimmt ob das Fenster verschoben werden kann.",
      ["Clamped"]	= "Sichtbereich",
      ["Toggles the ability to drag the frame off screen."]	= "Bestimmt ob das Fenster au\195\159erhalb des sichtbaren Bereichs geschoben werden kann.",
      ["Bag Break"] = "Taschen Zeilenumbruch",
      ["Sets wether to start a new row at the beginning of a bag."] = "Stellt ein eine neue Zeile zu benutzen beim Anzeigen einer neuen Tasche.",
      ["Vertical Alignment"] = "Vertikale Ausrichtung",
      ["Sets wether to have the extra spaces on the top or bottom."] = "Stellt ein ob die Taschen mit freien fensterplatz oben oder unten ausgerichtet werden.",
      ["Top"] = "Oben",
      ["Bottom"] = "Unten",

      ["Show"]	= "Zeige",
      ["Various Display Options"]	= "Verschiedene Anzeige Optionen.",
      ["Counts"]	= "Anzahl",
      ["Toggles showing the counts for special bags."]	= "Bestimmt ob die Anzahl besonderer Taschen angezeigt wird.",
      ["Direction"]	= "Richtung",
      ["Forward"]	= "Vorw\195\164rts",
      ["Toggles direction the bags are shown"]	= "Bestimmt die Richtung in der die Taschen angezeigt werden.",
      ["|cffff0000Reverse|r"]	= "|cffff0000R\195\188ckw\195\164rts|r",
      ["|cff00ff00Forward|r"]	= "|cffff0000Vorw\195\164rts|r",
      ["Ammo Bag"]	= "Munitionstasche",
      ["Turns display of ammo bags on and off."]	= "Schaltet die Munitionstasche an und aus.",
      ["Soul Bag"]	= "Seelentasche",
      ["Turns display of soul bags on and off."]	= "Schaltet die Seelentasche an und aus.",
      ["Profession Bag"]	= "Beruf Taschen",
      ["Turns display of profession bags on and off."]	= "Schaltet die Berufe Taschen an und aus.",
      ["Backpack"] = "Rucksack",
      ["Turns display of your backpack on and off."] = "Schaltet den Rucksack an und aus.",
      ["First Bag"] = "Erste Tasche",
      ["Turns display of your first bag on and off."] = "Schaltet das Anzeigen der ersten Tasche an und aus.",
      ["Second Bag"] = "Zweite Tasche",
      ["Turns display of your second bag on and off."] = "Schaltet das Anzeigen der zweiten Tasche an und aus.",
      ["Third Bag"] = "Dritte Tasche",
      ["Turns display of your third bag on and off."] = "Schaltet das Anzeigen der dritten Tasche an und aus.",
      ["Fourth Bag"] = "Vierte Tasche",
      ["Turns display of your fourth bag on and off."] = "Schaltet das Anzeigen der vierte Tasche an und aus.",
      ["'s Bags"] = "'s Taschen",		

      ["Colors"]	= "Farben",
      ["Different color code settings."]	= "Verschiedene Farbschema Einstellungen.",
      ["Mouseover Color"]	= "Mause\195\188ber Farbe",
      ["Changes the highlight color for when you mouseover a bag slot."]	= "Ver\195\164ndert die Hervorhebungsfarbe wenn du mit dem MAuscurser \195\188ber einen Bankplatz gehst.",
      ["Ammo Bag Color"]	= "Munitionstaschen Farbe",
      ["Changes the highlight color for Ammo Bags."]	= "Ver\195\164ndert die Hervorhebungsfarbe f\195\188r Munitionstaschen.",
      ["Soul Bag Color"]	= "Seelentaschen Farbe",
      ["Changes the highlight color for Soul Bags."]	= "Ver\195\164ndert die Hervorhebungsfarbe f\195\188r Seelentaschen.",
      ["Profession Bag Color"]	= "Berufe Taschen Farbe",
      ["Changes the highlight color for Profession Bags."]	= "Ver\195\164ndert die Hervorhebungsfarbe f\195\188r Berufe Taschen.",
      ["Background Color"]	= "Hintergrundfarbe",
      ["Changes the background color for the frame."]	= "Ver\195\164ndert die Hintergrundfarbe des Fensters.",
      ["Highlight Glow"]	= "Hervorhebungsleuchten",
      ["Turns hightlight glow on and off."]	= "Schaltet das Hervorhebebungsleuchten an und aus.",
      ["Rarity Coloring"]	= "Selteneheits Einf\195\164rbung",
      ["Turns rarity coloring on and off."]	= "Schaltet die Seltenheitseinf\195\164rbung von Items an und aus.",

      ["Reset"]	= "Zur\195\188ckstellen",
      ["Reset the different colors."]	= "Stellt die Einstellungen der Farben wieder zurr\195\188ck.",
      ["Mouseover Color"]	= "Maus\195\188ber Farbe",
      ["Returns your mouseover color to the default."]	= "Setzt deine Maus\195\188ber Farbe wieder auf die Grundeinstellung.",
      ["Ammo Slot Color"]	= "Munitionstaschen Farbe",
      ["Returns your ammo slot color to the default."]	= "Setzt deine Munitionstaschen Farbe wieder auf die Grundeinstellung.",
      ["Soul Slot Color"]	= "Seelenpl\195\164tze Farben",
      ["Returns your soul slot color to the default."]	= "Setzt deine Seelenpl\195\164tze Farbe wieder auf die Grundeinstellung.",
      ["Profession Slot Color"]	= "Berufe Pl\195\164tze Farben",
      ["Returns your profession slot color to the default."]	= "Setzt deine Berufepl\195\164tze Farbe wieder auf die Grundeinstellung.",
      ["Background"]	= "Hintergrund",
      ["Returns your frame background to the default."]	= "Setzt die Hintergrundfarbe wieder auf die Grundeinstellung zurr\195\188ck.",
      ["Plow!"]	= "Plow!",
      ["Organizes your bags."]	= "Sortiert deine Taschen.",
      ["- Note: This option only appears if you have MrPlow installed"]	= "- Hinweis: Diese Option erscheint nur wenn du das Addon MrPlow installiert hast.",

      ["%s ran in %s"]	= "%s lief in %s",
      ["Checking if bag %s is open"]	= "Pr\195\188fe ob Tasche %s ge\195\182ffnet ist.",
      ["Opening bag %s"]	= "\195\182ffne Tasche %s",
      ["Closing bag %s"]	= "Schliesse Tasche %s",

      ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "Normal benutzt: %s, Seele benutzt: %s, Berufe benutzt: %s, Munition benutzt %s, Munition quantit\195\164t %s.",
      ["%s/%s Slots"]	= "%s/%s Pl\195\164tze",
      ["%s/%s Ammo"]	= "%s/%s Munition",
      ["%s/%s Soul Shards"]	= "%s/%s Seelensplitter",
      ["%s/%s Profession Slots"]	= "%s/%s Berufe Pl\195\164tze",
      
      ["Menu"] = "Menü" 
   }
end)