--$Id: enUS.lua 12749 2006-10-03 02:19:17Z kergoth $-- 
 AceLibrary("AceLocale-2.1"):RegisterTranslation("OneBag", "enUS", function()
   return {
      ["Frame"]	= true,
      ["Frame Options"]	= true,
      ["Columns"]	= true,
      ["Sets the number of columns to use"]	= true,
      ["Scale"]	= true,
      ["Sets the scale of the frame"]	= true,
      ["Strata"]	= true,
      ["Sets the strata of the frame"]	= true,
      ["Alpha"]	= true,
      ["Sets the alpha of the frame"]	= true,
      ["Locked"]	= true,
      ["Toggles the ability to move the frame"]	= true,
      ["Clamped"]	= true,
      ["Toggles the ability to drag the frame off screen."]	= true,
      ["Bag Break"] = true,
      ["Sets wether to start a new row at the beginning of a bag."] = true,
      ["Vertical Alignment"] = true,
      ["Sets wether to have the extra spaces on the top or bottom."] = true,
      ["Top"] = true,
      ["Bottom"] = true,

      ["Show"]	= true,
      ["Various Display Options"]	= true,
      ["Counts"]	= true,
      ["Toggles showing the counts for special bags."]	= true,
      ["Direction"]	= true,
      ["Forward"]	= true,
      ["Toggles direction the bags are shown"]	= true,
      ["|cffff0000Reverse|r"]	= true,
      ["|cff00ff00Forward|r"]	= true,
      ["Ammo Bag"]	= true,
      ["Turns display of ammo bags on and off."]	= true,
      ["Soul Bag"]	= true,
      ["Turns display of soul bags on and off."]	= true,
      ["Profession Bag"]	= true,
      ["Turns display of profession bags on and off."]	= true,
      ["Backpack"] = true,
      ["Turns display of your backpack on and off."] = true,
      ["First Bag"] = true,
      ["Turns display of your first bag on and off."] = true,
      ["Second Bag"] = true,
      ["Turns display of your second bag on and off."] = true,
      ["Third Bag"] = true,
      ["Turns display of your third bag on and off."] = true,
      ["Fourth Bag"] = true,
      ["Turns display of your fourth bag on and off."] = true,
      ["'s Bags"] = true,		

      ["Colors"]	= true,
      ["Different color code settings."]	= true,
      ["Mouseover Color"]	= true,
      ["Changes the highlight color for when you mouseover a bag slot."]	= true,
      ["Ammo Bag Color"]	= true,
      ["Changes the highlight color for Ammo Bags."]	= true,
      ["Soul Bag Color"]	= true,
      ["Changes the highlight color for Soul Bags."]	= true,
      ["Profession Bag Color"]	= true,
      ["Changes the highlight color for Profession Bags."]	= true,
      ["Background Color"]	= true,
      ["Changes the background color for the frame."]	= true,
      ["Highlight Glow"]	= true,
      ["Turns hightlight glow on and off."]	= true,
      ["Rarity Coloring"]	= true,
      ["Turns rarity coloring on and off."]	= true,

      ["Reset"]	= true,
      ["Reset the different colors."]	= true,
      ["Mouseover Color"]	= true,
      ["Returns your mouseover color to the default."]	= true,
      ["Ammo Slot Color"]	= true,
      ["Returns your ammo slot color to the default."]	= true,
      ["Soul Slot Color"]	= true,
      ["Returns your soul slot color to the default."]	= true,
      ["Profession Slot Color"]	= true,
      ["Returns your profession slot color to the default."]	= true,
      ["Background"]	= true,
      ["Returns your frame background to the default."]	= true,
      ["Plow!"]	= true,
      ["Organizes your bags."]	= true,
      ["- Note: This option only appears if you have MrPlow installed"]	= true,

      ["Pick Locale"] = true, 
      ["Sets the locale to use.  Will not take effect until you reload your UI."] = true,

      ["%s ran in %s"]	= true,
      ["Checking if bag %s is open"]	= true,
      ["Opening bag %s"]	= true,
      ["Closing bag %s"]	= true,

      ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= true,
      ["%s/%s Slots"]	= true,
      ["%s/%s Ammo"]	= true,
      ["%s/%s Soul Shards"]	= true,
      ["%s/%s Profession Slots"]	= true,
      
      ["Menu"] = true 
   }
end)