--$Id: frFR.lua 12749 2006-10-03 02:19:17Z kergoth $-- 
  AceLibrary("AceLocale-2.1"):RegisterTranslation("OneBag", "frFR", function()
  return {
     ["Frame"] = "Fen\195\170tre",
     ["Frame Options"] = "Options de la fen\195\170tre pricipale",
     ["Columns"]       = "Colonnes",
     ["Sets the number of columns to use"]     = "Pour choisir le nombre de colonnes \195\160 utiliser",
     ["Scale"] = "Echelle",
     ["Sets the scale of the frame"]   = "Modifie la taille",
--     ["Strata"]        = true,
     ["Sets the strata of the frame"]  = "Avancer/reculer",
--     ["Alpha"] = true,
     ["Sets the alpha of the frame"]   = "Modifie la transparence",
     ["Locked"]        = "V\195\169rouiller",
     ["Toggles the ability to move the frame"] = "V\195\169rouiller/D\195\169v\195\169rouiller",
     ["Clamped"]       = "Clamp",
     ["Toggles the ability to drag the frame off screen."]     = "Permet de garder la fen\195\170tre \195\160 l'\195\169cran",
--     ["Bag Break"] = true,
     ["Sets wether to start a new row at the beginning of a bag."] = "Permet de commencer un sac sur une nouvelle ligne",
     ["Vertical Alignment"] = "Alignement",
     ["Sets wether to have the extra spaces on the top or bottom."] = "Permet d'afficher les cases vides en haut ou en bas",
     ["Top"] = "Haut",
     ["Bottom"] = "Bas",

     ["Show"]  = "Affichage",
     ["Various Display Options"]       = "Options d'affichage",
     ["Counts"]        = "Compteur",
     ["Toggles showing the counts for special bags."]  = "Active le compteur pour les sacs sp\195\169ciaux",
--     ["Direction"]     = true,
     ["Forward"]       = "Ordre",
     ["Toggles direction the bags are shown"]  = "Changer l'ordre dans lequel les sacs sont affich\195\169s",
--     ["|cffff0000Reverse|r"]   = true,
--     ["|cff00ff00Forward|r"]   = true,
     ["Ammo Bag"]      = "Sacs de munitions",
--     ["Turns display of ammo bags on and off."]        = true,
     ["Soul Bag"]      = "Sacs d'\195\162me",
--     ["Turns display of soul bags on and off."]        = true,
     ["Profession Bag"]        = "Sacs de profession",
--     ["Turns display of profession bags on and off."]  = true,
     ["Backpack"] = "Sac \195\160 dos",
--     ["Turns display of your backpack on and off."] = true,
     ["First Bag"] = "Sac 1",
--     ["Turns display of your first bag on and off."] = true,
     ["Second Bag"] = "Sac 2",
--     ["Turns display of your second bag on and off."] = true,
     ["Third Bag"] = "Sac 3",
--     ["Turns display of your third bag on and off."] = true,
     ["Fourth Bag"] = "Sac 4",
--     ["Turns display of your fourth bag on and off."] = true,
     ["'s Bags"] = " : Inventaire",

     ["Colors"]        = "Couleurs",
     ["Different color code settings."]        = "Pour modifier les codes couleur",
--     ["Mouseover Color"]       = true,
--     ["Changes the highlight color for when you mouseover a bag slot."]        = true,
     ["Ammo Bag Color"]        = "Sac de munitions",
     ["Changes the highlight color for Ammo Bags."]    = "Change la couleur du cadre",
     ["Soul Bag Color"]        = "Sac d'\195\162me",
     ["Changes the highlight color for Soul Bags."]    = "Change la couleur du cadre",
     ["Profession Bag Color"]  = "sac de profession",
     ["Changes the highlight color for Profession Bags."]      = "Change la couleur du cadre",
     ["Background Color"]      = "Arri\195\168re plan",
     ["Changes the background color for the frame."]   = "Change la couleur de fond de OneBag",
     ["Highlight Glow"]        = "Effet lumineux",
     ["Turns hightlight glow on and off."]     = "Active l'effet lumineux des cadres",
     ["Rarity Coloring"]       = "Raret\195\169",
     ["Turns rarity coloring on and off."]     = "Cadre coloré selon la raret\195\169",

--[[     ["Reset"] = true,
     ["Reset the different colors."]   = true,
     ["Mouseover Color"]       = true,
     ["Returns your mouseover color to the default."]  = true,
     ["Ammo Slot Color"]       = true,
     ["Returns your ammo slot color to the default."]  = true,
     ["Soul Slot Color"]       = true,
     ["Returns your soul slot color to the default."]  = true,
     ["Profession Slot Color"] = true,
     ["Returns your profession slot color to the default."]    = true,
     ["Background"]    = true,
     ["Returns your frame background to the default."] = true,
     ["Plow!"] = true,]]
     ["Organizes your bags."]  = "R\195\169organise vos sacs",
     ["- Note: This option only appears if you have MrPlow installed"] = "note: cette option ne fonctionnera que si vous avez MrPlow d'install\195\169",

     ["Pick Locale"] = "Choisir une langue",
     ["Sets the locale to use.  Will not take effect until you reload your UI."] = "Vous permet de s\195\169lectionner la langue a utiliser pour la traduction. Ne sera pris en compte qu'apres un rechargement de l'interface.",
--     ["None"] = "Aucune (prend celle du jeu)",

--     ["%s ran in %s"]  = true,
--     ["Checking if bag %s is open"]    = true,
--     ["Opening bag %s"]        = true,
--     ["Closing bag %s"]        = true,

--     ["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]        = true,
     ["%s/%s Slots"]   = "%s/%s places",
     ["%s/%s Ammo"]    = "%s/%s munitions",
     ["%s/%s Soul Shards"]     = "%s/%s fragments",
     ["%s/%s Profession Slots"]        = "%s/%s de profession",
  }
end)