--$Id: koKR.lua 12749 2006-10-03 02:19:17Z kergoth $
-- koKR localization by Next96
AceLibrary("AceLocale-2.1"):RegisterTranslation("OneBag", "koKR", function()
    return {
		["Frame"]	= "프레임",
		["Frame Options"]	= "프레임 설정",
		["Columns"]	= "칸",
		["Sets the number of columns to use"]	= "한 줄에 몇 개의 칸을 사용할지 변경",
		["Scale"]	= "크기",
		["Sets the scale of the frame"]	= "프레임의 크기를 변경",
		["Strata"]	= "프레임레벨",
		["Sets the strata of the frame"]	= "프레임의 높이를 변경",
		["Alpha"]	= "투명도",
		["Sets the alpha of the frame"]	= "프레임의 투명도를 변경",
		["Locked"]	= "고정",
		["Toggles the ability to move the frame"]	= "프레임이 이동 가능한지를 설정",
		["Clamped"]	= "외곽고정",
		["Toggles the ability to drag the frame off screen."]	= "프레임이 화면 바깥으로 이동가능한지 설정",
	        ["Bag Break"] = "가방 구분",
	        ["Sets wether to start a new row at the beginning of a bag."] = "가방을 구분하기 위한 표시를 사용할지 설정",
	        ["Vertical Alignment"] = "공간 정렬",
	        ["Sets wether to have the extra spaces on the top or bottom."] = "가방 공간을 위에서부터 정렬할 것인지 설정",
	        ["Top"] = "위로",
	        ["Bottom"] = "아래로",

		["Show"]	= "보기",
		["Various Display Options"]	= "보기 설정",
		["Counts"]	= "수량표시",
		["Toggles showing the counts for special bags."]	= "특수 가방의 아이템수량 표시를 설정",
		["Direction"]	= "방향",
		["Forward"]	= "가방순서",
		["Toggles direction the bags are shown"]	= "가방을 소지품부터 표시할 것인지 설정",
		["|cffff0000Reverse|r"]	= "|cffff0000거꾸로|r",
		["|cff00ff00Forward|r"]	= "|cff00ff00앞으로|r",
		["Ammo Bag"]	= "화살통",
		["Turns display of ammo bags on and off."]	= "화살통을 열거나 닫습니다.",
		["Soul Bag"]	= "영혼의 가방",
		["Turns display of soul bags on and off."]	= "영혼의 가방을 열거나 닫습니다.",
		["Profession Bag"]	= "전문기술 가방",
		["Turns display of profession bags on and off."]	= "전문기술 가방을 열거나 닫습니다.",
		["Backpack"] = "소지품",
		["Turns display of your backpack on and off."] = "소지품을 열거나 닫습니다.",
		["First Bag"] = "첫번째 가방",
		["Turns display of your first bag on and off."] = "첫번째 가방을 열거나 닫습니다.",
		["Second Bag"] = "두번째 가방",
		["Turns display of your second bag on and off."] = "두번째 가방을 열거나 닫습니다.",
		["Third Bag"] = "세번째 가방",
		["Turns display of your third bag on and off."] = "세번째 가방을 열거나 닫습니다.",
		["Fourth Bag"] = "네번째 가방",
		["Turns display of your fourth bag on and off."] = "네번째 가방을 열거나 닫습니다.",
		["'s Bags"] = "의 가방",		
		
		["Colors"]	= "색상",
		["Different color code settings."]	= "가방의 색상 설정",
		["Mouseover Color"]	= "마우스 색상",
		["Changes the highlight color for when you mouseover a bag slot."]	= "마우스를 드래그했을 때 선택된 가방의 색상",
		["Ammo Bag Color"]	= "화살통 색상",
		["Changes the highlight color for Ammo Bags."]	= "화살통 및 탄환주머니의 색상",
		["Soul Bag Color"]	= "영혼의 가방 색상",
		["Changes the highlight color for Soul Bags."]	= "영혼의 가방의 색상",
		["Profession Bag Color"]	= "전문기술 가방 색상",
		["Changes the highlight color for Profession Bags."]	= "전문기술 가방의 색상",
		["Background Color"]	= "배경 색상",
		["Changes the background color for the frame."]	= "가방의 배경의 색상",
		["Highlight Glow"]	= "강조 표시",
		["Turns hightlight glow on and off."]	= "아이템을 강조 표시를 설정",
		["Rarity Coloring"]	= "등급 표시",
		["Turns rarity coloring on and off."]	= "아이템의 등급 표시를 설정",
		
		["Reset"]	= "초기화",
		["Reset the different colors."]	= "모든 가방의 색상 초기화",
		["Mouseover Color"]	= "마우스 색상",
		["Returns your mouseover color to the default."]	= "마우스로 드래그했을 때의 색상을 초기화",
		["Ammo Slot Color"]	= "화살통 색상",
		["Returns your ammo slot color to the default."]	= "화살통의 색상을 초기화",
		["Soul Slot Color"]	= "영혼의 가방 색상",
		["Returns your soul slot color to the default."]	= "영혼의 가방 색상을 초기화",
		["Profession Slot Color"]	= "전문기술 가방 색상",
		["Returns your profession slot color to the default."]	= "전문기술 가방의 색상을 초기화",
		["Background"]	= "개병",
		["Returns your frame background to the default."]	= "가방의 배경 색상을 초기화",
		["Plow!"]	= "MrPlow 사용",
		["Organizes your bags."]	= "가방을 정렬합니다,",
		["- Note: This option only appears if you have MrPlow installed"]	= "이것은 MrPlow 애드온이 설치되어야 사용이 가능합니다.",
		
		["%s ran in %s"]	= "%s가 %s에 있습니다.",
		["Checking if bag %s is open"]	= "%s 가방을 선택하면 가방이 열립니다.",
		["Opening bag %s"]	= "%s 가방을 엽니다.",
		["Closing bag %s"]	= "%s 가방을 닫습니다.",
		
		["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "현재 사용 공간: %s, 조각 사용 공간: %s, 전문기술 사용 공간: %s, 화살(탄환) 사용 공간: %s, 화살(탄환) 수량 %s.",
		["%s/%s Slots"]	= "%s/%s 공간",
		["%s/%s Ammo"]	= "%s/%s 화살(탄환)",
		["%s/%s Soul Shards"]	= "%s/%s 조각",
		["%s/%s Profession Slots"]	="%s/%s 전문기술",
        
	        ["Menu"] = "메뉴"
    }
end)