--$Id: zhCN.lua 12749 2006-10-03 02:19:17Z kergoth $-- 
-- zhCN localization by hk2717
AceLibrary("AceLocale-2.1"):RegisterTranslation("OneBag", "zhCN", function()
    return {
		["Frame"]	= "框体",
		["Frame Options"]	= "框体设置",
		["Columns"]	= "栏数",
		["Sets the number of columns to use"]	= "设置每行的背包格子数量",
		["Scale"]	= "缩放",
		["Sets the scale of the frame"]	= "设置框体缩放比例",
		["Strata"]	= "层级",
		["Sets the strata of the frame"]	= "设置框体显示优先级",
		["Alpha"]	= "透明度",
		["Sets the alpha of the frame"]	= "设置框体透明度",
		["Locked"]	= "锁定",
		["Toggles the ability to move the frame"]	= "切换是否锁定框体位置",
		["Clamped"]	= "限制",
		["Toggles the ability to drag the frame off screen."]	= "切换是否限制框体位置使其不能被拖动到屏幕边缘之外。",
		["Bag Break"] = "背包分隔",
		["Sets wether to start a new row at the beginning of a bag."] = "设置是否在背包的起始位置前增加一格。",
		["Vertical Alignment"] = "垂直对齐",
		["Sets wether to have the extra spaces on the top or bottom."] = "设置是否在顶端或底端显示额外的空间。",
		["Top"] = "顶端",
		["Bottom"] = "底端",
		
		["Show"]	= "显示",
		["Various Display Options"]	= "各种显示设置",
		["Counts"]	= "计数",
		["Toggles showing the counts for special bags."]	= "切换是否显示特殊背包的格子计数。",
		["Direction"]	= "方向",
		["Forward"]	= "正向",
		["Toggles direction the bags are shown"]	= "切换背包显示顺序",
		["|cffff0000Reverse|r"]	= "|cffff0000反向|r",
		["|cff00ff00Forward|r"]	= "|cff00ff00正向|r",
		["Ammo Bag"]	= "弹药袋",
		["Turns display of ammo bags on and off."]	= "切换是否显示弹药袋。",
		["Soul Bag"]	= "灵魂袋",
		["Turns display of soul bags on and off."]	= "切换是否显示灵魂袋。",
		["Profession Bag"]	= "专业袋",
		["Turns display of profession bags on and off."]	= "切换是否显示专业袋。",
		["Backpack"] = "背包",
		["Turns display of your backpack on and off."] = "切换是否显示背包。",
		["First Bag"] = "第一个包",
		["Turns display of your first bag on and off."] = "切换是否显示第一个包。",
		["Second Bag"] = "第二个包",
		["Turns display of your second bag on and off."] = "切换是否显示第二个包。",
		["Third Bag"] = "第三个包",
		["Turns display of your third bag on and off."] = "切换是否显示第三个包。",
		["Fourth Bag"] = "第四个包",
		["Turns display of your fourth bag on and off."] = "切换是否显示第四个包。",
		["'s Bags"] = "的背包",		
		
		["Colors"]	= "颜色",
		["Different color code settings."]	= "各种颜色设置。",
		["Mouseover Color"]	= "鼠标悬浮颜色",
		["Changes the highlight color for when you mouseover a bag slot."]	= "变更鼠标悬浮于背包格子上时的高亮颜色。",
		["Ammo Bag Color"]	= "弹药袋颜色",
		["Changes the highlight color for Ammo Bags."]	= "变更弹药袋的高亮颜色。",
		["Soul Bag Color"]	= "灵魂袋颜色",
		["Changes the highlight color for Soul Bags."]	= "变更灵魂袋的高亮颜色。",
		["Profession Bag Color"]	= "专业袋颜色",
		["Changes the highlight color for Profession Bags."]	= "变更专业袋的高亮颜色。",
		["Background Color"]	= "背景颜色",
		["Changes the background color for the frame."]	= "变更框体背景颜色。",
		["Highlight Glow"]	= "高亮发光",
		["Turns hightlight glow on and off."]	= "开关高亮发光。",
		["Rarity Coloring"]	= "品质颜色",
		["Turns rarity coloring on and off."]	= "开关品质颜色。",
		
		["Reset"]	= "重置",
		["Reset the different colors."]	= "重置各种颜色设置",
		["Mouseover Color"]	= "鼠标悬浮颜色",
		["Returns your mouseover color to the default."]	= "重置鼠标悬浮颜色为默认设置。",
		["Ammo Slot Color"]	= "弹药格颜色",
		["Returns your ammo slot color to the default."]	= "重置弹药格颜色为默认设置。",
		["Soul Slot Color"]	= "灵魂格颜色",
		["Returns your soul slot color to the default."]	= "重置灵魂格颜色为默认设置。",
		["Profession Slot Color"]	= "专业格颜色",
		["Returns your profession slot color to the default."]	= "重置专业格颜色为默认设置。",
		["Background"]	= "背景",
		["Returns your frame background to the default."]	= "重置背景颜色为默认设置。",
		["Plow!"]	= "整理！",
		["Organizes your bags."]	= "整理你的背包。",
		["- Note: This option only appears if you have MrPlow installed"]	= "- 注意：只有当你安装了Mr.Plow插件时才会出现此设置",
		
		["%s ran in %s"]	= "%s运行于%s下",
		["Checking if bag %s is open"]	= "检测背包%s是否是打开状态",
		["Opening bag %s"]	= "打开背包%s",
		["Closing bag %s"]	= "关闭背包%s",
			
		["Normal used: %s, Soul used: %s, Prof used: %s, Ammo used %s, Ammo quantity %s."]	= "普通背包已用：%s，灵魂袋已用：%s，专业袋已用：%s，弹药袋已用：%s，弹药品质：%s。",
		["%s/%s Slots"]	= "%s/%s背包",
		["%s/%s Ammo"]	= "%s/%s弹药",
		["%s/%s Soul Shards"]	= "%s/%s灵魂碎片",
		["%s/%s Profession Slots"]	= "%s/%s专业袋",
        
		["Menu"] = "菜单"
    }
end)