TITAN_RUNETELEPORTCOUNTER_ALERT = 5;

TITAN_RUNETELEPORTCOUNTER_ITEMNAME = "Rune of Teleportation";
TITAN_RUNETELEPORTCOUNTER_BUTTON_LABEL = TITAN_RUNETELEPORTCOUNTER_ITEMNAME..": ";
TITAN_RUNETELEPORTCOUNTER_TOOLTIP_COUNT = TITAN_RUNETELEPORTCOUNTER_ITEMNAME..": ";
TITAN_RUNETELEPORTCOUNTER_TOOLTIPTEXT= "Current count of "..TITAN_RUNETELEPORTCOUNTER_ITEMNAME;
TITAN_RUNETELEPORTCOUNTER_MENU_TEXT = "Mage: "..TITAN_RUNETELEPORTCOUNTER_ITEMNAME;

if ( GetLocale() == "deDE" ) then
    TITAN_RUNETELEPORTCOUNTER_ITEMNAME = "Rune der Teleportation";
    TITAN_RUNETELEPORTCOUNTER_BUTTON_LABEL = TITAN_RUNETELEPORTCOUNTER_ITEMNAME..": ";
    TITAN_RUNETELEPORTCOUNTER_TOOLTIP_COUNT = TITAN_RUNETELEPORTCOUNTER_ITEMNAME..": ";
    TITAN_RUNETELEPORTCOUNTER_TOOLTIPTEXT= "Aktuelle Anzahl von"..TITAN_RUNETELEPORTCOUNTER_ITEMNAME;
    TITAN_RUNETELEPORTCOUNTER_MENU_TEXT = "Magier: "..TITAN_RUNETELEPORTCOUNTER_ITEMNAME;
end

if ( GetLocale() == "frFR" ) then
TITAN_RUNETELEPORTCOUNTER_ITEMNAME = "Rune de t\195\169l\195\169portation";
TITAN_RUNETELEPORTCOUNTER_BUTTON_LABEL = TITAN_RUNETELEPORTCOUNTER_ITEMNAME..": ";
TITAN_RUNETELEPORTCOUNTER_TOOLTIP_COUNT = TITAN_RUNETELEPORTCOUNTER_ITEMNAME..": ";
TITAN_RUNETELEPORTCOUNTER_TOOLTIPTEXT= "Compte courant de "..TITAN_RUNETELEPORTCOUNTER_ITEMNAME;
TITAN_RUNETELEPORTCOUNTER_MENU_TEXT = "Mage: "..TITAN_RUNETELEPORTCOUNTER_ITEMNAME;
end