local L = AceLibrary("AceLocale-2.2"):new("BigTrouble")
L:RegisterTranslations("enUS", function()
return {
	["Aimed Shot"] = true,
	["Auto Shot"] = true,
	["SPELLCAST_FAILED"] = "Failed",
	["SPELLCAST_INTERRUPTED"] = "Interrupted",

	["Lock"] = true,
	["Lock/Unlock BigTrouble."] = true,
	["Unlocked"] = true,
	["Locked"] = true,
	["Toggle Auto Shot"] = true,
	["Toggle Auto Shot bar."] = true,
	["On"] = true,
	["Off"] = true,
	["Toggle Aimed Shot"] = true,
	["Toggle Aimed Shot bar."] = true,
	["Bar"] = true, 
	["Set bar."] = true, 
	["Texture"] = true,
	["Toggle the texture."] = true,
	["Border"] = true,
	["Toggle borders BigTrouble"] = true,
	["Width"] = true, 
	["Set the width of BigTrouble."] = true,
	["Aimedshot delay"] = true, 
	["Set the delay of aimed shot."] = true,
	["Height"] = true, 
	["Set the height of BigTrouble."] = true,
	["Font"] = true,
	["Set the font size of BigTrouble."] = true,
	["Spell"] = true, 
	["Set the font size of the spellname."] = true,
	["Time"] = true, 
	["Set the font size of the spell time."] = true,
	["Delay"] = true, 
	["Set the font size on the delay time."] = true,
	["Son of a bitch must pay!"] = true,
}
end)