local L = AceLibrary("AceLocale-2.2"):new("BigTrouble")
L:RegisterTranslations("koKR", function()
return {
	["Aimed Shot"] = "조준 사격",
	["Auto Shot"] = "자동 사격",
	["SPELLCAST_FAILED"] = "실패",
	["SPELLCAST_INTERRUPTED"] = "방해를 받아 취소되었습니다",

	["Lock"] = "잠금",
	["Lock/Unlock BigTrouble."] = "BigTrouble 바의 위치를 잠그거나 잠금을 해제합니다.",
	["Unlocked"] = "이동",
	["Locked"] = "고정",
	["Toggle Auto Shot"] = "자동 사격 토글",
	["Toggle Auto Shot bar."] = "BigTrouble 자동 사격바를 표시하지 않습니다.",
	["On"] = "켬",
	["Off"] = "끔",
	["Toggle Aimed Shot"] = "조준 사격 표시 안함",
	["Toggle Aimed Shot bar."] = "BigTrouble 조준 사격바를 표시하지 않습니다.",
	["Bar"] = "바", 
	["Set bar."] = "바에 대한 설정을 변경합니다.", 
	["Texture"] = "텍스쳐",
	["Toggle the texture."] = "바의 텍스쳐를 변경합니다.",
	["Border"] = "외곽선",
	["Toggle borders BigTrouble"] = "BigTrouble 바의 외곽선 표시를 토글합니다",
	["Width"] = "너비", 
	["Set the width of BigTrouble."] = "BigTrouble 바의 너비를 설정합니다.",
	["Aimedshot delay"] = "조준 사격 지연시간", 
	["Set the delay of aimed shot."] = "조준 사격의 지연시간을 설정합니다.",
	["Height"] = "높이", 
	["Set the height of BigTrouble."] = "BigTrouble 바의 높이를 설정합니다.",
	["Font"] = "폰트",
	["Set the font size of BigTrouble."] = "BigTrouble 바의 글씨들의 크기를 설정합니다.",
	["Spell"] = "주문", 
	["Set the font size of the spellname."] = "주문의 이름의 글씨 크기를 설정합니다.",
	["Time"] = "시전 시간", 
	["Set the font size of the spell time."] = "주문 시전 시간의 글씨 크기를 설정합니다.",
	["Delay"] = "지연 시간", 
	["Set the font size on the delay time."] = "주문 시전 지연 시간의 글씨 크기를 설정합니다.",
	["Son of a bitch must pay!"] = "인과응보!",
}
end)