TITAN_SUMMONER_VERSION = "11000r3";

TITAN_SUMMONER_MENU_TEXT = "Summoner";
TITAN_SUMMONER_BUTTON_LABEL = "Summoner";
TITAN_SUMMONER_BUTTON_TEXT = "%s";
TITAN_SUMMONER_TOOLTIP = "Summoner";

TITAN_SUMMONER_TOOLTIP_TEXT = "Hint: Right-click to toggle summon demons.";

TITAN_SUMMONER_ABOUT_TEXT = "About";
TITAN_SUMMONER_ABOUT_POPUP_TEXT = TitanUtils_GetGreenText("Titan Panel [Summoner]").."\n"..TitanUtils_GetNormalText("Version: ")..TitanUtils_GetHighlightText(TITAN_SUMMONER_VERSION).."\n"..TitanUtils_GetNormalText("Author: ")..TitanUtils_GetHighlightText("Kyzac");

TITAN_SUMMONER_TEXT_IMP = "Summon Imp"
TITAN_SUMMONER_TEXT_VOIDWALKER = "Summon Voidwalker"
TITAN_SUMMONER_TEXT_SUCCUBUS = "Summon Succubus"
TITAN_SUMMONER_TEXT_FELHUNTER = "Summon Felhunter"
TITAN_SUMMONER_TEXT_INFERNAL = "Inferno"
TITAN_SUMMONER_TEXT_DOOMGAURD = "Ritual of Doom"
TITAN_SUMMONER_TEXT_ENSLAVE = "Enslave Demon"

TITAN_SUMMONER_TEXT_FELSTEED = "Summon Felsteed"
TITAN_SUMMONER_TEXT_DREADSTEED = "Summon Dreadsteed"

TITAN_SUMMONER_TEXT_RITUAL = "Ritual of Summoning"
TITAN_SUMMONER_TEXT_EYE = "Eye of Kilrogg"

TITAN_SUMMONER_TEXT_HEALTHSTONEMIN = "Create Healthstone (Minor)"
TITAN_SUMMONER_TEXT_HEALTHSTONEL = "Create Healthstone (Lesser)"
TITAN_SUMMONER_TEXT_HEALTHSTONE = "Create Healthstone"
TITAN_SUMMONER_TEXT_HEALTHSTONEG = "Create Healthstone (Greater)"
TITAN_SUMMONER_TEXT_HEALTHSTONEM = "Create Healthstone (Major)"

TITAN_SUMMONER_TEXT_SOULSTONEMIN = "Create Soulstone (Minor)"
TITAN_SUMMONER_TEXT_SOULSTONEL = "Create Soulstone (Lesser)"
TITAN_SUMMONER_TEXT_SOULSTONE = "Create Soulstone"
TITAN_SUMMONER_TEXT_SOULSTONEG = "Create Soulstone (Greater)"
TITAN_SUMMONER_TEXT_SOULSTONEM = "Create Soulstone (Major)"

TITAN_SUMMONER_TEXT_FIRESTONEL = "Create Firestone (Lesser)"
TITAN_SUMMONER_TEXT_FIRESTONE = "Create Firestone"
TITAN_SUMMONER_TEXT_FIRESTONEG = "Create Firestone (Greater)"
TITAN_SUMMONER_TEXT_FIRESTONEM = "Create Firestone (Major)"

TITAN_SUMMONER_TEXT_SPELLSTONE = "Create Spellstone"
TITAN_SUMMONER_TEXT_SPELLSTONEG = "Create Spellstone (Greater)"
TITAN_SUMMONER_TEXT_SPELLSTONEM = "Create Spellstone (Major)"

TITAN_SUMMONER_SET_SUMMONER_TEXT = "Demons";
TITAN_SUMMONER_SET_MOUNT_TEXT = "Mounts";
TITAN_SUMMONER_SET_PARTY_TEXT = "Party";
TITAN_SUMMONER_SET_STONE_TEXT = "Stones";
