-- items data base
-- array holding inftomation for each libram / enchant

BOOK_ENCHANTS_ITEMS = {
	[BEH_ITEM_ARCANUM_VORACITY] =  {
		["enchants"] = BEH_ITEM_ENCHANTMENT_PLUS8,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_VORACITY,
			"1x "..BEH_STRING_REAGS_BLACKDIAMOND,
			"1x "..BEH_STRING_REAGS_ROOTS,
			"4x "..BEH_STRING_REAGS_CRYSTALFORCE
		},
		["NPCs"] = BEH_STRING_BURNINGSTEPP
	},
	[BEH_ITEM_ARCANUM_RUMINATION] =  {
		["enchants"] = BEH_ITEM_ENCHANTMENT_150MANA,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_RUMINATION,
			"1x "..BEH_STRING_REAGS_BLACKDIAMOND,
			"1x "..BEH_STRING_REAGS_BLACKBLOOD,
			"1x "..BEH_STRING_REAGS_GIZZARDGUM
		},
		["NPCs"] = BEH_STRING_BURNINGSTEPP
	},
	[BEH_ITEM_ARCANUM_CONSTITUTION] =  {
		["enchants"] = BEH_ITEM_ENCHANTMENT_100HEALTH,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_CONSTITUTION,
			"1x "..BEH_STRING_REAGS_BLACKDIAMOND,
			"1x "..BEH_STRING_REAGS_LUNGJUICE,
			"4x "..BEH_STRING_REAGS_NIGHTBREATH
		},
		["NPCs"] = BEH_STRING_BURNINGSTEPP
	},
	[BEH_ITEM_ARCANUM_TENACITY] =  {
		["enchants"] = BEH_ITEM_ENCHANTMENT_125ARMOUR,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_TENACITY,
			"1x "..BEH_STRING_REAGS_BLACKDIAMOND,
			"1x "..BEH_STRING_REAGS_CRYSTALWARD,
			"1x "..BEH_STRING_REAGS_EYEKAJAL
		},
		["NPCs"] = BEH_STRING_BURNINGSTEPP
	},
	[BEH_ITEM_ARCANUM_RESILIENCE] =  {
		["enchants"] = BEH_ITEM_ENCHANTMENT_20FIRE,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_RESILIENCE,
			"1x "..BEH_STRING_REAGS_BLACKDIAMOND,
			"1x "..BEH_STRING_REAGS_BURNINGESSENCE,
			"4x "..BEH_STRING_REAGS_CRYSTALSPIRE
		},
		["NPCs"] = BEH_STRING_BURNINGSTEPP
	},
	[BEH_ITEM_ARCANUM_RAPIDITY] =  {
		["enchants"] = "1% "..BEH_ITEM_ENCHANTMENT_ATTACKSPEED,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_RAPIDITY,
			"2x "..BEH_STRING_REAGS_BLOODHEROS,
			"2x "..BEH_STRING_REAGS_LBRILLSHARD,
			"1x "..BEH_STRING_REAGS_PRBLACKDIAMOND
		},
		["NPCs"] = BEH_STRING_DIREMAUL
	},
	[BEH_ITEM_ARCANUM_FOCUS] =  {
		["enchants"] = "+8 "..BEH_ITEM_ENCHANTMENT_HEALSPELL,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_FOCUS,
			"2x "..BEH_STRING_REAGS_SHADOWSKIN,
			"4x "..BEH_STRING_REAGS_LBRILLSHARD,
			"1x "..BEH_STRING_REAGS_PRBLACKDIAMOND
		},
		["NPCs"] = BEH_STRING_DIREMAUL
	},
	[BEH_ITEM_ARCANUM_PROTECTION] =  {
		["enchants"] = "1% "..BEH_ITEM_ENCHANTMENT_ESCAPE,
		["needed_reags"] = {
			BEH_ITEM_LIBRAM_PROTECTION,
			"1x "..BEH_STRING_REAGS_STITCHING,
			"2x "..BEH_STRING_REAGS_LBRILLSHARD,
			"1x "..BEH_STRING_REAGS_PRBLACKDIAMOND
		},
		["NPCs"] = BEH_STRING_DIREMAUL
	},
	[BEH_ITEM_ENCHANTMENT_DRUID] = {
		["enchants"] = {
			"+10 "..BEH_ITEM_ENCHANTMENT_STAMINA,
			"+10 "..BEH_ITEM_ENCHANTMENT_INTELLECT,
			"+24 "..BEH_ITEM_ENCHANTMENT_HEALSPELL
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_BINDING,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_DRUID,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_PRIEST] = {
		["enchants"] = {
			"+10 "..BEH_ITEM_ENCHANTMENT_STAMINA, 
			"4 "..BEH_ITEM_ENCHANTMENT_MANAREG,
			"+24 "..BEH_ITEM_ENCHANTMENT_HEALSPELL
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_TABARD,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_PRIEST,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_WARLOCK] = {
		["enchants"] = {
			"+10 "..BEH_ITEM_ENCHANTMENT_STAMINA,
			"+18 "..BEH_ITEM_ENCHANTMENT_HEALSPELL
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_ARMSPLINT,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_WARLOCK,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_SHAMAN] = {
		["enchants"] = {
			"+15 "..BEH_ITEM_ENCHANTMENT_INTELLECT,
			"+13 "..BEH_ITEM_ENCHANTMENT_HEALSPELL
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_SASH,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_SHAMAN,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_MAGE] = {
		["enchants"] = {
			"+18 "..BEH_ITEM_ENCHANTMENT_HEALSPELL,
			"1% "..BEH_ITEM_ENCHANTMENT_CASTHIT
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_GIRDLE,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_MAGE,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_HUNTER] = {
		["enchants"] = {
			"+10 "..BEH_ITEM_ENCHANTMENT_STAMINA,
			"+24 "..BEH_ITEM_ENCHANTMENT_DISTPOWER,
			"1% "..BEH_ITEM_ENCHANTMENT_HITCHANCE
			},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_STANCHION,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_HUNTER,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_PALADIN] = {
		["enchants"] = {
			"+10 "..BEH_ITEM_ENCHANTMENT_STAMINA,
			"+7 "..BEH_ITEM_ENCHANTMENT_DEFENCE,
			"+24 "..BEH_ITEM_ENCHANTMENT_HEALSPELL
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_SHAWL,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_PALADIN,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_ROUGE] = {
		["enchants"] = {
			"+28 "..BEH_ITEM_ENCHANTMENT_ATTACKPOWER,
			"1% "..BEH_ITEM_ENCHANTMENT_ESCAPE
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_KOSSACK,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_ROUGE,
		["NPCs"] = BEH_STRING_ZULGURUB
	},
	[BEH_ITEM_ENCHANTMENT_WARRIOR] = {
		["enchants"] = {
			"+10 "..BEH_ITEM_ENCHANTMENT_STAMINA,
			"+7 "..BEH_ITEM_ENCHANTMENT_DEFENCE,
			"+15 "..BEH_ITEM_ENCHANTMENT_SHIELDBLOCK
		},
		["needed_reags"] = {
			BEH_ITEM_HAKKARI_AEGIS,
			BEH_ITEM_DOLL
		},
		["classes"] = BEH_CLASS_WARRIOR,
		["NPCs"] = BEH_STRING_ZULGURUB
	}
};

BOOK_ENCHANTS_QUESTS = {
	[BEH_ITEM_HAKKARI_BINDING] = {
		BEH_CLASS_MAGE,
		BEH_CLASS_PALADIN,
		BEH_CLASS_HUNTER
	},
	[BEH_ITEM_HAKKARI_TABARD] = {
		BEH_CLASS_PALADIN,
		BEH_CLASS_SHAMAN,
		BEH_CLASS_DRUID
	},
	[BEH_ITEM_HAKKARI_ARMSPLINT] = {
		BEH_CLASS_WARRIOR,
		BEH_CLASS_ROUGE,
		BEH_CLASS_SHAMAN
	},
	[BEH_ITEM_HAKKARI_SASH] = {
		BEH_CLASS_PRIEST,
		BEH_CLASS_DRUID,
		BEH_CLASS_WARLOCK
	},
	[BEH_ITEM_HAKKARI_GIRDLE] = {
		BEH_CLASS_WARRIOR,
		BEH_CLASS_ROUGE,
		BEH_CLASS_SHAMAN
	},
	[BEH_ITEM_HAKKARI_STANCHION] = {
		BEH_CLASS_PRIEST,
		BEH_CLASS_DRUID,
		BEH_CLASS_WARLOCK
	},
	[BEH_ITEM_HAKKARI_SHAWL] = {
		BEH_CLASS_MAGE,
		BEH_CLASS_PALADIN,
		BEH_CLASS_HUNTER
	},
	[BEH_ITEM_HAKKARI_KOSSACK] = {
		BEH_CLASS_WARRIOR,
		BEH_CLASS_MAGE,
		BEH_CLASS_WARLOCK
	},
	[BEH_ITEM_HAKKARI_AEGIS] = {
		BEH_CLASS_HUNTER,
		BEH_CLASS_ROUGE,
		BEH_CLASS_PRIEST
	}
};