-- ////////////////////////////////////////////////////////////////
-- GERMAN
-- \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

-- ä = /195/164
-- ü = /195/188
-- ö = /195/182

if ( GetLocale() == "deDE" ) then

ZHUNTER_MAGMADAR = "Magmadar"
ZHUNTER_FLAMEGORE = "Flammenmaul"
ZHUNTER_CHROMMAGUS = "Chrommagus"
ZHUNTER_HUHURAN = "Prinzessin Huhuran"
-- -----ZHUNTER_GLUTH = "Gluth"

ZHUNTER_TRANQCASTYOU = "(.+) (.+) Einlullender Schuss auf (.+)%."
ZHUNTER_TRANQMISSYOU = "kann dies nicht bannen: Raserei"
ZHUNTER_TRANQFAILYOU = "Du konntest (.+)'s Raserei nicht entfernen"
ZHUNTER_TRANQCASTOTHER = "(.+) (.+) Einlullender Schuss auf (.+)%."
ZHUNTER_TRANQMISSOTHER = "(.+) kann (.+) Raserei nicht bannen"
ZHUNTER_TRANQFAILOTHER = "(.+) kann (.+)s Raserei nicht bannen"
ZHUNTER_GAINFRENZY = "(.+) bekommt Raserei"
ZHUNTER_FRENZY = "raserei"

ZHUNTER_YOU = "Ihr"
ZHUNTER_HUNTER = "J\195\164ger"
ZHUNTER_BOWS = "B\195\182gen"
ZHUNTER_CROSSBOWS = "Armbr\195\188ste"
ZHUNTER_GUNS = "Schusswaffen"
ZHUNTER_AFFLICTED_DAZED = "(.+) (.+) ersch\195\188ttert"

ZHUNTER_BULLETS_LIGHT = "Leichtes Geschoss"
ZHUNTER_BULLETS_CRAFTLIGHT = "Gefertigtes leichtes Geschoss"
ZHUNTER_BULLETS_FLASH = "Blitzk\195\188gelchen"
ZHUNTER_BULLETS_HEAVY = "Schweres Geschoss"
ZHUNTER_BULLETS_PEBBLE = "Glatter Kiesel"
ZHUNTER_BULLETS_CRAFTHEAVY = "Gefertigtes schweres Geschoss"
ZHUNTER_BULLETS_SOLID = "Robustes Geschoss"
ZHUNTER_BULLETS_CRAFTSOLID = "Gefertigtes robustes Geschoss"
ZHUNTER_BULLETS_EXPLODING = "Explosivgeschoss"
ZHUNTER_BULLETS_MITHRILSLUG = "Stark einschlagende Mithrilpatronen"
ZHUNTER_BULLETS_ACCURATE = "Genaue Patronen"
ZHUNTER_BULLETS_GYROSHOT = "Gyro-Mithrilgeschoss"
ZHUNTER_BULLETS_ICETHREADED = "Eisgewirkte Kugel"
ZHUNTER_BULLETS_THORIUM = "Thoriumpatronen"
ZHUNTER_BULLETS_ROCKSHARD = "Felssplitterk\195\188gelchen"
ZHUNTER_BULLETS_CANNONBALL = "Miniaturkanonenkugeln"

ZHUNTER_ARROWS_ROUGH = "Rauer Pfeil"
ZHUNTER_ARROWS_SHARP = "Scharfer Pfeil"
ZHUNTER_ARROWS_RAZOR = "Schneidenpfeil"
ZHUNTER_ARROWS_FEATHER = "Gefiederter Pfeil"
ZHUNTER_ARROWS_PRECISION = "Pr\195\164zisionspfeil"
ZHUNTER_ARROWS_JAGGED = "Gezackter Pfeil"
ZHUNTER_ARROWS_ICETHREADED = "Eisgewirkter Pfeil"
ZHUNTER_ARROWS_THORIUM = "Thoriumpfeile"
ZHUNTER_ARROWS_DOOMSHOT = "Verdammnisgeschoss"

ZHUNTER_HUNTERSMARK = "J\195\164germal"
ZHUNTER_RAPIDFIRE = "Schnellfeuer"
ZHUNTER_IMPROVEDHAWK = "Schnelle Sch\195\188sse"
ZHUNTER_BERSERKING = "Berserker"
ZHUNTER_AUTO = "Autom. Schuss"
ZHUNTER_AIMED = "Gezielter Schuss"
ZHUNTER_SERPENT = "Schlangenbiss"
ZHUNTER_SCORPID = "Skorpidstich"
ZHUNTER_VIPER = "Vipernbiss"
ZHUNTER_ARCANE = "Arkaner Schuss"
ZHUNTER_CONCUSSIVE = "Ersch\195\188tternder Schuss"
ZHUNTER_TRANQUILIZING = "Einlullender Schuss"
ZHUNTER_DISTRACTING = "Ablenkender Schuss"

ZHUNTER_TRACK_HUMANOIDS = "Humanoide aufsp\195\188ren"
ZHUNTER_TRACK_HIDDEN = "Verborgenes aufsp\195\188ren"
ZHUNTER_TRACK_BEASTS = "Wildtiere aufsp\195\188ren"
ZHUNTER_TRACK_ELEMENTALS = "Elementare aufsp\195\188ren"
ZHUNTER_TRACK_DEMONS = "D\195\164monen aufsp\195\188ren"
ZHUNTER_TRACK_DRAGONKIN = "Drachkin aufsp\195\188ren"
ZHUNTER_TRACK_UNDEAD = "Untote aufsp\195\188ren"
ZHUNTER_TRACK_GIANTS = "Riesen aufsp\195\188ren"
ZHUNTER_TRACK_MINERALS = "Mineraliensuche"
ZHUNTER_TRACK_HERBS = "Kr\195\164utersuche"
ZHUNTER_TRACK_TREASURE = "Schatzsucher"

ZHUNTER_FEIGN = "Totstellen"
ZHUNTER_TRAP_FREEZING = "Eisk\195\164ltefalle"
ZHUNTER_TRAP_FROST = "Frostfalle"
ZHUNTER_TRAP_IMMOLATION = "Feuerbrandfalle"
ZHUNTER_TRAP_EXPLOSIVE = "Sprengfalle"

ZHUNTER_ASPECT_HAWK = "Aspekt des Falken"
ZHUNTER_ASPECT_MONKEY = "Aspekt des Affen"
ZHUNTER_ASPECT_CHEETAH = "Aspekt des Geparden"
ZHUNTER_ASPECT_BEAST = "Aspekt des Wildtiers"
ZHUNTER_ASPECT_PACK = "Aspekt des Rudels"
ZHUNTER_ASPECT_WILD = "Aspekt der Wildnis"

ZHUNTER_PET_EYES = "Augen des Wildtiers"
ZHUNTER_PET_DISMISS = "Tier freigeben"
ZHUNTER_PET_MEND = "Tier heilen"
ZHUNTER_PET_FEED = "Tier f\195\188ttern"
ZHUNTER_PET_CALL = "Tier rufen"
ZHUNTER_PET_REVIVE = "Tier wiederbeleben"
ZHUNTER_PET_TAMING = "Wildtier z\195\164hmen"
ZHUNTER_PET_TRAINING = "Wildtierausbildung"
ZHUNTER_PET_LORE = "Wildtierkunde"
ZHUNTER_PET_FEAR = "Wildtier \195\164ngstigen"

end