-- ////////////////////////////////////////////////////////////////
-- ENGLISH
-- \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

ZHUNTER_MAGMADAR = "Magmadar"
ZHUNTER_FLAMEGORE = "Flamegore"
ZHUNTER_CHROMMAGUS = "Chrommagus"
ZHUNTER_HUHURAN = "Princess Huhuran"
ZHUNTER_GLUTH = "Gluth"

ZHUNTER_TRANQCASTYOU = "You cast Tranquilizing Shot"
ZHUNTER_TRANQMISSYOU = "Your Tranquilizing Shot miss"
ZHUNTER_TRANQFAILYOU = "You fail to dispel (.+)'s Frenzy"
ZHUNTER_TRANQCASTOTHER = "(.+) (.+) Tranquilizing Shot on (.+)%."
ZHUNTER_TRANQMISSOTHER = "(.+)'s Tranquilizing Shot mis(.+)"
ZHUNTER_TRANQFAILOTHER = "(.+) fails to dispel (.+)'s Frenzy"
ZHUNTER_GAINFRENZY = "(.+) gains Frenzy"
ZHUNTER_FRENZY = "frenzy"

ZHUNTER_YOU = "You"
ZHUNTER_HUNTER = "Hunter"
ZHUNTER_BOWS = "Bows"
ZHUNTER_CROSSBOWS = "Crossbows"
ZHUNTER_GUNS = "Guns"
ZHUNTER_AFFLICTED_DAZED = "(.+) (.+) afflicted by Dazed"

ZHUNTER_BULLETS_LIGHT = "Light Shot"
ZHUNTER_BULLETS_CRAFTLIGHT = "Crafted Light Shot"
ZHUNTER_BULLETS_FLASH = "Flash Pellet"
ZHUNTER_BULLETS_HEAVY = "Heavy Shot"
ZHUNTER_BULLETS_PEBBLE = "Smooth Pebble"
ZHUNTER_BULLETS_CRAFTHEAVY = "Crafted Heavy Shot"
ZHUNTER_BULLETS_SOLID = "Solid Shot"
ZHUNTER_BULLETS_CRAFTSOLID = "Crafted Solid Shot"
ZHUNTER_BULLETS_EXPLODING = "Exploding Shot"
ZHUNTER_BULLETS_MITHRILSLUG = "Hi-impact Mithril Slugs"
ZHUNTER_BULLETS_ACCURATE = "Accurate Slugs"
ZHUNTER_BULLETS_GYROSHOT = "Mithril Gyro-Shot"
ZHUNTER_BULLETS_ICETHREADED = "Ice Threaded Bullet"
ZHUNTER_BULLETS_THORIUM = "Thorium Shells"
ZHUNTER_BULLETS_ROCKSHARD = "Rockshard Pellets"
ZHUNTER_BULLETS_CANNONBALL = "Miniature Cannon Balls"

ZHUNTER_ARROWS_ROUGH = "Rough Arrow"
ZHUNTER_ARROWS_SHARP = "Sharp Arrow"
ZHUNTER_ARROWS_RAZOR = "Razor Arrow"
ZHUNTER_ARROWS_FEATHER = "Feathered Arrow"
ZHUNTER_ARROWS_PRECISION = "Precision Arrow"
ZHUNTER_ARROWS_JAGGED = "Jagged Arrow"
ZHUNTER_ARROWS_ICETHREADED = "Ice Threaded Arrow"
ZHUNTER_ARROWS_THORIUM = "Thorium Headed Arrow"
ZHUNTER_ARROWS_DOOMSHOT = "Doomshot"

ZHUNTER_HUNTERSMARK = "Hunter's Mark"
ZHUNTER_RAPIDFIRE = "Rapid Fire"
ZHUNTER_IMPROVEDHAWK = "Quick Shots"
ZHUNTER_BERSERKING = "Berserking"
ZHUNTER_AUTO = "Auto Shot"
ZHUNTER_AIMED = "Aimed Shot"
ZHUNTER_SERPENT = "Serpent Sting"
ZHUNTER_SCORPID = "Scorpid Sting"
ZHUNTER_VIPER = "Viper Sting"
ZHUNTER_ARCANE = "Arcane Shot"
ZHUNTER_CONCUSSIVE = "Concussive Shot"
ZHUNTER_TRANQUILIZING = "Tranquilizing Shot"
ZHUNTER_DISTRACTING = "Distracting Shot"
ZHUNTER_VOLLEY = "Volley"

ZHUNTER_TRACK_HUMANOIDS = "Track Humanoids"
ZHUNTER_TRACK_HIDDEN = "Track Hidden"
ZHUNTER_TRACK_BEASTS = "Track Beasts"
ZHUNTER_TRACK_ELEMENTALS = "Track Elementals"
ZHUNTER_TRACK_DEMONS = "Track Demons"
ZHUNTER_TRACK_DRAGONKIN = "Track Dragonkin"
ZHUNTER_TRACK_UNDEAD = "Track Undead"
ZHUNTER_TRACK_GIANTS = "Track Giants"
ZHUNTER_TRACK_MINERALS = "Find Minerals"
ZHUNTER_TRACK_HERBS = "Find Herbs"
ZHUNTER_TRACK_TREASURE = "Find Treasure"

ZHUNTER_FEIGN = "Feign Death"
ZHUNTER_TRAP_FREEZING = "Freezing Trap"
ZHUNTER_TRAP_FROST = "Frost Trap"
ZHUNTER_TRAP_IMMOLATION = "Immolation Trap"
ZHUNTER_TRAP_EXPLOSIVE = "Explosive Trap"

ZHUNTER_ASPECT_HAWK = "Aspect of the Hawk"
ZHUNTER_ASPECT_MONKEY = "Aspect of the Monkey"
ZHUNTER_ASPECT_CHEETAH = "Aspect of the Cheetah"
ZHUNTER_ASPECT_BEAST = "Aspect of the Beast"
ZHUNTER_ASPECT_PACK = "Aspect of the Pack"
ZHUNTER_ASPECT_WILD = "Aspect of the Wild"

ZHUNTER_PET_EYES = "Eyes of the Beast"
ZHUNTER_PET_DISMISS = "Dismiss Pet"
ZHUNTER_PET_MEND = "Mend Pet"
ZHUNTER_PET_FEED = "Feed Pet"
ZHUNTER_PET_CALL = "Call Pet"
ZHUNTER_PET_REVIVE = "Revive Pet"
ZHUNTER_PET_LORE = "Beast Lore"
ZHUNTER_PET_TRAINING = "Beast Training"
ZHUNTER_PET_TAMING = "Tame Beast"
ZHUNTER_PET_FEAR = "Fear Beast"