if (GetLocale() == "frFR") then 

PowaAnim = {};
PowaAnim[0] = "[Invisible]";
PowaAnim[1] = "Statique";
PowaAnim[2] = "Clignotement";
PowaAnim[3] = "Agrandir";
PowaAnim[4] = "Pulsation";
PowaAnim[5] = "Effet bulle";
PowaAnim[6] = "Goutte d'eau";
PowaAnim[7] = "Electrique";
PowaAnim[8] = "R\195\169tr\195\169cir";
PowaAnim[9] = "Flamme";
PowaAnim[10] = "Orbite";

PowaDisplay = {};
PowaDisplay[0] = "[Aucun]";
PowaDisplay[1] = "Zoom Avant";
PowaDisplay[2] = "Zoom Arriere";
PowaDisplay[3] = "Transparence seule";
PowaDisplay[4] = "Gauche";
PowaDisplay[5] = "Haut-Gauche";
PowaDisplay[6] = "Haut";
PowaDisplay[7] = "Haut-Droite";
PowaDisplay[8] = "Droite";
PowaDisplay[9] = "Bas-Droite";
PowaDisplay[10] = "Bas";
PowaDisplay[11] = "Bas-Gauche";

PowaText = {
	welcome = "Tapez /powa pour afficher les options.",

	aucune = "Aucune",
	aucun = "Aucun",
	largeur = "Largeur",
	hauteur = "Hauteur",

	aideTexture = "La texture \195\160 afficher. Vous pouvez facilement remplacer les textures en changeant les fichier Aura#.tga du dossier de l'AddOn.",
	aideAnim1 = "Anime la texture ou pas, avec diff\195\169rents effets.",
	aideAnim2 = "Cette animation sera affich\195\169e avec moins d'opacit\195\169 que la principale. Attention, afin de ne pas surcharger le tout, une seule animation secondaire sera affich\195\169e a la fois.",
	aideDeform = "Etire la texture vers le haut ou en largeur.",
	aideColor = "Cliquez ici pour changer la couleur de la texture.",
	aideBuff = "Entrez ici le nom du buff, ou une partie du nom, qui doit activer/d\195\169sactiver l'effet. Vous pouvez entrer plusieurs noms s'ils sont s\195\169par\195\169 comme il convient (ex: Super Buff/Puissance)",
	aideBuff2 = "Entrez ici le nom du d\195\169buff, ou une partie du nom, qui doit activer/d\195\169sactiver l'effet. Vous pouvez entrer plusieurs noms s'ils sont s\195\169par\195\169 comme il convient (ex: Maladie noire/Peste)",
	aideBuff3 = "Entrez ici le type du d\195\169buff qui doit activer ou d\195\169sactiver l'effet (Poison, Maladie, Mal\195\169diction, Magie ou Aucun). Vous pouvez aussi entrer plusieurs types de d\195\169buffs \195\160 la fois.",
	aideDebuff = "Cochez cette case si vous voulez que cet effet s'applique plut\195\180t \195\160 un d\195\169buff.",
	aideDebuffType = "Cochez cette case si vous voulez que cet effet s'applique \195\160  un type de d\195\169buff particulier (commun\195\169ment : Poison, Maladie, Mal\195\169diction, Magie...)",
	aideShowTimer = "Cochez cette case pour afficher la dur\195\169e de cet effet.",
	aideInverse = "Cochez cette case pour afficher cet effet uniquement quand le buff/d\195\169buff n'est pas actif.",
	aideIgnoreMaj = "Cochez cette case pour ignorer les majuscules/minuscules du nom des buffs/d\195\169buffs.",
	aideDisable = "D\195\169sactive tous les effets",
	aideDuration = "Pass\195\169 ce d\195\169lai, l'animation sera masqu\195\169e (0 pour d\195\169sactiver)",
	aideListe = "Ceci est la liste des effets disponibles par tous les personnages. Attention, seuls les effets pr\195\169sents dans l'\195\169diteur d'effet seront actifs.",
	aideMaxTex = "Defini le maximum de textures disponibles dans l'Editeur d'Effets. Si vous rajoutez des textures en les mettant dans le dossier de l'AddOn (nomm\195\169es de AURA1.tga \195\160 AURA50.tga) c'est ici qu'il faudra le signaler.",
	aideClear = "Supprime tous les effets qui n'ont pas de nom, et trie les effets restants par type.",
	aideAddEffect = "Ajoute une page d'effet.",
	nomBuff = "Nom du Buff",
	nomDebuff = "Nom du Debuff",
	nomDebuffType = "Type de Debuff",
	nomCheckBuff = "Buff",
	nomCheckDebuff = "Debuff",
	nomCheckDebuffType = "Type du Debuff",
	nomCheckShowTimer = "Afficher la dur\195\169e",
	nomCheckInverse = "Afficher si inactif",
	nomCheckIgnoreMaj = "Ignorer les majuscules",
	nomTexture = "Texture",
	nomAnim1 = "Animation principale",
	nomAnim2 = "Animation secondaire",
	nomSpeed = "Vitesse d'Anim.",
	nomBegin = "Animation de d\195\169part",
	nomEnd = "Animation de fin",
	nomDuration = "Dur\195\169e de l'Anim.",
	nomSymetrie = "Sym\195\169trie",
	nomAlpha = "Transparence",
	nomPos = "Position",
	nomTaille = "Taille",
	nomDeform = "D\195\169formation",
	nomTest = "Tester",
	nomHide = "Tout masquer",
	nomClose = "Fermer",
	nomTitre = "Effet",
	nomListe = "Liste >>",
	nomCentiemes = "Afficher centiemes",
	nomDual = "Afficher 2 dur\195\169es",
	nomDisable = "D\195\169sactiver Power Auras",
	nomEffectEditor = "Editeur d'Effets",
	nomAdvOptions = "Options Avanc\195\169es",
	nomMaxTex = "Maximum de textures disponibles",
	nomTabAnim = "Animation",
	nomTabActiv = "Activation",
	listheader = "Liste des Buffs/Debuffs",
	listdelete = "Efface cet effet.",
	listload = "Copie cet effet dans la fenetre d'\195\169dition en cours.",
	listadd = ">> Ajouter",
	listaideadd = "Sauvegarde dans la liste l'effet actuellement \195\169dit\195\169.",
	erreur1 = "Erreur : L'effet actuel n'a aucun nom.",
	erreur2 = "Erreur : Un effet portant ce nom existe d\195\169j\195\160.",
	erreur3 = "Erreur : Pas assez de place pour sauver."
};

else

PowaAnim = {};
PowaAnim[0] = "[Invisible]";
PowaAnim[1] = "Static";
PowaAnim[2] = "Flashing";
PowaAnim[3] = "Growing";
PowaAnim[4] = "Pulse";
PowaAnim[5] = "Bubble";
PowaAnim[6] = "Water drop";
PowaAnim[7] = "Electric";
PowaAnim[8] = "Shrinking";
PowaAnim[9] = "Flame";
PowaAnim[10] = "Orbit";

PowaDisplay = {};
PowaDisplay[0] = "[None]";
PowaDisplay[1] = "Zoom In";
PowaDisplay[2] = "Zoom Out";
PowaDisplay[3] = "Opacity only";
PowaDisplay[4] = "Left";
PowaDisplay[5] = "Top-Left";
PowaDisplay[6] = "Top";
PowaDisplay[7] = "Top-Right";
PowaDisplay[8] = "Right";
PowaDisplay[9] = "Bottom-Right";
PowaDisplay[10] = "Bottom";
PowaDisplay[11] = "Bottom-Left";

PowaText = {
	welcome = "Type /powa to view the options.",

	aucune = "None",
	aucun = "None",
	largeur = "Width",
	hauteur = "Height",

	aideTexture = "The texture to be shown. You can easily replace textures by changing the files Aura#.tga in the Addon's directory.",
	aideAnim1 = "Animate the texture or not, with various effects.",
	aideAnim2 = "This animation will be shown with less opacity than the main animation. Attention, to not overload the screen, only a single secondary animation will be shown at the same time.",
	aideDeform = "Stretch the texture in height or in width.",
	aideColor = "Click here to change the color of the texture.",
	aideBuff = "Enter here the name of the buff, or a part of the name, which must activate/deactivate the effect. You can enter several names if they are decently separated (ex: Super Buff/Power)",
	aideBuff2 = "Enter here the name of the debuff, or a part of the name, which must activate/deactivate the effect. You can enter several names if they are decently separated (ex: Dark Disease/Plague)",
	aideBuff3 = "Enter here the type of the debuff which must activate or deactivate the effect (Poison, Disease, Curse, Magic or None). You can also enter several types of debuff.",
	aideDebuff = "Check this to maket this effect applies to a debuff.",
	aideDebuffType = "Check this to make this effect applies to a specific kind of debuff (Poison, Disease, Curse, Magic...)",
	aideShowTimer = "Check this to show the timer of this effect.",
	aideInverse = "Check this to show this effect only when buff/debuff is not active.",	
	aideIgnoreMaj = "Check this to ignore upper/lowercase of buff/debuff names.",
	aideDisable = "Disable all effects",
	aideDuration = "After this time, this effect will disapear (0 to deactivate)",
	aideListe = "This is the list of effects available by all characters. Beware, only the effects in the Effect Editor will be active.",
	aideMaxTex = "Define the maximum number of textures available on the Effect Editor. If you add textures on the Mod directory (with the names AURA1.tga to AURA50.tga), you must indicate the correct number here.",
	aideClear = "Delete all effects which don't have any name, and sort the others by type.",
	aideAddEffect = "Add an effect for edition.",
	nomBuff = "Name of the Buff",
	nomDebuff = "Name of the Debuff",
	nomDebuffType = "Type of the Debuff",
	nomCheckBuff = "Buff",
	nomCheckDebuff = "Debuff",
	nomCheckDebuffType = "Debuff's type",
	nomCheckShowTimer = "Show Timer",
	nomCheckInverse = "Show when not active",
	nomCheckIgnoreMaj = "Ignore uppercase",	
	nomTexture = "Texture",
	nomAnim1 = "Main Animation",
	nomAnim2 = "Secondary Animation",
	nomSpeed = "Animation speed",
	nomBegin = "Begin Animation",
	nomEnd = "End Animation",
	nomDuration = "Anim. duration",
	nomSymetrie = "Symmetry",
	nomAlpha = "Opacity",
	nomPos = "Position",
	nomTaille = "Size",
	nomDeform = "Deformation",
	nomTest = "Test",
	nomHide = "Hide all",
	nomClose = "Close",
	nomTitre = "Effect",
	nomListe = "List >>",
	nomCentiemes = "Show hundredth",
	nomDual = "Show 2 timers",
	nomDisable = "Desactivate Power Auras",
	nomEffectEditor = "Effect Editor",
	nomAdvOptions = "Advanced Options",
	nomMaxTex = "Maximum of textures available",
	nomTabAnim = "Animation",
	nomTabActiv = "Activation",
	listheader = "Buffs/Debuffs List",
	listdelete = "Delete this effect.",
	listload = "Copy this effect to the current edition window.",
	listadd = ">> Add",
	listaideadd = "Save in the list the current edited effect.",
	erreur1 = "Error : The current effect dont have any name.",
	erreur2 = "Error : A saved effect already have this name.",
	erreur3 = "Error : Not enough room to save this effect."
};

end

