lazyPriestLoad.metadata:updateRevisionFromKeyword("$Revision: 308 $")

function lazyPriestLoad.LoadPriestLocalization(locale)

   lazyPriestLocale.enUS.ACTION_TTS.abolishDisease                   = "Abolish Disease"
   lazyPriestLocale.enUS.ACTION_TTS.cureDisease                      = "Cure Disease"
   lazyPriestLocale.enUS.ACTION_TTS.desperatePrayer                  = "Desperate Prayer"
   lazyPriestLocale.enUS.ACTION_TTS.devouringPlague                  = "Devouring Plague"
   lazyPriestLocale.enUS.ACTION_TTS.dispelMagic                      = "Dispel Magic"
   lazyPriestLocale.enUS.ACTION_TTS.divineSpirit                     = "Divine Spirit"
   lazyPriestLocale.enUS.ACTION_TTS.elunesGrace                      = "Elune's Grace"
   lazyPriestLocale.enUS.ACTION_TTS.fade                             = "Fade"
   lazyPriestLocale.enUS.ACTION_TTS.fearWard                         = "Fear Ward"
   lazyPriestLocale.enUS.ACTION_TTS.feedback                         = "Feedback"
   lazyPriestLocale.enUS.ACTION_TTS.flashHeal                        = "Flash Heal"
   lazyPriestLocale.enUS.ACTION_TTS.greaterHeal                      = "Greater Heal"
   lazyPriestLocale.enUS.ACTION_TTS.heal                             = "Heal"
   lazyPriestLocale.enUS.ACTION_TTS.hexWeakness                      = "Hex of Weakness"
   lazyPriestLocale.enUS.ACTION_TTS.holyFire                         = "Holy Fire"
   lazyPriestLocale.enUS.ACTION_TTS.holyNova                         = "Holy Nova"
   lazyPriestLocale.enUS.ACTION_TTS.innerFire                        = "Inner Fire"
   lazyPriestLocale.enUS.ACTION_TTS.innerFocus                       = "Inner Focus"
   lazyPriestLocale.enUS.ACTION_TTS.lesserHeal                       = "Lesser Heal"
   lazyPriestLocale.enUS.ACTION_TTS.levitate                         = "Levitate"
   lazyPriestLocale.enUS.ACTION_TTS.lightwell                        = "Lightwell"
   lazyPriestLocale.enUS.ACTION_TTS.lightwellRenew                   = "Lightwell Renew"
   lazyPriestLocale.enUS.ACTION_TTS.manaBurn                         = "Mana Burn"
   lazyPriestLocale.enUS.ACTION_TTS.mindBlast                        = "Mind Blast"
   lazyPriestLocale.enUS.ACTION_TTS.mindControl                      = "Mind Control"
   lazyPriestLocale.enUS.ACTION_TTS.mindFlay                         = "Mind Flay"
   lazyPriestLocale.enUS.ACTION_TTS.mindSoothe                       = "Mind Soothe"
   lazyPriestLocale.enUS.ACTION_TTS.mindVision                       = "Mind Vision"
   lazyPriestLocale.enUS.ACTION_TTS.powerInfusion                    = "Power Infusion"
   lazyPriestLocale.enUS.ACTION_TTS.pwf                              = "Power Word: Fortitude"
   lazyPriestLocale.enUS.ACTION_TTS.pws                              = "Power Word: Shield"
   lazyPriestLocale.enUS.ACTION_TTS.prf                              = "Prayer of Fortitude"
   lazyPriestLocale.enUS.ACTION_TTS.prh                              = "Prayer of Healing"
   lazyPriestLocale.enUS.ACTION_TTS.prsp                             = "Prayer of Shadow Protection"
   lazyPriestLocale.enUS.ACTION_TTS.prs                              = "Prayer of Spirit"
   lazyPriestLocale.enUS.ACTION_TTS.psychicScream                    = "Psychic Scream"
   lazyPriestLocale.enUS.ACTION_TTS.renew                            = "Renew"
   lazyPriestLocale.enUS.ACTION_TTS.resurrection                     = "Resurrection"
   lazyPriestLocale.enUS.ACTION_TTS.shackleUndead                    = "Shackle Undead"
   lazyPriestLocale.enUS.ACTION_TTS.shadowProtection                 = "Shadow Protection"
   lazyPriestLocale.enUS.ACTION_TTS.swp                              = "Shadow Word: Pain"
   lazyPriestLocale.enUS.ACTION_TTS.shadowform                       = "Shadowform"
   lazyPriestLocale.enUS.ACTION_TTS.shadowguard                      = "Shadowguard"
   --lazyPriestLocale.enUS.ACTION_TTS.shoot                            = "Shoot"
   lazyPriestLocale.enUS.ACTION_TTS.silence                          = "Silence"
   lazyPriestLocale.enUS.ACTION_TTS.smite                            = "Smite"
   lazyPriestLocale.enUS.ACTION_TTS.starshards                       = "Starshards"
   lazyPriestLocale.enUS.ACTION_TTS.touchWeakness                    = "Touch of Weakness"
   lazyPriestLocale.enUS.ACTION_TTS.vampiricEmbrace                  = "Vampiric Embrace"

   -- assume english, unless overridden below
   if (locale == "deDE") then -- German
      lazyPriestLocale.deDE.ACTION_TTS.lightwell                        = "Brunnen des Lichts"
      lazyPriestLocale.deDE.ACTION_TTS.lightwellRenew                   = "Erneuerung des Lichtbrunnens"
   elseif (locale == "frFR") then -- French
      lazyPriestLocale.frFR.ACTION_TTS.lightwell                        = "Puits de lumi\195\168re"
      lazyPriestLocale.frFR.ACTION_TTS.lightwellRenew                   = "R\195\169novation du Puits de lumi\195\168re"
   end
end

