-- Version : Korean ( by gygabyte )
-- Last Update : 10/26/2006

local L = AceLibrary("AceLocale-2.2"):new("MainAssist")

L:RegisterTranslations("koKR", function()
    return {
		["TANK_LIST_HEADER"] = "탱커 목록",
		["CUSTOM"] = "사용자 설정",
		["CUSTOM_DESC"] = "사용자 탱커 목록 관리",
		["ADDNAME"] = "탱커 이름으로 추가",
		["ADD"] = "추가",
		["ADD_USAGE"] = "<탱커 이름>",
		["ADD_DESC"] = "사용자 탱커 목록에 탱커를 추가합니다.",
		["ADDTARGET"] = "대상 추가",
		["ADDTARGET_SHORT"] = "대상 추가",
		["ADDTARGET_DESC"] = "사용자 탱커 목록에 현태 대상을 추가합니다.",
		["REMOVE"] = "삭제",
		["REMOVE_DESC"] = "사용자 탱커목록에서 탱커를 삭제합니다.",
		["ARRANGE"] = "위치 정렬",
		["ARRANGE_DESC"] = "탱커를 선택하면 목록에서 위로 올라가고, 쉬프트를 누룬채로 탱커를 선택하면 목록에서 아래로 이동합니다.",
		["CLEAR"] = "초기화",
		["CLEAR_CUSTOM_DESC"] = "사용자 탱커 목록을 초기화 합니다.",
		["HIDE_CTRA"] = "CTRA 탱커 숨김",
		["HIDE_CTRA_DESC"] = "CTRA 탱커 목록이 있으면 사용자 탱커목록 숨깁니다.",
		["ENABLE"] = "활성화",
		["ENABLE_CTRA_DESC"] = "CTRA 탱커 목록을 표시를 활성화 합니다.",
		["CTRA"] = "CTRA",
		["CTRA_DESC"] = "CTRA 탱커 목록 관리",
		["ENABLE_CUSTOM_DESC"] = "사용자 탱커 목록을 활성화 합니다.",
		["SMART_ASSIST"] = "자동 지원 목록",
		["SMART_ASSIST_OPTIONS"] = "자동 지원 목록 설정",
		["CTRA_ASSIST_LAST"] = "CTRA 탱커 목록 아래로",
		["CTRA_ASSIST_LAST_DESC"] = "활성화 하면, 지원 목록은 CTRA 탱커 목록의 아래에 위치하고, 비활성화 하면 위에 위치하게 됩니다.",
		["CUSTOM_ASSIST_LAST"] = "사용자 탱커 목록 아래로",
		["CUSTOM_ASSIST_LAST_DESC"] = "활성화 하면, 지원 목록은 사용자 탱커 목록의 아래에 위치하고, 비활성화 하면 위에 위치하게 됩니다.",
		["SHOWTOT_SHORT"] = "ToT 표시",
		["SHOWTOT"] = "대상의 대상 표시",
		["SHOWTOT_DESC"] = "탱커들을 위한 대상의 대상을 표시합니다.",
		["COLORING"] = "색상화",
		["COLORING_DESC"] = "탱커 창의 색상화 되는 방법을 변경합니다.",
		["UNIQUE"] = "희귀",
		["UNIQUE_DESC"] = "탱커가 희귀 대상을 가지면 목록에서 녹색으로 보여집니다.",
		["SELF"] = "자신",
		["SELF_DESC"] = "탱커가 나와 같은 대상을 가지면 녹색으로 보여집니다.",
		["OPTIONS"] = "설정",
		["SCALE"] = "크기",
		["SCALE_DESC"] = "MainAssist 창의 크기를 조절합니다.",
		["LOCK"] = "고정",
		["LOCK_DESC"] = "원하는 위치에 창을 고정시킵니다",
		["HIDELOCKED"] = "고정시 숨김",
		["HIDELOCKED_GUI"] = "고정시 창 이름 숨김",
		["HIDELOCKED_DESC"] = "고정시킬 때 MainAssist 창 제목을 숨깁니다 (메뉴를 표시할려면 /ma menu 또는 단축키를 사용하세요)",
		["RESET_GUI"] = "초기화 위치",
		["RESET"] = "초기화",
		["RESET_DESC"] = "기본값으로 창 위치를 초기화 시킵니다.",
		["MENU"] = "메뉴",
		["MENU_DESC"] = "MainAssist 메뉴를 표시합니다.",
		["STATUS_DEAD"] = "*죽음*",
		["STATUS_NOTHERE"] = "*Not Here*",
		["STATUS_NONE"] = "*없음*"
    }
end)