MINIGROUP2_DEFAULT_OPTIONS = {
	Version = "dd-mm-yy",
	ShowMapButton = 1,	
	LockMGFrames = 1,
	CastPartyEnabled = 1,
	CastPartyTargetEnabled = 1,
	AlphaBorder = 0,
	IconPosition = 188,	
	CastPartyOverrideMouse = 2,
	CastPartyOverrideAlt = 0,
	CastPartyOverrideCtrl = 0,
	CastPartyOverrideShift = 0,	
	ShowClassText = 1,
	ShowEndcaps = 0,
	HighlightSelected = 1,
	UsePartyRaidColors = 1,
	HidePvPIcon = 1,
	HideGroupIcons = 0,
	RaidHideParty = 1,
	SmoothHealthBars = 1,
	RaidColorName = 0,
	
	BorderStyle = 3,
	BarStyle = 2,
	
	FrameGrowth = 1,
		
	ShowBlizFrames = {
		["PlayerFrame"] = 0,
		["PartyFrame"] = 0,
		["TargetFrame"] = 0
	},

	Anchors = {
		["MGraid_achor1"] = nil,
		["MGraid_achor2"] = "MGraid_achor1",
		["MGraid_achor3"] = "MGraid_achor2",
		["MGraid_achor4"] = "MGraid_achor3",
		["MGraid_achor5"] = "MGraid_achor4",
		["MGraid_achor6"] = "MGraid_achor5",		
		["MGraid_achor7"] = "MGraid_achor6",
		["MGraid_achor8"] = "MGraid_achor7"
		},
	
	PartyPetGrouping = 4,
	PartyGrouping = 0,
	
	PartyFrameColors = {
		r = 0,
		g = 0,
		b = 0,
		a = 0.5},
	TargetFrameColors = {
		r = 0,
		g = 0,
		b = 0,
		a = 0.5},

	DebuffOrder = {
		[1] = "Magic",
		[2] = "Poison",
		[3] = "Disease",
		[4] = "Curse",
		[5] = "None"
	},
	DebuffColors = {
		["Magic"] = {r = 0.5, g = 0.5, b = 0.75, c = "!"},
		["Poison"] = {r = 0.75, g = 0, b = 0, c = "$"},
		["Disease"] = {r = 1, g = 1, b = 0, c = "^"},
		["Curse"] = {r = 1, g = 0.5, b = 0, c = "@"},
		["None"] = {r = 1.0, g = 0.82, b = 0, c = ""}
	},
	
	Scaling = {
		["UseMGScale"] = 0,
		["MGScale"] = 1,
		["UseRaidScale"] = 1,
		["RaidScale"] = 0.75,				
	},
	
	RestIndicator = 2,
	FlashRestIndicator = 1,
	CombatIndicator = 2,
	FlashCombatIndicator = 1,
	AggroIndicator = 2,
	FlashAggroIndicator = 1,
		
	PlayerStatusTextStyle = 1,
	PlayerBarTextStyle = 4,
	PlayerFrameStyle = 1,
	PlayerAuraStyle = 1,
	PlayerAuraTipStyle = 1,	
	PlayerAuraPos = 6,
	PlayerAuraFilter = 1,
	PlayerAuraDebuffC = 1,
	
	PartyStatusTextStyle = 1,
	PartyBarTextStyle = 4,
	PartyFrameStyle = 1,
	PartyAuraStyle = 1,
	PartyAuraTipStyle = 1,	
	PartyAuraPos = 6,
	PartyAuraFilter = 1,
	PartyAuraDebuffC = 1,
	
	PartyPetStatusTextStyle = 1,
	PartyPetBarTextStyle = 4,
	PartyPetFrameStyle = 1,
	PartyPetAuraStyle = 5,
	PartyPetAuraTipStyle = 1,	
	PartyPetAuraPos = 6,
	PartyPetAuraFilter = 1,
	PartyPetAuraDebuffC = 1,
	PartyPetHideMana = 1,
	
	PetStatusTextStyle = 1,
	PetBarTextStyle = 4,
	PetFrameStyle = 1,
	PetAuraStyle = 1,
	PetAuraTipStyle = 1,	
	PetAuraPos = 6,
	PetAuraFilter = 1,
	PetAuraDebuffC = 1,
	
	RaidStatusTextStyle = 1,
	RaidBarTextStyle = 4,
	RaidFrameStyle = 1,
	RaidAuraStyle = 1,
	RaidAuraTipStyle = 1,	
	RaidAuraPos = 6,
	RaidAuraFilter = 1,
	RaidAuraDebuffC = 1,
	RaidHideMana = 1,
	RaidHideFrame = 1,
	
	RaidByClass = 0,
	ShowAnchors = 1,
	HideAnchorBackgrounds = 1,
	
	RaidPetStatusTextStyle = 1,
	RaidPetBarTextStyle = 4,
	RaidPetFrameStyle = 1,
	RaidPetAuraStyle = 5,
	RaidPetAuraTipStyle = 1,	
	RaidPetAuraPos = 6,
	RaidPetAuraFilter = 1,
	RaidPetAuraDebuffC = 1,
	RaidPetHideMana = 1,
	RaidPetHideFrame = 1,
	
	TargetStatusTextStyle = 1,
	TargetBarTextStyle = 4,
	TargetFrameStyle = 1,
	TargetAuraStyle = 2,
	TargetAuraTipStyle = 1,	
	TargetAuraPos = 2,
	TargetAuraFilter = 0,
	TargetAuraDebuffC = 0,
	
	TargettargetStatusTextStyle = 1,
	TargettargetBarTextStyle = 4,
	TargettargetFrameStyle = 1,
	TargettargetAuraStyle = 2,
	TargettargetAuraTipStyle = 1,	
	TargettargetAuraPos = 2,	
	TargettargetAuraFilter = 0,
	TargettargetAuraDebuffC = 0,
	TargettargetHideMana = 1,
	
	ShowPlayerCombat = 1,
	ShowPetCombat = 1,
	ShowPartyCombat = 1,
	ShowPartyPetCombat = 0,
	ShowRaidCombat = 1,
	ShowRaidPetCombat = 0,
	ShowTargetCombat = 1,
	ShowTargettargetCombat = 1,
	
	ShowPlayerXP = 1,
	ShowPetXP = 1,
	
	PlayerGrouping = 1,
	PetGrouping = 1,
	PartyGrouping = 1,
	PartyPetGrouping = 1,
	RaidGrouping = 1,
	RaidPetGrouping = 1,
	GroupSpace = 1,
	
	TargetShowHostile = 1,
	HideCastBars = 0,
	HideOORAlerts = 0,
	HideNotHereAlerts = 0,
	HideNotHereAlertsOffline = 1,
	ShowBuffTimes = 1,
	OORSpell = 1,
	UseBigHealthFonts = 0,
	CastBarR = 0.7,
	CastBarG = 0,
	CastBarB = 0.3,
	HideFSR = 0,
	HideOOFSR = 0,

	MGparty1Pos = {
		["x"] = 10,
		["y"] = -40,				
	},	
	MGpartypet1Pos = {
		["x"] = 10,
		["y"] = -80,				
	},	
	MGparty2Pos = {
		["x"] = 10,
		["y"] = -120,				
	},	
	MGpartypet2Pos = {
		["x"] = 10,
		["y"] = -160,				
	},
	MGparty3Pos = {
		["x"] = 10,
		["y"] = -200,				
	},	
	MGpartypet3Pos = {
		["x"] = 10,
		["y"] = -240,				
	},
	MGparty4Pos = {
		["x"] = 10,
		["y"] = -280,				
	},	
	MGpartypet4Pos = {
		["x"] = 0,
		["y"] = -320,				
	},	
}