FactionItemsFuLocals = {
	NAME = "FuBar - FactionItemsFu",
	DESCRIPTION = "Keeps track of Items used to gain Faction or Faction Rewards",
		
	TEXT_SET = "FactionItems",
    MENU_SHOW_ITEM_TEXT = "Show Text",
    MENU_TEXT_TITLE = "Show Title Text",
    MENU_TEXT_BANK_BAGS = "Bank / Bags",
    MENU_TEXT_BANK_BAGS_TOTAL = "Bank + Bags Total",
    MENU_TEXT_BANK = "Bank Total",
    MENU_TEXT_BAGS = "Bags Total",
    MENU_TEXT_TOTALS = "Total Items",
	MENU_TEXT_FACTION_WATCH = "Watch Items for ",
	MENU_TEXT_ARGENTDAWN = "Watch Items for Argent Dawn",
	MENU_TEXT_TIMBERMAWHOLD = "Watch Items for Timbermaw Hold",
	MENU_TEXT_CENARIONCIRCLE = "Watch Items for Cenarion Cirle",
	MENU_TEXT_WILDHAMMERCLAN = "Watch Items for Wildhammer Clan",
	MENU_TEXT_THORIUMBROTHERHOOD = "Watch Items for The Thorium Brotherhood",
	MENU_TEXT_DARKMOONFAIRE = "Watch Items for Darkmoon Faire",
	MENU_TEXT_NOZDORMU = "Watch Items for Brood of Nozdormu",
	MENU_TEXT_RAVENHOLDT = "Watch Items for Ravenholdt",
	MENU_TEXT_WINTERSPRING = "Watch Items for Winterspring Eko",
	MENU_TEXT_ZANDALAR = "Watch Items for Zandalar Tribe",
    MENU_TEXT_MAIN_FACTIONS = "Watch Items for Morrowgrain and Cities",
	TEXT_HINT = "Soon to come Click to open faction item list.",
	
	RepNames = {"Hated","Hostile","Unfriendly","Neutral","Friendly","Honored","Revered","Exalted","No Reputation" },

	TrackItems = {
	"Coarse Weightstone","Small Furry Paw","Copper Modulator","Embossed Leather Boots",
	"Torn Bear Pelt","Heavy Grinding Stone","Whirring Bronze Gizmo","Toughened Leather Armor",
	"Soft Bushy Tail","Green Iron Bracers","Green Firework","Barbaric Harness",
	"Vibrant Plume","Big Black Mace","Mechanical Repair Kit","Turtle Scale Leggings",
	"Glowing Scorpid Blood","Evil Bat Eye","Dense Grinding Stone","Thorium Widget",
	"Rugged Armor Kit","Darkmoon Faire Prize Ticket","Winterfall Spirit Beads", "Deadwood Headdress Feather",
	"Twilight Text","Cenarion Combat Badge","Cenarion Logistics Badge","Cenarion Tactical Badge",
	"Qiraji Regal Drape","Bone Scarab","Silver Scarab","Stone Scarab","Bronze Scarab","Ivory Scarab",
	"Crystal Scarab","Qiraji Magisterial Ring","Qiraji Ornate Hilt","Jasper Idol","Alibaster Idol",
	"Vermillion Idol","Qiraji Spiked Hilt","Qiraji Ceremonial Ring","Lambent Idol","Amber Idol","Azure Idol",
	"Gold Scarab","Clay Scarab","Qiraji Martial Drape","Obsidian Idol","Onyx Idol",	"Troll Tribal Necklace",
	"Coal","Incendosaur Scales","Kingsblood","Heavy Leather","Iron Bar","Dark Iron Residue","Dark Iron Ore",
	"Core Leather","Blood of the Mountain","Lava Core","Fiery Core","Arcane Quickener","Argent Dawn Valor Token","Corruptor\'s Scourgestone",
"Ectoplasmic Resonator","Invader\'s Scourgestone","Insignia of the Crusade","Insignia of the Dawn",
"Minion\'s Scourgestone","Osseous Agitator","Runecloth","Somatic Intensifier","Bone Fragments",
"Dark Iron Scraps","Savage Frond","Core of Elements","Crypt Fiend Parts","Syndicate Emblem","Heavy Junkboxes","Qiraji Bindings of Dominance","Idol of Strife",
	"Gold Scarab","Bone Scarab","Silver Scarab","Stone Scarab","Idol of Rebirth","Idol of War","Crystal Scarab",
	"Skin of the Great Sandworm","Clay Scarab","Idol of Life","Vek\'lor\'s Diadem","Husk of the Old God","Bronze Scarab",
	"Ivory Scarab","Idol of the Sun","Carapace of the Old God","Idol of the Sage","Idol of Death","Ouro\'s Intact Hide",
	"Vek\'nilash\'s Circlet","Idol of Night","Purple Hakkari Bijou","Green Hakkari Bijou",
	"Red Hakkari Bijou","Yellow Hakkari Bijou","Bronze Hakkari Bijou","Gold Hakkari Bijou","Orange Hakkari Bijou",
	"Blue Hakkari Bijou","Silver Hakkari Bijou","Primal Hakkari Aegis","Primal Hakkari Armsplint",
	"Primal Hakkari Bindings","Primal Hakkari Girdle","Primal Hakkari Idol","Primal Hakkari Kossock",
	"Primal Hakkari Sash","Primal Hakkari Shawl","Primal Hakkari Stanchion","Primal Hakkari Tabard",
	"Zandalar Honor Token","Sandfury Coin","Skullsplitter Coin","Bloodscalp Coin","Gurubashi Coin",
	"Vilebranch Coin","Witherbark Coin","Zulian Coin","Razzashi Coin","Hakkari Coin","Wushoolay\'s Mane",
	"Punctured Voodoo Doll","Gri\'lek\'s Blood","Renataki\'s Tooth","Hazza\'rah\'s Dream Thread",},
	
	TrackFactions = {"Argent Dawn","Cenarion Circle","Darkmoon Faire","Ravenholdt","Thorium Brotherhood",
    "Timbermaw Hold","Wildhammer Clan","Zandalar Tribe","Brood of Nozdormu","Alliance/Horde"},
	
	FactionItems = {
["FaireTier1"] = {"Coarse Weightstone","Copper Modulator","Embossed Leather Boots","Small Furry Paw",},
["FaireTier2"] = {"Heavy Grinding Stone","Torn Bear Pelt","Toughened Leather Armor","Whirring Bronze Gizmo",},
["FaireTier3"] = {"Barbaric Harness","Green Firework","Green Iron Bracers","Soft Bushy Tail",},
["FaireTier4"] = {"Big Black Mace","Mechanical Repair Kit","Turtle Scale Leggings","Vibrant Plume",},
["FaireTier5"] = {"Darkmoon Faire Prize Ticket","Dense Grinding Stone","Evil Bat Eye",
"Glowing Scorpid Blood","Rugged Armor Kit","Thorium Widget",},
["Timbermaw Hold"] = {"Deadwood Headdress Feather","Winterfall Spirit Beads",},
["Cenarion Circle"] = {"Cenarion Combat Badge","Cenarion Logistics Badge","Cenarion Tactical Badge","Twilight Text",
"Qiraji Regal Drape","Bone Scarab","Silver Scarab","Stone Scarab","Bronze Scarab","Ivory Scarab","Crystal Scarab",
"Qiraji Magisterial Ring","Qiraji Ornate Hilt","Jasper Idol","Alibaster Idol","Vermillion Idol","Qiraji Spiked Hilt",
"Qiraji Ceremonial Ring","Lambent Idol","Amber Idol","Azure Idol","Gold Scarab","Clay Scarab","Qiraji Martial Drape",
"Obsidian Idol","Onyx Idol",},
["Wildhammer Clan"] = {"Troll Tribal Necklace"},
["Brotherhood1"] = {"Heavy Leather","Incendosaur Scales","Iron Bar","Kingsblood","Coal",},
["Brotherhood2"] = {"Dark Iron Residue",},
["Brotherhood3"] = {"Blood of the Mountain","Core Leather","Dark Iron Ore","Lava Core","Fiery Core",},
["Argent Dawn"] = {"Arcane Quickener","Argent Dawn Valor Token","Corruptor\'s Scourgestone",
"Ectoplasmic Resonator","Invader\'s Scourgestone","Insignia of the Crusade","Insignia of the Dawn",
"Minion\'s Scourgestone","Osseous Agitator","Runecloth","Somatic Intensifier","Bone Fragments",
"Dark Iron Scraps","Savage Frond","Core of Elements","Crypt Fiend Parts",},
["Brood of Nozdormu"] = {"Qiraji Bindings of Dominance","Idol of Strife","Gold Scarab",
"Bone Scarab","Silver Scarab","Stone Scarab","Idol of Rebirth","Idol of War","Crystal Scarab",
"Skin of the Great Sandworm","Clay Scarab","Idol of Life","Vek\'lor\'s Diadem","Husk of the Old God",
"Bronze Scarab","Ivory Scarab","Idol of the Sun","Carapace of the Old God","Idol of the Sage","Idol of Death",
"Ouro\'s Intact Hide","Vek\'nilash\'s Circlet","Idol of Night",},
["Ravenholdt"] = {"Syndicate Emblem","Heavy Junkboxes",},
["Zandalar Tribe"] = {"Purple Hakkari Bijou","Green Hakkari Bijou","Red Hakkari Bijou","Yellow Hakkari Bijou",
"Bronze Hakkari Bijou","Gold Hakkari Bijou","Orange Hakkari Bijou","Blue Hakkari Bijou","Silver Hakkari Bijou",
"Primal Hakkari Aegis","Primal Hakkari Armsplint","Primal Hakkari Bindings","Primal Hakkari Girdle","Primal Hakkari Idol",
"Primal Hakkari Kossock","Primal Hakkari Sash","Primal Hakkari Shawl","Primal Hakkari Stanchion","Primal Hakkari Tabard",
"Zandalar Honor Token","Sandfury Coin","Skullsplitter Coin","Bloodscalp Coin","Gurubashi Coin","Vilebranch Coin",
"Witherbark Coin","Zulian Coin","Razzashi Coin","Hakkari Coin","Wushoolay\'s Mane","Punctured Voodoo Doll","Gri\'lek\'s Blood",
"Renataki\'s Tooth","Hazza\'rah\'s Dream Thread",},
["Alliance/Horde"] = {"Morrowgrain","Un\'Goro soil","Tarlendris Seeds","Runecloth"},
},

}
