--The List of frames to check against.
local FrameList = {"ActionButton1",
				"ActionButton2",
				"ActionButton3",
				"ActionButton4",
				"ActionButton5",
				"ActionButton6",
				"ActionButton7",
				"ActionButton8",
				"ActionButton9",
				"ActionButton10",
				"ActionButton11",
				"ActionButton12",
				"BonusActionButton1",
				"BonusActionButton2",
				"BonusActionButton3",
				"BonusActionButton4",
				"BonusActionButton5",
				"BonusActionButton6",
				"BonusActionButton7",
				"BonusActionButton8",
				"BonusActionButton9",
				"BonusActionButton10",
				"BonusActionButton11",
				"BonusActionButton12",
				"ShapeshiftButton1",
				"ShapeshiftButton2",
				"ShapeshiftButton3",
				"ShapeshiftButton4",
				"ShapeshiftButton5",
				"ShapeshiftButton6",
				"ShapeshiftButton7",
				"ShapeshiftButton8",
				"ShapeshiftButton9",
				"ShapeshiftButton10",
				"MultiBarBottomLeftButton1",
				"MultiBarBottomLeftButton2",
				"MultiBarBottomLeftButton3",
				"MultiBarBottomLeftButton4",
				"MultiBarBottomLeftButton5",
				"MultiBarBottomLeftButton6",
				"MultiBarBottomLeftButton7",
				"MultiBarBottomLeftButton8",
				"MultiBarBottomLeftButton9",
				"MultiBarBottomLeftButton10",
				"MultiBarBottomLeftButton11",
				"MultiBarBottomLeftButton12",
				"MultiBarBottomRightButton1",
				"MultiBarBottomRightButton2",
				"MultiBarBottomRightButton3",
				"MultiBarBottomRightButton4",
				"MultiBarBottomRightButton5",
				"MultiBarBottomRightButton6",
				"MultiBarBottomRightButton7",
				"MultiBarBottomRightButton8",
				"MultiBarBottomRightButton9",
				"MultiBarBottomRightButton10",
				"MultiBarBottomRightButton11",
				"MultiBarBottomRightButton12",
				"MultiBarRightButton1",
				"MultiBarRightButton2",
				"MultiBarRightButton3",
				"MultiBarRightButton4",
				"MultiBarRightButton5",
				"MultiBarRightButton6",
				"MultiBarRightButton7",
				"MultiBarRightButton8",
				"MultiBarRightButton9",
				"MultiBarRightButton10",
				"MultiBarRightButton11",
				"MultiBarRightButton12",
				"MultiBarLeftButton1",
				"MultiBarLeftButton2",
				"MultiBarLeftButton3",
				"MultiBarLeftButton4",
				"MultiBarLeftButton5",
				"MultiBarLeftButton6",
				"MultiBarLeftButton7",
				"MultiBarLeftButton8",
				"MultiBarLeftButton9",
				"MultiBarLeftButton10",
				"MultiBarLeftButton11",
				"MultiBarLeftButton12",}

--This function insirts into ltc.CountList tables with The string that the cout should be set too, and the actionbuttonid the count should be based on.
function ltc:Default_Buttons_UpdateCountList()
	for _,TButtonName in ipairs(FrameList) do
		local Button = getglobal(TButtonName)
		
		if(Button and Button:IsVisible()) then
			local AId = ActionButton_GetPagedID(Button)
			table.insert(ltc.CountList,{[TButtonName.."Count"] = AId})
		end
	end
end

--Make lern2count aware of this plugin
ltc:RegisterPlugin("Default_Buttons_UpdateCountList")
