
DART_CUSTOM_SETTINGS = {
	[1] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["highlightalpha"] = 0.3,
		["scale"] = 1.25,
		["hidebg"] = true,
		["height"] = 146,
		["attachpoint"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["color"] = {
			["b"] = 0.4588235294117647,
			["g"] = 0.4588235294117647,
			["r"] = 0.4588235294117647,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["width"] = 151,
		["alpha"] = 1,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["name"] = "Texture 1",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = 2,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\Glues\\Credits\\Parchment1",
		["yoffset"] = {
			[1] = -471.5999862670899,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[2] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["highlightalpha"] = 0.3,
		["scale"] = 1.25,
		["hidebg"] = true,
		["height"] = 141,
		["attachpoint"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["color"] = {
			["b"] = 0.4117647058823529,
			["g"] = 0.4117647058823529,
			["r"] = 0.4117647058823529,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["width"] = 282,
		["alpha"] = 1,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["name"] = "Texture 2",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = 245,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\Glues\\Credits\\Parchment3",
		["yoffset"] = {
			[1] = -487.5999862670899,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[3] = {
		["strata"] = "MEDIUM",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["hide"] = true,
		["highlightalpha"] = 0.3,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Rare",
		["height"] = 128,
		["hidebg"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 128,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 3",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = -101.9999892711639,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = -298.4999914169312,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[4] = {
		["strata"] = "MEDIUM",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["hide"] = true,
		["highlightalpha"] = 0.3,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\RareLeft",
		["height"] = 128,
		["hidebg"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 128,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 4",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = 109.5000107288361,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = -299.2499914169312,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[5] = {
		["strata"] = "LOW",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["hide"] = true,
		["highlightalpha"] = 0.3,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\BattlefieldFrame\\UI-Battlefield-Icon",
		["height"] = 64,
		["hidebg"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["parent"] = "UIParent",
		["scale"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 64,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 5",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = 96.75001072883606,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = -293.2499914169312,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[6] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["hide"] = true,
		["highlightalpha"] = 0.3,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\MainMenuBar\\UI-MainMenuBar-EndCap-Dwarf",
		["height"] = 128,
		["hidebg"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["parent"] = "UIParent",
		["scale"] = 0.5,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 128,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 6",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = -899.9999785423279,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = -470.9999828338623,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[7] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["coords"] = {
			[1] = 1,
			[2] = 0,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["hide"] = true,
		["highlightalpha"] = 0.3,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["texture"] = "Interface\\MainMenuBar\\UI-MainMenuBar-EndCap-Dwarf",
		["height"] = 128,
		["hidebg"] = true,
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["parent"] = "UIParent",
		["scale"] = 0.5,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["alpha"] = 1,
		["width"] = 128,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["name"] = "Texture 7",
		["bgalpha"] = 1,
		["xoffset"] = {
			[1] = 900.0000214576721,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = -467.9999828338623,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[8] = {
		["strata"] = "LOW",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["texture"] = "Interface\\QuestFrame\\UI-QuestLog-Empty-TopLeft",
		["parent"] = "UIParent",
		["height"] = 123,
		["hidebg"] = true,
		["coords"] = {
			[1] = 0.01,
			[2] = 0.98,
			[3] = 0.01,
			[4] = 0.38,
		},
		["scale"] = 1,
		["alpha"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 1,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 256,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightalpha"] = 0,
		["name"] = "Texture 8",
		["attachpoint"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 2.25,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hide"] = true,
		["yoffset"] = {
			[1] = -648.7499828338623,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[9] = {
		["strata"] = "HIGH",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 0.9686274509803922,
			["r"] = 0.9372549019607843,
		},
		["bgalpha"] = 1,
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["texture"] = "Interface\\QuestFrame\\UI-QuestLog-Empty-TopLeft",
		["parent"] = "UIParent",
		["height"] = 119,
		["hidebg"] = true,
		["coords"] = {
			[1] = 0.01,
			[2] = 0.98,
			[3] = 0.01,
			[4] = 0.38,
		},
		["scale"] = 1,
		["alpha"] = 1,
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 256,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightalpha"] = 0.3,
		["name"] = "Texture 9",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 269.2500107288361,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = -10,
		["hide"] = true,
		["yoffset"] = {
			[1] = -341.2499914169312,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[10] = {
		["strata"] = "LOW",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["highlightalpha"] = 0,
		["hidebg"] = 1,
		["parent"] = "UIParent",
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Human1.tga",
		["height"] = 512,
		["bgalpha"] = 1,
		["scale"] = 0.75,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 512,
		["alpha"] = 1,
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["name"] = "Texture 10",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["xoffset"] = {
			[1] = -389.7499856948853,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["scripts"] = {
		},
		["yoffset"] = {
			[1] = -502.9999885559082,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[11] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["parent"] = "UIParent",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["highlightalpha"] = 0.3,
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["scale"] = 0.76,
		["hidebg"] = true,
		["height"] = 512,
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["width"] = 512,
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["alpha"] = 1,
		["name"] = "Texture 11",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 459.7510588231971,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Human4.tga",
		["yoffset"] = {
			[1] = -505.2631529414422,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[12] = {
		["strata"] = "HIGH",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 0,
		["parent"] = "UIParent",
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["highlightalpha"] = 0,
		["attachto"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["scale"] = 0.75,
		["hidebg"] = 1,
		["height"] = 64,
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 0,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["bordercolor"] = {
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["highlightcolor"] = {
			["r"] = 0,
			["g"] = 0,
			["b"] = 0,
		},
		["width"] = 527,
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["alpha"] = 1,
		["name"] = "Texture 12",
		["attachpoint"] = {
			[1] = 1,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 420.12,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 0,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Human3.tga",
		["yoffset"] = {
			[1] = -798.5999771118164,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[13] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 0,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["highlightalpha"] = 0.3,
		["scripts"] = {
		},
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["parent"] = "UIParent",
		["hidebg"] = true,
		["height"] = 256,
		["bgalpha"] = 0,
		["scale"] = 0.77,
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["alpha"] = 1,
		["width"] = 256,
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["name"] = "Texture 13",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = -223.6166248845838,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\Human2.tga",
		["yoffset"] = {
			[1] = -403.261299907667,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[14] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 14",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[15] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 15",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[16] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 16",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[17] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 17",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[18] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 18",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[19] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 19",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	[20] = {
		["strata"] = "BACKGROUND",
		["bgcolor"] = {
			["b"] = 0,
			["g"] = 0,
			["r"] = 0,
		},
		["borderalpha"] = 1,
		["scale"] = 1,
		["coords"] = {
			[1] = 0,
			[2] = 1,
			[3] = 0,
			[4] = 1,
		},
		["attachframe"] = {
			[1] = "UIParent",
		},
		["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
		["attachto"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["scripts"] = {
		},
		["hide"] = true,
		["parent"] = "UIParent",
		["height"] = 50,
		["texture"] = "",
		["bgalpha"] = 1,
		["color"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
		["text"] = {
			["yoffset"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = "",
			["justifyV"] = 5,
			["width"] = 100,
			["alpha"] = 1,
			["justifyH"] = 5,
			["fontsize"] = 16,
			["attachto"] = 2,
			["xoffset"] = 0,
			["height"] = 20,
			["attachpoint"] = 2,
			["hide"] = true,
		},
		["highlightcolor"] = {
			["b"] = 0,
			["g"] = 1,
			["r"] = 1,
		},
		["bordercolor"] = {
			["b"] = 1,
			["g"] = 1,
			["r"] = 1,
		},
		["Backdrop"] = {
			["top"] = 5,
			["edgeSize"] = 16,
			["tileSize"] = 16,
			["tile"] = true,
			["right"] = 5,
			["left"] = 5,
			["bottom"] = 5,
		},
		["width"] = 50,
		["alpha"] = 1,
		["highlightalpha"] = 0.3,
		["name"] = "Texture 20",
		["attachpoint"] = {
			[1] = 5,
			[2] = 5,
			[3] = 5,
			[4] = 5,
		},
		["xoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
		["padding"] = 5,
		["hidebg"] = true,
		["yoffset"] = {
			[1] = 0,
			[2] = 0,
			[3] = 0,
			[4] = 0,
		},
	},
	["updatespeed"] = 30,
	["INITIALIZED1.0d"] = true,
	["optionsscale"] = 0.6,
}
