BINDING_HEADER_GARQUICKLOOK = "Quick Look by Garoun";
BINDING_NAME_GQUICKLOOKB = "Quick Look - Back";
BINDING_NAME_GQUICKLOOKR = "Quick Look - Right";
BINDING_NAME_GQUICKLOOKL = "Quick Look - Left";
BINDING_NAME_GQUICKLOOKRESET = "Quick Look - Reset";

GAR_LOOK_DEG = 0;
