-- French Translation
-- If you want to translate this to another language, make sure the names of buffs and abilities are *EXACTLY* the same as in-game. Spelling, punctuation, upper/lowercase letters, etc. MUST BE EXACT. Also, any 'foreign' characters must be converted to UNICODE.
-- Unicode resource:  http://www.allegro-c.de/unicode/zcodes.htm


-- To lower the upkeep we will not be adding Localization for english words that do not break compatibility in other game clients.
-- This Localization is only added for compatibility so that it may work in non english game clients and not as a translation.

if GetLocale() == "frFR" then
-- All file Localization
	LOCALIZATION_ZORLEN_Rank = "Rang";
	--LOCALIZATION_ZORLEN_sit = "";
	--LOCALIZATION_ZORLEN_You_dodge = "";
	--LOCALIZATION_ZORLEN_Your = "";
	--LOCALIZATION_ZORLEN_immune = "";
	--LOCALIZATION_ZORLEN_no_weapons_equipped = "";
	--LOCALIZATION_ZORLEN_dodged = "";
	--LOCALIZATION_ZORLEN_dodges = "";
	--LOCALIZATION_ZORLEN_pet_is_not_dead = "";
	--LOCALIZATION_ZORLEN_pet_is_dead = "";
	
	--LOCALIZATION_ZORLEN_PlusHealMinScan = "";
	--LOCALIZATION_ZORLEN_PlusHealMaxScan = "";
	--LOCALIZATION_ZORLEN_VariableHealScanEquip = "";
	--LOCALIZATION_ZORLEN_VariableHealScanSet = "";

-- Example: /script Zorlen_GiveName_OffHandType()
-- The example above will give the name required for LOCALIZATION_ZORLEN_Shields
-- You must have a shield equipped to get the correct name.
-- You can also get the correct name from the auction house filters under the Armor section.
	--LOCALIZATION_ZORLEN_Shields = "";
	
-- Example: /script Zorlen_GiveName_MainHandType()
-- The example above will give the name required for the weapons below.
-- You must have the weapon equipped to get the correct name.
-- You can also get the correct names from the auction house filters under the Weapon section.
	--LOCALIZATION_ZORLEN_Daggers = "";
	--LOCALIZATION_ZORLEN_OneHandedSwords = "";
	--LOCALIZATION_ZORLEN_TwoHandedSwords = "";
	--LOCALIZATION_ZORLEN_OneHandedAxes = "";
	--LOCALIZATION_ZORLEN_TwoHandedAxes = "";
	--LOCALIZATION_ZORLEN_OneHandedMaces = "";
	--LOCALIZATION_ZORLEN_TwoHandedMaces = "";
	--LOCALIZATION_ZORLEN_Polearms = "";
	--LOCALIZATION_ZORLEN_Staves = "";
	--LOCALIZATION_ZORLEN_FistWeapons = "";
	--LOCALIZATION_ZORLEN_FishingPole = "";



-- Zorlen_Other.lua file Localization
	--LOCALIZATION_ZORLEN_Attack = "";
	--LOCALIZATION_ZORLEN_Throw = "";
	--LOCALIZATION_ZORLEN_ShootBow = "";
	--LOCALIZATION_ZORLEN_ShootCrossbow = "";
	--LOCALIZATION_ZORLEN_ShootGun = "";
	--LOCALIZATION_ZORLEN_Shoot = "";
-- Human Racial
	--LOCALIZATION_ZORLEN_Perception = "";
-- Dwarf Racial
	--LOCALIZATION_ZORLEN_FindTreasure = "";
	--LOCALIZATION_ZORLEN_Stoneform = "";
-- Gnome Racial
	--LOCALIZATION_ZORLEN_EscapeArtist = "";
-- Night Elf Racial
	--LOCALIZATION_ZORLEN_Shadowmeld = "";
-- Orc Racial
	--LOCALIZATION_ZORLEN_BloodFury = "";
-- Undead Racial
	--LOCALIZATION_ZORLEN_Cannibalize = "";
	--LOCALIZATION_ZORLEN_WillOfTheForsaken = "";
-- Tauren Racial
	--LOCALIZATION_ZORLEN_WarStomp = "";
-- Troll Racial
	--LOCALIZATION_ZORLEN_Berserking = "";



-- Zorlen_Pets.lua file Localization
-- Hunter Pets
	--LOCALIZATION_ZORLEN_Dash = "";
	--LOCALIZATION_ZORLEN_Dive = "";
	--LOCALIZATION_ZORLEN_Bite = "";
	--LOCALIZATION_ZORLEN_Claw = "";
	--LOCALIZATION_ZORLEN_Cower = "";
	--LOCALIZATION_ZORLEN_Growl = "";
	--LOCALIZATION_ZORLEN_Prowl = "";
	--LOCALIZATION_ZORLEN_Charge = "";
	--LOCALIZATION_ZORLEN_Screech = "";
	--LOCALIZATION_ZORLEN_FuriousHowl = "";
	--LOCALIZATION_ZORLEN_LightningBreath = "";
	--LOCALIZATION_ZORLEN_ShellShield = "";
	--LOCALIZATION_ZORLEN_Thunderstomp = "";
	--LOCALIZATION_ZORLEN_ScorpidPoison = "";
-- Warlock Pets
	--LOCALIZATION_ZORLEN_BloodPact = "";
	--LOCALIZATION_ZORLEN_FireShield = "";
	--LOCALIZATION_ZORLEN_Firebolt = "";
	--LOCALIZATION_ZORLEN_PhaseShift = "";
	--LOCALIZATION_ZORLEN_ConsumeShadows = "";
	--LOCALIZATION_ZORLEN_Sacrifice = "";
	--LOCALIZATION_ZORLEN_Suffering = "";
	--LOCALIZATION_ZORLEN_Torment = "";
	--LOCALIZATION_ZORLEN_DevourMagic = "";
	--LOCALIZATION_ZORLEN_Paranoia = "";
	--LOCALIZATION_ZORLEN_SpellLock = "";
	--LOCALIZATION_ZORLEN_TaintedBlood = "";
	--LOCALIZATION_ZORLEN_LashOfPain = "";
	--LOCALIZATION_ZORLEN_Seduction = "";
	--LOCALIZATION_ZORLEN_SoothingKiss = "";
	--LOCALIZATION_ZORLEN_LesserInvisibility = "";



-- Zorlen_Hunter.lua file Localization
	--LOCALIZATION_ZORLEN_ImprovedAspectOfTheHawk = "";
	--LOCALIZATION_ZORLEN_ImprovedMendPet = "";
	--LOCALIZATION_ZORLEN_MendPet = "";
	LOCALIZATION_ZORLEN_CallPet = "Appel du familier";
	LOCALIZATION_ZORLEN_RevivePet = "Ressusciter le familier";
	LOCALIZATION_ZORLEN_DismissPet = "Renvoyer le familier";
	--LOCALIZATION_ZORLEN_AutoShot = "";
	--LOCALIZATION_ZORLEN_MongooseBite = "";
	--LOCALIZATION_ZORLEN_ArcaneShot = "";
	--LOCALIZATION_ZORLEN_ConcussiveShot = "";
	--LOCALIZATION_ZORLEN_RaptorStrike = "";
	--LOCALIZATION_ZORLEN_SerpentSting = "";
	--LOCALIZATION_ZORLEN_ViperSting = "";
	--LOCALIZATION_ZORLEN_ScorpidSting = "";
	--LOCALIZATION_ZORLEN_DistractingShot = "";
	--LOCALIZATION_ZORLEN_AimedShot = "";
	--LOCALIZATION_ZORLEN_HuntersMark = "";
	LOCALIZATION_ZORLEN_AspectOfTheHawk = "Aspect du Faucon";
	LOCALIZATION_ZORLEN_AspectOfTheMonkey = "Aspect du Singe";
	LOCALIZATION_ZORLEN_AspectOfTheCheetah = "Aspect du Gu\195\169pard";
	LOCALIZATION_ZORLEN_AspectOfThePack = "Aspect de la Meute";
	LOCALIZATION_ZORLEN_AspectOfTheWild = "Aspect de la Nature";
	LOCALIZATION_ZORLEN_AspectOfTheBeast = "Aspect de la B\195\170te";
	--LOCALIZATION_ZORLEN_WingClip = "";
	--LOCALIZATION_ZORLEN_FreezingTrap = "";
	--LOCALIZATION_ZORLEN_FrostTrap = "";
	--LOCALIZATION_ZORLEN_ExplosiveTrap = "";
	--LOCALIZATION_ZORLEN_ImmolationTrap = "";
	--LOCALIZATION_ZORLEN_FeignDeath = "";
	--LOCALIZATION_ZORLEN_Counterattack = "";
	--LOCALIZATION_ZORLEN_TranquilizingShot = "";
	--LOCALIZATION_ZORLEN_Disengage = "";
	--LOCALIZATION_ZORLEN_EyesOfTheBeast = "";
	--LOCALIZATION_ZORLEN_BeastLore = "";
	--LOCALIZATION_ZORLEN_TrackBeasts = "";
	--LOCALIZATION_ZORLEN_TrackDemons = "";
	--LOCALIZATION_ZORLEN_TrackDragonkin = "";
	--LOCALIZATION_ZORLEN_TrackElementals = "";
	--LOCALIZATION_ZORLEN_TrackGiants = "";
	--LOCALIZATION_ZORLEN_TrackHumanoids = "";
	--LOCALIZATION_ZORLEN_TrackUndead = "";
	--LOCALIZATION_ZORLEN_TrackHidden = "";
	--LOCALIZATION_ZORLEN_BestialWrath = "";
	--LOCALIZATION_ZORLEN_TrueshotAura = "";
	--LOCALIZATION_ZORLEN_ScatterShot = "";
	--LOCALIZATION_ZORLEN_WyvernSting = "";
	--LOCALIZATION_ZORLEN_Deterrence = "";
	--LOCALIZATION_ZORLEN_EagleEye = "";
	--LOCALIZATION_ZORLEN_RapidFire = "";
	--LOCALIZATION_ZORLEN_MultiShot = "";
	--LOCALIZATION_ZORLEN_Flare = "";
	--LOCALIZATION_ZORLEN_ScareBeast = "";
	--LOCALIZATION_ZORLEN_Volley = "";
	--LOCALIZATION_ZORLEN_Intimidation = "";



-- Zorlen_Warlock.lua file Localization
	--LOCALIZATION_ZORLEN_SoulShard = "";
	--LOCALIZATION_ZORLEN_AmplifyCurse = "";
	--LOCALIZATION_ZORLEN_CurseOfAgony = "";
	--LOCALIZATION_ZORLEN_CurseOfDoom = "";
	--LOCALIZATION_ZORLEN_CurseOfShadow = "";
	--LOCALIZATION_ZORLEN_CurseOfTheElements = "";
	--LOCALIZATION_ZORLEN_CurseOfWeakness = "";
	--LOCALIZATION_ZORLEN_CurseOfExhaustion = "";
	--LOCALIZATION_ZORLEN_CurseOfRecklessness = "";
	--LOCALIZATION_ZORLEN_CurseOfTongues = "";
	--LOCALIZATION_ZORLEN_Corruption = "";
	--LOCALIZATION_ZORLEN_ImprovedCorruption = "";
	--LOCALIZATION_ZORLEN_Immolate = "";
	--LOCALIZATION_ZORLEN_SiphonLife = "";
	--LOCALIZATION_ZORLEN_DrainLife = "";
	--LOCALIZATION_ZORLEN_DrainMana = "";
	--LOCALIZATION_ZORLEN_Hellfire = "";
	--LOCALIZATION_ZORLEN_RainOfFire = "";
	--LOCALIZATION_ZORLEN_DrainSoul = "";
	LOCALIZATION_ZORLEN_LifeTap = "Connexion";
	--LOCALIZATION_ZORLEN_ImprovedLifeTap = "";
	LOCALIZATION_ZORLEN_DarkPact = "Pacte noir";
	--LOCALIZATION_ZORLEN_Nightfall = "";
	--LOCALIZATION_ZORLEN_ShadowBolt = "";
	--LOCALIZATION_ZORLEN_Banish = "";
	--LOCALIZATION_ZORLEN_Conflagrate = "";
	--LOCALIZATION_ZORLEN_CreateFirestoneLesser = "";
	--LOCALIZATION_ZORLEN_CreateFirestone = "";
	--LOCALIZATION_ZORLEN_CreateFirestoneGreater = "";
	--LOCALIZATION_ZORLEN_CreateFirestoneMajor = "";
	--LOCALIZATION_ZORLEN_CreateHealthstoneMinor = "";
	--LOCALIZATION_ZORLEN_CreateHealthstoneLesser = "";
	--LOCALIZATION_ZORLEN_CreateHealthstone = "";
	--LOCALIZATION_ZORLEN_CreateHealthstoneGreater = "";
	--LOCALIZATION_ZORLEN_CreateHealthstoneMajor = "";
	--LOCALIZATION_ZORLEN_CreateSoulstoneMinor = "";
	--LOCALIZATION_ZORLEN_CreateSoulstoneLesser = "";
	--LOCALIZATION_ZORLEN_CreateSoulstone = "";
	--LOCALIZATION_ZORLEN_CreateSoulstoneGreater = "";
	--LOCALIZATION_ZORLEN_CreateSoulstoneMajor = "";
	--LOCALIZATION_ZORLEN_CreateSpellstone = "";
	--LOCALIZATION_ZORLEN_CreateSpellstoneGreater = "";
	--LOCALIZATION_ZORLEN_CreateSpellstoneMajor = "";
	--LOCALIZATION_ZORLEN_DeathCoil = "";
	--LOCALIZATION_ZORLEN_DemonArmor = "";
	--LOCALIZATION_ZORLEN_DemonSkin = "";
	--LOCALIZATION_ZORLEN_DemonicSacrifice = "";
	--LOCALIZATION_ZORLEN_DetectLesserInvisibility = "";
	--LOCALIZATION_ZORLEN_DetectInvisibility = "";
	--LOCALIZATION_ZORLEN_DetectGreaterInvisibility = "";
	--LOCALIZATION_ZORLEN_EnslaveDemon = "";
	--LOCALIZATION_ZORLEN_EyeOfKilrogg = "";
	--LOCALIZATION_ZORLEN_Fear = "";
	--LOCALIZATION_ZORLEN_FelDomination = "";
	--LOCALIZATION_ZORLEN_HealthFunnel = "";
	--LOCALIZATION_ZORLEN_HowlOfTerror = "";
	--LOCALIZATION_ZORLEN_Inferno = "";
	--LOCALIZATION_ZORLEN_RitualOfDoom = "";
	--LOCALIZATION_ZORLEN_RitualOfSummoning = "";
	--LOCALIZATION_ZORLEN_SearingPain = "";
	--LOCALIZATION_ZORLEN_SenseDemons = "";
	--LOCALIZATION_ZORLEN_ShadowWard = "";
	--LOCALIZATION_ZORLEN_Shadowburn = "";
	--LOCALIZATION_ZORLEN_SoulFire = "";
	--LOCALIZATION_ZORLEN_SoulLink = "";
	--LOCALIZATION_ZORLEN_SummonDreadsteed = "";
	--LOCALIZATION_ZORLEN_SummonFelhunter = "";
	--LOCALIZATION_ZORLEN_SummonFelsteed = "";
	--LOCALIZATION_ZORLEN_SummonImp = "";
	--LOCALIZATION_ZORLEN_SummonSuccubus = "";
	--LOCALIZATION_ZORLEN_SummonVoidwalker = "";
	--LOCALIZATION_ZORLEN_UnendingBreath = "";
	--LOCALIZATION_ZORLEN_FelConcentration = "";



-- Zorlen_Druid.lua file Localization
	LOCALIZATION_ZORLEN_TravelForm = "Forme de voyage";
	LOCALIZATION_ZORLEN_MoonkinForm = "Forme de s\195\169l\195\169nien";
	LOCALIZATION_ZORLEN_BearForm = "Forme d'ours";
	LOCALIZATION_ZORLEN_DireBearForm = "Forme d'ours redoutable";
	LOCALIZATION_ZORLEN_CatForm = "Forme de f\195\169lin";
	LOCALIZATION_ZORLEN_AquaticForm = "Forme aquatique";
	--LOCALIZATION_ZORLEN_ChallengingRoar = "";
	--LOCALIZATION_ZORLEN_DemoralizingRoar = "";
	--LOCALIZATION_ZORLEN_AbolishPoison = "";
	--LOCALIZATION_ZORLEN_Barkskin = "";
	--LOCALIZATION_ZORLEN_Bash = "";
	--LOCALIZATION_ZORLEN_Claw = "";
	--LOCALIZATION_ZORLEN_Cower = "";
	--LOCALIZATION_ZORLEN_Dash = "";
	--LOCALIZATION_ZORLEN_Enrage = "";
	--LOCALIZATION_ZORLEN_EntanglingRoots = "";
	--LOCALIZATION_ZORLEN_FaerieFire = "";
	--LOCALIZATION_ZORLEN_FaerieFireFeral = "";
	--LOCALIZATION_ZORLEN_FeralCharge = "";
	--LOCALIZATION_ZORLEN_FerociousBite = "";
	--LOCALIZATION_ZORLEN_FrenziedRegeneration = "";
	--LOCALIZATION_ZORLEN_GiftOfTheWild = "";
	--LOCALIZATION_ZORLEN_HealingTouch = "";
	--LOCALIZATION_ZORLEN_Hibernate = "";
	--LOCALIZATION_ZORLEN_Hurricane = "";
	--LOCALIZATION_ZORLEN_Innervate = "";
	--LOCALIZATION_ZORLEN_InsectSwarm = "";
	--LOCALIZATION_ZORLEN_LeaderOfThePack = "";
	--LOCALIZATION_ZORLEN_MarkOfTheWild = "";
	--LOCALIZATION_ZORLEN_Maul = "";
	--LOCALIZATION_ZORLEN_Moonfire = "";
	--LOCALIZATION_ZORLEN_NaturesGrasp = "";
	--LOCALIZATION_ZORLEN_NaturesSwiftness = "";
	--LOCALIZATION_ZORLEN_OmenOfClarity = "";
	--LOCALIZATION_ZORLEN_Pounce = "";
	--LOCALIZATION_ZORLEN_Prowl = "";
	--LOCALIZATION_ZORLEN_Rake = "";
	--LOCALIZATION_ZORLEN_Ravage = "";
	--LOCALIZATION_ZORLEN_Rebirth = "";
	--LOCALIZATION_ZORLEN_Regrowth = "";
	--LOCALIZATION_ZORLEN_Rejuvenation = "";
	--LOCALIZATION_ZORLEN_RemoveCurse = "";
	--LOCALIZATION_ZORLEN_Rip = "";
	--LOCALIZATION_ZORLEN_Shred = "";
	--LOCALIZATION_ZORLEN_SootheAnimal = "";
	--LOCALIZATION_ZORLEN_Starfire = "";
	--LOCALIZATION_ZORLEN_Swipe = "";
	--LOCALIZATION_ZORLEN_Thorns = "";
	--LOCALIZATION_ZORLEN_TigersFury = "";
	--LOCALIZATION_ZORLEN_TrackHumanoids = "";
	--LOCALIZATION_ZORLEN_Tranquility = "";
	--LOCALIZATION_ZORLEN_Wrath = "";
	--LOCALIZATION_ZORLEN_ImprovedWrath = "";
	--LOCALIZATION_ZORLEN_ImprovedNaturesGrasp = "";
	--LOCALIZATION_ZORLEN_ImprovedEntanglingRoots = "";
	--LOCALIZATION_ZORLEN_ImprovedMoonfire = "";
	--LOCALIZATION_ZORLEN_NaturalWeapons = "";
	--LOCALIZATION_ZORLEN_NaturalShapeshifter = "";
	--LOCALIZATION_ZORLEN_ImprovedThorns = "";
	--LOCALIZATION_ZORLEN_NaturesReach = "";
	--LOCALIZATION_ZORLEN_Vengeance = "";
	--LOCALIZATION_ZORLEN_ImprovedStarfire = "";
	--LOCALIZATION_ZORLEN_NaturesGrace = "";
	--LOCALIZATION_ZORLEN_Moonglow = "";
	--LOCALIZATION_ZORLEN_Moonfury = "";
	--LOCALIZATION_ZORLEN_Ferocity = "";
	--LOCALIZATION_ZORLEN_FeralAggression = "";
	--LOCALIZATION_ZORLEN_FeralInstinct = "";
	--LOCALIZATION_ZORLEN_BrutalImpact = "";
	--LOCALIZATION_ZORLEN_ThickHide = "";
	--LOCALIZATION_ZORLEN_FelineSwiftness = "";
	--LOCALIZATION_ZORLEN_SharpenedClaws = "";
	--LOCALIZATION_ZORLEN_ImprovedShred = "";
	--LOCALIZATION_ZORLEN_PredatoryStrikes = "";
	--LOCALIZATION_ZORLEN_BloodFrenzy = "";
	--LOCALIZATION_ZORLEN_PrimalFury = "";
	--LOCALIZATION_ZORLEN_SavageFury = "";
	--LOCALIZATION_ZORLEN_HeartOfTheWild = "";
	--LOCALIZATION_ZORLEN_ImprovedMarkOfTheWild = "";
	--LOCALIZATION_ZORLEN_Furor = "";
	--LOCALIZATION_ZORLEN_ImprovedHealingTouch = "";
	--LOCALIZATION_ZORLEN_NaturesFocus = "";
	--LOCALIZATION_ZORLEN_ImprovedEnrage = "";
	--LOCALIZATION_ZORLEN_Reflection = "";
	--LOCALIZATION_ZORLEN_Subtlety = "";
	--LOCALIZATION_ZORLEN_TranquilSpirit = "";
	--LOCALIZATION_ZORLEN_ImprovedRejuvenation = "";
	--LOCALIZATION_ZORLEN_GiftOfNature = "";
	--LOCALIZATION_ZORLEN_ImprovedTranquility = "";
	--LOCALIZATION_ZORLEN_ImprovedRegrowth = "";



-- Zorlen_Mage.lua file Localization
	--LOCALIZATION_ZORLEN_AmplifyMagic = "";
	--LOCALIZATION_ZORLEN_ArcaneBrilliance = "";
	--LOCALIZATION_ZORLEN_ArcaneExplosion = "";
	--LOCALIZATION_ZORLEN_ArcaneIntellect = "";
	--LOCALIZATION_ZORLEN_ArcaneMissiles = "";
	--LOCALIZATION_ZORLEN_ArcanePower = "";
	--LOCALIZATION_ZORLEN_BlastWave = "";
	--LOCALIZATION_ZORLEN_Blink = "";
	--LOCALIZATION_ZORLEN_Blizzard = "";
	--LOCALIZATION_ZORLEN_ColdSnap = "";
	--LOCALIZATION_ZORLEN_Combustion = "";
	--LOCALIZATION_ZORLEN_ConeOfCold = "";
	--LOCALIZATION_ZORLEN_ConjureFood = "";
	--LOCALIZATION_ZORLEN_ConjureManaAgate = "";
	--LOCALIZATION_ZORLEN_ConjureManaJade = "";
	--LOCALIZATION_ZORLEN_ConjureManaCitrine = "";
	--LOCALIZATION_ZORLEN_ConjureManaRuby = "";
	--LOCALIZATION_ZORLEN_ConjureWater = "";
	--LOCALIZATION_ZORLEN_Counterspell = "";
	--LOCALIZATION_ZORLEN_DampenMagic = "";
	--LOCALIZATION_ZORLEN_DetectMagic = "";
	--LOCALIZATION_ZORLEN_Evocation = "";
	--LOCALIZATION_ZORLEN_FireBlast = "";
	--LOCALIZATION_ZORLEN_FireWard = "";
	--LOCALIZATION_ZORLEN_Fireball = "";
	--LOCALIZATION_ZORLEN_Flamestrike = "";
	--LOCALIZATION_ZORLEN_FrostArmor = "";
	--LOCALIZATION_ZORLEN_FrostNova = "";
	--LOCALIZATION_ZORLEN_FrostWard = "";
	--LOCALIZATION_ZORLEN_Frostbolt = "";
	--LOCALIZATION_ZORLEN_IceArmor = "";
	--LOCALIZATION_ZORLEN_IceBarrier = "";
	--LOCALIZATION_ZORLEN_IceBlock = "";
	--LOCALIZATION_ZORLEN_MageArmor = "";
	--LOCALIZATION_ZORLEN_ManaShield = "";
	--LOCALIZATION_ZORLEN_Polymorph = "";
	--LOCALIZATION_ZORLEN_PortalDarnassus = "";
	--LOCALIZATION_ZORLEN_PortalIronforge = "";
	--LOCALIZATION_ZORLEN_PortalOrgrimmar = "";
	--LOCALIZATION_ZORLEN_PortalStormwind = "";
	--LOCALIZATION_ZORLEN_PortalThunderBluff = "";
	--LOCALIZATION_ZORLEN_PortalUndercity = "";
	--LOCALIZATION_ZORLEN_TeleportDarnassus = "";
	--LOCALIZATION_ZORLEN_TeleportIronforge = "";
	--LOCALIZATION_ZORLEN_TeleportOrgrimmar = "";
	--LOCALIZATION_ZORLEN_TeleportStormwind = "";
	--LOCALIZATION_ZORLEN_TeleportThunderBluff = "";
	--LOCALIZATION_ZORLEN_TeleportUndercity = "";
	--LOCALIZATION_ZORLEN_PresenceOfMind = "";
	--LOCALIZATION_ZORLEN_Pyroblast = "";
	--LOCALIZATION_ZORLEN_RemoveLesserCurse = "";
	--LOCALIZATION_ZORLEN_Scorch = "";
	--LOCALIZATION_ZORLEN_SlowFall = "";



-- Zorlen_Paladin.lua file Localization
	--LOCALIZATION_ZORLEN_BlessingOfFreedom = "";
	--LOCALIZATION_ZORLEN_BlessingOfKings = "";
	--LOCALIZATION_ZORLEN_BlessingOfLight = "";
	--LOCALIZATION_ZORLEN_BlessingOfMight = "";
	--LOCALIZATION_ZORLEN_BlessingOfProtection = "";
	--LOCALIZATION_ZORLEN_BlessingOfSacrifice = "";
	--LOCALIZATION_ZORLEN_BlessingOfSalvation = "";
	--LOCALIZATION_ZORLEN_BlessingOfSanctuary = "";
	--LOCALIZATION_ZORLEN_BlessingOfWisdom = "";
	--LOCALIZATION_ZORLEN_Cleanse = "";
	--LOCALIZATION_ZORLEN_ConcentrationAura = "";
	--LOCALIZATION_ZORLEN_Consecration = "";
	--LOCALIZATION_ZORLEN_DevotionAura = "";
	--LOCALIZATION_ZORLEN_DivineFavor = "";
	--LOCALIZATION_ZORLEN_DivineIntervention = "";
	--LOCALIZATION_ZORLEN_DivineProtection = "";
	--LOCALIZATION_ZORLEN_DivineShield = "";
	--LOCALIZATION_ZORLEN_Exorcism = "";
	--LOCALIZATION_ZORLEN_FireResistanceAura = "";
	--LOCALIZATION_ZORLEN_FlashOfLight = "";
	--LOCALIZATION_ZORLEN_FrostResistanceAura = "";
	--LOCALIZATION_ZORLEN_GreaterBlessingOfKings = "";
	--LOCALIZATION_ZORLEN_GreaterBlessingOfLight = "";
	--LOCALIZATION_ZORLEN_GreaterBlessingOfMight = "";
	--LOCALIZATION_ZORLEN_GreaterBlessingOfSalvation = "";
	--LOCALIZATION_ZORLEN_GreaterBlessingOfSanctuary = "";
	--LOCALIZATION_ZORLEN_GreaterBlessingOfWisdom = "";
	--LOCALIZATION_ZORLEN_HammerOfJustice = "";
	--LOCALIZATION_ZORLEN_HammerOfWrath = "";
	--LOCALIZATION_ZORLEN_HolyLight = "";
	--LOCALIZATION_ZORLEN_HolyShield = "";
	--LOCALIZATION_ZORLEN_HolyShock = "";
	--LOCALIZATION_ZORLEN_HolyWrath = "";
	--LOCALIZATION_ZORLEN_Judgement = "";
	--LOCALIZATION_ZORLEN_LayOnHands = "";
	--LOCALIZATION_ZORLEN_Purify = "";
	--LOCALIZATION_ZORLEN_Redemption = "";
	--LOCALIZATION_ZORLEN_Repentance = "";
	--LOCALIZATION_ZORLEN_RetributionAura = "";
	--LOCALIZATION_ZORLEN_RighteousFury = "";
	--LOCALIZATION_ZORLEN_SanctityAura = "";
	--LOCALIZATION_ZORLEN_SealOfCommand = "";
	--LOCALIZATION_ZORLEN_SealOfJustice = "";
	--LOCALIZATION_ZORLEN_SealOfLight = "";
	--LOCALIZATION_ZORLEN_SealOfRighteousness = "";
	--LOCALIZATION_ZORLEN_SealOfWisdom = "";
	--LOCALIZATION_ZORLEN_SealOfTheCrusader = "";
	--LOCALIZATION_ZORLEN_SenseUndead = "";
	--LOCALIZATION_ZORLEN_ShadowResistanceAura = "";
	--LOCALIZATION_ZORLEN_SummonCharger = "";
	--LOCALIZATION_ZORLEN_SummonWarhorse = "";
	--LOCALIZATION_ZORLEN_TurnUndead = "";



-- Zorlen_Priest.lua file Localization
	--LOCALIZATION_ZORLEN_AbolishDisease = "";
	--LOCALIZATION_ZORLEN_CureDisease = "";
	--LOCALIZATION_ZORLEN_DesperatePrayer = "";
	--LOCALIZATION_ZORLEN_DevouringPlague = "";
	--LOCALIZATION_ZORLEN_DispelMagic = "";
	--LOCALIZATION_ZORLEN_DivineSpirit = "";
	--LOCALIZATION_ZORLEN_ElunesGrace = "";
	--LOCALIZATION_ZORLEN_Fade = "";
	--LOCALIZATION_ZORLEN_FearWard = "";
	--LOCALIZATION_ZORLEN_Feedback = "";
	--LOCALIZATION_ZORLEN_FlashHeal = "";
	--LOCALIZATION_ZORLEN_FocusedCasting = "";
	--LOCALIZATION_ZORLEN_LesserHeal = "";
	--LOCALIZATION_ZORLEN_Heal = "";
	--LOCALIZATION_ZORLEN_GreaterHeal = "";
	--LOCALIZATION_ZORLEN_HexOfWeakness = "";
	--LOCALIZATION_ZORLEN_HolyFire = "";
	--LOCALIZATION_ZORLEN_HolyNova = "";
	--LOCALIZATION_ZORLEN_InnerFire = "";
	--LOCALIZATION_ZORLEN_InnerFocus = "";
	--LOCALIZATION_ZORLEN_Levitate = "";
	--LOCALIZATION_ZORLEN_ManaBurn = "";
	--LOCALIZATION_ZORLEN_MindBlast = "";
	--LOCALIZATION_ZORLEN_MindControl = "";
	--LOCALIZATION_ZORLEN_MindFlay = "";
	--LOCALIZATION_ZORLEN_MindSoothe = "";
	--LOCALIZATION_ZORLEN_MindVision = "";
	--LOCALIZATION_ZORLEN_PowerWordFortitude = "";
	--LOCALIZATION_ZORLEN_PowerWordShield = "";
	--LOCALIZATION_ZORLEN_PrayerOfFortitude = "";
	--LOCALIZATION_ZORLEN_PrayerOfHealing = "";
	--LOCALIZATION_ZORLEN_PsychicScream = "";
	--LOCALIZATION_ZORLEN_Renew = "";
	--LOCALIZATION_ZORLEN_Resurrection = "";
	--LOCALIZATION_ZORLEN_ShackleUndead = "";
	--LOCALIZATION_ZORLEN_ShadowProtection = "";
	--LOCALIZATION_ZORLEN_ShadowWordPain = "";
	--LOCALIZATION_ZORLEN_Shadowform = "";
	--LOCALIZATION_ZORLEN_Shadowguard = "";
	--LOCALIZATION_ZORLEN_Silence = "";
	--LOCALIZATION_ZORLEN_Smite = "";
	--LOCALIZATION_ZORLEN_SpiritOfRedemption = "";
	--LOCALIZATION_ZORLEN_Starshards = "";
	--LOCALIZATION_ZORLEN_TouchOfWeakness = "";
	--LOCALIZATION_ZORLEN_VampiricEmbrace = "";



-- Zorlen_Rogue.lua file Localization
	--LOCALIZATION_ZORLEN_ImprovedCheapShot = "";
	--LOCALIZATION_ZORLEN_ImprovedSinisterStrike = "";
	--LOCALIZATION_ZORLEN_CripplingPoison = "";
	--LOCALIZATION_ZORLEN_CripplingPoisonII = "";
	--LOCALIZATION_ZORLEN_DeadlyPoison = "";
	--LOCALIZATION_ZORLEN_DeadlyPoisonII = "";
	--LOCALIZATION_ZORLEN_DeadlyPoisonIII = "";
	--LOCALIZATION_ZORLEN_DeadlyPoisonIV = "";
	--LOCALIZATION_ZORLEN_DeadlyPoisonV = "";
	--LOCALIZATION_ZORLEN_InstantPoison = "";
	--LOCALIZATION_ZORLEN_InstantPoisonII = "";
	--LOCALIZATION_ZORLEN_InstantPoisonIII = "";
	--LOCALIZATION_ZORLEN_InstantPoisonIV = "";
	--LOCALIZATION_ZORLEN_InstantPoisonV = "";
	--LOCALIZATION_ZORLEN_InstantPoisonVI = "";
	--LOCALIZATION_ZORLEN_MindnumbingPoison = "";
	--LOCALIZATION_ZORLEN_MindnumbingPoisonII = "";
	--LOCALIZATION_ZORLEN_MindnumbingPoisonIII = "";
	--LOCALIZATION_ZORLEN_WoundPoison = "";
	--LOCALIZATION_ZORLEN_WoundPoisonII = "";
	--LOCALIZATION_ZORLEN_WoundPoisonIII = "";
	--LOCALIZATION_ZORLEN_WoundPoisonIV = "";
	--LOCALIZATION_ZORLEN_AdrenalineRush = "";
	--LOCALIZATION_ZORLEN_Ambush = "";
	--LOCALIZATION_ZORLEN_Backstab = "";
	--LOCALIZATION_ZORLEN_BladeFlurry = "";
	--LOCALIZATION_ZORLEN_Blind = "";
	--LOCALIZATION_ZORLEN_BlindingPowder = "";
	--LOCALIZATION_ZORLEN_CheapShot = "";
	--LOCALIZATION_ZORLEN_ColdBlood = "";
	--LOCALIZATION_ZORLEN_DetectTraps = "";
	--LOCALIZATION_ZORLEN_DisarmTrap = "";
	--LOCALIZATION_ZORLEN_Distract = "";
	--LOCALIZATION_ZORLEN_Evasion = "";
	--LOCALIZATION_ZORLEN_Eviscerate = "";
	--LOCALIZATION_ZORLEN_ExposeArmor = "";
	--LOCALIZATION_ZORLEN_Feint = "";
	--LOCALIZATION_ZORLEN_Garrote = "";
	--LOCALIZATION_ZORLEN_GhostlyStrike = "";
	--LOCALIZATION_ZORLEN_Gouge = "";
	--LOCALIZATION_ZORLEN_Hemorrhage = "";
	--LOCALIZATION_ZORLEN_Kick = "";
	--LOCALIZATION_ZORLEN_KidneyShot = "";
	--LOCALIZATION_ZORLEN_PickLock = "";
	--LOCALIZATION_ZORLEN_PickPocket = "";
	--LOCALIZATION_ZORLEN_Premeditation = "";
	--LOCALIZATION_ZORLEN_Preparation = "";
	--LOCALIZATION_ZORLEN_RelentlessStrikes = "";
	--LOCALIZATION_ZORLEN_Riposte = "";
	--LOCALIZATION_ZORLEN_Rupture = "";
	--LOCALIZATION_ZORLEN_Sap = "";
	--LOCALIZATION_ZORLEN_SinisterStrike = "";
	--LOCALIZATION_ZORLEN_SliceAndDice = "";
	--LOCALIZATION_ZORLEN_Sprint = "";
	--LOCALIZATION_ZORLEN_Stealth = "";
	--LOCALIZATION_ZORLEN_Vanish = "";



-- Zorlen_Shaman.lua file Localization
	--LOCALIZATION_ZORLEN_DiseaseCleansingTotem = "";
	--LOCALIZATION_ZORLEN_EarthbindTotem = "";
	--LOCALIZATION_ZORLEN_FireNovaTotem = "";
	--LOCALIZATION_ZORLEN_FireResistanceTotem = "";
	--LOCALIZATION_ZORLEN_FlametongueTotem = "";
	--LOCALIZATION_ZORLEN_FrostResistanceTotem = "";
	--LOCALIZATION_ZORLEN_GraceOfAirTotem = "";
	--LOCALIZATION_ZORLEN_GroundingTotem = "";
	--LOCALIZATION_ZORLEN_HealingStreamTotem = "";
	--LOCALIZATION_ZORLEN_MagmaTotem = "";
	--LOCALIZATION_ZORLEN_ManaSpringTotem = "";
	--LOCALIZATION_ZORLEN_ManaTideTotem = "";
	--LOCALIZATION_ZORLEN_NatureResistanceTotem = "";
	--LOCALIZATION_ZORLEN_PoisonCleansingTotem = "";
	--LOCALIZATION_ZORLEN_SearingTotem = "";
	--LOCALIZATION_ZORLEN_SentryTotem = "";
	--LOCALIZATION_ZORLEN_StoneclawTotem = "";
	--LOCALIZATION_ZORLEN_StoneskinTotem = "";
	--LOCALIZATION_ZORLEN_StrengthOfEarthTotem = "";
	--LOCALIZATION_ZORLEN_TremorTotem = "";
	--LOCALIZATION_ZORLEN_WindfuryTotem = "";
	--LOCALIZATION_ZORLEN_WindwallTotem = "";
	--LOCALIZATION_ZORLEN_EarthShock = "";
	--LOCALIZATION_ZORLEN_FlameShock = "";
	--LOCALIZATION_ZORLEN_FrostShock = "";
	--LOCALIZATION_ZORLEN_FlametongueWeapon = "";
	--LOCALIZATION_ZORLEN_FrostbrandWeapon = "";
	--LOCALIZATION_ZORLEN_RockbiterWeapon = "";
	--LOCALIZATION_ZORLEN_WindfuryWeapon = "";
	--LOCALIZATION_ZORLEN_AncestralSpirit = "";
	--LOCALIZATION_ZORLEN_AstralRecall = "";
	--LOCALIZATION_ZORLEN_ChainHeal = "";
	--LOCALIZATION_ZORLEN_ChainLightning = "";
	--LOCALIZATION_ZORLEN_CureDisease = "";
	--LOCALIZATION_ZORLEN_CurePoison = "";
	--LOCALIZATION_ZORLEN_ElementalFocus = "";
	--LOCALIZATION_ZORLEN_ElementalMastery = "";
	--LOCALIZATION_ZORLEN_FarSight = "";
	--LOCALIZATION_ZORLEN_GhostWolf = "";
	--LOCALIZATION_ZORLEN_LesserHealingWave = "";
	--LOCALIZATION_ZORLEN_HealingWave = "";
	--LOCALIZATION_ZORLEN_LightningBolt = "";
	--LOCALIZATION_ZORLEN_LightningShield = "";
	--LOCALIZATION_ZORLEN_NaturesSwiftness = "";
	--LOCALIZATION_ZORLEN_Purge = "";
	--LOCALIZATION_ZORLEN_Reincarnation = "";
	--LOCALIZATION_ZORLEN_Stormstrike = "";
	--LOCALIZATION_ZORLEN_WaterBreathing = "";
	--LOCALIZATION_ZORLEN_WaterWalking = "";



-- Zorlen_Warrior.lua file Localization
	--LOCALIZATION_ZORLEN_ImprovedOverpower = "";
	--LOCALIZATION_ZORLEN_ImprovedBerserkerRage = "";
	--LOCALIZATION_ZORLEN_ImprovedExecute = "";
	--LOCALIZATION_ZORLEN_Execute = "";
	--LOCALIZATION_ZORLEN_ImprovedHeroicStrike = "";
	--LOCALIZATION_ZORLEN_HeroicStrike = "";
	--LOCALIZATION_ZORLEN_ImprovedSunderArmor = "";
	--LOCALIZATION_ZORLEN_SunderArmor = "";
	--LOCALIZATION_ZORLEN_ImprovedThunderClap = "";
	--LOCALIZATION_ZORLEN_ThunderClap = "";
	--LOCALIZATION_ZORLEN_MortalStrike = "";
	--LOCALIZATION_ZORLEN_Bloodthirst = "";
	--LOCALIZATION_ZORLEN_ShieldSlam = "";
	--LOCALIZATION_ZORLEN_Charge = "";
	--LOCALIZATION_ZORLEN_Taunt = "";
	--LOCALIZATION_ZORLEN_Intercept = "";
	--LOCALIZATION_ZORLEN_Overpower = "";
	--LOCALIZATION_ZORLEN_Revenge = "";
	--LOCALIZATION_ZORLEN_Rend = "";
	--LOCALIZATION_ZORLEN_Hamstring = "";
	--LOCALIZATION_ZORLEN_ShieldBash = "";
	--LOCALIZATION_ZORLEN_Pummel = "";
	--LOCALIZATION_ZORLEN_ShieldBlock = "";
	--LOCALIZATION_ZORLEN_DemoralizingShout = "";
	LOCALIZATION_ZORLEN_BattleShout = "Cri de guerre";
	--LOCALIZATION_ZORLEN_BerserkerRage = "";
	--LOCALIZATION_ZORLEN_Enrage = "";
	--LOCALIZATION_ZORLEN_DefensiveStance = "";
	--LOCALIZATION_ZORLEN_BattleStance = "";
	--LOCALIZATION_ZORLEN_BerserkerStance = "";
	--LOCALIZATION_ZORLEN_AngerManagement = "";
	--LOCALIZATION_ZORLEN_Bloodrage = "";
	--LOCALIZATION_ZORLEN_ChallengingShout = "";
	--LOCALIZATION_ZORLEN_Cleave = "";
	--LOCALIZATION_ZORLEN_ConcussionBlow = "";
	--LOCALIZATION_ZORLEN_DeathWish = "";
	--LOCALIZATION_ZORLEN_Disarm = "";
	--LOCALIZATION_ZORLEN_IntimidatingShout = "";
	--LOCALIZATION_ZORLEN_LastStand = "";
	--LOCALIZATION_ZORLEN_MockingBlow = "";
	--LOCALIZATION_ZORLEN_PiercingHowl = "";
	--LOCALIZATION_ZORLEN_Recklessness = "";
	--LOCALIZATION_ZORLEN_Retaliation = "";
	--LOCALIZATION_ZORLEN_ShieldWall = "";
	--LOCALIZATION_ZORLEN_Slam = "";
	--LOCALIZATION_ZORLEN_SweepingStrikes = "";
	--LOCALIZATION_ZORLEN_Whirlwind = "";
	--LOCALIZATION_ZORLEN_TacticalMastery = "";
end
