local L = AceLibrary("AceLocale-2.2"):new("ag_UnitFrames")

L:RegisterTranslations("enUS", function() return {
		["Fonts\\FRIZQT__.TTF"] = true,
		["Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf"] = true,
		
		["addonname"]			= "ag_UnitFrames",
		
		["config"]				= "Configure",
		["configdesc"]			= "Opens the configuration menu",
		
		["reset"]				= "Reset",
		["resetdesc"]			= "Resets the current profile",
		
		["player"]				= "Player",
		["pet"]					= "Player's Pet",
		["party"]				= "Party",
		["partypet"]			= "Party Pets",
		["target"]				= "Target",
		["targettarget"]		= "Target's Target",
		["raid"]				= "Raid",
		["raidpet"]				= "Raid Pets",
		
		["dead"]				= "DEAD",
		["ghost"]				= "GHOST",
		["disc"]				= "OFFLINE",
		
		["frame"]				= "%s Frame",
		["aurasettings"]		= "Aura Settings",
		["layoutsettings"]		= "%s Layout Settings",
		["unitsettings"]		= "Frame Settings",
		
		["units"]			    = "Unit Frames",
		["groups"]			    = "Unit Groups",
		["borders"]				= "Borders",
		["barstyle"]			= "Bar Style",
		["highlightselected"]	= "Highlight Selected",
		["smoothbarcoloring"]	= "Smooth Bar Coloring",
		["targetshowhostile"]	= "Hostility Coloring",
		["pvpicon"]				= "Show PvP Icons",
		["groupicon"]			= "Show Group Icons",
		["lock"]				= "Lock Frames",
		
		["framestyle"]			= "Frame Layout",
		["widthadjust"]			= "Frame Width",
		["aurastyle"]			= "Aura Style",
		["aurapos"]				= "Aura Position",
		["statustext"]			= "Statusbar Text",
		["scale"]				= "Scale",
		["longbars"]			= "Extend Statusbars",
		["classcolorbar"]		= "Color Health by Class",
		["raidcolorname"]		= "Color Name by Class",
		["showcombat"]			= "Display Combat Text",
		["aurafilter"]			= "Filter Auras",
		["debuffcoloring"]		= "Debuff Highlighting",
		["hidemana"]			= "Hide Mana Bar",
		["hideframe"]			= "Hide Frames",
		["showincombat"] 		= "Show Status Icon",
--		["showresting"] 		= "Show Resting Icon",
		["showraidicon"] 		= "Show Raid Target Icon",
		["showportrait"]		= "Show Portrait",
		["showxp"]				= "Show Experience Bar",
		["raidhideparty"]		= "Hide Frames in Raid",
		["raidgrouping"]		= "Group Raid By",
		
		["bysubgroup"]			= "Raid Subgroups",
		["byclass"]				= "Classes",
		["byrole"]				= "Healer/Tank/DPS",
		["onebiggroup"]			= "All Together",
		["nogroup"]				= "Don't Group",
		
		["partygrouping"]		= "Group Party",
		["petgrouping"]			= "Group Pets",
		
		["withplayer"]			= "With Player",
		["withoutplayer"]		= "Without Player",
		
		["oneline"]				= "One Line",
		["twolines"]			= "Two Lines",
		["hide"]				= "Hidden",
		
		["health"] 				= "Health",
		["mana"] 				= "Mana",
		["rage"] 				= "Rage",
		["petfocus"] 			= "Pet Focus",
		["barcolors"] 			= "Bar Colors",
		["energy"] 				= "Energy",
		
		["healthDesc"] 			= "Set the health color",
		["manaDesc"] 			= "Set the mana color",
		["rageDesc"] 			= "Set the rage color",
		["petfocusDesc"] 		= "Set the pet focus color",
		["energyDesc"] 			= "Set the energy color",
		["barcolorsDesc"] 		= "Set power colors for all units",
		["UnitDesc"]			= "Individual frame configuration",
		["groupsDesc"]			= "Unit group configuration",
		["BordersDesc"]			= "Set frame borders",
		["BarStyleDesc"]		= "Set bar textures",
		["HighlightSelectedDesc"]	= "Check to show selection highlight on frames",
		["SmoothBarColoringDesc"]	= "Check to have the health bar turn red as health drops",
		["ShowPVPIconDesc"]		= "Check to show pvp icons",
		["ShowGroupIconsDesc"]	= "Check to show group leader icon",
		["LockedDesc"]		    = "Lock the frames",
		["FrameStyleDesc"]		= "Set the frame style",
		["StatusTextDesc"]		= "Set what information is shown on health and mana bars",
		["ScaleDesc"]		    = "Set the frame scale",
		["widthadjustDesc"]		= "Set the frame width",
		["ClassColorBarsDesc"]	= "Check to color health bars by class type",
		["RaidColorNameDesc"]	= "Check to color unit names by class type",
		["ShowCombatDesc"]		= "Check to show combat text in the frame",
		["LongBarsDesc"]		= "Check to extend health and mana bars over the entire frame",
		["HideManaDesc"]		= "Check to hide the mana bar",
		["HideFrameDesc"]		= "Check to hide the entire frame",
		["AuraStyleDesc"]		= "Set the aura style",
		["AuraPosDesc"] 		= "Set the aura position",
		["DebuffColoringDesc"]	= "Check to color the frame by debuff type",
		["AuraFilterDesc"]		= "Check to only show auras you can cast or cure",
		["ShowInCombatDesc"]	= "Check to show status icon",
		["ShowRaidIconDesc"]	= "Check to show raid target icon",
--		["ShowRestingDesc"] = "Check to show resting icon",
		["ShowXPDesc"]		    = "Check to show an experience bar",
		["ShowPortraitDesc"]	= "Check to show a portrait (if the theme supports it!!)",
		["PetGroupingDesc"]		= "Set pet grouping",
		["TargetHostileDesc"]	= "Check to color health bars by hostility",
		["RaidHidePartyDesc"]	= "Check to hide party frames in raid",
		["PartyGroupingDesc"]	= "Set party grouping",
		["RaidGroupingDesc"]	= "Set raid grouping",
		["targetbg"]			= "Target Background",
		["targetbgdesc"]		= "Target frame background color",
		["partybg"]				= "Party Background",
		["partybgdesc"]			= "Party frame background color",
		["bordercolor"]			= "Border Color",
		["bordercolordesc"]		= "Frame border color",
		["framecolors"]			= "Frame Colors",
		["framecolorsdesc"]		= "Frame background and border color",

		["Group %s"] = true,
		["Group %s *"] = true,

		["%s Settings"] = true,
		
		["groupgrow"]		= "Growth Direction",
		["groupgrowDesc"]	= "Set the direction in which the group grows",
		["groupshowanchor"]		= "Show Group Anchor",
		["groupshowanchorDesc"]	= "Check to show the group anchor",
		["groupanchorto"]		= "Anchor to Group",
		["groupanchortoDesc"]	= "Set which other group the group will stick to",		

		["up"]	= "Up",		
		["down"]	= "Down",		
		["left"]	= "Left",		
		["right"]	= "Right",		

		
		["Status Text"] = true,
		["%s Text"] = true,
		["Health"] = true,
		["Name"] = true,
		["Class"] = true,
		["Style"] = true,
		["Custom"] = true,
		
		-- Unit classifications
		["Boss"] = true,
		["Rare-Elite"] = true,
		["Elite"] = true,
		["Rare"] = true,
		
		-- Unit status
		["Dead"] = true,
		["Ghost"] = true,
		["Offline"] = true,
		["Combat"] = true,
		["Resting"] = true,
		["Unknown"] = true,
		["Male"] = true,
		["Female"] = true,
		["Rested"] = true,
		["(L)"] = true,
		["(Leader)"] = true,
		["Tapped"] = "*",
		
		-- Power types
		["Rage"] = true,
		["Focus"] = true,
		["Energy"] = true,
		["Mana"] = true,
	}
end)
