local L = AceLibrary("AceLocale-2.2"):new("ag_UnitFrames")

L:RegisterTranslations("frFR", function()
    return {


["addonname"]          = "ag_UnitFrames",

["config"] = "Configuration",
["configdesc"]          = "Ouvre le menu de configuration",

["reset"] = "R\195\169-initialise",
["resetdesc"]          = "R\195\169-initialise le profile actuel",

["player"] = "Soi",
["pet"]          = "Familier",
["party"] = "Groupe",
["partypet"] = "Familiers du groupe",
["target"] = "Cible",
["targettarget"] = "Cible de la cible",
["raid"] = "Raid",
["raidpet"] = "Familiers du Raid",

["dead"] = "MORT",
["ghost"] = "FANTOME",
["disc"] = "HORS-LIGNE",

["frame"] = "Cadre",
["aurasettings"]          = "Param\195\168trage des Buffs/Debuffs",
["layoutsettings"]            = "%s: Param\195\168trage de l'interface",
["unitsettings"]                = "Param\195\168trage des Interfaces",

["units"] = "Gestion des interfaces",
["borders"]          = "Bordures",
["barstyle"]            = "Style des barres",
["highlightselected"]           = "Sur-brillance de la s\195\169lection",
["smoothbarcoloring"]         = "Couleur des barres att\195\169nu\195\169e",
["targetshowhostile"]           = "Coloration Hostilit\195\169",
["pvpicon"] = "Montre les ic\195\180nes JcJ",
["groupicon"]          = "Montre les ic\195\180nes Groupe",
["lock"] = "Verrouillage de l'interface",

["framestyle"]         = "Aspect de l'interface",
["widthadjust"] = "Largeur de l'interface",
["aurastyle"]           = "Style des buffs/debuffs",
["aurapos"] = "Position des buffs/debuffs",
["statustext"]          = "Textes des barres d'\195\169tat",
["scale"] = "Echelle",
["longbars"]          = "Extension des barres d'\195\169tat",
["classcolorbar"]          = "Coloration des barres de vie par classe",
["raidcolorname"] = "Coloration des noms par classe",
["showcombat"] = "Affichage des textes de Combat",
["aurafilter"] = "Filtre des buffs/debuffs",
["debuffcoloring"] = "Mise en surbrillance des debuffs",
["hidemana"] = "Cache la barre de mana",
["hideframe"] = "Cache l'interface",
["showincombat"] = "Affiche l'ic\195\180ne de combat",
-- ["showresting"] = "Affiche l'ic\195\180ne de repos",
["showraidicon"] = "Affiche l'ic\195\180ne de ciblage de raid",
["showportrait"] = "Affiche le Portrait",
["showxp"] = "Affiche barre d'exp\195\169rience",
["raidhideparty"] = "Cache l'interface en Raid",
["raidgrouping"] = "Regroupe le raid par",

["bysubgroup"] = "Sous-groupe du raid",
["byclass"] = "Classes",
["byrole"] = "Healer/Tank/DPS",
["onebiggroup"] = "Tous ensemble",
["nogroup"] = "Pas de regroupement",

["partygrouping"] = "Lier le groupe",
["petgrouping"] = "Lier les familiers",

["withplayer"] = "Avec Soi",
["withoutplayer"] = "Sans Soi",

["oneline"] = "Une ligne",
["twolines"] = "Deux lignes",
["hide"] = "Cacher",

                ["health"]                      = "Vie",
["mana"] = "Mana",
["rage"] = "Rage",
["petfocus"] = "Focalisation du Pet",
["barcolors"] = "Couleurs des barres",
["energy"] = "Energie",

["healthDesc"] = "Param\195\169trage de la couleur des barres de vie",
["manaDesc"] = "Param\195\169trage de la couleur des barres de mana",
["rageDesc"] = "Param\195\169trage de la couleur des barres de rage",
["petfocusDesc"] = "Param\195\169trage de la couleur des barres de focalisation des pets",
["energyDesc"] = "Param\195\169trage de la couleur des barres d'\195\169nergie",
["barcolorsDesc"] = "Param\195\169trage des couleurs des barres d'\195\169tat des interfaces",
                ["UnitDesc"]                    = "Configuration des interfaces",
                ["BordersDesc"]                 = "Param\195\169trage des bordures des Cadres",
                ["BarStyleDesc"]                = "Param\195\169trage de la texture des interfaces",
                ["HighlightSelectedDesc"]       = "Cocher pour voir la s\195\169lection en surbrillance dans les Cadres",
["SmoothBarColoringDesc"] = "Cocher pour voir la barre de vie se colorer en rouge quand la vie devient faible",
                ["ShowPVPIconDesc"]             = "Cocher pour voir les ic\195\180nes PVP",
                ["ShowGroupIconsDesc"]         = "Cocher pour voir l'ic\195\180ne de leader du raid",
                ["LockedDesc"]                  = "Verrouillage des interfaces",
                ["FrameStyleDesc"]              = "Param\195\169trage du style des interfaces",
                ["StatusTextDesc"]              = "Param\195\169trage des informations apparaissant sur les barres de vie et de mana",
                ["ScaleDesc"]                   = "Param\195\169trage de l'\195\169chelle des interfaces",
["widthadjustDesc"]             = "Ajuste la largeur de l'interface.",
                ["ClassColorBarsDesc"]          = "Cocher pour colorier les barres de vie selon le type de classe",
                ["RaidColorNameDesc"]           = "Cocher pour colorier les noms des personnages selon le type de classe",
                ["ShowCombatDesc"]              = "Cocher pour afficher les textes de combat dans l'interface",
                ["LongBarsDesc"]                = "Cocher pour \195\169tendre les barres de vie et de mana à tous le cadre",
                ["HideManaDesc"]                = "Cocher pour cacher la barre de mana",
                ["HideFrameDesc"]               = "Cocher pour cacher l'interface",
                ["AuraStyleDesc"]               = "D\195\169finit le style des buffs/debuffs",
                ["AuraPosDesc"]                 = "D\195\169finit la position des buffs/debuffs",
                ["DebuffColoringDesc"]          = "Cocher pour colorier les cadres selon le type de debuff",
                ["AuraFilterDesc"]              = "Cocher pour montrer seulement les buffs/debuffs que vous pouvez lancer ou soigner",
["ShowInCombatDesc"]            = "Cocher pour afficher l'ic\195\180ne de combat",
["ShowRaidIconDesc"]            = "Cocher pour afficher l'ic\195\180ne de ciblage de raid",
-- ["ShowRestingDesc"]             = "Cocher pour afficher l'ic\195\180ne de repos",
                ["ShowXPDesc"]                  = "Cocher pour afficher une barre d'exp\195\169rience",
["ShowPortraitDesc"]         = "Cocher pour afficher les protraits dans l'interface (si le th\195\170me l'autorise !!)",
                ["PetGroupingDesc"]             = "Param\195\169trage de la liaison du cadre des familiers",
                ["TargetHostileDesc"]           = "Cocher pour colorier la barre de vie selon l'hostilit\195\169",
                ["RaidHidePartyDesc"]           = "Cocher pour cacher l'interface de groupe en raid",
                ["PartyGroupingDesc"]           = "Param\195\169trage des liaisons de l'interface de groupe",
                ["RaidGroupingDesc"]            = "Param\195\169trage des regroupements de l'interface de raid",
                ["targetbg"]                    = "Arri\195\168re-plan de la cible",
["targetbgdesc"]                = "Choix de la couleur de l'arri\195\168re-plan de la cible.",
["partybg"]                     = "Arri\195\168re-plan du groupe",
["partybgdesc"]                 = "Choix de la couleur de l'arri\195\168re-plan de groupe.",
["bordercolor"]                 = "Couleur des bordures",
["bordercolordesc"]             = "Choix de la couleur des bordures des interfaces.",
["framecolors"]                 = "Couleur des interfaces",
["framecolorsdesc"]             = "Choix de la couleur des interfaces et des bordures.",

["Group %s"]                    = "Groupe %s",
["Group %s *"]                  = "Groupe %s *",

["%s Settings"]                 = "Param\195\169trage de l'interface : %s",

["Status Text"]                 = "Information d'\195\169tat",
["%s Text"]                     = "Information : %s",
["Health"]                      = "Vie",
["Name"]                        = "Nom",
["Class"]                       = "Classe",
["Style"]                       = "Style",
["Custom"]                      = "Personnalis\195\169",

-- Unit classifications
["Boss"]                        = "Boss",
["Rare-Elite"]                  = "Rare-Elite",
["Elite"]                       = "Elite",
["Rare"]                        = "Rare",

-- Unit status
["Dead"]                        = "Mort",
["Ghost"]                       = "Forme Fant\195\180me",
["Offline"]                     = "Hors-ligne",
["Combat"]                      = "Combat",
["Resting"]                     = "Repos",
["Unknown"]                     = "Inconnu",
["Male"]                        = "Male",
["Female"]                      = "Female",
["Rested"]                      = "Repos\195\169",
["(L)"]                         = "(L)",
["(Leader)"]                    = "(Leader)",
["Tapped"]                      = "*",

-- Power types
["Rage"]                        = "Rage",
["Focus"]                       = "Focus",
["Energy"]                      = "Energie",
["Mana"]                        = "Mana",
}
end)

