local L = AceLibrary("AceLocale-2.2"):new("ag_UnitFrames")

L:RegisterTranslations("koKR", function() return {
		["Fonts\\FRIZQT__.TTF"]	= "Fonts\\2002.TTF",
		["Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf"] = "Fonts\\K_Damage.TTF",

		["addonname"]			= "ag_UnitFrames",	
		
		["config"]				= "환경설정",	
		["configdesc"]			= "환경설정 메뉴 열기",	

		["reset"]				= "초기화",	
		["resetdesc"]			= "현재 프로필 초기화",	
		
		["player"]				= "플레이어",
		["pet"]					= "플레이어 소환수",
		["party"]				= "파티",
		["partypet"]			= "파티 소환수",
		["target"]				= "대상",
		["targettarget"]		= "대상의 대상",
		["raid"]				= "공격대",
		["raidpet"]				= "공격대 소환수",
		
		["dead"] 				= "죽음",
		["ghost"] 				= "유령",
		["disc"] 				= "오프라인",
		
		["frame"] 				= "프레임",
		["aurasettings"] 		= "버프 설정",
		["layoutsettings"] 		= "외관 설정",
		["unitsettings"] 		= "프레임 설정",
		
		["units"] 				= "유닛 프레임",
		["groups"]			    = "유닛 그룹",
		["borders"] 			= "테두리",
		["barstyle"] 			= "바 스타일",
		["highlightselected"]	= "선택 강조",
		["smoothbarcoloring"]	= "부르러운 바 색상화",
		["targetshowhostile"]	= "우호도 색상",
		["pvpicon"]				= "PvP 아이콘 표시",
		["groupicon"]			= "그룹 아이콘 표시",
		["lock"]				= "프레임 고정",
		
		["framestyle"]			= "프레임 외관",
		["widthadjust"]			= "프레임 너비",
		["aurastyle"]			= "버프 스타일",
		["aurapos"]				= "버프 위치",
		["statustext"]			= "상태바 글자",
		["scale"]				= "크기",
		["longbars"]			= "상태바 확장",
		["classcolorbar"]		= "생명력 클래스 색상",
		["raidcolorname"]		= "이름 클래스 색상",
		["showcombat"]			= "전투 텍스트 표시",
		["aurafilter"]			= "버프 필터",
		["debuffcoloring"]		= "디버프 강조",
		["hidemana"]			= "마나바 숨김",
		["hideframe"]			= "프레임 숨김",
		["showincombat"] 		= "전투상태 아이콘 표시",
--		["showresting"] 		= "휴식중 아이콘 표시",
		["showraidicon"] 		= "공격대 대상 아이콘 표시",
		["showportrait"]		= "초상화 표시",
		["showxp"]				= "경험치바 표시",
		["raidhideparty"]		= "공격대일 때 프레임 숨김",
		["raidgrouping"]		= "공격대 분류",
		
		["bysubgroup"]			= "파티별 분류",
		["byclass"]				= "직업별 분류",
		["byrole"]				= "힐러/탱커/DPS",
		["onebiggroup"]			= "분류 없음",
		["nogroup"]				= "파티표시 숨김",

		["partygrouping"]		= "파티 그룹화",
		["petgrouping"]			= "소환수 그룹화",

		["withplayer"]			= "플레이와 함께",
		["withoutplayer"]		= "플레이어 제외",		
		
		["oneline"]				= "한줄",
		["twolines"]			= "두줄",	
		["hide"]				= "숨김",	
        
		["health"] 				= "생명력",	
		["mana"] 				= "마나",	
		["rage"] 				= "분노",	
		["petfocus"] 			= "수환수 포커스",	
		["barcolors"] 			= "바 색상",	
		["energy"] 				= "기력",	

		["healthDesc"] 			= "생명력 색상 설정",	
		["manaDesc"] 			= "마나 색상 설정",	
		["rageDesc"] 			= "분노 색상 설정",	
		["petfocusDesc"] 		= "소환수 포커스 색상 설정",	
		["energyDesc"] 			= "기력 색상 설정",	
		["barcolorsDesc"] 		= "모든 유닛에 대한 파워 색상 설정",			
        ["UnitDesc"]			= "개별 프레임 환경설정",
	["groupsDesc"]			= "유닛 그룹 환경설정",
        ["BordersDesc"]			= "프레임 테두리 설정",
        ["BarStyleDesc"]		= "바 텍스쳐 설정",
        ["HighlightSelectedDesc"]	= "선택된 프레임 강조 표시 설정",
	["SmoothBarColoringDesc"]	= "생명력 저하에 따라 생명력바를 빨간색으로 변화시키려면 체크 하세요.",
        ["ShowPVPIconDesc"]		= "pvp 아이콘 표시 설정",
        ["ShowGroupIconsDesc"]	= "파티 리더 아이콘 표시 설정",
        ["LockedDesc"]		    = "프레임 고정",
        ["FrameStyleDesc"]		= "프레임 스타일 설정",
        ["StatusTextDesc"]		= "생명력과 마나바에 표시할 정보 설정",
        ["ScaleDesc"]		    = "프레임 크기 설정",
        ["widthadjustDesc"]		= "프레임 너비 설정",
        ["ClassColorBarsDesc"]	= "클래스 타입에 따른 생명력 색상 설정",
        ["RaidColorNameDesc"]	= "클래스 타입에 따른 이름 색상 설정",
        ["ShowCombatDesc"]		= "프레임에 전투 텍스트 표시 설정",
        ["LongBarsDesc"]		= "모든 프레임에 생명력과 마나바 확장 설정",
        ["HideManaDesc"]		= "마나바 숨김 설정",
        ["HideFrameDesc"]		= "모든 프레임 숨김 설정",
        ["AuraStyleDesc"]		= "버프 스타일 설정",
        ["AuraPosDesc"] 		= "버프 위치 설정",
        ["DebuffColoringDesc"]	= "디버프 타입에 따른 프레임 색상 설정",
        ["AuraFilterDesc"]		= "시전/해제 가능한 버프만 표시 설정",
		["ShowInCombatDesc"] = "전투 상태 아이콘 표시 설정",
		["ShowRaidIconDesc"] = "공격대 대상 아이콘 표시 설정",
--		["ShowRestingDesc"] = "휴식중 아이콘 표시 설정",
        ["ShowXPDesc"]		    = "경험치바 표시",
	["ShowPortraitDesc"]	= "초상화를 표시하려면 체크 하세요(테마 지원 시 적용!!)",
        ["PetGroupingDesc"]		= "소환수 그룹화 설정",
        ["TargetHostileDesc"]	= "우호도에 따른 생명력 색상 사용",
        ["RaidHidePartyDesc"]	= "공격대시 파티 프레임 숨김",
        ["PartyGroupingDesc"]	= "파티 그룹화 설정",
        ["RaidGroupingDesc"]	= "공격대 그룹화 설정",
		["targetbg"]			= "대상 배경",
		["targetbgdesc"]		= "대상 프레임 배경 색상",
		["partybg"]				= "파티 배경",
		["partybgdesc"]			= "파티 프레임 배경 색상",
		["bordercolor"]			= "테두리 색상",
		["bordercolordesc"]		= "프레임 테두리 색상",
		["framecolors"]			= "프레임 색상",
		["framecolorsdesc"]		= "프레임 배경과 테두리 색상",

		["Group %s"] = "%s 파티",
		["Group %s *"] = "%s 파티 *",

		["%s Settings"] = "%s 설정",
		
		["groupgrow"]		= "생성 방향",
		["groupgrowDesc"]	= "그룹 생성 방향을 설정합니다.",
		["groupshowanchor"]		= "그룹 고정위치 표시",
		["groupshowanchorDesc"]	= "그룹 고정위치를 표시하려면 체크하세요",
		["groupanchorto"]		= "그룹 고정위치",
		["groupanchortoDesc"]	= "그룹을 다른 그룹에 붙이기를 설정합니다.",		

		["up"]	= "위",		
		["down"]	= "아래",		
		["left"]	= "왼쪽",		
		["right"]	= "오른쪽",		

		
		["Status Text"] = "상태 텍스트",
		["%s Text"] = "%s 텍스트",
		["Health"] = "생명력",
		["Name"] = "이름",
		["Class"] = "직업",
		["Style"] = "스타일",
		["Custom"] = "사용자",

		-- Unit classifications
		["Boss"] = "보스",
		["Rare-Elite"] = "희귀-정예",
		["Elite"] = "정예",
		["Rare"] = "희귀",

		-- Unit status
		["Dead"] = "죽음",
		["Ghost"] = "유령",
		["Offline"] = "오프라인",
		["Combat"] = "전투",
		["Resting"] = "휴식 중",
		["Unknown"] = "알 수 없음",
		["Male"] = "남성",
		["Female"] = "여성",
		["Rested"] = "Rested",
		["(L)"] = "(L)",
		["(Leader)"] = "(Leader)",
		["Tapped"] = "*",

		-- Power types
		["Rage"] = "Rage",
		["Focus"] = "Focus",
		["Energy"] = "기력",
		["Mana"] = "마나",
	}
end)
