
-- ************************************* Const / defines *************************************
TITAN_HOLYCANDLESCOUNTER_ALERT = 10


TITAN_HOLYCANDLESCOUNTER_ITEMNAME = "Holy Candle";
TITAN_HOLYCANDLESCOUNTER_BUTTON_LABEL = TITAN_HOLYCANDLESCOUNTER_ITEMNAME..": ";
TITAN_HOLYCANDLESCOUNTER_TOOLTIP_COUNT = TITAN_HOLYCANDLESCOUNTER_ITEMNAME..": ";
TITAN_HOLYCANDLESCOUNTER_TOOLTIPTEXT= "Current count of "..TITAN_HOLYCANDLESCOUNTER_ITEMNAME;
TITAN_HOLYCANDLESCOUNTER_MENU_TEXT = "Priest: "..TITAN_HOLYCANDLESCOUNTER_ITEMNAME;

if ( GetLocale() == "deDE" ) then
    TITAN_HOLYCANDLESCOUNTER_ITEMNAME = "Heilige Kerze";
    TITAN_HOLYCANDLESSCOUNTER_BUTTON_LABEL = TITAN_HOLYCANDLESCOUNTER_ITEMNAME..": ";
    TITAN_HOLYCANDLESCOUNTER_TOOLTIP_COUNT = TITAN_HOLYCANDLESCOUNTER_ITEMNAME..": ";
    TITAN_HOLYCANDLESCOUNTER_TOOLTIPTEXT= "Aktuelle Anzahl von"..TITAN_HOLYCANDLESCOUNTER_ITEMNAME;
    TITAN_HOLYCANDLESCOUNTER_MENU_TEXT = "Priest: "..TITAN_HOLYCANDLESCOUNTER_ITEMNAME;
end

if ( GetLocale() == "frFR" ) then
TITAN_HOLYCANDLESCOUNTER_ITEMNAME = "Bougie sanctifi\195\169e";
TITAN_HOLYCANDLESCOUNTER_BUTTON_LABEL = TITAN_HOLYCANDLESCOUNTER_ITEMNAME..": ";
TITAN_HOLYCANDLESCOUNTER_TOOLTIP_COUNT = TITAN_HOLYCANDLESCOUNTER_ITEMNAME..": ";
TITAN_HOLYCANDLESCOUNTER_TOOLTIPTEXT= "Compte courant de "..TITAN_HOLYCANDLESCOUNTER_ITEMNAME;
TITAN_HOLYCANDLESCOUNTER_MENU_TEXT = "Priest: "..TITAN_HOLYCANDLESCOUNTER_ITEMNAME;
end