OneRaid_DefaultOptions = {
	["leaderColor"] = { r = 1, g = .5, b = 0 },
	["assistantColor"] = { r = 1, g = 1, b = 0 },
	["raidInfoColor"] = { r = .5, g = .5, b = .5 },
	["statusBuffs"] = {
		[1] = { name = "Feign Death", 	status = "feign" },
		[2] = { name = "Stealth", 		status = "stealth" },
		[3] = { name = "Prowl", 		status = "prowl" },
		[4] = { name = "Shadowmeld", 	status = "meld" },
	},
	["statusDebuffs"]	= {},
	["buffs"] = {
		[1] = { name = "Power Word: Fortitude", groupName = "Prayer of Fortitude" },
		[2] = { name = "Divine Spirit",			groupName = "Prayer of Spirit" },
		[3] = { name = "Shadow Protection",		groupName = "Prayer of Shadow Protection" },
		[4] = { name = "Mark of the Wild",		groupName = "Gift of the Wild" },
		[5] = { name = "Arcane Intellect",		groupName = "Arcane Brilliance" },
		[6] = { name = "Blessing of Kings",		groupName = "Greater Blessing of Kings" },
		[7] = { name = "Blessing of Wisdom",	groupName = "Greater Blessing of Wisdom" },
		[8] = { name = "Blessing of Might",		groupName = "Greater Blessing of Might" },
		[9] = { name = "Blessing of Light",		groupName = "Greater Blessing of Light" },
		[10] ={ name = "Blessing of Sanctuary",	groupName = "Greater Blessing of Sanctuary" },
		[11] ={ name = "Blessing of Sacrifice",	groupName = "Greater Blessing of Sacrifice" },
		[12] ={ name = "Blessing of Salvation",	groupName = "Greater Blessing of Salvation" },
		[13] ={ name = "Renew" },
		[14] ={ name = "Power Word: Shield" },
		[15] ={ name = "Fear Ward" },
		[16] ={ name = "Rejuvenation" },
		[17] ={ name = "Regrowth" },
		[18] ={ name = "Innervate" },
		[19] ={ name = "Thorns" },
		[20] ={ name = "Soulstone Resurrection" },
		[21] ={ name = "Fire Shield" },
		[22] ={ name = "Amplify Magic" },
		[23] ={ name = "Dampen Magic" },
	},
	["debuffs"] = {
		[1] = { name = ONERAID_DEBUFF_TYPE_MAGIC, 		standard = 1, debuffMonitor = 1, readonly = 1 },
		[2] = { name = ONERAID_DEBUFF_TYPE_DISEASE, 	standard = 1, debuffMonitor = 1, readonly = 1 },
		[3] = { name = ONERAID_DEBUFF_TYPE_POISON, 		standard = 1, debuffMonitor = 1, readonly = 1 },
		[4] = { name = ONERAID_DEBUFF_TYPE_CURSE, 		standard = 1, debuffMonitor = 1, readonly = 1 },
		[5] = { name = ONERAID_DEBUFF_TYPE_UNCURABLE, 	readonly = 1 },
		[6] = { name = "Recently Bandaged", standard = 1 },
		[7] = { name = "Mortal Strike", standard = 1, tankMonitor = 1 },
		[8] = { name = "Mortal Cleave", standard = 1, tankMonitor = 1 },
		[9] = { name = "Mortal Wound", standard = 1, tankMonitor = 1 },
	},
	["cureDebuffs"] = {
		[1] = { name = "Banish", ignore = 1 },
		[2] = { name = "Phase Shift", ignore = 1 },
		[3] = { name = "Dreamless Sleep", [ONERAID_WARRIOR] = 1, [ONERAID_PALADIN] = 1, [ONERAID_SHAMAN] = 1, [ONERAID_PRIEST] = 1, [ONERAID_DRUID] = 1, [ONERAID_MAGE] = 1, [ONERAID_WARLOCK] = 1, [ONERAID_HUNTER] = 1, [ONERAID_ROGUE] = 1 },
		[4] = { name = "Greater Dreamless Sleep", [ONERAID_WARRIOR] = 1, [ONERAID_PALADIN] = 1, [ONERAID_SHAMAN] = 1, [ONERAID_PRIEST] = 1, [ONERAID_DRUID] = 1, [ONERAID_MAGE] = 1, [ONERAID_WARLOCK] = 1, [ONERAID_HUNTER] = 1, [ONERAID_ROGUE] = 1 },
		[5] = { name = "Silence", [ONERAID_ROGUE] = 1 },
		[6] = { name = "Ignite Mana", [ONERAID_WARRIOR] = 1, [ONERAID_ROGUE] = 1 },
		[7] = { name = "Ancient Hysteria", [ONERAID_WARRIOR] = 1, [ONERAID_ROGUE] = 1 },
		[8] = { name = "Tainted Mind", [ONERAID_WARRIOR] = 1, [ONERAID_ROGUE] = 1 },
	},
	["cure" .. ONERAID_DEBUFF_TYPE_MAGIC] = 1,
	["cure" .. ONERAID_DEBUFF_TYPE_DISEASE] = 1,
	["cure" .. ONERAID_DEBUFF_TYPE_POISON] = 1,
	["cure" .. ONERAID_DEBUFF_TYPE_CURSE] = 1,
	["curePets"] = 1,
	["curePriority"] = {},
	["debuffPriority"] = {
		[1] = ONERAID_DEBUFF_TYPE_MAGIC,
		[2] = ONERAID_DEBUFF_TYPE_DISEASE,
		[3] = ONERAID_DEBUFF_TYPE_POISON,
		[4] = ONERAID_DEBUFF_TYPE_CURSE,
	},
	["classPriority"] = {
		[1] = ONERAID_WARRIOR,
		[2] = ONERAID_PALADIN,
		[3] = ONERAID_SHAMAN,
		[4] = ONERAID_PRIEST,
		[5] = ONERAID_DRUID,
		[6] = ONERAID_MAGE,
		[7] = ONERAID_WARLOCK,
		[8] = ONERAID_HUNTER,
		[9] = ONERAID_ROGUE,
	},
	["autoPromote"] = {},
	["Groups"] = {
		[ONERAID_GROUP1] = {
			["name"] = ONERAID_GROUP1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [1] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP2] = {
			["name"] = ONERAID_GROUP2,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {				
				["groups"] = { [2] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP3] = {
			["name"] = ONERAID_GROUP3,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [3] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP4] = {
			["name"] = ONERAID_GROUP4,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [4] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP5] = {
			["name"] = ONERAID_GROUP5,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [5] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP6] = {
			["name"] = ONERAID_GROUP6,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [6] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP7] = {
			["name"] = ONERAID_GROUP7,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [7] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_GROUP8] = {
			["name"] = ONERAID_GROUP8,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["class"] = 1,
			},
			["filters"] = {
				["groups"] = { [8] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_WARRIORS] = {
			["name"] = ONERAID_WARRIORS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_WARRIOR] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_PALADINS] = {
			["name"] = ONERAID_PALADINS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_PALADIN] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_SHAMANS] = {
			["name"] = ONERAID_SHAMANS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_SHAMAN] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_PRIESTS] = {
			["name"] = ONERAID_PRIESTS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_PRIEST] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_DRUIDS] = {
			["name"] = ONERAID_DRUIDS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_DRUID] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_MAGES] = {
			["name"] = ONERAID_MAGES,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_MAGE] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_WARLOCKS] = {
			["name"] = ONERAID_WARLOCKS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_WARLOCK] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_HUNTERS] = {
			["name"] = ONERAID_HUNTERS,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_HUNTER] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_ROGUES] = {
			["name"] = ONERAID_ROGUES,
			["hide"] = 1,
			["enableGroupToggle"] = 1,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenNotInRaid"] = 1,
			["sorting"] = {
				["offline"] = 1,
				["health"] = 1,
			},
			["filters"] = {
				["groups"] = {},
				["classes"] = { [ONERAID_ROGUE] = 1},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_PARTY] = {
			["name"] = ONERAID_PARTY,
			["scale"] = 1,
			["style"] = "Default",
			["hideWhenEmpty"] = 1,
			["hideWhenInRaid"] = 1,
			["sorting"] = {},
			["filters"] = {
				["groups"] = { ["party"] = 1 },
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_BUFFS] = {
			["name"] = ONERAID_BUFFS,
			["scale"] = 1,
			["style"] = "Buff",
			["hideWhenEmpty"] = 1,
			["buffMonitor"] = 1,
			["sorting"] = {
				["group"] = 1,
			},
			["filters"] = {
				["classes"] = {},
				["health"] = {},
				["groups"] = {
					[1] = 1,
					[2] = 1,
					[3] = 1,
					[4] = 1,
					[5] = 1,
					[6] = 1,
					[7] = 1,
					[8] = 1,
					["party"] = 1,
				},
				["offline"] = { ["hide"] = 1 },
				["players"] = {},
				["dead"] = { ["hide"] = 1 },
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_DEBUFFS] = {
			["name"] = ONERAID_DEBUFFS,
			["scale"] = 1,
			["style"] = "Debuff",
			["hideWhenEmpty"] = 1,
			["limit"] = 10,
			["debuffMonitor"] = 1,
			["sorting"] = {
				["alpha"] = 1,
			},
			["filters"] = {
				["classes"] = {},
				["health"] = {},
				["groups"] = {
					[1] = 1,
					[2] = 1,
					[3] = 1,
					[4] = 1,
					[5] = 1,
					[6] = 1,
					[7] = 1,
					[8] = 1,
					["party"] = 1,
				},
				["offline"] = { ["hide"] = 1 },
				["players"] = {},
				["dead"] = { ["hide"] = 1 },
				["buffs"] = {},
				["debuffs"] = {},
			},
		},
		[ONERAID_TANK_MONITOR] = {
			["name"] = ONERAID_TANK_MONITOR,
			["scale"] = 1,
			["style"] = "Tank Monitor",
			["hideWhenEmpty"] = 1,
			["sorting"] = {},
			["filters"] = {
				["groups"] = {},
				["classes"] = {},
				["players"] = {},
				["dead"] = {},
				["offline"] = {},
				["health"] = {},
				["buffs"] = {},
				["debuffs"] = {},
			},
			["tankMonitor"] = 1,
		},
	},
	["UnitStyles"] = {
		["Debuff"] = {
			["numberBuffs"] = 6,
			["borderType"] = 1,
			["voiceColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["range3ColorUseClassColor"] = 1,
			["rageColor"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["oorColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["targetIcon"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 16,
				["y"] = 0,
				["x"] = 0,
				["height"] = 16,
				["hide"] = 1,
				["frameLevel"] = 2,
				["texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["pvpColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["tankedColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["warnSameTarget"] = 1,
			["range2ColorUseClassColor"] = 1,
			["showAggroGain"] = 1,
			["showDebuffs"] = 1,
			["warningColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["enableBuffToggle"] = 1,
			["keybindings"] = {
				[1] = {
					["type"] = 7,
				},
				[2] = {
					["type"] = 1,
				},
				[3] = {
					["type"] = 3,
					["attack"] = 1,
				},
				[4] = {
					["type"] = 5,
				},
				[5] = {
					["type"] = 4,
				},
				[6] = {
					["type"] = 1,
				},
				[7] = {
					["type"] = 6,
				},
				[8] = {
					["type"] = 1,
				},
			},
			["farColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["manaType"] = 1,
			["focusColor"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.25,
			},
			["buffs"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["growth"] = 1,
				["width"] = 13,
				["y"] = -1,
				["x"] = -1,
				["height"] = 13,
				["frameLevel"] = 4,
			},
			["hoverColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["mediumColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["energyColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["range1Color"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["playAggroLost"] = 1,
			["buffCount"] = {
				["outline"] = 1,
				["point"] = "BOTTOMRIGHT",
				["shadowX"] = 0,
				["justifyV"] = "BOTTOM",
				["justifyH"] = "RIGHT",
				["shadowY"] = 0,
				["attach"] = "Frame",
				["layer"] = 1,
				["fontHeight"] = 10,
				["width"] = 12,
				["y"] = 1,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["relative"] = "BOTTOMRIGHT",
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["x"] = 0,
			},
			["range1ColorUseClassColor"] = 1,
			["backgroundType"] = 2,
			["range"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 4,
				["y"] = -2,
				["x"] = 2,
				["height"] = 11,
				["frameLevel"] = 2,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["healthBar"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["width"] = 73,
				["statusBarAlpha"] = 0.25,
				["x"] = -3,
				["hide"] = 1,
				["y"] = -18,
				["height"] = 12,
				["frameLevel"] = 1,
				["soloHeight"] = 17,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["health"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["x"] = 0,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["targetColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["showAggroLost"] = 1,
			["healthColor"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["maColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
			["healthType"] = 1,
			["voice"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 20,
				["y"] = 2,
				["x"] = -1,
				["height"] = 20,
				["hide"] = 1,
				["frameLevel"] = 3,
				["texture"] = "Interface\\GossipFrame\\GossipGossipIcon",
			},
			["mana"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["x"] = 0,
			},
			["manaBar"] = {
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "BOTTOM",
				["width"] = 73,
				["statusBarAlpha"] = 0.25,
				["x"] = 0,
				["hide"] = 1,
				["height"] = 4,
				["y"] = -1,
				["point"] = "TOP",
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["showTargetsTarget"] = 1,
			["manaColor"] = {
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 1,
			},
			["status"] = {
				["point"] = "CENTER",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "CENTER",
				["fontHeight"] = 14,
				["width"] = 70,
				["y"] = -6,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["x"] = 0,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
			},
			["nameColorType"] = 7,
			["playAggroGain"] = 1,
			["name"] = {
				["outline"] = 1,
				["point"] = "LEFT",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "LEFT",
				["shadowY"] = 0,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "LEFT",
				["fontHeight"] = 13,
				["width"] = 79,
				["y"] = 0,
				["x"] = 6,
				["height"] = 13,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["debuffColorAlpha"] = 0.25,
			["nameColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["closeColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["healthColorType"] = 1,
			["range3Color"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["range4Color"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["frame"] = {
				["height"] = 15,
				["width"] = 130,
			},
			["range2Color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["pvp"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 33,
				["y"] = 1,
				["x"] = -3,
				["height"] = 33,
				["hide"] = 1,
				["frameLevel"] = 1,
				["texture"] = "Interface\\ChatFrame\\ChatFrameBackground",
			},
		},
		["Default"] = {
			["numberBuffs"] = 6,
			["borderType"] = 5,
			["voiceColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["range3ColorUseClassColor"] = 1,
			["rageColor"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["oorColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["targetIcon"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 16,
				["y"] = 0,
				["x"] = 0,
				["height"] = 16,
				["frameLevel"] = 2,
				["texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["pvpColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["tankedColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["warnSameTarget"] = 1,
			["range2ColorUseClassColor"] = 1,
			["showAggroGain"] = 1,
			["showDebuffs"] = 1,
			["showBuffs"] = 1,
			["warningColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["enableBuffToggle"] = 1,
			["keybindings"] = {
				[1] = {
					["type"] = 2,
				},
				[2] = {
					["type"] = 1,
				},
				[3] = {
					["type"] = 3,
					["attack"] = 1,
				},
				[4] = {
					["type"] = 5,
				},
				[5] = {
					["type"] = 4,
				},
				[6] = {
					["type"] = 1,
				},
				[7] = {
					["type"] = 6,
				},
				[8] = {
					["type"] = 1,
				},
			},
			["farColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["manaType"] = 1,
			["focusColor"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.25,
			},
			["buffs"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["growth"] = 1,
				["width"] = 13,
				["y"] = -3,
				["x"] = -3,
				["height"] = 13,
				["frameLevel"] = 4,
			},
			["hoverColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["mediumColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["energyColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["range1Color"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["playAggroLost"] = 1,
			["buffCount"] = {
				["outline"] = 1,
				["point"] = "BOTTOMRIGHT",
				["shadowX"] = 0,
				["justifyV"] = "BOTTOM",
				["justifyH"] = "RIGHT",
				["shadowY"] = 0,
				["attach"] = "Frame",
				["layer"] = 1,
				["fontHeight"] = 10,
				["width"] = 12,
				["y"] = 1,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["relative"] = "BOTTOMRIGHT",
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["x"] = 0,
			},
			["range1ColorUseClassColor"] = 1,
			["backgroundType"] = 2,
			["range"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 4,
				["y"] = -18,
				["x"] = 3,
				["height"] = 17,
				["frameLevel"] = 2,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["healthBar"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["width"] = 73,
				["y"] = -18,
				["soloHeight"] = 17,
				["statusBarAlpha"] = 0.25,
				["height"] = 12,
				["frameLevel"] = 1,
				["x"] = -3,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["health"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["x"] = 0,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["targetColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["showAggroLost"] = 1,
			["healthColor"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["maColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
			["healthType"] = 1,
			["voice"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 20,
				["y"] = 2,
				["x"] = -1,
				["height"] = 20,
				["frameLevel"] = 3,
				["texture"] = "Interface\\GossipFrame\\GossipGossipIcon",
			},
			["mana"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["x"] = 0,
			},
			["manaBar"] = {
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "BOTTOM",
				["width"] = 73,
				["statusBarAlpha"] = 0.25,
				["x"] = 0,
				["height"] = 4,
				["y"] = -1,
				["point"] = "TOP",
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["showTargetsTarget"] = 1,
			["manaColor"] = {
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 1,
			},
			["status"] = {
				["point"] = "CENTER",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "CENTER",
				["fontHeight"] = 14,
				["width"] = 70,
				["y"] = -6,
				["x"] = 0,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["nameColorType"] = 7,
			["playAggroGain"] = 1,
			["name"] = {
				["outline"] = 1,
				["point"] = "TOPLEFT",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "LEFT",
				["shadowY"] = 0,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["fontHeight"] = 13,
				["width"] = 71,
				["y"] = -3,
				["x"] = 13,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["debuffColorAlpha"] = 0.25,
			["nameColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["closeColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["healthColorType"] = 1,
			["range3Color"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["range4Color"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["frame"] = {
				["height"] = 39,
				["width"] = 84,
			},
			["range2Color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["pvp"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 33,
				["y"] = 1,
				["x"] = -3,
				["height"] = 33,
				["frameLevel"] = 1,
				["texture"] = "Interface\\ChatFrame\\ChatFrameBackground",
			},
		},
		["Buff"] = {
			["numberBuffs"] = 3,
			["borderType"] = 1,
			["voiceColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["range3ColorUseClassColor"] = 1,
			["rageColor"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["oorColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["range3Color"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["range1ColorUseClassColor"] = 1,
			["tankedColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["warnSameTarget"] = 1,
			["range4Color"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["healthBar"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["width"] = 73,
				["y"] = -18,
				["soloHeight"] = 17,
				["hide"] = 1,
				["statusBarAlpha"] = 0.25,
				["height"] = 12,
				["frameLevel"] = 1,
				["x"] = -3,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["keybindings"] = {
				[1] = {
					["type"] = 2,
				},
				[2] = {
					["type"] = 1,
				},
				[3] = {
					["type"] = 3,
					["attack"] = 1,
				},
				[4] = {
					["type"] = 5,
				},
				[5] = {
					["type"] = 4,
				},
				[6] = {
					["type"] = 1,
				},
				[7] = {
					["type"] = 6,
				},
				[8] = {
					["type"] = 1,
				},
			},
			["warningColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["enableBuffToggle"] = 1,
			["pvp"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 33,
				["y"] = 1,
				["x"] = -3,
				["height"] = 33,
				["hide"] = 1,
				["frameLevel"] = 1,
				["texture"] = "Interface\\ChatFrame\\ChatFrameBackground",
			},
			["farColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["playAggroLost"] = 1,
			["focusColor"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.25,
			},
			["buffs"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["growth"] = 1,
				["width"] = 13,
				["y"] = -1,
				["x"] = -1,
				["height"] = 13,
				["frameLevel"] = 4,
			},
			["hoverColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["mediumColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["energyColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["range1Color"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["showAggroGain"] = 1,
			["buffCount"] = {
				["outline"] = 1,
				["point"] = "BOTTOMRIGHT",
				["shadowX"] = 0,
				["justifyV"] = "BOTTOM",
				["justifyH"] = "RIGHT",
				["shadowY"] = 0,
				["attach"] = "Frame",
				["relative"] = "BOTTOMRIGHT",
				["fontHeight"] = 10,
				["width"] = 12,
				["y"] = 1,
				["x"] = 0,
				["height"] = 12,
				["layer"] = 1,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["pvpColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["backgroundType"] = 1,
			["range"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 4,
				["y"] = -2,
				["x"] = 2,
				["height"] = 11,
				["frameLevel"] = 2,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["health"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["x"] = 0,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["showBuffs"] = 1,
			["targetColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["showAggroLost"] = 1,
			["healthColor"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["maColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
			["healthType"] = 1,
			["voice"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 20,
				["y"] = 2,
				["x"] = -1,
				["height"] = 20,
				["hide"] = 1,
				["frameLevel"] = 3,
				["texture"] = "Interface\\GossipFrame\\GossipGossipIcon",
			},
			["mana"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["x"] = 0,
			},
			["showTargetsTarget"] = 1,
			["manaBar"] = {
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "BOTTOM",
				["width"] = 73,
				["statusBarAlpha"] = 0.25,
				["x"] = 0,
				["hide"] = 1,
				["height"] = 4,
				["y"] = -1,
				["point"] = "TOP",
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["manaColor"] = {
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 1,
			},
			["status"] = {
				["point"] = "CENTER",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "CENTER",
				["fontHeight"] = 14,
				["width"] = 70,
				["y"] = -6,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["x"] = 0,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
			},
			["nameColorType"] = 7,
			["playAggroGain"] = 1,
			["name"] = {
				["outline"] = 1,
				["point"] = "LEFT",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "LEFT",
				["shadowY"] = 0,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "LEFT",
				["fontHeight"] = 13,
				["width"] = 79,
				["y"] = 0,
				["x"] = 6,
				["height"] = 13,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["debuffColorAlpha"] = 0.25,
			["nameColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["closeColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["healthColorType"] = 1,
			["targetIcon"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 16,
				["y"] = 0,
				["x"] = 0,
				["height"] = 16,
				["hide"] = 1,
				["frameLevel"] = 2,
				["texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["range2ColorUseClassColor"] = 1,
			["frame"] = {
				["height"] = 15,
				["width"] = 84,
			},
			["range2Color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["manaType"] = 1,
		},
		["Tank Monitor"] = {
			["numberBuffs"] = 6,
			["borderType"] = 5,
			["voiceColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["range3ColorUseClassColor"] = 1,
			["rageColor"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["oorColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["range3Color"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["range1ColorUseClassColor"] = 1,
			["tankedColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["warnSameTarget"] = 1,
			["range4Color"] = {
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["showAggroGain"] = 1,
			["showDebuffs"] = 1,
			["showBuffs"] = 1,
			["warningColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0,
				["b"] = 0,
			},
			["keybindings"] = {
				[1] = {
					["type"] = 2,
				},
				[2] = {
					["type"] = 1,
				},
				[3] = {
					["type"] = 3,
					["attack"] = 1,
				},
				[4] = {
					["type"] = 5,
				},
				[5] = {
					["type"] = 4,
				},
				[6] = {
					["type"] = 1,
				},
				[7] = {
					["type"] = 6,
				},
				[8] = {
					["type"] = 1,
				},
			},
			["enableBuffToggle"] = 1,
			["farColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0,
			},
			["manaType"] = 1,
			["focusColor"] = {
				["r"] = 1,
				["g"] = 0.5,
				["b"] = 0.25,
			},
			["buffs"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["growth"] = 1,
				["width"] = 13,
				["y"] = -3,
				["x"] = -3,
				["height"] = 13,
				["frameLevel"] = 4,
			},
			["hoverColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["pvp"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 33,
				["y"] = 1,
				["x"] = -3,
				["height"] = 33,
				["frameLevel"] = 1,
				["texture"] = "Interface\\ChatFrame\\ChatFrameBackground",
			},
			["energyColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["range1Color"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["playAggroLost"] = 1,
			["buffCount"] = {
				["outline"] = 1,
				["point"] = "BOTTOMRIGHT",
				["shadowX"] = 0,
				["justifyV"] = "BOTTOM",
				["justifyH"] = "RIGHT",
				["shadowY"] = 0,
				["attach"] = "Frame",
				["relative"] = "BOTTOMRIGHT",
				["fontHeight"] = 10,
				["width"] = 12,
				["y"] = 1,
				["x"] = 0,
				["height"] = 12,
				["layer"] = 1,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["pvpColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["backgroundType"] = 7,
			["range"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 4,
				["y"] = -18,
				["x"] = 3,
				["height"] = 17,
				["frameLevel"] = 2,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["healthBar"] = {
				["point"] = "TOPRIGHT",
				["attach"] = "Frame",
				["relative"] = "TOPRIGHT",
				["width"] = 73,
				["y"] = -18,
				["soloHeight"] = 17,
				["statusBarAlpha"] = 0.25,
				["height"] = 12,
				["frameLevel"] = 1,
				["x"] = -3,
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["health"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["x"] = 0,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["targetColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["showAggroLost"] = 1,
			["healthColor"] = {
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["maColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 0,
				["b"] = 1,
			},
			["healthType"] = 1,
			["voice"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 20,
				["y"] = 2,
				["x"] = -1,
				["height"] = 20,
				["frameLevel"] = 3,
				["texture"] = "Interface\\GossipFrame\\GossipGossipIcon",
			},
			["mana"] = {
				["outline"] = 1,
				["point"] = "TOP",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["hide"] = 1,
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "TOP",
				["fontHeight"] = 10,
				["width"] = 70,
				["y"] = 0,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["x"] = 0,
			},
			["showTargetsTarget"] = 1,
			["manaBar"] = {
				["frameLevel"] = 1,
				["attach"] = "HealthBar",
				["relative"] = "BOTTOM",
				["width"] = 73,
				["statusBarAlpha"] = 0.25,
				["x"] = 0,
				["height"] = 4,
				["y"] = -1,
				["point"] = "TOP",
				["texture"] = "Interface\\AddOns\\OneRaid4\\textures\\bg.tga",
			},
			["manaColor"] = {
				["r"] = 0,
				["g"] = 0.6,
				["b"] = 1,
			},
			["status"] = {
				["point"] = "CENTER",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "CENTER",
				["shadowY"] = 0,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "CENTER",
				["fontHeight"] = 14,
				["width"] = 70,
				["y"] = -6,
				["font"] = "Fonts\\FRIZQT__.ttf",
				["height"] = 12,
				["x"] = 0,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
			},
			["nameColorType"] = 7,
			["playAggroGain"] = 1,
			["name"] = {
				["outline"] = 1,
				["point"] = "TOPLEFT",
				["shadowX"] = 0,
				["justifyV"] = "MIDDLE",
				["justifyH"] = "LEFT",
				["shadowY"] = 0,
				["frameLevel"] = 1,
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["fontHeight"] = 13,
				["width"] = 71,
				["y"] = -3,
				["x"] = 13,
				["height"] = 12,
				["shadowColor"] = {
					["r"] = 0,
					["g"] = 0,
					["b"] = 0,
				},
				["font"] = "Fonts\\FRIZQT__.ttf",
			},
			["debuffColorAlpha"] = 0.25,
			["nameColor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["closeColor"] = {
				["a"] = 0.25,
				["r"] = 0,
				["g"] = 1,
				["b"] = 0,
			},
			["healthColorType"] = 1,
			["targetIcon"] = {
				["point"] = "TOPLEFT",
				["attach"] = "Frame",
				["relative"] = "TOPLEFT",
				["width"] = 16,
				["y"] = 0,
				["x"] = 0,
				["height"] = 16,
				["frameLevel"] = 2,
				["texture"] = "Interface\\TargetingFrame\\UI-RaidTargetingIcons",
			},
			["range2ColorUseClassColor"] = 1,
			["frame"] = {
				["height"] = 39,
				["width"] = 84,
			},
			["range2Color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["mediumColor"] = {
				["a"] = 0.25,
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
		},
	},
};