if (GetLocale() == "zhCN") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "德鲁伊";
	PERL_LOCALIZED_HUNTER = "猎人";
	PERL_LOCALIZED_MAGE = "法师";
	PERL_LOCALIZED_PALADIN = "圣骑士";
	PERL_LOCALIZED_PRIEST = "牧师";
	PERL_LOCALIZED_ROGUE = "盗贼";
	PERL_LOCALIZED_SHAMAN = "萨满祭司";
	PERL_LOCALIZED_WARLOCK = "术士";
	PERL_LOCALIZED_WARRIOR = "战士";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "平民";
	PERL_LOCALIZED_CREATURE = "生物";
	PERL_LOCALIZED_NOTSPECIFIED = "非特定的";

	-- Debuff Types
	PERL_LOCALIZED_BUFF_CURSE = "诅咒";
	PERL_LOCALIZED_BUFF_DISEASE = "疾病";
	PERL_LOCALIZED_BUFF_MAGIC = "魔法";
	PERL_LOCALIZED_BUFF_POISON = "中毒";

	-- Status Types
	PERL_LOCALIZED_STATUS_DEAD = "死亡";
	PERL_LOCALIZED_STATUS_FEIGNDEATH = "假死";
	PERL_LOCALIZED_STATUS_OFFLINE = "离线";
	PERL_LOCALIZED_STATUS_RESURRECTED = "复活";
	PERL_LOCALIZED_STATUS_SS_AVAILABLE = "灵魂已保存";

	-- Perl ArcaneBar Strings
	PERL_LOCALIZED_ARCANEBAR_CHANNELING = "正在引导";

	-- Perl Config Strings
	PERL_LOCALIZED_CONFIG_MINIMAP_LOCK = "点击将锁定所有框体";
	PERL_LOCALIZED_CONFIG_MINIMAP_UNLOCK = "点击将解锁所有框体";

	-- Perl Player Strings
	PERL_LOCALIZED_PLAYER_GROUP = "小队";
	PERL_LOCALIZED_PLAYER_LEVEL_SEVENTY = "70级";
	PERL_LOCALIZED_PLAYER_NOMORE_EXPERIENCE = "你不能再得到经验了!";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_ONE = "仇恨";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_TWO = "敌对";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_THREE = "冷淡";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FOUR = "中立";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FIVE = "友善";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SIX = "尊敬";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SEVEN = "崇敬";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_EIGHT = "崇拜";
	PERL_LOCALIZED_PLAYER_NO_REPUTATION = "按(u)打开声望窗口,选择一个阵营作为声望条.";
	PERL_LOCALIZED_PLAYER_SELECT_REPUTATION = "声望条(还没指定)";
	PERL_LOCALIZED_PLAYER_UNRANKED = "你从未参加过战斗没有军衔荣誉.";

	-- Perl Target Strings
	PERL_LOCALIZED_TARGET_BOSS = "世界精英";
	PERL_LOCALIZED_TARGET_ELITE = "精英";
	PERL_LOCALIZED_TARGET_RARE = "稀有";
	PERL_LOCALIZED_TARGET_RAREELITE = "稀有精英";
	PERL_LOCALIZED_TARGET_FIRE_VULNERABILITY = "火焰易伤";
	PERL_LOCALIZED_TARGET_SHADOW_VULNERABILITY = "暗影易伤";
	PERL_LOCALIZED_TARGET_SUNDER_ARMOR = "破甲";

	-- Perl Target Target Strings
	PERL_LOCALIZED_TARGET_TARGET_CHANGED_TO_YOU = " 的目标已经变成你!";

	-- Perl Config Key Binging Strings
	BINDING_HEADER_PERLCONFIG = PERL_LOCALIZED_NAME;
	BINDING_NAME_TOGGLEOPTIONS = "Toggle选项菜单";

	-- Perl Raid Key Binging Strings
	BINDING_HEADER_PERLRAID = "Perl Raid";
	BINDING_NAME_SHOWHIDE = "显示/隐藏 团队框体";
	BINDING_NAME_TOGGLECLASS = "Toggle 队伍/职业 分类排列";
end