if (GetLocale() == "deDE") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "Druide";
	PERL_LOCALIZED_HUNTER = "J\195\164ger";
	PERL_LOCALIZED_MAGE = "Magier";
	PERL_LOCALIZED_PALADIN = "Paladin";
	PERL_LOCALIZED_PRIEST = "Priester";
	PERL_LOCALIZED_ROGUE = "Schurke";
	PERL_LOCALIZED_SHAMAN = "Schamane";
	PERL_LOCALIZED_WARLOCK = "Hexenmeister";
	PERL_LOCALIZED_WARRIOR = "Krieger";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "Zivilist";
	PERL_LOCALIZED_CREATURE = "Kreatur";
	PERL_LOCALIZED_NOTSPECIFIED = "Nicht spezifiziert";

	-- Debuff Types
	PERL_LOCALIZED_BUFF_CURSE = "Fluch";
	PERL_LOCALIZED_BUFF_DISEASE = "Krankheit";
	PERL_LOCALIZED_BUFF_MAGIC = "Magie";
	PERL_LOCALIZED_BUFF_POISON = "Gift";

	-- Status Types
	PERL_LOCALIZED_STATUS_DEAD = "Tot";
	PERL_LOCALIZED_STATUS_FEIGNDEATH = "Totstellen";
	PERL_LOCALIZED_STATUS_OFFLINE = "Offline";
	PERL_LOCALIZED_STATUS_RESURRECTED = "Wiederbelebt";
	PERL_LOCALIZED_STATUS_SS_AVAILABLE = "SS verf\195\188gbar";

	-- Perl ArcaneBar Strings
	PERL_LOCALIZED_ARCANEBAR_CHANNELING = "Channeling";

	-- Perl Config Strings
	PERL_LOCALIZED_CONFIG_MINIMAP_LOCK = "Rechts-Klick um alle Frames zu fixieren";
	PERL_LOCALIZED_CONFIG_MINIMAP_UNLOCK = "Rechts-Klick um alle Frames freigeben";

	-- Perl Player Strings
	PERL_LOCALIZED_PLAYER_GROUP = "Gruppe ";
	PERL_LOCALIZED_PLAYER_LEVEL_SEVENTY = "Level 70";
	PERL_LOCALIZED_PLAYER_NOMORE_EXPERIENCE = "Du kannst keine Erfahrung mehr erhalten!";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_ONE = "Hasserf\195\188llt";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_TWO = "Feindselig";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_THREE = "Unfreundlich";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FOUR = "Neutral";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FIVE = "Freundlich";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SIX = "Wohlwollend";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SEVEN = "Respektvoll";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_EIGHT = "Ehrf\195\188rchtig";
	PERL_LOCALIZED_PLAYER_NO_REPUTATION = "Es wurde kein Ruf ausgew\195\164hlt.";
	PERL_LOCALIZED_PLAYER_SELECT_REPUTATION = "W\195\164hle einen Ruf";
	PERL_LOCALIZED_PLAYER_UNRANKED = "Du bist Unranked.";

	-- Perl Target Strings
	PERL_LOCALIZED_TARGET_BOSS = "Boss";
	PERL_LOCALIZED_TARGET_ELITE = "Elite";
	PERL_LOCALIZED_TARGET_RARE = "Rar";
	PERL_LOCALIZED_TARGET_RAREELITE = "Rar+";
	PERL_LOCALIZED_TARGET_FIRE_VULNERABILITY = "Feuerverwundbarkeit";
	PERL_LOCALIZED_TARGET_SHADOW_VULNERABILITY = "Schattenverwundbarkeit";
	PERL_LOCALIZED_TARGET_SUNDER_ARMOR = "R\195\188stungszerrei\195\159en";

	-- Perl Target Target Strings
	PERL_LOCALIZED_TARGET_TARGET_CHANGED_TO_YOU = " hat sein Ziel zu dir gewechselt";

	-- Perl Config Key Binging Strings
	BINDING_HEADER_PERLCONFIG = PERL_LOCALIZED_NAME;
	BINDING_NAME_TOGGLEOPTIONS = "Optionen Men\195\188 ein-/ausschalten";

	-- Perl Raid Key Binging Strings
	BINDING_HEADER_PERLRAID = "Perl Raid";
	BINDING_NAME_SHOWHIDE = "Zeige/Verstecke Raid Frames";
	BINDING_NAME_TOGGLECLASS = "Wechsel Gruppen/Klassen Sortierung";
end