if (GetLocale() == "zhTW") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "德魯伊";
	PERL_LOCALIZED_HUNTER = "獵人";
	PERL_LOCALIZED_MAGE = "法師";
	PERL_LOCALIZED_PALADIN = "聖騎士";
	PERL_LOCALIZED_PRIEST = "牧師";
	PERL_LOCALIZED_ROGUE = "盜賊";
	PERL_LOCALIZED_SHAMAN = "薩滿";
	PERL_LOCALIZED_WARLOCK = "術士";
	PERL_LOCALIZED_WARRIOR = "戰士";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "平民";
	PERL_LOCALIZED_CREATURE = "生物";
	PERL_LOCALIZED_NOTSPECIFIED = "非特定的";

	-- Debuff Types
	PERL_LOCALIZED_BUFF_CURSE = "詛咒";
	PERL_LOCALIZED_BUFF_DISEASE = "疾病";
	PERL_LOCALIZED_BUFF_MAGIC = "魔法";
	PERL_LOCALIZED_BUFF_POISON = "中毒";

	-- Status Types
	PERL_LOCALIZED_STATUS_DEAD = "死亡";
	PERL_LOCALIZED_STATUS_FEIGNDEATH = "假死";
	PERL_LOCALIZED_STATUS_OFFLINE = "離線";
	PERL_LOCALIZED_STATUS_RESURRECTED = "復活";
	PERL_LOCALIZED_STATUS_SS_AVAILABLE = "可以利用的SS";

	-- Perl ArcaneBar Strings
	PERL_LOCALIZED_ARCANEBAR_CHANNELING = "Channeling";

	-- Perl Config Strings
	PERL_LOCALIZED_CONFIG_MINIMAP_LOCK = "點擊將鎖定所有框體";
	PERL_LOCALIZED_CONFIG_MINIMAP_UNLOCK = "點擊將解鎖所有框體";

	-- Perl Player Strings
	PERL_LOCALIZED_PLAYER_GROUP = "小隊";
	PERL_LOCALIZED_PLAYER_LEVEL_SEVENTY = "70級";
	PERL_LOCALIZED_PLAYER_NOMORE_EXPERIENCE = "你不能再得到經驗了!";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_ONE = "仇恨";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_TWO = "敵對";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_THREE = "不友好";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FOUR = "中立";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FIVE = "友好";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SIX = "尊敬";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SEVEN = "崇敬";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_EIGHT = "崇拜";
	PERL_LOCALIZED_PLAYER_NO_REPUTATION = "按(u)打開聲望窗口,選擇一個陣營作為聲望條.";
	PERL_LOCALIZED_PLAYER_SELECT_REPUTATION = "聲望條(還沒指定)";
	PERL_LOCALIZED_PLAYER_UNRANKED = "你從未參加過戰鬥沒有軍階榮譽.";

	-- Perl Target Strings
	PERL_LOCALIZED_TARGET_BOSS = "世界精英";
	PERL_LOCALIZED_TARGET_ELITE = "精英";
	PERL_LOCALIZED_TARGET_RARE = "稀有";
	PERL_LOCALIZED_TARGET_RAREELITE = "稀有精英";
	PERL_LOCALIZED_TARGET_FIRE_VULNERABILITY = "火焰易傷";
	PERL_LOCALIZED_TARGET_SHADOW_VULNERABILITY = "暗影易傷";
	PERL_LOCALIZED_TARGET_SUNDER_ARMOR = "破甲";

	-- Perl Target Target Strings
	PERL_LOCALIZED_TARGET_TARGET_CHANGED_TO_YOU = " 的目標已經變成你!";

	-- Perl Config Key Binging Strings
	BINDING_HEADER_PERLCONFIG = PERL_LOCALIZED_NAME;
	BINDING_NAME_TOGGLEOPTIONS = "Toggle選項目錄";

	-- Perl Raid Key Binging Strings
	BINDING_HEADER_PERLRAID = "Perl Raid";
	BINDING_NAME_SHOWHIDE = "顯示/隱藏 團隊框";
	BINDING_NAME_TOGGLECLASS = "Toggle 隊伍/職業 分類排列";
end