if (GetLocale() == "koKR") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "드루이드";
	PERL_LOCALIZED_HUNTER = "사냥꾼";
	PERL_LOCALIZED_MAGE = "마법사";
	PERL_LOCALIZED_PALADIN = "성기사";
	PERL_LOCALIZED_PRIEST = "사제";
	PERL_LOCALIZED_ROGUE = "도적";
	PERL_LOCALIZED_SHAMAN = "주술사";
	PERL_LOCALIZED_WARLOCK = "흑마법사";
	PERL_LOCALIZED_WARRIOR = "전사";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "민간인";
	PERL_LOCALIZED_CREATURE = "동물";
	PERL_LOCALIZED_NOTSPECIFIED = "무엇인가";

	-- Debuff Types
	PERL_LOCALIZED_BUFF_CURSE = "저주";
	PERL_LOCALIZED_BUFF_DISEASE = "질병";
	PERL_LOCALIZED_BUFF_MAGIC = "마법";
	PERL_LOCALIZED_BUFF_POISON = "독";

	-- Status Types
	PERL_LOCALIZED_STATUS_DEAD = "죽음";
	PERL_LOCALIZED_STATUS_FEIGNDEATH = "죽은척하기";
	PERL_LOCALIZED_STATUS_OFFLINE = "오프라인";
	PERL_LOCALIZED_STATUS_RESURRECTED = "부활받음";
	PERL_LOCALIZED_STATUS_SS_AVAILABLE = "영혼석 있음";

	-- Perl ArcaneBar Strings
	PERL_LOCALIZED_ARCANEBAR_CHANNELING = "채널링";

	-- Perl Config Strings
	PERL_LOCALIZED_CONFIG_MINIMAP_LOCK = "오른쪽 클릭 : 잠금";
	PERL_LOCALIZED_CONFIG_MINIMAP_UNLOCK = "오른쪽 클릭 : 풀림";

	-- Perl Player Strings
	PERL_LOCALIZED_PLAYER_GROUP = "파티 ";
	PERL_LOCALIZED_PLAYER_LEVEL_SEVENTY = "70 레벨";
	PERL_LOCALIZED_PLAYER_NOMORE_EXPERIENCE = "더 이상 경험치를 얻을 수 없습니다!";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_ONE = "매우 적대적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_TWO = "적대적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_THREE = "약간 적대적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FOUR = "중립적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FIVE = "약간 우호적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SIX = "우호적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SEVEN = "매우 우호적";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_EIGHT = "확고한 동맹";
	PERL_LOCALIZED_PLAYER_NO_REPUTATION = "선택된 평판이 없습니다.";
	PERL_LOCALIZED_PLAYER_SELECT_REPUTATION = "평판을 선택하세요";
	PERL_LOCALIZED_PLAYER_UNRANKED = "당신은 계급|1이;가; 없습니다.";

	-- Perl Target Strings
	PERL_LOCALIZED_TARGET_BOSS = "우두머리";
	PERL_LOCALIZED_TARGET_ELITE = "정예";
	PERL_LOCALIZED_TARGET_RARE = "희귀";
	PERL_LOCALIZED_TARGET_RAREELITE = "희귀+";
	PERL_LOCALIZED_TARGET_FIRE_VULNERABILITY = "화염 저항력 약화";
	PERL_LOCALIZED_TARGET_SHADOW_VULNERABILITY = "암흑 저항력 약화";
	PERL_LOCALIZED_TARGET_SUNDER_ARMOR = "방어구 가르기";

	-- Perl Target Target Strings
	PERL_LOCALIZED_TARGET_TARGET_CHANGED_TO_YOU = "|1이;가; 당신을 타겟으로 합니다!";

	-- Perl Config Key Binging Strings
	BINDING_HEADER_PERLCONFIG = PERL_LOCALIZED_NAME;
	BINDING_NAME_TOGGLEOPTIONS = "설정창 토글";

	-- Perl Raid Key Binging Strings
	BINDING_HEADER_PERLRAID = "Perl Raid";
	BINDING_NAME_SHOWHIDE = "공격대 창 표시/숨김";
	BINDING_NAME_TOGGLECLASS = "그룹/직업 정렬 토글";
end