if (GetLocale() == "frFR") then
	-- Class Names
	PERL_LOCALIZED_DRUID = "Druide";
	PERL_LOCALIZED_HUNTER = "Chasseur";
	PERL_LOCALIZED_MAGE = "Mage";
	PERL_LOCALIZED_PALADIN = "Paladin";
	PERL_LOCALIZED_PRIEST = "Pr\195\170tre";
	PERL_LOCALIZED_ROGUE = "Voleur";
	PERL_LOCALIZED_SHAMAN = "Chaman";
	PERL_LOCALIZED_WARLOCK = "D\195\169moniste";
	PERL_LOCALIZED_WARRIOR = "Guerrier";

	-- Creature Types
	PERL_LOCALIZED_CIVILIAN = "Civil";
	PERL_LOCALIZED_CREATURE = "Cr\195\169ature";
	PERL_LOCALIZED_NOTSPECIFIED = "Non indiqu\195\169";

	-- Debuff Types
	PERL_LOCALIZED_BUFF_CURSE = "Mal\195\169diction";
	PERL_LOCALIZED_BUFF_DISEASE = "Maladie";
	PERL_LOCALIZED_BUFF_MAGIC = "Magique";
	PERL_LOCALIZED_BUFF_POISON = "Poison";

	-- Status Types
	PERL_LOCALIZED_STATUS_DEAD = "Mort";
	PERL_LOCALIZED_STATUS_FEIGNDEATH = "Feint la Mort";
	PERL_LOCALIZED_STATUS_OFFLINE = "Offline";
	PERL_LOCALIZED_STATUS_RESURRECTED = "R\195\169ssucit\195\169";
	PERL_LOCALIZED_STATUS_SS_AVAILABLE = "SS Available";

	-- Perl ArcaneBar Strings
	PERL_LOCALIZED_ARCANEBAR_CHANNELING = "Channeling";

	-- Perl Config Strings
	PERL_LOCALIZED_CONFIG_MINIMAP_LOCK = "Clic-droit VERROUILLERA tous cadres";
	PERL_LOCALIZED_CONFIG_MINIMAP_UNLOCK = "Clic-droit DEVERROUILLERA tous cadres";

	-- Perl Player Strings
	PERL_LOCALIZED_PLAYER_GROUP = "Groupe ";
	PERL_LOCALIZED_PLAYER_LEVEL_SEVENTY = "Niveau 70";
	PERL_LOCALIZED_PLAYER_NOMORE_EXPERIENCE = "Vous ne pouvez plus gagner d\' experience!";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_ONE = "D\195\169test\195\169";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_TWO = "Hostile";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_THREE = "Inamical";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FOUR = "Neutre";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_FIVE = "Amical";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SIX = "Honor\195\169";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_SEVEN = "R\195\169v\195\169r\195\169";
	PERL_LOCALIZED_PLAYER_REACTIONNAME_EIGHT = "Exalt\195\169";
	PERL_LOCALIZED_PLAYER_NO_REPUTATION = "Il n\'y a pas de r\195\169putation trouv\195\169.";
	PERL_LOCALIZED_PLAYER_SELECT_REPUTATION = "S\195\169lectionner une R\195\169putation";
	PERL_LOCALIZED_PLAYER_UNRANKED = "Vous \195\170tes pas class\195\169.";

	-- Perl Target Strings
	PERL_LOCALIZED_TARGET_BOSS = "Boss";
	PERL_LOCALIZED_TARGET_ELITE = "Elite";
	PERL_LOCALIZED_TARGET_RARE = "Rare";
	PERL_LOCALIZED_TARGET_RAREELITE = "Rare+";
	PERL_LOCALIZED_TARGET_FIRE_VULNERABILITY = "Vuln\195\169rable au feu";
	PERL_LOCALIZED_TARGET_SHADOW_VULNERABILITY = "Vuln\195\169rable a l\'ombre";
	PERL_LOCALIZED_TARGET_SUNDER_ARMOR = "S\195\169parer l\'armure";

	-- Perl Target Target Strings
	PERL_LOCALIZED_TARGET_TARGET_CHANGED_TO_YOU = " vous cible !!!";

	-- Perl Config Key Binging Strings
	BINDING_HEADER_PERLCONFIG = PERL_LOCALIZED_NAME;
	BINDING_NAME_TOGGLEOPTIONS = "Afficher le menu d\'options ";

	-- Perl Raid Key Binging Strings
	BINDING_HEADER_PERLRAID = "Perl Raid";
	BINDING_NAME_SHOWHIDE = "Afficher/Cacher les cadres du Raid";
	BINDING_NAME_TOGGLECLASS = "Classer par Groupes/Classes";
end