DEFENSETRACKER_STRINGS_MODVERSION = "2.02";
DEFENSETRACKER_STRINGS_MODNAME = "Infobar: Defense Tracker";
DEFENSETRACKER_STRINGS_MODDESC = "Summarizes WorldDef spam";
DEFENSETRACKER_STRINGS_BARFRAMENAME = "DefenseTracker";

DEFENSETRACKER_STRINGS_NEWZONE1 = "DefenseTracker: New subzone found ";
DEFENSETRACKER_STRINGS_NEWZONE2 = ", check your SavedVariables.lua file and upload the IB_Defense_newSubzones variable block to the forum!";

DEFENSETRACKER_STRINGS_WDCHANNAME = "WorldDefense";
DEFENSETRACKER_STRINGS_LDCHANNAME = "LocalDefense";

DEFENSETRACKER_STRINGS_ATTACKTEXT = "1 Attack";
DEFENSETRACKER_STRINGS_ATTACKSTEXT = " Attacks";
DEFENSETRACKER_STRINGS_NOATTACKS = "No Attacks";
DEFENSETRACKER_STRINGS_SECONDS = " sec";
DEFENSETRACKER_STRINGS_MINUTES = " min";
DEFENSETRACKER_STRINGS_HOUR = " hour";
DEFENSETRACKER_STRINGS_SZTIMETITLE = "Most Recently Attacked Subzones"
DEFENSETRACKER_STRINGS_ZTIMETITLE = "Most Recently Attacked Zones";
DEFENSETRACKER_STRINGS_SZFRQTITLE = "Most Frequently Attacked Subzones";
DEFENSETRACKER_STRINGS_ZFRQTITLE = "Most Frequently Attacked Zones";
DEFENSETRACKER_STRINGS_LOCALHEADER = "LOCAL: ";
DEFENSETRACKER_STRINGS_AGOENDER = " ago";
DEFENSETRACKER_STRINGS_UNKNOWNZONE = "Unknown Zone";


-- Strings for Titan Plugin --
TITAN_DEFENSE_STRINGS_MODNAME = "Titan Plugin - Defense Tracker";
TITAN_DEFENSE_STRINGS_MODDESC = "Defense Tracker plugin for Titan Panel";
TITAN_DEFENSE_STRINGS_BARFRAMENAME = "TitanPanelDefenseButton";
TITAN_DEFENSE_MENU_TEXT = "Defense Tracker"
TITAN_DEFENSE_TOOLTIP = "Defense Tracker"

-- Strings for Infobar Plugin --
IB_DEFENSE_STRINGS_MODNAME = "Infobar: Defense Tracker";
IB_DEFENSE_STRINGS_MODDESC = "Defense Tracker plugin for Infobar";
IB_DEFENSE_STRINGS_BARFRAMENAME = "IB_Defense";

if ( GetLocale() == "frFR" ) then

elseif ( GetLocale() == "deDE" ) then
	ZONE_UNDER_ATTACK = "|cffffff00Angriff auf: %s!|r";

	DEFENSETRACKER_STRINGS_WDCHANNAME = "WeltVerteidigung";
	DEFENSETRACKER_STRINGS_LDCHANNAME = "LokaleVerteidigung";
	
	DEFENSETRACKER_STRINGS_ATTACKTEXT = "Ein Angriff";
	DEFENSETRACKER_STRINGS_ATTACKSTEXT = " Angriffe";
	DEFENSETRACKER_STRINGS_NOATTACKS = "Kein Angriff";
	
	DEFENSETRACKER_STRINGS_SECONDS = " Sek";
	DEFENSETRACKER_STRINGS_MINUTES = " Min";
	DEFENSETRACKER_STRINGS_HOUR = " Std";

	DEFENSETRACKER_STRINGS_SZTIMETITLE = "Kürzlich angegriffene Subzonen"
	DEFENSETRACKER_STRINGS_ZTIMETITLE = "Kürzlich angegriffene Zonen";
	DEFENSETRACKER_STRINGS_SZFRQTITLE = "Am meisten angegriffene Subzonen";
	DEFENSETRACKER_STRINGS_ZFRQTITLE = "Am meisten angegriffene Zonen";
	DEFENSETRACKER_STRINGS_LOCALHEADER = "LOKAL: ";
	DEFENSETRACKER_STRINGS_AGOENDER = " her";
	DEFENSETRACKER_STRINGS_UNKNOWNZONE = "Unbekannte Zone";

end

DEFENSETRACKER_STRINGS_UNDERATTACK = string.gsub(ZONE_UNDER_ATTACK,'%%s','(.+)');
