lazyHunterLoad.metadata:updateRevisionFromKeyword("$Revision: 277 $")

function lazyHunterLoad.LoadHunterLocalization(locale)

   lazyHunterLocale.enUS.ACTION_TTS.aimed                = "Aimed Shot"
   lazyHunterLocale.enUS.ACTION_TTS.arcane               = "Arcane Shot"
   lazyHunterLocale.enUS.ACTION_TTS.aspectBeast          = "Aspect of the Beast"
   lazyHunterLocale.enUS.ACTION_TTS.aspectCheetah        = "Aspect of the Cheetah"
   lazyHunterLocale.enUS.ACTION_TTS.aspectHawk           = "Aspect of the Hawk"
   lazyHunterLocale.enUS.ACTION_TTS.aspectMonkey         = "Aspect of the Monkey"
   lazyHunterLocale.enUS.ACTION_TTS.aspectPack           = "Aspect of the Pack"
   lazyHunterLocale.enUS.ACTION_TTS.aspectWild           = "Aspect of the Wild"
   lazyHunterLocale.enUS.ACTION_TTS.eotb                 = "Eyes of the Beast"
   lazyHunterLocale.enUS.ACTION_TTS.beastLore            = "Beast Lore"
   lazyHunterLocale.enUS.ACTION_TTS.call                 = "Call Pet"
   lazyHunterLocale.enUS.ACTION_TTS.concussive           = "Concussive Shot"
   lazyHunterLocale.enUS.ACTION_TTS.counter              = "Counterattack"
   lazyHunterLocale.enUS.ACTION_TTS.deterrence           = "Deterrence"
   lazyHunterLocale.enUS.ACTION_TTS.disengage            = "Disengage"
   lazyHunterLocale.enUS.ACTION_TTS.dismiss              = "Dismiss Pet"
   lazyHunterLocale.enUS.ACTION_TTS.distract             = "Distracting Shot"
   lazyHunterLocale.enUS.ACTION_TTS.eagleEye             = "Eagle Eye"
   lazyHunterLocale.enUS.ACTION_TTS.explosiveTrap        = "Explosive Trap"
   lazyHunterLocale.enUS.ACTION_TTS.feed                 = "Feed Pet"
   lazyHunterLocale.enUS.ACTION_TTS.feign                = "Feign Death"
   lazyHunterLocale.enUS.ACTION_TTS.flare                = "Flare"
   lazyHunterLocale.enUS.ACTION_TTS.frostTrap            = "Frost Trap"
   lazyHunterLocale.enUS.ACTION_TTS.freezingTrap         = "Freezing Trap"
   lazyHunterLocale.enUS.ACTION_TTS.immolationTrap       = "Immolation Trap"
   lazyHunterLocale.enUS.ACTION_TTS.intimidate           = "Intimidation"
   lazyHunterLocale.enUS.ACTION_TTS.huntersMark          = "Hunter's Mark"
   lazyHunterLocale.enUS.ACTION_TTS.mend                 = "Mend Pet"
   lazyHunterLocale.enUS.ACTION_TTS.mongoose             = "Mongoose Bite"
   lazyHunterLocale.enUS.ACTION_TTS.multi                = "Multi-Shot"
   lazyHunterLocale.enUS.ACTION_TTS.raptor               = "Raptor Strike"
   lazyHunterLocale.enUS.ACTION_TTS.rapidFire            = "Rapid Fire"
   lazyHunterLocale.enUS.ACTION_TTS.revive               = "Revive Pet"
   lazyHunterLocale.enUS.ACTION_TTS.scare                = "Scare Beast"
   lazyHunterLocale.enUS.ACTION_TTS.scatter              = "Scatter Shot"
   lazyHunterLocale.enUS.ACTION_TTS.scorpid              = "Scorpid Sting"
   lazyHunterLocale.enUS.ACTION_TTS.serpent              = "Serpent Sting"
   lazyHunterLocale.enUS.ACTION_TTS.tame                 = "Tame Beast"
   lazyHunterLocale.enUS.ACTION_TTS.trackBeasts          = "Track Beasts"
   lazyHunterLocale.enUS.ACTION_TTS.trackDemons          = "Track Demons"
   lazyHunterLocale.enUS.ACTION_TTS.trackDragonkin       = "Track Dragonkin"
   lazyHunterLocale.enUS.ACTION_TTS.trackElementals      = "Track Elementals"
   lazyHunterLocale.enUS.ACTION_TTS.trackGiants          = "Track Giants"
   lazyHunterLocale.enUS.ACTION_TTS.trackHidden          = "Track Hidden"
   lazyHunterLocale.enUS.ACTION_TTS.trackHumanoids       = "Track Humanoids"
   lazyHunterLocale.enUS.ACTION_TTS.trackUndead          = "Track Undead"
   lazyHunterLocale.enUS.ACTION_TTS.train                = "Beast Training"
   lazyHunterLocale.enUS.ACTION_TTS.tranquilizing        = "Tranquilizing Shot"
   lazyHunterLocale.enUS.ACTION_TTS.trueshot             = "Trueshot Aura"
   lazyHunterLocale.enUS.ACTION_TTS.viper                = "Viper Sting"
   lazyHunterLocale.enUS.ACTION_TTS.volley               = "Volley"
   lazyHunterLocale.enUS.ACTION_TTS.wingClip             = "Wing Clip"
   lazyHunterLocale.enUS.ACTION_TTS.bestialWrath         = "Bestial Wrath"
   lazyHunterLocale.enUS.ACTION_TTS.wyvern               = "Wyvern Sting"

   lazyHunterLocale.enUS.ACTION_TTS.petBite              = "Bite"
   lazyHunterLocale.enUS.ACTION_TTS.petBreath            = "Lightning Breath"
   lazyHunterLocale.enUS.ACTION_TTS.petCharge            = "Charge"
   lazyHunterLocale.enUS.ACTION_TTS.petClaw              = "Claw"
   lazyHunterLocale.enUS.ACTION_TTS.petCower             = "Cower"
   lazyHunterLocale.enUS.ACTION_TTS.petDash              = "Dash"
   lazyHunterLocale.enUS.ACTION_TTS.petDive              = "Dive"
   lazyHunterLocale.enUS.ACTION_TTS.petGrowl             = "Growl"
   lazyHunterLocale.enUS.ACTION_TTS.petHowl              = "Furious Howl"
   lazyHunterLocale.enUS.ACTION_TTS.petPoison            = "Scorpid Poison"
   lazyHunterLocale.enUS.ACTION_TTS.petProwl             = "Prowl"
   lazyHunterLocale.enUS.ACTION_TTS.petScreech           = "Screech"
   lazyHunterLocale.enUS.ACTION_TTS.petShell             = "Shell Shield"
   lazyHunterLocale.enUS.ACTION_TTS.petStomp             = "Thunder Stomp"
   lazyHunterLocale.enUS.ACTION_TTS.petUnprowl           = "Stop Prowling"

   -- assume english, unless overridden below
   if (locale == "deDE") then -- German
      lazyHunterLocale.deDE.ACTION_TTS.beastLore         = "Wildtierkunde"
      lazyHunterLocale.deDE.ACTION_TTS.deterrence        = "Abschreckung"
      lazyHunterLocale.deDE.ACTION_TTS.scare             = "Wildtier \195\164ngstigen"
      lazyHunterLocale.deDE.ACTION_TTS.volley            = "Salve"
      lazyHunterLocale.deDE.ACTION_TTS.wingClip          = "Zurechtstutzen"

      lazyHunterLocale.deDE.ACTION_TTS.petBite           = "Bei\195\159en"
      lazyHunterLocale.deDE.ACTION_TTS.petCower          = "Ducken"
      lazyHunterLocale.deDE.ACTION_TTS.petGrowl          = "Knurren"

   elseif (locale == "frFR") then -- French
      lazyHunterLocale.frFR.ACTION_TTS.beastLore         = "Connaissance des b\195\170tes"
      lazyHunterLocale.frFR.ACTION_TTS.deterrence        = "Dissuasion"
      lazyHunterLocale.frFR.ACTION_TTS.scare             = "Effrayer une b\195\170te"
      lazyHunterLocale.frFR.ACTION_TTS.volley            = "Salve"
      lazyHunterLocale.frFR.ACTION_TTS.wingClip          = "Coupure d'ailes"

      lazyHunterLocale.frFR.ACTION_TTS.petBite           = "Morsure"
      lazyHunterLocale.frFR.ACTION_TTS.petCower          = "D\195\169robade"
      lazyHunterLocale.frFR.ACTION_TTS.petGrowl          = "Grondement"
   end
end

