BINDING_HEADER_TOTEMKEYS_BINDINGS = "Marsti CallOfElements Totem Keys";
BINDING_NAME_TOTEMKEYS_FIREMENU = "Fire totems";
BINDING_NAME_TOTEMKEYS_WATERMENU = "Water totems";
BINDING_NAME_TOTEMKEYS_EARTHMENU = "Earth totems";
BINDING_NAME_TOTEMKEYS_AIRMENU = "Air totems";
BINDING_NAME_TOTEMKEYS_TOTEM1 = "Totem #1";
BINDING_NAME_TOTEMKEYS_TOTEM2 = "Totem #2";
BINDING_NAME_TOTEMKEYS_TOTEM3 = "Totem #3";
BINDING_NAME_TOTEMKEYS_TOTEM4 = "Totem #4";
BINDING_NAME_TOTEMKEYS_TOTEM5 = "Totem #5";
BINDING_NAME_TOTEMKEYS_TOTEM6 = "Totem #6";
BINDING_NAME_TOTEMKEYS_TOTEM7 = "Totem #7";
BINDING_NAME_TOTEMKEYS_NOMENU = "Deselect totems";

TOTEMKEYS_ELEMENT_FIRE = "Fire";
TOTEMKEYS_ELEMENT_WATER = "Water";
TOTEMKEYS_ELEMENT_EARTH = "Earth";
TOTEMKEYS_ELEMENT_AIR = "Air";

TOTEMKEYS_NOT_THIS_ELEMENT = "Currently there is no %s totem available.";
TOTEMKEYS_NO_TOTEM = "%s totem #%d does not exist.";
TOTEMKEYS_NO_MENU = "You must first select a totem element.";

if (GetLocale() == "deDE") then
	BINDING_NAME_TOTEMKEYS_FIREMENU = "Feuertotems";
	BINDING_NAME_TOTEMKEYS_WATERMENU = "Wassertotems";
	BINDING_NAME_TOTEMKEYS_EARTHMENU = "Erdtotems";
	BINDING_NAME_TOTEMKEYS_AIRMENU = "Lufttotems";
	BINDING_NAME_TOTEMKEYS_TOTEM1 = "Totem #1";
	BINDING_NAME_TOTEMKEYS_TOTEM2 = "Totem #2";
	BINDING_NAME_TOTEMKEYS_TOTEM3 = "Totem #3";
	BINDING_NAME_TOTEMKEYS_TOTEM4 = "Totem #4";
	BINDING_NAME_TOTEMKEYS_TOTEM5 = "Totem #5";
	BINDING_NAME_TOTEMKEYS_TOTEM6 = "Totem #6";
	BINDING_NAME_TOTEMKEYS_TOTEM7 = "Totem #7";
	BINDING_NAME_TOTEMKEYS_NOMENU = "Totems abw\195\164hlen";

	TOTEMKEYS_ELEMENT_FIRE = "Feuer";
	TOTEMKEYS_ELEMENT_WATER = "Wasser";
	TOTEMKEYS_ELEMENT_EARTH = "Erde";
	TOTEMKEYS_ELEMENT_AIR = "Luft";

	TOTEMKEYS_NOT_THIS_ELEMENT = "Momentan ist kein %s-Totem vorhanden.";
	TOTEMKEYS_NO_TOTEM = "%s-Totem #%d existiert nicht.";
	TOTEMKEYS_NO_MENU = "Du musst zuerst eine Totemart w\195\164hlen.";
end
