-- Auto generated by WoWBench 1.11.0.a3 from "D:/Games/World of Warcraft/Interface/AddOns/Warrior/GUI/Fonts.xml" on 2006-07-20 21:11:38
local WOWB_XMLFILE="D:/Games/World of Warcraft/Interface/AddOns/Warrior/GUI/Fonts.xml";
local WOWB_XMLFILENOPATH="D:/Games/World of Warcraft/Interface/AddOns/Warrior/GUI/Fonts.xml";
local WOWB_TAG = { [0]={content=""} }
local WOWB_PARENTOBJECT = WOWB_RootFrame;
local xfpc = WOWB_XMLFileParserContext:New(WOWB_XMLFILE);

do -- <Ui ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=1
local WOWB_TAG = { [0]={  xmltag="Ui",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=1,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["xmlns"] ="http://www.blizzard.com/wow/ui/",
["xmlns:xsi"] ="http://www.w3.org/2001/XMLSchema-instance",
["xsi:schemaLocation"] ="http://www.blizzard.com/wow/ui/",
}};
WOWB_PARENT[0]["Ui"] = WOWB_TAG;
do -- <Font ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=4
local WOWB_TAG = { [0]={  xmltag="Font",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=4,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="WGUI_MasterFont",
["virtual"] ="true",
}};
if(not WOWB_ISVIRTUAL) then
  if(not WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME)) then
    bIgnored = true;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
local WOWB_PARENTOBJECT = nil;
local WOWB_ISVIRTUAL = true;
WOWB_InheritType(WOWB_TAG, WBClass_Font);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass_Font);

do -- <Shadow ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=5
local WOWB_TAG = { [0]={  xmltag="Shadow",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=5,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["Shadow"] = WOWB_TAG;
do -- <Offset ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=6
local WOWB_TAG = { [0]={  xmltag="Offset",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=6,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["Offset"] = WOWB_TAG;
do -- <AbsDimension ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=7
local WOWB_TAG = { [0]={  xmltag="AbsDimension",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=7,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["x"] =1,
["y"] =-1,
}};
WOWB_PARENT[0]["AbsDimension"] = WOWB_TAG;
end
WOWB_ParseXML_CompileScriptNode(xfpc:Recurse(WOWB_TAG), WOWB_TAG);end
do -- <Color ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=9
local WOWB_TAG = { [0]={  xmltag="Color",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=9,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["r"] =0,
["g"] =0,
["b"] =0,
}};
WOWB_PARENT[0]["Color"] = WOWB_TAG;
end
end
do -- <FontHeight ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=11
local WOWB_TAG = { [0]={  xmltag="FontHeight",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=11,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["FontHeight"] = WOWB_TAG;
do -- <AbsValue ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=12
local WOWB_TAG = { [0]={  xmltag="AbsValue",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=12,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["val"] =12,
}};
WOWB_PARENT[0]["AbsValue"] = WOWB_TAG;
end
end
end
do -- <Font ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=17
local WOWB_TAG = { [0]={  xmltag="Font",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=17,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="WGUI_LargeFont",
["inherts"] ="WGUI_MasterFont",
["font"] ="Interface\\AddOns\\Warrior\\Fonts\\WGUI_1.ttf",
["virtual"] ="true",
}};
if(not WOWB_ISVIRTUAL) then
  if(not WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME)) then
    bIgnored = true;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
local WOWB_PARENTOBJECT = nil;
local WOWB_ISVIRTUAL = true;
WOWB_InheritType(WOWB_TAG, WBClass_Font);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass_Font);

do -- <FontHeight ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=18
local WOWB_TAG = { [0]={  xmltag="FontHeight",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=18,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["FontHeight"] = WOWB_TAG;
do -- <AbsValue ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=19
local WOWB_TAG = { [0]={  xmltag="AbsValue",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=19,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["val"] =16,
}};
WOWB_PARENT[0]["AbsValue"] = WOWB_TAG;
end
end
end
do -- <Font ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=24
local WOWB_TAG = { [0]={  xmltag="Font",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=24,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="WGUI_NormalFont",
["inherts"] ="WGUI_MasterFont",
["font"] ="Interface\\AddOns\\Warrior\\Fonts\\WGUI_1.ttf",
["virtual"] ="true",
}};
if(not WOWB_ISVIRTUAL) then
  if(not WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME)) then
    bIgnored = true;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
local WOWB_PARENTOBJECT = nil;
local WOWB_ISVIRTUAL = true;
WOWB_InheritType(WOWB_TAG, WBClass_Font);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass_Font);

do -- <FontHeight ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=25
local WOWB_TAG = { [0]={  xmltag="FontHeight",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=25,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["FontHeight"] = WOWB_TAG;
do -- <AbsValue ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=26
local WOWB_TAG = { [0]={  xmltag="AbsValue",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=26,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["val"] =12,
}};
WOWB_PARENT[0]["AbsValue"] = WOWB_TAG;
end
end
end
do -- <Font ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=31
local WOWB_TAG = { [0]={  xmltag="Font",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=31,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="WGUI_SmallFont",
["inherts"] ="WGUI_MasterFont",
["font"] ="Interface\\AddOns\\Warrior\\Fonts\\WGUI_1.ttf",
["virtual"] ="true",
}};
if(not WOWB_ISVIRTUAL) then
  if(not WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME)) then
    bIgnored = true;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
local WOWB_PARENTOBJECT = nil;
local WOWB_ISVIRTUAL = true;
WOWB_InheritType(WOWB_TAG, WBClass_Font);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass_Font);

do -- <FontHeight ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=32
local WOWB_TAG = { [0]={  xmltag="FontHeight",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=32,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["FontHeight"] = WOWB_TAG;
do -- <AbsValue ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=33
local WOWB_TAG = { [0]={  xmltag="AbsValue",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=33,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["val"] =10,
}};
WOWB_PARENT[0]["AbsValue"] = WOWB_TAG;
end
end
end
do -- <Font ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=38
local WOWB_TAG = { [0]={  xmltag="Font",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=38,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["name"] ="WGUI_TinyFont",
["inherts"] ="WGUI_MasterFont",
["font"] ="Interface\\AddOns\\Warrior\\Fonts\\WGUI_1.ttf",
["virtual"] ="true",
}};
if(not WOWB_ISVIRTUAL) then
  if(not WOWB_ParseXML_FixObjectName(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_LASTOBJNAME)) then
    bIgnored = true;
  end
end
local WOWB_LASTOBJNAME = WOWB_TAG[0].name;
if(not bIgnored) then tinsert(WOWB_PARENT[0], WOWB_TAG); end
local WOWB_PARENTOBJECT = nil;
local WOWB_ISVIRTUAL = true;
WOWB_InheritType(WOWB_TAG, WBClass_Font);
WOWB_TAG[0].parentobj = WOWB_PARENTOBJECT;
if(WOWB_PARENTOBJECT) then
  WOWB_PARENTOBJECT[0].children[WOWB_TAG] = true;
end
local WOWB_PARENTOBJECT = (not WOWB_ISVIRTUAL) and WOWB_TAG or nil;
if WOWB_TAG[0].inherits then
  WOWB_ParseXML_InheritObj(xfpc:Recurse(WOWB_TAG), WOWB_TAG, WOWB_TAG[0].inherits, WOWB_ISVIRTUAL);
end
WOWB_RunObjConstructors(WOWB_TAG, WBClass_Font);

do -- <FontHeight ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=39
local WOWB_TAG = { [0]={  xmltag="FontHeight",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=39,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
}};
WOWB_PARENT[0]["FontHeight"] = WOWB_TAG;
do -- <AbsValue ...>
local WOWB_PARENT = WOWB_TAG;
local bIgnored = false;
xfpc.linenum=40
local WOWB_TAG = { [0]={  xmltag="AbsValue",   xmlfile=WOWB_XMLFILE,  xmlfilelinenum=40,  children={},  virtual=WOWB_ISVIRTUAL and "true",  content="",
["val"] =8,
}};
WOWB_PARENT[0]["AbsValue"] = WOWB_TAG;
end
end
end
end
if(not WOWB_TAG[0][WOWB_ROOTXMLTAG]) then xfpc:error("No <"..WOWB_ROOTXMLTAG.."> tag?"); end
WOWB_ParseXML_QueueScripts(WOWB_TAG[0][WOWB_ROOTXMLTAG]);

xfpc:Return();
