-- german localization
if ( GetLocale() == "deDE" ) then
  BINDING_HEADER_RAIDSUMMON= "RaidSummon";
  BINDING_NAME_RAIDSUMMON=   "Ziel/von Warteschlange beschwören";

  RSM_SPELL_NAME=            "Ritual der Beschwörung";
  RSM_SPELL_HELP=            "Beginnt ein Ritual, das dass aktuell gewählte Gruppenmitglied oder den nächsten Spieler in der Warteschlange beschwört. Wenn kein Spieler im Ziel ist oder wartet, werdet ihr gefragt ob ihr den gesamten Raid beschwören wollt. Klicken mit gedrückter Strg-Taste überspringt den ersten Spieler in der Warteschlange. Klicken mit rechter Maustaste für Optionen.";
  RSM_SPELL_QUEUE_EMPTY=     "Warteschlange leer.";
  RSM_SPELL_QUEUE=           "Spieler in Warteschlange: ";

  RSM_HEADER=                "RaidSummon: ";
  RSM_LOADED=                "RaidSummon geladen. <h>/rsm</h> für Hilfe eingeben!";  
  RSM_MORE=                  "Weitere Spieler müssen beschworen werden. Nächster: %s.";
  RSM_REQUEST=               "Beschwörungs-Anfrage von %s.";
  RSM_NOTHING_TO_DO=         "Es liegen keine Beschwörungs-Anfragen vor.";
  RSM_FAILED=                "Ritual der Beschwörung fehlgeschlagen!";
  RSM_NOSHARDSUMMONING=      "Nicht genügend Seelensplitter!";
  RSM_GHOSTSUMMONING=        "%s ist tot oder offline und kann derzeit nicht beschworen werden!";
  RSM_GHOSTSKIPPED=          "%s ist tot oder offline und wurde an das Ende der Warteschlange verschoben.";
  RSM_CONFIRMMASSSUMMON=     "Wollt ihr alle Spieler beschwören, die sich derzeit nicht in der Nähe befinden?";
  RSM_SUMMONING=             "Beschwöre %s.";
  RSM_NOT_IN_RAID=           "Euer Ziel ist nicht in dieser Gruppe oder diesem Schlachtzug!";
  RSM_ALL_IN_RANGE=          "Es sind bereits alle Schlachtzugsmitglieder in Reichweite.";
  RSM_NOT_IN_INSTANCE=       "Massenbeschwörung nicht in Instanzen verfügbar.";
  RSM_ALREADY_SUMMONED=      "%s wurde bereits beschworen und daher aus der Warteschlange entfernt.";
  RSM_ALMOST_SUMMONED=       "%s wird bald von einem anderen Hexer beschworen und daher fürs Erste an das Ende eurer Warteschlange gesetzt.";  
  RSM_GROUP_REQUIRED=        "Ihr müsst euch in einer Gruppe oder einem Schlachtzug befinden.";
  RSM_PRE2x2MIGRATION=       "Statistiken der Version 2.1 und niedriger wurden importiert, alle weiteren Einstellungen müssen leider erneut vorgenommen werden.";
  RSM_NO_KEYWORDS=           "Kann RaidSummon nicht ausrufen da keine Schlüsselwörter definiert sind!";
  RSM_UNKNOWN_PARAMETER=     "Unbekannter Parameter.";
  RSM_MASSSUMMON=            "Übergehe Warteschlange für Massenbeschwörung.";
  RSM_RESET_QUEUE=           "Warteschlange wurde zurückgesetzt.";
  RSM_QUEUED_PLAYERS=        "Spieler derzeit in Warteschlange: ";
  RSM_DEQUEUE_PLAYER=        "%s wurde aus der Warteschlange entfernt.";
  RSM_ADDON_ENABLED=         "RaidSummon aktiviert.";
  RSM_ADDON_DISABLED=        "RaidSummon deaktiviert.";
  RSM_LISTEN_ENABLED=        "Anfragen werden verarbeitet.";
  RSM_LISTEN_DISABLED=       "Anfragen werden nicht verarbeitet.";
  RSM_ANNOUNCE_ENABLED=      "Beschwörungen werden angesagt.";
  RSM_ANNOUNCE_DISABLED=     "Beschwörungen werden nicht angesagt.";
  RSM_WHISPER_ENABLED=       "Spieler werden per Nachricht informiert.";
  RSM_WHISPER_DISABLED=      "Spieler werden nicht per Nachricht informiert.";
  RSM_END_OF_LIST=           "(Ende der Liste)";
  RSM_STATS_RESET=           "Statistiken wurden zurückgesetzt.";
  RSM_TOTALS_RAID=           "Gesamtanzahl an Beschwörungen aktueller Schlachtzugsmitglieder:";
  RSM_TOTALS=                "Gesamtanzahl an Beschwörungen: ";
  RSM_MINIMUM_SHARDS=        "Minimalanzahl an Splittern für Beschwörungsanfragen: %n";
  RSM_MINIMUM_DISTANCE=      "Minimaldistanz für Massenbeschwörung: %n Yrd";
  RSM_WHISPERLANG=           "Sprache für Spielernachrichten: ";
  RSM_KEYWORDS=              "Schlüsselwörter (%l): %k";
  RSM_KEYWORDRESET=          "Schlüsselwörter zurückgesetzt. Bitte neue Schlüsselwörter definieren, da ansonsten keine Beschwörungs-Anfragen verarbeitet werden können.";
  RSM_REPLIES_HIDDEN=        "RaidSummons Antworten werden nicht angezeigt.";
  RSM_REPLIES_SHOWN=         "RaidSummons Antworten werden angezeigt.";
  RSM_REQUESTS_HIDDEN=       "Akzeptierte Beschwörungs-Anfragen werden nicht im Chat angezeigt.";
  RSM_REQUESTS_SHOWN=        "Auch akzeptierte Beschwörungs-Anfragen werden im Chat angezeigt.";
  RSM_BLINKING_ENABLED=      "Die 'Ritual der Beschwörung'-Aktion blinkt wenn Beschwörungs-Anfragen vorhanden sind.";
  RSM_BLINKING_DISABLED=     "Die 'Ritual der Beschwörung'-Aktion wird nicht blinken wenn Beschwörungs-Anfragen vorhanden sind.";

  RSM_HELP_MSG0=             "RaidSummon: <h>/raidsummon</h> (oder <h>/rsm</h>) gefolgt von....";
  RSM_HELP_MSG1=             "<h>basic</h>, <h>logging</h> oder <h>settings</h> für weiter Hilfe!";
  RSM_HELP_MSG2=             "<h>togglehiderequests/thq</h> umschalten ob akzeptierte Anfragen im Chat angezeigt werden";
  RSM_HELP_MSG3=             "<h>toggleenable/te</h> RaidSummon aktivieren/deaktivieren";
  RSM_HELP_MSG4=             "<h>togglelisten/tl</h> umschalten ob auf geflüsterte Nachrichten reagiert werden soll";
  RSM_HELP_MSG5=             "<h>toggleannounce/ta</h> umschalten ob Beschwörungen dem Raid angesagt werden sollen";
  RSM_HELP_MSG6=             "<h>status</h> aktuelle Einstellungen anzeigen";
  RSM_HELP_MSG7=             "<h>list</h> alle Spieler in der Warteschlange auflisten";
  RSM_HELP_MSG8=             "<h>clear</h> Warteschlange zurücksetzen";
  RSM_HELP_MSG9=             "<h>skip</h> ersten Spieler in der Warteschlange löschen/überspringen";
  RSM_HELP_MSG10=            "<h>shards <num></h> minimale Anzahl an Splittern setzen, die nötig sind um auf geflüsterte Anfragen zu reagieren";
  RSM_HELP_MSG11=            "<h>stats <num></h> zeigt die Gesamtanzahl an Beschwörungen pro Spieler an";
  RSM_HELP_MSG12=            "<h>raidstats <num></h> zeigt die Gesamtanzahl an Beschwörungen pro Spieler des Raids an";
  RSM_HELP_MSG13=            "<h>postraidstats <num></h> wie raidstats, nur werden die Ergebnisse im Raid geschrieben";
  RSM_HELP_MSG14=            "<h>resetstats</h> setzt die Beschwörungsstatistiken zurück";
  RSM_HELP_MSG15=            "<h>announce</h> RaidSummon dem Raid/der Gruppe bekannt geben";
  RSM_HELP_MSG16=            "<h>lang <de|en|fr></h> ändert die Sprache die für Nachrichten an andere Spieler verwendet wird";
  RSM_HELP_MSG17=            "<h>addkeyword</h> definiert ein weiteres Schlüsselwort, auf das RaidSummon reagiert (Schlüsselwörter können Leerzeichen enthalten)";
  RSM_HELP_MSG18=            "<h>resetkeywords</h> setzt die Liste der Schlüsselwörter, die eine Beschwörung aktivieren, zurück";
  RSM_HELP_MSG19=            "<h>togglewhisper/tw</h> umschalten ob Spieler per Nachricht informiert werden sollen";
  RSM_HELP_MSG20=            "<h>togglehidereplies/thp</h> umschalten ob RaidSummons Antworten im Chat angezeigt werden";
  RSM_HELP_MSG21=            "<h>toggleflash/tf</h> umschalten ob die 'Ritual der Beschwörung'-Aktion bei Spielern in Warteschlange blinken soll";
  RSM_HELP_MSG22=            "<h>distance <num></h> Minimaldistanz ab der Spieler von der Massenbeschwörungsfunktion ausgewählt werden";
  
  RSM_UFMENU_SUMMON=         "Beschwören";
  RSM_MENU_SUMMON=           "Spieler aus Warteschlange beschwören";
  RSM_MENU_SUMMON_TARGET=    "Aktuelles Ziel beschwören";
  RSM_MENU_SUMMON_ALL=       "Alle nicht anwesenden Spieler beschwören";
  RSM_MENU_SKIP=             "Spieler überspringen";
  RSM_MENU_CLEAR=            "Warteschlange löschen";
  RSM_MENU_STOP=             "Massenbeschwörung abbrechen";
  RSM_MENU_ANNOUNCE=         "RaidSummon Funktionalität bekanntgeben";
  RSM_MENU_PROCESS=          "Beschwörungsanfragen verarbeiten";
  RSM_MENU_NOTIFICATIONS=    "Benachrichtigungen/Anfragen";
  RSM_MENU_SELECT=           "Auswahl";
  RSM_MENU_ANNOUNCING=       "Beschwörungen ansagen";
  RSM_MENU_WHISPERING=       "Anfragen per Nachricht beantworten";
  RSM_MENU_DISPLAY=          "Chat Fenster";
  RSM_MENU_HIDE_REQUESTS=    "Akzeptierte Anfragen ausblenden";
  RSM_MENU_HIDE_TELLS=       "RaidSummon's Antworten ausblenden";
  RSM_MENU_FLASHING=         "Aktion bei wartenden Spielern blinken lassen";
  RSM_MENU_LOCALE=           "Sprache";
  RSM_MENU_SHARD_MINIMUM=    "Min. Anzahl an Splittern für Anfragen";
  RSM_MENU_SHARDS=           "Seelensplitter";
  RSM_MENU_CLOSE=            "Schließen";

-- french localization by cthol & Tenebra
elseif ( GetLocale() == "frFR" ) then
  BINDING_HEADER_RAIDSUMMON= "RaidSummon";
  BINDING_NAME_RAIDSUMMON=   "Invoque Cible/List";

  RSM_SPELL_NAME=            "Rituel d'invocation";
  RSM_SPELL_HELP=            "Débute un rituel qui invoque le membre du groupe qui est ciblé ou le joueur suivant dans la file d'attente. Si personne n'est ciblé ou dans la file il vous sera proposé d'invoquer tout le raid. Maintenez la touche control enfoncée et cliquer pour annuler la demande d'invocation du premier joueur dans la file. Cliquez droit pour les options.";
  RSM_SPELL_QUEUE_EMPTY=     "Fille d'attente vide.";
  RSM_SPELL_QUEUE=           "Joeurs en attente: ";

  RSM_HEADER=                "RaidSummon: ";
  RSM_LOADED=                "RaidSummon chargé. tapez <h>/rsm</h> pour l'aide !";
  RSM_MORE=                  "D'autres joueurs ont demandé une invocation. Suivant dans la file d'attente: %s.";
  RSM_REQUEST=               "Demande d'invocation - %s.";
  RSM_NOTHING_TO_DO=         "Plus de demande d'invocation dans la file d'attente.";
  RSM_FAILED=                "Le rituel a échoué !";
  RSM_NOSHARDSUMMONING=      "Plus assez de fragments!";
  RSM_GHOSTSUMMONING=        "%s est mort ou est un fantôme!"; -- fixme:  or offline... and cannot be summoned
  RSM_GHOSTSKIPPED=          "%s est mort ou est un fantôme, il est placé en fin de la file d'attente."; -- fixme: dead or offline
  RSM_CONFIRMMASSSUMMON=     "Souhaitez-vous invoquer tous les joueurs qui ne sont pas présents dans la zone actuellement ?"; -- fixme: this has changed to "in proximity" instead of zone
  RSM_SUMMONING=             "Invocation %s.";
  RSM_NOT_IN_RAID=           "La cible n'est pas dans le raid.";
  RSM_ALL_IN_RANGE=          "Tous les memebres du raid sont à vos cotés.";
  RSM_GROUP_REQUIRED=        "Vous devez être en groupe ou en raid.";
  RSM_NOT_IN_INSTANCE=       "Invocation en masse indisponible dans les instances.";
  RSM_ALREADY_SUMMONED=      "%s has already been summoned and was thus removed from the queue."; -- FIXME: translate
  RSM_ALMOST_SUMMONED=       "%s is about to be summoned by another warlock and thus moved to the end of your queue for now."; -- FIXME: :-(  
  RSM_NO_KEYWORDS=           "Cannot announce RaidSummon since there are no keywords defined!"; -- FIXME: translate please;)  
  RSM_PRE2x2MIGRATION=       "Statistics from version 2.1 and below have been imported, all other settings will need to be configured again.";  -- fixme: translate
  RSM_UNKNOWN_PARAMETER=     "Paramètre inconnu.";
  RSM_MASSSUMMON=            "Liste principale pour invocation en nombre.";
  RSM_RESET_QUEUE=           "La file d'attente a été vidée.";
  RSM_QUEUED_PLAYERS=        "Joueurs actuellement en attente d'une invocation: ";
  RSM_DEQUEUE_PLAYER=        "Joueur quittant la file d'attente: %s.";
  RSM_ADDON_ENABLED=         "RaidSummon activé.";
  RSM_ADDON_DISABLED=        "RaidSummon désactivé.";
  RSM_LISTEN_ENABLED=        "Traitement des demandes activé.";
  RSM_LISTEN_DISABLED=       "Traitement des demandes désactivé.";
  RSM_ANNOUNCE_ENABLED=      "Les invocations seront annoncées.";
  RSM_ANNOUNCE_DISABLED=     "Les invocations ne seront pas annoncées.";
  RSM_WHISPER_ENABLED=       "Les joueurs seront tenus informés par chuchotement.";
  RSM_WHISPER_DISABLED=      "Les joueurs ne seront pas tenus informés par chuchotement.";
  RSM_END_OF_LIST=           "(Fin de la liste)";
  RSM_STATS_RESET=           "Les statistiques ont été vidées.";
  RSM_TOTALS_RAID=           "Nombre total d'invocations pour chaque membre du raid:";
  RSM_TOTALS=                "Nombre total d'invocations: ";
  RSM_MINIMUM_SHARDS=        "Nombre minimum de fragments pour réaliser une invocation: %n";
  RSM_MINIMUM_DISTANCE=      "Minimum distance for mass summoning: %n Yrd";
  RSM_WHISPERLANG=           "Langue des messages envoyés aux joueurs: ";
  RSM_KEYWORDS=              "Mots-clés (%l): %k";
  RSM_KEYWORDRESET=          "Les mots-clés ont été réinitialisés. Veuillez définir de nouveaux mots-clés, pour traiter les demandes d'invocation il vous faut au moins un mot-clé défini.";
  RSM_REPLIES_HIDDEN=        "Les réponses de RaidSummon ne seront pas affichées.";
  RSM_REPLIES_SHOWN=         "Les réponses de RaidSummon seront affichées.";
  RSM_REQUESTS_HIDDEN=       "Les demandes d'invocation acceptées ne seront pas affichées.";
  RSM_REQUESTS_SHOWN=        "Même les demandes d'invocation acceptées seront affichées.";
  RSM_BLINKING_ENABLED=      "The 'Ritual of Summoning' action will flash while players are queued."; -- FIXME: translate
  RSM_BLINKING_DISABLED=     "The 'Ritual of Summoning' action will not flash while players are queued."; -- FIXME: translate

  RSM_HELP_MSG0=             "RaidSummon: Tapez <h>/raidsummon</h> (ou <h>/rsm</h>) suivi de...";
  RSM_HELP_MSG1=             "<h>basic</h>, <h>logging</h> ou <h>settings</h> pour l'aide!";
  RSM_HELP_MSG2=             "<h>togglehiderequests/thq</h> active/désactive l'affichage des demandes d'invocation acceptées.";
  RSM_HELP_MSG3=             "<h>toggleenable/te</h> active/désactive RaidSummon";
  RSM_HELP_MSG4=             "<h>togglelisten/tl</h> active/désactive l'attente des demandes d'invocation";
  RSM_HELP_MSG5=             "<h>toggleannounce/ta</h> active/désactive l'annonce des invocation au raid/groupe";
  RSM_HELP_MSG6=             "<h>status</h> affiche l'état actuel";
  RSM_HELP_MSG7=             "<h>list</h> affiche les joueurs dans la file d'attente";
  RSM_HELP_MSG8=             "<h>clear</h> vide la file d'attente";
  RSM_HELP_MSG9=             "<h>skip</h> saute/efface le premier joueur dans la file d'attente";
  RSM_HELP_MSG10=            "<h>shards <num></h> configure le nombre minimum de fragments d'âme";
  RSM_HELP_MSG11=            "<h>stats <num></h> affiche le total des invocations et les invocations par joueur";
  RSM_HELP_MSG12=            "<h>raidstats <num></h> liste seulement les invocations des joueurs actuellement dans le raid";
  RSM_HELP_MSG13=            "<h>postraidstats <num></h> envoi le total des invocation sur le canal de raid";
  RSM_HELP_MSG14=            "<h>resetstats</h> efface toutes les statistiques d'invocation";
  RSM_HELP_MSG15=            "<h>announce</h> envoi le message d'utilisation de raidsummon au raid/groupe";
  RSM_HELP_MSG16=            "<h>lang <de|en|fr></h> change la langue des messages envoyé aux autres joueurs";
  RSM_HELP_MSG17=            "<h>addkeyword</h> ajoute un mot-clé à la liste des mots-clés qui indiquent une demande d'invocation (les mots-clés peuvent contenir des espaces)";
  RSM_HELP_MSG18=            "<h>resetkeywords</h> réinitialise la liste des mots-clés qui indiquent une demande d'invocation";
  RSM_HELP_MSG19=            "<h>togglewhisper/tw</h> active/désactive le fait de prévenir les joueurs par chuchotement";
  RSM_HELP_MSG20=            "<h>togglehidereplies/thp</h> active/désactive le fait de cacher les réponse de RaidSummon";
  RSM_HELP_MSG21=            "<h>toggleflash/tf</h> toggle whether the 'Ritual of Summoning' action should flash while players are queued"; -- FIXME: translate
  RSM_HELP_MSG22=            "<h>distance <num></h> minimum distance required before players will be selected for mass summoning"; -- FIXME: translate
  
  RSM_UFMENU_SUMMON=         "Invoquer";
  RSM_MENU_SUMMON=           "Invoquer le joueur suivant";
  RSM_MENU_SUMMON_TARGET=    "Invoquer le joueur ciblé";
  RSM_MENU_SUMMON_ALL=       "Invoquer tout le groupe";
  RSM_MENU_SKIP=             "Annuler la demande du joueur";
  RSM_MENU_CLEAR=            "effacer la file d'attente";
  RSM_MENU_STOP=             "annuler l'invocation en masse";
  RSM_MENU_ANNOUNCE=         "Faire une annonce RaidSummon";
  RSM_MENU_PROCESS=          "Attendre les demandes d'invocation";
  RSM_MENU_NOTIFICATIONS=    "Notifications/demandes";
  RSM_MENU_SELECT=           "Sélectionner";
  RSM_MENU_ANNOUNCING=       "Annoncer les invocations";
  RSM_MENU_WHISPERING=       "Répondre aux demandes par chuchotement";
  RSM_MENU_DISPLAY=          "Fenêtre de discussion";
  RSM_MENU_HIDE_REQUESTS=    "Masquer les demandes acceptées";
  RSM_MENU_HIDE_TELLS=       "Masquer les réponse de RaidSummon";
  RSM_MENU_FLASHING=         "Flash action while players in queue"; -- FIXME: translate
  RSM_MENU_LOCALE=           "Langue";
  RSM_MENU_SHARD_MINIMUM=    "Fragments nécessaires pour accepter les demandes";
  RSM_MENU_SHARDS=           "Fragments d'âme";
  RSM_MENU_CLOSE=            "Fermer";

-- defaulting to english localization
else
  BINDING_HEADER_RAIDSUMMON= "RaidSummon";
  BINDING_NAME_RAIDSUMMON=   "Summon target/queue";

  RSM_SPELL_NAME=            "Ritual of Summoning";
  RSM_SPELL_HELP=            "Begins a ritual that summons the targeted group member or the next player in the queue. If no player is queued or targeted you will be asked if you wish to summon the entire raid. Hold control-key and click to skip the first queued player. Right-click for options.";
  RSM_SPELL_QUEUE_EMPTY=     "Queue empty.";
  RSM_SPELL_QUEUE=           "Players in queue: ";

  RSM_HEADER=                "RaidSummon: ";
  RSM_LOADED=                "RaidSummon loaded. Type <h>/rsm</h> for help!";  
  RSM_MORE=                  "More players need to be summoned. Next: %s.";
  RSM_REQUEST=               "Summoning request by %s.";
  RSM_NOTHING_TO_DO=         "No summoning requests queued.";
  RSM_FAILED=                "Ritual of Summoning failed!";
  RSM_NOSHARDSUMMONING=      "Not enough Soul Shards!";
  RSM_GHOSTSUMMONING=        "%s is dead or offline and cannot be summoned!";
  RSM_GHOSTSKIPPED=          "%s is dead or offline and was moved to the end of the queue.";
  RSM_CONFIRMMASSSUMMON=     "Do you wish to summon all players who are not currently in proximity?";
  RSM_SUMMONING=             "Summoning %s.";
  RSM_NOT_IN_RAID=           "Your target is not in this party or raidgroup!";
  RSM_ALL_IN_RANGE=          "All raidmembers are in range.";
  RSM_NOT_IN_INSTANCE=       "Mass summoning not available from within instances.";
  RSM_ALREADY_SUMMONED=      "%s has already been summoned and was thus removed from the queue.";
  RSM_ALMOST_SUMMONED=       "%s is about to be summoned by another warlock and thus moved to the end of your queue for now.";
  RSM_GROUP_REQUIRED=        "You need to be in a party or raidgroup.";
  RSM_PRE2x2MIGRATION=       "Statistics from version 2.1 and below have been imported, all other settings will need to be configured again.";
  RSM_NO_KEYWORDS=           "Cannot announce RaidSummon since there are no keywords defined!";
  RSM_UNKNOWN_PARAMETER=     "Unknown parameter.";
  RSM_MASSSUMMON=            "Overriding list for mass-summoning.";
  RSM_RESET_QUEUE=           "Queue has been resetted.";
  RSM_QUEUED_PLAYERS=        "Players currently queued: ";
  RSM_DEQUEUE_PLAYER=        "%s has been removed from the queue.";
  RSM_ADDON_ENABLED=         "RaidSummon enabled.";
  RSM_ADDON_DISABLED=        "RaidSummon disabled.";
  RSM_LISTEN_ENABLED=        "Summoning requests will be processed.";
  RSM_LISTEN_DISABLED=       "Summoning requests will not be processed.";
  RSM_ANNOUNCE_ENABLED=      "Summoning announcement enabled.";
  RSM_ANNOUNCE_DISABLED=     "Summoning announcement disabled.";
  RSM_WHISPER_ENABLED=       "Players will be notified by tell.";
  RSM_WHISPER_DISABLED=      "Players will not be notified by tell.";
  RSM_END_OF_LIST=           "(End of List)";
  RSM_STATS_RESET=           "Stats have been resetted.";
  RSM_TOTALS_RAID=           "Total summons of each raid-member:";
  RSM_TOTALS=                "Total summons: ";
  RSM_MINIMUM_SHARDS=        "Number of shards required to accept summoning requests: %n";
  RSM_MINIMUM_DISTANCE=      "Minimum distance for mass summoning: %n Yrd";  
  RSM_WHISPERLANG=           "Playermessage language: ";
  RSM_KEYWORDS=              "Keywords (%l): %k";
  RSM_KEYWORDRESET=          "Keywords have been reset. Please define new keywords as at least one keyword is required to process summoning-requests.";
  RSM_REPLIES_HIDDEN=        "RaidSummon's replies will not be displayed.";
  RSM_REPLIES_SHOWN=         "RaidSummon's replies will be displayed.";
  RSM_REQUESTS_HIDDEN=       "Accepted summon-requests will not be displayed.";
  RSM_REQUESTS_SHOWN=        "Even accepted summon-requests will be displayed.";
  RSM_BLINKING_ENABLED=      "The 'Ritual of Summoning' action will flash while players are queued.";
  RSM_BLINKING_DISABLED=     "The 'Ritual of Summoning' action will not flash while players are queued.";

  RSM_HELP_MSG0=             "RaidSummon: Type <h>/raidsummon</h> (or <h>/rsm</h>) followed by....";
  RSM_HELP_MSG1=             "<h>basic</h>, <h>logging</h> or <h>settings</h> for further help!";
  RSM_HELP_MSG2=             "<h>togglehiderequests/thq</h> toggle whether accepted requests should be hidden from chat.";
  RSM_HELP_MSG3=             "<h>toggleenable/te</h> enable/disable RaidSummon";
  RSM_HELP_MSG4=             "<h>togglelisten/tl</h> toggle listening to summoning requests";
  RSM_HELP_MSG5=             "<h>toggleannounce/ta</h> toggle summoning announcements to party/raid";
  RSM_HELP_MSG6=             "<h>status</h> show current settings";
  RSM_HELP_MSG7=             "<h>list</h> list all players in queue";
  RSM_HELP_MSG8=             "<h>clear</h> reset the queue";
  RSM_HELP_MSG9=             "<h>skip</h> skip/delete first queued player";
  RSM_HELP_MSG10=            "<h>shards <num></h> set minimum shard-count for summoning";
  RSM_HELP_MSG11=            "<h>stats <num></h> show total summons and summons per players";
  RSM_HELP_MSG12=            "<h>raidstats <num></h> show summons only of players currently in raid";
  RSM_HELP_MSG13=            "<h>postraidstats <num></h> post total summons of raid-members to raid";
  RSM_HELP_MSG14=            "<h>resetstats</h> reset all summoning stats";
  RSM_HELP_MSG15=            "<h>announce</h> announce raidsummon to party/raid";
  RSM_HELP_MSG16=            "<h>lang <de|en|fr></h> change language of tells to other players";
  RSM_HELP_MSG17=            "<h>addkeyword</h> adds a keyword to the list of keywords that trigger a summoning request (keywords may contain spaces)";
  RSM_HELP_MSG18=            "<h>resetkeywords</h> resets list of keywords that trigger a summoning request";
  RSM_HELP_MSG19=            "<h>togglewhisper/tw</h> toggle whether players should be informed by tell";
  RSM_HELP_MSG20=            "<h>togglehidereplies/thp</h> hide/show RaidSummon's replies";
  RSM_HELP_MSG21=            "<h>toggleflash/tf</h> toggle whether the 'Ritual of Summoning' action should flash while players are queued";
  RSM_HELP_MSG22=            "<h>distance <num></h> minimum distance required before players will be selected for mass summoning";
  
  RSM_UFMENU_SUMMON=         "Summon";
  RSM_MENU_SUMMON=           "Summon next queued player";
  RSM_MENU_SUMMON_TARGET=    "Summon current target";
  RSM_MENU_SUMMON_ALL=       "Summon entire group";
  RSM_MENU_SKIP=             "Skip player";
  RSM_MENU_CLEAR=            "Clear queue";
  RSM_MENU_STOP=             "Abort mass summoning";
  RSM_MENU_ANNOUNCE=         "Announce RaidSummon";
  RSM_MENU_PROCESS=          "Listen for summon-requests";
  RSM_MENU_NOTIFICATIONS=    "Notifications/requests";
  RSM_MENU_SELECT=           "Select";
  RSM_MENU_ANNOUNCING=       "Announce summons";
  RSM_MENU_WHISPERING=       "Reply to requests by whisper";
  RSM_MENU_DISPLAY=          "Chat window";
  RSM_MENU_HIDE_REQUESTS=    "Hide accepted requests";
  RSM_MENU_HIDE_TELLS=       "Hide RaidSummon's replies";
  RSM_MENU_FLASHING=         "Flash action while players in queue";
  RSM_MENU_LOCALE=           "Language";
  RSM_MENU_SHARD_MINIMUM=    "Shards required to accept requests";
  RSM_MENU_SHARDS=           "Soul Shards";
  RSM_MENU_CLOSE=            "Close";

end;


-- messages to other players: player might not wish to have these in his clients language
-- so the language for these messsages can be set with /rsm lang <de|en...>
RSM_PREFIX= "[RaidSummon] ";
RSM_DEFAULT_KEYWORDS= { 
  ["en"]= { "summon" },
  ["de"]= { "port" },
  ["fr"]= { "invocation" }
};
RSM_LANG= {
  ["en"]= {
    ["LANGUAGE"]=       "English",
    ["ANNOUNCE_PORT"]=  "Summoning >>> %s <<<",
    ["PORT_SUPPORT"]=   "Please click on my portal.",
    ["PORT_FAILED"]=    "Summoning failed. (Please don't move during the ritual.) :p",
    ["WAIT"]=           RSM_PREFIX.."Ok. %n will summon you in a few moments, so please don't ask any other warlocks.",
    ["BUSY"]=           RSM_PREFIX.."Ok. %n will summon you as soon as %g{he,she}'s out of combat (and alive), so please don't ask any other Warlocks.",
    ["INCOMING"]=       RSM_PREFIX.."Ok. That should be no problem.",
    ["SKIP"]=           RSM_PREFIX.."%n has deleted your summoning request.",
    ["INSTANCE_NONE"]=  RSM_PREFIX.."You are not in %n's instance but please don't ask another Warlock unless %g{he,she} deletes your request.",
    ["INSTANCE_AUTO"]=  RSM_PREFIX.."%w will summon you in a few moments sinc you are not in %n's instance but . Please don't ask another Warlock now.",
    ["INSTANCE_MANUAL"]=RSM_PREFIX.."%n is already inside the instance but %w is not. Please ask %h{him,her} instead. Thank you!",
    ["AFK_NONE"]=       RSM_PREFIX.."Sorry. %n is AFK. Please ask another Warlock.",
    ["AFK_AUTO"]=       RSM_PREFIX.."%w will summon you in a few moments since %n is AFK. Please don't ask another Warlock now.",
    ["AFK_MANUAL"]=     RSM_PREFIX.."Sorry. %n is AFK. %w is in %g{his,her} proximity and might be able to summon you. Please ask %h{him,her} instead. Thank you!",
    ["FULL_NONE"]=      RSM_PREFIX.."Sorry. Too many players in queue. Please ask another Warlock.",
    ["FULL_AUTO"]=      RSM_PREFIX.."%w will summon you in a few moments since %n has already too many players in %g{his,her} queue. Please don't ask another Warlock now.",
    ["FULL_MANUAL"]=    RSM_PREFIX.."Sorry. Too many players in queue. %w is in %n's proximity and might be able to summon you. Please ask %h{him,her} instead. Thank you!",
    ["SHARDS_NONE"]=    RSM_PREFIX.."Sorry. %n doesn't have enough Shards. Please ask another Warlock.",
    ["SHARDS_AUTO"]=    RSM_PREFIX.."%w will summon you in a few moments since %n is out of Shards. Please don't ask another Warlock now.",
    ["SHARDS_MANUAL"]=  RSM_PREFIX.."Sorry. %n is out of Shards. %w is in %n's proximity and might be able to summon you. Please ask %h{him,her} instead. Thank you!",
    
    ["SHARDS_WHOOPS"]=  RSM_PREFIX.."Whoops... %n mysteriously ran out of Soulshards. :( Hopefully another Warlock can help you.",
    ["YOU_ARE_DEAD"]=   RSM_PREFIX.."%n will summon you as soon as you are alive. ;)",
    ["NOW"]=            RSM_PREFIX.."Prepare to be summoned! ;)",
    ["TOTALS_RAID"]=    "Total summons of each raid-member:",
    ["END_OF_LIST"]=    "- - -",
    ["ANNOUNCE1"]=      "> Please whisper keyword \"%k\",",
    ["ANNOUNCE2"]=      "> if you need to be summoned.",
  },
  ["de"]= {
    ["LANGUAGE"]=       "Deutsch",
    ["ANNOUNCE_PORT"]=  "Beschwöre >>> %s <<<",
    ["PORT_SUPPORT"]=   "Bitte jetzt auf mein Portal klicken.",
    ["PORT_FAILED"]=    "Beschwörung fehlgeschlagen. (Bitte während des Rituals nicht bewegen.) :p",
    ["WAIT"]=           RSM_PREFIX.."Ok. %n beschwört dich in ein paar Augenblicken also frage bitte keinen weiteren Hexer.",
    ["BUSY"]=           RSM_PREFIX.."Ok. %n beschwört dich sobald %g{er,sie} nicht mehr im Kampf ist (und lebt). Bitte keinen weiteren Hexer fragen.",
    ["INCOMING"]=       RSM_PREFIX.."Ok. Das sollte kein Problem sein.",
    ["SKIP"]=           RSM_PREFIX.."%n hat deine Port-Anfrage gelöscht.",
    ["INSTANCE_NONE"]=  RSM_PREFIX.."Du befindest dich nicht in %ns Instanz, aber frage bitte nur einen anderen Hexer falls %g{er,sie} deine Anfrage löscht.",
    ["INSTANCE_AUTO"]=  RSM_PREFIX.."%w wird dich gleich beschwören, da du dich nicht in %ns Instanz befindest. Bitte frage jetzt keine anderen Hexer mehr.",
    ["INSTANCE_MANUAL"]=RSM_PREFIX.."%n ist bereits in der Instanz, %w aber nicht. Bitte frage %h{ihn,sie}, ob %h{er,sie} dich beschwören kann. Danke!",
    ["AFK_NONE"]=       RSM_PREFIX.."Sorry. %n ist AFK. Bitte frage einen anderen Hexer.",
    ["AFK_AUTO"]=       RSM_PREFIX.."%w wird dich gleich beschwören, da %n AFK ist. Bitte keinen weiteren Hexer fragen.",
    ["AFK_MANUAL"]=     RSM_PREFIX.."Sorry. %n ist AFK, aber %w ist in %g{seiner,ihrer} Nähe. Bitte frage %h{ihn,sie}, ob %h{er,sie} dich beschwören kann. Danke!",
    ["FULL_NONE"]=      RSM_PREFIX.."Sorry. Zuviele Spieler in Warteschlange. Bitte frage einen anderen Hexer.",
    ["FULL_AUTO"]=      RSM_PREFIX.."%w wird dich gleich beschwören, da %n bereits zuviele Spieler in %g{seiner,ihrer} Warteschlange hat. Bitte frage jetzt keine anderen Hexer mehr.",
    ["FULL_MANUAL"]=    RSM_PREFIX.."Sorry. %n hat zuviele Spieler in %g{seiner,ihrer} Warteschlange, aber %w ist in %g{seiner,ihrer} Nähe und kann dich vielleicht beschwören, wenn du %h{ihn,sie} fragst.",
    ["SHARDS_NONE"]=    RSM_PREFIX.."Sorry. %n hat nicht mehr genügend Splitter. Bitte wende dich an einen anderen Hexer.",
    ["SHARDS_AUTO"]=    RSM_PREFIX.."%w wird dich gleich beschwören, da %n nicht mehr genügend Splitter hat. Bitte keinen weiteren Hexer fragen.",
    ["SHARDS_MANUAL"]=  RSM_PREFIX.."Sorry. %n hat nicht mehr genügend Splitter, aber %w ist in %g{seiner,ihrer} Nähe und kann dich vielleicht beschwören, wenn du %h{ihn,sie} fragst.",
    
    ["SHARDS_WHOOPS"]=  RSM_PREFIX.."Mhm... irgendwie hat %n keine Seelensplitter mehr. :( Hoffentlich kann dir ein anderer Hexer weiterhelfen.",
    ["YOU_ARE_DEAD"]=   RSM_PREFIX.."%n wird dich beschwören sobald du wieder lebst. ;)",
    ["NOW"]=            RSM_PREFIX.."Bereite dich auf deine Beschwörung vor! ;)",
    ["TOTALS_RAID"]=    "Gesamtanzahl an Beschwörungen aktueller Raid-Mitglieder:",
    ["END_OF_LIST"]=    "- - -",
    ["ANNOUNCE1"]=      "> Bitte schreibt mich mit \"%k\" an,",
    ["ANNOUNCE2"]=      "> wenn ihr beschworen werden wollt.",
  },
  ["fr"]= {
    ["LANGUAGE"]=       "Français",
    ["ANNOUNCE_PORT"]=  "Invocation >>> %s <<<",
    ["PORT_SUPPORT"]=   "Cliquer sur le portail maintenant s'il vous plaît.",
    ["PORT_FAILED"]=    "L'invocation a échoué. (Ne bougez pas pendant le rituel s'il vous plaît.) :p",
    ["WAIT"]=           RSM_PREFIX.."%n va vous invoquer dans un petit moment, ce n'est pas la peine de demander à un autre démoniste !",
    ["BUSY"]=           RSM_PREFIX.."%n va vous invoquer dès qu'%g{il,elle} ne sera plus en combat ou %g{mort,morte}. Ce n'est pas la peine de demander à un autre démoniste !",
    ["INCOMING"]=       RSM_PREFIX.."L'invocation ne devrait pas poser de problème.",
    ["SKIP"]=           RSM_PREFIX.."%n a été annulée votre demande d'invocation.",
    ["INSTANCE_NONE"]=  RSM_PREFIX.."Vous n'êtes pas dans mon instance, mais s'il vous plaît ne demander pas à un autre démoniste sauf si votre demande est annulée.",
    ["INSTANCE_AUTO"]=  RSM_PREFIX.."%w will summon you in a few moments sinc you are not in %n's instance but . Please don't ask another Warlock now.",
    ["INSTANCE_MANUAL"]=RSM_PREFIX.."Sorry. %n is already inside the instance but %w is not. Please ask %h{him,her} instead. Thank you!", -- FIXME: translate
    ["AFK_NONE"]=       RSM_PREFIX.."Désolé %n est ABS. Veuillez demander à un autre démoniste !",
    ["AFK_AUTO"]=       RSM_PREFIX.."%w will summon you in a few moments since %n is AFK. Please don't ask another Warlock now.",
    ["AFK_MANUAL"]=     RSM_PREFIX.."Sorry. %n is AFK. %w is in %g{his,her} proximity and might be able to summon you. Please ask %h{him,her} instead. Thank you!",
    ["FULL_NONE"]=      RSM_PREFIX.."Désolé il y a déjà trop de monde dans la file d'attente pour les invocations. Veuillez demander à un autre d\195\169moniste !",
    ["FULL_AUTO"]=      RSM_PREFIX.."%w will summon you in a few moments since %n has already too many players in %g{his,her} queue. Please don't ask another Warlock now.",
    ["FULL_MANUAL"]=    RSM_PREFIX.."Sorry. Too many players in queue. %w is in %n's proximity and might be able to summon you. Please ask %h{him,her} instead. Thank you!",
    ["SHARDS_NONE"]=    RSM_PREFIX.."Désolé %n n'a plus assez de fragments. Veuillez demander à un autre démoniste !",
    ["SHARDS_AUTO"]=    RSM_PREFIX.."%w will summon you in a few moments since %n is out of Shards. Please don't ask another Warlock now.",
    ["SHARDS_MANUAL"]=  RSM_PREFIX.."Sorry. %n is out of Shards. %w is in %n's proximity and might be able to summon you. Please ask %h{him,her} instead. Thank you!",

    ["SHARDS_WHOOPS"]=  RSM_PREFIX.."Ooops %n n'a bizarrement plus du tout de fragments. :( Heureusement un autre démoniste se fera un plaisir de vous aider.",
    ["YOU_ARE_DEAD"]=   RSM_PREFIX.."%n vous invoquera dès que vous serez en vie. ;)",
    ["NOW"]=            RSM_PREFIX.."Préparez-vous à être invoqué(e) ! ;)",
    ["TOTALS_RAID"]=    "Nombre total d'invocations pour chaque membre du raid:",
    ["END_OF_LIST"]=    "- - -", --"Fin de la liste.",
    ["ANNOUNCE1"]=      "> Please whisper keyword \"%k\",",  -- FIXME: translate (text changed, sorry ;) )
    ["ANNOUNCE2"]=      "> if you need to be summoned.",
  }
}
