if (GetLocale() == "zhTW") then

XPERL_MSG_PREFIX	= "|c00C05050X-Perl|r "
XPERL_COMMS_PREFIX	= "X-Perl"

XPERL_TOOLTIP_ASSISTING	= "正在協助的玩家："
XPERL_TOOLTIP_HEALERS	= "以我為目標的治療者："
XPERL_TOOLTIP_ALLONME	= "以我為目標的所有人："
XPERL_TOOLTIP_ENEMYONME	= "以我為目標的敵對者："
XPERL_TOOLTIP_HELP	= "點擊開啟即時觀察"
XPERL_TOOLTIP_PET	= "%s's 寵物"

XPERL_LOC_DEAD		= "死亡"

BINDING_HEADER_XPERL = "X-Perl 快捷鍵設定"
BINDING_NAME_TARGETFIRSTOTHER = "首要目標為非坦克目標"
BINDING_NAME_SMARTASSIST = "智能協助"

XPERL_BUTTON_TOGGLE_STATS_DESC	= "顯示目標統計"
XPERL_BUTTON_EXPAND_DESC	= "明顯化其他目標列表"
XPERL_BUTTON_EXPAND_LOCK	= "總是明顯化非坦克目標列表, 否則只有第一個目標將被顯示除非您的滑鼠經過在該區域."
XPERL_BUTTON_TOGGLE_LABELS	= "顯示坦克標籤"
XPERL_BUTTON_TOGGLE_TARGETS	= "顯示其他目標的目標"
XPERL_BUTTON_TOGGLE_MTTARGETS	= "顯示MT目標的目標"
XPERL_BUTTON_TOGGLE_SHOWMT	= "開關是否顯示主坦克"
XPERL_BUTTON_HELPER_PIN		= "固定視窗"

XPERL_STATS_NO_TARGET		= "%s 沒有目標。 懶鬼！"
XPERL_STATS_NOT_ASSIST_MT1	= "%s 主dps沒有協助 %s"
XPERL_STATS_NOT_ASSIST_ANY	= "%s 主dps沒有協助任何 MT"
XPERL_STATS_HEALERS_MT1		= "%s 主治療者在協助 %s"
XPERL_STATS_HEALERS_ANY		= "%s 主治療者在協助其他 MTs"
XPERL_STATS_HEALERS_NON_MT	= "%s 主治療者不在協助其他 MTs"

XPERL_XS_TARGET			= "%s 的目標"
XPERL_NO_TARGET			= "沒有目標"

XPERL_TITLE_MT_LONG		= "MT 目標"
XPERL_TITLE_MT_SHORT		= "MT"
XPERL_TITLE_WARRIOR_LONG	= "戰士目標"
XPERL_TITLE_WARRIOR_SHORT	= "坦克"

XPERL_TITLE_OTHERS		= "其他目標"
XPERL_TARGET_STATISTICS		= "目標統計"

XPERL_KEYHELP1			= "你可以設置一個快捷鍵"
XPERL_KEYHELP2			= "選中第一個非坦克目標"

XPERL_FOOTER_MORE		= "%d 尚未標示"
XPERL_TO_TARGET			= "%s 選取目標"

XPERL_HELPER_NEEDPROMOTE	= "你必須接受提升後才能設定主要協助對象"
XPERL_HELPER_MASET		= "主要協助對象設為 %s"
XPERL_HELPER_MACLEAR		= "主要協助對象 |c00FF0000已清除!"
XPERL_HELPER_MAREMOVED		= "坦克列表中沒有找到主要協助 %s - 移除!"
XPERL_HELPER_MAREMOTESET	= "%s 分配主要協助對象是 %s"

XPERL_HELPER_FINDFOUND		= "使用 FIND 來搜尋適合的目標. ('|c00007F00/xp find|r' 可清除)."
XPERL_HELPER_FINDCLEARED	= "Find |c00FF0000已清除!|r"
XPERL_HELPER_FINDSET		= "Find 設置為 %s. ('|c00007F00/xp find|r' 可清除)."

end
