OZ_PRESETS = {
	["WARLOCK"] = {
		["Raid View"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Raid",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{2,"Unending Breath","Breathing Spell_Shadow_DemonBreath"},
				{2,"Detect Lesser Invisibility", "Spell_Shadow_DetectLesserInvisibility"},
				{2,"Detect Invisibility", "Spell_Shadow_DetectInvisibility"},
				{4,"Soulstone", "Spell_Shadow_SoulGem"},
			},
		},
		["SoulStones"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6},
			["maxBars"] = 10,
			["active"] = 1,
			["buffsMob"] = {},
			["sort2"] = 0,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 1,
			["minBars"] = 0,
			["heading"] = {0,0,0},
			["refresh"] = 0.5,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Soulstones",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 1,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notbuffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1,},
			["buffsPlayer"] = {
				[1] = {4,"Soulstone","Interface\\Icons\\Spell_Shadow_SoulGem"},
			},
		},
	},
	["MAGE"] = {
		["Raid View"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Raid",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{4,"Arcane Brilliance", "Spell_Holy_ArcaneIntellect"},
				{4,"Arcane Intellect", "Spell_Holy_MagicalSentry"},
				{3,"Dampen Magic", "Spell_Nature_AbolishMagic"},
				{3,"Amplify Magic", "Spell_Holy_FlashHeal"},
			},
		},
		["Buff Me"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 1,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Buff me",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 0,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 0,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 0,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{4,"Arcane Brilliance", "Spell_Holy_ArcaneIntellect"},
				{4,"Arcane Intellect", "Spell_Holy_MagicalSentry"},
			},
		},
	},

	["PRIEST"] = {
		["Raid View"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Raid",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{3,"Shadow Protection", "Spell_Shadow_AntiShadow"},
				{3,"Prayer of Shadow Protection", "Spell_Shadow_DeadofNight"},
				{3,"Power Word: Fortitude", "Spell_Holy_WordFortitude"},
				{3,"Prayer Of Fortitude", "Spell_Holy_PrayerOfFortitude"},
				{3,"Divine Spirit", "Spell_Holy_DivineSpirit"},
				{3,"Prayer of Spirit", "Spell_Holy_PrayerofSpirit"},
				{3,"Power Word: Shield", "Spell_Holy_PowerWordShield"},
				{3,"Renew", "Spell_Holy_Renew"},
				{3,"Power Infusion", "Spell_Holy_PowerInfusion"},
				{4,"Weakened Soul", "Spell_Holy_AshesToAshes"},
				{1,"Rejuvenation", "Spell_Nature_Rejuvenation"},
				{1,"Regrowth", "Spell_Nature_ResistNature"},
			},
		},
		["Buff Me"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 1,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Buff me",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 0,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 0,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 0,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{3,"Power Word: Fortitude", "Spell_Holy_WordFortitude"},
				{3,"Prayer Of Fortitude", "Spell_Holy_PrayerOfFortitude"},
			},
		},
	},

	["DRUID"] = {
		["Raid View"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Raid",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{2,"Mark of the Wild/Gift of the Wild", "Spell_Nature_Regeneration"},
				{2,"Rejuvenation", "Spell_Nature_Rejuvenation"},
				{2,"Regrowth", "Spell_Nature_ResistNature"},
				{1,"Power Word: Shield", "Spell_Holy_PowerWordShield"},
				{1,"Renew", "Spell_Holy_Renew"},
				{2,"Abolish Poison", "Spell_Nature_NullifyPoison_02"},
				{1,"Thorns","Spell_Nature_Thorns"},
			},
		},
		["Innervate Me"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6},
			["outlineNames"] = 1,
			["maxBars"] = 8,
			["active"] = 1,
			["barHeight"] = 18,
			["titleHeight"] = 20,
			["sort2"] = 5,
			["sort1"] = 1,
			["classNames"] = 1,
			["textSize"] = 11,
			["colour"] = 3,
			["minBars"] = 0,
			["heading"] = {5,0,0},
			["icon"] = 1,
			["buttonSize"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["refresh"] = 1,
			["input"] = 2,
			["width"] = 136,
			["sort3"] = 0,
			["buffSize"] = 1,
			["valueType"] = 1,
			["buffPos"] = 2,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 0.33,
			},
			["namePos"] = 1,
			["text"] = "Innervate",
			["buffsMob"] = {
			},
			["buffsPlayer"] = {
			},
		},
		["Buff Me"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 1,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Buff me",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 0,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 0,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 0,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{2,"Mark of the Wild/Gift of the Wild", "Spell_Nature_Regeneration"},
			},
		},
	},

	["PALADIN"] = {
		["Raid View"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Raid",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{1,"Power Word: Shield", "Spell_Holy_PowerWordShield"},
				{1,"Renew", "Spell_Holy_Renew"},
				{1,"Rejuvenation", "Spell_Nature_Rejuvenation"},
				{1,"Regrowth", "Spell_Nature_ResistNature"},
				{2,"Blessing of Kings", "Spell_Magic_MageArmor"},
				{2,"Blessing of Might", "Spell_Holy_FistOfJustice"},
				{2,"Blessing of Wisdom", "Spell_Holy_SealOfWisdom"},
				{2,"Blessing of Salvation", "Spell_Holy_SealOfSalvation"},
				{2,"Blessing of Light", "Spell_Holy_PrayerOfHealing02"},
				{2,"Blessing of Freedom", "Spell_Holy_SealOfValor"},
				{2,"Blessing of Protection", "Spell_Holy_SealOfProtection"},
				{2,"Blessing of Sacrifice", "Spell_Holy_SealOfSacrifice"},
				{3,"Greater Blessing of Might", "Spell_Holy_GreaterBlessingofKings"},
				{3,"Greater Blessing of Wisdom", "Spell_Holy_GreaterBlessingofWisdom"},
				{3,"Greater Blessing of Salvation", "Spell_Holy_GreaterBlessingofSalvation"},
				{3,"Greater Blessing of Light", "Spell_Holy_GreaterBlessingofLight"},
				{3,"Greater Blessing of Sanctuary", "Spell_Holy_GreaterBlessingofSanctuary"},
				{3,"Greater Blessing of Kings", "Spell_Magic_GreaterBlessingofKings"},
				{4,"Divine Intervention", "Spell_Nature_TimeStop"},
			},
		},
		["Buff Me (Kings)"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 1,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Buff me",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 0,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 0,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 0,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{2,"Blessing of Kings", "Spell_Magic_MageArmor"},
				{3,"Greater Blessing of Kings", "Spell_Magic_GreaterBlessingofKings"},
			},
		},
	},

	["GENERAL"] = {
		["Raid View"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6,},
			["outlineNames"] = 1,
			["maxBars"] = 40,
			["active"] = 1,
			["classNames"] = 1,
			["buffsMob"] = {},
			["sort2"] = 3,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["titleHeight"] = 20,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {3,0,0},
			["refresh"] = 1,
			["buttonSize"] = 16,
			["icon"] = 1,
			["text"] = "Raid",
			["input"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["buffPos"] = 2,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["notcurable"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["dead"] = 1,
					["offline"] = 1,
					["healthy"] = 1,
					["outofrange"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["ROGUE"] = 1,
					["HEALERS"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["WARLOCK"] = 1,
				},
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
			},
			["namePos"] = 1,
			["barHeight"] = 16,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {
				{4,"Divine Intervention", "Spell_Nature_TimeStop"},
				{3,"Soulstone", "Spell_Shadow_SoulGem"},
				{1,"Fire Protection", "Spell_Fire_FireArmor"},
			},
		},
		["Raid Mana"] = {
			["bottomCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 0,["b"] = 0.6},
			["maxBars"] = 8,
			["active"] = 1,
			["buffsMob"] = {},
			["sort2"] = 0,
			["textSize"] = 11,
			["sort1"] = 4,
			["titleHeight"] = 20,
			["icon"] = 1,
			["colour"] = 3,
			["minBars"] = 0,
			["heading"] = {
				[1] = 0,
				[2] = 0,
				[3] = 0,
			},
			["barHeight"] = 19,
			["buttonSize"] = 16,
			["namePos"] = 1,
			["refresh"] = 1,
			["text"] = "Class Mana",
			["width"] = 126,
			["sort3"] = 0,
			["buffSize"] = 1,
			["valueType"] = 1,
			["buffPos"] = 2,
			["filter"] = {
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["outofrange"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["healthy"] = 1,
					["notcurable"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["HEALERS"] = 1,
					["WARLOCK"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
				},
			},
			["input"] = 4,
			["topCol"] = {["a"] = 0.5,["r"] = 0,["g"] = 1,["b"] = 1},
			["buffsPlayer"] = {},
		},
		["Cure Me"] = {
			["bottomCol"] = {
				["a"] = 0.5,
				["r"] = 0,
				["g"] = 0,
				["b"] = 0.6,
			},
			["maxBars"] = 20,
			["active"] = 1,
			["topCol"] = {
				["a"] = 0.5,
				["r"] = 0,
				["g"] = 1,
				["b"] = 1,
			},
			["buffsMob"] = {},
			["sort2"] = 5,
			["rangeFade"] = 1,
			["sort1"] = 1,
			["textSize"] = 10,
			["colour"] = 2,
			["minBars"] = 0,
			["heading"] = {5,0,0},
			["icon"] = 1,
			["buttonSize"] = 16,
			["barHeight"] = 16,
			["text"] = "Cure Me",
			["buffPos"] = 1,
			["width"] = 120,
			["sort3"] = 0,
			["namePos"] = 1,
			["buffSize"] = 1,
			["valueType"] = 1,
			["filter"] = {
				["group"] = {1,1,1,1,1,1,1,1},
				["injuredVal"] = 1,
				["status"] = {
					["inrange"] = 1,
					["close"] = 1,
					["curable"] = 1,
					["buffed"] = 1,
					["online"] = 1,
					["notbuffed"] = 1,
					["injured"] = 1,
					["outofrange"] = 1,
					["healthy"] = 1,
				},
				["class"] = {
					["HUNTER"] = 1,
					["WARRIOR"] = 1,
					["TARGET"] = 1,
					["PALADIN"] = 1,
					["MAGE"] = 1,
					["TANKS"] = 1,
					["PRIEST"] = 1,
					["HEALERS"] = 1,
					["WARLOCK"] = 1,
					["MELEE"] = 1,
					["SHAMAN"] = 1,
					["DRUID"] = 1,
					["RANGED"] = 1,
					["ROGUE"] = 1,
				},
			},
			["input"] = 1,
			["refresh"] = 0.5,
			["titleHeight"] = 20,
			["buffsPlayer"] = {
			},
		},
	},
};
