
Zorlen_DE_FileBuildNumber = 681

-- German Translation
-- If you want to translate this to another language, make sure the names of buffs and abilities are *EXACTLY* the same as in-game. Spelling, punctuation, upper/lowercase letters, etc. MUST BE EXACT. Also, any 'foreign' characters must be converted to UNICODE.
-- Unicode resource:
-- http://www.utf8-chartable.de/unicode-utf8-table.pl?start=128&number=1024&utf8=dec
-- http://home.tiscali.nl/t876506/utf8tbl.html
-- http://www.allegro-c.de/unicode/zcodes.htm
-- You will need to use the UTF-8 decimal numbers with a back slash in front of them in the same way that Å is represented by: \195\133


-- To lower the upkeep we will not be adding Localization for english words that do not break compatibility in other game clients.
-- This Localization is only added for compatibility so that it may work in non english game clients and not as a translation.

if GetLocale() == "deDE" then
-- All file Localization
	--LOCALIZATION_ZORLEN_EatMacroName = ""
	--LOCALIZATION_ZORLEN_DrinkMacroName = ""
	--LOCALIZATION_ZORLEN_Conjured = ""
	--LOCALIZATION_ZORLEN_Water = ""
	--LOCALIZATION_ZORLEN_AllConjuredWater = ""
	--LOCALIZATION_ZORLEN_well_fed = ""
	LOCALIZATION_ZORLEN_HitsOrCritsArray = {"(.+) von Euch trifft (.*) f\195\188r (%d+)", "(.+) trifft (.*). Schaden: (%d+)", "(.+) trifft (.*) kritisch: (%d+)"}
	LOCALIZATION_ZORLEN_EnemyDies = "(.*)"
	LOCALIZATION_ZORLEN_Rank = "Rang"
	LOCALIZATION_ZORLEN_sit = "sitzen"
	LOCALIZATION_ZORLEN_You_dodge = "Ausgewichen"
	LOCALIZATION_ZORLEN_immune = "(.+).*(.*).* Immun"
	LOCALIZATION_ZORLEN_no_weapons_equipped = "(.+).*Keine Waffen angelegt"
	LOCALIZATION_ZORLEN_dodged = "Pariert"
	--LOCALIZATION_ZORLEN_dodges = ""
	LOCALIZATION_ZORLEN_pet_is_not_dead = "Euer Begleiter ist nicht tot"
	LOCALIZATION_ZORLEN_pet_is_dead = "Euer Begleiter ist tot"
	LOCALIZATION_ZORLEN_A_more_powerful_spell_is_already_active = "(.+).*Ein m\195\164chtigerer Spruch ist bereits aktiv"
	--LOCALIZATION_ZORLEN_Asleep = ""
	LOCALIZATION_ZORLEN_RequiresLevel = "Ben\195\182tigt Stufe"
	
	--LOCALIZATION_ZORLEN_GreaterHealingWard = ""
	--LOCALIZATION_ZORLEN_LavaSpoutTotem = ""
	
	LOCALIZATION_ZORLEN_HealingBonusWordsArray = {"Heilung", "Heilzauber"}
	LOCALIZATION_ZORLEN_HealingBonusPhraseArray = {"Erh\195\131\194\182ht durch Zauber und Effekte verursachte Heilung um bis zu (%d+)%.", "Erh\195\131\194\182ht die durch Zauber und Effekte verursachte Heilung um bis zu (%d+)%."}
	
	LOCALIZATION_ZORLEN_SpellDamageAndHealingBonusWordsArray = {"Heilung und Zauberschaden", "Zauberschaden und Heilung"}
	LOCALIZATION_ZORLEN_SpellDamageAndHealingBonusPhraseArray = {"Erh\195\131\194\182ht durch Zauber und magische Effekte zugef\195\131\194\188gten Schaden und Heilung um bis zu (%d+)%."}
	
	LOCALIZATION_ZORLEN_SpellDamageBonusWordsArray = {"Zauberschaden", "Zauberschaden erh\195\131\194\182hen"}
	LOCALIZATION_ZORLEN_SpellDamageBonusPhraseArray = {}
	LOCALIZATION_ZORLEN_BrilliantWizardOil = "Hervorragendes Zauber\195\131\194\182l"
	LOCALIZATION_ZORLEN_WizardOil = "Zauber\195\131\194\182l"
	LOCALIZATION_ZORLEN_LesserWizardOil = "Geringes Zauber\195\131\194\182l"
	LOCALIZATION_ZORLEN_MinorWizardOil = "Schwaches Zauber\195\131\194\182l"
	--LOCALIZATION_ZORLEN_SupremePower = ""
	--LOCALIZATION_ZORLEN_GreaterArcaneElixir = ""
	LOCALIZATION_ZORLEN_ArcaneElixir = "Arkanes Elixier"
	
	LOCALIZATION_ZORLEN_ShadowDamageBonusWordsArray = {"Schattenschaden"}
	LOCALIZATION_ZORLEN_ShadowDamageBonusPhraseArray = {}
	--LOCALIZATION_ZORLEN_ShadowPower = ""
	
-- Battleground Names
	--LOCALIZATION_ZORLEN_WarsongGulch = ""
	--LOCALIZATION_ZORLEN_AlteracValley = ""
	--LOCALIZATION_ZORLEN_ArathiBasin = ""
	
-- Raid Target Names
	LOCALIZATION_ZORLEN_WhiteSkull = "Wei\195\159er Totenkopf"
	LOCALIZATION_ZORLEN_RedX = "Rotes X"
	LOCALIZATION_ZORLEN_BlueSquare = "Blaues Quadrat"
	LOCALIZATION_ZORLEN_WhiteCrescentMoon = "Wei\195\159er Sichelf\195\182rmiger Mond"
	LOCALIZATION_ZORLEN_GreenTriangle = "Gruenes Dreieck"
	LOCALIZATION_ZORLEN_PurpleDiamond = "Violetter Diamant"
	LOCALIZATION_ZORLEN_OrangeCircle = "Orangener Kreis"
	LOCALIZATION_ZORLEN_YellowStar = "Gelber Stern"



-- Food Item Tool Tip Text:
	--LOCALIZATION_ZORLEN_FoodToolTipTextAny = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText3180 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText2148 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText1392 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText874 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText552 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText243 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText61 = ""
-- Drink Item Tool Tip Text:
	--LOCALIZATION_ZORLEN_DrinkToolTipTextAny = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText4200 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText2934 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText1992 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText1344 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText835 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText436 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText151 = ""



-- Zorlen_Other.lua file Localization
	LOCALIZATION_ZORLEN_Attack = "Angreifen"
	LOCALIZATION_ZORLEN_Throw = "Wurf"
	--LOCALIZATION_ZORLEN_ShootBow = ""
	--LOCALIZATION_ZORLEN_ShootCrossbow = ""
	--LOCALIZATION_ZORLEN_ShootGun = ""
	LOCALIZATION_ZORLEN_Shoot = "Schie\195\159en"
-- Human Racial
	LOCALIZATION_ZORLEN_Perception = "Wachsamkeit"
-- Dwarf Racial
	LOCALIZATION_ZORLEN_FindTreasure = "Schatzsucher"
	LOCALIZATION_ZORLEN_Stoneform = "Steingestalt"
-- Gnome Racial
	LOCALIZATION_ZORLEN_EscapeArtist = "Entfesselungsk\195\188nstler"
-- Night Elf Racial
	LOCALIZATION_ZORLEN_Shadowmeld = "Schattenhaftigkeit"
-- Orc Racial
	LOCALIZATION_ZORLEN_BloodFury = "Kochendes Blut"
-- Undead Racial
	LOCALIZATION_ZORLEN_Cannibalize = "Kannibalismus"
	LOCALIZATION_ZORLEN_WillOfTheForsaken = "Wille der Verlassenen"
-- Tauren Racial
	LOCALIZATION_ZORLEN_WarStomp = "Kriegsdonner"
-- Troll Racial
	LOCALIZATION_ZORLEN_Berserking = "Berserker"



-- Zorlen_Pets.lua file Localization
-- Hunter Pets
	LOCALIZATION_ZORLEN_Dash = "Spurt"
	LOCALIZATION_ZORLEN_Dive = "Sturzflug"
	LOCALIZATION_ZORLEN_Bite = "Bei\195\159en"
	LOCALIZATION_ZORLEN_Claw = "Klaue"
	LOCALIZATION_ZORLEN_Cower = "Ducken"
	LOCALIZATION_ZORLEN_Growl = "Knurren"
	LOCALIZATION_ZORLEN_Prowl = "Schleichen"
	LOCALIZATION_ZORLEN_Charge = "Sturmangriff"
	LOCALIZATION_ZORLEN_Screech = "Schrei"
	LOCALIZATION_ZORLEN_FuriousHowl = "Wutgeheul"
	LOCALIZATION_ZORLEN_LightningBreath = "Blitzschlagatem"
	LOCALIZATION_ZORLEN_ShellShield = "Panzerschild"
	LOCALIZATION_ZORLEN_Thunderstomp = "Donnerstampfer"
	LOCALIZATION_ZORLEN_ScorpidPoison = "Scorpidgift"
-- Warlock Pets
	LOCALIZATION_ZORLEN_Felhunter = "Teufelsj\195\164ger"
	LOCALIZATION_ZORLEN_Imp = "Wichtel"
	LOCALIZATION_ZORLEN_Succubus = "Succubus"
	LOCALIZATION_ZORLEN_Voidwalker = "Leerwandler"
	LOCALIZATION_ZORLEN_BloodPact = "Blutpakt"
	LOCALIZATION_ZORLEN_FireShield = "Feuerschild"
	LOCALIZATION_ZORLEN_Firebolt = "Feuerblitz"
	LOCALIZATION_ZORLEN_PhaseShift = "Phasenverschiebung"
	LOCALIZATION_ZORLEN_ConsumeShadows = "Schatten verzehren"
	LOCALIZATION_ZORLEN_Sacrifice = "Opferung"
	LOCALIZATION_ZORLEN_Suffering = "Leiden"
	LOCALIZATION_ZORLEN_Torment = "Qual"
	LOCALIZATION_ZORLEN_DevourMagic = "Magie verzehren"
	LOCALIZATION_ZORLEN_Paranoia = "Paranoia"
	LOCALIZATION_ZORLEN_SpellLock = "Zaubersperre"
	LOCALIZATION_ZORLEN_TaintedBlood = "Besudeltes Blut"
	LOCALIZATION_ZORLEN_LashOfPain = "Schmerzenspeitsche"
	LOCALIZATION_ZORLEN_Seduction = "Verf\195\188hrung"
	LOCALIZATION_ZORLEN_SoothingKiss = "Bes\195\164nftigender Kuss"
	LOCALIZATION_ZORLEN_LesserInvisibility = "Geringe Unsichtbarkeit"



-- Zorlen_Hunter.lua file Localization
	--LOCALIZATION_ZORLEN_FeedPet = ""
	LOCALIZATION_ZORLEN_ImprovedAspectOfTheHawk = "Verbesserte Aspekt des Falken"
	LOCALIZATION_ZORLEN_ImprovedMendPet = "Verbesserte Tier heilen"
	LOCALIZATION_ZORLEN_MendPet = "Tier heilen"
	LOCALIZATION_ZORLEN_CallPet = "Tier rufen"
	LOCALIZATION_ZORLEN_RevivePet = "Tier wiederbeleben"
	LOCALIZATION_ZORLEN_DismissPet = "Tier freigeben"
	LOCALIZATION_ZORLEN_AutoShot = "Automatischer Schuss"
	LOCALIZATION_ZORLEN_MongooseBite = "Mungobiss"
	LOCALIZATION_ZORLEN_ArcaneShot = "Arkaner Schuss"
	LOCALIZATION_ZORLEN_ConcussiveShot = "Ersch\195\188tternder Schuss"
	LOCALIZATION_ZORLEN_RaptorStrike = "Raptorsto\195\159"
	LOCALIZATION_ZORLEN_SerpentSting = "Schlangenbiss"
	LOCALIZATION_ZORLEN_ViperSting = "Vipernbiss"
	LOCALIZATION_ZORLEN_ScorpidSting = "Skorpidstich"
	LOCALIZATION_ZORLEN_DistractingShot = "Ablenkender Schuss"
	LOCALIZATION_ZORLEN_AimedShot = "Gezielter Schuss"
	LOCALIZATION_ZORLEN_HuntersMark = "Mal des J\195\164gers"
	LOCALIZATION_ZORLEN_AspectOfTheHawk = "Aspekt des Falken"
	LOCALIZATION_ZORLEN_AspectOfTheMonkey = "Aspekt des Affen"
	LOCALIZATION_ZORLEN_AspectOfTheCheetah = "Aspekt des Geparden"
	LOCALIZATION_ZORLEN_AspectOfThePack = "Aspekt des Rudels"
	LOCALIZATION_ZORLEN_AspectOfTheWild = "Aspekt der Wildniss"
	LOCALIZATION_ZORLEN_AspectOfTheBeast = "Aspekt des Wildtieres"
	LOCALIZATION_ZORLEN_WingClip = "Zurechtstutzen"
	LOCALIZATION_ZORLEN_FreezingTrap = "Eisk\195\164ltefalle"
	LOCALIZATION_ZORLEN_FrostTrap = "Frostfalle"
	LOCALIZATION_ZORLEN_ExplosiveTrap = "Sprengfalle"
	LOCALIZATION_ZORLEN_ImmolationTrap = "Feuerbrandfalle"
	LOCALIZATION_ZORLEN_FeignDeath = "Totstellen"
	LOCALIZATION_ZORLEN_Counterattack = "Gegenangriff"
	LOCALIZATION_ZORLEN_TranquilizingShot = "Einlullender Schuss"
	LOCALIZATION_ZORLEN_Disengage = "R\195\188ckzug"
	LOCALIZATION_ZORLEN_EyesOfTheBeast = "Augen des Wildtiers"
	LOCALIZATION_ZORLEN_BeastLore = "Wildtierkunde"
	LOCALIZATION_ZORLEN_TrackBeasts = "Wildtiere aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackDemons = "D\195\164monen aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackDragonkin = "Drachkin aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackElementals = "Elementare aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackGiants = "Riesen aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackHumanoids = "Humanoide aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackUndead = "Untote aufsp\195\188ren"
	LOCALIZATION_ZORLEN_TrackHidden = "Verborgenes aufsp\195\188ren"
	LOCALIZATION_ZORLEN_BestialWrath = "Zorn des Wildtiers"
	LOCALIZATION_ZORLEN_TrueshotAura = "Aura des Volltreffers"
	LOCALIZATION_ZORLEN_ScatterShot = "Streuschuss"
	LOCALIZATION_ZORLEN_WyvernSting = "Stich des Fl\195\188geldrachen"
	LOCALIZATION_ZORLEN_Deterrence = "Abschreckung"
	LOCALIZATION_ZORLEN_EagleEye = "Adlerauge"
	LOCALIZATION_ZORLEN_RapidFire = "Schnellfeuer"
	LOCALIZATION_ZORLEN_MultiShot = "Mehrfachschuss"
	LOCALIZATION_ZORLEN_Flare = "Leuchtfeuer"
	LOCALIZATION_ZORLEN_ScareBeast = "Wildtier \195\164ngstigen"
	LOCALIZATION_ZORLEN_Volley = "Salve"
	LOCALIZATION_ZORLEN_Intimidation = "Einsch\195\188chterung"



-- Zorlen_Warlock.lua file Localization
	--LOCALIZATION_ZORLEN_SoulSiphon = ""
	--LOCALIZATION_ZORLEN_SeedOfCorruption = ""
	--LOCALIZATION_ZORLEN_FelArmor = ""
	--LOCALIZATION_ZORLEN_RitualOfSouls = ""
	--LOCALIZATION_ZORLEN_Soulshatter = ""
	--LOCALIZATION_ZORLEN_Incinerate = ""
	--LOCALIZATION_ZORLEN_UnstableAffliction = ""
	--LOCALIZATION_ZORLEN_DemonicAegis = ""
	--LOCALIZATION_ZORLEN_SummonFelGuard = ""
	--LOCALIZATION_ZORLEN_Shadowfury = ""
	
	--LOCALIZATION_ZORLEN_Bane = ""
	LOCALIZATION_ZORLEN_AmplifyCurse = "Fluch verst\195\164rken"
	LOCALIZATION_ZORLEN_CurseOfAgony = "Fluch der Pein"
	LOCALIZATION_ZORLEN_CurseOfDoom = "Fluch der Verdammnis"
	LOCALIZATION_ZORLEN_CurseOfShadow = "Fluch der Schatten"
	LOCALIZATION_ZORLEN_CurseOfTheElements = "Fluch der Elemente"
	LOCALIZATION_ZORLEN_CurseOfWeakness = "Fluch der Schw\195\164che"
	LOCALIZATION_ZORLEN_CurseOfExhaustion = "Fluch der Ersch\195\182pfung"
	LOCALIZATION_ZORLEN_CurseOfRecklessness = "Fluch der Tollk\195\188hnheit"
	LOCALIZATION_ZORLEN_CurseOfTongues = "Fluch der Sprachen"
	LOCALIZATION_ZORLEN_Corruption = "Verderbnis"
	LOCALIZATION_ZORLEN_ImprovedCorruption = "Verbesserte Verderbnis"
	LOCALIZATION_ZORLEN_Immolate = "Feuerbrand"
	LOCALIZATION_ZORLEN_SiphonLife = "Lebensentzug"
	LOCALIZATION_ZORLEN_DrainLife = "Blutsauger"
	LOCALIZATION_ZORLEN_DrainMana = "Mana entziehen"
	LOCALIZATION_ZORLEN_Hellfire = "H\195\182llenfeuer"
	LOCALIZATION_ZORLEN_RainOfFire = "Feuerregen"
	LOCALIZATION_ZORLEN_DrainSoul = "Seelendieb"
	LOCALIZATION_ZORLEN_LifeTap = "Aderlass"
	LOCALIZATION_ZORLEN_ImprovedLifeTap = "Verbesserter Aderlass"
	LOCALIZATION_ZORLEN_DarkPact = "Dunkler Pakt"
	LOCALIZATION_ZORLEN_Nightfall = "Einbruch der Nacht"
	LOCALIZATION_ZORLEN_ShadowBolt = "Schattenblitz"
	LOCALIZATION_ZORLEN_Banish = "Verbannen"
	LOCALIZATION_ZORLEN_Conflagrate = "Feuersbrunst"
	LOCALIZATION_ZORLEN_CreateFirestoneLesser = "Feuerstein herstellen (gering)"
	LOCALIZATION_ZORLEN_CreateFirestone = "Feuerstein herstellen"
	LOCALIZATION_ZORLEN_CreateFirestoneGreater = "Feuerstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN_CreateFirestoneMajor = "Feuerstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN_CreateHealthstoneMinor = "Gesundheitsstein herstellen (schwach)"
	LOCALIZATION_ZORLEN_CreateHealthstoneLesser = "Gesundheitsstein herstellen (gering)"
	LOCALIZATION_ZORLEN_CreateHealthstone = "Gesundheitsstein herstellen"
	LOCALIZATION_ZORLEN_CreateHealthstoneGreater = "Gesundheitsstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN_CreateHealthstoneMajor = "Gesundheitsstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN_CreateSoulstoneMinor = "Seelenstein herstellen (schwach)"
	LOCALIZATION_ZORLEN_CreateSoulstoneLesser = "Seelenstein herstellen (gering)"
	LOCALIZATION_ZORLEN_CreateSoulstone = "Seelenstein herstellen"
	LOCALIZATION_ZORLEN_CreateSoulstoneGreater = "Seelenstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN_CreateSoulstoneMajor = "Seelenstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN_CreateSpellstone = "Zauberstein herstellen"
	LOCALIZATION_ZORLEN_CreateSpellstoneGreater = "Zauberstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN_CreateSpellstoneMajor = "Zauberstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN_DeathCoil = "Todesmantel"
	LOCALIZATION_ZORLEN_DemonArmor = "D\195\164monenr\195\188stung"
	LOCALIZATION_ZORLEN_DemonSkin = "D\195\164monenhaut"
	LOCALIZATION_ZORLEN_DemonicSacrifice = "D\195\164monenopferung"
	LOCALIZATION_ZORLEN_DetectLesserInvisibility = "Geringe Unsichtbarkeit entdecken"
	LOCALIZATION_ZORLEN_DetectInvisibility = "Unsichtbarkeit entdecken"
	LOCALIZATION_ZORLEN_DetectGreaterInvisibility = "Gro\195\159e Unsichtbarkeit entdecken"
	LOCALIZATION_ZORLEN_EnslaveDemon = "D\195\164monensklave"
	LOCALIZATION_ZORLEN_EyeOfKilrogg = "Auge von Kilrogg"
	LOCALIZATION_ZORLEN_Fear = "Furcht"
	LOCALIZATION_ZORLEN_FelDomination = "Teufelsbeherrschung"
	LOCALIZATION_ZORLEN_HealthFunnel = "Lebenslinie"
	LOCALIZATION_ZORLEN_HowlOfTerror = "Schreckgeheul"
	LOCALIZATION_ZORLEN_Inferno = "Inferno"
	LOCALIZATION_ZORLEN_RitualOfDoom = "Ritual der Verdammnis"
	LOCALIZATION_ZORLEN_RitualOfSummoning = "Ritual der Herbeirufung"
	LOCALIZATION_ZORLEN_SearingPain = "Sengender Schmerz"
	LOCALIZATION_ZORLEN_SenseDemons = "D\195\164monen sp\195\188ren"
	LOCALIZATION_ZORLEN_ShadowWard = "Schatten-Zauberschutz"
	LOCALIZATION_ZORLEN_Shadowburn = "Schattenbrand"
	LOCALIZATION_ZORLEN_SoulFire = "Seelenfeuer"
	LOCALIZATION_ZORLEN_SoulLink = "Seelenverbindung"
	--LOCALIZATION_ZORLEN_SummonDreadsteed = ""
	LOCALIZATION_ZORLEN_SummonFelhunter = "Teufelsj\195\164ger beschw\195\182ren"
	--LOCALIZATION_ZORLEN_SummonFelsteed = ""
	LOCALIZATION_ZORLEN_SummonImp = "Wichtel beschw\195\182ren"
	LOCALIZATION_ZORLEN_SummonSuccubus = "Succubus beschw\195\182ren"
	LOCALIZATION_ZORLEN_SummonVoidwalker = "Leerwandler beschw\195\182ren"
	LOCALIZATION_ZORLEN_UnendingBreath = "Unendlicher Atem"
	--LOCALIZATION_ZORLEN_FelConcentration = ""



-- Zorlen_Druid.lua file Localization
	LOCALIZATION_ZORLEN_TravelForm = "Reisegestalt"
	LOCALIZATION_ZORLEN_MoonkinForm = "Moonkingestalt"
	LOCALIZATION_ZORLEN_BearForm = "B\195\164rengestalt"
	LOCALIZATION_ZORLEN_DireBearForm = "Terrorb\195\164rengestalt"
	LOCALIZATION_ZORLEN_CatForm = "Katzengestalt"
	LOCALIZATION_ZORLEN_AquaticForm = "Wassergestalt"
	LOCALIZATION_ZORLEN_ChallengingRoar = "Knurren"
	LOCALIZATION_ZORLEN_DemoralizingRoar = "Demoralisierendes Gebr\195\188ll"
	LOCALIZATION_ZORLEN_AbolishPoison = "Vergiftung aufheben"
	LOCALIZATION_ZORLEN_Barkskin = "Baumrinde"
	LOCALIZATION_ZORLEN_Bash = "Hieb"
	LOCALIZATION_ZORLEN_Claw = "Klaue"
	LOCALIZATION_ZORLEN_Cower = "Ducken"
	LOCALIZATION_ZORLEN_Dash = "Spurt"
	LOCALIZATION_ZORLEN_Enrage = "Wutanfall"
	LOCALIZATION_ZORLEN_EntanglingRoots = "Wucherwurzeln"
	LOCALIZATION_ZORLEN_FaerieFire = "Feenfeuer"
	LOCALIZATION_ZORLEN_FaerieFireFeral = "Feenfeuer (Tiergestalt)"
	LOCALIZATION_ZORLEN_FeralCharge = "Wilde Attacke"
	LOCALIZATION_ZORLEN_FerociousBite = "Wilder Biss"
	LOCALIZATION_ZORLEN_FrenziedRegeneration = "Rasende Regeneration"
	LOCALIZATION_ZORLEN_GiftOfTheWild = "Gabe der Wildnis"
	LOCALIZATION_ZORLEN_HealingTouch = "Heilende Ber\195\188hrung"
	LOCALIZATION_ZORLEN_Hibernate = "Winterschlaf"
	LOCALIZATION_ZORLEN_Hurricane = "Hurrikan"
	LOCALIZATION_ZORLEN_Innervate = "Anregen"
	LOCALIZATION_ZORLEN_InsectSwarm = "Insektenschwarm"
	LOCALIZATION_ZORLEN_LeaderOfThePack = "Rudelf\195\188hrer"
	LOCALIZATION_ZORLEN_MarkOfTheWild = "Mal der Wildnis"
	LOCALIZATION_ZORLEN_Maul = "Zermalmen"
	LOCALIZATION_ZORLEN_Moonfire = "Mondfeuer"
	LOCALIZATION_ZORLEN_NaturesGrasp = "Griff der Natur"
	LOCALIZATION_ZORLEN_NaturesSwiftness = "Schnelligkeit der Natur"
	LOCALIZATION_ZORLEN_OmenOfClarity = "Omen der Klarsicht"
	LOCALIZATION_ZORLEN_Pounce = "Anspringen"
	LOCALIZATION_ZORLEN_Prowl = "Schleichen"
	LOCALIZATION_ZORLEN_Rake = "Krallenhieb"
	LOCALIZATION_ZORLEN_Ravage = "Verheeren"
	LOCALIZATION_ZORLEN_Rebirth = "Wiedergeburt"
	LOCALIZATION_ZORLEN_Regrowth = "Nachwachsen"
	LOCALIZATION_ZORLEN_Rejuvenation = "Verj\195\188ngung"
	--LOCALIZATION_ZORLEN_RemoveCurse = ""
	LOCALIZATION_ZORLEN_Rip = "Zerfetzen"
	LOCALIZATION_ZORLEN_Shred = "Schreddern"
	LOCALIZATION_ZORLEN_SootheAnimal = "Tier bes\195\164nftigen"
	LOCALIZATION_ZORLEN_Starfire = "Sternenfeuer"
	LOCALIZATION_ZORLEN_Swipe = "Prankenhieb"
	LOCALIZATION_ZORLEN_Thorns = "Dornen"
	LOCALIZATION_ZORLEN_TigersFury = "Tigerfuror"
	LOCALIZATION_ZORLEN_TrackHumanoids = "Humanoide aufsp\195\188ren"
	LOCALIZATION_ZORLEN_Tranquility = "Gelassenheit"
	LOCALIZATION_ZORLEN_Wrath = "Zorn"
	LOCALIZATION_ZORLEN_ImprovedWrath = "Verbesserter Zorn"
	LOCALIZATION_ZORLEN_ImprovedNaturesGrasp = "Verbesserter Griff der Natur"
	LOCALIZATION_ZORLEN_ImprovedEntanglingRoots = "Verbesserte Wucherwurzeln"
	LOCALIZATION_ZORLEN_ImprovedMoonfire = "Verbessertes Mondfeuer"
	LOCALIZATION_ZORLEN_NaturalWeapons = "Waffenbalance"
	LOCALIZATION_ZORLEN_NaturalShapeshifter = "Schnellwandlung"
	LOCALIZATION_ZORLEN_ImprovedThorns = "Verbesserte Dornen"
	LOCALIZATION_ZORLEN_NaturesReach = "Reichweite der Natur"
	LOCALIZATION_ZORLEN_Vengeance = "Rache"
	LOCALIZATION_ZORLEN_ImprovedStarfire = "Verbessertes Sternenfeuer"
	LOCALIZATION_ZORLEN_NaturesGrace = "Anmut der Natur"
	LOCALIZATION_ZORLEN_Moonglow = "Mondschein"
	LOCALIZATION_ZORLEN_Moonfury = "Mondfuror"
	LOCALIZATION_ZORLEN_Ferocity = "Wildheit"
	LOCALIZATION_ZORLEN_FeralAggression = "Wilde Aggression"
	LOCALIZATION_ZORLEN_FeralInstinct = "Instinkt der Wildnis"
	LOCALIZATION_ZORLEN_BrutalImpact = "Brutaler Hieb"
	LOCALIZATION_ZORLEN_ThickHide = "Dickes Fell"
	LOCALIZATION_ZORLEN_FelineSwiftness = "Katzenhafte Schnelligkeit"
	LOCALIZATION_ZORLEN_SharpenedClaws = "Gesch\195\164rfte Klauen"
	LOCALIZATION_ZORLEN_ImprovedShred = "Verbessertes Schreddern"
	LOCALIZATION_ZORLEN_PredatoryStrikes = "Raubtierschl\195\164ge"
	LOCALIZATION_ZORLEN_BloodFrenzy = "Blutraserei"
	LOCALIZATION_ZORLEN_PrimalFury = "Urfuror"
	LOCALIZATION_ZORLEN_SavageFury = "Ungez\195\164hmte Wut"
	LOCALIZATION_ZORLEN_HeartOfTheWild = "Herz der Wildnis"
	LOCALIZATION_ZORLEN_ImprovedMarkOfTheWild = "Verbessertes Mal der Wildnis"
	LOCALIZATION_ZORLEN_Furor = "Ingrimm"
	LOCALIZATION_ZORLEN_ImprovedHealingTouch = "Verbesserte Heilende Ber\195\188hrung"
	LOCALIZATION_ZORLEN_NaturesFocus = "Naturfokus"
	LOCALIZATION_ZORLEN_ImprovedEnrage = "Verbesserter Wutanfall"
	LOCALIZATION_ZORLEN_Reflection = "Reflexion"
	LOCALIZATION_ZORLEN_Subtlety = "Feingef\195\188hl"
	LOCALIZATION_ZORLEN_TranquilSpirit = "Gelassener Geist"
	LOCALIZATION_ZORLEN_ImprovedRejuvenation = "Verbesserte Verj\195\188ngung"
	LOCALIZATION_ZORLEN_GiftOfNature = "Geschenk der Natur"
	LOCALIZATION_ZORLEN_ImprovedTranquility = "Verbesserte Gelassenheit"
	LOCALIZATION_ZORLEN_ImprovedRegrowth = "Verbessertes Nachwachsen"
	LOCALIZATION_ZORLEN_Swiftmend = "Rasche Heilung"



-- Zorlen_Mage.lua file Localization
	--LOCALIZATION_ZORLEN_ConjuredCinnamonRoll = ""
	--LOCALIZATION_ZORLEN_ConjuredSweetRoll = ""
	--LOCALIZATION_ZORLEN_ConjuredSourdough = ""
	--LOCALIZATION_ZORLEN_ConjuredPumpernickel = ""
	--LOCALIZATION_ZORLEN_ConjuredRye = ""
	--LOCALIZATION_ZORLEN_ConjuredBread = ""
	--LOCALIZATION_ZORLEN_ConjuredMuffin = ""
	--LOCALIZATION_ZORLEN_ConjuredCrystalWater = ""
	--LOCALIZATION_ZORLEN_ConjuredSparklingWater = ""
	--LOCALIZATION_ZORLEN_ConjuredMineralWater = ""
	--LOCALIZATION_ZORLEN_ConjuredSpringWater = ""
	--LOCALIZATION_ZORLEN_ConjuredPurifiedWater = ""
	--LOCALIZATION_ZORLEN_ConjuredFreshWater = ""
	--LOCALIZATION_ZORLEN_ConjuredWater = ""
	--LOCALIZATION_ZORLEN_AmplifyMagic = ""
	--LOCALIZATION_ZORLEN_ArcaneBrilliance = ""
	--LOCALIZATION_ZORLEN_ArcaneExplosion = ""
	--LOCALIZATION_ZORLEN_ArcaneIntellect = ""
	--LOCALIZATION_ZORLEN_ArcaneMissiles = ""
	--LOCALIZATION_ZORLEN_ArcanePower = ""
	--LOCALIZATION_ZORLEN_BlastWave = ""
	--LOCALIZATION_ZORLEN_Blink = ""
	--LOCALIZATION_ZORLEN_Blizzard = ""
	--LOCALIZATION_ZORLEN_ColdSnap = ""
	--LOCALIZATION_ZORLEN_Combustion = ""
	--LOCALIZATION_ZORLEN_ConeOfCold = ""
	--LOCALIZATION_ZORLEN_ConjureFood = ""
	--LOCALIZATION_ZORLEN_ConjureManaAgate = ""
	--LOCALIZATION_ZORLEN_ConjureManaJade = ""
	--LOCALIZATION_ZORLEN_ConjureManaCitrine = ""
	--LOCALIZATION_ZORLEN_ConjureManaRuby = ""
	--LOCALIZATION_ZORLEN_ConjureWater = ""
	--LOCALIZATION_ZORLEN_Counterspell = ""
	--LOCALIZATION_ZORLEN_DampenMagic = ""
	--LOCALIZATION_ZORLEN_DetectMagic = ""
	--LOCALIZATION_ZORLEN_Evocation = ""
	--LOCALIZATION_ZORLEN_FireBlast = ""
	--LOCALIZATION_ZORLEN_FireWard = ""
	--LOCALIZATION_ZORLEN_Fireball = ""
	--LOCALIZATION_ZORLEN_Flamestrike = ""
	--LOCALIZATION_ZORLEN_FrostArmor = ""
	--LOCALIZATION_ZORLEN_FrostNova = ""
	--LOCALIZATION_ZORLEN_FrostWard = ""
	--LOCALIZATION_ZORLEN_Frostbolt = ""
	--LOCALIZATION_ZORLEN_IceArmor = ""
	--LOCALIZATION_ZORLEN_IceBarrier = ""
	--LOCALIZATION_ZORLEN_IceBlock = ""
	--LOCALIZATION_ZORLEN_MageArmor = ""
	--LOCALIZATION_ZORLEN_ManaShield = ""
	--LOCALIZATION_ZORLEN_Polymorph = ""
	--LOCALIZATION_ZORLEN_PortalDarnassus = ""
	--LOCALIZATION_ZORLEN_PortalIronforge = ""
	--LOCALIZATION_ZORLEN_PortalOrgrimmar = ""
	--LOCALIZATION_ZORLEN_PortalStormwind = ""
	--LOCALIZATION_ZORLEN_PortalThunderBluff = ""
	--LOCALIZATION_ZORLEN_PortalUndercity = ""
	--LOCALIZATION_ZORLEN_TeleportDarnassus = ""
	--LOCALIZATION_ZORLEN_TeleportIronforge = ""
	--LOCALIZATION_ZORLEN_TeleportOrgrimmar = ""
	--LOCALIZATION_ZORLEN_TeleportStormwind = ""
	--LOCALIZATION_ZORLEN_TeleportThunderBluff = ""
	--LOCALIZATION_ZORLEN_TeleportUndercity = ""
	--LOCALIZATION_ZORLEN_PresenceOfMind = ""
	--LOCALIZATION_ZORLEN_Pyroblast = ""
	--LOCALIZATION_ZORLEN_RemoveLesserCurse = ""
	--LOCALIZATION_ZORLEN_Scorch = ""
	--LOCALIZATION_ZORLEN_SlowFall = ""



-- Zorlen_Paladin.lua file Localization
	--LOCALIZATION_ZORLEN_BlessingOfFreedom = ""
	--LOCALIZATION_ZORLEN_BlessingOfKings = ""
	--LOCALIZATION_ZORLEN_BlessingOfLight = ""
	--LOCALIZATION_ZORLEN_BlessingOfMight = ""
	--LOCALIZATION_ZORLEN_BlessingOfProtection = ""
	--LOCALIZATION_ZORLEN_BlessingOfSacrifice = ""
	--LOCALIZATION_ZORLEN_BlessingOfSalvation = ""
	--LOCALIZATION_ZORLEN_BlessingOfSanctuary = ""
	--LOCALIZATION_ZORLEN_BlessingOfWisdom = ""
	--LOCALIZATION_ZORLEN_Cleanse = ""
	--LOCALIZATION_ZORLEN_ConcentrationAura = ""
	--LOCALIZATION_ZORLEN_Consecration = ""
	--LOCALIZATION_ZORLEN_DevotionAura = ""
	--LOCALIZATION_ZORLEN_DivineFavor = ""
	--LOCALIZATION_ZORLEN_DivineIntervention = ""
	--LOCALIZATION_ZORLEN_DivineProtection = ""
	--LOCALIZATION_ZORLEN_DivineShield = ""
	--LOCALIZATION_ZORLEN_Exorcism = ""
	--LOCALIZATION_ZORLEN_FireResistanceAura = ""
	--LOCALIZATION_ZORLEN_FlashOfLight = ""
	--LOCALIZATION_ZORLEN_FrostResistanceAura = ""
	--LOCALIZATION_ZORLEN_GreaterBlessingOfKings = ""
	--LOCALIZATION_ZORLEN_GreaterBlessingOfLight = ""
	--LOCALIZATION_ZORLEN_GreaterBlessingOfMight = ""
	--LOCALIZATION_ZORLEN_GreaterBlessingOfSalvation = ""
	--LOCALIZATION_ZORLEN_GreaterBlessingOfSanctuary = ""
	--LOCALIZATION_ZORLEN_GreaterBlessingOfWisdom = ""
	--LOCALIZATION_ZORLEN_HammerOfJustice = ""
	--LOCALIZATION_ZORLEN_HammerOfWrath = ""
	--LOCALIZATION_ZORLEN_HolyLight = ""
	--LOCALIZATION_ZORLEN_HolyShield = ""
	--LOCALIZATION_ZORLEN_HolyShock = ""
	--LOCALIZATION_ZORLEN_HolyWrath = ""
	--LOCALIZATION_ZORLEN_Judgement = ""
	--LOCALIZATION_ZORLEN_LayOnHands = ""
	--LOCALIZATION_ZORLEN_Purify = ""
	--LOCALIZATION_ZORLEN_Redemption = ""
	--LOCALIZATION_ZORLEN_Repentance = ""
	--LOCALIZATION_ZORLEN_RetributionAura = ""
	--LOCALIZATION_ZORLEN_RighteousFury = ""
	--LOCALIZATION_ZORLEN_SanctityAura = ""
	--LOCALIZATION_ZORLEN_SealOfCommand = ""
	--LOCALIZATION_ZORLEN_SealOfJustice = ""
	--LOCALIZATION_ZORLEN_SealOfLight = ""
	--LOCALIZATION_ZORLEN_SealOfRighteousness = ""
	--LOCALIZATION_ZORLEN_SealOfWisdom = ""
	--LOCALIZATION_ZORLEN_SealOfTheCrusader = ""
	--LOCALIZATION_ZORLEN_SenseUndead = ""
	--LOCALIZATION_ZORLEN_ShadowResistanceAura = ""
	--LOCALIZATION_ZORLEN_SummonCharger = ""
	--LOCALIZATION_ZORLEN_SummonWarhorse = ""
	--LOCALIZATION_ZORLEN_TurnUndead = ""



-- Zorlen_Priest.lua file Localization
	LOCALIZATION_ZORLEN_PowerInfusion = "Seele der Macht"
	--LOCALIZATION_ZORLEN_Lightwell = ""
	LOCALIZATION_ZORLEN_AbolishDisease = "Krankheit aufheben"
	LOCALIZATION_ZORLEN_CureDisease = "Krankheit heilen"
	LOCALIZATION_ZORLEN_DesperatePrayer = "Verzweifeltes Gebet"
	LOCALIZATION_ZORLEN_DevouringPlague = "Verschlingende Seuche"
	LOCALIZATION_ZORLEN_DispelMagic = "Magiebannung"
	LOCALIZATION_ZORLEN_DivineSpirit = "G\195\182ttlicher Willen"
	LOCALIZATION_ZORLEN_ElunesGrace = "Elunes Anmut"
	LOCALIZATION_ZORLEN_Fade = "Verblassen"
	LOCALIZATION_ZORLEN_FearWard = "Furcht-Zauberschutz"
	LOCALIZATION_ZORLEN_Feedback = "R\195\188ckkopplung"
	LOCALIZATION_ZORLEN_FlashHeal = "Blitzheilung"
	--LOCALIZATION_ZORLEN_FocusedCasting = ""
	LOCALIZATION_ZORLEN_LesserHeal = "Geringes Heilen"
	LOCALIZATION_ZORLEN_Heal = "Heilen"
	LOCALIZATION_ZORLEN_GreaterHeal = "Gro\195\159e Heilung"
	LOCALIZATION_ZORLEN_HexOfWeakness = "Verhexung der Schw\195\164che"
	LOCALIZATION_ZORLEN_HolyFire = "Heiliges Feuer"
	LOCALIZATION_ZORLEN_HolyNova = "Heilige Nova"
	LOCALIZATION_ZORLEN_InnerFire = "Inneres Feuer"
	LOCALIZATION_ZORLEN_InnerFocus = "Innerer Fokus"
	LOCALIZATION_ZORLEN_Levitate = "Levitieren"
	LOCALIZATION_ZORLEN_ManaBurn = "Manabrand"
	LOCALIZATION_ZORLEN_MindBlast = "Gedankenschlag"
	LOCALIZATION_ZORLEN_MindControl = "Gedankenkontrolle"
	LOCALIZATION_ZORLEN_MindFlay = "Gedankenschinden"
	LOCALIZATION_ZORLEN_MindSoothe = "Gedankenbes\195\164nftigung"
	--LOCALIZATION_ZORLEN_MindVision = ""
	LOCALIZATION_ZORLEN_PowerWordFortitude = "Machtwort: Seelenst\195\164rke"
	LOCALIZATION_ZORLEN_PowerWordShield = "Machtwort: Schild"
	LOCALIZATION_ZORLEN_PrayerOfFortitude = "Gebet der Seelenst\195\164rke"
	LOCALIZATION_ZORLEN_PrayerOfHealing = "Gebet der Heilung"
	LOCALIZATION_ZORLEN_PsychicScream = "Psychischer Schrei"
	LOCALIZATION_ZORLEN_Renew = "Erneuerung"
	LOCALIZATION_ZORLEN_Resurrection = "Wiederbelebung"
	LOCALIZATION_ZORLEN_ShackleUndead = "Untote Fesseln"
	LOCALIZATION_ZORLEN_ShadowProtection = "Schattenschutz"
	LOCALIZATION_ZORLEN_ShadowWordPain = "Schattenwort: Schmerz"
	LOCALIZATION_ZORLEN_Shadowform = "Schattengestalt"
	LOCALIZATION_ZORLEN_Shadowguard = "Schattenschild"
	LOCALIZATION_ZORLEN_Silence = "Scheigsame Entschlossenheit"
	LOCALIZATION_ZORLEN_Smite = "G\195\182ttliche Pein"
	--LOCALIZATION_ZORLEN_SpiritOfRedemption = ""
	LOCALIZATION_ZORLEN_Starshards = "Sternensplitter"
	LOCALIZATION_ZORLEN_TouchOfWeakness = "Ber\195\188hrung der Schw\195\164che"
	LOCALIZATION_ZORLEN_VampiricEmbrace = "Vampirumarmung"



-- Zorlen_Rogue.lua file Localization
	LOCALIZATION_ZORLEN_ImprovedCheapShot = "Verbesserter Fieser Trick"
	LOCALIZATION_ZORLEN_ImprovedSinisterStrike = "Verbesserter Finsterer Sto\195\159"
	LOCALIZATION_ZORLEN_CripplingPoison = "Verkr\195\188ppeldes Gift"
	LOCALIZATION_ZORLEN_CripplingPoisonII = "Verkr\195\188ppeldes Gift II"
	LOCALIZATION_ZORLEN_DeadlyPoison = "T\195\182dliches Gift"
	LOCALIZATION_ZORLEN_DeadlyPoisonII = "T\195\182dliches Gift II"
	LOCALIZATION_ZORLEN_DeadlyPoisonIII = "T\195\182dliches Gift III"
	LOCALIZATION_ZORLEN_DeadlyPoisonIV = "T\195\182dliches Gift IV"
	LOCALIZATION_ZORLEN_DeadlyPoisonV = "T\195\182dliches Gift V"
	LOCALIZATION_ZORLEN_InstantPoison = "Sofortwirkendes Gift"
	LOCALIZATION_ZORLEN_InstantPoisonII = "Sofortwirkendes Gift II"
	LOCALIZATION_ZORLEN_InstantPoisonIII = "Sofortwirkendes Gift III"
	LOCALIZATION_ZORLEN_InstantPoisonIV = "Sofortwirkendes Gift IV"
	LOCALIZATION_ZORLEN_InstantPoisonV = "Sofortwirkendes Gift V"
	LOCALIZATION_ZORLEN_InstantPoisonVI = "Sofortwirkendes Gift VI"
	LOCALIZATION_ZORLEN_MindnumbingPoison = "Gedankenblendendes Gift"
	LOCALIZATION_ZORLEN_MindnumbingPoisonII = "Gedankenblendendes Gift II"
	LOCALIZATION_ZORLEN_MindnumbingPoisonIII = "Gedankenblendendes Gift III"
	LOCALIZATION_ZORLEN_WoundPoison = "Wundgift"
	LOCALIZATION_ZORLEN_WoundPoisonII = "Wundgift II"
	LOCALIZATION_ZORLEN_WoundPoisonIII = "Wundgift III"
	LOCALIZATION_ZORLEN_WoundPoisonIV = "Wundgift IV"
	LOCALIZATION_ZORLEN_AdrenalineRush = "Adrenalinrausch"
	LOCALIZATION_ZORLEN_Ambush = "Hinterhalt"
	LOCALIZATION_ZORLEN_Backstab = "Meucheln"
	LOCALIZATION_ZORLEN_BladeFlurry = "Klingenwirbel"
	LOCALIZATION_ZORLEN_Blind = "Blenden"
	LOCALIZATION_ZORLEN_BlindingPowder = "Blendungspulver"
	LOCALIZATION_ZORLEN_CheapShot = "Fieser Trick"
	LOCALIZATION_ZORLEN_ColdBlood = "Kaltbl\195\188tigkeit"
	LOCALIZATION_ZORLEN_DetectTraps = "Fallen entdecken"
	LOCALIZATION_ZORLEN_DisarmTrap = "Fallen entsch\195\164rfen"
	LOCALIZATION_ZORLEN_Distract = "Ablenken"
	LOCALIZATION_ZORLEN_Evasion = "Entrinnen"
	LOCALIZATION_ZORLEN_Eviscerate = "Ausweiden"
	LOCALIZATION_ZORLEN_ExposeArmor = "R\195\188stung schw\195\164chen"
	LOCALIZATION_ZORLEN_Feint = "Finte"
	LOCALIZATION_ZORLEN_Garrote = "Erdrosseln"
	LOCALIZATION_ZORLEN_GhostlyStrike = "Geisterhafter Sto\195\159"
	LOCALIZATION_ZORLEN_Gouge = "Solarplexus"
	LOCALIZATION_ZORLEN_Hemorrhage = "Blutsturz"
	LOCALIZATION_ZORLEN_Kick = "Tritt"
	LOCALIZATION_ZORLEN_KidneyShot = "Nierenhieb"
	LOCALIZATION_ZORLEN_PickLock = "Schl\195\182sser knacken"
	LOCALIZATION_ZORLEN_PickPocket = "Taschendiebstahl"
	LOCALIZATION_ZORLEN_Premeditation = "Konzentration"
	LOCALIZATION_ZORLEN_Preparation = "Vorbereitung"
	LOCALIZATION_ZORLEN_RelentlessStrikes = "Unerbitliche St\195\182\195\159e"
	LOCALIZATION_ZORLEN_Riposte = "Riposte"
	LOCALIZATION_ZORLEN_Rupture = "Blutung"
	LOCALIZATION_ZORLEN_Sap = "Kopfnuss"
	LOCALIZATION_ZORLEN_SinisterStrike = "Finsterer Sto\195\159"
	LOCALIZATION_ZORLEN_SliceAndDice = "Zerh\195\164chseln"
	LOCALIZATION_ZORLEN_Sprint = "Sprinten"
	LOCALIZATION_ZORLEN_Stealth = "Verstohlenheit"
	LOCALIZATION_ZORLEN_Vanish = "Verschwinden"



-- Zorlen_Shaman.lua file Localization
	--LOCALIZATION_ZORLEN_DiseaseCleansingTotem = ""
	--LOCALIZATION_ZORLEN_EarthbindTotem = ""
	--LOCALIZATION_ZORLEN_FireNovaTotem = ""
	--LOCALIZATION_ZORLEN_FireResistanceTotem = ""
	--LOCALIZATION_ZORLEN_FlametongueTotem = ""
	--LOCALIZATION_ZORLEN_FrostResistanceTotem = ""
	--LOCALIZATION_ZORLEN_GraceOfAirTotem = ""
	--LOCALIZATION_ZORLEN_GroundingTotem = ""
	--LOCALIZATION_ZORLEN_HealingStreamTotem = ""
	--LOCALIZATION_ZORLEN_MagmaTotem = ""
	--LOCALIZATION_ZORLEN_ManaSpringTotem = ""
	--LOCALIZATION_ZORLEN_ManaTideTotem = ""
	--LOCALIZATION_ZORLEN_NatureResistanceTotem = ""
	--LOCALIZATION_ZORLEN_PoisonCleansingTotem = ""
	--LOCALIZATION_ZORLEN_SearingTotem = ""
	--LOCALIZATION_ZORLEN_SentryTotem = ""
	--LOCALIZATION_ZORLEN_StoneclawTotem = ""
	--LOCALIZATION_ZORLEN_StoneskinTotem = ""
	--LOCALIZATION_ZORLEN_StrengthOfEarthTotem = ""
	--LOCALIZATION_ZORLEN_TremorTotem = ""
	--LOCALIZATION_ZORLEN_WindfuryTotem = ""
	--LOCALIZATION_ZORLEN_WindwallTotem = ""
	--LOCALIZATION_ZORLEN_EarthShock = ""
	--LOCALIZATION_ZORLEN_FlameShock = ""
	--LOCALIZATION_ZORLEN_FrostShock = ""
	--LOCALIZATION_ZORLEN_FlametongueWeapon = ""
	--LOCALIZATION_ZORLEN_FrostbrandWeapon = ""
	--LOCALIZATION_ZORLEN_RockbiterWeapon = ""
	--LOCALIZATION_ZORLEN_WindfuryWeapon = ""
	--LOCALIZATION_ZORLEN_AncestralSpirit = ""
	--LOCALIZATION_ZORLEN_AstralRecall = ""
	--LOCALIZATION_ZORLEN_ChainHeal = ""
	--LOCALIZATION_ZORLEN_ChainLightning = ""
	--LOCALIZATION_ZORLEN_CureDisease = ""
	--LOCALIZATION_ZORLEN_CurePoison = ""
	--LOCALIZATION_ZORLEN_ElementalFocus = ""
	--LOCALIZATION_ZORLEN_ElementalMastery = ""
	--LOCALIZATION_ZORLEN_FarSight = ""
	--LOCALIZATION_ZORLEN_GhostWolf = ""
	--LOCALIZATION_ZORLEN_LesserHealingWave = ""
	--LOCALIZATION_ZORLEN_HealingWave = ""
	--LOCALIZATION_ZORLEN_LightningBolt = ""
	--LOCALIZATION_ZORLEN_LightningShield = ""
	--LOCALIZATION_ZORLEN_NaturesSwiftness = ""
	--LOCALIZATION_ZORLEN_Purge = ""
	--LOCALIZATION_ZORLEN_Reincarnation = ""
	--LOCALIZATION_ZORLEN_Stormstrike = ""
	--LOCALIZATION_ZORLEN_WaterBreathing = ""
	--LOCALIZATION_ZORLEN_WaterWalking = ""



-- Zorlen_Warrior.lua file Localization
	--LOCALIZATION_ZORLEN_Devastate = ""
	--LOCALIZATION_ZORLEN_ImprovedWhirlwind = ""
	--LOCALIZATION_ZORLEN_FocusedRage = ""
	--LOCALIZATION_ZORLEN_CommandingShout = ""
	--LOCALIZATION_ZORLEN_SpellReflection = ""
	--LOCALIZATION_ZORLEN_Intervene = ""
	--LOCALIZATION_ZORLEN_VictoryRush = ""
	--LOCALIZATION_ZORLEN_EndlessRage = ""
	--LOCALIZATION_ZORLEN_Rampage = ""
	
	LOCALIZATION_ZORLEN_ImprovedBloodrage = "Verbessertes Blutrausch"
	LOCALIZATION_ZORLEN_ImprovedOverpower = "Verbessertes \195\156berw\195\164ltigen"
	LOCALIZATION_ZORLEN_ImprovedBerserkerRage = "Verbesserte Berserkerwut"
	LOCALIZATION_ZORLEN_ImprovedExecute = "Verbessertes Hinrichten"
	LOCALIZATION_ZORLEN_Execute = "Hinrichten"
	LOCALIZATION_ZORLEN_ImprovedHeroicStrike = "Verbesserter Heldenhafter Sto\195\159"
	LOCALIZATION_ZORLEN_HeroicStrike = "Heldenhafter Sto\195\159"
	LOCALIZATION_ZORLEN_ImprovedSunderArmor = "Verbessertes R\195\188stung zerrei\195\159en"
	LOCALIZATION_ZORLEN_SunderArmor = "R\195\188stung zerrei\195\159en"
	LOCALIZATION_ZORLEN_ImprovedThunderClap = "Verbesserter Donnerknall"
	LOCALIZATION_ZORLEN_ThunderClap = "Donnerknall"
	LOCALIZATION_ZORLEN_MortalStrike = "T\195\182dlicher Sto\195\159"
	LOCALIZATION_ZORLEN_Bloodthirst = "Blutdurst"
	LOCALIZATION_ZORLEN_ShieldSlam = "Schildschlag"
	LOCALIZATION_ZORLEN_Charge = "Sturmangriff"
	LOCALIZATION_ZORLEN_Taunt = "Spott"
	LOCALIZATION_ZORLEN_Intercept = "Abfangen"
	LOCALIZATION_ZORLEN_Overpower = "\195\156berw\195\164ltigen"
	LOCALIZATION_ZORLEN_Revenge = "Rache"
	LOCALIZATION_ZORLEN_Rend = "Verwunden"
	LOCALIZATION_ZORLEN_Hamstring = "Kniesehne"
	LOCALIZATION_ZORLEN_ShieldBash = "Schildhieb"
	LOCALIZATION_ZORLEN_Pummel = "Zuschlagen"
	LOCALIZATION_ZORLEN_ShieldBlock = "Schildblock"
	LOCALIZATION_ZORLEN_DemoralizingShout = "Demoralisierungsruf"
	LOCALIZATION_ZORLEN_BattleShout = "Schlachtruf"
	LOCALIZATION_ZORLEN_BerserkerRage = "Berserkerwut"
	LOCALIZATION_ZORLEN_Enrage = "Wutanfall"
	LOCALIZATION_ZORLEN_DefensiveStance = "Verteidigungshaltung"
	LOCALIZATION_ZORLEN_BattleStance = "Kampfhaltung"
	LOCALIZATION_ZORLEN_BerserkerStance = "Berserkerhaltung"
	LOCALIZATION_ZORLEN_AngerManagement = "Agressionskontrolle"
	LOCALIZATION_ZORLEN_Bloodrage = "Blutrausch"
	LOCALIZATION_ZORLEN_ChallengingShout = "Herausforderungsruf"
	LOCALIZATION_ZORLEN_Cleave = "Spalten"
	LOCALIZATION_ZORLEN_ConcussionBlow = "Ersch\195\188tternder Schlag"
	LOCALIZATION_ZORLEN_DeathWish = "Todeswunsch"
	LOCALIZATION_ZORLEN_Disarm = "Entwaffnen"
	LOCALIZATION_ZORLEN_IntimidatingShout = "Drohruf"
	LOCALIZATION_ZORLEN_LastStand = "Letztes Gefecht"
	LOCALIZATION_ZORLEN_MockingBlow = "Sp\195\182ttischer Schlag"
	LOCALIZATION_ZORLEN_PiercingHowl = "Durchdringendes Heulen"
	LOCALIZATION_ZORLEN_Recklessness = "Tollk\195\188hnheit"
	LOCALIZATION_ZORLEN_Retaliation = "Gegenschlag"
	LOCALIZATION_ZORLEN_ShieldWall = "Schildwall"
	LOCALIZATION_ZORLEN_Slam = "Zerschmettern"
	LOCALIZATION_ZORLEN_SweepingStrikes = "Weitreichende St\195\182\195\159e"
	LOCALIZATION_ZORLEN_Whirlwind = "Wirbelwind"
	LOCALIZATION_ZORLEN_TacticalMastery = "Taktiker"



-- Fire Immune MOB's
 -- Molten Core
	LOCALIZATION_ZORLEN_Firelord = "Feuerlord"
	LOCALIZATION_ZORLEN_Firewalker = "Feuerg\195\164nger"
	LOCALIZATION_ZORLEN_Flameguard = "Flammenw\195\164chter"
	LOCALIZATION_ZORLEN_LavaSpawn = "Lavabrut"
	LOCALIZATION_ZORLEN_BaronGeddon = "Baron Geddon"
	LOCALIZATION_ZORLEN_Ragnaros = "Ragnaros"
 -- Upper Blackrock Spire
	LOCALIZATION_ZORLEN_PyroguardEmberseer = "Feuerwache Glutseher"
 -- Blackrock Depths
	LOCALIZATION_ZORLEN_Fireguard = "Brandwache"
	LOCALIZATION_ZORLEN_FireguardDestroyer = "Brandwachenzerst\195\182rer"
	LOCALIZATION_ZORLEN_BlazingFireguard = "Lodernde Brandwache"
	LOCALIZATION_ZORLEN_AmbassadorFlamelash = "Botschafter Flammenschlag"
	LOCALIZATION_ZORLEN_LordIncendius = "Lord Incendius"
 --Searing Gorge
	LOCALIZATION_ZORLEN_BlazingElemental = "Lodernder Elementar"
	LOCALIZATION_ZORLEN_InfernoElemental = "Infernoelementar"
 --Un'Goro Crater
	LOCALIZATION_ZORLEN_ScorchingElemental = "Versengender Elementar"
	LOCALIZATION_ZORLEN_LivingBlaze = "Lebendiges Feuer"
	LOCALIZATION_ZORLEN_Blazerunner = "Lodernder Eindringling"

-- Drain Life Immune MOB's
 -- Blackrock Depths
	--LOCALIZATION_ZORLEN_MoltenWarGolem = ""
	--LOCALIZATION_ZORLEN_PanzorTheInvincible = ""
 --Searing Gorge
	--LOCALIZATION_ZORLEN_HeavyWarGolem = ""
	--LOCALIZATION_ZORLEN_FaultyWarGolem = ""
	--LOCALIZATION_ZORLEN_TemperedWarGolem = ""
	--LOCALIZATION_ZORLEN_RagereaverGolem = ""
end
