
Zorlen_FR_FileBuildNumber = 681

-- French Translation
-- If you want to translate this to another language, make sure the names of buffs and abilities are *EXACTLY* the same as in-game. Spelling, punctuation, upper/lowercase letters, etc. MUST BE EXACT. Also, any 'foreign' characters must be converted to UNICODE.
-- Unicode resource:
-- http://www.utf8-chartable.de/unicode-utf8-table.pl?start=128&number=1024&utf8=dec
-- http://home.tiscali.nl/t876506/utf8tbl.html
-- http://www.allegro-c.de/unicode/zcodes.htm
-- You will need to use the UTF-8 decimal numbers with a back slash in front of them in the same way that Å is represented by: \195\133


-- To lower the upkeep we will not be adding Localization for english words that do not break compatibility in other game clients.
-- This Localization is only added for compatibility so that it may work in non english game clients and not as a translation.

if GetLocale() == "frFR" then
-- All file Localization
	--LOCALIZATION_ZORLEN_EatMacroName = ""
	--LOCALIZATION_ZORLEN_DrinkMacroName = ""
	LOCALIZATION_ZORLEN_Conjured = "invoqu\195\169"
	LOCALIZATION_ZORLEN_Water = "Eau"
	--LOCALIZATION_ZORLEN_AllConjuredWater = ""
	--LOCALIZATION_ZORLEN_well_fed = ""
	LOCALIZATION_ZORLEN_HitsOrCritsArray = {}
	LOCALIZATION_ZORLEN_EnemyDies = "(.*)"
	LOCALIZATION_ZORLEN_Rank = "Rang"
	LOCALIZATION_ZORLEN_sit = "sit"
	LOCALIZATION_ZORLEN_You_dodge = "Vous esquivez"
	LOCALIZATION_ZORLEN_immune = "insensible"
	--LOCALIZATION_ZORLEN_no_weapons_equipped = ""
	--LOCALIZATION_ZORLEN_dodged = ""
	--LOCALIZATION_ZORLEN_dodges = ""
	--LOCALIZATION_ZORLEN_pet_is_not_dead = ""
	--LOCALIZATION_ZORLEN_pet_is_dead = ""
	--LOCALIZATION_ZORLEN_A_more_powerful_spell_is_already_active = ""
	--LOCALIZATION_ZORLEN_Asleep = ""
	--LOCALIZATION_ZORLEN_RequiresLevel = ""
	
	--LOCALIZATION_ZORLEN_GreaterHealingWard = ""
	--LOCALIZATION_ZORLEN_LavaSpoutTotem = ""
	
	LOCALIZATION_ZORLEN_HealingBonusWordsArray = {"Soins", "Sorts de Soins", "Sorts de soin", "Sorts de soins"}
	LOCALIZATION_ZORLEN_HealingBonusPhraseArray = {"Augmente les effets des sorts de soins de (%d+)% au maximum.", "Augmente les soins prodigués par les sorts et effets de (%d+)% au maximum."}
	
	LOCALIZATION_ZORLEN_SpellDamageAndHealingBonusWordsArray = {"Dégâts et soins ", "Dégâts et soins"}
	LOCALIZATION_ZORLEN_SpellDamageAndHealingBonusPhraseArray = {"Augmente les soins et dégâts produits par les sorts et effets magiques de (%d+) au maximum.", "Augmente les dégâts et les soins produits par les sorts et effets magiques de (%d+) au maximum."}
	
	LOCALIZATION_ZORLEN_SpellDamageBonusWordsArray = {"Sorts de Dommages", "dégâts des sorts", "dégâts et les effets des sorts"}
	LOCALIZATION_ZORLEN_SpellDamageBonusPhraseArray = {}
	--LOCALIZATION_ZORLEN_BrilliantWizardOil = ""
	--LOCALIZATION_ZORLEN_WizardOil = ""
	--LOCALIZATION_ZORLEN_LesserWizardOil = ""
	--LOCALIZATION_ZORLEN_MinorWizardOil = ""
	--LOCALIZATION_ZORLEN_SupremePower = ""
	--LOCALIZATION_ZORLEN_GreaterArcaneElixir = ""
	--LOCALIZATION_ZORLEN_ArcaneElixir = ""
	
	LOCALIZATION_ZORLEN_ShadowDamageBonusWordsArray = {"Dégâts des Ombres"}
	LOCALIZATION_ZORLEN_ShadowDamageBonusPhraseArray = {"Augmente les points de dégâts infligés par les sorts et les effets d'ombre de (%d+)% au maximum.", "(%d+)% aux dégâts des sorts d'ombres."}
	--LOCALIZATION_ZORLEN_ShadowPower = ""
	
-- Battleground Names
	--LOCALIZATION_ZORLEN_WarsongGulch = ""
	--LOCALIZATION_ZORLEN_AlteracValley = ""
	--LOCALIZATION_ZORLEN_ArathiBasin = ""
	
-- Raid Target Names
	--LOCALIZATION_ZORLEN_WhiteSkull = ""
	--LOCALIZATION_ZORLEN_RedX = ""
	--LOCALIZATION_ZORLEN_BlueSquare = ""
	--LOCALIZATION_ZORLEN_WhiteCrescentMoon = ""
	--LOCALIZATION_ZORLEN_GreenTriangle = ""
	--LOCALIZATION_ZORLEN_PurpleDiamond = ""
	--LOCALIZATION_ZORLEN_OrangeCircle = ""
	--LOCALIZATION_ZORLEN_YellowStar = ""



-- Food Item Tool Tip Text:
	--LOCALIZATION_ZORLEN_FoodToolTipTextAny = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText3180 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText2148 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText1392 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText874 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText552 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText243 = ""
	--LOCALIZATION_ZORLEN_FoodToolTipText61 = ""
-- Drink Item Tool Tip Text:
	--LOCALIZATION_ZORLEN_DrinkToolTipTextAny = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText4200 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText2934 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText1992 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText1344 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText835 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText436 = ""
	--LOCALIZATION_ZORLEN_DrinkToolTipText151 = ""



-- Zorlen_Other.lua file Localization
	LOCALIZATION_ZORLEN_Attack = "Attaque"
	LOCALIZATION_ZORLEN_Throw = "Lancer"
	LOCALIZATION_ZORLEN_ShootBow = "Tir \195\160 l'arc"
	LOCALIZATION_ZORLEN_ShootCrossbow = "Tir \195\160 l\226\128\153arbal\195\168te"
	LOCALIZATION_ZORLEN_ShootGun = "Tir avec une arme \195\160 feu"
	LOCALIZATION_ZORLEN_Shoot = "Tir"
-- Human Racial
	LOCALIZATION_ZORLEN_Perception = "Perception"
-- Dwarf Racial
	LOCALIZATION_ZORLEN_FindTreasure = "D\195\169couverte de tr\195\169sors"
	LOCALIZATION_ZORLEN_Stoneform = "Forme de pierre"
-- Gnome Racial
	LOCALIZATION_ZORLEN_EscapeArtist = "Ma\195\174tre de l'\195\169vasion"
-- Night Elf Racial
	LOCALIZATION_ZORLEN_Shadowmeld = "Camouflage dans l'ombre"
-- Orc Racial
	LOCALIZATION_ZORLEN_BloodFury = "Fureur sanguinaire"
-- Undead Racial
	LOCALIZATION_ZORLEN_Cannibalize = "Cannibalisme"
	LOCALIZATION_ZORLEN_WillOfTheForsaken = "Volont\195\169 des R\195\169prouv\195\169s"
-- Tauren Racial
	LOCALIZATION_ZORLEN_WarStomp = "Choc martial"
-- Troll Racial
	LOCALIZATION_ZORLEN_Berserking = "Berserker"



-- Zorlen_Pets.lua file Localization
-- Hunter Pets
	LOCALIZATION_ZORLEN_Dash = "C\195\169l\195\169rit\195\169"
	LOCALIZATION_ZORLEN_Dive = "Plongeon"
	LOCALIZATION_ZORLEN_Bite = "Morsure"
	LOCALIZATION_ZORLEN_Claw = "Griffe"
	LOCALIZATION_ZORLEN_Cower = "D\195\169robade"
	LOCALIZATION_ZORLEN_Growl = "Grondement"
	LOCALIZATION_ZORLEN_Prowl = "R\195\180der"
	LOCALIZATION_ZORLEN_Charge = "Charge"
	LOCALIZATION_ZORLEN_Screech = "Hurlement"
	LOCALIZATION_ZORLEN_FuriousHowl = "Hurlement furieux"
	LOCALIZATION_ZORLEN_LightningBreath = "Souffle de foudre"
	LOCALIZATION_ZORLEN_ShellShield = "Carapace bouclier"
	LOCALIZATION_ZORLEN_Thunderstomp = "Grondeterre"
	LOCALIZATION_ZORLEN_ScorpidPoison = "Poison de scorpide"
-- Warlock Pets
	LOCALIZATION_ZORLEN_Felhunter = "Chasseur corrompu"
	LOCALIZATION_ZORLEN_Imp = "Diablotin"
	LOCALIZATION_ZORLEN_Succubus = "Succube"
	LOCALIZATION_ZORLEN_Voidwalker = "Marcheur du Vide"
	LOCALIZATION_ZORLEN_BloodPact = "Pacte de sang"
	LOCALIZATION_ZORLEN_FireShield = "Bouclier de feu"
	LOCALIZATION_ZORLEN_Firebolt = "Eclair de feu"
	LOCALIZATION_ZORLEN_PhaseShift = "Changement de phase"
	LOCALIZATION_ZORLEN_ConsumeShadows = "Consumer les ombres"
	LOCALIZATION_ZORLEN_Sacrifice = "Sacrifice"
	LOCALIZATION_ZORLEN_Suffering = "Souffrance"
	LOCALIZATION_ZORLEN_Torment = "Tourment"
	LOCALIZATION_ZORLEN_DevourMagic = "Festin magique"
	LOCALIZATION_ZORLEN_Paranoia = "Parano\195\175a"
	LOCALIZATION_ZORLEN_SpellLock = "Verrou magique"
	LOCALIZATION_ZORLEN_TaintedBlood = "Corruption sanguine"
	LOCALIZATION_ZORLEN_LashOfPain = "Fouet de la douleur"
	LOCALIZATION_ZORLEN_Seduction = "S\195\169duction"
	LOCALIZATION_ZORLEN_SoothingKiss = "Baiser apaisant"
	LOCALIZATION_ZORLEN_LesserInvisibility = "Invisibilit\195\169 inf\195\169rieure"



-- Zorlen_Hunter.lua file Localization
	--LOCALIZATION_ZORLEN_FeedPet = ""
	LOCALIZATION_ZORLEN_ImprovedAspectOfTheHawk = "Aspect du Faucon am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_ImprovedMendPet = "Gu\195\169rison du familier am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_MendPet = "Gu\195\169rison du familier"
	LOCALIZATION_ZORLEN_CallPet = "Appel du familier"
	LOCALIZATION_ZORLEN_RevivePet = "Ressusciter le familier"
	LOCALIZATION_ZORLEN_DismissPet = "Renvoyer le familier"
	LOCALIZATION_ZORLEN_AutoShot = "Tir automatique"
	LOCALIZATION_ZORLEN_MongooseBite = "Morsure de la mangouste"
	LOCALIZATION_ZORLEN_ArcaneShot = "Tir des arcanes"
	LOCALIZATION_ZORLEN_ConcussiveShot = "Trait de choc"
	LOCALIZATION_ZORLEN_RaptorStrike = "Attaque du raptor"
	LOCALIZATION_ZORLEN_SerpentSting = "Morsure de serpent"
	LOCALIZATION_ZORLEN_ViperSting = "Morsure de vip\195\168re"
	LOCALIZATION_ZORLEN_ScorpidSting = "Piq\195\187re de scorpide"
	LOCALIZATION_ZORLEN_DistractingShot = "Trait provocateur"
	LOCALIZATION_ZORLEN_AimedShot = "Vis\195\169e"
	LOCALIZATION_ZORLEN_HuntersMark = "Marque du chasseur"
	LOCALIZATION_ZORLEN_AspectOfTheHawk = "Aspect du Faucon"
	LOCALIZATION_ZORLEN_AspectOfTheMonkey = "Aspect du Singe"
	LOCALIZATION_ZORLEN_AspectOfTheCheetah = "Aspect du Gu\195\169pard"
	LOCALIZATION_ZORLEN_AspectOfThePack = "Aspect de la Meute"
	LOCALIZATION_ZORLEN_AspectOfTheWild = "Aspect de la Nature"
	LOCALIZATION_ZORLEN_AspectOfTheBeast = "Aspect de la B\195\170te"
	LOCALIZATION_ZORLEN_WingClip = "Coupure d'ailes"
	LOCALIZATION_ZORLEN_FreezingTrap = "Pi\195\168ge givrant"
	LOCALIZATION_ZORLEN_FrostTrap = "Pi\195\168ge de givre"
	LOCALIZATION_ZORLEN_ExplosiveTrap = "Pi\195\168ge explosif"
	LOCALIZATION_ZORLEN_ImmolationTrap = "Pi\195\168ge d'Immolation"
	LOCALIZATION_ZORLEN_FeignDeath = "Feindre la mort"
	LOCALIZATION_ZORLEN_Counterattack = "Contre-attaque"
	LOCALIZATION_ZORLEN_TranquilizingShot = "Tir tranquillisant"
	LOCALIZATION_ZORLEN_Disengage = "D\195\169sengagement"
	LOCALIZATION_ZORLEN_EyesOfTheBeast = "Oeil de la b\195\170te"
	LOCALIZATION_ZORLEN_BeastLore = "Connaissance des b\195\170tes"
	LOCALIZATION_ZORLEN_TrackBeasts = "Pistage des b\195\170tes"
	LOCALIZATION_ZORLEN_TrackDemons = "Pistage des d\195\169mons"
	LOCALIZATION_ZORLEN_TrackDragonkin = "Pistage des draconiens"
	LOCALIZATION_ZORLEN_TrackElementals = "Pistage des \195\169l\195\169mentaires"
	LOCALIZATION_ZORLEN_TrackGiants = "Pistage des g\195\169ants"
	LOCALIZATION_ZORLEN_TrackHumanoids = "Pistage des humano\195\175des"
	LOCALIZATION_ZORLEN_TrackUndead = "Pistage des morts-vivants"
	LOCALIZATION_ZORLEN_TrackHidden = "Pistage des camoufl\195\169s"
	LOCALIZATION_ZORLEN_BestialWrath = "Courroux bestial"
	LOCALIZATION_ZORLEN_TrueshotAura = "Aura de pr\195\169cision"
	LOCALIZATION_ZORLEN_ScatterShot = "Fl\195\168che de dispersion"
	LOCALIZATION_ZORLEN_WyvernSting = "Piq\195\187re de wyverne"
	LOCALIZATION_ZORLEN_Deterrence = "Dissuasion"
	LOCALIZATION_ZORLEN_EagleEye = "Oeil d'aigle"
	LOCALIZATION_ZORLEN_RapidFire = "Tir rapide"
	LOCALIZATION_ZORLEN_MultiShot = "Fl\195\168ches multiples"
	LOCALIZATION_ZORLEN_Flare = "Fus\195\169e \195\169clairante"
	LOCALIZATION_ZORLEN_ScareBeast = "Effrayer une b\195\170te"
	LOCALIZATION_ZORLEN_Volley = "Salve"
	LOCALIZATION_ZORLEN_Intimidation = "Intimidation"



-- Zorlen_Warlock.lua file Localization
	--LOCALIZATION_ZORLEN_SoulSiphon = ""
	--LOCALIZATION_ZORLEN_SeedOfCorruption = ""
	--LOCALIZATION_ZORLEN_FelArmor = ""
	--LOCALIZATION_ZORLEN_RitualOfSouls = ""
	--LOCALIZATION_ZORLEN_Soulshatter = ""
	--LOCALIZATION_ZORLEN_Incinerate = ""
	--LOCALIZATION_ZORLEN_UnstableAffliction = ""
	--LOCALIZATION_ZORLEN_DemonicAegis = ""
	--LOCALIZATION_ZORLEN_SummonFelGuard = ""
	--LOCALIZATION_ZORLEN_Shadowfury = ""
	
	--LOCALIZATION_ZORLEN_Bane = ""
	LOCALIZATION_ZORLEN_AmplifyCurse = "Mal\195\169diction amplifi\195\169e"
	LOCALIZATION_ZORLEN_CurseOfAgony = "Mal\195\169diction d'agonie"
	LOCALIZATION_ZORLEN_CurseOfDoom = "Mal\195\169diction funeste"
	LOCALIZATION_ZORLEN_CurseOfShadow = "Mal\195\169diction de l'ombre"
	LOCALIZATION_ZORLEN_CurseOfTheElements = "Mal\195\169diction des \195\169l\195\169ments"
	LOCALIZATION_ZORLEN_CurseOfWeakness = "Mal\195\169diction de faiblesse"
	LOCALIZATION_ZORLEN_CurseOfExhaustion = "Mal\195\169diction de fatigue"
	LOCALIZATION_ZORLEN_CurseOfRecklessness = "Mal\195\169diction de t\195\169m\195\169rit\195\169"
	LOCALIZATION_ZORLEN_CurseOfTongues = "Mal\195\169diction des langages"
	LOCALIZATION_ZORLEN_Corruption = "Corruption"
	LOCALIZATION_ZORLEN_ImprovedCorruption = "Corruption am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_Immolate = "Immolate"
	LOCALIZATION_ZORLEN_SiphonLife = "Siphon de vie"
	LOCALIZATION_ZORLEN_DrainLife = "Drain de vie"
	LOCALIZATION_ZORLEN_DrainMana = "Drain de mana"
	LOCALIZATION_ZORLEN_Hellfire = "lammes infernales"
	LOCALIZATION_ZORLEN_RainOfFire = "Pluie de feu"
	LOCALIZATION_ZORLEN_DrainSoul = "Siphon d'\195\162me"
	LOCALIZATION_ZORLEN_LifeTap = "Connexion"
	LOCALIZATION_ZORLEN_ImprovedLifeTap = "Connexion am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_DarkPact = "Pacte noir"
	LOCALIZATION_ZORLEN_Nightfall = "Cr\195\169puscule"
	LOCALIZATION_ZORLEN_ShadowBolt = "Trait de l'ombre"
	LOCALIZATION_ZORLEN_Banish = "Bannir"
	LOCALIZATION_ZORLEN_Conflagrate = "Conflagration"
	LOCALIZATION_ZORLEN_CreateFirestoneLesser = "Cr\195\169ation de Pierre de feu inf\195\169rieure"
	LOCALIZATION_ZORLEN_CreateFirestone = "Cr\195\169ation de Pierre de feu"
	LOCALIZATION_ZORLEN_CreateFirestoneGreater = "Cr\195\169ation de Pierre de feu sup\195\169rieure"
	LOCALIZATION_ZORLEN_CreateFirestoneMajor = "Cr\195\169ation de Pierre de feu majeure"
	LOCALIZATION_ZORLEN_CreateHealthstoneMinor = "Cr\195\169ation de Pierre de soins mineure"
	LOCALIZATION_ZORLEN_CreateHealthstoneLesser = "Cr\195\169ation de Pierre de soins inf\195\169rieure"
	LOCALIZATION_ZORLEN_CreateHealthstone = "Cr\195\169ation de Pierre de soins"
	LOCALIZATION_ZORLEN_CreateHealthstoneGreater = "Cr\195\169ation de Pierre de soins sup\195\169rieure"
	LOCALIZATION_ZORLEN_CreateHealthstoneMajor = "Cr\195\169ation de Pierre de soins majeure"
	LOCALIZATION_ZORLEN_CreateSoulstoneMinor = "Cr\195\169ation de Pierre d'\195\162me mineure"
	LOCALIZATION_ZORLEN_CreateSoulstoneLesser = "Cr\195\169ation de Pierre d'\195\162me inf\195\169rieure"
	LOCALIZATION_ZORLEN_CreateSoulstone = "Cr\195\169ation de Pierre d'\195\162me"
	LOCALIZATION_ZORLEN_CreateSoulstoneGreater = "Cr\195\169ation de Pierre d'\195\162me sup\195\169rieure"
	LOCALIZATION_ZORLEN_CreateSoulstoneMajor = "Cr\195\169ation de Pierre d'\195\162me majeure"
	LOCALIZATION_ZORLEN_CreateSpellstone = "Cr\195\169ation de Pierre de sort"
	LOCALIZATION_ZORLEN_CreateSpellstoneGreater = "Cr\195\169ation de Pierre de sort sup\195\169rieur"
	LOCALIZATION_ZORLEN_CreateSpellstoneMajor = "Cr\195\169ation de Pierre de sort majeure"
	LOCALIZATION_ZORLEN_DeathCoil = "Voile mortel"
	LOCALIZATION_ZORLEN_DemonArmor = "Armure d\195\169moniaque"
	LOCALIZATION_ZORLEN_DemonSkin = "Peau de d\195\169mon"
	LOCALIZATION_ZORLEN_DemonicSacrifice = "Sacrifice d\195\169moniaque"
	LOCALIZATION_ZORLEN_DetectLesserInvisibility = "D\195\169tection de l'invisibilit\195\169 inf\195\169rieure"
	LOCALIZATION_ZORLEN_DetectInvisibility = "D\195\169tection de l'invisibilit\195\169"
	LOCALIZATION_ZORLEN_DetectGreaterInvisibility = "D\195\169tection de l'invisibilit\195\169 sup\195\169rieure"
	LOCALIZATION_ZORLEN_EnslaveDemon = "Asservir d\195\169mon"
	LOCALIZATION_ZORLEN_EyeOfKilrogg = "Oeil de Kilrogg"
	LOCALIZATION_ZORLEN_Fear = "Peur"
	LOCALIZATION_ZORLEN_FelDomination = "Domination corrompue"
	LOCALIZATION_ZORLEN_HealthFunnel = "Captation de vie"
	LOCALIZATION_ZORLEN_HowlOfTerror = "Hurlement de terreur"
	LOCALIZATION_ZORLEN_Inferno = "Inferno"
	LOCALIZATION_ZORLEN_RitualOfDoom = "Rituel de mal\195\169diction"
	LOCALIZATION_ZORLEN_RitualOfSummoning = "Rituel d'invocation"
	LOCALIZATION_ZORLEN_SearingPain = "Douleur br\195\187lante"
	LOCALIZATION_ZORLEN_SenseDemons = "D\195\169tection des d\195\169mons"
	LOCALIZATION_ZORLEN_ShadowWard = "Gardien de l'ombre"
	LOCALIZATION_ZORLEN_Shadowburn = "Br\195\187lure de l'ombre"
	LOCALIZATION_ZORLEN_SoulFire = "Feu de l'\195\162me"
	LOCALIZATION_ZORLEN_SoulLink = "Lien spirituel"
	LOCALIZATION_ZORLEN_SummonDreadsteed = "Invocation d'un Destrier de l'Effroi"
	LOCALIZATION_ZORLEN_SummonFelhunter = "Invocation d'un chasseur corrompu"
	LOCALIZATION_ZORLEN_SummonFelsteed = "Invocation d'un palefroi corrompu"
	LOCALIZATION_ZORLEN_SummonImp = "Invocation d'un diablotin"
	LOCALIZATION_ZORLEN_SummonSuccubus = "Invocation d'une succube"
	LOCALIZATION_ZORLEN_SummonVoidwalker = "Invocation d'un marcheur du Vide"
	LOCALIZATION_ZORLEN_UnendingBreath = "Respiration interminable"
	LOCALIZATION_ZORLEN_FelConcentration = "Concentration corrompue"



-- Zorlen_Druid.lua file Localization
	LOCALIZATION_ZORLEN_TravelForm = "Forme de voyage"
	LOCALIZATION_ZORLEN_MoonkinForm = "Forme de s\195\169l\195\169nien"
	LOCALIZATION_ZORLEN_BearForm = "Forme d'ours"
	LOCALIZATION_ZORLEN_DireBearForm = "Forme d'ours redoutable"
	LOCALIZATION_ZORLEN_CatForm = "Forme de f\195\169lin"
	LOCALIZATION_ZORLEN_AquaticForm = "Forme aquatique"
	LOCALIZATION_ZORLEN_ChallengingRoar = "Rugissement provocateur"
	LOCALIZATION_ZORLEN_DemoralizingRoar = "Rugissement d\195\169moralisant"
	LOCALIZATION_ZORLEN_AbolishPoison = "Abolir le poison"
	LOCALIZATION_ZORLEN_Barkskin = "Ecorce"
	LOCALIZATION_ZORLEN_Bash = "Sonner"
	LOCALIZATION_ZORLEN_Claw = "Griffe"
	LOCALIZATION_ZORLEN_Cower = "D\195\169robade"
	LOCALIZATION_ZORLEN_Dash = "C\195\169l\195\169rit\195\169"
	LOCALIZATION_ZORLEN_Enrage = "Enrager"
	LOCALIZATION_ZORLEN_EntanglingRoots = "Sarments"
	LOCALIZATION_ZORLEN_FaerieFire = "Lucioles"
	--LOCALIZATION_ZORLEN_FaerieFireFeral = ""
	LOCALIZATION_ZORLEN_FeralCharge = "Charge farouche"
	LOCALIZATION_ZORLEN_FerociousBite = "Morsure f\195\169roce"
	LOCALIZATION_ZORLEN_FrenziedRegeneration = "R\195\169g\195\169n\195\169ration fr\195\169n\195\169tique"
	LOCALIZATION_ZORLEN_GiftOfTheWild = "Don du fauve"
	LOCALIZATION_ZORLEN_HealingTouch = "Toucher gu\195\169risseur"
	LOCALIZATION_ZORLEN_Hibernate = "Hibernation"
	LOCALIZATION_ZORLEN_Hurricane = "Ouragan"
	LOCALIZATION_ZORLEN_Innervate = "Innervation"
	LOCALIZATION_ZORLEN_InsectSwarm = "Essaim d'insectes"
	LOCALIZATION_ZORLEN_LeaderOfThePack = "Chef de la meute"
	LOCALIZATION_ZORLEN_MarkOfTheWild = "Marque du fauve"
	LOCALIZATION_ZORLEN_Maul = "Mutiler"
	LOCALIZATION_ZORLEN_Moonfire = "Eclat lunaire"
	LOCALIZATION_ZORLEN_NaturesGrasp = "Emprise de la nature"
	LOCALIZATION_ZORLEN_NaturesSwiftness = "Rapidit\195\169 de la nature"
	LOCALIZATION_ZORLEN_OmenOfClarity = "Augure de clart\195\169"
	LOCALIZATION_ZORLEN_Pounce = "Traquenard"
	LOCALIZATION_ZORLEN_Prowl = "R\195\180der"
	LOCALIZATION_ZORLEN_Rake = "Griffure"
	LOCALIZATION_ZORLEN_Ravage = "Ravage"
	LOCALIZATION_ZORLEN_Rebirth = "Renaissance"
	LOCALIZATION_ZORLEN_Regrowth = "R\195\169tablissement"
	LOCALIZATION_ZORLEN_Rejuvenation = "R\195\169cup\195\169ration"
	LOCALIZATION_ZORLEN_RemoveCurse = "D\195\169livrance de la mal\195\169diction"
	LOCALIZATION_ZORLEN_Rip = "D\195\169chirure"
	LOCALIZATION_ZORLEN_Shred = "Lambeau"
	LOCALIZATION_ZORLEN_SootheAnimal = "Apaiser les animaux"
	LOCALIZATION_ZORLEN_Starfire = "Feu stellaire"
	LOCALIZATION_ZORLEN_Swipe = "Balayage"
	LOCALIZATION_ZORLEN_Thorns = "Epines"
	LOCALIZATION_ZORLEN_TigersFury = "Fureur du tigre"
	LOCALIZATION_ZORLEN_TrackHumanoids = "Pistage des humano\195\175des"
	LOCALIZATION_ZORLEN_Tranquility = "Tranquillit\195\169"
	LOCALIZATION_ZORLEN_Wrath = "Col\195\168re"
	LOCALIZATION_ZORLEN_ImprovedWrath = "Col\195\168re am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_ImprovedNaturesGrasp = "Emprise de la nature am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_ImprovedEntanglingRoots = "Sarments am\195\169lior\195\169s"
	LOCALIZATION_ZORLEN_ImprovedMoonfire = "Eclat lunaire am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_NaturalWeapons = "Armes naturelles"
	LOCALIZATION_ZORLEN_NaturalShapeshifter = "Changeforme naturel"
	LOCALIZATION_ZORLEN_ImprovedThorns = "Epines am\195\169lior\195\169es"
	LOCALIZATION_ZORLEN_NaturesReach = "Allonge de la Nature"
	LOCALIZATION_ZORLEN_Vengeance = "Vengeance"
	LOCALIZATION_ZORLEN_ImprovedStarfire = "Feu stellaire am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_NaturesGrace = "Gr\195\162ce de la nature"
	LOCALIZATION_ZORLEN_Moonglow = "Lueur de la lune"
	LOCALIZATION_ZORLEN_Moonfury = "Fureur lunaire"
	LOCALIZATION_ZORLEN_Ferocity = "Ferocit\195\169"
	LOCALIZATION_ZORLEN_FeralAggression = "Agressivit\195\169 farouche"
	LOCALIZATION_ZORLEN_FeralInstinct = "Instinct farouche"
	LOCALIZATION_ZORLEN_BrutalImpact = "Impact brutal"
	LOCALIZATION_ZORLEN_ThickHide = "Peau \195\169paisse"
	LOCALIZATION_ZORLEN_FelineSwiftness = "C\195\169l\195\169rit\195\169 f\195\169line"
	LOCALIZATION_ZORLEN_SharpenedClaws = "Griffes aiguis\195\169es"
	LOCALIZATION_ZORLEN_ImprovedShred = "Lambeau am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_PredatoryStrikes = "Frappes de pr\195\169dateur"
	LOCALIZATION_ZORLEN_BloodFrenzy = "Fr\195\169n\195\169sie sanglante"
	LOCALIZATION_ZORLEN_PrimalFury = "Fureur primitive"
	LOCALIZATION_ZORLEN_SavageFury = "Frappes sauvages"
	LOCALIZATION_ZORLEN_HeartOfTheWild = "C\197\147ur de fauve"
	LOCALIZATION_ZORLEN_ImprovedMarkOfTheWild = "Marque du fauve am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_Furor = "Fureur"
	LOCALIZATION_ZORLEN_ImprovedHealingTouch = "Toucher gu\195\169risseur am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_NaturesFocus = "Focalisation de la nature"
	LOCALIZATION_ZORLEN_ImprovedEnrage = "Enrager am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_Reflection = "Renvoi"
	LOCALIZATION_ZORLEN_Subtlety = "Discr\195\169tion"
	LOCALIZATION_ZORLEN_TranquilSpirit = "Tranquillit\195\169 de l'esprit"
	LOCALIZATION_ZORLEN_ImprovedRejuvenation = "R\195\169cup\195\169ration am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_GiftOfNature = "Don de la Nature"
	LOCALIZATION_ZORLEN_ImprovedTranquility = "Tranquillit\195\169 am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_ImprovedRegrowth = "R\195\169tablissement am\195\169lior\195\169"
	--LOCALIZATION_ZORLEN_Swiftmend = ""



-- Zorlen_Mage.lua file Localization
	--LOCALIZATION_ZORLEN_ConjuredCinnamonRoll = ""
	--LOCALIZATION_ZORLEN_ConjuredSweetRoll = ""
	--LOCALIZATION_ZORLEN_ConjuredSourdough = ""
	--LOCALIZATION_ZORLEN_ConjuredPumpernickel = ""
	--LOCALIZATION_ZORLEN_ConjuredRye = ""
	--LOCALIZATION_ZORLEN_ConjuredBread = ""
	--LOCALIZATION_ZORLEN_ConjuredMuffin = ""
	--LOCALIZATION_ZORLEN_ConjuredCrystalWater = ""
	--LOCALIZATION_ZORLEN_ConjuredSparklingWater = ""
	--LOCALIZATION_ZORLEN_ConjuredMineralWater = ""
	--LOCALIZATION_ZORLEN_ConjuredSpringWater = ""
	--LOCALIZATION_ZORLEN_ConjuredPurifiedWater = ""
	--LOCALIZATION_ZORLEN_ConjuredFreshWater = ""
	--LOCALIZATION_ZORLEN_ConjuredWater = ""
	LOCALIZATION_ZORLEN_AmplifyMagic = "Amplification de la magie"
	LOCALIZATION_ZORLEN_ArcaneBrilliance = "Illumination des arcanes"
	LOCALIZATION_ZORLEN_ArcaneExplosion = "Explosion des arcanes"
	LOCALIZATION_ZORLEN_ArcaneIntellect = "Intelligence des arcanes"
	LOCALIZATION_ZORLEN_ArcaneMissiles = "Projectiles des arcanes"
	LOCALIZATION_ZORLEN_ArcanePower = "Pouvoir des arcanes"
	LOCALIZATION_ZORLEN_BlastWave = "Vague explosive"
	LOCALIZATION_ZORLEN_Blink = "Transfert"
	LOCALIZATION_ZORLEN_Blizzard = "Blizzard"
	LOCALIZATION_ZORLEN_ColdSnap = "Morsure de glace"
	LOCALIZATION_ZORLEN_Combustion = "Combustion"
	LOCALIZATION_ZORLEN_ConeOfCold = "C\195\180ne de froid"
	LOCALIZATION_ZORLEN_ConjureFood = "Invocation de nourriture"
	LOCALIZATION_ZORLEN_ConjureManaAgate = "Invocation d'une agate de mana"
	LOCALIZATION_ZORLEN_ConjureManaJade = "Invocation d'une jade de mana"
	LOCALIZATION_ZORLEN_ConjureManaCitrine = "Invocation d'une citrine de mana"
	LOCALIZATION_ZORLEN_ConjureManaRuby = "Invocation d'un rubis de mana"
	LOCALIZATION_ZORLEN_ConjureWater = "Invocation d'eau"
	LOCALIZATION_ZORLEN_Counterspell = "Contresort"
	LOCALIZATION_ZORLEN_DampenMagic = "Att\195\169nuation de la magie"
	LOCALIZATION_ZORLEN_DetectMagic = "D\195\169tection de la magie"
	LOCALIZATION_ZORLEN_Evocation = "Evocation"
	LOCALIZATION_ZORLEN_FireBlast = "Trait de feu"
	LOCALIZATION_ZORLEN_FireWard = "Gardien de feu"
	LOCALIZATION_ZORLEN_Fireball = "Boule de feu"
	LOCALIZATION_ZORLEN_Flamestrike = "Choc de flammes"
	LOCALIZATION_ZORLEN_FrostArmor = "Armure de givre"
	LOCALIZATION_ZORLEN_FrostNova = "Nova de givre"
	LOCALIZATION_ZORLEN_FrostWard = "Gardien de givre"
	LOCALIZATION_ZORLEN_Frostbolt = "Eclair de givre"
	LOCALIZATION_ZORLEN_IceArmor = "Armure de glace"
	LOCALIZATION_ZORLEN_IceBarrier = "Barri\195\168re de glace"
	LOCALIZATION_ZORLEN_IceBlock = "Parade de glace"
	LOCALIZATION_ZORLEN_MageArmor = "Armure du mage"
	LOCALIZATION_ZORLEN_ManaShield = "Bouclier de mana"
	LOCALIZATION_ZORLEN_Polymorph = "M\195\169tamorphose"
	LOCALIZATION_ZORLEN_PortalDarnassus = "Portail : Darnassus"
	LOCALIZATION_ZORLEN_PortalIronforge = "Portail : Ironforge"
	LOCALIZATION_ZORLEN_PortalOrgrimmar = "Portail : Orgrimmar"
	LOCALIZATION_ZORLEN_PortalStormwind = "Portail\194\160: Stormwind"
	LOCALIZATION_ZORLEN_PortalThunderBluff = "Portail : Thunder Bluff"
	LOCALIZATION_ZORLEN_PortalUndercity = "Portail : Undercity"
	LOCALIZATION_ZORLEN_TeleportDarnassus = "T\195\169l\195\169portation\194\160: Darnassus"
	LOCALIZATION_ZORLEN_TeleportIronforge = "T\195\169l\195\169portation\194\160: Ironforge"
	LOCALIZATION_ZORLEN_TeleportOrgrimmar = "T\195\169l\195\169portation\194\160: Orgrimmar"
	LOCALIZATION_ZORLEN_TeleportStormwind = "T\195\169l\195\169portation\194\160: Stormwind"
	LOCALIZATION_ZORLEN_TeleportThunderBluff = "T\195\169l\195\169portation\194\160: Thunder Bluff"
	LOCALIZATION_ZORLEN_TeleportUndercity = "T\195\169l\195\169portation\194\160: Undercity"
	LOCALIZATION_ZORLEN_PresenceOfMind = "Pr\195\169sence spirituelle"
	LOCALIZATION_ZORLEN_Pyroblast = "Explosion pyrotechnique"
	LOCALIZATION_ZORLEN_RemoveLesserCurse = "D\195\169livrance de la mal\195\169diction mineure"
	LOCALIZATION_ZORLEN_Scorch = "Br\195\187lure"
	LOCALIZATION_ZORLEN_SlowFall = "Chute lente"



-- Zorlen_Paladin.lua file Localization
	LOCALIZATION_ZORLEN_BlessingOfFreedom = "B\195\169n\195\169diction de libert\195\169"
	LOCALIZATION_ZORLEN_BlessingOfKings = "B\195\169n\195\169diction des rois"
	LOCALIZATION_ZORLEN_BlessingOfLight = "B\195\169n\195\169diction de lumi\195\168re"
	LOCALIZATION_ZORLEN_BlessingOfMight = "B\195\169n\195\169diction de puissance"
	LOCALIZATION_ZORLEN_BlessingOfProtection = "B\195\169n\195\169diction de protection"
	LOCALIZATION_ZORLEN_BlessingOfSacrifice = "B\195\169n\195\169diction de sacrifice"
	LOCALIZATION_ZORLEN_BlessingOfSalvation = "B\195\169n\195\169diction de salut"
	LOCALIZATION_ZORLEN_BlessingOfSanctuary = "B\195\169n\195\169diction du sanctuaire"
	LOCALIZATION_ZORLEN_BlessingOfWisdom = "B\195\169n\195\169diction de sagesse"
	LOCALIZATION_ZORLEN_Cleanse = "Epuration"
	LOCALIZATION_ZORLEN_ConcentrationAura = "Aura de concentration"
	LOCALIZATION_ZORLEN_Consecration = "Cons\195\169cration"
	LOCALIZATION_ZORLEN_DevotionAura = "Aura de d\195\169votion"
	LOCALIZATION_ZORLEN_DivineFavor = "Faveur divine"
	LOCALIZATION_ZORLEN_DivineIntervention = "Intervention divine"
	LOCALIZATION_ZORLEN_DivineProtection = "Protection divine"
	LOCALIZATION_ZORLEN_DivineShield = "Bouclier divin"
	LOCALIZATION_ZORLEN_Exorcism = "Exorcisme"
	LOCALIZATION_ZORLEN_FireResistanceAura = "Aura de r\195\169sistance au Feu"
	LOCALIZATION_ZORLEN_FlashOfLight = "Eclair lumineux"
	LOCALIZATION_ZORLEN_FrostResistanceAura = "Aura de r\195\169sistance au Givre"
	LOCALIZATION_ZORLEN_GreaterBlessingOfKings = "B\195\169n\195\169diction des rois sup\195\169rieure"
	LOCALIZATION_ZORLEN_GreaterBlessingOfLight = "B\195\169n\195\169diction de lumi\195\168re sup\195\169rieure"
	LOCALIZATION_ZORLEN_GreaterBlessingOfMight = "B\195\169n\195\169diction de puissance sup\195\169rieure"
	LOCALIZATION_ZORLEN_GreaterBlessingOfSalvation = "B\195\169n\195\169diction de salut sup\195\169rieure"
	LOCALIZATION_ZORLEN_GreaterBlessingOfSanctuary = "B\195\169n\195\169diction du sanctuaire sup\195\169rieure"
	LOCALIZATION_ZORLEN_GreaterBlessingOfWisdom = "B\195\169n\195\169diction de sagesse sup\195\169rieure"
	LOCALIZATION_ZORLEN_HammerOfJustice = "Marteau de la justice"
	LOCALIZATION_ZORLEN_HammerOfWrath = "Marteau de courroux"
	LOCALIZATION_ZORLEN_HolyLight = "Lumi\195\168re sacr\195\169e"
	LOCALIZATION_ZORLEN_HolyShield = "Bouclier sacr\195\169"
	LOCALIZATION_ZORLEN_HolyShock = "Horion sacr\195\169"
	LOCALIZATION_ZORLEN_HolyWrath = "Col\195\168re divine"
	LOCALIZATION_ZORLEN_Judgement = "Jugement"
	LOCALIZATION_ZORLEN_LayOnHands = "Imposition des mains"
	LOCALIZATION_ZORLEN_Purify = "Purification"
	LOCALIZATION_ZORLEN_Redemption = "R\195\169demption"
	LOCALIZATION_ZORLEN_Repentance = "Repentir"
	LOCALIZATION_ZORLEN_RetributionAura = "Aura de vindicte"
	LOCALIZATION_ZORLEN_RighteousFury = "Fureur vertueuse"
	LOCALIZATION_ZORLEN_SanctityAura = "Aura de saintet\195\169"
	LOCALIZATION_ZORLEN_SealOfCommand = "Sceau d'autorit\195\169"
	LOCALIZATION_ZORLEN_SealOfJustice = "Sceau de justice"
	LOCALIZATION_ZORLEN_SealOfLight = "Sceau de lumi\195\168re"
	LOCALIZATION_ZORLEN_SealOfRighteousness = "Sceau de pi\195\169t\195\169"
	LOCALIZATION_ZORLEN_SealOfWisdom = "Sceau de sagesse"
	LOCALIZATION_ZORLEN_SealOfTheCrusader = "Sceau du Crois\195\169"
	LOCALIZATION_ZORLEN_SenseUndead = "D\195\169tection des morts-vivants"
	LOCALIZATION_ZORLEN_ShadowResistanceAura = "Aura de r\195\169sistance \195\160 l'Ombre"
	LOCALIZATION_ZORLEN_SummonCharger = "Invocation de destrier"
	LOCALIZATION_ZORLEN_SummonWarhorse = "Invocation d'un cheval de guerre"
	LOCALIZATION_ZORLEN_TurnUndead = "Renvoi des morts-vivants"



-- Zorlen_Priest.lua file Localization
	--LOCALIZATION_ZORLEN_PowerInfusion = ""
	--LOCALIZATION_ZORLEN_Lightwell = ""
	LOCALIZATION_ZORLEN_AbolishDisease = "Abolir maladie"
	LOCALIZATION_ZORLEN_CureDisease = "Gu\195\169rison des maladies"
	LOCALIZATION_ZORLEN_DesperatePrayer = "Pri\195\168re du d\195\169sespoir"
	LOCALIZATION_ZORLEN_DevouringPlague = "Peste d\195\169vorante"
	LOCALIZATION_ZORLEN_DispelMagic = "Dissipation de la magie"
	LOCALIZATION_ZORLEN_DivineSpirit = "Esprit divin"
	LOCALIZATION_ZORLEN_ElunesGrace = "Gr\195\162ce d'Elune"
	LOCALIZATION_ZORLEN_Fade = "Oubli"
	LOCALIZATION_ZORLEN_FearWard = "Gardien de peur"
	LOCALIZATION_ZORLEN_Feedback = "R\195\169action"
	LOCALIZATION_ZORLEN_FlashHeal = "Soins rapides"
	LOCALIZATION_ZORLEN_FocusedCasting = "Incantation focalis\195\169e"
	LOCALIZATION_ZORLEN_LesserHeal = "Soins inf\195\169rieurs"
	LOCALIZATION_ZORLEN_Heal = "Soins"
	LOCALIZATION_ZORLEN_GreaterHeal = "Soins sup\195\169rieurs"
	LOCALIZATION_ZORLEN_HexOfWeakness = "Mal\195\169fice de faiblesse"
	LOCALIZATION_ZORLEN_HolyFire = "Flammes sacr\195\169es"
	LOCALIZATION_ZORLEN_HolyNova = "Nova sacr\195\169e"
	LOCALIZATION_ZORLEN_InnerFire = "Feu int\195\169rieur"
	LOCALIZATION_ZORLEN_InnerFocus = "Focalisation am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_Levitate = "L\195\169vitation"
	LOCALIZATION_ZORLEN_ManaBurn = "Br\195\187lure de mana"
	LOCALIZATION_ZORLEN_MindBlast = "Attaque mentale"
	LOCALIZATION_ZORLEN_MindControl = "Contr\195\180le mental"
	LOCALIZATION_ZORLEN_MindFlay = "Fouet mental"
	LOCALIZATION_ZORLEN_MindSoothe = "Apaisement"
	LOCALIZATION_ZORLEN_MindVision = "Vision t\195\169l\195\169pathique"
	LOCALIZATION_ZORLEN_PowerWordFortitude = "Mot de pouvoir : Robustesse"
	LOCALIZATION_ZORLEN_PowerWordShield = "Mot de pouvoir : Bouclier"
	LOCALIZATION_ZORLEN_PrayerOfFortitude = "Pri\195\168re de robustesse"
	LOCALIZATION_ZORLEN_PrayerOfHealing = "Pri\195\168re de soins"
	LOCALIZATION_ZORLEN_PsychicScream = "Cri psychique"
	LOCALIZATION_ZORLEN_Renew = "R\195\169novation"
	LOCALIZATION_ZORLEN_Resurrection = "R\195\169surrection"
	LOCALIZATION_ZORLEN_ShackleUndead = "Entraves des morts-vivants"
	LOCALIZATION_ZORLEN_ShadowProtection = "Protection contre l'Ombre"
	LOCALIZATION_ZORLEN_ShadowWordPain = "Mot de l'ombre\194\160: Douleur"
	LOCALIZATION_ZORLEN_Shadowform = "Forme d'Ombre"
	LOCALIZATION_ZORLEN_Shadowguard = "Garde de l'ombre"
	LOCALIZATION_ZORLEN_Silence = "Silence"
	LOCALIZATION_ZORLEN_Smite = "Ch\195\162timent"
	LOCALIZATION_ZORLEN_SpiritOfRedemption = "Esprit de r\195\169demption"
	LOCALIZATION_ZORLEN_Starshards = "Eclats stellaires"
	LOCALIZATION_ZORLEN_TouchOfWeakness = "Toucher de faiblesse"
	LOCALIZATION_ZORLEN_VampiricEmbrace = "Etreinte vampirique"



-- Zorlen_Rogue.lua file Localization
	LOCALIZATION_ZORLEN_ImprovedCheapShot = "Coup bas am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_ImprovedSinisterStrike = "Attaque pernicieuse am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_CripplingPoison = "Poison affaiblissant"
	LOCALIZATION_ZORLEN_CripplingPoisonII = "Poison affaiblissant I"
	LOCALIZATION_ZORLEN_DeadlyPoison = "Poison mortel"
	LOCALIZATION_ZORLEN_DeadlyPoisonII = "Poison mortel II"
	LOCALIZATION_ZORLEN_DeadlyPoisonIII = "Poison mortel III"
	LOCALIZATION_ZORLEN_DeadlyPoisonIV = "Poison mortel IV"
	LOCALIZATION_ZORLEN_DeadlyPoisonV = "Poison mortel V"
	LOCALIZATION_ZORLEN_InstantPoison = "Poison instantan\195\169"
	LOCALIZATION_ZORLEN_InstantPoisonII = "Poison instantan\195\169 II"
	LOCALIZATION_ZORLEN_InstantPoisonIII = "Poison instantan\195\169 III"
	LOCALIZATION_ZORLEN_InstantPoisonIV = "Poison instantan\195\169 IV"
	LOCALIZATION_ZORLEN_InstantPoisonV = "Poison instantan\195\169 V"
	LOCALIZATION_ZORLEN_InstantPoisonVI = "Poison instantan\195\169 VI"
	LOCALIZATION_ZORLEN_MindnumbingPoison = "Poison de distraction mentale"
	LOCALIZATION_ZORLEN_MindnumbingPoisonII = "Poison de distraction mentale II"
	LOCALIZATION_ZORLEN_MindnumbingPoisonIII = "Poison de distraction mentale III"
	LOCALIZATION_ZORLEN_WoundPoison = "Poison douloureux"
	LOCALIZATION_ZORLEN_WoundPoisonII = "Poison douloureux II"
	LOCALIZATION_ZORLEN_WoundPoisonIII = "Poison douloureux III"
	LOCALIZATION_ZORLEN_WoundPoisonIV = "Poison douloureux IV"
	LOCALIZATION_ZORLEN_AdrenalineRush = "Adrenaline Rush"
	LOCALIZATION_ZORLEN_Ambush = "Embuscade"
	LOCALIZATION_ZORLEN_Backstab = "Attaque sournoise"
	LOCALIZATION_ZORLEN_BladeFlurry = "D\195\169luge de lames"
	LOCALIZATION_ZORLEN_Blind = "C\195\169cit\195\169"
	LOCALIZATION_ZORLEN_BlindingPowder = "Poudre aveuglante"
	LOCALIZATION_ZORLEN_CheapShot = "Coup bas"
	LOCALIZATION_ZORLEN_ColdBlood = "Sang froid"
	LOCALIZATION_ZORLEN_DetectTraps = "D\195\169tection des pi\195\168ges"
	LOCALIZATION_ZORLEN_DisarmTrap = "D\195\169sarmement de pi\195\168ge"
	LOCALIZATION_ZORLEN_Distract = "Distraction"
	LOCALIZATION_ZORLEN_Evasion = "Evasion"
	LOCALIZATION_ZORLEN_Eviscerate = "Evisc\195\169ration"
	LOCALIZATION_ZORLEN_ExposeArmor = "Exposer l'armure"
	LOCALIZATION_ZORLEN_Feint = "Feinte"
	LOCALIZATION_ZORLEN_Garrote = "Garrot"
	LOCALIZATION_ZORLEN_GhostlyStrike = "Frappe fantomatique"
	LOCALIZATION_ZORLEN_Gouge = "Suriner"
	LOCALIZATION_ZORLEN_Hemorrhage = "H\195\169morragie"
	LOCALIZATION_ZORLEN_Kick = "Coup de pied"
	LOCALIZATION_ZORLEN_KidneyShot = "Aiguillon perfide"
	LOCALIZATION_ZORLEN_PickLock = "Crochetage"
	LOCALIZATION_ZORLEN_PickPocket = "Vol \195\160 la tire"
	LOCALIZATION_ZORLEN_Premeditation = "Pr\195\169m\195\169ditation"
	LOCALIZATION_ZORLEN_Preparation = "Pr\195\169paration"
	LOCALIZATION_ZORLEN_RelentlessStrikes = "Frappes implacables"
	LOCALIZATION_ZORLEN_Riposte = "Riposte"
	LOCALIZATION_ZORLEN_Rupture = "Rupture"
	LOCALIZATION_ZORLEN_Sap = "Assommer"
	LOCALIZATION_ZORLEN_SinisterStrike = "Attaque pernicieuse"
	LOCALIZATION_ZORLEN_SliceAndDice = "D\195\169biter"
	LOCALIZATION_ZORLEN_Sprint = "Sprint"
	LOCALIZATION_ZORLEN_Stealth = "Camouflage"
	LOCALIZATION_ZORLEN_Vanish = "Disparition"



-- Zorlen_Shaman.lua file Localization
	LOCALIZATION_ZORLEN_DiseaseCleansingTotem = "Totem de Purification des maladies"
	LOCALIZATION_ZORLEN_EarthbindTotem = "Totem de lien terrestre"
	LOCALIZATION_ZORLEN_FireNovaTotem = "Totem Nova de feu"
	LOCALIZATION_ZORLEN_FireResistanceTotem = "Totem de r\195\169sistance au feu"
	LOCALIZATION_ZORLEN_FlametongueTotem = "Totem Langue de feu"
	LOCALIZATION_ZORLEN_FrostResistanceTotem = "Totem de r\195\169sistance au Givre"
	LOCALIZATION_ZORLEN_GraceOfAirTotem = "Totem de Gr\195\162ce a\195\169rienne"
	LOCALIZATION_ZORLEN_GroundingTotem = "Totem de Gl\195\168be"
	LOCALIZATION_ZORLEN_HealingStreamTotem = "Totem gu\195\169risseur"
	LOCALIZATION_ZORLEN_MagmaTotem = "Totem de Magma"
	LOCALIZATION_ZORLEN_ManaSpringTotem = "Totem Fontaine de mana"
	LOCALIZATION_ZORLEN_ManaTideTotem = "Totem de Vague de mana"
	LOCALIZATION_ZORLEN_NatureResistanceTotem = "Totem de r\195\169sistance \195\160 la Nature"
	LOCALIZATION_ZORLEN_PoisonCleansingTotem = "Totem de Purification du poison"
	LOCALIZATION_ZORLEN_SearingTotem = "Totem incendiaire"
	LOCALIZATION_ZORLEN_SentryTotem = "Totem Sentinelle"
	LOCALIZATION_ZORLEN_StoneclawTotem = "Totem de Griffes de pierre"
	LOCALIZATION_ZORLEN_StoneskinTotem = "Totem de Peau de pierre"
	LOCALIZATION_ZORLEN_StrengthOfEarthTotem = "Totem de Force de la Terre"
	LOCALIZATION_ZORLEN_TremorTotem = "Totem de S\195\169isme"
	LOCALIZATION_ZORLEN_WindfuryTotem = "Totem Furie-des-vents"
	LOCALIZATION_ZORLEN_WindwallTotem = "Totem de Mur des vents"
	LOCALIZATION_ZORLEN_EarthShock = "Horion de terre"
	LOCALIZATION_ZORLEN_FlameShock = "Horion de flammes"
	LOCALIZATION_ZORLEN_FrostShock = "Horion de givre"
	LOCALIZATION_ZORLEN_FlametongueWeapon = "Arme Langue de feu"
	LOCALIZATION_ZORLEN_FrostbrandWeapon = "Arme de givre"
	LOCALIZATION_ZORLEN_RockbiterWeapon = "Arme Croque-roc"
	LOCALIZATION_ZORLEN_WindfuryWeapon = "Arme Furie-des-vents"
	LOCALIZATION_ZORLEN_AncestralSpirit = "Esprit ancestral"
	LOCALIZATION_ZORLEN_AstralRecall = "Rappel astral"
	LOCALIZATION_ZORLEN_ChainHeal = "Salve de gu\195\169rison"
	LOCALIZATION_ZORLEN_ChainLightning = "Cha\195\174ne d'\195\169clairs"
	LOCALIZATION_ZORLEN_CureDisease = "Gu\195\169rison des maladies"
	LOCALIZATION_ZORLEN_CurePoison = "Gu\195\169rison du poison"
	LOCALIZATION_ZORLEN_ElementalFocus = "Focalisation \195\169l\195\169mentaire"
	LOCALIZATION_ZORLEN_ElementalMastery = "Ma\195\174trise \195\169l\195\169mentaire"
	LOCALIZATION_ZORLEN_FarSight = "Double vue"
	LOCALIZATION_ZORLEN_GhostWolf = "Loup fant\195\180me"
	LOCALIZATION_ZORLEN_LesserHealingWave = "Vague de soins inf\195\169rieurs"
	LOCALIZATION_ZORLEN_HealingWave = "Vague de soins"
	LOCALIZATION_ZORLEN_LightningBolt = "Eclair"
	LOCALIZATION_ZORLEN_LightningShield = "Bouclier de foudre"
	LOCALIZATION_ZORLEN_NaturesSwiftness = "Rapidit\195\169 de la nature"
	LOCALIZATION_ZORLEN_Purge = "Expiation"
	LOCALIZATION_ZORLEN_Reincarnation = "R\195\169incarnation"
	LOCALIZATION_ZORLEN_Stormstrike = "Courroux naturel"
	LOCALIZATION_ZORLEN_WaterBreathing = "Respiration aquatique"
	LOCALIZATION_ZORLEN_WaterWalking = "Marcher sur l\226\128\153eau"



-- Zorlen_Warrior.lua file Localization
	--LOCALIZATION_ZORLEN_Devastate = ""
	--LOCALIZATION_ZORLEN_ImprovedWhirlwind = ""
	--LOCALIZATION_ZORLEN_FocusedRage = ""
	--LOCALIZATION_ZORLEN_CommandingShout = ""
	--LOCALIZATION_ZORLEN_SpellReflection = ""
	--LOCALIZATION_ZORLEN_Intervene = ""
	--LOCALIZATION_ZORLEN_VictoryRush = ""
	--LOCALIZATION_ZORLEN_EndlessRage = ""
	--LOCALIZATION_ZORLEN_Rampage = ""
	
	LOCALIZATION_ZORLEN_ImprovedBloodrage = "Rage sanguinaire am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_ImprovedOverpower = "Fulgurance am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_ImprovedBerserkerRage = "Rage berserker am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_ImprovedExecute = "Ex\195\169cution am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_Execute = "Ex\195\169cution"
	LOCALIZATION_ZORLEN_ImprovedHeroicStrike = "Frappe h\195\169ro\195\175que am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN_HeroicStrike = "Frappe h\195\169ro\195\175que"
	LOCALIZATION_ZORLEN_ImprovedSunderArmor = "Fracasser armure am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_SunderArmor = "Fracasser armure"
	LOCALIZATION_ZORLEN_ImprovedThunderClap = "Coup de tonnerre am\195\169lior\195\169"
	LOCALIZATION_ZORLEN_ThunderClap = "Coup de tonnerre"
	LOCALIZATION_ZORLEN_MortalStrike = "Frappe mortelle"
	LOCALIZATION_ZORLEN_Bloodthirst = "Sanguinaire"
	LOCALIZATION_ZORLEN_ShieldSlam = "Heurt de bouclier"
	LOCALIZATION_ZORLEN_Charge = "Charge"
	LOCALIZATION_ZORLEN_Taunt = "Provocation"
	LOCALIZATION_ZORLEN_Intercept = "Interception"
	LOCALIZATION_ZORLEN_Overpower = "Fulgurance"
	LOCALIZATION_ZORLEN_Revenge = "Vengeance"
	LOCALIZATION_ZORLEN_Rend = "Pourfendre"
	LOCALIZATION_ZORLEN_Hamstring = "Brise-genou"
	LOCALIZATION_ZORLEN_ShieldBash = "Coup de bouclier"
	LOCALIZATION_ZORLEN_Pummel = "Vol\195\169e de coups"
	LOCALIZATION_ZORLEN_ShieldBlock = "Ma\195\174trise du blocage"
	LOCALIZATION_ZORLEN_DemoralizingShout = "Cri d\195\169moralisant"
	LOCALIZATION_ZORLEN_BattleShout = "Cri de guerre"
	LOCALIZATION_ZORLEN_BerserkerRage = "Rage berserker"
	LOCALIZATION_ZORLEN_Enrage = "Enrager"
	LOCALIZATION_ZORLEN_DefensiveStance = "Posture d\195\169fensive"
	LOCALIZATION_ZORLEN_BattleStance = "Posture de combat"
	LOCALIZATION_ZORLEN_BerserkerStance = "Posture berserker"
	LOCALIZATION_ZORLEN_AngerManagement = "Ma\195\174trise de la Rage"
	LOCALIZATION_ZORLEN_Bloodrage = "Rage sanguinaire"
	LOCALIZATION_ZORLEN_ChallengingShout = "Cri de d\195\169fi"
	LOCALIZATION_ZORLEN_Cleave = "Encha\195\174nement"
	LOCALIZATION_ZORLEN_ConcussionBlow = "Bourrasque"
	LOCALIZATION_ZORLEN_DeathWish = "Souhait mortel"
	LOCALIZATION_ZORLEN_Disarm = "D\195\169sarmement"
	LOCALIZATION_ZORLEN_IntimidatingShout = "Cri d'intimidation"
	LOCALIZATION_ZORLEN_LastStand = "Dernier rempart"
	LOCALIZATION_ZORLEN_MockingBlow = "Coup railleur"
	LOCALIZATION_ZORLEN_PiercingHowl = "Hurlement per\195\167ant"
	LOCALIZATION_ZORLEN_Recklessness = "T\195\169m\195\169rit\195\169"
	LOCALIZATION_ZORLEN_Retaliation = "Repr\195\169sailles"
	LOCALIZATION_ZORLEN_ShieldWall = "Mur protecteur"
	LOCALIZATION_ZORLEN_Slam = "Heurtoir"
	LOCALIZATION_ZORLEN_SweepingStrikes = "Attaques circulaires"
	LOCALIZATION_ZORLEN_Whirlwind = "Tourbillon"
	LOCALIZATION_ZORLEN_TacticalMastery = "Ma\195\174trise tactique"



-- Fire Immune MOB's
 -- Molten Core
	LOCALIZATION_ZORLEN_Firelord = "Seigneur du feu"
	LOCALIZATION_ZORLEN_Firewalker = "Marchefeu"
	LOCALIZATION_ZORLEN_Flameguard = "Garde des flammes"
	LOCALIZATION_ZORLEN_LavaSpawn = "El\195\169mentaire de lave"
	LOCALIZATION_ZORLEN_BaronGeddon = "Baron Geddon"
	LOCALIZATION_ZORLEN_Ragnaros = "Ragnaros"
 -- Upper Blackrock Spire
	LOCALIZATION_ZORLEN_PyroguardEmberseer = "Pyrogarde Proph\195\168te ardent"
 -- Blackrock Depths
	LOCALIZATION_ZORLEN_Fireguard = "Garde du feu"
	LOCALIZATION_ZORLEN_FireguardDestroyer = "Destructeur garde du feu"
	LOCALIZATION_ZORLEN_BlazingFireguard = "Garde du feu flamboyant"
	LOCALIZATION_ZORLEN_AmbassadorFlamelash = "Ambassadeur Flamelash"
	LOCALIZATION_ZORLEN_LordIncendius = "Seigneur Incendius"
 --Searing Gorge
	LOCALIZATION_ZORLEN_BlazingElemental = "El\195\169mentaire flamboyant"
	LOCALIZATION_ZORLEN_InfernoElemental = "El\195\169mentaire infernal"
 --Un'Goro Crater
	--LOCALIZATION_ZORLEN_ScorchingElemental = ""
	--LOCALIZATION_ZORLEN_LivingBlaze = ""
	--LOCALIZATION_ZORLEN_Blazerunner = ""

-- Drain Life Immune MOB's
 -- Blackrock Depths
	LOCALIZATION_ZORLEN_MoltenWarGolem = "Golem de lave de guerre"
	LOCALIZATION_ZORLEN_PanzorTheInvincible = "Panzor l'Invincible"
 --Searing Gorge
	LOCALIZATION_ZORLEN_HeavyWarGolem = "Golem de guerre lourd"
	LOCALIZATION_ZORLEN_FaultyWarGolem = "Golem de guerre d\195\169faillant"
	LOCALIZATION_ZORLEN_TemperedWarGolem = "Golem de guerre"
	LOCALIZATION_ZORLEN_RagereaverGolem = "Golem ravageur enrag\195\169"
end
