
DART_CUSTOM_SETTINGS = {
		[1] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = -2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 138,
			["scale"] = 1.25,
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 276,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 2",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 625.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["yoffset"] = {
				[1] = -630.6,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[2] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1.25,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = -2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["height"] = 138,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 276,
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 2",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 120.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -631.6,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[3] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\leftframe1",
			["height"] = 266,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 3",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = -732.41,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -479,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[4] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\rightframe1",
			["height"] = 266,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 4",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 723.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -479.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[5] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.95,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["height"] = 138,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 522,
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 5",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 65.24,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chattopleft1",
			["yoffset"] = {
				[1] = -282.87,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[6] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hide"] = true,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["height"] = 138,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chattopright1",
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 522,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 6",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 65.5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -312.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[7] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 10,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hide"] = true,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\logo",
			["height"] = 138,
			["hidebg"] = true,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 138,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["scale"] = 0.75,
			["name"] = "Texture 7",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 33,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -255.5,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[8] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chattopleft1",
			["height"] = 138,
			["scale"] = 0.8,
			["highlightalpha"] = 0,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 522,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 1,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 8",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 211.91,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -972.56,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[9] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 0.9686274509803922,
				["r"] = 0.9372549019607843,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chattopright1",
			["height"] = 108,
			["scale"] = 0.8,
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 492,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 9",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 463.31,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = -10,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -440.67,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[10] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.95,
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = 1,
			["height"] = 266,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["width"] = 266,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 10",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -91.92,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chatbleft1",
			["yoffset"] = {
				[1] = -355.56,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[11] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["height"] = 266,
			["scale"] = 0.95,
			["parent"] = "UIParent",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 11",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 276.7,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\chatbright1",
			["yoffset"] = {
				[1] = -351.43,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[12] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 1,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topmiddel1v2",
			["height"] = 138,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["parent"] = "UIParent",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["width"] = 266,
			["alpha"] = 1,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 12",
			["scale"] = 0.95,
			["xoffset"] = {
				[1] = 9.770014305114728,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = 415,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[13] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["scale"] = 0.95,
			["bgalpha"] = 0,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["scripts"] = {
			},
			["hidebg"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topleft1v2",
			["height"] = 74,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 522,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 13",
			["parent"] = "UIParent",
			["xoffset"] = {
				[1] = -373.35,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = 447.99,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[14] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 74,
			["scale"] = 0.95,
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 522,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 14",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 374.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topright1v2",
			["yoffset"] = {
				[1] = 447,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[15] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topright1v2extra",
			["height"] = 138,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 15",
			["scale"] = 0.95,
			["xoffset"] = {
				[1] = 544.24,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = 415.05,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[16] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\ne\\topleft1v2extra",
			["height"] = 138,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 16",
			["scale"] = 0.95,
			["xoffset"] = {
				[1] = -546.29,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = 415.22,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[17] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\castingbar",
			["bgalpha"] = 1,
			["height"] = 74,
			["hide"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.75,
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["width"] = 522,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 17",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 118.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -241.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[18] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 15,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hide"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 138,
			["hidebg"] = true,
			["scale"] = 0.75,
			["parent"] = "UIParent",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 74,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["name"] = "Texture 18",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = -3.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull2",
			["yoffset"] = {
				[1] = -244.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[19] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scale"] = 0.95,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframeleft",
			["height"] = 522,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 19",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 129,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -483.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[20] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["scale"] = 0.95,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframelright",
			["height"] = 522,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 20",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -65.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -483.25,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		["updatespeed"] = 60,
		["INITIALIZED1.0d"] = true,
		["optionsscale"] = 0.8,
		["autolock"] = 1,
		["INITIALIZED1.1"] = true,
}
