-- [[
-- Version: 1.21
-- Last Updated: 2006/11/08
-- Maintained by: Arith Hsu
-- ]]
if (GetLocale() == 	"zhTW") then

AtlasLoot_LootTypes = { "副本",	"野外首領",	"套裝",	"陣營",	"PvP" };

AtlasLoot_Zones = {
    { 
        { "黑暗深淵", 			"" },
        { "黑石深淵", 			"" },
        { "黑石塔 (下層)", 		"" },
        { "黑石塔 (上層)", 		"" },
        { "黑翼之巢", 			"" },
        { "死亡礦井", 			"" },
        { "厄運之槌 (東)", 		"" },
        { "厄運之槌 (北)", 		"" },
        { "厄運之槌 (西)", 		"" },
        { "諾姆瑞根", 			"" },
        { "瑪拉頓", 			"" },
        { "熔火之心", 			"" },
        { "納克薩瑪斯", 		"" },
        { "奧妮克希亞的巢穴", 	"" },
        { "怒焰裂谷", 			"" },
        { "剃刀高地", 			"" },
        { "剃刀沼澤", 			"" },
        { "安其拉廢墟", 		"" },
        { "血色修道院", 		"" },
        { "通靈學院", 			"" },
        { "影牙城堡", 			"" },
        { "監獄", 				"" },
        { "斯坦索姆", 			"" },
        { "沉沒的神廟", 		"" },
        { "安其拉神廟", 		"" },
        { "奧達曼", 			"" },
        { "哀嚎洞穴", 			"" },
        { "祖爾法拉克", 		"" },
        { "祖爾格拉布", 		"" },
    },
    {
        { "艾索雷葛斯",	"AAzuregos" },
        { "艾莫莉絲", 	"DEmeriss" },
        { "卡札克", 	"KKazzak" },
        { "雷索", 		"DLethon"},
        { "泰拉爾", 	"DTaerar" },
        { "伊索德雷", 	"DYsondre" },
    },
    {
        { "傳說物品", 			"Legendaries" },
        { "PvP套裝 (等級 60)", 	"" },
        { "RAQ 套裝", 			"" },
        { "TAQ 套裝", 			"" },
        { "T0/T0.5套裝", 		"" },
        { "T1套裝", 			"" },
        { "T2套裝", 			"" },
        { "T3套裝", 			"" },
        { "ZG套裝", 			"" },
    },
    {
        { "銀色黎明", 		"" },
        { "諾茲多姆的子嗣",	"AQBroodRings" },
        { "塞納里奧議會", 	"" },
        { "暗月馬戲團", 	"Darkmoon" },
        { "瑟銀兄弟會", 	"" },
        { "木喉要塞", 		"Timbermaw" },
        { "贊達拉部族", 	"" },
    },
    {
        { "奧特蘭克山谷", 		"" },
        { "阿拉希盆地", 		"" },
        { "PvP套裝 (等級 60)", 	"" },
        { "戰歌峽谷", 			"" },
    },
};

AtlasLoot_Bosses = {
    ["黑暗深淵"] = {
        { "加摩拉", 		"BFDGhamoora" },
        { "薩利維絲", 		"BFDLadySarevess" },
        { "格里哈斯特", 	"BFDGelihast" },
        { "阿奎尼斯男爵", 	"BFDBaronAquanis" },
        { "夢遊者克爾里斯",	"BFDTwilightLordKelris" },
        { "瑟拉吉斯	", 		"BFDOldSerrakis" },
        { "阿庫麥爾", 		"BFDAkumai" },
        { "小怪", 			"BFDTrash" },
    },
    ["黑石深淵"] = {
        { "洛考爾", 			"BRDLordRoccor" },
        { "審訊官格斯塔恩", 	"BRDHighInterrogatorGerstahn" },
        { "法律之環, 瑟爾倫", 	"BRDArena" },
        { "馴犬者格雷布瑪爾", 	"BRDHoundmaster" },
        { "控火師羅格雷恩", 	"BRDPyromantLoregrain" },
        { "黑色寶庫", 			"BRDWarderStilgiss" },
        { "弗諾斯·達克維爾", 	"BRDFineousDarkvire" },
        { "伊森迪奧斯", 		"BRDLordIncendius" },
        { "貝爾加", 			"BRDBaelGar" },
        { "安格弗將軍", 		"BRDGeneralAngerforge" },
        { "傀儡統帥阿格曼奇", 	"BRDGolemLordArgelmach" },
        { "黑鐵酒吧", 			"BRDGuzzler" },
        { "弗萊拉斯大使", 		"BRDFlamelash" },
        { "無敵的潘佐爾", 		"BRDPanzor" },
        { "召喚者之墓", 		"BRDTomb" },
        { "瑪格姆斯", 			"BRDMagmus" },
        { "達格蘭·索瑞森大帝", 	"BRDImperatorDagranThaurissan" },
        { "茉艾拉·銅鬚公主", 	"BRDPrincess" },
        { "小怪", 				"BRDTrash" },
    },
    ["黑石塔 (下層)"] = {
        { "歐莫克大王", 		"LBRSOmokk" },
        { "尖石統帥	", 			"LBRSSpirestoneLord" },
        { "暗影獵手沃許加斯", 	"LBRSVosh" },
        { "指揮官沃恩", 		"LBRSVoone" },
        { "莫爾·灰蹄", 			"LBRSGrayhoof" },
        { "煙網蛛后", 			"LBRSSmolderweb" },
        { "水晶之牙", 			"LBRSCrystalFang" },
        { "烏洛克", 			"LBRSDoomhowl" },
        { "軍需官茲格雷斯", 	"LBRSZigris" },
        { "奴役者基茲盧爾", 	"LBRSSlavener" },
        { "哈雷肯", 			"LBRSHalycon" },
        { "維姆薩拉克", 		"LBRSWyrmthalak" },
        { "班諾克·巨斧", 		"LBRSGrimaxe" },
        { "尖石屠夫", 			"LBRSSpirestoneButcher" },
        { "小怪", 				"LBRSTrash" },
    },
    ["黑石塔 (上層)"] = {
        { "烈焰衛士艾博希爾", 	"UBRSEmberseer" },
        { "索拉卡·火冠", 		"UBRSSolakar" },
        { "烈焰之父", 			"UBRSFLAME" },
        { "傑德", 				"UBRSRunewatcher" },
        { "古拉魯克	", 			"UBRSAnvilcrack" },
        { "大酋長雷德·黑手", 	"UBRSRend" },
        { "蓋斯", 				"UBRSGyth" },
        { "比斯巨獸", 			"UBRSBeast" },
        { "瓦薩拉克", 			"UBRSValthalak" },
        { "達基薩斯將軍", 		"UBRSDrakkisath" },
        { "小怪", 				"UBRSTrash" },
    },
    ["黑翼之巢"] = {
        { "狂野的拉佐格爾", 	"BWLRazorgore" },
        { "墮落的瓦拉斯塔茲", 	"BWLVaelastrasz" },
        { "勒西雷爾", 			"BWLLashlayer" },
        { "費爾默", 			"BWLFiremaw" },
        { "埃博諾克", 			"BWLEbonroc" },
        { "弗萊格爾", 			"BWLFlamegor" },
        { "克洛瑪古斯", 		"BWLChromaggus" },
        { "奈法利安", 			"BWLNefarian" },
        { "小怪", 				"BWLTrashMobs" },
    },
    ["死亡礦井"] = {
        { "拉克佐", 			"VCRhahkZor" },
        { "礦工約翰森", 		"VCMinerJohnson" },
        { "斯尼德", 			"VCSneed" },
        { "基爾尼格", 			"VCGilnid" },
        { "綠皮隊長	", 			"VCCaptainGreenskin" },
        { "艾德溫·范克里夫", 	"VCVanCleef" },
        { "重拳先生", 			"VCMrSmite" },
        { "曲奇", 				"VCCookie" },
        { "套裝: 迪菲亞皮甲", 	"VCDefiasSET" },
    },
    ["厄運之槌 (東)"] = {
        { "普希林", 		"DMEPusillin" },
        { "瑟雷姆·刺蹄", 	"DMEZevrimThornhoof" },
        { "海多斯博恩", 	"DMEHydro" },
        { "蕾瑟塔蒂絲", 	"DMELethtendris" },
        { "奧茲恩", 		"DMEAlzzin" },
        { "依薩利恩", 		"DMEIsalien" },
        { "小怪", 			"DMETrash" },
        { "厄運書籍", 		"DMBooks" },
    },
    ["厄運之槌 (北)"] = {
        { "衛兵摩爾達", 	"DMNGuardMoldar" },
        { "踐踏者克雷格", 	"DMNStomperKreeg" },
        { "衛兵芬古斯", 	"DMNGuardFengus" },
        { "諾特·希姆加克", 	"DMNThimblejack" },
        { "衛兵斯里基克", 	"DMNGuardSlipkik" },
        { "克羅卡斯", 		"DMNCaptainKromcrush" },
        { "戈多克大王", 	"DMNKingGordok" },
        { "貢品", 			"DMNTRIBUTERUN" },
        { "厄運書籍", 		"DMBooks" },
    },
    ["厄運之槌 (西)"] = {
        { "特迪斯·扭木", 	"DMWTendrisWarpwood" },
        { "伊琳娜·暗木", 	"DMWIllyannaRavenoak" },
        { "卡雷迪斯鎮長", 	"DMWMagisterKalendris" },
        { "蘇斯", 			"DMWTsuzee" },
        { "伊莫塔爾", 		"DMWImmolthar" },
        { "赫爾努拉斯",		"DMWHelnurath" },
        { "托塞德林王子",	"DMWPrinceTortheldrin" },
        { "小怪",			"DMWTrash" },
        { "厄運書籍",		"DMBooks" },
    },
    ["諾姆瑞根"] = {
        { "粘性輻射塵",				"GnViscousFallout" },
        { "格魯比斯",				"GnGrubbis" },
        { "電刑器6000型",			"GnElectrocutioner6000" },
        { "麥克尼爾·瑟瑪普拉格",	"GnMekgineerThermaplugg" },
        { "黑鐵大師",				"GnDIAmbassador" },
        { "群體打擊者9-60",			"GnCrowdPummeler960" },
        { "小怪",					"GnTrash" },
    },
    ["瑪拉頓"] = {
        { "諾克賽恩",			"MaraNoxxion" },
        { "銳刺鞭笞者",			"MaraRazorlash" },
        { "維利塔恩",			"MaraLordVyletongue" },
        { "收割者麥什洛克",		"MaraMeshlok" },
        { "被詛咒的塞雷布拉斯",	"MaraCelebras" },
        { "蘭斯利德",			"MaraLandslide" },
        { "工匠吉茲洛克",		"MaraTinkererGizlock" },
        { "洛特格里普",			"MaraRotgrip" },
        { "瑟萊德絲公主",		"MaraPrincessTheradras" },
    },
    ["熔火之心"] = {
        { "魯西弗隆",			"MCLucifron" },
        { "瑪格曼達	",			"MCMagmadar" },
        { "基赫納斯",			"MCGehennas" },
        { "加爾",				"MCGarr" },
        { "沙斯拉爾",			"MCShazzrah" },
        { "迦頓男爵",			"MCGeddon" },
        { "焚化者古雷曼格",		"MCGolemagg" },
        { "薩弗隆先驅者",		"MCSulfuron" },
        { "管理者埃克索圖斯",	"MCMajordomo" },
        { "拉格納羅斯",			"MCRagnaros" },
        { "小怪",				"MCTrashMobs" },
        { "首領隨機掉落",		"MCRANDOMBOSSDROPPS" },
    },
    ["納克薩瑪斯"] = {
        { "縫補者	",		"NAXPatchwerk" },
        { "葛羅巴斯",		"NAXGrobbulus" },
        { "古魯斯",			"NAXGluth" },
        { "泰迪斯",			"NAXThaddius" },
        { "阿努比瑞克漢",	"NAXAnubRekhan" },
        { "大寡婦費琳娜",	"NAXGrandWidowFaerlina" },
        { "梅克絲娜",		"NAXMaexxna" },
        { "講師拉祖維斯",	"NAXInstructorRazuvious" },
        { "收割者高希",		"NAXGothikderHarvester" },
        { "四死靈騎士",		"NAXTheFourHorsemen" },
        { "瘟疫者諾斯",		"NAXNothderPlaguebringer" },
        { "骯髒者海根",		"NAXHeiganderUnclean" },
        { "洛斯伯",			"NAXLoatheb" },
        { "薩菲隆",			"NAXSapphiron" },
        { "科爾蘇加德",		"NAXKelThuzard" },
        { "小怪",			"NAXTrash" },
    },
    ["奧妮克希亞的巢穴"] = {
        { "奧妮克希亞",	"Onyxia" },
    },
    ["怒焰裂谷"] = {
        { "饑餓者塔拉加曼",	"RFCTaragaman" },
        { "祈求者耶戈什",	"RFCJergosh" },
    },
    ["剃刀高地"] = {
        { "圖特卡什",			"RFDTutenkash" },
        { "火眼莫德雷斯",		"RFDMordreshFireEye" },
        { "暴食者",				"RFDGlutton" },
        { "拉戈斯諾特",			"RFDRagglesnout" },
        { "寒冰之王亞門納爾",	"RFDAmnennar" },
        { "小怪",				"RFDTrash" },
    },
    ["剃刀沼澤"] = {
        { "亡語者賈格巴	",		"RFKDeathSpeakerJargba" },
        { "主宰拉姆塔斯",		"RFKOverlordRamtusk" },
        { "暴怒的阿迦賽羅斯",	"RFKAgathelos" },
        { "盲眼獵手",			"RFKBlindHunter" },
        { "卡爾加·刺肋",		"RFKCharlgaRazorflank" },
        { "喚地者哈穆加",		"RFKEarthcallerHalmgar" },
        { "小怪",				"RFKTrash" },
    },
    ["安其拉廢墟"] = {
        { "庫林納克斯",		"AQ20Kurinnaxx" },
        { "安多洛夫中將",	"AQ20Andorov" },
        { "拉賈克斯的上尉",	"AQ20CAPTIAN" },
        { "拉賈克斯將軍",	"AQ20Rajaxx" },
        { "莫阿姆",			"AQ20Moam" },
        { "吞咽者布魯",		"AQ20Buru" },
        { "狩獵者阿亞米斯",	"AQ20Ayamiss" },
        { "無疤者奧斯里安",	"AQ20Ossirian" },
        { "職業書籍",		"AQ20ClassBooks" },
        { "附魔公式",		"AQEnchants" },
    },
    ["血色修道院"] = {
        { "馴犬者洛克希",				"SMHoundmasterLoksey" },
        { "祕法師杜安",					"SMDoan" },
        { "赫洛德",						"SMHerod" },
        { "大檢察官法爾班克斯",			"SMFairbanks" },
        { "血色十字軍指揮官莫格萊尼",	"SMMograine" },
        { "大檢察官懷特邁恩",			"SMWhitemane" },
        { "鐵脊死靈",					"SMIronspine" },
        { "永醒的艾希爾",				"SMAzshir" },
        { "死靈勇士",					"SMFallenChampion" },
        { "血法師薩爾諾斯",				"SMBloodmageThalnos" },
        { "小怪",						"SMTrash" },
        { "套裝︰血色十字軍鏈甲",		"SMScarletSET" },
    },
    ["通靈學院"] = {
        { "基爾圖諾斯的衛士",  		"SCHOLOBloodSteward" },
        { "傳令官基爾圖諾斯",		"SCHOLOKirtonostheHerald" },
        { "詹迪斯·巴羅夫",			"SCHOLOJandiceBarov" },
        { "血骨傀儡	",				"SCHOLORattlegore" },
        { "死亡騎士達克雷爾",		"SCHOLODeathKnight" },
        { "馬杜克·布萊克波爾",		"SCHOLOMarduk" },
        { "維克圖斯",				"SCHOLOVectus" },
        { "萊斯·霜語",				"SCHOLORasFrostwhisper" },
        { "科爾莫克",				"SCHOLOKormok" },
        { "講師瑪麗希亞",			"SCHOLOInstructorMalicia" },
        { "瑟爾林·卡斯迪諾夫教授",	"SCHOLODoctorTheolenKrastinov" },
        { "博學者普克爾特",			"SCHOLOLorekeeperPolkelt" },
        { "拉文尼亞",				"SCHOLOTheRavenian" },
        { "阿萊克斯·巴羅夫",		"SCHOLOLordAlexeiBarov" },
        { "伊露希亞·巴羅夫",		"SCHOLOLadyIlluciaBarov" },
        { "黑暗院長加丁",			"SCHOLODarkmasterGandling" },
        { "小怪",					"SCHOLOTrash" },
    },
    ["影牙城堡"] = {
        { "屠夫拉佐克勞",		"BSFRazorclawtheButcher" },
        { "席瓦萊恩男爵",		"BSFSilverlaine" },
        { "指揮官斯普林瓦爾",	"BSFSpringvale" },
        { "盲眼守衛奧杜",		"BSFOdotheBlindwatcher" },
        { "吞噬者芬魯斯",		"BSFFenrustheDevourer" },
        { "狼王南杜斯",			"BSFWolfMasterNandos" },
        { "大法師阿魯高",		"BSFArchmageArugal" },
        { "小怪",				"BSFTrash" },
    },
    ["監獄"] = {
        { "卡姆·深怒",			"SWStKamDeepfury" },
        { "布魯戈·艾爾克納寇",	"SWStBruegalIronknuckle" },
    },
    ["斯坦索姆"] = {
        { "斯庫爾",					"STRATSkull" },
        { "斯坦索姆信差",			"STRATStratholmeCourier" },
        { "弗拉斯·希亞比",			"STRATFrasSiabi" },
        { "弗雷斯特恩",				"STRATHearthsingerForresten" },
        { "不可寬恕者",				"STRATTheUnforgiven" },
        { "悲慘的提米",				"STRATTimmytheCruel" },
        { "炮手威利",				"STRATCannonMasterWilley" },
        { "檔案管理員加爾福特",		"STRATArchivistGalford" },
        { "巴納札爾",				"STRATBalnazzar" },
        { "索索斯/賈林",			"STRATSothosJarien" },
        { "石脊",					"STRATStonespine" },
        { "安娜絲塔麗男爵夫人",		"STRATBaronessAnastari" },
        { "奈魯布恩坎",				"STRATNerubenkan" },
        { "蒼白的瑪勒基",			"STRATMalekithePallid" },
        { "巴瑟拉斯鎮長",			"STRATMagistrateBarthilas" },
        { "吞嚥者拉姆斯登",			"STRATRamsteintheGorger" },
        { "瑞文戴爾男爵",			"STRATBaronRivendare" },
        { "小怪",					"STRATTrash" },
    },
    ["沉沒的神廟"] = {
        { "食人妖小首領",		"STTrollMinibosses" },
        { "阿塔拉利恩",			"STAtalalarion" },
        { "德姆塞卡爾",			"STDreamscythe" },
        { "德拉維沃爾",			"STWeaver"},
        { "哈卡的化身",			"STAvatarofHakkar" },
        { "預言者迦瑪蘭",		"STJammalan" },
        { "可悲的奧戈姆",		"STOgom" },
        { "摩弗拉斯",			"STMorphaz" },
        { "哈札斯",				"STHazzas" },
        { "伊蘭尼庫斯的陰影",	"STEranikus" },
        { "小怪",				"STTrash" },
    },
    ["安其拉神廟"] = {
        { "預言者斯克拉姆",				"AQ40Skeram" },
        { "維姆/克里勳爵/亞爾基公主",	"AQ40Vem" },
        { "沙爾圖拉",					"AQ40Sartura" },
        { "頑強的范克里斯",				"AQ40Fankriss" },
        { "維希度斯",					"AQ40Viscidus" },
        { "哈霍蘭公主",					"AQ40Huhuran" },
        { "雙子帝王",					"AQ40Emperors" },
        { "奧羅",						"AQ40Ouro" },
        { "克蘇恩",						"AQ40CThun" },
        { "小怪",						"AQ40Trash" },
        { "附魔公式",					"AQEnchants" },
        { "安其拉開門事件",				"AQOpening" },
    },
    ["奧達曼"] = {
        { "魯維羅什",			"UldRevelosh" },
        { "艾隆納亞",			"UldIronaya" },
        { "古代的石頭看守者",	"UldAncientStoneKeeper" },
        { "加加恩·火錘",		"UldGalgannFirehammer" },
        { "格瑞姆洛克",			"UldGrimlok" },
        { "阿札達斯",			"UldArchaedas" },
        { "小怪",				"UldTrash" },
    },
    ["哀嚎洞穴"] = {
        { "考布萊恩",			"WCLordCobrahn" },
        { "安娜科德拉",			"WCLadyAnacondra" },
        { "克雷什",				"WCKresh" },
        { "皮薩斯",				"WCLordPythas" },
        { "斯卡姆",				"WCSkum" },
        { "瑟芬迪斯",			"WCLordSerpentis" },
        { "永生者沃爾丹",		"WCVerdan" },
        { "吞噬者穆坦努斯",		"WCMutanus" },
        { "變異精靈龍",			"WCDeviateFaerieDragon" },
        { "套裝: 毒蛇的擁抱",	"WCViperSET" },
    },
    ["祖爾法拉克"] = {
        { "安圖蘇爾",		"ZFAntusul" },
        { "巫醫祖穆拉恩",	"ZFWitchDoctorZumrah" },
        { "暗影祭司塞瑟斯",	"ZFSezzziz" },
        { "加茲瑞拉",		"ZFGahzrilla" },
        { "灰塵怨靈",		"ZFDustwraith" },
        { "烏克茲·沙頂",	"ZFChiefUkorzSandscalp" },
        { "澤雷利斯",		"ZFZerillis" },
        { "小怪",			"ZFTrash" },
    },
    ["祖爾格拉布"] = {
        { "高階祭司耶克里克",	"ZGJeklik" },
        { "高階祭司溫諾希斯",	"ZGVenoxis" },
        { "哈卡萊安魂者",		"ZGMarli" },
        { "血領主曼多基爾",		"ZGMandokir" },
        { "格里雷克‧鋼鐵之血",	"ZGGrilek" },
        { "哈札拉爾‧織夢者",	"ZGHazzarah" },
        { "雷納塔基‧千刃之王",	"ZGRenataki" },
        { "烏蘇雷‧雷巫",		"ZGWushoolay" },
        { "加茲蘭卡",			"ZGGahzranka" },
        { "古拉巴什食腐者",		"ZGThekal" },
        { "哈卡萊先知",			"ZGArlokk" },
        { "妖術師金度",			"ZGJindo" },
        { "哈卡",				"ZGHakkar" },
        { "首領共同掉落",		"ZGShared" },
        { "小怪",				"ZGTrash" },
        { "附魔公式",	"		ZGEnchants" },
    },
    ["PvP套裝 (等級 60)"] = {
        { "德魯伊",	"PVPDruid" },
        { "獵人", 	"PVPHunter" },
        { "法師", 	"PVPMage" },
        { "聖騎士",	"PVPPaladin" },
        { "牧師", 	"PVPPriest" },
        { "盜賊", 	"PVPRogue" },
        { "薩滿", 	"PVPShaman" },
        { "術士", 	"PVPWarlock" },
        { "戰士", 	"PVPWarrior" },

        { "武器1",	"PVPWeapons1" },
        { "武器2",	"PVPWeapons2" },
    },
    ["RAQ 套裝"] = {
        { "德魯伊",	"AQ20Druid" },
        { "獵人", 	"AQ20Hunter" },
        { "法師", 	"AQ20Mage" },
        { "聖騎士",	"AQ20Paladin" },
        { "牧師", 	"AQ20Priest" },
        { "盜賊", 	"AQ20Rogue" },
        { "薩滿", 	"AQ20Shaman" },
        { "術士",  	"AQ20Warlock" },
        { "戰士",  	"AQ20Warrior" },
    },
    ["TAQ 套裝"] = {
        { "德魯伊",	"AQ40Druid" },
        { "獵人", 	"AQ40Hunter" },
        { "法師", 	"AQ40Mage" },
        { "聖騎士",	"AQ40Paladin" },
        { "牧師", 	"AQ40Priest" },
        { "盜賊", 	"AQ40Rogue" },
        { "薩滿", 	"AQ40Shaman" },
        { "術士",  	"AQ40Warlock" },
        { "戰士",  	"AQ40Warrior" },
    },
    ["ZG套裝"] = {
        { "德魯伊",	"ZGDruid" },
        { "獵人", 	"ZGHunter" },
        { "法師", 	"ZGMage" },
        { "聖騎士",	"ZGPaladin" },
        { "牧師", 	"ZGPriest" },
        { "盜賊", 	"ZGRogue" },
        { "薩滿", 	"ZGShaman" },
        { "術士",  	"ZGWarlock" },
        { "戰士",  	"ZGWarrior" },
    },
    ["T0/T0.5套裝"] = {
        { "德魯伊",	"T0Druid" },
        { "獵人", 	"T0Hunter" },
        { "法師", 	"T0Mage" },
        { "聖騎士",	"T0Paladin" },
        { "牧師", 	"T0Priest" },
        { "盜賊", 	"T0Rogue" },
        { "薩滿", 	"T0Shaman" },
        { "術士",  	"T0Warlock" },
        { "戰士",  	"T0Warrior" },
    },
    ["T1套裝"] = {
        { "德魯伊",	"T1Druid" },
        { "獵人", 	"T1Hunter" },
        { "法師", 	"T1Mage" },
        { "聖騎士",	"T1Paladin" },
        { "牧師", 	"T1Priest" },
        { "盜賊", 	"T1Rogue" },
        { "薩滿", 	"T1Shaman" },
        { "術士", 	"T1Warlock" },
        { "戰士",  	"T1Warrior" },
    },
    ["T2套裝"] = {
        { "德魯伊",	"T2Druid" },
        { "獵人", 	"T2Hunter" },
        { "法師", 	"T2Mage" },
        { "聖騎士",	"T2Paladin" },
        { "牧師", 	"T2Priest" },
        { "盜賊", 	"T2Rogue" },
        { "薩滿", 	"T2Shaman" },
        { "術士",  	"T2Warlock" },
        { "戰士",  	"T2Warrior" },
    },
    ["T3套裝"] = {
        { "德魯伊",	"T3Druid" },
        { "獵人", 	"T3Hunter" },
        { "法師", 	"T3Mage" },
        { "聖騎士",	"T3Paladin" },
        { "牧師", 	"T3Priest" },
        { "盜賊", 	"T3Rogue" },
        { "薩滿", 	"T3Shaman" },
        { "術士",  	"T3Warlock" },
        { "戰士",  	"T3Warrior" },
    },
    ["銀色黎明"] = {
        { "可兌換的獎勵",	"Argent1" },
        { "友好/尊敬",		"Argent2" },
        { "崇敬/崇拜",		"Argent3" },
    },
    ["塞納里奧議會"] = {
        { "友好", 	"Cenarion1" },
        { "尊敬", 	"Cenarion2" },
        { "崇敬", 	"Cenarion3" },
        { "崇拜", 	"Cenarion4" },
    },
    ["瑟銀兄弟會"] = {
        { "友好",	"Thorium1" },
        { "尊敬",	"Thorium2" },
        { "崇敬",	"Thorium3" },
        { "崇拜",	"Thorium4" },
    },
    ["贊達拉部族"] = {
        { "友好", 	"Zandalar1" },
        { "尊敬",	"Zandalar2" },
        { "崇敬",	"Zandalar3" },
        { "崇拜",	"Zandalar4" },
    },
    ["奧特蘭克山谷"] = {
        { "友好",	"AVFriendly" },
        { "尊敬",	"AVHonored" },
        { "崇敬",	"AVRevered" },
        { "崇拜",	"AVExalted" },
    },
    ["阿拉希盆地"] = {
        { "友好 (等級60)",	"ABFriendly" },
        { "尊敬 (等級60)",	"ABHonored" },
        { "崇敬 (等級60)",	"ABRevered" },
        { "崇拜 (等級60)",	"ABExalted" },
    },
    ["戰歌峽谷"] = {
        { "友好 (等級60)",	"WSGFriendly" },
        { "尊敬 (等級60)",	"WSGHonored" },
        { "崇敬 (等級60)",	"WSGRevered" },
        { "崇拜 (等級60)",	"WSGExalted" },
    },
};
        
end
