if (GetLocale() == "deDE") then

AtlasLoot_LootTypes = { "Instanzen", "Schlachtzugbosse", "Sets", "Ruf Belohnungen", "PvP" };

AtlasLoot_Zones = {
    {
        { "Blackfathom-Tiefen", "" },
        { "Blackrocktiefen", "" },
        { "Blackrockspitze (unten)", "" },
        { "Blackrockspitze (oben)", "" },
        { "Pechschwingenhort", "" },
        { "Die Todesminen", "" },
        { "D\195\188sterbruch (Ost)", "" },
        { "D\195\188sterbruch (Nord)", "" },
        { "D\195\188sterbruch (West)", "" },
        { "Gnomeregan", "" },
        { "Maraudon", "" },
        { "Geschmolzener Kern", "" },
        { "Naxxramas", "" },
        { "Onyxias Hort", "" },
        { "Ragefireabgrund", "" },
        { "Die H\195\188gel von Razorfen", "" },
        { "Der Kral von Razorfen", "" },
        { "Ruinen von Ahn'Qiraj", "" },
        { "Das scharlachrote Kloster", "" },
        { "Scholomance", "" },
        { "Burg Shadowfang", "" },
        { "Das Verlies", "" },
        { "Stratholme", "" },
        { "Der versunkene Tempel", "" },
        { "Tempel von Ahn'Qiraj", "" },
        { "Uldaman", "" },
        { "Die H\195\182hlen des Wehklagens", "" },
        { "Zul'Farrak", "" },
        { "Zul'Gurub", "" },
    },
    {
        { "Azuregos", "AAzuregos" },
        { "Emeriss", "DEmeriss" },
        { "Kazzak", "KKazzak" },
        { "Lethon", "DLethon"},
        { "Taerar", "DTaerar" },
        { "Ysondre", "DYsondre" },
    },
    {
        { "Legend\195\164re Items", "Legendaries" },
        { "PvP Sets (Level 60)", "" },
        { "Ruinen von Ahn'Qiraj Set", "" },
        { "Ahn'Qiraj Set", "" },
        { "Tier 0/0.5", "" },
        { "Tier 1", "" },
        { "Tier 2", "" },
        { "Tier 3", "" },
        { "Zul'Gurub Sets", "" },
    },
    {
        { "Die Argentumd\195\164mmerung", "" },
        { "Nozdormus Brut", "AQBroodRings" },
        { "Der Zirkel des Cenarius", "" },
        { "Dunkelmond-Jahrmarkt", "Darkmoon" },
        { "Die Thoriumbruderschaft", "" },
        { "Die Holzschlundfeste", "Timbermaw" },
        { "Der Stamm der Zandalar", "" },
    },
    {
        { "Das Alteractal", "" },
        { "Das Arathibecken", "" },
        { "PvP Sets (Level 60)", "" },
        { "Die Warsongschlucht", "" },
    },
};

AtlasLoot_Bosses = {
    ["Blackfathom-Tiefen"] = {
        { "Ghamoo-ra", "BFDGhamoora" },
        { "Lady Sarevess", "BFDLadySarevess" },
        { "Gelihast", "BFDGelihast" },
        { "Baron Aquanis", "BFDBaronAquanis" },
        { "Twilight-Lord Kelris", "BFDTwilightLordKelris" },
        { "Old Serra'kis", "BFDOldSerrakis" },
        { "Aku'mai", "BFDAkumai" },
        { "Trash Mobs", "BFDTrash" },
    },
    ["Blackrocktiefen"] = {
        { "Lord Roccor", "BRDLordRoccor" },
        { "Verh\195\182rmeisterin Gerstahn", "BRDHighInterrogatorGerstahn" },
        { "Ring des Gesetzes, Theldren", "BRDArena" },
        { "Houndmaster Grebmar", "BRDHoundmaster" },                --hä? Welcher boss is das?
        { "Pyromant Loregrain", "BRDPyromantLoregrain" },
        { "Das schwarze Gew\195\182lbe", "BRDWarderStilgiss" },
        { "Fineous Darkvire", "BRDFineousDarkvire" },
        { "Lord Incendius", "BRDLordIncendius" },
        { "Bael'Gar", "BRDBaelGar" },
        { "General Zornesschmied", "BRDGeneralAngerforge" },
        { "Golemlord Argelmach", "BRDGolemLordArgelmach" },
        { "The Grim Guzzler", "BRDGuzzler" },
        { "Botschafter Flammenschlag", "BRDFlamelash" },
        { "Panzor der Unbesiegbare", "BRDPanzor" },
        { "Grabmal der Boten", "BRDTomb" },
        { "Magmus", "BRDMagmus" },
        { "Imperator Dagran Thaurissan", "BRDImperatorDagranThaurissan" },
        { "Prinzessin Moira Bronzebeard", "BRDPrincess" },
        { "Trash Mobs", "BRDTrash" },
    },
    ["Blackrockspitze (unten)"] = {
        { "Hochlord Omokk", "LBRSOmokk" },
        { "Kampflord der Felsspitzoger", "LBRSSpirestoneLord" },
        { "Schattenj\195\164gerin Vosh'gajin", "LBRSVosh" },
        { "Kriegsmeister Voone", "LBRSVoone" },
        { "Mor Grayhoof", "LBRSGrayhoof" },
        { "Mutter Glimmernetz", "LBRSSmolderweb" },
        { "Kristallfangzahn", "LBRSCrystalFang" },
        { "Urok Schreckensbote", "LBRSDoomhowl" },
        { "Quartiermeister Zigris", "LBRSZigris" },
        { "Gizrul der Geifernde", "LBRSSlavener" },
        { "Halycon", "LBRSHalycon" },
        { "Hochlord Wyrmthalak", "LBRSWyrmthalak" },
        { "Bannok Grimaxe", "LBRSGrimaxe" },
        { "Metzger der Felsspitzoger", "LBRSSpirestoneButcher" },
        { "Trash Mobs", "LBRSTrash" },
    },
    ["Blackrockspitze (oben)"] = {
        { "Feuerwache Glutseher", "UBRSEmberseer" },
        { "Solakar Feuerkrone", "UBRSSolakar" },
        { "Vater Flamme", "UBRSFLAME" },
        { "Jed Runewatcher", "UBRSRunewatcher" },
        { "Goraluk Anvilcrack", "UBRSAnvilcrack" },
        { "Kriegsh\195\164uptling Rend Blackhand", "UBRSRend" },
        { "Gyth", "UBRSGyth" },
        { "Die Bestie", "UBRSBeast" },
        { "Lord Valthalak", "UBRSValthalak" },
        { "General Drakkisath", "UBRSDrakkisath" },
        { "Trash Mobs", "UBRSTrash" },
    },
    ["Pechschwingenhort"] = {
        { "Razorgore der Ungez\195\164hmte", "BWLRazorgore" },
        { "Vaelastrasz der Verdorbene", "BWLVaelastrasz" },
        { "Brutw\195\164chter Dreschbringer", "BWLLashlayer" },
        { "Feuerschwinge", "BWLFiremaw" },
        { "Schattenschwinge", "BWLEbonroc" },
        { "Flammenmaul", "BWLFlamegor" },
        { "Chromaggus", "BWLChromaggus" },
        { "Nefarian", "BWLNefarian" },
        { "Trash Mobs", "BWLTrashMobs" },
    },
    ["Die Todesminen"] = {
        { "Rhahk'Zor", "VCRhahkZor" },
        { "Minenarbeiter Johnson", "VCMinerJohnson" },
        { "Sneed", "VCSneed" },
        { "Gilnid", "VCGilnid" },
        { "Captain Greenskin", "VCCaptainGreenskin" },
        { "Edwin VanCleef", "VCVanCleef" },
        { "Mr. Smite", "VCMrSmite" },
        { "Cookie", "VCCookie" },
        { "Set: Defiasleder (5 Teile)", "VCDefiasSET" },
    },
    ["D\195\188sterbruch (Ost)"] = {
        { "Pusillin", "DMEPusillin" },
        { "Zevrim Dornhuf", "DMEZevrimThornhoof" },
        { "Hydrobrut", "DMEHydro" },
        { "Lethtendris", "DMELethtendris" },
        { "Alzzin der Wildformer", "DMEAlzzin" },
        { "Isalien", "DMEIsalien" },
        { "Trash Mobs", "DMETrash" },
        { "D\195\188sterbruch B\195\188cher", "DMBooks" },
    },
    ["D\195\188sterbruch (Nord)"] = {
        { "Wache Mol'dar", "DMNGuardMoldar" },
        { "Stampfer Kreeg", "DMNStomperKreeg" },
        { "Wache Fengus", "DMNGuardFengus" },
        { "Knot Thimblejack", "DMNThimblejack" },
        { "Wache Slip'kik", "DMNGuardSlipkik" },
        { "Captain Kromcrush", "DMNCaptainKromcrush" },
        { "K\195\182nig Gordok", "DMNKingGordok" },
        { "Tribute Run", "DMNTRIBUTERUN" },
        { "D\195\188sterbruch B\195\188cher", "DMBooks" },
    },
    ["D\195\188sterbruch (West)"] = {
        { "Tendris Wucherborke", "DMWTendrisWarpwood" },
        { "Illyanna Rabeneiche", "DMWIllyannaRavenoak" },
        { "Magister Kalendris", "DMWMagisterKalendris" },
        { "Tsu'Zee", "DMWTsuzee" },
        { "Immol'thar", "DMWImmolthar" },
        { "Lord Hel'nurath", "DMWHelnurath" },
        { "Prinz Tortheldrin", "DMWPrinceTortheldrin" },
        { "Trash Mobs", "DMWTrash" },
        { "D\195\188sterbruch B\195\188cher", "DMBooks" },
    },
    ["Gnomeregan"] = {
        { "Z\195\164hfl\195\188ssiger Niederschlag", "GnViscousFallout" },
        { "Grubbis", "GnGrubbis" },
        { "Electrocutioner 6000", "GnElectrocutioner6000" },
        { "Robogenieur Thermaplugg", "GnMekgineerThermaplugg" },
        { "Botschafter der Dunkeleisenzwerge", "GnDIAmbassador" },
        { "Meute Verpr\195\188geler 9-60", "GnCrowdPummeler960" },
        { "Trash Mobs", "GnTrash" },
    },
    ["Maraudon"] = {
        { "Noxxion", "MaraNoxxion" },
        { "Schlingwurzler", "MaraRazorlash" },
        { "Lord Schlangenzunge", "MaraLordVyletongue" },
        { "Meshlok der Ernter", "MaraMeshlok" },
        { "Celebras der Verbannte", "MaraCelebras" },
        { "Erdrutsch", "MaraLandslide" },
        { "T\195\188ftler Gizlock", "MaraTinkererGizlock" },
        { "Faulschnapper", "MaraRotgrip" },
        { "Prinzessin Theradras", "MaraPrincessTheradras" },
    },
    ["Geschmolzener Kern"] = {
        { "Lucifron", "MCLucifron" },
        { "Magmadar", "MCMagmadar" },
        { "Gehennas", "MCGehennas" },
        { "Garr", "MCGarr" },
        { "Shazzrah", "MCShazzrah" },
        { "Baron Geddon", "MCGeddon" },
        { "Golemagg der Verbrenner", "MCGolemagg" },
        { "Sulfuronherold", "MCSulfuron" },
        { "Majordomo Exekutus", "MCMajordomo" },
        { "Ragnaros", "MCRagnaros" },
        { "Trash Mobs", "MCTrashMobs" },
        { "Zuf\195\164lliger Boss Loot", "MCRANDOMBOSSDROPPS" },
    },
    ["Naxxramas"] = {
        { "Flickwerk", "NAXPatchwerk" },
        { "Grobbulus", "NAXGrobbulus" },
        { "Gluth", "NAXGluth" },
        { "Thaddius", "NAXThaddius" },
        { "Anub'Rekhan", "NAXAnubRekhan" },
        { "Gro\195\159witwe Faerlina", "NAXGrandWidowFaerlina" },
        { "Maexxna", "NAXMaexxna" },
        { "Instrukteur Razuvious", "NAXInstructorRazuvious" },
        { "Gothik der Seelenj\195\164ger", "NAXGothikderHarvester" },
        { "Die vier Ritter", "NAXTheFourHorsemen" },
        { "Noth der Seuchenf\195\188rst", "NAXNothderPlaguebringer" },
        { "Heigan der Unreine", "NAXHeiganderUnclean" },
        { "Loatheb", "NAXLoatheb" },
        { "Sapphiron", "NAXSapphiron" },
        { "Kel'Thuzad", "NAXKelThuzard" },
        { "Trash Mobs", "NAXTrash" },
    },
    ["Onyxias Hort"] = {
        { "Onyxia", "Onyxia" },
    },
    ["Ragefireabgrund"] = {
        { "Taragaman der Hungerleider", "RFCTaragaman" },
        { "Jergosh der Herbeirufer", "RFCJergosh" },
    },
    ["Die H\195\188gel von Razorfen"] = {
        { "Tuten'kash", "RFDTutenkash" },
        { "Mordresh Feuerauge", "RFDMordreshFireEye" },
        { "Nimmersatt", "RFDGlutton" },
        { "Struppm\195\164hne", "RFDRagglesnout" },
        { "Amnennar der K\195\164ltebringer", "RFDAmnennar" },
        { "Trash Mobs", "RFDTrash" },
    },
    ["Der Kral von Razorfen"] = {
        { "Todessprecher Jargba", "RFKDeathSpeakerJargba" },
        { "Oberanf\195\188hrer Rammhauer", "RFKOverlordRamtusk" },
        { "Agathelos der Tobende", "RFKAgathelos" },
        { "Blinder J\195\164ger", "RFKBlindHunter" },
        { "Charlga Razorflank", "RFKCharlgaRazorflank" },
        { "Erdenrufer Halmgar", "RFKEarthcallerHalmgar" },
        { "Trash Mobs", "RFKTrash" },
    },
    ["Ruinen von Ahn'Qiraj"] = {
        { "Kurinnaxx", "AQ20Kurinnaxx" },
        { "Generallieutenant Andorov", "AQ20Andorov" },
        { "Rajaxx's Captains", "AQ20CAPTIAN" },
        { "General Rajaxx", "AQ20Rajaxx" },
        { "Moam", "AQ20Moam" },
        { "Buru der Verschlinger", "AQ20Buru" },
        { "Ayamiss der J\195\164ger", "AQ20Ayamiss" },
        { "Ossirian der Narbenlose", "AQ20Ossirian" },
        { "Klassenb\195\188cher", "AQ20ClassBooks" },
        { "AQ Verzauberungen", "AQEnchants" },
    },
    ["Das scharlachrote Kloster"] = {
        { "Hundemeister Loksey", "SMHoundmasterLoksey" },
        { "Arkanist Doan", "SMDoan" },
        { "Herod", "SMHerod" },
        { "Hochinquisitor Fairbanks", "SMFairbanks" },
        { "Scharlachroter Kommandant Mograine", "SMMograine" },
        { "Hochinquisitor Whitemane", "SMWhitemane" },
        { "Eisenstachel", "SMIronspine" },
        { "Azshir der Schlaflose", "SMAzshir" },
        { "Gefallener Held", "SMFallenChampion" },
        { "Blutmagier Thalnos", "SMBloodmageThalnos" },
        { "Trash Mobs", "SMTrash" },
        { "Set: Kettenr\195\188stung des Scharlachroten Kreuzzugs", "SMScarletSET" },
    },
    ["Scholomance"] = {
        { "Blutschale von Kirtonos",  "SCHOLOBloodSteward" },
        { "Kirtonos der Herold", "SCHOLOKirtonostheHerald" },
        { "Jandice Barov", "SCHOLOJandiceBarov" },
        { "Blutrippe", "SCHOLORattlegore" },
        { "Todesritter Schattensichel", "SCHOLODeathKnight" },
        { "Marduk Blackpool", "SCHOLOMarduk" },
        { "Vectus", "SCHOLOVectus" },
        { "Ras Frostraunen", "SCHOLORasFrostwhisper" },
        { "Kormok", "SCHOLOKormok" },
        { "Instrukteurin Malicia", "SCHOLOInstructorMalicia" },
        { "Doktor Theolen Krastinov", "SCHOLODoctorTheolenKrastinov" },
        { "H\195\188ter des Wissens Polkelt", "SCHOLOLorekeeperPolkelt" },
        { "Der Ravenier", "SCHOLOTheRavenian" },
        { "Lord Alexei Barov", "SCHOLOLordAlexeiBarov" },
        { "Lady Illucia Barov", "SCHOLOLadyIlluciaBarov" },
        { "Dunkelmeister Gandling", "SCHOLODarkmasterGandling" },
        { "Trash Mobs", "SCHOLOTrash" },
    },
    ["Burg Shadowfang"] = {
        { "Klingenklaue der Metzger", "BSFRazorclawtheButcher" },
        { "Baron Silverlaine", "BSFSilverlaine" },
        { "Commander Springvale", "BSFSpringvale" },
        { "Odo der Blindseher", "BSFOdotheBlindwatcher" },
        { "Fenrus der Verschlinger", "BSFFenrustheDevourer" },
        { "Wolfmeister Nandos", "BSFWolfMasterNandos" },
        { "Erzmagier Arugal", "BSFArchmageArugal" },
        { "Trash Mobs", "BSFTrash" },
    },
    ["Das Verlies"] = {
        { "Kam Deepfury", "SWStKamDeepfury" },
        { "Bruegal Eisenfaust", "SWStBruegalIronknuckle" },
    },
    ["Stratholme"] = {
        { "Skul", "STRATSkull" },
        { "Kurier von Stratholme", "STRATStratholmeCourier" },
        { "Fras Siabi", "STRATFrasSiabi" },
        { "Herdsinger Forresten", "STRATHearthsingerForresten" },
        { "Der Unverziehene", "STRATTheUnforgiven" },
        { "Timmy der Grausame", "STRATTimmytheCruel" },
        { "Kanonenmeister Willey", "STRATCannonMasterWilley" },
        { "Archivar Galford", "STRATArchivistGalford" },
        { "Balnazzar", "STRATBalnazzar" },
        { "Sothos und Jarien", "STRATSothosJarien" },
        { "Steinbuckel", "STRATStonespine" },
        { "Baroness Anastari", "STRATBaronessAnastari" },
        { "Nerub'enkan", "STRATNerubenkan" },
        { "Maleki der Leichenblasse", "STRATMalekithePallid" },
        { "Magistrate Barthilas", "STRATMagistrateBarthilas" },
        { "Ramstein der Verschlinger", "STRATRamsteintheGorger" },
        { "Baron Rivendare", "STRATBaronRivendare" },
        { "Trash Mobs", "STRATTrash" },
    },
    ["Der versunkene Tempel"] = {
        { "Troll Minibosse", "STTrollMinibosses" },
        { "Atal'alarion", "STAtalalarion" },
        { "Traumsense", "STDreamscythe" },
        { "Wirker", "STWeaver"},
        { "Avatar von Hakkar", "STAvatarofHakkar" },
        { "Jammal'an der Prophet", "STJammalan" },
        { "Ogom der Elende", "STOgom" },
        { "Morphaz", "STMorphaz" },
        { "Hazzas", "STHazzas" },
        { "Eranikus' Schemen", "STEranikus" },
        { "Trash Mobs", "STTrash" },
    },
    ["Tempel von Ahn'Qiraj"] = {
        { "Der Prophet Skeram", "AQ40Skeram" },
        { "Die 3 K\195\164fer", "AQ40Vem" },
        { "Schlachtwache Satura", "AQ40Sartura" },
        { "Fankriss der Unnachgiebige", "AQ40Fankriss" },
        { "Viscidus", "AQ40Viscidus" },
        { "Prinzessin Huhuran", "AQ40Huhuran" },
        { "Die Zwillingsimperatoren", "AQ40Emperors" },
        { "Ouro", "AQ40Ouro" },
        { "C'Thun", "AQ40CThun" },
        { "Trash Mobs", "AQ40Trash" },
        { "AQ Verzauberungen", "AQEnchants" },
        { "AQ Tor \195\150ffnung", "AQOpening" },
    },
    ["Uldaman"] = {
        { "Revelosh", "UldRevelosh" },
        { "Ironaya", "UldIronaya" },
        { "Uralter Steinbewahrer", "UldAncientStoneKeeper" },
        { "Galgann Firehammer", "UldGalgannFirehammer" },
        { "Grimlok", "UldGrimlok" },
        { "Archaedas", "UldArchaedas" },
        { "Trash Mobs", "UldTrash" },
    },
    ["Die H\195\182hlen des Wehklagens"] = {
        { "Lord Cobrahn", "WCLordCobrahn" },
        { "Lady Anacondra", "WCLadyAnacondra" },
        { "Kresh", "WCKresh" },
        { "Lord Pythas", "WCLordPythas" },
        { "Skum", "WCSkum" },
        { "Lord Serpentis", "WCLordSerpentis" },
        { "Verdan der Ewiglebende", "WCVerdan" },
        { "Mutanus der Verschlinger", "WCMutanus" },
        { "Deviatfeendrache", "WCDeviateFaerieDragon" },
        { "Set: Umarmung der Viper (5 Teile)", "WCViperSET" },
    },
    ["Zul'Farrak"] = {
        { "Antu'sul", "ZFAntusul" },
        { "Hexendoktor Zum'rah", "ZFWitchDoctorZumrah" },
        { "Schattenpriester Sezz'ziz", "ZFSezzziz" },
        { "Gahz'rilla", "ZFGahzrilla" },
        { "Dustwraith", "ZFDustwraith" },
        { "H\195\164uptling Ukorz Sandscalp", "ZFChiefUkorzSandscalp" },
        { "Zerillis", "ZFZerillis" },
        { "Trash Mobs", "ZFTrash" },
    },
    ["Zul'Gurub"] = {
        { "Hohepriesterin Jeklik", "ZGJeklik" },
        { "Hohepriester Venoxis", "ZGVenoxis" },
        { "Hohepriesterin Mar'li", "ZGMarli" },
        { "Blutf\195\188rst Mandokir", "ZGMandokir" },
        { "Gri'lek", "ZGGrilek" },
        { "Hazzarah", "ZGHazzarah" },
        { "Renataki", "ZGRenataki" },
        { "Wushoolay", "ZGWushoolay" },
        { "Gahz'ranka", "ZGGahzranka" },
        { "Hohepriester Thekal", "ZGThekal" },
        { "Hohepriesterin Arlokk", "ZGArlokk" },
        { "Jin'do der Hexer", "ZGJindo" },
        { "Hakkar", "ZGHakkar" },
        { "Geteilter Boss Loot", "ZGShared" },
        { "Trash Mobs", "ZGTrash" },
        { "ZG Verzauberungen", "ZGEnchants" },
    },
    ["PvP Sets (Level 60)"] = {
        { "Druide", "PVPDruid" },
        { "J\195\164ger", "PVPHunter" },
        { "Magier", "PVPMage" },
        { "Paladin", "PVPPaladin" },
        { "Priester", "PVPPriest" },
        { "Schurke", "PVPRogue" },
        { "Schamane", "PVPShaman" },
        { "Hexenmeister", "PVPWarlock" },
        { "Krieger", "PVPWarrior" },
        { "Waffen 1", "PVPWeapons1" },
        { "Waffen 2", "PVPWeapons2" },
    },
    ["Ruinen von Ahn'Qiraj Set"] = {
        { "Druide", "AQ20Druid" },
        { "J\195\164ger", "AQ20Hunter" },
        { "Magier", "AQ20Mage" },
        { "Paladin", "AQ20Paladin" },
        { "Priester", "AQ20Priest" },
        { "Schurke", "AQ20Rogue" },
        { "Schamane", "AQ20Shaman" },
        { "Hexenmeister", "AQ20Warlock" },
        { "Krieger", "AQ20Warrior" },
    },
    ["Ahn'Qiraj Set"] = {
        { "Druide", "AQ40Druid" },
        { "J\195\164ger", "AQ40Hunter" },
        { "Magier", "AQ40Mage" },
        { "Paladin", "AQ40Paladin" },
        { "Priester", "AQ40Priest" },
        { "Schurke", "AQ40Rogue" },
        { "Schamane", "AQ40Shaman" },
        { "Hexenmeister", "AQ40Warlock" },
        { "Krieger", "AQ40Warrior" },
    },
    ["Zul'Gurub Sets"] = {
        { "Druide", "ZGDruid" },
        { "J\195\164ger", "ZGHunter" },
        { "Magier", "ZGMage" },
        { "Paladin", "ZGPaladin" },
        { "Priester", "ZGPriest" },
        { "Schurke", "ZGRogue" },
        { "Schamane", "ZGShaman" },
        { "Hexenmeister", "ZGWarlock" },
        { "Krieger", "ZGWarrior" },
    },
    ["Tier 0/0.5"] = {
        { "Druide", "T0Druid" },
        { "J\195\164ger", "T0Hunter" },
        { "Magier", "T0Mage" },
        { "Paladin", "T0Paladin" },
        { "Priester", "T0Priest" },
        { "Schurke", "T0Rogue" },
        { "Schamane", "T0Shaman" },
        { "Hexenmeister", "T0Warlock" },
        { "Krieger", "T0Warrior" },
    },
    ["Tier 1"] = {
        { "Druide", "T1Druid" },
        { "J\195\164ger", "T1Hunter" },
        { "Magier", "T1Mage" },
        { "Paladin", "T1Paladin" },
        { "Priester", "T1Priest" },
        { "Schurke", "T1Rogue" },
        { "Schamane", "T1Shaman" },
        { "Hexenmeister", "T1Warlock" },
        { "Krieger", "T1Warrior" },
    },
    ["Tier 2"] = {
        { "Druide", "T2Druid" },
        { "J\195\164ger", "T2Hunter" },
        { "Magier", "T2Mage" },
        { "Paladin", "T2Paladin" },
        { "Priester", "T2Priest" },
        { "Schurke", "T2Rogue" },
        { "Schamane", "T2Shaman" },
        { "Hexenmeister", "T2Warlock" },
        { "Krieger", "T2Warrior" },
    },
    ["Tier 3"] = {
        { "Druide", "T3Druid" },
        { "J\195\164ger", "T3Hunter" },
        { "Magier", "T3Mage" },
        { "Paladin", "T3Paladin" },
        { "Priester", "T3Priest" },
        { "Schurke", "T3Rogue" },
        { "Schamane", "T3Shaman" },
        { "Hexenmeister", "T3Warlock" },
        { "Krieger", "T3Warrior" },
    },
    ["Die Argentumd\195\164mmerung"] = {
        { "Gutscheine", "Argent1" },
        { "Freundlich/Wohlwollend", "Argent2" },
        { "Respektvoll/Ehrf\195\188rchtig", "Argent3" },
    },
    ["Der Zirkel des Cenarius"] = {
        { ATLASLOOT_FRIENDLY, "Cenarion1" },
        { ATLASLOOT_HONORED, "Cenarion2" },
        { ATLASLOOT_REVERED, "Cenarion3" },
        { ATLASLOOT_EXALTED, "Cenarion4" },
    },
    ["Die Thoriumbruderschaft"] = {
        { ATLASLOOT_FRIENDLY, "Thorium1" },
        { ATLASLOOT_HONORED, "Thorium2" },
        { ATLASLOOT_REVERED, "Thorium3" },
        { ATLASLOOT_EXALTED, "Thorium4" },
    },
    ["Der Stamm der Zandalar"] = {
        { ATLASLOOT_FRIENDLY, "Zandalar1" },
        { ATLASLOOT_HONORED, "Zandalar2" },
        { ATLASLOOT_REVERED, "Zandalar3" },
        { ATLASLOOT_EXALTED, "Zandalar4" },
    },
    ["Das Alteractal"] = {
        { ATLASLOOT_FRIENDLY, "AVFriendly" },
        { ATLASLOOT_HONORED, "AVHonored" },
        { ATLASLOOT_REVERED, "AVRevered" },
        { ATLASLOOT_EXALTED, "AVExalted" },
    },
    ["Das Arathibecken"] = {
        { ATLASLOOT_FRIENDLY, "ABFriendly" },
        { ATLASLOOT_HONORED, "ABHonored" },
        { ATLASLOOT_REVERED, "ABRevered" },
        { ATLASLOOT_EXALTED, "ABExalted" },
    },
    ["Die Warsongschlucht"] = {
        { ATLASLOOT_FRIENDLY, "WSGFriendly" },
        { ATLASLOOT_HONORED, "WSGHonored" },
        { ATLASLOOT_REVERED, "WSGRevered" },
        { ATLASLOOT_EXALTED, "WSGExalted" },
    },
};

end
