AtlasLoot_LootTypes = { "Instances", "World Bosses", "Item Sets", "Faction Rewards", "PvP" };

AtlasLoot_Zones = {
    { 
        { "Blackfathom Deeps", "" },
        { "Blackrock Depths", "" },
        { "Blackrock Spire (Lower)", "" },
        { "Blackrock Spire (Upper)", "" },
        { "Blackwing Lair", "" },
        { "The Deadmines", "" },
        { "Dire Maul (East)", "" },
        { "Dire Maul (North)", "" },
        { "Dire Maul (West)", "" },
        { "Gnomeregan", "" },
        { "Maraudon", "" },
        { "Molten Core", "" },
        { "Naxxramas", "" },
        { "Onyxia's Lair", "" },
        { "Ragefire Chasm", "" },
        { "Razorfen Downs", "" },
        { "Razorfen Kraul", "" },
        { "The Ruins of Ahn'Qiraj", "" },
        { "Scarlet Monestery", "" },
        { "Scholomance", "" },
        { "Shadowfang Keep", "" },
        { "The Stockade", "" },
        { "Stratholme", "" },
        { "The Sunken Temple", "" },
        { "The Temple of Ahn'Qiraj", "" },
        { "Uldaman", "" },
        { "Wailing Caverns", "" },
        { "Zul'Farrak", "" },
        { "Zul'Gurub", "" },
    },
    {
        { "Azuregos", "AAzuregos" },
        { "Emeriss", "DEmeriss" },
        { "Kazzak", "KKazzak" },
        { "Lethon", "DLethon"},
        { "Taerar", "DTaerar" },
        { "Ysondre", "DYsondre" },
    },
    {
        { "Legendary Items", "Legendaries" },
        { "PvP Sets (Level 60)", "" },
        { "Ruins of AQ Sets", "" },
        { "Temple of AQ Sets", "" },
        { "Tier 0/0.5", "" },
        { "Tier 1", "" },
        { "Tier 2", "" },
        { "Tier 3", "" },
        { "Zul'Gurub Sets", "" },
    },
    {
        { "The Argent Dawn", "" },
        { "The Brood of Nozdormu", "AQBroodRings" },
        { "The Cenarion Circle", "" },
        { "The Darkmoon Faire", "Darkmoon" },
        { "The Thorium Brotherhood", "" },
        { "The Timbermaw Furbolgs", "Timbermaw" },
        { "The Zandalar Tribe", "" },
    },
    {
        { "Alterac Valley", "" },
        { "Arathi Basin", "" },
        { "PvP Sets (Level 60)", "" },
        { "Warsong Gulch", "" },
    },
};

AtlasLoot_Bosses = {
    ["Blackfathom Deeps"] = {
        { "Ghamoo-ra", "BFDGhamoora" },
        { "Lady Sarevess", "BFDLadySarevess" },
        { "Gelihast", "BFDGelihast" },
        { "Baron Aquanis", "BFDBaronAquanis" },
        { "Twilight Lord Kelris", "BFDTwilightLordKelris" },
        { "Old Serra'kis", "BFDOldSerrakis" },
        { "Aku'mai", "BFDAkumai" },
        { "Trash Mobs", "BFDTrash" },
    },
    ["Blackrock Depths"] = {
        { "Lord Roccor", "BRDLordRoccor" },
        { "High Interrogator Gerstahn", "BRDHighInterrogatorGerstahn" },
        { "Ring of Law, Theldren", "BRDArena" },
        { "Houndmaster Grebmar", "BRDHoundmaster" },
        { "Pyromancer Loregrain", "BRDPyromantLoregrain" },
        { "The Vault", "BRDWarderStilgiss" },
        { "Fineous Darkvire", "BRDFineousDarkvire" },
        { "Lord Incendius", "BRDLordIncendius" },
        { "Bael'Gar", "BRDBaelGar" },
        { "General Angerforge", "BRDGeneralAngerforge" },
        { "Golem Lord Argelmach", "BRDGolemLordArgelmach" },
        { "The Grim Guzzler", "BRDGuzzler" },
        { "Ambassador Flamelash", "BRDFlamelash" },
        { "Panzor the Invincible", "BRDPanzor" },
        { "Summoner's Tomb", "BRDTomb" },
        { "Magmus", "BRDMagmus" },
        { "Emperor Dagran Thaurissan", "BRDImperatorDagranThaurissan" },
        { "Princess Moira Bronzebeard", "BRDPrincess" },
        { "Trash Mobs", "BRDTrash" },
    },
    ["Blackrock Spire (Lower)"] = {
        { "Highlord Omokk", "LBRSOmokk" },
        { "Spirestone Battle Lord", "LBRSSpirestoneLord" },
        { "Shadow Hunter Vosh'gajin", "LBRSVosh" },
        { "War Master Voone", "LBRSVoone" },
        { "Mor Grayhoof", "LBRSGrayhoof" },
        { "Mother Smoulderweb", "LBRSSmolderweb" },
        { "Crystal Fang", "LBRSCrystalFang" },
        { "Urok Doomhowl", "LBRSDoomhowl" },
        { "Quartermaster Zigris", "LBRSZigris" },
        { "Gizrul the Slavener", "LBRSSlavener" },
        { "Halycon", "LBRSHalycon" },
        { "Overlord Wyrmthalak", "LBRSWyrmthalak" },
        { "Bannok Grimaxe", "LBRSGrimaxe" },
        { "Spirestone Butcher", "LBRSSpirestoneButcher" },
        { "Trash Mobs", "LBRSTrash" },
    },
    ["Blackrock Spire (Upper)"] = {
        { "Pyroguard Emberseer", "UBRSEmberseer" },
        { "Solakar Flamewreath", "UBRSSolakar" },
        { "Father Flame", "UBRSFLAME" },
        { "Jed Runewatcher", "UBRSRunewatcher" },
        { "Goraluk Anvilcrack", "UBRSAnvilcrack" },
        { "Warchief Rend Blackhand", "UBRSRend" },
        { "Gyth", "UBRSGyth" },
        { "The Beast", "UBRSBeast" },
        { "Lord Valthalak", "UBRSValthalak" },
        { "General Drakkisath", "UBRSDrakkisath" },
        { "Trash Mobs", "UBRSTrash" },
    },
    ["Blackwing Lair"] = {
        { "Razorgore the Untamed", "BWLRazorgore" },
        { "Vaelastrasz the Corrupt", "BWLVaelastrasz" },
        { "Broodlord Lashlayer", "BWLLashlayer" },
        { "Firemaw", "BWLFiremaw" },
        { "Ebonroc", "BWLEbonroc" },
        { "Flamegor", "BWLFlamegor" },
        { "Chromaggus", "BWLChromaggus" },
        { "Nefarian", "BWLNefarian" },
        { "Trash Mobs", "BWLTrashMobs" },
    },
    ["The Deadmines"] = {
        { "Rhahk'Zor", "VCRhahkZor" },
        { "Miner Johnson", "VCMinerJohnson" },
        { "Sneed", "VCSneed" },
        { "Gilnid", "VCGilnid" },
        { "Captain Greenskin", "VCCaptainGreenskin" },
        { "Edwin VanCleef", "VCVanCleef" },
        { "Mr. Smite", "VCMrSmite" },
        { "Cookie", "VCCookie" },
        { "Item Set: Defias Leather", "VCDefiasSET" },
    },
    ["Dire Maul (East)"] = {
        { "Pusillin", "DMEPusillin" },
        { "Zevrim Thornhoof", "DMEZevrimThornhoof" },
        { "Hydrospawn", "DMEHydro" },
        { "Lethtendris", "DMELethtendris" },
        { "Alzzin the Wildshaper", "DMEAlzzin" },
        { "Isalien", "DMEIsalien" },
        { "Trash Mobs", "DMETrash" },
        { "Dire Maul Books", "DMBooks" },
    },
    ["Dire Maul (North)"] = {
        { "Guard Mol'dar", "DMNGuardMoldar" },
        { "Stomper Kreeg", "DMNStomperKreeg" },
        { "Guard Fengus", "DMNGuardFengus" },
        { "Knot Thimblejack", "DMNThimblejack" },
        { "Guard Slip'kik", "DMNGuardSlipkik" },
        { "Captain Kromcrush", "DMNCaptainKromcrush" },
        { "King Gordok", "DMNKingGordok" },
        { "Tribute Run", "DMNTRIBUTERUN" },
        { "Dire Maul Books", "DMBooks" },
    },
    ["Dire Maul (West)"] = {
        { "Tendris Warpwood", "DMWTendrisWarpwood" },
        { "Illyanna Ravenoak", "DMWIllyannaRavenoak" },
        { "Magister Kalendris", "DMWMagisterKalendris" },
        { "Tsu'Zee", "DMWTsuzee" },
        { "Immol'thar", "DMWImmolthar" },
        { "Lord Hel'nurath", "DMWHelnurath" },
        { "Prince Tortheldrin", "DMWPrinceTortheldrin" },
        { "Trash Mobs", "DMWTrash" },
        { "Dire Maul Books", "DMBooks" },
    },
    ["Gnomeregan"] = {
        { "Viscous Fallout", "GnViscousFallout" },
        { "Grubbis", "GnGrubbis" },
        { "Electrocutioner 6000", "GnElectrocutioner6000" },
        { "Mekgineer Thermaplugg", "GnMekgineerThermaplugg" },
        { "Dark Iron Ambassador", "GnDIAmbassador" },
        { "Crowd Pummeler 9-60", "GnCrowdPummeler960" },
        { "Trash Mobs", "GnTrash" },
    },
    ["Maraudon"] = {
        { "Noxxion", "MaraNoxxion" },
        { "Razorlash", "MaraRazorlash" },
        { "Lord Vyletongue", "MaraLordVyletongue" },
        { "Meshlok the Harvester", "MaraMeshlok" },
        { "Celebras the Cursed", "MaraCelebras" },
        { "Landslide", "MaraLandslide" },
        { "Tinkerer Gizlock", "MaraTinkererGizlock" },
        { "Rotgrip", "MaraRotgrip" },
        { "Princess Theradras", "MaraPrincessTheradras" },
    },
    ["Molten Core"] = {
        { "Lucifron", "MCLucifron" },
        { "Magmadar", "MCMagmadar" },
        { "Gehennas", "MCGehennas" },
        { "Garr", "MCGarr" },
        { "Shazzrah", "MCShazzrah" },
        { "Baron Geddon", "MCGeddon" },
        { "Golemagg the Incinerator", "MCGolemagg" },
        { "Sulfuron Harbinger", "MCSulfuron" },
        { "Majordomo Executus", "MCMajordomo" },
        { "Ragnaros", "MCRagnaros" },
        { "Trash Mobs", "MCTrashMobs" },
        { "Random Boss Drops", "MCRANDOMBOSSDROPPS" },
    },
    ["Naxxramas"] = {
        { "Patchwerk", "NAXPatchwerk" },
        { "Grobbulus", "NAXGrobbulus" },
        { "Gluth", "NAXGluth" },
        { "Thaddius", "NAXThaddius" },
        { "Anub'Rekhan", "NAXAnubRekhan" },
        { "Grand Widow Faerlina", "NAXGrandWidowFaerlina" },
        { "Maexxna", "NAXMaexxna" },
        { "Instructor Razuvious", "NAXInstructorRazuvious" },
        { "Gothik the Harvester", "NAXGothikderHarvester" },
        { "The Four Horsemen", "NAXTheFourHorsemen" },
        { "Noth the Plaguebringer", "NAXNothderPlaguebringer" },
        { "Heigan the Unclean", "NAXHeiganderUnclean" },
        { "Loatheb", "NAXLoatheb" },
        { "Sapphiron", "NAXSapphiron" },
        { "Kel'Thuzad", "NAXKelThuzard" },
        { "Trash Mobs", "NAXTrash" },
    },
    ["Onyxia's Lair"] = {
        { "Onyxia", "Onyxia" },
    },
    ["Ragefire Chasm"] = {
        { "Taragaman the Hungerer", "RFCTaragaman" },
        { "Jergosh the Invoker", "RFCJergosh" },
    },
    ["Razorfen Downs"] = {
        { "Tuten'kash", "RFDTutenkash" },
        { "Mordresh Fire Eye", "RFDMordreshFireEye" },
        { "Glutton", "RFDGlutton" },
        { "Ragglesnout", "RFDRagglesnout" },
        { "Amnennar the Coldbringer", "RFDAmnennar" },
        { "Trash Mobs", "RFDTrash" },
    },
    ["Razorfen Kraul"] = {
        { "Death Speaker Jargba", "RFKDeathSpeakerJargba" },
        { "Overlord Ramtusk", "RFKOverlordRamtusk" },
        { "Agathelos the Raging", "RFKAgathelos" },
        { "Blind Hunter", "RFKBlindHunter" },
        { "Charlga Razorflank", "RFKCharlgaRazorflank" },
        { "Earthcaller Halmgar", "RFKEarthcallerHalmgar" },
        { "Trash Mobs", "RFKTrash" },
    },
    ["The Ruins of Ahn'Qiraj"] = {
        { "Kurinnaxx", "AQ20Kurinnaxx" },
        { "Lieutenant General Andorov", "AQ20Andorov" },
        { "Rajaxx's Captains", "AQ20CAPTIAN" },
        { "General Rajaxx", "AQ20Rajaxx" },
        { "Moam", "AQ20Moam" },
        { "Buru the Gorger", "AQ20Buru" },
        { "Ayamiss the Hunter", "AQ20Ayamiss" },
        { "Ossirian the Unscarred", "AQ20Ossirian" },
        { "Class Books", "AQ20ClassBooks" },
        { "Enchants", "AQEnchants" },
    },
    ["Scarlet Monestery"] = {
        { "Houndmaster Loksey", "SMHoundmasterLoksey" },
        { "Arcanist Doan", "SMDoan" },
        { "Herod", "SMHerod" },
        { "High Inquisitor Fairbanks", "SMFairbanks" },
        { "Scarlet Commander Mograine", "SMMograine" },
        { "High Inquisitor Whitemane", "SMWhitemane" },
        { "Ironspine", "SMIronspine" },
        { "Azshir the Sleepless", "SMAzshir" },
        { "Fallen Champion", "SMFallenChampion" },
        { "Bloodmage Thalnos", "SMBloodmageThalnos" },
        { "Trash Mobs", "SMTrash" },
        { "Set: Chain of the Scarlet Crusade", "SMScarletSET" },
    },
    ["Scholomance"] = {
        { "Blood Steward of Kirtonos",  "SCHOLOBloodSteward" },
        { "Kirtonos the Herald", "SCHOLOKirtonostheHerald" },
        { "Jandice Barov", "SCHOLOJandiceBarov" },
        { "Rattlegore", "SCHOLORattlegore" },
        { "Death Knight Darkreaver", "SCHOLODeathKnight" },
        { "Marduk Blackpool", "SCHOLOMarduk" },
        { "Vectus", "SCHOLOVectus" },
        { "Ras Frostwhisper", "SCHOLORasFrostwhisper" },
        { "Kormok", "SCHOLOKormok" },
        { "Instructor Malicia", "SCHOLOInstructorMalicia" },
        { "Doctor Theolen Krastinov", "SCHOLODoctorTheolenKrastinov" },
        { "Lorekeeper Polkelt", "SCHOLOLorekeeperPolkelt" },
        { "The Ravenian", "SCHOLOTheRavenian" },
        { "Lord Alexei Barov", "SCHOLOLordAlexeiBarov" },
        { "Lady Illucia Barov", "SCHOLOLadyIlluciaBarov" },
        { "Darkmaster Gandling", "SCHOLODarkmasterGandling" },
        { "Trash Mobs", "SCHOLOTrash" },
    },
    ["Shadowfang Keep"] = {
        { "Razorclaw the Butcher", "BSFRazorclawtheButcher" },
        { "Baron Silverlaine", "BSFSilverlaine" },
        { "Commander Springvale", "BSFSpringvale" },
        { "Odo the Blindwatcher", "BSFOdotheBlindwatcher" },
        { "Fenrus the Devourer", "BSFFenrustheDevourer" },
        { "Wolf Master Nandos", "BSFWolfMasterNandos" },
        { "Archmage Arugal", "BSFArchmageArugal" },
        { "Trash Mobs", "BSFTrash" },
    },
    ["The Stockade"] = {
        { "Kam Deepfury", "SWStKamDeepfury" },
        { "Bruegal Ironknuckle", "SWStBruegalIronknuckle" },
    },
    ["Stratholme"] = {
        { "Skul", "STRATSkull" },
        { "Stratholme Courier", "STRATStratholmeCourier" },
        { "Fras Siabi", "STRATFrasSiabi" },
        { "Hearthsinger Forresten", "STRATHearthsingerForresten" },
        { "The Unforgiven", "STRATTheUnforgiven" },
        { "Timmy the Cruel", "STRATTimmytheCruel" },
        { "Cannon Master Willey", "STRATCannonMasterWilley" },
        { "Archivist Galford", "STRATArchivistGalford" },
        { "Balnazzar", "STRATBalnazzar" },
        { "Sothos and Jarien", "STRATSothosJarien" },
        { "Stonespine", "STRATStonespine" },
        { "Baroness Anastari", "STRATBaronessAnastari" },
        { "Nerub'enkan", "STRATNerubenkan" },
        { "Maleki the Pallid", "STRATMalekithePallid" },
        { "Magistrate Barthilas", "STRATMagistrateBarthilas" },
        { "Ramstein the Gorger", "STRATRamsteintheGorger" },
        { "Baron Rivendare", "STRATBaronRivendare" },
        { "Trash Mobs", "STRATTrash" },
    },
    ["The Sunken Temple"] = {
        { "Troll Minibosses", "STTrollMinibosses" },
        { "Atal'alarion", "STAtalalarion" },
        { "Dreamscythe", "STDreamscythe" },
        { "Weaver", "STWeaver"},
        { "Avatar of Hakkar", "STAvatarofHakkar" },
        { "Jammal'an the Prophet", "STJammalan" },
        { "Ogom the Wretched", "STOgom" },
        { "Morphaz", "STMorphaz" },
        { "Hazzas", "STHazzas" },
        { "Shade of Eranikus", "STEranikus" },
        { "Trash Mobs", "STTrash" },
    },
    ["The Temple of Ahn'Qiraj"] = {
        { "The Prophet Skeram", "AQ40Skeram" },
        { "The Bug Family", "AQ40Vem" },
        { "Battleguard Sartura", "AQ40Sartura" },
        { "Fankriss the Unyielding", "AQ40Fankriss" },
        { "Viscidus", "AQ40Viscidus" },
        { "Princess Huhuran", "AQ40Huhuran" },
        { "The Twin Emperors", "AQ40Emperors" },
        { "Ouro", "AQ40Ouro" },
        { "C'Thun", "AQ40CThun" },
        { "Trash Mobs", "AQ40Trash" },
        { "Enchants", "AQEnchants" },
        { "AQ Opening Event", "AQOpening" },
    },
    ["Uldaman"] = {
        { "Revelosh", "UldRevelosh" },
        { "Ironaya", "UldIronaya" },
        { "Ancient Stone Keeper", "UldAncientStoneKeeper" },
        { "Galgann Firehammer", "UldGalgannFirehammer" },
        { "Grimlok", "UldGrimlok" },
        { "Archaedas", "UldArchaedas" },
        { "Trash Mobs", "UldTrash" },
    },
    ["Wailing Caverns"] = {
        { "Lord Cobrahn", "WCLordCobrahn" },
        { "Lady Anacondra", "WCLadyAnacondra" },
        { "Kresh", "WCKresh" },
        { "Lord Pythas", "WCLordPythas" },
        { "Skum", "WCSkum" },
        { "Lord Serpentis", "WCLordSerpentis" },
        { "Verdan the Everliving", "WCVerdan" },
        { "Mutanus the Devourer", "WCMutanus" },
        { "Deviate Faerie Dragon", "WCDeviateFaerieDragon" },
        { "Item Set: Embrace of the Viper", "WCViperSET" },
    },
    ["Zul'Farrak"] = {
        { "Antu'sul", "ZFAntusul" },
        { "Witch Doctor Zum'rah", "ZFWitchDoctorZumrah" },
        { "Shadowpriest Sezz'ziz", "ZFSezzziz" },
        { "Gahz'rilla", "ZFGahzrilla" },
        { "Dustwraith", "ZFDustwraith" },
        { "Chief Ukorz Sandscalp", "ZFChiefUkorzSandscalp" },
        { "Zerillis", "ZFZerillis" },
        { "Trash Mobs", "ZFTrash" },
    },
    ["Zul'Gurub"] = {
        { "High Priestess Jeklik", "ZGJeklik" },
        { "High Priest Venoxis", "ZGVenoxis" },
        { "High Priestess Mar'li", "ZGMarli" },
        { "Bloodlord Mandokir", "ZGMandokir" },
        { "Gri'lek of the Iron Blood", "ZGGrilek" },
        { "Hazzarah the Dreamweaver", "ZGHazzarah" },
        { "Renataki of the Thousand Blades", "ZGRenataki" },
        { "Wushoolay the Storm Witch", "ZGWushoolay" },
        { "Gahz'ranka", "ZGGahzranka" },
        { "High Priest Thekal", "ZGThekal" },
        { "High Priestess Arlokk", "ZGArlokk" },
        { "Jin'do the Hexxer", "ZGJindo" },
        { "Hakkar", "ZGHakkar" },
        { "Shared Boss Drops", "ZGShared" },
        { "Trash Mobs", "ZGTrash" },
        { "Enchants", "ZGEnchants" },
    },
    ["PvP Sets (Level 60)"] = {
        { "Druid", "PVPDruid" },
        { "Hunter", "PVPHunter" },
        { "Mage", "PVPMage" },
        { "Paladin", "PVPPaladin" },
        { "Priest", "PVPPriest" },
        { "Rogue", "PVPRogue" },
        { "Shaman", "PVPShaman" },
        { "Warlock", "PVPWarlock" },
        { "Warrior", "PVPWarrior" },
        { "Weapons 1", "PVPWeapons1" },
        { "Weapons 2", "PVPWeapons2" },
    },
    ["Ruins of AQ Sets"] = {
        { "Druid", "AQ20Druid" },
        { "Hunter", "AQ20Hunter" },
        { "Mage", "AQ20Mage" },
        { "Paladin", "AQ20Paladin" },
        { "Priest", "AQ20Priest" },
        { "Rogue", "AQ20Rogue" },
        { "Shaman", "AQ20Shaman" },
        { "Warlock", "AQ20Warlock" },
        { "Warrior", "AQ20Warrior" },
    },
    ["Temple of AQ Sets"] = {
        { "Druid", "AQ40Druid" },
        { "Hunter", "AQ40Hunter" },
        { "Mage", "AQ40Mage" },
        { "Paladin", "AQ40Paladin" },
        { "Priest", "AQ40Priest" },
        { "Rogue", "AQ40Rogue" },
        { "Shaman", "AQ40Shaman" },
        { "Warlock", "AQ40Warlock" },
        { "Warrior", "AQ40Warrior" },
    },
    ["Zul'Gurub Sets"] = {
        { "Druid", "ZGDruid" },
        { "Hunter", "ZGHunter" },
        { "Mage", "ZGMage" },
        { "Paladin", "ZGPaladin" },
        { "Priest", "ZGPriest" },
        { "Rogue", "ZGRogue" },
        { "Shaman", "ZGShaman" },
        { "Warlock", "ZGWarlock" },
        { "Warrior", "ZGWarrior" },
    },
    ["Tier 0/0.5"] = {
        { "Druid", "T0Druid" },
        { "Hunter", "T0Hunter" },
        { "Mage", "T0Mage" },
        { "Paladin", "T0Paladin" },
        { "Priest", "T0Priest" },
        { "Rogue", "T0Rogue" },
        { "Shaman", "T0Shaman" },
        { "Warlock", "T0Warlock" },
        { "Warrior", "T0Warrior" },
    },
    ["Tier 1"] = {
        { "Druid", "T1Druid" },
        { "Hunter", "T1Hunter" },
        { "Mage", "T1Mage" },
        { "Paladin", "T1Paladin" },
        { "Priest", "T1Priest" },
        { "Rogue", "T1Rogue" },
        { "Shaman", "T1Shaman" },
        { "Warlock", "T1Warlock" },
        { "Warrior", "T1Warrior" },
    },
    ["Tier 2"] = {
        { "Druid", "T2Druid" },
        { "Hunter", "T2Hunter" },
        { "Mage", "T2Mage" },
        { "Paladin", "T2Paladin" },
        { "Priest", "T2Priest" },
        { "Rogue", "T2Rogue" },
        { "Shaman", "T2Shaman" },
        { "Warlock", "T2Warlock" },
        { "Warrior", "T2Warrior" },
    },
    ["Tier 3"] = {
        { "Druid", "T3Druid" },
        { "Hunter", "T3Hunter" },
        { "Mage", "T3Mage" },
        { "Paladin", "T3Paladin" },
        { "Priest", "T3Priest" },
        { "Rogue", "T3Rogue" },
        { "Shaman", "T3Shaman" },
        { "Warlock", "T3Warlock" },
        { "Warrior", "T3Warrior" },
    },
    ["The Argent Dawn"] = {
        { "Token Hand-Ins", "Argent1" },
        { "Friendly/Honored", "Argent2" },
        { "Revered/Exalted", "Argent3" },
    },
    ["The Cenarion Circle"] = {
        { "Friendly", "Cenarion1" },
        { "Honored", "Cenarion2" },
        { "Revered", "Cenarion3" },
        { "Exalted", "Cenarion4" },
    },
    ["The Thorium Brotherhood"] = {
        { "Friendly", "Thorium1" },
        { "Honored", "Thorium2" },
        { "Revered", "Thorium3" },
        { "Exalted", "Thorium4" },
    },
    ["The Zandalar Tribe"] = {
        { "Friendly", "Zandalar1" },
        { "Honored", "Zandalar2" },
        { "Revered", "Zandalar3" },
        { "Exalted", "Zandalar4" },
    },
    ["Alterac Valley"] = {
        { "Friendly", "AVFriendly" },
        { "Honored", "AVHonored" },
        { "Revered", "AVRevered" },
        { "Exalted", "AVExalted" },
    },
    ["Arathi Basin"] = {
        { "Friendly (Lvl 60)", "ABFriendly" },
        { "Honored (Lvl 60)", "ABHonored" },
        { "Revered (Lvl 60)", "ABRevered" },
        { "Exalted (Lvl 60)", "ABExalted" },
    },
    ["Warsong Gulch"] = {
        { "Friendly (Lvl 60)", "WSGFriendly" },
        { "Honored (Lvl 60)", "WSGHonored" },
        { "Revered (Lvl 60)", "WSGRevered" },
        { "Exalted (Lvl 60)", "WSGExalted" },
    },
};
        
    