
DART_DEFAULT_SETTINGS = {
		[1] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 100,
			["scale"] = 1.25,
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 400,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 2",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = -2.85,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["yoffset"] = {
				[1] = -736.1,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[2] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 100,
			["scale"] = 1.25,
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 400,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 2",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 629.4,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["yoffset"] = {
				[1] = -733.3,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[3] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\leftframe1",
			["height"] = 266,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 3",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = -732.05,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -519.29,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[4] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\rightframe1",
			["height"] = 266,
			["parent"] = "UIParent",
			["scale"] = 0.75,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 4",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 721.87,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -524.53,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[5] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopleft1",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 139,
			["parent"] = "UIParent",
			["highlightalpha"] = 0,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 1,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 600,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 8",
			["scale"] = 0.75,
			["xoffset"] = {
				[1] = 218.08,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -1216.91,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[6] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1.25,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["height"] = 100,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["r"] = 0.4117647058823529,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 260,
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 2",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 383.15,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -736.1,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[7] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 10,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["hidebg"] = true,
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull",
			["height"] = 138,
			["hide"] = true,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 74,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["scale"] = 0.75,
			["name"] = "Texture 7",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -365.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -151.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[8] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopleft1",
			["height"] = 139,
			["scale"] = 0.75,
			["highlightalpha"] = 0,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 1,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 600,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 8",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["xoffset"] = {
				[1] = 656.75,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -1216.91,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[9] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopright1",
			["height"] = 106,
			["scale"] = 0.75,
			["highlightalpha"] = 0.3,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 580,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 9",
			["color"] = {
				["b"] = 1,
				["g"] = 0.9686274509803922,
				["r"] = 0.9372549019607843,
			},
			["xoffset"] = {
				[1] = 504.86,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = -10,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -601.91,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[10] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["hidebg"] = 1,
			["highlightalpha"] = 0,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chatbleft1",
			["height"] = 320,
			["parent"] = "UIParent",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 280,
			["alpha"] = 1,
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 10",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 140.34,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -670.84,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[11] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["hidebg"] = true,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chatbright1",
			["height"] = 320,
			["scale"] = 0.75,
			["parent"] = "UIParent",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 280,
			["alpha"] = 1,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 11",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 53.68,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -671,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[12] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 1,
			["attachto"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = 1,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topmiddel1v2",
			["height"] = 138,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["parent"] = "UIParent",
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["highlightcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["alpha"] = 1,
			["name"] = "Texture 12",
			["scale"] = 1,
			["xoffset"] = {
				[1] = 5.84,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -83.14,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[13] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 0,
			["scale"] = 1,
			["bgalpha"] = 0,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["scripts"] = {
			},
			["hidebg"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topleft1v2",
			["height"] = 74,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 522,
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["name"] = "Texture 13",
			["parent"] = "UIParent",
			["xoffset"] = {
				[1] = -378.09,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = 460.29,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[14] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scale"] = 1,
			["bgalpha"] = 1,
			["hidebg"] = true,
			["height"] = 74,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["width"] = 522,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "Texture 14",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = 370.82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topright1v2",
			["yoffset"] = {
				[1] = 459.85,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[15] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bgalpha"] = 1,
			["hidebg"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topright1v2extra",
			["height"] = 135,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["alpha"] = 1,
			["name"] = "Texture 15",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["xoffset"] = {
				[1] = 505.09,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = 428.88,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[16] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["bgalpha"] = 1,
			["hidebg"] = true,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topleft1v2extra",
			["height"] = 135,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["alpha"] = 1,
			["name"] = "Texture 16",
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["xoffset"] = {
				[1] = -510.43,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = 429.35,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[17] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 3,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\castingbar",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 74,
			["hide"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.75,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["width"] = 522,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["highlightalpha"] = 0.3,
			["name"] = "Texture 17",
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = -288.82,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -141.79,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[18] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 15,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
				[2] = "",
				[14] = "",
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\Addons\\DiscordArt\\CustomTextures\\new\\logo",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["height"] = 130,
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 130,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["justifyH"] = 5,
				["fontsize"] = 16,
				["attachto"] = 2,
				["xoffset"] = 0,
				["height"] = 20,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["name"] = "logo",
			["scale"] = 1,
			["xoffset"] = {
				[1] = 16,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["bgalpha"] = 1,
			["yoffset"] = {
				[1] = -440.34,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[19] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframeleft",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 522,
			["hide"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.98,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightalpha"] = 0.3,
			["name"] = "Texture 19",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = 124.56,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -485.15,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[20] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframelright",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 2,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 522,
			["hide"] = true,
			["color"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["scale"] = 0.98,
			["bordercolor"] = {
				["b"] = 1,
				["g"] = 1,
				["r"] = 1,
			},
			["alpha"] = 1,
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 1,
				["r"] = 1,
			},
			["text"] = {
				["yoffset"] = 0,
				["color"] = {
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["alpha"] = 1,
				["fontsize"] = 16,
				["justifyH"] = 5,
				["attachto"] = 2,
				["height"] = 20,
				["xoffset"] = 0,
				["attachpoint"] = 2,
				["hide"] = true,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightalpha"] = 0.3,
			["name"] = "Texture 20",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["xoffset"] = {
				[1] = -62.86,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -223.32,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		["updatespeed"] = 60,
		["INITIALIZED1.0d"] = true,
		["optionsscale"] = 1,
		["autolock"] = 1,
		["INITIALIZED1.1"] = true,
}
