aUF.Layouts.Roartindon = {
		Name = "Roartindon",
		Tip = "Roartindon Raid",
		ResizeBars = false,
		BackgroundBarColor = true,
		AlphaBar = true,
		RaidColorName = false,
		PetClassName = true,	
		ComboGFX = true,
		HappinessBar = true,
		
		ThemeData = {
			all = {
				FrameHeight = 21,
				FrameWidth = 110,

				Combo1 = 	{ 		Hidden = true },
								
				HealthBar_BG = 	{ 	Point = "TOPLEFT",
									RelativePoint = "TOPLEFT",
									x = 4,
									y = -4,	
									Visibility = {"HealthBar_BG","HealthBar","BarHealthText","HealthText",},
									Height = 13,
									HeightAdd = 0,									
									Width = 92,
								},
									
				ManaBar_BG = 	{	Point = "TOPLEFT",
									RelativePoint = "BOTTOMLEFT", 
									RelativeTo = "HealthBar_BG",
									x = 0, 
									y = -1, 
									HeightAdd = 3,
									Visibility = {"ManaBar_BG","ManaBar","BarManaText","ManaText","ClassText",},	
									Height = 2,
									Width = 92,
								},
								
				XPBar_BG = 	{		Point = "TOPLEFT",
									RelativePoint = "BOTTOMLEFT",
									RelativeTo = "ManaBar_BG",
									x = 0, 
									y = -1, 
									HeightAdd = 3,
									Visibility = {"XPBar_BG","XPBar","XPBar_Rest"},	
									Height = 2,
									Width = 92,
								},
								
				NameBackground=	{	Hidden = true },
								
					Happiness =	{	Hidden = true },
								
				NameLabel = 	{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 9, 
									Width = 92, 
									Point = "LEFT", 
									RelativeTo = "HealthBar", 
									RelativePoint = "LEFT", 
									x = 1, 
									y = 0,
								},

				ClassText =	 	{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf",
									FontSize = 6, 
									Justify = "LEFT",
									Width = 90, 
									Point = "LEFT", 
									RelativeTo = "ManaBar_BG", 
									RelativePoint = "LEFT", 
									x = 1, 
									y = 0.5,
								},
					
				HealthText = 	{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 9,
									Point = "RIGHT", 
									RelativeTo = "HealthBar_BG", 
									RelativePoint = "RIGHT", 
									x=-2,
									y=0,
									Width = 92,
									Justify = "RIGHT",
								},

				ManaText = 		{ 	Font = "Interface\\AddOns\\ag_UnitFrames\\fonts\\barframes.ttf", 
									FontSize = 6,
									Point = "RIGHT", 
									RelativeTo = "ManaBar_BG", 
									RelativePoint = "RIGHT", 
									x=-2,
									y=0.5,
									Width = 92,
									Justify = "RIGHT",
								},
					
				BarHealthText = { Hidden = true },
				BarManaText = 	{ Hidden = true },
--				InCombatIcon = 	{ Hidden = true },
				RestingIcon =	{ Hidden = true },
				MasterIcon =	{ Hidden = true },

				PVPIcon = 		{ 	Point = "TOPRIGHT", 
									RelativePoint = "TOPRIGHT", 
									x = 14, 
									y= 2,
								},

				InCombatIcon = 		{ 	Point = "BOTTOMLEFT", 
									RelativePoint = "BOTTOMLEFT", 
									x = -4, 
									y= -3,
								},
				RaidTargetIcon =	{	Point = "CENTER",
									RelativePoint = "TOP",
									x = 0,
									y = -3,
								},
				LeaderIcon = 	{ 	Point = "TOPLEFT", 
									RelativePoint = "TOPLEFT", 
									x = -2, 
									y= 2,
								},
			},
		}
	}

