local L = AceLibrary("AceLocale-2.2"):new("XRS")

L:RegisterTranslations("deDE", function() return {
	-- XRS.lua
	Scale = "Skalierung",
	Scale_D = "Die Skalierung des XRaidStatus Fenster setzen.",
	Texture = "Textur",
	Textures = "Texturen",
	Textures_D = "Textur der Bars auswählen",
	Color_Group = "Farben auswählen",
	Color_Group_D = "Farben des XRaidStatus Fenster ändern.",
	BColor = "Hintergrundfarbe",
	BColor_D = "Die Hintergrundfarbe des XRaidStatus Fensters ändern.",
	BOColor = "Rand Farbe",
	BOColor_D = "Die Farbe des Randes ändern.",
	TColor = "Titel Farbe",
	TColor_D = "Die Farbe der Titel Schrift ändern.",
	Update_Rate = "Aktualisierungsrate",
	Update_Rate_D = "Die Aktualisierungsrate der Bars ändern.",
	Save = "Speichern",
	Save_D = "Eine Konfiguration sichern.",
	Load = "Laden",
	Load_D = "Eine Konfiguration laden.",
	Delete = "Löschen",
	Delete_D = "Eine Konfiguration löschen.",
	New_Group = "Neu",
	New_Group_D = "Eine neue Bar oder einen neuen Buff-Button erstellen.",
	Create_Bar = "Neue Bar",
	Create_Bar_D = "Eine neue Bar mit Standardwerten erstellen.",
	Create_Button = "Neuen Buff-Button",
	Create_Button_D = "Einen neuen Buff-Button erstellen.",
	Delete_DB = "DB löschen",
	Delete_DB_D = "Löscht die Datenbank/das Profil",
	Lock = "Fenster sperren",
	Lock_D = "Sperrt das XRaidStatus Fenster so dass es nichtmehr bewegt werden kann",
	Raid_Leader_Options = "Raid Leiter Optionen",
	Buff_Check = "Buff Test",
	Buff_Check_TTText = "Einen Buff Test mit den ausgewählten Buffs ausführen und die Ergebnisse im Raid Chat posten.",
	Ready_Check = "Bereitschafts Test",
	Ready_Check_TTText = "Startet den Bereitschafts Test von Blizzard",
	Select_Buffs = "Buffs auswählen",
	Select_Buffs_TTText = "Buffs auswählen nach denen gesucht werden soll",
	Start_Check = "Test starten",
	Start_Check_TTText = "Startet den Buff Test und veröffentlicht das Ergebnis im Raid Chat.",
	Hint = "Hinweis",
	Hint_D = "Hinweise anzeigen in den Tooltips",
	["No Buffs Needed!"] = "Keine Buffs benötigt!",
	[" missing buffs."] = " fehlende Buffs.",
	Width = "Breite",
	Width_D = "Breite des XRaidStatus Fensters setzen.",

	-- XRS_BarClass.lua
	Name = "Name",
	Name_TTText = "Name der Statusbar.",
	Type = "Typ",
	Type_TTTitle = "Typ auswählen",
	Type_TTText = "Typ der Bar.",
	Classes = "Klassen",
	Classes_TTTitle = "Klassen auswählen",
	Classes_TTText = "Klassen die diese Bar repräsentieren.",
	Groups = "Gruppen",
	Groups_TTTitle = "Gruppen auswählen",
	Groups_TTText = "Raid Gruppen die diese Bar repräsentieren.",
	Group = "Gruppe",
	Color = "Farbe",
	Color_TTTitle = "Farben auswählen",
	Color_TTText = "Die Farbe der Bar und dem Text auswählen oder Standard Einstellungen benutzen.",    
	Backgroundbar = "Hintergrund Bar aktivieren",
	Backgroundbar_TTTitle = "Hintergrund Bar aktivieren",
	Backgroundbar_TTText = "Eine Bar im Hintergrund aktivieren mit der gleichen Farbeinstellung.",
	Deaths = "Tote miteinbeziehen",
	Deaths_TTText = "Tote miteinbeziehen in der Berechnung der Bar.",
	Bar_Up = "Bar hoch",
	Bar_Up_TTText = "Die Bar wird um eine Zeile nach oben verschoben.",
	Bar_Down = "Bar runter",
	Bar_Down_TTText = "Die Bar wird um eine Zeile nach unten verschoben.",
	Delete_Bar = "Bar löschen",
	Delete_Bar_TTText = "Löscht die Bar.",
	Create_Bar_TTTitle = "Neue Bar erstellen",
	Create_Bar_TTText = "Eine neue Bar mit Standardwerten erstellen.",
	Life = "Leben",
	Mana = "Mana",
	Alive = "Am Leben",
	Dead = "Tot",
	Offline = "Offline",
	Range = "In Reichweite",
	Range_Text = "Reichweiten Modus",
	Range_TTTitle = "Reichweiten Modus",
	Range_TTText = "Den Reichweiten Modus auswählen.",
	Blank = "Frei",
	Afk = "Afk",
	PvP = "PvP",
	Use_Bar_Color = "Bar Farbe benutzen",
	Bar_Color = "Farbe der Bar",
	Use_Text_Color = "Text Farbe benutzen",
	Text_Color = "Farbe vom Text",
	Yards_0 = "10 Meter",
	Yards_1 = "30 Meter",
	Yards_2 = "100 Meter",
	Yards_3 = "Zone",

	-- XRS_BuffClass.lua
	Buff_Text = "Buff auswählen",
	Buff_TTTitle = "Buff auswählen",
	Buff_TTText = "Einen Buff für diesen Button auswählen.",
	Delete_Buff_Text = "Buff löschen",
	Delete_Buff_TTTitle = "Buff löschen",
	Delete_Buff_TTText = "Diesen Buff aus der Anzeige löschen.",
	Predefined_Text = "Vordefinierte Buffs", 
	Predefined_TTTitle = "Vordefinierte Buffs",
	Predefined_TTText = "Einen Buff aus dem vordefinierten Pool auswählen.",
	Enter_Buff = "Eigener Buff",
	Enter_Buff_TTTitle = "Eigenen Buff eintragen",
	Enter_Buff_TTText = "Einen eigenen Buff eintragen nach dem gesucht werden soll.",
	Group = "(Gruppen) ",
	Invert = "Invertieren",
	UnitIsVisible ="Einheit ist sichtbar",
	["Full buffed!"] = "Voll gebuffed!",
	[" missing."] = " fehlen.",

	-- XRS_TooltipClasses.lua
	Buff_Hint = "Linksklick = buffen, Shift-linksklick = Fehlende Buffs posten, Strg-linksklick = Tooltip lösen",
	Bar_Hint = "Strg-linksklick = Tooltip lösen",
} end)