local L = AceLibrary("AceLocale-2.2"):new("XRS")

L:RegisterTranslations("frFR", function() return {
    -- XRS.lua
    Scale = "Echelle",
    Scale_D = "D\195\169finit l'\195\169chelle de la fen\195\170tre XRaidStatus.",
    Texture = "Texture",
    Textures = "Textures",
    Textures_D = "S\195\169lectionne une texture pour les barres.",
    Color_Group = "Gestion des couleurs",
    Color_Group_D = "Change les couleurs de la fen\195\170tre XRaidStatus.",
    BColor = "Couleur de l'arri\195\168re-plan",
    BColor_D = "Change la couleur de l'arri\195\168re-plan.",
    BOColor = "Couleur de bordure",
    BOColor_D = "Change la couleur de la bordure.",
    TColor = "Couleur du titre",
    TColor_D = "Change la couleur du titre.",
    Update_Rate = "Taux de rafraichissement",
    Update_Rate_D = "R\195\168gle le taux de rafraichissement des barres.",
    Save = "Sauvegarde",
    Save_D = "Sauvegarde une configuration.",
    Load = "Charge",
    Load_D = "Charge une configuration.",
    Delete = "Supprime",
    Delete_D = "Supprime une configuration.",
    New_Group = "Nouveau",
    New_Group_D = "Cr\195\169e une nouvelle barre ou un nouveau bouton de buff.",
    Create_Bar = "Cr\195\169e une nouvelle barre",
    Create_Bar_D = "Cr\195\169e une nouvelle barre (valeurs par d\195\169faut).",
    Create_Button = "Cr\195\169e un nouveau bouton de buff",
    Create_Button_D = "Cr\195\169e un nouveau bouton de buff.",
    Delete_DB = "Supprime la BdD",
    Delete_DB_D = "Supprime la base de donn\195\169es/Profil",
    Lock = "Verrouille l'interface",
    Lock_D = "Verrouille l'interface XRaidStatus \195\160 la position actuelle.",
    Raid_Leader_Options = "Options du Raid Leader",
    Buff_Check = "V\195\169rification des buffs",
    Buff_Check_TTText = "Effectue une v\195\169rification des buffs s\195\169lectionn\195\169s et affiche le r\195\169sultat sur le canal raid.",
    Ready_Check = "Ready Check",
    Ready_Check_TTText = "Lance le ready check Blizzard",
    Select_Buffs = "S\195\169lection des buffs",
    Select_Buffs_TTText = "S\195\169lection des buffs qui devront \195\170tre examin\195\169 lors de la v\195\169rification.",
    Start_Check = "Lance la v\195\169rification",
    Start_Check_TTText = "Lance la v\195\169rification des buffs et affiche le r\195\169sultat sur le canal de raid.",
    Hint = "Infobulle",
    Hint_D = "Affiche les infobulles",
    ["No Buffs Needed!"] = "Aucun buff manquant !",
    [" missing buffs."] = " buff manquants.",
    Width = "Largeur",
    Width_D = "R\195\168gle la largeur de la fen\195\170tre XRaidStatus.",

    -- XRS_BarClass.lua
    Name = "Nom",
    Name_TTText = "Nom de la barre d'\195\169tat.",
    Type = "Type",
    Type_TTTitle = "Choix du type",
    Type_TTText = "Choix du type de barre.",
    Classes = "Classes",
    Classes_TTTitle = "S\195\169lection des classes",
    Classes_TTText = "S\195\169lection des classes incluses dans cette barre.",
    Groups = "Groupes",
    Groups_TTTitle = "S\195\169lection des groupes",
    Groups_TTText = "S\195\169lection des groupes inclus dans cette barre.",
    Group = "Groupe",
    Color = "Couleur",
    Color_TTTitle = "S\195\169lection des couleurs",
    Color_TTText = "S\195\169lectionne les couleurs des barres et du texte (utilisation des valeurs par d\195\169faut sinon).",
    Deaths = "Inclus les morts",
    Deaths_TTText = "Inclus les morts dans le calcul la valeur en pourcentage de la barre.",
    Backgroundbar = "Activation des arri\195\168re-plans",
    Backgroundbar_TTTitle = "Activation des arri\195\168re-plans",
    Backgroundbar_TTText = "Activation des arri\195\168re-plan pour cette barre d'\195\169tat.",
    Bar_Up = "Vers le haut",
    Bar_Up_TTText = "D\195\169place la barre d'une position vers le haut.",
    Bar_Down = "Vers le bas",
    Bar_Down_TTText = "D\195\169place la barre d'une position vers le bas.",
    Delete_Bar = "Suppression de la barre",
    Delete_Bar_TTText = "Supprime la barre",
    Create_Bar_TTTitle = "Cr\195\169e une nouvelle barre",
    Create_Bar_TTText = "Cr\195\169e une nouvelle barre avec des valeurs (par d\195\169faut).",
    Life = "Vie",
    Mana = "Mana",
    Alive = "Vivant",
    Dead = "Mort",
    Offline = "Hors-ligne",
    Range = "Port\195\169e",
    Range_Text = "Mode port\195\169e",
    Range_TTTitle = "S\195\169lection du mode port\195\169e",
    Range_TTText = "S\195\169lection de la port\195\169 pour le comptage de la barre.",
    Blank = "Blanc",
    Afk = "Afk",
    PvP = "JcJ",
    Use_Bar_Color = "Utilise les barres de couleur",
    Bar_Color = "Barre de Couleur",
    Use_Text_Color = "Utilise les textes de couleur",
    Text_Color = "Texte de Couleur",
    Yards_0 = "10 yards",
    Yards_1 = "30 yards",
    Yards_2 = "100 yards",
    Yards_3 = "Zone",
    
    -- XRS_BuffClass.lua
    Buff_Text = "S\195\169lection du Buff",
    Buff_TTTitle = "S\195\169lection du Buff",
    Buff_TTText = "S\195\169lectionne le buff pour cet ic\195\180ne.",
    Delete_Buff_Text = "Supprime le buff",
    Delete_Buff_TTTitle = "Supprime le buff",
    Delete_Buff_TTText = "Supprime le buff de cette vue.",
    Predefined_Text = "Buffs pr\195\169-existants",
    Predefined_TTTitle = "Buffs pr\195\169-existants",
    Predefined_TTText = "Choix d'un buff pr\195\169-existant.",
    Enter_Buff = "Entr\195\169e d'un nouveau buff",
    Enter_Buff_TTTitle = "Entr\195\169e d'un nouveau buff",
    Enter_Buff_TTText = "Entr\195\169e d'un nouveau buff \195\160 v\195\169rifier",
    Group = "(Groupe) ",
    Invert = "Inverse",
    UnitIsVisible ="Unit is visble",
    ["Full buffed!"] = "Aucun buff manquant !",
    [" missing."] = " manquants.",

    -- XRS_TooltipClasses.lua
    Buff_Hint = "ClickGauche = buff, Shift-ClickGauche = Affiche les buffs manquants, Ctrl-ClickGauche = D\195\169tache la tooltip",
    Bar_Hint = "Ctrl-ClickGauche = D\195\169tache la tooltip",
} end)


