local L = AceLibrary("AceLocale-2.2"):new("XRS")

L:RegisterTranslations("zhCN", function() return {
	-- XRS.lua

	-- zhCN localization by hk2717
	Scale = "设置缩放",
	Scale_D = "设置XRaidStatus窗口的缩放比例。",
	Texture = "材质",
	Textures = "材质",
	Textures_D = "选择状态条材质。",
	Color_Group = "设定颜色",
	Color_Group_D = "设定XRaidStatus窗口的颜色。",
	BColor = "背景颜色",
	BColor_D = "设定背景颜色。",
	BOColor = "边框颜色",
	BOColor_D = "设定边框颜色。",
	TColor = "标题颜色",
	TColor_D = "设定标题颜色。",
	Update_Rate = "更新速率",
	Update_Rate_D = "设定状态条更新速率。",
	Save = "保存",
	Save_D = "保存设置。",
	Load = "载入",
	Load_D = "载入设置。",
	Delete = "删除",
	Delete_D = "删除设置。",
	New_Group = "新建",
	New_Group_D = "新建一个状态条或增益按钮。",
	Create_Bar = "新建状态条",
	Create_Bar_D = "新建一个状态条。",
	Create_Button = "新建增益按钮",
	Create_Button_D = "新建一个增益按钮。",
	Delete_DB = "删除数据",
	Delete_DB_D = "删除一组保存的数据。",
	Lock = "锁定框体",
	Lock_D = "锁定XRaidStatus框体于当前位置。",
	Raid_Leader_Options = "团队领袖设置",
	Buff_Check = "增益检查",
	Buff_Check_TTText = "检查选择的增益效果，在团队聊天频道输出结果。",
	Ready_Check = "就绪检查",
	Ready_Check_TTText = "检查团队就绪状态。",
	Select_Buffs = "选择增益",
	Select_Buffs_TTText = "选择要检测的增益效果。",
	Start_Check = "开始检查",
	Start_Check_TTText = "进行增益效果检查，在团队聊天频道输出结果。",
	Hint = "提示",
	Hint_D = "显示提示",
	["No Buffs Needed!"] = "无需buff！", -- CHECK
	[" missing buffs."] = " 遗漏的buff。", -- CHECK
	Width = "设定宽度",
	Width_D = "设定XRaidStatus窗口宽度",

	-- XRS_BarClass.lua
	Name = "名字",
	Name_TTText = "状态条的名字。",
	Type = "类型",
	Type_TTTitle = "选择类型",
	Type_TTText = "状态条的类型。",
	Classes = "职业",
	Classes_TTTitle = "选择职业",
	Classes_TTText = "此状态条代表的职业。",
	Groups = "小队",
	Groups_TTTitle = "选择小队",
	Groups_TTText = "此状态条代表的小队。",
	Group = "小队",
	Color = "颜色",
	Color_TTTitle = "选择颜色",
	Color_TTText = "选择状态条及其上文本的颜色，或使用默认设置。",    
	Deaths = "包括死亡玩家",
	Deaths_TTText = "计算状态条数值时包括已死亡的玩家。",
	Backgroundbar = "激活背景条",
	Backgroundbar_TTTitle = "激活背景条",
	Backgroundbar_TTText = "为此状态条激活背景条。",
	Bar_Up = "向上移动",
	Bar_Up_TTText = "将此状态条向上移动一排",
	Bar_Down = "向下移动",
	Bar_Down_TTText = "将此状态条向下移动一排",
	Delete_Bar = "删除状态条",
	Delete_Bar_TTText = "删除状态条",
	Create_Bar_TTTitle = "新建状态条",
	Create_Bar_TTText = "新建一个状态条。",
	Life = "生命",
	Mana = "法力",
	Alive = "存活",
	Dead = "死亡",
	Offline = "离线",
	Range = "范围",
	Range_Text = "范围模式",
	Range_TTTitle = "选择范围模式",
	Range_TTText = "为此范围类型选择一个范围模式。",
	Blank = "空白",
	Afk = "Afk",
	PvP = "PvP",
	Use_Bar_Color = "使用状态条颜色",
	Bar_Color = "状态条颜色",
	Use_Text_Color = "使用文本颜色",
	Text_Color = "文本颜色",
	Yards_0 = "10码",
	Yards_1 = "30码",
	Yards_2 = "100码",
	Yards_3 = "全区域",

	-- XRS_BuffClass.lua
	Buff_Text = "选择增益",
	Buff_TTTitle = "选择增益",
	Buff_TTText = "为此按钮选择一个增益效果。",
	Delete_Buff_Text = "删除增益",
	Delete_Buff_TTTitle = "删除增益",
	Delete_Buff_TTText = "删除此增益的显示。",
	Predefined_Text = "预定义增益", 
	Predefined_TTTitle = "预定义增益",
	Predefined_TTText = "选择一个预定义增益。",
	Enter_Buff = "输入自定义增益",
	Enter_Buff_TTTitle = "输入自定义增益",
	Enter_Buff_TTText = "输入一个供检查的自定义增益。",
	Group = "小队",
	Invert = "翻转",
	UnitIsVisible ="目标可见",
	["Full buffed!"] = "buff齐全！", -- CHECK
	[" missing."] = " 缺少。", -- CHECK

	-- XRS_TooltipClasses.lua
	Buff_Hint = "左键 = 增益, Shift-左键 = 报告增益缺失, Ctrl-左键 = 分离信息条",
	Bar_Hint = "Ctrl-左键 = 分离信息条",
} end)