EmoteButtons_ImageList =
	{ "Ability_Ambush", "Ability_BackStab", "Ability_BullRush", "Ability_CheapShot",
"Ability_CriticalStrike", "Ability_Defend", "Ability_Devour", "Ability_Druid_AquaticForm",
"Ability_Druid_Bash", "Ability_Druid_CatForm", "Ability_Druid_CatFormAttack", "Ability_Druid_ChallangingRoar",
"Ability_Druid_Cower", "Ability_Druid_Dash", "Ability_Druid_DemoralizingRoar", "Ability_Druid_Disembowel",
"Ability_Druid_Enrage", "Ability_Druid_Maul", "Ability_Druid_Rake", "Ability_Druid_Ravage",
"Ability_Druid_SupriseAttack", "Ability_Druid_Swipe", "Ability_Druid_TravelForm", "Ability_DualWield",
"Ability_Ensnare", "Ability_EyeOfTheOwl", "Ability_FiegnDead", "Ability_GhoulFrenzy",
"Ability_GolemStormBolt", "Ability_GolemThunderClap", "Ability_Gouge", "Ability_Hibernation",
"Ability_Hunter_AimedShot", "Ability_Hunter_AspectOfTheMonkey", "Ability_Hunter_BeastCall", "Ability_Hunter_BeastCall02",
"Ability_Hunter_BeastSoothe", "Ability_Hunter_BeastTaming", "Ability_Hunter_BeastTraining", "Ability_Hunter_CriticalShot",
"Ability_Hunter_EagleEye", "Ability_Hunter_MendPet", "Ability_Hunter_Pathfinding", "Ability_Hunter_Pet_Bat",
"Ability_Hunter_Pet_Bear", "Ability_Hunter_Pet_Boar", "Ability_Hunter_Pet_Cat", "Ability_Hunter_Pet_Crab",
"Ability_Hunter_Pet_Crocolisk", "Ability_Hunter_Pet_Gorilla", "Ability_Hunter_Pet_Hyena", "Ability_Hunter_Pet_Owl",
"Ability_Hunter_Pet_Raptor", "Ability_Hunter_Pet_Scorpid", "Ability_Hunter_Pet_Spider", "Ability_Hunter_Pet_TallStrider",
"Ability_Hunter_Pet_Turtle", "Ability_Hunter_Pet_Vulture", "Ability_Hunter_Pet_WindSerpent", "Ability_Hunter_Pet_Wolf",
"Ability_Hunter_Quickshot", "Ability_Hunter_RunningShot", "Ability_Hunter_SniperShot", "Ability_Hunter_SwiftStrike",
"Ability_ImpalingBolt", "Ability_Kick", "Ability_Marksmanship", "Ability_MeleeDamage",
"Ability_Mount_BlackDireWolf", "Ability_Mount_BlackPanther", "Ability_Mount_JungleTiger", "Ability_Mount_MechaStrider",
"Ability_Mount_MountainRam", "Ability_Mount_NightmareHorse", "Ability_Mount_PinkTiger", "Ability_Mount_Raptor",
"Ability_Mount_RidingHorse", "Ability_Mount_Undeadhorse", "Ability_Mount_WhiteDireWolf", "Ability_Mount_WhiteTiger",
"Ability_Parry", "Ability_Physical_Taunt", "Ability_PierceDamage", "Ability_PoisonArrow",
"Ability_Poisons","Ability_PoisonSting", "Ability_Racial_Avatar", "Ability_Racial_BearForm",
"Ability_Racial_BloodRage", "Ability_Racial_Cannibalize", "Ability_Racial_ShadowMeld", "Ability_Racial_Ultravision",
"Ability_Repair", "Ability_Rogue_Ambush", "Ability_Rogue_Disguise", "Ability_Rogue_Distract", "Ability_Rogue_DualWeild",
"Ability_Rogue_Eviscerate", "Ability_Rogue_FeignDeath", "Ability_Rogue_Feint", "Ability_Rogue_Garrote",
"Ability_Rogue_KidneyShot", "Ability_Rogue_Rupture", "Ability_Rogue_SliceDice", "Ability_Rogue_Sprint",
"Ability_Rogue_Trip", "Ability_Sap", "Ability_Seal", "Ability_SearingArrow",
"Ability_ShockWave", "Ability_ShootWand", "Ability_Smash", "Ability_Spy", "Ability_Stealth",
"Ability_SteelMelee", "Ability_TheBlackArrow", "Ability_Throw", "Ability_ThunderBolt",
"Ability_ThunderClap", "Ability_TownWatch", "Ability_Tracking", "Ability_TrueShot",
"Ability_UpgradeMoonGlaive", "Ability_Vanish", "Ability_Warrior_BattleShout", "Ability_Warrior_Challange",
"Ability_Warrior_Charge", "Ability_Warrior_Cleave", "Ability_Warrior_DecisiveStrike", "Ability_Warrior_DefensiveStance",
"Ability_Warrior_Disarm","Ability_Warrior_InnerRage", "Ability_Warrior_OffensiveStance", "Ability_Warrior_PunishingBlow",
"Ability_Warrior_Revenge", "Ability_Warrior_Riposte", "Ability_Warrior_SavageBlow", "Ability_Warrior_ShieldBash",
"Ability_Warrior_ShieldWall", "Ability_Warrior_Sunder", "Ability_Warrior_WarCry", "Ability_WarStomp",
"Ability_Whirlwind", "Racial_Dwarf_FindTreasure", "Racial_Orc_BerserkerStrength", "Racial_Troll_Berserk",
"Spell_Arcane_Blink", "Spell_Arcane_PortalDarnassus", "Spell_Arcane_PortalIronForge","Spell_Arcane_PortalOrgrimmar",
"Spell_Arcane_PortalStormWind", "Spell_Arcane_PortalThunderBluff", "Spell_Arcane_PortalUnderCity","Spell_Arcane_StarFire",
"Spell_Arcane_TeleportDarnassus", "Spell_Arcane_TeleportIronForge", "Spell_Arcane_TeleportMoonglade", "Spell_Arcane_TeleportOrgrimmar",
"Spell_Arcane_TeleportStormWind", "Spell_Arcane_TeleportThunderBluff", "Spell_Arcane_TeleportUnderCity", "Spell_Fire_EnchantWeapon",
 "Spell_Fire_Fire", "Spell_Fire_FireArmor", "Spell_Fire_Fireball", "Spell_Fire_Fireball02",
"Spell_Fire_FireBolt", "Spell_Fire_FireBolt02", "Spell_Fire_FlameBlades", "Spell_Fire_FlameBolt",
"Spell_Fire_FlameShock", "Spell_Fire_FlameTounge", "Spell_Fire_Flare", "Spell_Fire_Immolation",
"Spell_Fire_Incinerate", "Spell_Fire_LavaSpawn", "Spell_Fire_MeteorStorm", "Spell_Fire_SealOfFire",
"Spell_Fire_SearingTotem", "Spell_Fire_SelfDestruct", "Spell_Fire_SoulBurn", "Spell_Fire_SunKey",
"Spell_Fire_Volcano", "Spell_Fire_WindsofWoe", "Spell_Frost_ChainsOfIce", "Spell_Frost_ChillingArmor",
"Spell_Frost_ChillingBlast", "Spell_Frost_ChillingBolt", "Spell_Frost_FreezingBreath", "Spell_Frost_Frost",
"Spell_Frost_FrostArmor", "Spell_Frost_FrostArmor02", "Spell_Frost_FrostBlast", "Spell_Frost_Frostbolt",
"Spell_Frost_FrostBolt02", "Spell_Frost_FrostBrand", "Spell_Frost_FrostNova", "Spell_Frost_FrostShock",
"Spell_Frost_FrostWard", "Spell_Frost_Glacier", "Spell_Frost_IceClaw", "Spell_Frost_IceShard",
"Spell_Frost_IceShock", "Spell_Frost_IceStorm", "Spell_Frost_ManaBurn", "Spell_Frost_ManaRecharge",
"Spell_Frost_Stun", "Spell_Frost_SummonWaterElemental", "Spell_Frost_WindWalkOn", "Spell_Frost_Wisp",
"Spell_Frost_WizardMark", "Spell_Holy_AshesToAshes", "Spell_Holy_AuraOfLight", "Spell_Holy_BlessingOfAgility",
"Spell_Holy_BlessingOfProtection", "Spell_Holy_BlessingOfStamina", "Spell_Holy_BlessingOfStrength", "Spell_Holy_Devotion",
"Spell_Holy_DevotionAura", "Spell_Holy_DispelMagic", "Spell_Holy_DivineIntervention", "Spell_Holy_Dizzy",
"Spell_Holy_Excorcism", "Spell_Holy_Excorcism_02", "Spell_Holy_FistOfJustice", "Spell_Holy_FlashHeal",
"Spell_Holy_GreaterHeal", "Spell_Holy_HarmUndeadAura", "Spell_Holy_Heal", "Spell_Holy_Heal02",
"Spell_Holy_HealingAura", "Spell_Holy_HolyBolt", "Spell_Holy_HolyProtection", "Spell_Holy_HolySmite",
"Spell_Holy_InnerFire", "Spell_Holy_LayOnHands", "Spell_Holy_LesserHeal", "Spell_Holy_LesserHeal02",
"Spell_Holy_MagicalSentry", "Spell_Holy_MindSooth", "Spell_Holy_MindVision", "Spell_Holy_NullifyDisease",
"Spell_Holy_PowerWordShield", "Spell_Holy_PrayerOfHealing", "Spell_Holy_PrayerOfHealing02", "Spell_Holy_Purify",
"Spell_Holy_Redemption", "Spell_Holy_RemoveCurse", "Spell_Holy_Renew", "Spell_Holy_Restoration",
"Spell_Holy_Resurrection", "Spell_Holy_Retribution", "Spell_Holy_RetributionAura", "Spell_Holy_RighteousFury",
"Spell_Holy_RighteousnessAura", "Spell_Holy_SealOfFury", "Spell_Holy_SealOfMight", "Spell_Holy_SealOfProtection",
"Spell_Holy_SealOfRighteousness", "Spell_Holy_SealOfSacrifice", "Spell_Holy_SealOfSalvation", "Spell_Holy_SealOfValor",
"Spell_Holy_SealOfWisdom", "Spell_Holy_SealOfWrath", "Spell_Holy_SearingLight", "Spell_Holy_SenseUndead",
"Spell_Holy_Silence", "Spell_Holy_TurnUndead", "Spell_Holy_WordFortitude", "Spell_Ice_Lament",
"Spell_Ice_MagicDamage","Spell_Lightning_LightningBolt01", "Spell_Magic_FeatherFall", "Spell_Magic_LesserInvisibilty",
"Spell_Magic_MageArmor","Spell_Magic_PolymorphChicken",  "Spell_Magic_PolymorphPig", "Spell_Misc_ConjureManaJewel",
"Spell_Misc_Drink", "Spell_Misc_Food", "Spell_Nature_AbolishMagic", "Spell_Nature_Acid_01",
"Spell_Nature_AgitatingTotem", "Spell_Nature_AncestralGuardian", "Spell_Nature_AstralRecal", "Spell_Nature_AstralRecalGroup",
"Spell_Nature_BloodLust","Spell_Nature_Brilliance",  "Spell_Nature_CallStorm","Spell_Nature_ChainLightning",
"Spell_Nature_CorrosiveBreath", "Spell_Nature_CrystalBall", "Spell_Nature_Cyclone", "Spell_Nature_Drowsy",
"Spell_Nature_DryadDispelMagic", "Spell_Nature_EarthBind", "Spell_Nature_EarthBindTotem", "Spell_Nature_Earthquake",
"Spell_Nature_EarthShock", "Spell_Nature_EnchantArmor", "Spell_Nature_FaerieFire", "Spell_Nature_FarSight",
"Spell_Nature_ForceOfNature", "Spell_Nature_GuardianWard", "Spell_Nature_HealingTouch", "Spell_Nature_HealingWaveGreater",
"Spell_Nature_HealingWaveLesser","Spell_Nature_InvisibilityTotem", "Spell_Nature_Invisibilty", "Spell_Nature_Lightning",
"Spell_Nature_LightningBolt","Spell_Nature_LightningShield", "Spell_Nature_MagicImmunity", "Spell_Nature_ManaRegenTotem",
"Spell_Nature_MassTeleport","Spell_Nature_MirrorImage", "Spell_Nature_MoonGlow", "Spell_Nature_MoonKey",
"Spell_Nature_NaturesBlessing", "Spell_Nature_NaturesWrath", "Spell_Nature_NatureTouchDecay", "Spell_Nature_NatureTouchGrow",
"Spell_Nature_NullifyDisease", "Spell_Nature_NullifyPoison", "Spell_Nature_NullifyPoison_02", "Spell_Nature_NullWard",
"Spell_Nature_Polymorph", "Spell_Nature_Preservation", "Spell_Nature_ProtectionformNature", "Spell_Nature_Purge",
"Spell_Nature_RavenForm", "Spell_Nature_Regenerate", "Spell_Nature_Regeneration", "Spell_Nature_Reincarnation",
"Spell_Nature_Rejuvenation","Spell_Nature_RemoveCurse", "Spell_Nature_RemoveDisease", "Spell_Nature_ResistMagic",
"Spell_Nature_ResistNature", "Spell_Nature_RockBiter", "Spell_Nature_Sentinal", "Spell_Nature_Sleep",
"Spell_Nature_Slow", "Spell_Nature_SlowingTotem", "Spell_Nature_SlowPoison","Spell_Nature_SpiritArmor",
"Spell_Nature_SpiritWolf", "Spell_Nature_StarFall", "Spell_Nature_StoneClawTotem", "Spell_Nature_StoneSkinTotem",
"Spell_Nature_StrangleVines", "Spell_Nature_Strength", "Spell_Nature_StrengthOfEarthTotem02","Spell_Nature_Swiftness",
"Spell_Nature_Thorns", "Spell_Nature_ThunderClap", "Spell_Nature_TimeStop","Spell_Nature_Tranquility",
"Spell_Nature_UndyingStrength", "Spell_Nature_UnyeildingStamina", "Spell_Nature_Web", "Spell_Nature_Windfury",
"Spell_Nature_WispHeal", "Spell_Nature_WispSplode", "Spell_Shadow_AbominationExplosion","Spell_Shadow_AnimateDead",
"Spell_Shadow_AntiMagicShell", "Spell_Shadow_AntiShadow","Spell_Shadow_AuraOfDarkness", "Spell_Shadow_BlackPlague",
"Spell_Shadow_BloodBoil", "Spell_Shadow_BurningSpirit", "Spell_Shadow_CallofBone","Spell_Shadow_CarrionSwarm",
"Spell_Shadow_Charm", "Spell_Shadow_ChillTouch", "Spell_Shadow_Contagion", "Spell_Shadow_CorpseExplode",
"Spell_Shadow_CreepingPlague","Spell_Shadow_Cripple", "Spell_Shadow_Curse", "Spell_Shadow_CurseOfAchimonde",
"Spell_Shadow_CurseOfMannoroth","Spell_Shadow_CurseOfSargeras", "Spell_Shadow_CurseOfTounges", "Spell_Shadow_DarkRitual",
"Spell_Shadow_DarkSummoning",
"Spell_Shadow_DeadofNight", "Spell_Shadow_DeathAndDecay", "Spell_Shadow_DeathCoil", "Spell_Shadow_DeathPact",
"Spell_Shadow_DeathScream", "Spell_Shadow_DemonBreath", "Spell_Shadow_DetectInvisibility", "Spell_Shadow_DetectLesserInvisibility",
"Spell_Shadow_EnslaveDemon", "Spell_Shadow_EvilEye", "Spell_Shadow_FingerOfDeath", "Spell_Shadow_Fumble",
"Spell_Shadow_GatherShadows", "Spell_Shadow_GhostKey", "Spell_Shadow_GrimWard", "Spell_Shadow_Haunting",
"Spell_Shadow_ImpPhaseShift", "Spell_Shadow_LifeDrain", "Spell_Shadow_LifeDrain02", "Spell_Shadow_ManaBurn",
"Spell_Shadow_Metamorphosis", "Spell_Shadow_MindBomb", "Spell_Shadow_MindRot", "Spell_Shadow_MindSteal",
"Spell_Shadow_NightOfTheDead", "Spell_Shadow_PlagueCloud", "Spell_Shadow_Possession", "Spell_Shadow_PsychicScream",
"Spell_Shadow_RagingScream", "Spell_Shadow_RainOfFire", "Spell_Shadow_RaiseDead", "Spell_Shadow_Requiem",
"Spell_Shadow_RitualOfSacrifice", "Spell_Shadow_SacrificialShield", "Spell_Shadow_ScourgeBuild", "Spell_Shadow_SealOfKings",
"Spell_Shadow_ShadeTrueSight", "Spell_Shadow_ShadowBolt", "Spell_Shadow_Shadowform", "Spell_Shadow_ShadowPact",
"Spell_Shadow_ShadowWard", "Spell_Shadow_ShadowWordDominate", "Spell_Shadow_ShadowWordPain", "Spell_Shadow_SiphonMana",
"Spell_Shadow_SoothingKiss", "Spell_Shadow_SoulGem", "Spell_Shadow_SpectralSight", "Spell_Shadow_SummonFelHunter",
"Spell_Shadow_SummonImp", "Spell_Shadow_SummonInfernal", "Spell_Shadow_SummonSuccubus", "Spell_Shadow_SummonVoidWalker",
"Spell_Shadow_Teleport", "Spell_Shadow_Twilight", "Spell_Shadow_UnholyFrenzy", "Spell_Shadow_UnholyStrength",
"Spell_Shadow_UnsummonBuilding", "Spell_Shadow_VampiricAura", "Spell_Totem_WardOfDraining", "Trade_Alchemy",
"Trade_BlackSmithing", "Trade_BrewPoison", "Trade_Engineering", "Trade_Engraving",
"Trade_Fishing", "Trade_Herbalism", "Trade_LeatherWorking", "Trade_Mining", "Trade_Tailoring",
"INV_Banner_01", "INV_Banner_02", "INV_Banner_03", "INV_Box_01", "INV_Box_02","INV_Box_03", "INV_Box_01",
"INV_Box_Birdcage_01", "INV_Box_PetCarrier_01", "INV_Cask_01", "INV_Cask_02", "INV_Cask_03", "INV_Cask_04",
"INV_Crate_01", "INV_Crate_02", "INV_Crate_03", "INV_Crate_04", "INV_Crate_05", "INV_Crate_06", 
"INV_Drink_01", "INV_Drink_02", "INV_Drink_03", "INV_Drink_04", "INV_Drink_05", "INV_Drink_06", "INV_Drink_07",
"INV_Drink_08", "INV_Drink_09", "INV_Drink_10", "INV_Drink_11", "INV_Drink_12", "INV_Drink_13", "INV_Drink_14",
"INV_Drink_15", "INV_Drink_16", "INV_Drink_17", "INV_Drink_18", "INV_Drink_19",
"INV_Drink_Milk_01", "INV_Drink_Milk_02", "INV_Drink_Milk_03", "INV_Drink_Milk_04", "INV_Drink_Milk_05",
"INV_Gizmo_01", "INV_Gizmo_02", "INV_Gizmo_03", "INV_Gizmo_04", "INV_Gizmo_05", "INV_Gizmo_06", "INV_Gizmo_07",
"INV_Gizmo_08", "INV_Gizmo_09", "INV_Gizmo_RocketBoot_01",
"INV_Helmet_02", "INV_Helmet_03", "INV_Helmet_04", "INV_Helmet_05", "INV_Helmet_06", "INV_Helmet_44", "INV_Helmet_47", "INV_Helmet_49",
"INV_Jewelry_Amulet_03", "INV_Mask_01", "INV_Mask_02",
"INV_Letter_01", "INV_Letter_02", "INV_Letter_03", "INV_Letter_04", "INV_Letter_05", "INV_Letter_06", "INV_Letter_07",
"INV_Letter_08", "INV_Letter_09", "INV_Letter_10", "INV_Letter_11", "INV_Letter_12", "INV_Letter_13", "INV_Letter_14",
"INV_Letter_15", "INV_Letter_16", "INV_Letter_17", "INV_Misc_Foot_Centaur", "INV_Misc_Foot_Kodo",
"INV_Misc_Gear_01", "INV_Misc_Gear_02", "INV_Misc_Gear_03", "INV_Misc_Gear_04", "INV_Misc_Gear_05", "INV_Misc_Gear_06", "INV_Misc_Gear_07",
"INV_Misc_Gear_08", "INV_Misc_Gift_01", "INV_Misc_Gift_02", "INV_Misc_Gift_03", "INV_Misc_Gift_04", "INV_Misc_Gift_05",
"INV_Misc_Note_01", "INV_Misc_Note_02", "INV_Misc_Note_03", "INV_Misc_Note_04", "INV_Misc_Note_05", "INV_Misc_Note_06",
"INV_Misc_Orb_01", "INV_Misc_Orb_02", "INV_Misc_Orb_03", "INV_Misc_Orb_04", "INV_Misc_Orb_05"
};
EmoteButtons_ImageCount = getn(EmoteButtons_ImageList);