NurfedDKPPlayers = {
	["Valdez"] = {
		["rank"] = 1,
		["dkp"] = 143.047,
		["class"] = "Rogue",
		["att"] = 100.0,
	},
	["Brujaa"] = {
		["rank"] = 2,
		["dkp"] = 142.040,
		["class"] = "Shaman",
		["att"] = 76.5,
	},
	["Tivoli"] = {
		["rank"] = 3,
		["dkp"] = 136.304,
		["class"] = "Priest",
		["att"] = 100.0,
	},
	["Suarez"] = {
		["rank"] = 4,
		["dkp"] = 131.826,
		["class"] = "Shaman",
		["att"] = 85.3,
	},
	["Xyno"] = {
		["rank"] = 5,
		["dkp"] = 119.626,
		["class"] = "Warrior",
		["att"] = 100.0,
	},
	["Nastrand"] = {
		["rank"] = 6,
		["dkp"] = 104.479,
		["class"] = "Warrior",
		["att"] = 100.0,
	},
	["Urobulol"] = {
		["rank"] = 7,
		["dkp"] = 95.587,
		["class"] = "Warrior",
		["att"] = 64.7,
	},
	["Noktyn"] = {
		["dkp"] = 86.226,
		["class"] = "Warrior",
		["att"] = 41.2,
	},
	["Balroc"] = {
		["dkp"] = 83.102,
		["class"] = "Shaman",
		["att"] = 23.5,
	},
	["Orgg"] = {
		["rank"] = 8,
		["dkp"] = 81.824,
		["class"] = "Rogue",
		["att"] = 64.7,
	},
	["Predtr"] = {
		["dkp"] = 72.735,
		["class"] = "Hunter",
		["att"] = 17.6,
	},
	["Psylynt"] = {
		["rank"] = 9,
		["dkp"] = 61.716,
		["class"] = "Priest",
		["att"] = 94.1,
	},
	["Nisstyr"] = {
		["rank"] = 10,
		["dkp"] = 60.554,
		["class"] = "Warlock",
		["att"] = 55.9,
	},
	["Nulil"] = {
		["rank"] = 11,
		["dkp"] = 52.629,
		["class"] = "Priest",
		["att"] = 73.5,
	},
	["Savorz"] = {
		["rank"] = 12,
		["dkp"] = 46.373,
		["class"] = "Mage",
		["att"] = 100.0,
	},
	["Demiz"] = {
		["dkp"] = 45.160,
		["class"] = "Priest",
		["att"] = 35.3,
	},
	["Vhellol"] = {
		["rank"] = 13,
		["dkp"] = 45.085,
		["class"] = "Priest",
		["att"] = 70.6,
	},
	["Ziot"] = {
		["rank"] = 14,
		["dkp"] = 33.586,
		["class"] = "Mage",
		["att"] = 67.6,
	},
	["Evilution"] = {
		["rank"] = 15,
		["dkp"] = 31.065,
		["class"] = "Shaman",
		["att"] = 76.5,
	},
	["Frizzo"] = {
		["rank"] = 16,
		["dkp"] = 29.404,
		["class"] = "Rogue",
		["att"] = 64.7,
	},
	["Trixxz"] = {
		["rank"] = 17,
		["dkp"] = 27.202,
		["class"] = "Warlock",
		["att"] = 76.5,
	},
	["Fisteena"] = {
		["rank"] = 18,
		["dkp"] = 21.766,
		["class"] = "Druid",
		["att"] = 94.1,
	},
	["Sintourr"] = {
		["dkp"] = 21.268,
		["class"] = "Hunter",
		["att"] = 23.5,
	},
	["Ayrez"] = {
		["rank"] = 19,
		["dkp"] = 18.764,
		["class"] = "Warrior",
		["att"] = 67.6,
	},
	["Epidermik"] = {
		["dkp"] = 17.045,
		["class"] = "Priest",
		["att"] = 29.4,
	},
	["Scorchy"] = {
		["dkp"] = 16.701,
		["class"] = "Druid",
		["att"] = 29.4,
	},
	["Calaio"] = {
		["dkp"] = 14.061,
		["class"] = "Shaman",
		["att"] = 32.4,
	},
	["Alvarez"] = {
		["rank"] = 20,
		["dkp"] = 5.935,
		["class"] = "Warrior",
		["att"] = 94.1,
	},
	["Naeadil"] = {
		["dkp"] = 4.000,
		["class"] = "Druid",
		["att"] = 23.5,
	},
	["Roddyrotten"] = {
		["dkp"] = 4.000,
		["class"] = "Warlock",
		["att"] = 26.5,
	},
	["Tangible"] = {
		["dkp"] = 2.000,
		["class"] = "Hunter",
		["att"] = 11.8,
	},
	["Benitez"] = {
		["dkp"] = 1.488,
		["class"] = "Warlock",
		["att"] = 23.5,
	},
	["Ashia"] = {
		["rank"] = 21,
		["dkp"] = -0.553,
		["class"] = "Mage",
		["att"] = 88.2,
	},
	["Kanchi"] = {
		["rank"] = 22,
		["dkp"] = -0.804,
		["class"] = "Mage",
		["att"] = 61.8,
	},
	["Mirargul"] = {
		["dkp"] = -3.621,
		["class"] = "Rogue",
		["att"] = 41.2,
	},
	["Awowa"] = {
		["dkp"] = -4.099,
		["class"] = "Mage",
		["att"] = 5.9,
	},
	["Souken"] = {
		["dkp"] = -5.263,
		["class"] = "Rogue",
		["att"] = 8.8,
	},
	["Jinzi"] = {
		["dkp"] = -6.179,
		["class"] = "Shaman",
		["att"] = 14.7,
	},
	["Halfscrub"] = {
		["rank"] = 23,
		["dkp"] = -7.216,
		["class"] = "Mage",
		["att"] = 97.1,
	},
	["Wil"] = {
		["rank"] = 24,
		["dkp"] = -8.233,
		["class"] = "Hunter",
		["att"] = 73.5,
	},
	["Altiods"] = {
		["rank"] = 25,
		["dkp"] = -9.351,
		["class"] = "Warlock",
		["att"] = 94.1,
	},
	["Gbyd"] = {
		["dkp"] = -9.745,
		["class"] = "Rogue",
		["att"] = 8.8,
	},
	["Zazzles"] = {
		["rank"] = 26,
		["dkp"] = -14.988,
		["class"] = "Druid",
		["att"] = 67.6,
	},
	["Mendez"] = {
		["rank"] = 27,
		["dkp"] = -25.139,
		["class"] = "Priest",
		["att"] = 100.0,
	},
	["Svartig"] = {
		["rank"] = 28,
		["dkp"] = -35.642,
		["class"] = "Mage",
		["att"] = 70.6,
	},
	["Tsuruchi"] = {
		["dkp"] = -35.995,
		["class"] = "Hunter",
		["att"] = 2.9,
	},
	["Khb"] = {
		["rank"] = 29,
		["dkp"] = -38.577,
		["class"] = "Priest",
		["att"] = 61.8,
	},
	["Kaeto"] = {
		["rank"] = 30,
		["dkp"] = -40.149,
		["class"] = "Hunter",
		["att"] = 55.9,
	},
	["Morison"] = {
		["rank"] = 31,
		["dkp"] = -43.269,
		["class"] = "Shaman",
		["att"] = 50.0,
	},
	["Volkhar"] = {
		["rank"] = 32,
		["dkp"] = -45.126,
		["class"] = "Warrior",
		["att"] = 73.5,
	},
	["Cdthiten"] = {
		["dkp"] = -49.668,
		["class"] = "Druid",
		["att"] = 44.1,
	},
	["Drakkonn"] = {
		["rank"] = 33,
		["dkp"] = -50.483,
		["class"] = "Priest",
		["att"] = 52.9,
	},
	["Crouton"] = {
		["rank"] = 34,
		["dkp"] = -56.855,
		["class"] = "Priest",
		["att"] = 55.9,
	},
	["Socratic"] = {
		["rank"] = 35,
		["dkp"] = -58.160,
		["class"] = "Warrior",
		["att"] = 85.3,
	},
	["Kaisy"] = {
		["dkp"] = -64.261,
		["class"] = "Shaman",
		["att"] = 41.2,
	},
	["Scorpoo"] = {
		["rank"] = 36,
		["dkp"] = -69.778,
		["class"] = "Hunter",
		["att"] = 58.8,
	},
	["Saqen"] = {
		["rank"] = 37,
		["dkp"] = -76.463,
		["class"] = "Priest",
		["att"] = 91.2,
	},
	["Waldoric"] = {
		["rank"] = 38,
		["dkp"] = -79.995,
		["class"] = "Rogue",
		["att"] = 58.8,
	},
	["Bhaltair"] = {
		["rank"] = 39,
		["dkp"] = -92.205,
		["class"] = "Warlock",
		["att"] = 97.1,
	},
	["Inalende"] = {
		["rank"] = 40,
		["dkp"] = -107.319,
		["class"] = "Druid",
		["att"] = 55.9,
	},
	["Fennesz"] = {
		["rank"] = 41,
		["dkp"] = -109.140,
		["class"] = "Rogue",
		["att"] = 50.0,
	},
	["Cynapse"] = {
		["rank"] = 42,
		["dkp"] = -115.287,
		["class"] = "Shaman",
		["att"] = 88.2,
	},
	["Pheryl"] = {
		["rank"] = 43,
		["dkp"] = -128.584,
		["class"] = "Hunter",
		["att"] = 55.9,
	},
	["Indalamar"] = {
		["dkp"] = -137.375,
		["class"] = "Warrior",
		["att"] = 8.8,
	},
}