if (GetLocale() == "zhCN") then

-- Shaman
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "次级治疗波";
QUICKHEAL_SPELL_HEALING_WAVE = "治疗波";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = '次级治疗术';
QUICKHEAL_SPELL_HEAL = '治疗术';
QUICKHEAL_SPELL_GREATER_HEAL = '强效治疗术';
QUICKHEAL_SPELL_FLASH_HEAL = '快速治疗';

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = '圣光术';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = '圣光闪现';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = '治疗之触';
QUICKHEAL_SPELL_REGROWTH = '愈合';

end