-- Shaman
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "Lesser Healing Wave";
QUICKHEAL_SPELL_HEALING_WAVE = "Healing Wave";
QUICKHEAL_SPELL_CHAIN_HEAL = "Chain Heal";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = 'Lesser Heal';
QUICKHEAL_SPELL_HEAL = 'Heal';
QUICKHEAL_SPELL_GREATER_HEAL = 'Greater Heal';
QUICKHEAL_SPELL_FLASH_HEAL = 'Flash Heal';
QUICKHEAL_SPELL_RENEW = 'Renew';
QUICKHEAL_SPELL_PWS = "Power Word: Shield";

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = 'Holy Light';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = 'Flash of Light';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = 'Healing Touch';
QUICKHEAL_SPELL_REGROWTH = 'Regrowth';
QUICKHEAL_SPELL_REJUVENATION = 'Rejuvenation';