if (GetLocale() == "zhTW") then

-- Shaman
QUICKHEAL_SPELL_LESSER_HEALING_WAVE = "次級治療波";
QUICKHEAL_SPELL_HEALING_WAVE = "治療波";

-- Priest
QUICKHEAL_SPELL_LESSER_HEAL = '次級治療術';
QUICKHEAL_SPELL_HEAL = '治療術';
QUICKHEAL_SPELL_GREATER_HEAL = '強效治療術';
QUICKHEAL_SPELL_FLASH_HEAL = '快速治療';

-- Paladin
QUICKHEAL_SPELL_HOLY_LIGHT = '聖光術';
QUICKHEAL_SPELL_FLASH_OF_LIGHT = '聖光閃現';

-- Druid
QUICKHEAL_SPELL_HEALING_TOUCH = '治療之觸';
QUICKHEAL_SPELL_REGROWTH = '癒合';

end
