
Zorlen_DE_FileBuildNumber = 687

-- German Translation
-- If you want to translate this to another language, make sure the names of buffs and abilities are *EXACTLY* the same as in-game. Spelling, punctuation, upper/lowercase letters, etc. MUST BE EXACT. Also, any 'foreign' characters must be converted to UNICODE.
-- Unicode resource:
-- http://www.utf8-chartable.de/unicode-utf8-table.pl?start=128&number=1024&utf8=dec
-- http://home.tiscali.nl/t876506/utf8tbl.html
-- http://www.allegro-c.de/unicode/zcodes.htm
-- You will need to use the UTF-8 decimal numbers with a back slash in front of them in the same way that Å is represented by: \195\133


-- To lower the upkeep we will not be adding Localization for english words that do not break compatibility in other game clients.
-- This Localization is only added for compatibility so that it may work in non english game clients and not as a translation.

if GetLocale() ~= "deDE" then return end

-- All file Localization
	--LOCALIZATION_ZORLEN["EatMacroName"] = ""
	--LOCALIZATION_ZORLEN["DrinkMacroName"] = ""
	--LOCALIZATION_ZORLEN["Conjured"] = ""
	--LOCALIZATION_ZORLEN["Water"] = ""
	--LOCALIZATION_ZORLEN["AllConjuredWater"] = ""
	--LOCALIZATION_ZORLEN["well_fed"] = ""
	LOCALIZATION_ZORLEN["HitsOrCritsArray"] = {"^(.+) von Euch trifft (.*) f\195\188r (%d+)", "^(.+) trifft (.*). Schaden: (%d+)", "^(.+) trifft (.*) kritisch: (%d+)", "Euer (.+) trifft (.*) kritisch f\195\188r (%d+)", "Euer (.+) trifft (.*) f\195\188r (%d+)"}
	LOCALIZATION_ZORLEN["EnemyDies"] = "(.*)"
	LOCALIZATION_ZORLEN["Rank"] = "Rang"
	LOCALIZATION_ZORLEN["sit"] = "sitzen"
	LOCALIZATION_ZORLEN["You_dodge"] = "Ausgewichen"
	LOCALIZATION_ZORLEN["ImmuneArray"] = {"^(.+) war ein Fehlschlag. (.*) ist immun."}
	LOCALIZATION_ZORLEN["no_weapons_equipped"] = "(.+).*Keine Waffen angelegt"
	LOCALIZATION_ZORLEN["dodged"] = "Pariert"
	--LOCALIZATION_ZORLEN["dodges"] = ""
	LOCALIZATION_ZORLEN["pet_is_not_dead"] = "Euer Begleiter ist nicht tot"
	LOCALIZATION_ZORLEN["pet_is_dead"] = "Euer Begleiter ist tot"
	LOCALIZATION_ZORLEN["You fail to perform (.+): A more powerful spell is already active."] = "(.+).*Ein m\195\164chtigerer Spruch ist bereits aktiv"
	--LOCALIZATION_ZORLEN["Asleep"] = ""
	LOCALIZATION_ZORLEN["RequiresLevel"] = "Ben\195\182tigt Stufe"
	
	--LOCALIZATION_ZORLEN["GreaterHealingWard"] = ""
	--LOCALIZATION_ZORLEN["LavaSpoutTotem"] = ""
	
	LOCALIZATION_ZORLEN["HealingBonusWordsArray"] = {"Heilung", "Heilzauber"}
	LOCALIZATION_ZORLEN["HealingBonusPhraseArray"] = {"Erh\195\131\194\182ht durch Zauber und Effekte verursachte Heilung um bis zu (%d+)%.", "Erh\195\131\194\182ht die durch Zauber und Effekte verursachte Heilung um bis zu (%d+)%."}
	
	LOCALIZATION_ZORLEN["SpellDamageAndHealingBonusWordsArray"] = {"Heilung und Zauberschaden", "Zauberschaden und Heilung"}
	LOCALIZATION_ZORLEN["SpellDamageAndHealingBonusPhraseArray"] = {"Erh\195\131\194\182ht durch Zauber und magische Effekte zugef\195\131\194\188gten Schaden und Heilung um bis zu (%d+)%."}
	
	LOCALIZATION_ZORLEN["SpellDamageBonusWordsArray"] = {"Zauberschaden", "Zauberschaden erh\195\131\194\182hen"}
	LOCALIZATION_ZORLEN["SpellDamageBonusPhraseArray"] = {}
	LOCALIZATION_ZORLEN["BrilliantWizardOil"] = "Hervorragendes Zauber\195\131\194\182l"
	LOCALIZATION_ZORLEN["WizardOil"] = "Zauber\195\131\194\182l"
	LOCALIZATION_ZORLEN["LesserWizardOil"] = "Geringes Zauber\195\131\194\182l"
	LOCALIZATION_ZORLEN["MinorWizardOil"] = "Schwaches Zauber\195\131\194\182l"
	--LOCALIZATION_ZORLEN["SupremePower"] = ""
	--LOCALIZATION_ZORLEN["GreaterArcaneElixir"] = ""
	LOCALIZATION_ZORLEN["ArcaneElixir"] = "Arkanes Elixier"
	
	LOCALIZATION_ZORLEN["ShadowDamageBonusWordsArray"] = {"Schattenschaden"}
	LOCALIZATION_ZORLEN["ShadowDamageBonusPhraseArray"] = {}
	--LOCALIZATION_ZORLEN["ShadowPower"] = ""
	
-- Battleground Names
	--LOCALIZATION_ZORLEN["WarsongGulch"] = ""
	--LOCALIZATION_ZORLEN["AlteracValley"] = ""
	--LOCALIZATION_ZORLEN["ArathiBasin"] = ""
	
-- Raid Target Names
	LOCALIZATION_ZORLEN["WhiteSkull"] = "Wei\195\159er Totenkopf"
	LOCALIZATION_ZORLEN["RedX"] = "Rotes X"
	LOCALIZATION_ZORLEN["BlueSquare"] = "Blaues Quadrat"
	LOCALIZATION_ZORLEN["WhiteCrescentMoon"] = "Wei\195\159er Sichelf\195\182rmiger Mond"
	LOCALIZATION_ZORLEN["GreenTriangle"] = "Gruenes Dreieck"
	LOCALIZATION_ZORLEN["PurpleDiamond"] = "Violetter Diamant"
	LOCALIZATION_ZORLEN["OrangeCircle"] = "Orangener Kreis"
	LOCALIZATION_ZORLEN["YellowStar"] = "Gelber Stern"

-- Example: /script Zorlen_GiveName_OffHandType()
-- The example above will give the name required for ["Shields
-- You must have a shield equipped to get the correct name.
-- You can also get the correct name from the auction house filters under the Armor section.
	LOCALIZATION_ZORLEN["Shields"] = "Schilde"
	
-- Example: /script Zorlen_GiveName_MainHandType()
-- The example above will give the name required for the weapons below.
-- You must have the weapon equipped to get the correct name.
-- You can also get the correct names from the auction house filters under the Weapon section.
	LOCALIZATION_ZORLEN["Daggers"] = "Dolch"
	LOCALIZATION_ZORLEN["One-Handed Swords"] = "Schwert"
	LOCALIZATION_ZORLEN["Two-Handed Swords"] = "Zweihandschwert"
	LOCALIZATION_ZORLEN["One-Handed Axes"] = "Axt"
	LOCALIZATION_ZORLEN["Two-Handed Axes"] = "Zweihandaxt"
	LOCALIZATION_ZORLEN["One-Handed Maces"] = "Streitkolben"
	LOCALIZATION_ZORLEN["Two-Handed Maces"] = "Zweihandstreitkolben"
	LOCALIZATION_ZORLEN["Polearms"] = "Stangenwaffe"
	LOCALIZATION_ZORLEN["Staves"] = "Stab"
	LOCALIZATION_ZORLEN["Fist Weapons"] = "Faustwaffe"
	LOCALIZATION_ZORLEN["Fishing Pole"] = "Angel"

-- Item Sub Types:
	--LOCALIZATION_ZORLEN["Bag"] = ""
	--LOCALIZATION_ZORLEN["Soul Bag"] = ""


-- Food Item Tool Tip Text:
	--LOCALIZATION_ZORLEN["FoodToolTipTextAny"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText3180"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText2148"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText1392"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText874"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText552"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText243"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText61"] = ""
-- Drink Item Tool Tip Text:
	--LOCALIZATION_ZORLEN["DrinkToolTipTextAny"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText4200"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText2934"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText1992"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText1344"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText835"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText436"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText151"] = ""



-- Zorlen_Other.lua file Localization
	LOCALIZATION_ZORLEN["Attack"] = "Angreifen"
	LOCALIZATION_ZORLEN["Throw"] = "Wurf"
	--LOCALIZATION_ZORLEN["ShootBow"] = ""
	--LOCALIZATION_ZORLEN["ShootCrossbow"] = ""
	--LOCALIZATION_ZORLEN["ShootGun"] = ""
	LOCALIZATION_ZORLEN["Shoot"] = "Schie\195\159en"
-- Human Racial
	LOCALIZATION_ZORLEN["Perception"] = "Wachsamkeit"
-- Dwarf Racial
	LOCALIZATION_ZORLEN["FindTreasure"] = "Schatzsucher"
	LOCALIZATION_ZORLEN["Stoneform"] = "Steingestalt"
-- Gnome Racial
	LOCALIZATION_ZORLEN["EscapeArtist"] = "Entfesselungsk\195\188nstler"
-- Night Elf Racial
	LOCALIZATION_ZORLEN["Shadowmeld"] = "Schattenhaftigkeit"
-- Orc Racial
	LOCALIZATION_ZORLEN["BloodFury"] = "Kochendes Blut"
-- Undead Racial
	LOCALIZATION_ZORLEN["Cannibalize"] = "Kannibalismus"
	LOCALIZATION_ZORLEN["WillOfTheForsaken"] = "Wille der Verlassenen"
-- Tauren Racial
	LOCALIZATION_ZORLEN["WarStomp"] = "Kriegsdonner"
-- Troll Racial
	LOCALIZATION_ZORLEN["Berserking"] = "Berserker"



-- Zorlen_Pets.lua file Localization
-- Hunter Pets
	LOCALIZATION_ZORLEN["Dash"] = "Spurt"
	LOCALIZATION_ZORLEN["Dive"] = "Sturzflug"
	LOCALIZATION_ZORLEN["Bite"] = "Bei\195\159en"
	LOCALIZATION_ZORLEN["Claw"] = "Klaue"
	LOCALIZATION_ZORLEN["Cower"] = "Ducken"
	LOCALIZATION_ZORLEN["Growl"] = "Knurren"
	LOCALIZATION_ZORLEN["Prowl"] = "Schleichen"
	LOCALIZATION_ZORLEN["Charge"] = "Sturmangriff"
	LOCALIZATION_ZORLEN["Screech"] = "Schrei"
	LOCALIZATION_ZORLEN["FuriousHowl"] = "Wutgeheul"
	LOCALIZATION_ZORLEN["LightningBreath"] = "Blitzschlagatem"
	LOCALIZATION_ZORLEN["ShellShield"] = "Panzerschild"
	LOCALIZATION_ZORLEN["Thunderstomp"] = "Donnerstampfer"
	LOCALIZATION_ZORLEN["ScorpidPoison"] = "Scorpidgift"
-- Warlock Pets
	LOCALIZATION_ZORLEN["Felhunter"] = "Teufelsj\195\164ger"
	LOCALIZATION_ZORLEN["Imp"] = "Wichtel"
	LOCALIZATION_ZORLEN["Succubus"] = "Succubus"
	LOCALIZATION_ZORLEN["Voidwalker"] = "Leerwandler"
	LOCALIZATION_ZORLEN["BloodPact"] = "Blutpakt"
	LOCALIZATION_ZORLEN["FireShield"] = "Feuerschild"
	LOCALIZATION_ZORLEN["Firebolt"] = "Feuerblitz"
	LOCALIZATION_ZORLEN["PhaseShift"] = "Phasenverschiebung"
	LOCALIZATION_ZORLEN["ConsumeShadows"] = "Schatten verzehren"
	LOCALIZATION_ZORLEN["Sacrifice"] = "Opferung"
	LOCALIZATION_ZORLEN["Suffering"] = "Leiden"
	LOCALIZATION_ZORLEN["Torment"] = "Qual"
	LOCALIZATION_ZORLEN["DevourMagic"] = "Magie verzehren"
	LOCALIZATION_ZORLEN["Paranoia"] = "Paranoia"
	LOCALIZATION_ZORLEN["SpellLock"] = "Zaubersperre"
	LOCALIZATION_ZORLEN["TaintedBlood"] = "Besudeltes Blut"
	LOCALIZATION_ZORLEN["LashOfPain"] = "Schmerzenspeitsche"
	LOCALIZATION_ZORLEN["Seduction"] = "Verf\195\188hrung"
	LOCALIZATION_ZORLEN["SoothingKiss"] = "Bes\195\164nftigender Kuss"
	LOCALIZATION_ZORLEN["LesserInvisibility"] = "Geringe Unsichtbarkeit"



-- Zorlen_Hunter.lua file Localization
	--LOCALIZATION_ZORLEN["FeedPet"] = ""
	LOCALIZATION_ZORLEN["ImprovedAspectOfTheHawk"] = "Verbesserte Aspekt des Falken"
	LOCALIZATION_ZORLEN["ImprovedMendPet"] = "Verbesserte Tier heilen"
	LOCALIZATION_ZORLEN["MendPet"] = "Tier heilen"
	LOCALIZATION_ZORLEN["CallPet"] = "Tier rufen"
	LOCALIZATION_ZORLEN["RevivePet"] = "Tier wiederbeleben"
	LOCALIZATION_ZORLEN["DismissPet"] = "Tier freigeben"
	LOCALIZATION_ZORLEN["AutoShot"] = "Automatischer Schuss"
	LOCALIZATION_ZORLEN["MongooseBite"] = "Mungobiss"
	LOCALIZATION_ZORLEN["ArcaneShot"] = "Arkaner Schuss"
	LOCALIZATION_ZORLEN["ConcussiveShot"] = "Ersch\195\188tternder Schuss"
	LOCALIZATION_ZORLEN["RaptorStrike"] = "Raptorsto\195\159"
	LOCALIZATION_ZORLEN["SerpentSting"] = "Schlangenbiss"
	LOCALIZATION_ZORLEN["ViperSting"] = "Vipernbiss"
	LOCALIZATION_ZORLEN["ScorpidSting"] = "Skorpidstich"
	LOCALIZATION_ZORLEN["DistractingShot"] = "Ablenkender Schuss"
	LOCALIZATION_ZORLEN["AimedShot"] = "Gezielter Schuss"
	LOCALIZATION_ZORLEN["HuntersMark"] = "Mal des J\195\164gers"
	LOCALIZATION_ZORLEN["AspectOfTheHawk"] = "Aspekt des Falken"
	LOCALIZATION_ZORLEN["AspectOfTheMonkey"] = "Aspekt des Affen"
	LOCALIZATION_ZORLEN["AspectOfTheCheetah"] = "Aspekt des Geparden"
	LOCALIZATION_ZORLEN["AspectOfThePack"] = "Aspekt des Rudels"
	LOCALIZATION_ZORLEN["AspectOfTheWild"] = "Aspekt der Wildniss"
	LOCALIZATION_ZORLEN["AspectOfTheBeast"] = "Aspekt des Wildtieres"
	LOCALIZATION_ZORLEN["WingClip"] = "Zurechtstutzen"
	LOCALIZATION_ZORLEN["FreezingTrap"] = "Eisk\195\164ltefalle"
	LOCALIZATION_ZORLEN["FrostTrap"] = "Frostfalle"
	LOCALIZATION_ZORLEN["ExplosiveTrap"] = "Sprengfalle"
	LOCALIZATION_ZORLEN["ImmolationTrap"] = "Feuerbrandfalle"
	LOCALIZATION_ZORLEN["FeignDeath"] = "Totstellen"
	LOCALIZATION_ZORLEN["Counterattack"] = "Gegenangriff"
	LOCALIZATION_ZORLEN["TranquilizingShot"] = "Einlullender Schuss"
	LOCALIZATION_ZORLEN["Disengage"] = "R\195\188ckzug"
	LOCALIZATION_ZORLEN["EyesOfTheBeast"] = "Augen des Wildtiers"
	LOCALIZATION_ZORLEN["BeastLore"] = "Wildtierkunde"
	LOCALIZATION_ZORLEN["TrackBeasts"] = "Wildtiere aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackDemons"] = "D\195\164monen aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackDragonkin"] = "Drachkin aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackElementals"] = "Elementare aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackGiants"] = "Riesen aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackHumanoids"] = "Humanoide aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackUndead"] = "Untote aufsp\195\188ren"
	LOCALIZATION_ZORLEN["TrackHidden"] = "Verborgenes aufsp\195\188ren"
	LOCALIZATION_ZORLEN["BestialWrath"] = "Zorn des Wildtiers"
	LOCALIZATION_ZORLEN["TrueshotAura"] = "Aura des Volltreffers"
	LOCALIZATION_ZORLEN["ScatterShot"] = "Streuschuss"
	LOCALIZATION_ZORLEN["WyvernSting"] = "Stich des Fl\195\188geldrachen"
	LOCALIZATION_ZORLEN["Deterrence"] = "Abschreckung"
	LOCALIZATION_ZORLEN["EagleEye"] = "Adlerauge"
	LOCALIZATION_ZORLEN["RapidFire"] = "Schnellfeuer"
	LOCALIZATION_ZORLEN["MultiShot"] = "Mehrfachschuss"
	LOCALIZATION_ZORLEN["Flare"] = "Leuchtfeuer"
	LOCALIZATION_ZORLEN["ScareBeast"] = "Wildtier \195\164ngstigen"
	LOCALIZATION_ZORLEN["Volley"] = "Salve"
	LOCALIZATION_ZORLEN["Intimidation"] = "Einsch\195\188chterung"



-- Zorlen_Warlock.lua file Localization
	--LOCALIZATION_ZORLEN["SoulSiphon"] = ""
	--LOCALIZATION_ZORLEN["SeedOfCorruption"] = ""
	--LOCALIZATION_ZORLEN["FelArmor"] = ""
	--LOCALIZATION_ZORLEN["RitualOfSouls"] = ""
	--LOCALIZATION_ZORLEN["Soulshatter"] = ""
	--LOCALIZATION_ZORLEN["Incinerate"] = ""
	--LOCALIZATION_ZORLEN["UnstableAffliction"] = ""
	--LOCALIZATION_ZORLEN["DemonicAegis"] = ""
	--LOCALIZATION_ZORLEN["SummonFelGuard"] = ""
	--LOCALIZATION_ZORLEN["Shadowfury"] = ""
	
	--LOCALIZATION_ZORLEN["Bane"] = ""
	LOCALIZATION_ZORLEN["AmplifyCurse"] = "Fluch verst\195\164rken"
	LOCALIZATION_ZORLEN["CurseOfAgony"] = "Fluch der Pein"
	LOCALIZATION_ZORLEN["CurseOfDoom"] = "Fluch der Verdammnis"
	LOCALIZATION_ZORLEN["CurseOfShadow"] = "Fluch der Schatten"
	LOCALIZATION_ZORLEN["CurseOfTheElements"] = "Fluch der Elemente"
	LOCALIZATION_ZORLEN["CurseOfWeakness"] = "Fluch der Schw\195\164che"
	LOCALIZATION_ZORLEN["CurseOfExhaustion"] = "Fluch der Ersch\195\182pfung"
	LOCALIZATION_ZORLEN["CurseOfRecklessness"] = "Fluch der Tollk\195\188hnheit"
	LOCALIZATION_ZORLEN["CurseOfTongues"] = "Fluch der Sprachen"
	LOCALIZATION_ZORLEN["Corruption"] = "Verderbnis"
	LOCALIZATION_ZORLEN["ImprovedCorruption"] = "Verbesserte Verderbnis"
	LOCALIZATION_ZORLEN["Immolate"] = "Feuerbrand"
	LOCALIZATION_ZORLEN["SiphonLife"] = "Lebensentzug"
	LOCALIZATION_ZORLEN["DrainLife"] = "Blutsauger"
	LOCALIZATION_ZORLEN["DrainMana"] = "Mana entziehen"
	LOCALIZATION_ZORLEN["Hellfire"] = "H\195\182llenfeuer"
	LOCALIZATION_ZORLEN["RainOfFire"] = "Feuerregen"
	LOCALIZATION_ZORLEN["DrainSoul"] = "Seelendieb"
	LOCALIZATION_ZORLEN["LifeTap"] = "Aderlass"
	LOCALIZATION_ZORLEN["ImprovedLifeTap"] = "Verbesserter Aderlass"
	LOCALIZATION_ZORLEN["DarkPact"] = "Dunkler Pakt"
	LOCALIZATION_ZORLEN["Nightfall"] = "Einbruch der Nacht"
	LOCALIZATION_ZORLEN["ShadowBolt"] = "Schattenblitz"
	LOCALIZATION_ZORLEN["Banish"] = "Verbannen"
	LOCALIZATION_ZORLEN["Conflagrate"] = "Feuersbrunst"
	LOCALIZATION_ZORLEN["CreateFirestoneLesser"] = "Feuerstein herstellen (gering)"
	LOCALIZATION_ZORLEN["CreateFirestone"] = "Feuerstein herstellen"
	LOCALIZATION_ZORLEN["CreateFirestoneGreater"] = "Feuerstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN["CreateFirestoneMajor"] = "Feuerstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN["CreateHealthstoneMinor"] = "Gesundheitsstein herstellen (schwach)"
	LOCALIZATION_ZORLEN["CreateHealthstoneLesser"] = "Gesundheitsstein herstellen (gering)"
	LOCALIZATION_ZORLEN["CreateHealthstone"] = "Gesundheitsstein herstellen"
	LOCALIZATION_ZORLEN["CreateHealthstoneGreater"] = "Gesundheitsstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN["CreateHealthstoneMajor"] = "Gesundheitsstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN["CreateSoulstoneMinor"] = "Seelenstein herstellen (schwach)"
	LOCALIZATION_ZORLEN["CreateSoulstoneLesser"] = "Seelenstein herstellen (gering)"
	LOCALIZATION_ZORLEN["CreateSoulstone"] = "Seelenstein herstellen"
	LOCALIZATION_ZORLEN["CreateSoulstoneGreater"] = "Seelenstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN["CreateSoulstoneMajor"] = "Seelenstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN["CreateSpellstone"] = "Zauberstein herstellen"
	LOCALIZATION_ZORLEN["CreateSpellstoneGreater"] = "Zauberstein herstellen (gro\195\159)"
	LOCALIZATION_ZORLEN["CreateSpellstoneMajor"] = "Zauberstein herstellen (erheblich)"
	LOCALIZATION_ZORLEN["DeathCoil"] = "Todesmantel"
	LOCALIZATION_ZORLEN["DemonArmor"] = "D\195\164monenr\195\188stung"
	LOCALIZATION_ZORLEN["DemonSkin"] = "D\195\164monenhaut"
	LOCALIZATION_ZORLEN["DemonicSacrifice"] = "D\195\164monenopferung"
	LOCALIZATION_ZORLEN["DetectLesserInvisibility"] = "Geringe Unsichtbarkeit entdecken"
	LOCALIZATION_ZORLEN["DetectInvisibility"] = "Unsichtbarkeit entdecken"
	LOCALIZATION_ZORLEN["DetectGreaterInvisibility"] = "Gro\195\159e Unsichtbarkeit entdecken"
	LOCALIZATION_ZORLEN["EnslaveDemon"] = "D\195\164monensklave"
	LOCALIZATION_ZORLEN["EyeOfKilrogg"] = "Auge von Kilrogg"
	LOCALIZATION_ZORLEN["Fear"] = "Furcht"
	LOCALIZATION_ZORLEN["FelDomination"] = "Teufelsbeherrschung"
	LOCALIZATION_ZORLEN["HealthFunnel"] = "Lebenslinie"
	LOCALIZATION_ZORLEN["HowlOfTerror"] = "Schreckgeheul"
	LOCALIZATION_ZORLEN["Inferno"] = "Inferno"
	LOCALIZATION_ZORLEN["RitualOfDoom"] = "Ritual der Verdammnis"
	LOCALIZATION_ZORLEN["RitualOfSummoning"] = "Ritual der Herbeirufung"
	LOCALIZATION_ZORLEN["SearingPain"] = "Sengender Schmerz"
	LOCALIZATION_ZORLEN["SenseDemons"] = "D\195\164monen sp\195\188ren"
	LOCALIZATION_ZORLEN["ShadowWard"] = "Schatten-Zauberschutz"
	LOCALIZATION_ZORLEN["Shadowburn"] = "Schattenbrand"
	LOCALIZATION_ZORLEN["SoulFire"] = "Seelenfeuer"
	LOCALIZATION_ZORLEN["SoulLink"] = "Seelenverbindung"
	--LOCALIZATION_ZORLEN["SummonDreadsteed"] = ""
	LOCALIZATION_ZORLEN["SummonFelhunter"] = "Teufelsj\195\164ger beschw\195\182ren"
	--LOCALIZATION_ZORLEN["SummonFelsteed"] = ""
	LOCALIZATION_ZORLEN["SummonImp"] = "Wichtel beschw\195\182ren"
	LOCALIZATION_ZORLEN["SummonSuccubus"] = "Succubus beschw\195\182ren"
	LOCALIZATION_ZORLEN["SummonVoidwalker"] = "Leerwandler beschw\195\182ren"
	LOCALIZATION_ZORLEN["UnendingBreath"] = "Unendlicher Atem"
	--LOCALIZATION_ZORLEN["FelConcentration"] = ""



-- Zorlen_Druid.lua file Localization
	LOCALIZATION_ZORLEN["TravelForm"] = "Reisegestalt"
	LOCALIZATION_ZORLEN["MoonkinForm"] = "Moonkingestalt"
	LOCALIZATION_ZORLEN["BearForm"] = "B\195\164rengestalt"
	LOCALIZATION_ZORLEN["DireBearForm"] = "Terrorb\195\164rengestalt"
	LOCALIZATION_ZORLEN["CatForm"] = "Katzengestalt"
	LOCALIZATION_ZORLEN["AquaticForm"] = "Wassergestalt"
	LOCALIZATION_ZORLEN["ChallengingRoar"] = "Knurren"
	LOCALIZATION_ZORLEN["DemoralizingRoar"] = "Demoralisierendes Gebr\195\188ll"
	LOCALIZATION_ZORLEN["AbolishPoison"] = "Vergiftung aufheben"
	LOCALIZATION_ZORLEN["Barkskin"] = "Baumrinde"
	LOCALIZATION_ZORLEN["Bash"] = "Hieb"
	LOCALIZATION_ZORLEN["Claw"] = "Klaue"
	LOCALIZATION_ZORLEN["Cower"] = "Ducken"
	LOCALIZATION_ZORLEN["Dash"] = "Spurt"
	LOCALIZATION_ZORLEN["Enrage"] = "Wutanfall"
	LOCALIZATION_ZORLEN["EntanglingRoots"] = "Wucherwurzeln"
	LOCALIZATION_ZORLEN["FaerieFire"] = "Feenfeuer"
	LOCALIZATION_ZORLEN["FaerieFireFeral"] = "Feenfeuer (Tiergestalt)"
	LOCALIZATION_ZORLEN["FeralCharge"] = "Wilde Attacke"
	LOCALIZATION_ZORLEN["FerociousBite"] = "Wilder Biss"
	LOCALIZATION_ZORLEN["FrenziedRegeneration"] = "Rasende Regeneration"
	LOCALIZATION_ZORLEN["GiftOfTheWild"] = "Gabe der Wildnis"
	LOCALIZATION_ZORLEN["HealingTouch"] = "Heilende Ber\195\188hrung"
	LOCALIZATION_ZORLEN["Hibernate"] = "Winterschlaf"
	LOCALIZATION_ZORLEN["Hurricane"] = "Hurrikan"
	LOCALIZATION_ZORLEN["Innervate"] = "Anregen"
	LOCALIZATION_ZORLEN["InsectSwarm"] = "Insektenschwarm"
	LOCALIZATION_ZORLEN["LeaderOfThePack"] = "Rudelf\195\188hrer"
	LOCALIZATION_ZORLEN["MarkOfTheWild"] = "Mal der Wildnis"
	LOCALIZATION_ZORLEN["Maul"] = "Zermalmen"
	LOCALIZATION_ZORLEN["Moonfire"] = "Mondfeuer"
	LOCALIZATION_ZORLEN["NaturesGrasp"] = "Griff der Natur"
	LOCALIZATION_ZORLEN["NaturesSwiftness"] = "Schnelligkeit der Natur"
	LOCALIZATION_ZORLEN["OmenOfClarity"] = "Omen der Klarsicht"
	LOCALIZATION_ZORLEN["Pounce"] = "Anspringen"
	LOCALIZATION_ZORLEN["Prowl"] = "Schleichen"
	LOCALIZATION_ZORLEN["Rake"] = "Krallenhieb"
	LOCALIZATION_ZORLEN["Ravage"] = "Verheeren"
	LOCALIZATION_ZORLEN["Rebirth"] = "Wiedergeburt"
	LOCALIZATION_ZORLEN["Regrowth"] = "Nachwachsen"
	LOCALIZATION_ZORLEN["Rejuvenation"] = "Verj\195\188ngung"
	--LOCALIZATION_ZORLEN["RemoveCurse"] = ""
	LOCALIZATION_ZORLEN["Rip"] = "Zerfetzen"
	LOCALIZATION_ZORLEN["Shred"] = "Schreddern"
	LOCALIZATION_ZORLEN["SootheAnimal"] = "Tier bes\195\164nftigen"
	LOCALIZATION_ZORLEN["Starfire"] = "Sternenfeuer"
	LOCALIZATION_ZORLEN["Swipe"] = "Prankenhieb"
	LOCALIZATION_ZORLEN["Thorns"] = "Dornen"
	LOCALIZATION_ZORLEN["TigersFury"] = "Tigerfuror"
	LOCALIZATION_ZORLEN["TrackHumanoids"] = "Humanoide aufsp\195\188ren"
	LOCALIZATION_ZORLEN["Tranquility"] = "Gelassenheit"
	LOCALIZATION_ZORLEN["Wrath"] = "Zorn"
	LOCALIZATION_ZORLEN["ImprovedWrath"] = "Verbesserter Zorn"
	LOCALIZATION_ZORLEN["ImprovedNaturesGrasp"] = "Verbesserter Griff der Natur"
	LOCALIZATION_ZORLEN["ImprovedEntanglingRoots"] = "Verbesserte Wucherwurzeln"
	LOCALIZATION_ZORLEN["ImprovedMoonfire"] = "Verbessertes Mondfeuer"
	LOCALIZATION_ZORLEN["NaturalWeapons"] = "Waffenbalance"
	LOCALIZATION_ZORLEN["NaturalShapeshifter"] = "Schnellwandlung"
	LOCALIZATION_ZORLEN["ImprovedThorns"] = "Verbesserte Dornen"
	LOCALIZATION_ZORLEN["NaturesReach"] = "Reichweite der Natur"
	LOCALIZATION_ZORLEN["Vengeance"] = "Rache"
	LOCALIZATION_ZORLEN["ImprovedStarfire"] = "Verbessertes Sternenfeuer"
	LOCALIZATION_ZORLEN["NaturesGrace"] = "Anmut der Natur"
	LOCALIZATION_ZORLEN["Moonglow"] = "Mondschein"
	LOCALIZATION_ZORLEN["Moonfury"] = "Mondfuror"
	LOCALIZATION_ZORLEN["Ferocity"] = "Wildheit"
	LOCALIZATION_ZORLEN["FeralAggression"] = "Wilde Aggression"
	LOCALIZATION_ZORLEN["FeralInstinct"] = "Instinkt der Wildnis"
	LOCALIZATION_ZORLEN["BrutalImpact"] = "Brutaler Hieb"
	LOCALIZATION_ZORLEN["ThickHide"] = "Dickes Fell"
	LOCALIZATION_ZORLEN["FelineSwiftness"] = "Katzenhafte Schnelligkeit"
	LOCALIZATION_ZORLEN["SharpenedClaws"] = "Gesch\195\164rfte Klauen"
	LOCALIZATION_ZORLEN["ImprovedShred"] = "Verbessertes Schreddern"
	LOCALIZATION_ZORLEN["PredatoryStrikes"] = "Raubtierschl\195\164ge"
	LOCALIZATION_ZORLEN["BloodFrenzy"] = "Blutraserei"
	LOCALIZATION_ZORLEN["PrimalFury"] = "Urfuror"
	LOCALIZATION_ZORLEN["SavageFury"] = "Ungez\195\164hmte Wut"
	LOCALIZATION_ZORLEN["HeartOfTheWild"] = "Herz der Wildnis"
	LOCALIZATION_ZORLEN["ImprovedMarkOfTheWild"] = "Verbessertes Mal der Wildnis"
	LOCALIZATION_ZORLEN["Furor"] = "Ingrimm"
	LOCALIZATION_ZORLEN["ImprovedHealingTouch"] = "Verbesserte Heilende Ber\195\188hrung"
	LOCALIZATION_ZORLEN["NaturesFocus"] = "Naturfokus"
	LOCALIZATION_ZORLEN["ImprovedEnrage"] = "Verbesserter Wutanfall"
	LOCALIZATION_ZORLEN["Reflection"] = "Reflexion"
	LOCALIZATION_ZORLEN["Subtlety"] = "Feingef\195\188hl"
	LOCALIZATION_ZORLEN["TranquilSpirit"] = "Gelassener Geist"
	LOCALIZATION_ZORLEN["ImprovedRejuvenation"] = "Verbesserte Verj\195\188ngung"
	LOCALIZATION_ZORLEN["GiftOfNature"] = "Geschenk der Natur"
	LOCALIZATION_ZORLEN["ImprovedTranquility"] = "Verbesserte Gelassenheit"
	LOCALIZATION_ZORLEN["ImprovedRegrowth"] = "Verbessertes Nachwachsen"
	LOCALIZATION_ZORLEN["Swiftmend"] = "Rasche Heilung"



-- Zorlen_Mage.lua file Localization
	--LOCALIZATION_ZORLEN["ConjuredCinnamonRoll"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSweetRoll"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSourdough"] = ""
	--LOCALIZATION_ZORLEN["ConjuredPumpernickel"] = ""
	--LOCALIZATION_ZORLEN["ConjuredRye"] = ""
	--LOCALIZATION_ZORLEN["ConjuredBread"] = ""
	--LOCALIZATION_ZORLEN["ConjuredMuffin"] = ""
	--LOCALIZATION_ZORLEN["ConjuredCrystalWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSparklingWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredMineralWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSpringWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredPurifiedWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredFreshWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredWater"] = ""
	--LOCALIZATION_ZORLEN["AmplifyMagic"] = ""
	--LOCALIZATION_ZORLEN["ArcaneBrilliance"] = ""
	--LOCALIZATION_ZORLEN["ArcaneExplosion"] = ""
	--LOCALIZATION_ZORLEN["ArcaneIntellect"] = ""
	--LOCALIZATION_ZORLEN["ArcaneMissiles"] = ""
	--LOCALIZATION_ZORLEN["ArcanePower"] = ""
	--LOCALIZATION_ZORLEN["BlastWave"] = ""
	--LOCALIZATION_ZORLEN["Blink"] = ""
	--LOCALIZATION_ZORLEN["Blizzard"] = ""
	--LOCALIZATION_ZORLEN["ColdSnap"] = ""
	--LOCALIZATION_ZORLEN["Combustion"] = ""
	--LOCALIZATION_ZORLEN["ConeOfCold"] = ""
	--LOCALIZATION_ZORLEN["ConjureFood"] = ""
	--LOCALIZATION_ZORLEN["ConjureManaAgate"] = ""
	--LOCALIZATION_ZORLEN["ConjureManaJade"] = ""
	--LOCALIZATION_ZORLEN["ConjureManaCitrine"] = ""
	--LOCALIZATION_ZORLEN["ConjureManaRuby"] = ""
	--LOCALIZATION_ZORLEN["ConjureWater"] = ""
	--LOCALIZATION_ZORLEN["Counterspell"] = ""
	--LOCALIZATION_ZORLEN["DampenMagic"] = ""
	--LOCALIZATION_ZORLEN["DetectMagic"] = ""
	--LOCALIZATION_ZORLEN["Evocation"] = ""
	--LOCALIZATION_ZORLEN["FireBlast"] = ""
	--LOCALIZATION_ZORLEN["FireWard"] = ""
	--LOCALIZATION_ZORLEN["Fireball"] = ""
	--LOCALIZATION_ZORLEN["Flamestrike"] = ""
	--LOCALIZATION_ZORLEN["FrostArmor"] = ""
	--LOCALIZATION_ZORLEN["FrostNova"] = ""
	--LOCALIZATION_ZORLEN["FrostWard"] = ""
	--LOCALIZATION_ZORLEN["Frostbolt"] = ""
	--LOCALIZATION_ZORLEN["IceArmor"] = ""
	--LOCALIZATION_ZORLEN["IceBarrier"] = ""
	--LOCALIZATION_ZORLEN["IceBlock"] = ""
	--LOCALIZATION_ZORLEN["MageArmor"] = ""
	--LOCALIZATION_ZORLEN["ManaShield"] = ""
	--LOCALIZATION_ZORLEN["Polymorph"] = ""
	--LOCALIZATION_ZORLEN["PortalDarnassus"] = ""
	--LOCALIZATION_ZORLEN["PortalIronforge"] = ""
	--LOCALIZATION_ZORLEN["PortalOrgrimmar"] = ""
	--LOCALIZATION_ZORLEN["PortalStormwind"] = ""
	--LOCALIZATION_ZORLEN["PortalThunderBluff"] = ""
	--LOCALIZATION_ZORLEN["PortalUndercity"] = ""
	--LOCALIZATION_ZORLEN["TeleportDarnassus"] = ""
	--LOCALIZATION_ZORLEN["TeleportIronforge"] = ""
	--LOCALIZATION_ZORLEN["TeleportOrgrimmar"] = ""
	--LOCALIZATION_ZORLEN["TeleportStormwind"] = ""
	--LOCALIZATION_ZORLEN["TeleportThunderBluff"] = ""
	--LOCALIZATION_ZORLEN["TeleportUndercity"] = ""
	--LOCALIZATION_ZORLEN["PresenceOfMind"] = ""
	--LOCALIZATION_ZORLEN["Pyroblast"] = ""
	--LOCALIZATION_ZORLEN["RemoveLesserCurse"] = ""
	--LOCALIZATION_ZORLEN["Scorch"] = ""
	--LOCALIZATION_ZORLEN["SlowFall"] = ""



-- Zorlen_Paladin.lua file Localization
	--LOCALIZATION_ZORLEN["BlessingOfFreedom"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfKings"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfLight"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfMight"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfProtection"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfSacrifice"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfSalvation"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfSanctuary"] = ""
	--LOCALIZATION_ZORLEN["BlessingOfWisdom"] = ""
	--LOCALIZATION_ZORLEN["Cleanse"] = ""
	--LOCALIZATION_ZORLEN["ConcentrationAura"] = ""
	--LOCALIZATION_ZORLEN["Consecration"] = ""
	--LOCALIZATION_ZORLEN["DevotionAura"] = ""
	--LOCALIZATION_ZORLEN["DivineFavor"] = ""
	--LOCALIZATION_ZORLEN["DivineIntervention"] = ""
	--LOCALIZATION_ZORLEN["DivineProtection"] = ""
	--LOCALIZATION_ZORLEN["DivineShield"] = ""
	--LOCALIZATION_ZORLEN["Exorcism"] = ""
	--LOCALIZATION_ZORLEN["FireResistanceAura"] = ""
	--LOCALIZATION_ZORLEN["FlashOfLight"] = ""
	--LOCALIZATION_ZORLEN["FrostResistanceAura"] = ""
	--LOCALIZATION_ZORLEN["GreaterBlessingOfKings"] = ""
	--LOCALIZATION_ZORLEN["GreaterBlessingOfLight"] = ""
	--LOCALIZATION_ZORLEN["GreaterBlessingOfMight"] = ""
	--LOCALIZATION_ZORLEN["GreaterBlessingOfSalvation"] = ""
	--LOCALIZATION_ZORLEN["GreaterBlessingOfSanctuary"] = ""
	--LOCALIZATION_ZORLEN["GreaterBlessingOfWisdom"] = ""
	--LOCALIZATION_ZORLEN["HammerOfJustice"] = ""
	--LOCALIZATION_ZORLEN["HammerOfWrath"] = ""
	--LOCALIZATION_ZORLEN["HolyLight"] = ""
	--LOCALIZATION_ZORLEN["HolyShield"] = ""
	--LOCALIZATION_ZORLEN["HolyShock"] = ""
	--LOCALIZATION_ZORLEN["HolyWrath"] = ""
	--LOCALIZATION_ZORLEN["Judgement"] = ""
	--LOCALIZATION_ZORLEN["LayOnHands"] = ""
	--LOCALIZATION_ZORLEN["Purify"] = ""
	--LOCALIZATION_ZORLEN["Redemption"] = ""
	--LOCALIZATION_ZORLEN["Repentance"] = ""
	--LOCALIZATION_ZORLEN["RetributionAura"] = ""
	--LOCALIZATION_ZORLEN["RighteousFury"] = ""
	--LOCALIZATION_ZORLEN["SanctityAura"] = ""
	--LOCALIZATION_ZORLEN["SealOfCommand"] = ""
	--LOCALIZATION_ZORLEN["SealOfJustice"] = ""
	--LOCALIZATION_ZORLEN["SealOfLight"] = ""
	--LOCALIZATION_ZORLEN["SealOfRighteousness"] = ""
	--LOCALIZATION_ZORLEN["SealOfWisdom"] = ""
	--LOCALIZATION_ZORLEN["SealOfTheCrusader"] = ""
	--LOCALIZATION_ZORLEN["SenseUndead"] = ""
	--LOCALIZATION_ZORLEN["ShadowResistanceAura"] = ""
	--LOCALIZATION_ZORLEN["SummonCharger"] = ""
	--LOCALIZATION_ZORLEN["SummonWarhorse"] = ""
	--LOCALIZATION_ZORLEN["TurnUndead"] = ""



-- Zorlen_Priest.lua file Localization
	LOCALIZATION_ZORLEN["PowerInfusion"] = "Seele der Macht"
	LOCALIZATION_ZORLEN["Lightwell"] = "Lichtbrunnen"
	LOCALIZATION_ZORLEN["AbolishDisease"] = "Krankheit aufheben"
	LOCALIZATION_ZORLEN["CureDisease"] = "Krankheit heilen"
	LOCALIZATION_ZORLEN["DesperatePrayer"] = "Verzweifeltes Gebet"
	LOCALIZATION_ZORLEN["DevouringPlague"] = "Verschlingende Seuche"
	LOCALIZATION_ZORLEN["DispelMagic"] = "Magiebannung"
	LOCALIZATION_ZORLEN["DivineSpirit"] = "G\195\182ttlicher Willen"
	LOCALIZATION_ZORLEN["ElunesGrace"] = "Elunes Anmut"
	LOCALIZATION_ZORLEN["Fade"] = "Verblassen"
	LOCALIZATION_ZORLEN["FearWard"] = "Furcht-Zauberschutz"
	LOCALIZATION_ZORLEN["Feedback"] = "R\195\188ckkopplung"
	LOCALIZATION_ZORLEN["FlashHeal"] = "Blitzheilung"
	LOCALIZATION_ZORLEN["FocusedCasting"] = "Fokusiertes Zaubern"
	LOCALIZATION_ZORLEN["LesserHeal"] = "Geringes Heilen"
	LOCALIZATION_ZORLEN["Heal"] = "Heilen"
	LOCALIZATION_ZORLEN["GreaterHeal"] = "Gro\195\159e Heilung"
	LOCALIZATION_ZORLEN["HexOfWeakness"] = "Verhexung der Schw\195\164che"
	LOCALIZATION_ZORLEN["HolyFire"] = "Heiliges Feuer"
	LOCALIZATION_ZORLEN["HolyNova"] = "Heilige Nova"
	LOCALIZATION_ZORLEN["InnerFire"] = "Inneres Feuer"
	LOCALIZATION_ZORLEN["InnerFocus"] = "Innerer Fokus"
	LOCALIZATION_ZORLEN["Levitate"] = "Levitieren"
	LOCALIZATION_ZORLEN["ManaBurn"] = "Manabrand"
	LOCALIZATION_ZORLEN["MindBlast"] = "Gedankenschlag"
	LOCALIZATION_ZORLEN["MindControl"] = "Gedankenkontrolle"
	LOCALIZATION_ZORLEN["MindFlay"] = "Gedankenschinden"
	LOCALIZATION_ZORLEN["MindSoothe"] = "Gedankenbes\195\164nftigung"
	LOCALIZATION_ZORLEN["MindVision"] = "Gedankensicht"
	LOCALIZATION_ZORLEN["PowerWordFortitude"] = "Machtwort: Seelenst\195\164rke"
	LOCALIZATION_ZORLEN["PowerWordShield"] = "Machtwort: Schild"
	LOCALIZATION_ZORLEN["PrayerOfFortitude"] = "Gebet der Seelenst\195\164rke"
	LOCALIZATION_ZORLEN["PrayerOfHealing"] = "Gebet der Heilung"
	LOCALIZATION_ZORLEN["PsychicScream"] = "Psychischer Schrei"
	LOCALIZATION_ZORLEN["Renew"] = "Erneuerung"
	LOCALIZATION_ZORLEN["Resurrection"] = "Wiederbelebung"
	LOCALIZATION_ZORLEN["ShackleUndead"] = "Untote Fesseln"
	LOCALIZATION_ZORLEN["ShadowProtection"] = "Schattenschutz"
	LOCALIZATION_ZORLEN["ShadowWordPain"] = "Schattenwort: Schmerz"
	LOCALIZATION_ZORLEN["Shadowform"] = "Schattengestalt"
	LOCALIZATION_ZORLEN["Shadowguard"] = "Schattenschild"
	LOCALIZATION_ZORLEN["Silence"] = "Scheigsame Entschlossenheit"
	LOCALIZATION_ZORLEN["Smite"] = "G\195\182ttliche Pein"
	LOCALIZATION_ZORLEN["SpiritOfRedemption"] = "Geist der Erl\195\182sung"
	LOCALIZATION_ZORLEN["Starshards"] = "Sternensplitter"
	LOCALIZATION_ZORLEN["TouchOfWeakness"] = "Ber\195\188hrung der Schw\195\164che"
	LOCALIZATION_ZORLEN["VampiricEmbrace"] = "Vampirumarmung"



-- Zorlen_Rogue.lua file Localization
	--LOCALIZATION_ZORLEN["DirtyDeeds"] = ""
	LOCALIZATION_ZORLEN["ImprovedSinisterStrike"] = "Verbesserter Finsterer Sto\195\159"
	LOCALIZATION_ZORLEN["CripplingPoison"] = "Verkr\195\188ppeldes Gift"
	LOCALIZATION_ZORLEN["CripplingPoisonII"] = "Verkr\195\188ppeldes Gift II"
	LOCALIZATION_ZORLEN["DeadlyPoison"] = "T\195\182dliches Gift"
	LOCALIZATION_ZORLEN["DeadlyPoisonII"] = "T\195\182dliches Gift II"
	LOCALIZATION_ZORLEN["DeadlyPoisonIII"] = "T\195\182dliches Gift III"
	LOCALIZATION_ZORLEN["DeadlyPoisonIV"] = "T\195\182dliches Gift IV"
	LOCALIZATION_ZORLEN["DeadlyPoisonV"] = "T\195\182dliches Gift V"
	LOCALIZATION_ZORLEN["InstantPoison"] = "Sofortwirkendes Gift"
	LOCALIZATION_ZORLEN["InstantPoisonII"] = "Sofortwirkendes Gift II"
	LOCALIZATION_ZORLEN["InstantPoisonIII"] = "Sofortwirkendes Gift III"
	LOCALIZATION_ZORLEN["InstantPoisonIV"] = "Sofortwirkendes Gift IV"
	LOCALIZATION_ZORLEN["InstantPoisonV"] = "Sofortwirkendes Gift V"
	LOCALIZATION_ZORLEN["InstantPoisonVI"] = "Sofortwirkendes Gift VI"
	LOCALIZATION_ZORLEN["MindnumbingPoison"] = "Gedankenblendendes Gift"
	LOCALIZATION_ZORLEN["MindnumbingPoisonII"] = "Gedankenblendendes Gift II"
	LOCALIZATION_ZORLEN["MindnumbingPoisonIII"] = "Gedankenblendendes Gift III"
	LOCALIZATION_ZORLEN["WoundPoison"] = "Wundgift"
	LOCALIZATION_ZORLEN["WoundPoisonII"] = "Wundgift II"
	LOCALIZATION_ZORLEN["WoundPoisonIII"] = "Wundgift III"
	LOCALIZATION_ZORLEN["WoundPoisonIV"] = "Wundgift IV"
	LOCALIZATION_ZORLEN["AdrenalineRush"] = "Adrenalinrausch"
	LOCALIZATION_ZORLEN["Ambush"] = "Hinterhalt"
	LOCALIZATION_ZORLEN["Backstab"] = "Meucheln"
	LOCALIZATION_ZORLEN["BladeFlurry"] = "Klingenwirbel"
	LOCALIZATION_ZORLEN["Blind"] = "Blenden"
	LOCALIZATION_ZORLEN["BlindingPowder"] = "Blendungspulver"
	LOCALIZATION_ZORLEN["CheapShot"] = "Fieser Trick"
	LOCALIZATION_ZORLEN["ColdBlood"] = "Kaltbl\195\188tigkeit"
	LOCALIZATION_ZORLEN["DetectTraps"] = "Fallen entdecken"
	LOCALIZATION_ZORLEN["DisarmTrap"] = "Fallen entsch\195\164rfen"
	LOCALIZATION_ZORLEN["Distract"] = "Ablenken"
	LOCALIZATION_ZORLEN["Evasion"] = "Entrinnen"
	LOCALIZATION_ZORLEN["Eviscerate"] = "Ausweiden"
	LOCALIZATION_ZORLEN["ExposeArmor"] = "R\195\188stung schw\195\164chen"
	LOCALIZATION_ZORLEN["Feint"] = "Finte"
	LOCALIZATION_ZORLEN["Garrote"] = "Erdrosseln"
	LOCALIZATION_ZORLEN["GhostlyStrike"] = "Geisterhafter Sto\195\159"
	LOCALIZATION_ZORLEN["Gouge"] = "Solarplexus"
	LOCALIZATION_ZORLEN["Hemorrhage"] = "Blutsturz"
	LOCALIZATION_ZORLEN["Kick"] = "Tritt"
	LOCALIZATION_ZORLEN["KidneyShot"] = "Nierenhieb"
	LOCALIZATION_ZORLEN["PickLock"] = "Schl\195\182sser knacken"
	LOCALIZATION_ZORLEN["PickPocket"] = "Taschendiebstahl"
	LOCALIZATION_ZORLEN["Premeditation"] = "Konzentration"
	LOCALIZATION_ZORLEN["Preparation"] = "Vorbereitung"
	LOCALIZATION_ZORLEN["RelentlessStrikes"] = "Unerbitliche St\195\182\195\159e"
	LOCALIZATION_ZORLEN["Riposte"] = "Riposte"
	LOCALIZATION_ZORLEN["Rupture"] = "Blutung"
	LOCALIZATION_ZORLEN["Sap"] = "Kopfnuss"
	LOCALIZATION_ZORLEN["SinisterStrike"] = "Finsterer Sto\195\159"
	LOCALIZATION_ZORLEN["SliceAndDice"] = "Zerh\195\164chseln"
	LOCALIZATION_ZORLEN["Sprint"] = "Sprinten"
	LOCALIZATION_ZORLEN["Stealth"] = "Verstohlenheit"
	LOCALIZATION_ZORLEN["Vanish"] = "Verschwinden"



-- Zorlen_Shaman.lua file Localization
	--LOCALIZATION_ZORLEN["DiseaseCleansingTotem"] = ""
	--LOCALIZATION_ZORLEN["EarthbindTotem"] = ""
	--LOCALIZATION_ZORLEN["FireNovaTotem"] = ""
	--LOCALIZATION_ZORLEN["FireResistanceTotem"] = ""
	--LOCALIZATION_ZORLEN["FlametongueTotem"] = ""
	--LOCALIZATION_ZORLEN["FrostResistanceTotem"] = ""
	--LOCALIZATION_ZORLEN["GraceOfAirTotem"] = ""
	--LOCALIZATION_ZORLEN["GroundingTotem"] = ""
	--LOCALIZATION_ZORLEN["HealingStreamTotem"] = ""
	--LOCALIZATION_ZORLEN["MagmaTotem"] = ""
	--LOCALIZATION_ZORLEN["ManaSpringTotem"] = ""
	--LOCALIZATION_ZORLEN["ManaTideTotem"] = ""
	--LOCALIZATION_ZORLEN["NatureResistanceTotem"] = ""
	--LOCALIZATION_ZORLEN["PoisonCleansingTotem"] = ""
	--LOCALIZATION_ZORLEN["SearingTotem"] = ""
	--LOCALIZATION_ZORLEN["SentryTotem"] = ""
	--LOCALIZATION_ZORLEN["StoneclawTotem"] = ""
	--LOCALIZATION_ZORLEN["StoneskinTotem"] = ""
	--LOCALIZATION_ZORLEN["StrengthOfEarthTotem"] = ""
	--LOCALIZATION_ZORLEN["TremorTotem"] = ""
	--LOCALIZATION_ZORLEN["WindfuryTotem"] = ""
	--LOCALIZATION_ZORLEN["WindwallTotem"] = ""
	--LOCALIZATION_ZORLEN["EarthShock"] = ""
	--LOCALIZATION_ZORLEN["FlameShock"] = ""
	--LOCALIZATION_ZORLEN["FrostShock"] = ""
	--LOCALIZATION_ZORLEN["FlametongueWeapon"] = ""
	--LOCALIZATION_ZORLEN["FrostbrandWeapon"] = ""
	--LOCALIZATION_ZORLEN["RockbiterWeapon"] = ""
	--LOCALIZATION_ZORLEN["WindfuryWeapon"] = ""
	--LOCALIZATION_ZORLEN["AncestralSpirit"] = ""
	--LOCALIZATION_ZORLEN["AstralRecall"] = ""
	--LOCALIZATION_ZORLEN["ChainHeal"] = ""
	--LOCALIZATION_ZORLEN["ChainLightning"] = ""
	--LOCALIZATION_ZORLEN["CureDisease"] = ""
	--LOCALIZATION_ZORLEN["CurePoison"] = ""
	--LOCALIZATION_ZORLEN["ElementalFocus"] = ""
	--LOCALIZATION_ZORLEN["ElementalMastery"] = ""
	--LOCALIZATION_ZORLEN["FarSight"] = ""
	--LOCALIZATION_ZORLEN["GhostWolf"] = ""
	--LOCALIZATION_ZORLEN["LesserHealingWave"] = ""
	--LOCALIZATION_ZORLEN["HealingWave"] = ""
	--LOCALIZATION_ZORLEN["LightningBolt"] = ""
	--LOCALIZATION_ZORLEN["LightningShield"] = ""
	--LOCALIZATION_ZORLEN["NaturesSwiftness"] = ""
	--LOCALIZATION_ZORLEN["Purge"] = ""
	--LOCALIZATION_ZORLEN["Reincarnation"] = ""
	--LOCALIZATION_ZORLEN["Stormstrike"] = ""
	--LOCALIZATION_ZORLEN["WaterBreathing"] = ""
	--LOCALIZATION_ZORLEN["WaterWalking"] = ""



-- Zorlen_Warrior.lua file Localization
	--LOCALIZATION_ZORLEN["Devastate"] = ""
	--LOCALIZATION_ZORLEN["ImprovedWhirlwind"] = ""
	--LOCALIZATION_ZORLEN["FocusedRage"] = ""
	--LOCALIZATION_ZORLEN["CommandingShout"] = ""
	--LOCALIZATION_ZORLEN["SpellReflection"] = ""
	--LOCALIZATION_ZORLEN["Intervene"] = ""
	--LOCALIZATION_ZORLEN["VictoryRush"] = ""
	--LOCALIZATION_ZORLEN["EndlessRage"] = ""
	--LOCALIZATION_ZORLEN["Rampage"] = ""
	
	LOCALIZATION_ZORLEN["ImprovedBloodrage"] = "Verbessertes Blutrausch"
	LOCALIZATION_ZORLEN["ImprovedOverpower"] = "Verbessertes \195\156berw\195\164ltigen"
	LOCALIZATION_ZORLEN["ImprovedBerserkerRage"] = "Verbesserte Berserkerwut"
	LOCALIZATION_ZORLEN["ImprovedExecute"] = "Verbessertes Hinrichten"
	LOCALIZATION_ZORLEN["Execute"] = "Hinrichten"
	LOCALIZATION_ZORLEN["ImprovedHeroicStrike"] = "Verbesserter Heldenhafter Sto\195\159"
	LOCALIZATION_ZORLEN["HeroicStrike"] = "Heldenhafter Sto\195\159"
	LOCALIZATION_ZORLEN["ImprovedSunderArmor"] = "Verbessertes R\195\188stung zerrei\195\159en"
	LOCALIZATION_ZORLEN["SunderArmor"] = "R\195\188stung zerrei\195\159en"
	LOCALIZATION_ZORLEN["ImprovedThunderClap"] = "Verbesserter Donnerknall"
	LOCALIZATION_ZORLEN["ThunderClap"] = "Donnerknall"
	LOCALIZATION_ZORLEN["MortalStrike"] = "T\195\182dlicher Sto\195\159"
	LOCALIZATION_ZORLEN["Bloodthirst"] = "Blutdurst"
	LOCALIZATION_ZORLEN["ShieldSlam"] = "Schildschlag"
	LOCALIZATION_ZORLEN["Charge"] = "Sturmangriff"
	LOCALIZATION_ZORLEN["Taunt"] = "Spott"
	LOCALIZATION_ZORLEN["Intercept"] = "Abfangen"
	LOCALIZATION_ZORLEN["Overpower"] = "\195\156berw\195\164ltigen"
	LOCALIZATION_ZORLEN["Revenge"] = "Rache"
	LOCALIZATION_ZORLEN["Rend"] = "Verwunden"
	LOCALIZATION_ZORLEN["Hamstring"] = "Kniesehne"
	LOCALIZATION_ZORLEN["ShieldBash"] = "Schildhieb"
	LOCALIZATION_ZORLEN["Pummel"] = "Zuschlagen"
	LOCALIZATION_ZORLEN["ShieldBlock"] = "Schildblock"
	LOCALIZATION_ZORLEN["DemoralizingShout"] = "Demoralisierungsruf"
	LOCALIZATION_ZORLEN["BattleShout"] = "Schlachtruf"
	LOCALIZATION_ZORLEN["BerserkerRage"] = "Berserkerwut"
	LOCALIZATION_ZORLEN["Enrage"] = "Wutanfall"
	LOCALIZATION_ZORLEN["DefensiveStance"] = "Verteidigungshaltung"
	LOCALIZATION_ZORLEN["BattleStance"] = "Kampfhaltung"
	LOCALIZATION_ZORLEN["BerserkerStance"] = "Berserkerhaltung"
	LOCALIZATION_ZORLEN["AngerManagement"] = "Agressionskontrolle"
	LOCALIZATION_ZORLEN["Bloodrage"] = "Blutrausch"
	LOCALIZATION_ZORLEN["ChallengingShout"] = "Herausforderungsruf"
	LOCALIZATION_ZORLEN["Cleave"] = "Spalten"
	LOCALIZATION_ZORLEN["ConcussionBlow"] = "Ersch\195\188tternder Schlag"
	LOCALIZATION_ZORLEN["DeathWish"] = "Todeswunsch"
	LOCALIZATION_ZORLEN["Disarm"] = "Entwaffnen"
	LOCALIZATION_ZORLEN["IntimidatingShout"] = "Drohruf"
	LOCALIZATION_ZORLEN["LastStand"] = "Letztes Gefecht"
	LOCALIZATION_ZORLEN["MockingBlow"] = "Sp\195\182ttischer Schlag"
	LOCALIZATION_ZORLEN["PiercingHowl"] = "Durchdringendes Heulen"
	LOCALIZATION_ZORLEN["Recklessness"] = "Tollk\195\188hnheit"
	LOCALIZATION_ZORLEN["Retaliation"] = "Gegenschlag"
	LOCALIZATION_ZORLEN["ShieldWall"] = "Schildwall"
	LOCALIZATION_ZORLEN["Slam"] = "Zerschmettern"
	LOCALIZATION_ZORLEN["SweepingStrikes"] = "Weitreichende St\195\182\195\159e"
	LOCALIZATION_ZORLEN["Whirlwind"] = "Wirbelwind"
	LOCALIZATION_ZORLEN["TacticalMastery"] = "Taktiker"



-- Fire Immune MOB's
 -- Molten Core
	LOCALIZATION_ZORLEN["Firelord"] = "Feuerlord"
	LOCALIZATION_ZORLEN["Firewalker"] = "Feuerg\195\164nger"
	LOCALIZATION_ZORLEN["Flameguard"] = "Flammenw\195\164chter"
	LOCALIZATION_ZORLEN["LavaSpawn"] = "Lavabrut"
	LOCALIZATION_ZORLEN["BaronGeddon"] = "Baron Geddon"
	LOCALIZATION_ZORLEN["Ragnaros"] = "Ragnaros"
 -- Upper Blackrock Spire
	LOCALIZATION_ZORLEN["PyroguardEmberseer"] = "Feuerwache Glutseher"
 -- Blackrock Depths
	LOCALIZATION_ZORLEN["Fireguard"] = "Brandwache"
	LOCALIZATION_ZORLEN["FireguardDestroyer"] = "Brandwachenzerst\195\182rer"
	LOCALIZATION_ZORLEN["BlazingFireguard"] = "Lodernde Brandwache"
	LOCALIZATION_ZORLEN["AmbassadorFlamelash"] = "Botschafter Flammenschlag"
	LOCALIZATION_ZORLEN["LordIncendius"] = "Lord Incendius"
 --Searing Gorge
	LOCALIZATION_ZORLEN["BlazingElemental"] = "Lodernder Elementar"
	LOCALIZATION_ZORLEN["InfernoElemental"] = "Infernoelementar"
 --Un'Goro Crater
	LOCALIZATION_ZORLEN["ScorchingElemental"] = "Versengender Elementar"
	LOCALIZATION_ZORLEN["LivingBlaze"] = "Lebendiges Feuer"
	LOCALIZATION_ZORLEN["Blazerunner"] = "Lodernder Eindringling"

-- Drain Life Immune MOB's
 -- Blackrock Depths
	--LOCALIZATION_ZORLEN["MoltenWarGolem"] = ""
	--LOCALIZATION_ZORLEN["PanzorTheInvincible"] = ""
 --Searing Gorge
	--LOCALIZATION_ZORLEN["HeavyWarGolem"] = ""
	--LOCALIZATION_ZORLEN["FaultyWarGolem"] = ""
	--LOCALIZATION_ZORLEN["TemperedWarGolem"] = ""
	--LOCALIZATION_ZORLEN["RagereaverGolem"] = ""
