
Zorlen_FR_FileBuildNumber = 687

-- French Translation
-- If you want to translate this to another language, make sure the names of buffs and abilities are *EXACTLY* the same as in-game. Spelling, punctuation, upper/lowercase letters, etc. MUST BE EXACT. Also, any 'foreign' characters must be converted to UNICODE.
-- Unicode resource:
-- http://www.utf8-chartable.de/unicode-utf8-table.pl?start=128&number=1024&utf8=dec
-- http://home.tiscali.nl/t876506/utf8tbl.html
-- http://www.allegro-c.de/unicode/zcodes.htm
-- You will need to use the UTF-8 decimal numbers with a back slash in front of them in the same way that Å is represented by: \195\133


-- To lower the upkeep we will not be adding Localization for english words that do not break compatibility in other game clients.
-- This Localization is only added for compatibility so that it may work in non english game clients and not as a translation.

if GetLocale() ~= "frFR" then return end

-- All file Localization
	--LOCALIZATION_ZORLEN["EatMacroName"] = ""
	--LOCALIZATION_ZORLEN["DrinkMacroName"] = ""
	LOCALIZATION_ZORLEN["Conjured"] = "invoqu\195\169"
	LOCALIZATION_ZORLEN["Water"] = "Eau"
	--LOCALIZATION_ZORLEN["AllConjuredWater"] = ""
	--LOCALIZATION_ZORLEN["well_fed"] = ""
	LOCALIZATION_ZORLEN["HitsOrCritsArray"] = {}
	LOCALIZATION_ZORLEN["EnemyDies"] = "(.*)"
	LOCALIZATION_ZORLEN["Rank"] = "Rang"
	LOCALIZATION_ZORLEN["sit"] = "sit"
	LOCALIZATION_ZORLEN["You_dodge"] = "Vous esquivez"
	LOCALIZATION_ZORLEN["ImmuneArray"] = {"(.+).* (.*) .*insensible"}
	--LOCALIZATION_ZORLEN["no_weapons_equipped"] = ""
	--LOCALIZATION_ZORLEN["dodged"] = ""
	--LOCALIZATION_ZORLEN["dodges"] = ""
	--LOCALIZATION_ZORLEN["pet_is_not_dead"] = ""
	--LOCALIZATION_ZORLEN["pet_is_dead"] = ""
	--LOCALIZATION_ZORLEN["You fail to perform (.+): A more powerful spell is already active."] = ""
	--LOCALIZATION_ZORLEN["Asleep"] = ""
	--LOCALIZATION_ZORLEN["RequiresLevel"] = ""
	
	--LOCALIZATION_ZORLEN["GreaterHealingWard"] = ""
	--LOCALIZATION_ZORLEN["LavaSpoutTotem"] = ""
	
	LOCALIZATION_ZORLEN["HealingBonusWordsArray"] = {"Soins", "Sorts de Soins", "Sorts de soin", "Sorts de soins"}
	LOCALIZATION_ZORLEN["HealingBonusPhraseArray"] = {"Augmente les effets des sorts de soins de (%d+)% au maximum.", "Augmente les soins prodigu\195\169s par les sorts et effets de (%d+)% au maximum."}
	
	LOCALIZATION_ZORLEN["SpellDamageAndHealingBonusWordsArray"] = {"D\195\169g\195\162ts et soins ", "D\195\169g\195\162ts et soins"}
	LOCALIZATION_ZORLEN["SpellDamageAndHealingBonusPhraseArray"] = {"Augmente les soins et d\195\169g\195\162ts produits par les sorts et effets magiques de (%d+) au maximum.", "Augmente les d\195\169g\195\162ts et les soins produits par les sorts et effets magiques de (%d+) au maximum."}
	
	LOCALIZATION_ZORLEN["SpellDamageBonusWordsArray"] = {"Sorts de Dommages", "d\195\169g\195\162ts des sorts", "d\195\169g\195\162ts et les effets des sorts"}
	LOCALIZATION_ZORLEN["SpellDamageBonusPhraseArray"] = {}
	--LOCALIZATION_ZORLEN["BrilliantWizardOil"] = ""
	--LOCALIZATION_ZORLEN["WizardOil"] = ""
	--LOCALIZATION_ZORLEN["LesserWizardOil"] = ""
	--LOCALIZATION_ZORLEN["MinorWizardOil"] = ""
	--LOCALIZATION_ZORLEN["SupremePower"] = ""
	--LOCALIZATION_ZORLEN["GreaterArcaneElixir"] = ""
	--LOCALIZATION_ZORLEN["ArcaneElixir"] = ""
	
	LOCALIZATION_ZORLEN["ShadowDamageBonusWordsArray"] = {"D\195\169g\195\162ts des Ombres"}
	LOCALIZATION_ZORLEN["ShadowDamageBonusPhraseArray"] = {"Augmente les points de d\195\169g\195\162ts inflig\195\169s par les sorts et les effets d'ombre de (%d+)% au maximum.", "(%d+)% aux d\195\169g\195\162ts des sorts d'ombres."}
	--LOCALIZATION_ZORLEN["ShadowPower"] = ""
	
-- Battleground Names
	--LOCALIZATION_ZORLEN["WarsongGulch"] = ""
	--LOCALIZATION_ZORLEN["AlteracValley"] = ""
	--LOCALIZATION_ZORLEN["ArathiBasin"] = ""
	
-- Raid Target Names
	--LOCALIZATION_ZORLEN["WhiteSkull"] = ""
	--LOCALIZATION_ZORLEN["RedX"] = ""
	--LOCALIZATION_ZORLEN["BlueSquare"] = ""
	--LOCALIZATION_ZORLEN["WhiteCrescentMoon"] = ""
	--LOCALIZATION_ZORLEN["GreenTriangle"] = ""
	--LOCALIZATION_ZORLEN["PurpleDiamond"] = ""
	--LOCALIZATION_ZORLEN["OrangeCircle"] = ""
	--LOCALIZATION_ZORLEN["YellowStar"] = ""

-- Example: /script Zorlen_GiveName_OffHandType()
-- The example above will give the name required for ["Shields
-- You must have a shield equipped to get the correct name.
-- You can also get the correct name from the auction house filters under the Armor section.
	LOCALIZATION_ZORLEN["Shields"] = "Bouclier"
	
-- Example: /script Zorlen_GiveName_MainHandType()
-- The example above will give the name required for the weapons below.
-- You must have the weapon equipped to get the correct name.
-- You can also get the correct names from the auction house filters under the Weapon section.
	LOCALIZATION_ZORLEN["Daggers"] = "Dagues"
	LOCALIZATION_ZORLEN["One-Handed Swords"] = "Ep\195\169es \195\160 une main"
	LOCALIZATION_ZORLEN["Two-Handed Swords"] = "Ep\195\169es \195\160 deux mains"
	LOCALIZATION_ZORLEN["One-Handed Axes"] = "Haches \195\160 une main"
	LOCALIZATION_ZORLEN["Two-Handed Axes"] = "Haches \195\160 deux mains"
	LOCALIZATION_ZORLEN["One-Handed Maces"] = "Masses \195\160 une main"
	LOCALIZATION_ZORLEN["Two-Handed Maces"] = "Masses \195\160 deux mains"
	LOCALIZATION_ZORLEN["Polearms"] = "Armes d'hast"
	LOCALIZATION_ZORLEN["Staves"] = "B\195\162tons"
	LOCALIZATION_ZORLEN["Fist Weapons"] = "Armes de pugilat"
	LOCALIZATION_ZORLEN["Fishing Pole"] = "Cannes \195\160 p\195\170che"

-- Item Sub Types:
	--LOCALIZATION_ZORLEN["Bag"] = ""
	--LOCALIZATION_ZORLEN["Soul Bag"] = ""


-- Food Item Tool Tip Text:
	--LOCALIZATION_ZORLEN["FoodToolTipTextAny"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText3180"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText2148"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText1392"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText874"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText552"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText243"] = ""
	--LOCALIZATION_ZORLEN["FoodToolTipText61"] = ""
-- Drink Item Tool Tip Text:
	--LOCALIZATION_ZORLEN["DrinkToolTipTextAny"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText4200"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText2934"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText1992"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText1344"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText835"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText436"] = ""
	--LOCALIZATION_ZORLEN["DrinkToolTipText151"] = ""



-- Zorlen_Other.lua file Localization
	LOCALIZATION_ZORLEN["Attack"] = "Attaque"
	LOCALIZATION_ZORLEN["Throw"] = "Lancer"
	LOCALIZATION_ZORLEN["ShootBow"] = "Tir \195\160 l'arc"
	LOCALIZATION_ZORLEN["ShootCrossbow"] = "Tir \195\160 l\226\128\153arbal\195\168te"
	LOCALIZATION_ZORLEN["ShootGun"] = "Tir avec une arme \195\160 feu"
	LOCALIZATION_ZORLEN["Shoot"] = "Tir"
-- Human Racial
	LOCALIZATION_ZORLEN["Perception"] = "Perception"
-- Dwarf Racial
	LOCALIZATION_ZORLEN["FindTreasure"] = "D\195\169couverte de tr\195\169sors"
	LOCALIZATION_ZORLEN["Stoneform"] = "Forme de pierre"
-- Gnome Racial
	LOCALIZATION_ZORLEN["EscapeArtist"] = "Ma\195\174tre de l'\195\169vasion"
-- Night Elf Racial
	LOCALIZATION_ZORLEN["Shadowmeld"] = "Camouflage dans l'ombre"
-- Orc Racial
	LOCALIZATION_ZORLEN["BloodFury"] = "Fureur sanguinaire"
-- Undead Racial
	LOCALIZATION_ZORLEN["Cannibalize"] = "Cannibalisme"
	LOCALIZATION_ZORLEN["WillOfTheForsaken"] = "Volont\195\169 des R\195\169prouv\195\169s"
-- Tauren Racial
	LOCALIZATION_ZORLEN["WarStomp"] = "Choc martial"
-- Troll Racial
	LOCALIZATION_ZORLEN["Berserking"] = "Berserker"



-- Zorlen_Pets.lua file Localization
-- Hunter Pets
	LOCALIZATION_ZORLEN["Dash"] = "C\195\169l\195\169rit\195\169"
	LOCALIZATION_ZORLEN["Dive"] = "Plongeon"
	LOCALIZATION_ZORLEN["Bite"] = "Morsure"
	LOCALIZATION_ZORLEN["Claw"] = "Griffe"
	LOCALIZATION_ZORLEN["Cower"] = "D\195\169robade"
	LOCALIZATION_ZORLEN["Growl"] = "Grondement"
	LOCALIZATION_ZORLEN["Prowl"] = "R\195\180der"
	LOCALIZATION_ZORLEN["Charge"] = "Charge"
	LOCALIZATION_ZORLEN["Screech"] = "Hurlement"
	LOCALIZATION_ZORLEN["FuriousHowl"] = "Hurlement furieux"
	LOCALIZATION_ZORLEN["LightningBreath"] = "Souffle de foudre"
	LOCALIZATION_ZORLEN["ShellShield"] = "Carapace bouclier"
	LOCALIZATION_ZORLEN["Thunderstomp"] = "Grondeterre"
	LOCALIZATION_ZORLEN["ScorpidPoison"] = "Poison de scorpide"
-- Warlock Pets
	LOCALIZATION_ZORLEN["Felhunter"] = "Chasseur corrompu"
	LOCALIZATION_ZORLEN["Imp"] = "Diablotin"
	LOCALIZATION_ZORLEN["Succubus"] = "Succube"
	LOCALIZATION_ZORLEN["Voidwalker"] = "Marcheur du Vide"
	LOCALIZATION_ZORLEN["BloodPact"] = "Pacte de sang"
	LOCALIZATION_ZORLEN["FireShield"] = "Bouclier de feu"
	LOCALIZATION_ZORLEN["Firebolt"] = "Eclair de feu"
	LOCALIZATION_ZORLEN["PhaseShift"] = "Changement de phase"
	LOCALIZATION_ZORLEN["ConsumeShadows"] = "Consumer les ombres"
	LOCALIZATION_ZORLEN["Sacrifice"] = "Sacrifice"
	LOCALIZATION_ZORLEN["Suffering"] = "Souffrance"
	LOCALIZATION_ZORLEN["Torment"] = "Tourment"
	LOCALIZATION_ZORLEN["DevourMagic"] = "Festin magique"
	LOCALIZATION_ZORLEN["Paranoia"] = "Parano\195\175a"
	LOCALIZATION_ZORLEN["SpellLock"] = "Verrou magique"
	LOCALIZATION_ZORLEN["TaintedBlood"] = "Corruption sanguine"
	LOCALIZATION_ZORLEN["LashOfPain"] = "Fouet de la douleur"
	LOCALIZATION_ZORLEN["Seduction"] = "S\195\169duction"
	LOCALIZATION_ZORLEN["SoothingKiss"] = "Baiser apaisant"
	LOCALIZATION_ZORLEN["LesserInvisibility"] = "Invisibilit\195\169 inf\195\169rieure"



-- Zorlen_Hunter.lua file Localization
	--LOCALIZATION_ZORLEN["FeedPet"] = ""
	LOCALIZATION_ZORLEN["ImprovedAspectOfTheHawk"] = "Aspect du Faucon am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["ImprovedMendPet"] = "Gu\195\169rison du familier am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["MendPet"] = "Gu\195\169rison du familier"
	LOCALIZATION_ZORLEN["CallPet"] = "Appel du familier"
	LOCALIZATION_ZORLEN["RevivePet"] = "Ressusciter le familier"
	LOCALIZATION_ZORLEN["DismissPet"] = "Renvoyer le familier"
	LOCALIZATION_ZORLEN["AutoShot"] = "Tir automatique"
	LOCALIZATION_ZORLEN["MongooseBite"] = "Morsure de la mangouste"
	LOCALIZATION_ZORLEN["ArcaneShot"] = "Tir des arcanes"
	LOCALIZATION_ZORLEN["ConcussiveShot"] = "Trait de choc"
	LOCALIZATION_ZORLEN["RaptorStrike"] = "Attaque du raptor"
	LOCALIZATION_ZORLEN["SerpentSting"] = "Morsure de serpent"
	LOCALIZATION_ZORLEN["ViperSting"] = "Morsure de vip\195\168re"
	LOCALIZATION_ZORLEN["ScorpidSting"] = "Piq\195\187re de scorpide"
	LOCALIZATION_ZORLEN["DistractingShot"] = "Trait provocateur"
	LOCALIZATION_ZORLEN["AimedShot"] = "Vis\195\169e"
	LOCALIZATION_ZORLEN["HuntersMark"] = "Marque du chasseur"
	LOCALIZATION_ZORLEN["AspectOfTheHawk"] = "Aspect du Faucon"
	LOCALIZATION_ZORLEN["AspectOfTheMonkey"] = "Aspect du Singe"
	LOCALIZATION_ZORLEN["AspectOfTheCheetah"] = "Aspect du Gu\195\169pard"
	LOCALIZATION_ZORLEN["AspectOfThePack"] = "Aspect de la Meute"
	LOCALIZATION_ZORLEN["AspectOfTheWild"] = "Aspect de la Nature"
	LOCALIZATION_ZORLEN["AspectOfTheBeast"] = "Aspect de la B\195\170te"
	LOCALIZATION_ZORLEN["WingClip"] = "Coupure d'ailes"
	LOCALIZATION_ZORLEN["FreezingTrap"] = "Pi\195\168ge givrant"
	LOCALIZATION_ZORLEN["FrostTrap"] = "Pi\195\168ge de givre"
	LOCALIZATION_ZORLEN["ExplosiveTrap"] = "Pi\195\168ge explosif"
	LOCALIZATION_ZORLEN["ImmolationTrap"] = "Pi\195\168ge d'Immolation"
	LOCALIZATION_ZORLEN["FeignDeath"] = "Feindre la mort"
	LOCALIZATION_ZORLEN["Counterattack"] = "Contre-attaque"
	LOCALIZATION_ZORLEN["TranquilizingShot"] = "Tir tranquillisant"
	LOCALIZATION_ZORLEN["Disengage"] = "D\195\169sengagement"
	LOCALIZATION_ZORLEN["EyesOfTheBeast"] = "Oeil de la b\195\170te"
	LOCALIZATION_ZORLEN["BeastLore"] = "Connaissance des b\195\170tes"
	LOCALIZATION_ZORLEN["TrackBeasts"] = "Pistage des b\195\170tes"
	LOCALIZATION_ZORLEN["TrackDemons"] = "Pistage des d\195\169mons"
	LOCALIZATION_ZORLEN["TrackDragonkin"] = "Pistage des draconiens"
	LOCALIZATION_ZORLEN["TrackElementals"] = "Pistage des \195\169l\195\169mentaires"
	LOCALIZATION_ZORLEN["TrackGiants"] = "Pistage des g\195\169ants"
	LOCALIZATION_ZORLEN["TrackHumanoids"] = "Pistage des humano\195\175des"
	LOCALIZATION_ZORLEN["TrackUndead"] = "Pistage des morts-vivants"
	LOCALIZATION_ZORLEN["TrackHidden"] = "Pistage des camoufl\195\169s"
	LOCALIZATION_ZORLEN["BestialWrath"] = "Courroux bestial"
	LOCALIZATION_ZORLEN["TrueshotAura"] = "Aura de pr\195\169cision"
	LOCALIZATION_ZORLEN["ScatterShot"] = "Fl\195\168che de dispersion"
	LOCALIZATION_ZORLEN["WyvernSting"] = "Piq\195\187re de wyverne"
	LOCALIZATION_ZORLEN["Deterrence"] = "Dissuasion"
	LOCALIZATION_ZORLEN["EagleEye"] = "Oeil d'aigle"
	LOCALIZATION_ZORLEN["RapidFire"] = "Tir rapide"
	LOCALIZATION_ZORLEN["MultiShot"] = "Fl\195\168ches multiples"
	LOCALIZATION_ZORLEN["Flare"] = "Fus\195\169e \195\169clairante"
	LOCALIZATION_ZORLEN["ScareBeast"] = "Effrayer une b\195\170te"
	LOCALIZATION_ZORLEN["Volley"] = "Salve"
	LOCALIZATION_ZORLEN["Intimidation"] = "Intimidation"



-- Zorlen_Warlock.lua file Localization
	--LOCALIZATION_ZORLEN["SoulSiphon"] = ""
	--LOCALIZATION_ZORLEN["SeedOfCorruption"] = ""
	--LOCALIZATION_ZORLEN["FelArmor"] = ""
	--LOCALIZATION_ZORLEN["RitualOfSouls"] = ""
	--LOCALIZATION_ZORLEN["Soulshatter"] = ""
	--LOCALIZATION_ZORLEN["Incinerate"] = ""
	--LOCALIZATION_ZORLEN["UnstableAffliction"] = ""
	--LOCALIZATION_ZORLEN["DemonicAegis"] = ""
	--LOCALIZATION_ZORLEN["SummonFelGuard"] = ""
	--LOCALIZATION_ZORLEN["Shadowfury"] = ""
	
	--LOCALIZATION_ZORLEN["Bane"] = ""
	LOCALIZATION_ZORLEN["AmplifyCurse"] = "Mal\195\169diction amplifi\195\169e"
	LOCALIZATION_ZORLEN["CurseOfAgony"] = "Mal\195\169diction d'agonie"
	LOCALIZATION_ZORLEN["CurseOfDoom"] = "Mal\195\169diction funeste"
	LOCALIZATION_ZORLEN["CurseOfShadow"] = "Mal\195\169diction de l'ombre"
	LOCALIZATION_ZORLEN["CurseOfTheElements"] = "Mal\195\169diction des \195\169l\195\169ments"
	LOCALIZATION_ZORLEN["CurseOfWeakness"] = "Mal\195\169diction de faiblesse"
	LOCALIZATION_ZORLEN["CurseOfExhaustion"] = "Mal\195\169diction de fatigue"
	LOCALIZATION_ZORLEN["CurseOfRecklessness"] = "Mal\195\169diction de t\195\169m\195\169rit\195\169"
	LOCALIZATION_ZORLEN["CurseOfTongues"] = "Mal\195\169diction des langages"
	LOCALIZATION_ZORLEN["Corruption"] = "Corruption"
	LOCALIZATION_ZORLEN["ImprovedCorruption"] = "Corruption am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["Immolate"] = "Immolate"
	LOCALIZATION_ZORLEN["SiphonLife"] = "Siphon de vie"
	LOCALIZATION_ZORLEN["DrainLife"] = "Drain de vie"
	LOCALIZATION_ZORLEN["DrainMana"] = "Drain de mana"
	LOCALIZATION_ZORLEN["Hellfire"] = "lammes infernales"
	LOCALIZATION_ZORLEN["RainOfFire"] = "Pluie de feu"
	LOCALIZATION_ZORLEN["DrainSoul"] = "Siphon d'\195\162me"
	LOCALIZATION_ZORLEN["LifeTap"] = "Connexion"
	LOCALIZATION_ZORLEN["ImprovedLifeTap"] = "Connexion am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["DarkPact"] = "Pacte noir"
	LOCALIZATION_ZORLEN["Nightfall"] = "Cr\195\169puscule"
	LOCALIZATION_ZORLEN["ShadowBolt"] = "Trait de l'ombre"
	LOCALIZATION_ZORLEN["Banish"] = "Bannir"
	LOCALIZATION_ZORLEN["Conflagrate"] = "Conflagration"
	LOCALIZATION_ZORLEN["CreateFirestoneLesser"] = "Cr\195\169ation de Pierre de feu inf\195\169rieure"
	LOCALIZATION_ZORLEN["CreateFirestone"] = "Cr\195\169ation de Pierre de feu"
	LOCALIZATION_ZORLEN["CreateFirestoneGreater"] = "Cr\195\169ation de Pierre de feu sup\195\169rieure"
	LOCALIZATION_ZORLEN["CreateFirestoneMajor"] = "Cr\195\169ation de Pierre de feu majeure"
	LOCALIZATION_ZORLEN["CreateHealthstoneMinor"] = "Cr\195\169ation de Pierre de soins mineure"
	LOCALIZATION_ZORLEN["CreateHealthstoneLesser"] = "Cr\195\169ation de Pierre de soins inf\195\169rieure"
	LOCALIZATION_ZORLEN["CreateHealthstone"] = "Cr\195\169ation de Pierre de soins"
	LOCALIZATION_ZORLEN["CreateHealthstoneGreater"] = "Cr\195\169ation de Pierre de soins sup\195\169rieure"
	LOCALIZATION_ZORLEN["CreateHealthstoneMajor"] = "Cr\195\169ation de Pierre de soins majeure"
	LOCALIZATION_ZORLEN["CreateSoulstoneMinor"] = "Cr\195\169ation de Pierre d'\195\162me mineure"
	LOCALIZATION_ZORLEN["CreateSoulstoneLesser"] = "Cr\195\169ation de Pierre d'\195\162me inf\195\169rieure"
	LOCALIZATION_ZORLEN["CreateSoulstone"] = "Cr\195\169ation de Pierre d'\195\162me"
	LOCALIZATION_ZORLEN["CreateSoulstoneGreater"] = "Cr\195\169ation de Pierre d'\195\162me sup\195\169rieure"
	LOCALIZATION_ZORLEN["CreateSoulstoneMajor"] = "Cr\195\169ation de Pierre d'\195\162me majeure"
	LOCALIZATION_ZORLEN["CreateSpellstone"] = "Cr\195\169ation de Pierre de sort"
	LOCALIZATION_ZORLEN["CreateSpellstoneGreater"] = "Cr\195\169ation de Pierre de sort sup\195\169rieur"
	LOCALIZATION_ZORLEN["CreateSpellstoneMajor"] = "Cr\195\169ation de Pierre de sort majeure"
	LOCALIZATION_ZORLEN["DeathCoil"] = "Voile mortel"
	LOCALIZATION_ZORLEN["DemonArmor"] = "Armure d\195\169moniaque"
	LOCALIZATION_ZORLEN["DemonSkin"] = "Peau de d\195\169mon"
	LOCALIZATION_ZORLEN["DemonicSacrifice"] = "Sacrifice d\195\169moniaque"
	LOCALIZATION_ZORLEN["DetectLesserInvisibility"] = "D\195\169tection de l'invisibilit\195\169 inf\195\169rieure"
	LOCALIZATION_ZORLEN["DetectInvisibility"] = "D\195\169tection de l'invisibilit\195\169"
	LOCALIZATION_ZORLEN["DetectGreaterInvisibility"] = "D\195\169tection de l'invisibilit\195\169 sup\195\169rieure"
	LOCALIZATION_ZORLEN["EnslaveDemon"] = "Asservir d\195\169mon"
	LOCALIZATION_ZORLEN["EyeOfKilrogg"] = "Oeil de Kilrogg"
	LOCALIZATION_ZORLEN["Fear"] = "Peur"
	LOCALIZATION_ZORLEN["FelDomination"] = "Domination corrompue"
	LOCALIZATION_ZORLEN["HealthFunnel"] = "Captation de vie"
	LOCALIZATION_ZORLEN["HowlOfTerror"] = "Hurlement de terreur"
	LOCALIZATION_ZORLEN["Inferno"] = "Inferno"
	LOCALIZATION_ZORLEN["RitualOfDoom"] = "Rituel de mal\195\169diction"
	LOCALIZATION_ZORLEN["RitualOfSummoning"] = "Rituel d'invocation"
	LOCALIZATION_ZORLEN["SearingPain"] = "Douleur br\195\187lante"
	LOCALIZATION_ZORLEN["SenseDemons"] = "D\195\169tection des d\195\169mons"
	LOCALIZATION_ZORLEN["ShadowWard"] = "Gardien de l'ombre"
	LOCALIZATION_ZORLEN["Shadowburn"] = "Br\195\187lure de l'ombre"
	LOCALIZATION_ZORLEN["SoulFire"] = "Feu de l'\195\162me"
	LOCALIZATION_ZORLEN["SoulLink"] = "Lien spirituel"
	LOCALIZATION_ZORLEN["SummonDreadsteed"] = "Invocation d'un Destrier de l'Effroi"
	LOCALIZATION_ZORLEN["SummonFelhunter"] = "Invocation d'un chasseur corrompu"
	LOCALIZATION_ZORLEN["SummonFelsteed"] = "Invocation d'un palefroi corrompu"
	LOCALIZATION_ZORLEN["SummonImp"] = "Invocation d'un diablotin"
	LOCALIZATION_ZORLEN["SummonSuccubus"] = "Invocation d'une succube"
	LOCALIZATION_ZORLEN["SummonVoidwalker"] = "Invocation d'un marcheur du Vide"
	LOCALIZATION_ZORLEN["UnendingBreath"] = "Respiration interminable"
	LOCALIZATION_ZORLEN["FelConcentration"] = "Concentration corrompue"



-- Zorlen_Druid.lua file Localization
	LOCALIZATION_ZORLEN["TravelForm"] = "Forme de voyage"
	LOCALIZATION_ZORLEN["MoonkinForm"] = "Forme de s\195\169l\195\169nien"
	LOCALIZATION_ZORLEN["BearForm"] = "Forme d'ours"
	LOCALIZATION_ZORLEN["DireBearForm"] = "Forme d'ours redoutable"
	LOCALIZATION_ZORLEN["CatForm"] = "Forme de f\195\169lin"
	LOCALIZATION_ZORLEN["AquaticForm"] = "Forme aquatique"
	LOCALIZATION_ZORLEN["ChallengingRoar"] = "Rugissement provocateur"
	LOCALIZATION_ZORLEN["DemoralizingRoar"] = "Rugissement d\195\169moralisant"
	LOCALIZATION_ZORLEN["AbolishPoison"] = "Abolir le poison"
	LOCALIZATION_ZORLEN["Barkskin"] = "Ecorce"
	LOCALIZATION_ZORLEN["Bash"] = "Sonner"
	LOCALIZATION_ZORLEN["Claw"] = "Griffe"
	LOCALIZATION_ZORLEN["Cower"] = "D\195\169robade"
	LOCALIZATION_ZORLEN["Dash"] = "C\195\169l\195\169rit\195\169"
	LOCALIZATION_ZORLEN["Enrage"] = "Enrager"
	LOCALIZATION_ZORLEN["EntanglingRoots"] = "Sarments"
	LOCALIZATION_ZORLEN["FaerieFire"] = "Lucioles"
	--LOCALIZATION_ZORLEN["FaerieFireFeral"] = ""
	LOCALIZATION_ZORLEN["FeralCharge"] = "Charge farouche"
	LOCALIZATION_ZORLEN["FerociousBite"] = "Morsure f\195\169roce"
	LOCALIZATION_ZORLEN["FrenziedRegeneration"] = "R\195\169g\195\169n\195\169ration fr\195\169n\195\169tique"
	LOCALIZATION_ZORLEN["GiftOfTheWild"] = "Don du fauve"
	LOCALIZATION_ZORLEN["HealingTouch"] = "Toucher gu\195\169risseur"
	LOCALIZATION_ZORLEN["Hibernate"] = "Hibernation"
	LOCALIZATION_ZORLEN["Hurricane"] = "Ouragan"
	LOCALIZATION_ZORLEN["Innervate"] = "Innervation"
	LOCALIZATION_ZORLEN["InsectSwarm"] = "Essaim d'insectes"
	LOCALIZATION_ZORLEN["LeaderOfThePack"] = "Chef de la meute"
	LOCALIZATION_ZORLEN["MarkOfTheWild"] = "Marque du fauve"
	LOCALIZATION_ZORLEN["Maul"] = "Mutiler"
	LOCALIZATION_ZORLEN["Moonfire"] = "Eclat lunaire"
	LOCALIZATION_ZORLEN["NaturesGrasp"] = "Emprise de la nature"
	LOCALIZATION_ZORLEN["NaturesSwiftness"] = "Rapidit\195\169 de la nature"
	LOCALIZATION_ZORLEN["OmenOfClarity"] = "Augure de clart\195\169"
	LOCALIZATION_ZORLEN["Pounce"] = "Traquenard"
	LOCALIZATION_ZORLEN["Prowl"] = "R\195\180der"
	LOCALIZATION_ZORLEN["Rake"] = "Griffure"
	LOCALIZATION_ZORLEN["Ravage"] = "Ravage"
	LOCALIZATION_ZORLEN["Rebirth"] = "Renaissance"
	LOCALIZATION_ZORLEN["Regrowth"] = "R\195\169tablissement"
	LOCALIZATION_ZORLEN["Rejuvenation"] = "R\195\169cup\195\169ration"
	LOCALIZATION_ZORLEN["RemoveCurse"] = "D\195\169livrance de la mal\195\169diction"
	LOCALIZATION_ZORLEN["Rip"] = "D\195\169chirure"
	LOCALIZATION_ZORLEN["Shred"] = "Lambeau"
	LOCALIZATION_ZORLEN["SootheAnimal"] = "Apaiser les animaux"
	LOCALIZATION_ZORLEN["Starfire"] = "Feu stellaire"
	LOCALIZATION_ZORLEN["Swipe"] = "Balayage"
	LOCALIZATION_ZORLEN["Thorns"] = "Epines"
	LOCALIZATION_ZORLEN["TigersFury"] = "Fureur du tigre"
	LOCALIZATION_ZORLEN["TrackHumanoids"] = "Pistage des humano\195\175des"
	LOCALIZATION_ZORLEN["Tranquility"] = "Tranquillit\195\169"
	LOCALIZATION_ZORLEN["Wrath"] = "Col\195\168re"
	LOCALIZATION_ZORLEN["ImprovedWrath"] = "Col\195\168re am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["ImprovedNaturesGrasp"] = "Emprise de la nature am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["ImprovedEntanglingRoots"] = "Sarments am\195\169lior\195\169s"
	LOCALIZATION_ZORLEN["ImprovedMoonfire"] = "Eclat lunaire am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["NaturalWeapons"] = "Armes naturelles"
	LOCALIZATION_ZORLEN["NaturalShapeshifter"] = "Changeforme naturel"
	LOCALIZATION_ZORLEN["ImprovedThorns"] = "Epines am\195\169lior\195\169es"
	LOCALIZATION_ZORLEN["NaturesReach"] = "Allonge de la Nature"
	LOCALIZATION_ZORLEN["Vengeance"] = "Vengeance"
	LOCALIZATION_ZORLEN["ImprovedStarfire"] = "Feu stellaire am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["NaturesGrace"] = "Gr\195\162ce de la nature"
	LOCALIZATION_ZORLEN["Moonglow"] = "Lueur de la lune"
	LOCALIZATION_ZORLEN["Moonfury"] = "Fureur lunaire"
	LOCALIZATION_ZORLEN["Ferocity"] = "Ferocit\195\169"
	LOCALIZATION_ZORLEN["FeralAggression"] = "Agressivit\195\169 farouche"
	LOCALIZATION_ZORLEN["FeralInstinct"] = "Instinct farouche"
	LOCALIZATION_ZORLEN["BrutalImpact"] = "Impact brutal"
	LOCALIZATION_ZORLEN["ThickHide"] = "Peau \195\169paisse"
	LOCALIZATION_ZORLEN["FelineSwiftness"] = "C\195\169l\195\169rit\195\169 f\195\169line"
	LOCALIZATION_ZORLEN["SharpenedClaws"] = "Griffes aiguis\195\169es"
	LOCALIZATION_ZORLEN["ImprovedShred"] = "Lambeau am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["PredatoryStrikes"] = "Frappes de pr\195\169dateur"
	LOCALIZATION_ZORLEN["BloodFrenzy"] = "Fr\195\169n\195\169sie sanglante"
	LOCALIZATION_ZORLEN["PrimalFury"] = "Fureur primitive"
	LOCALIZATION_ZORLEN["SavageFury"] = "Frappes sauvages"
	LOCALIZATION_ZORLEN["HeartOfTheWild"] = "C\197\147ur de fauve"
	LOCALIZATION_ZORLEN["ImprovedMarkOfTheWild"] = "Marque du fauve am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["Furor"] = "Fureur"
	LOCALIZATION_ZORLEN["ImprovedHealingTouch"] = "Toucher gu\195\169risseur am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["NaturesFocus"] = "Focalisation de la nature"
	LOCALIZATION_ZORLEN["ImprovedEnrage"] = "Enrager am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["Reflection"] = "Renvoi"
	LOCALIZATION_ZORLEN["Subtlety"] = "Discr\195\169tion"
	LOCALIZATION_ZORLEN["TranquilSpirit"] = "Tranquillit\195\169 de l'esprit"
	LOCALIZATION_ZORLEN["ImprovedRejuvenation"] = "R\195\169cup\195\169ration am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["GiftOfNature"] = "Don de la Nature"
	LOCALIZATION_ZORLEN["ImprovedTranquility"] = "Tranquillit\195\169 am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["ImprovedRegrowth"] = "R\195\169tablissement am\195\169lior\195\169"
	--LOCALIZATION_ZORLEN["Swiftmend"] = ""



-- Zorlen_Mage.lua file Localization
	--LOCALIZATION_ZORLEN["ConjuredCinnamonRoll"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSweetRoll"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSourdough"] = ""
	--LOCALIZATION_ZORLEN["ConjuredPumpernickel"] = ""
	--LOCALIZATION_ZORLEN["ConjuredRye"] = ""
	--LOCALIZATION_ZORLEN["ConjuredBread"] = ""
	--LOCALIZATION_ZORLEN["ConjuredMuffin"] = ""
	--LOCALIZATION_ZORLEN["ConjuredCrystalWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSparklingWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredMineralWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredSpringWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredPurifiedWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredFreshWater"] = ""
	--LOCALIZATION_ZORLEN["ConjuredWater"] = ""
	LOCALIZATION_ZORLEN["AmplifyMagic"] = "Amplification de la magie"
	LOCALIZATION_ZORLEN["ArcaneBrilliance"] = "Illumination des arcanes"
	LOCALIZATION_ZORLEN["ArcaneExplosion"] = "Explosion des arcanes"
	LOCALIZATION_ZORLEN["ArcaneIntellect"] = "Intelligence des arcanes"
	LOCALIZATION_ZORLEN["ArcaneMissiles"] = "Projectiles des arcanes"
	LOCALIZATION_ZORLEN["ArcanePower"] = "Pouvoir des arcanes"
	LOCALIZATION_ZORLEN["BlastWave"] = "Vague explosive"
	LOCALIZATION_ZORLEN["Blink"] = "Transfert"
	LOCALIZATION_ZORLEN["Blizzard"] = "Blizzard"
	LOCALIZATION_ZORLEN["ColdSnap"] = "Morsure de glace"
	LOCALIZATION_ZORLEN["Combustion"] = "Combustion"
	LOCALIZATION_ZORLEN["ConeOfCold"] = "C\195\180ne de froid"
	LOCALIZATION_ZORLEN["ConjureFood"] = "Invocation de nourriture"
	LOCALIZATION_ZORLEN["ConjureManaAgate"] = "Invocation d'une agate de mana"
	LOCALIZATION_ZORLEN["ConjureManaJade"] = "Invocation d'une jade de mana"
	LOCALIZATION_ZORLEN["ConjureManaCitrine"] = "Invocation d'une citrine de mana"
	LOCALIZATION_ZORLEN["ConjureManaRuby"] = "Invocation d'un rubis de mana"
	LOCALIZATION_ZORLEN["ConjureWater"] = "Invocation d'eau"
	LOCALIZATION_ZORLEN["Counterspell"] = "Contresort"
	LOCALIZATION_ZORLEN["DampenMagic"] = "Att\195\169nuation de la magie"
	LOCALIZATION_ZORLEN["DetectMagic"] = "D\195\169tection de la magie"
	LOCALIZATION_ZORLEN["Evocation"] = "Evocation"
	LOCALIZATION_ZORLEN["FireBlast"] = "Trait de feu"
	LOCALIZATION_ZORLEN["FireWard"] = "Gardien de feu"
	LOCALIZATION_ZORLEN["Fireball"] = "Boule de feu"
	LOCALIZATION_ZORLEN["Flamestrike"] = "Choc de flammes"
	LOCALIZATION_ZORLEN["FrostArmor"] = "Armure de givre"
	LOCALIZATION_ZORLEN["FrostNova"] = "Nova de givre"
	LOCALIZATION_ZORLEN["FrostWard"] = "Gardien de givre"
	LOCALIZATION_ZORLEN["Frostbolt"] = "Eclair de givre"
	LOCALIZATION_ZORLEN["IceArmor"] = "Armure de glace"
	LOCALIZATION_ZORLEN["IceBarrier"] = "Barri\195\168re de glace"
	LOCALIZATION_ZORLEN["IceBlock"] = "Parade de glace"
	LOCALIZATION_ZORLEN["MageArmor"] = "Armure du mage"
	LOCALIZATION_ZORLEN["ManaShield"] = "Bouclier de mana"
	LOCALIZATION_ZORLEN["Polymorph"] = "M\195\169tamorphose"
	LOCALIZATION_ZORLEN["PortalDarnassus"] = "Portail : Darnassus"
	LOCALIZATION_ZORLEN["PortalIronforge"] = "Portail : Ironforge"
	LOCALIZATION_ZORLEN["PortalOrgrimmar"] = "Portail : Orgrimmar"
	LOCALIZATION_ZORLEN["PortalStormwind"] = "Portail\194\160: Stormwind"
	LOCALIZATION_ZORLEN["PortalThunderBluff"] = "Portail : Thunder Bluff"
	LOCALIZATION_ZORLEN["PortalUndercity"] = "Portail : Undercity"
	LOCALIZATION_ZORLEN["TeleportDarnassus"] = "T\195\169l\195\169portation\194\160: Darnassus"
	LOCALIZATION_ZORLEN["TeleportIronforge"] = "T\195\169l\195\169portation\194\160: Ironforge"
	LOCALIZATION_ZORLEN["TeleportOrgrimmar"] = "T\195\169l\195\169portation\194\160: Orgrimmar"
	LOCALIZATION_ZORLEN["TeleportStormwind"] = "T\195\169l\195\169portation\194\160: Stormwind"
	LOCALIZATION_ZORLEN["TeleportThunderBluff"] = "T\195\169l\195\169portation\194\160: Thunder Bluff"
	LOCALIZATION_ZORLEN["TeleportUndercity"] = "T\195\169l\195\169portation\194\160: Undercity"
	LOCALIZATION_ZORLEN["PresenceOfMind"] = "Pr\195\169sence spirituelle"
	LOCALIZATION_ZORLEN["Pyroblast"] = "Explosion pyrotechnique"
	LOCALIZATION_ZORLEN["RemoveLesserCurse"] = "D\195\169livrance de la mal\195\169diction mineure"
	LOCALIZATION_ZORLEN["Scorch"] = "Br\195\187lure"
	LOCALIZATION_ZORLEN["SlowFall"] = "Chute lente"



-- Zorlen_Paladin.lua file Localization
	LOCALIZATION_ZORLEN["BlessingOfFreedom"] = "B\195\169n\195\169diction de libert\195\169"
	LOCALIZATION_ZORLEN["BlessingOfKings"] = "B\195\169n\195\169diction des rois"
	LOCALIZATION_ZORLEN["BlessingOfLight"] = "B\195\169n\195\169diction de lumi\195\168re"
	LOCALIZATION_ZORLEN["BlessingOfMight"] = "B\195\169n\195\169diction de puissance"
	LOCALIZATION_ZORLEN["BlessingOfProtection"] = "B\195\169n\195\169diction de protection"
	LOCALIZATION_ZORLEN["BlessingOfSacrifice"] = "B\195\169n\195\169diction de sacrifice"
	LOCALIZATION_ZORLEN["BlessingOfSalvation"] = "B\195\169n\195\169diction de salut"
	LOCALIZATION_ZORLEN["BlessingOfSanctuary"] = "B\195\169n\195\169diction du sanctuaire"
	LOCALIZATION_ZORLEN["BlessingOfWisdom"] = "B\195\169n\195\169diction de sagesse"
	LOCALIZATION_ZORLEN["Cleanse"] = "Epuration"
	LOCALIZATION_ZORLEN["ConcentrationAura"] = "Aura de concentration"
	LOCALIZATION_ZORLEN["Consecration"] = "Cons\195\169cration"
	LOCALIZATION_ZORLEN["DevotionAura"] = "Aura de d\195\169votion"
	LOCALIZATION_ZORLEN["DivineFavor"] = "Faveur divine"
	LOCALIZATION_ZORLEN["DivineIntervention"] = "Intervention divine"
	LOCALIZATION_ZORLEN["DivineProtection"] = "Protection divine"
	LOCALIZATION_ZORLEN["DivineShield"] = "Bouclier divin"
	LOCALIZATION_ZORLEN["Exorcism"] = "Exorcisme"
	LOCALIZATION_ZORLEN["FireResistanceAura"] = "Aura de r\195\169sistance au Feu"
	LOCALIZATION_ZORLEN["FlashOfLight"] = "Eclair lumineux"
	LOCALIZATION_ZORLEN["FrostResistanceAura"] = "Aura de r\195\169sistance au Givre"
	LOCALIZATION_ZORLEN["GreaterBlessingOfKings"] = "B\195\169n\195\169diction des rois sup\195\169rieure"
	LOCALIZATION_ZORLEN["GreaterBlessingOfLight"] = "B\195\169n\195\169diction de lumi\195\168re sup\195\169rieure"
	LOCALIZATION_ZORLEN["GreaterBlessingOfMight"] = "B\195\169n\195\169diction de puissance sup\195\169rieure"
	LOCALIZATION_ZORLEN["GreaterBlessingOfSalvation"] = "B\195\169n\195\169diction de salut sup\195\169rieure"
	LOCALIZATION_ZORLEN["GreaterBlessingOfSanctuary"] = "B\195\169n\195\169diction du sanctuaire sup\195\169rieure"
	LOCALIZATION_ZORLEN["GreaterBlessingOfWisdom"] = "B\195\169n\195\169diction de sagesse sup\195\169rieure"
	LOCALIZATION_ZORLEN["HammerOfJustice"] = "Marteau de la justice"
	LOCALIZATION_ZORLEN["HammerOfWrath"] = "Marteau de courroux"
	LOCALIZATION_ZORLEN["HolyLight"] = "Lumi\195\168re sacr\195\169e"
	LOCALIZATION_ZORLEN["HolyShield"] = "Bouclier sacr\195\169"
	LOCALIZATION_ZORLEN["HolyShock"] = "Horion sacr\195\169"
	LOCALIZATION_ZORLEN["HolyWrath"] = "Col\195\168re divine"
	LOCALIZATION_ZORLEN["Judgement"] = "Jugement"
	LOCALIZATION_ZORLEN["LayOnHands"] = "Imposition des mains"
	LOCALIZATION_ZORLEN["Purify"] = "Purification"
	LOCALIZATION_ZORLEN["Redemption"] = "R\195\169demption"
	LOCALIZATION_ZORLEN["Repentance"] = "Repentir"
	LOCALIZATION_ZORLEN["RetributionAura"] = "Aura de vindicte"
	LOCALIZATION_ZORLEN["RighteousFury"] = "Fureur vertueuse"
	LOCALIZATION_ZORLEN["SanctityAura"] = "Aura de saintet\195\169"
	LOCALIZATION_ZORLEN["SealOfCommand"] = "Sceau d'autorit\195\169"
	LOCALIZATION_ZORLEN["SealOfJustice"] = "Sceau de justice"
	LOCALIZATION_ZORLEN["SealOfLight"] = "Sceau de lumi\195\168re"
	LOCALIZATION_ZORLEN["SealOfRighteousness"] = "Sceau de pi\195\169t\195\169"
	LOCALIZATION_ZORLEN["SealOfWisdom"] = "Sceau de sagesse"
	LOCALIZATION_ZORLEN["SealOfTheCrusader"] = "Sceau du Crois\195\169"
	LOCALIZATION_ZORLEN["SenseUndead"] = "D\195\169tection des morts-vivants"
	LOCALIZATION_ZORLEN["ShadowResistanceAura"] = "Aura de r\195\169sistance \195\160 l'Ombre"
	LOCALIZATION_ZORLEN["SummonCharger"] = "Invocation de destrier"
	LOCALIZATION_ZORLEN["SummonWarhorse"] = "Invocation d'un cheval de guerre"
	LOCALIZATION_ZORLEN["TurnUndead"] = "Renvoi des morts-vivants"



-- Zorlen_Priest.lua file Localization
	--LOCALIZATION_ZORLEN["PowerInfusion"] = ""
	--LOCALIZATION_ZORLEN["Lightwell"] = ""
	LOCALIZATION_ZORLEN["AbolishDisease"] = "Abolir maladie"
	LOCALIZATION_ZORLEN["CureDisease"] = "Gu\195\169rison des maladies"
	LOCALIZATION_ZORLEN["DesperatePrayer"] = "Pri\195\168re du d\195\169sespoir"
	LOCALIZATION_ZORLEN["DevouringPlague"] = "Peste d\195\169vorante"
	LOCALIZATION_ZORLEN["DispelMagic"] = "Dissipation de la magie"
	LOCALIZATION_ZORLEN["DivineSpirit"] = "Esprit divin"
	LOCALIZATION_ZORLEN["ElunesGrace"] = "Gr\195\162ce d'Elune"
	LOCALIZATION_ZORLEN["Fade"] = "Oubli"
	LOCALIZATION_ZORLEN["FearWard"] = "Gardien de peur"
	LOCALIZATION_ZORLEN["Feedback"] = "R\195\169action"
	LOCALIZATION_ZORLEN["FlashHeal"] = "Soins rapides"
	LOCALIZATION_ZORLEN["FocusedCasting"] = "Incantation focalis\195\169e"
	LOCALIZATION_ZORLEN["LesserHeal"] = "Soins inf\195\169rieurs"
	LOCALIZATION_ZORLEN["Heal"] = "Soins"
	LOCALIZATION_ZORLEN["GreaterHeal"] = "Soins sup\195\169rieurs"
	LOCALIZATION_ZORLEN["HexOfWeakness"] = "Mal\195\169fice de faiblesse"
	LOCALIZATION_ZORLEN["HolyFire"] = "Flammes sacr\195\169es"
	LOCALIZATION_ZORLEN["HolyNova"] = "Nova sacr\195\169e"
	LOCALIZATION_ZORLEN["InnerFire"] = "Feu int\195\169rieur"
	LOCALIZATION_ZORLEN["InnerFocus"] = "Focalisation am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["Levitate"] = "L\195\169vitation"
	LOCALIZATION_ZORLEN["ManaBurn"] = "Br\195\187lure de mana"
	LOCALIZATION_ZORLEN["MindBlast"] = "Attaque mentale"
	LOCALIZATION_ZORLEN["MindControl"] = "Contr\195\180le mental"
	LOCALIZATION_ZORLEN["MindFlay"] = "Fouet mental"
	LOCALIZATION_ZORLEN["MindSoothe"] = "Apaisement"
	LOCALIZATION_ZORLEN["MindVision"] = "Vision t\195\169l\195\169pathique"
	LOCALIZATION_ZORLEN["PowerWordFortitude"] = "Mot de pouvoir : Robustesse"
	LOCALIZATION_ZORLEN["PowerWordShield"] = "Mot de pouvoir : Bouclier"
	LOCALIZATION_ZORLEN["PrayerOfFortitude"] = "Pri\195\168re de robustesse"
	LOCALIZATION_ZORLEN["PrayerOfHealing"] = "Pri\195\168re de soins"
	LOCALIZATION_ZORLEN["PsychicScream"] = "Cri psychique"
	LOCALIZATION_ZORLEN["Renew"] = "R\195\169novation"
	LOCALIZATION_ZORLEN["Resurrection"] = "R\195\169surrection"
	LOCALIZATION_ZORLEN["ShackleUndead"] = "Entraves des morts-vivants"
	LOCALIZATION_ZORLEN["ShadowProtection"] = "Protection contre l'Ombre"
	LOCALIZATION_ZORLEN["ShadowWordPain"] = "Mot de l'ombre\194\160: Douleur"
	LOCALIZATION_ZORLEN["Shadowform"] = "Forme d'Ombre"
	LOCALIZATION_ZORLEN["Shadowguard"] = "Garde de l'ombre"
	LOCALIZATION_ZORLEN["Silence"] = "Silence"
	LOCALIZATION_ZORLEN["Smite"] = "Ch\195\162timent"
	LOCALIZATION_ZORLEN["SpiritOfRedemption"] = "Esprit de r\195\169demption"
	LOCALIZATION_ZORLEN["Starshards"] = "Eclats stellaires"
	LOCALIZATION_ZORLEN["TouchOfWeakness"] = "Toucher de faiblesse"
	LOCALIZATION_ZORLEN["VampiricEmbrace"] = "Etreinte vampirique"



-- Zorlen_Rogue.lua file Localization
	--LOCALIZATION_ZORLEN["DirtyDeeds"] = ""
	LOCALIZATION_ZORLEN["ImprovedSinisterStrike"] = "Attaque pernicieuse am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["CripplingPoison"] = "Poison affaiblissant"
	LOCALIZATION_ZORLEN["CripplingPoisonII"] = "Poison affaiblissant I"
	LOCALIZATION_ZORLEN["DeadlyPoison"] = "Poison mortel"
	LOCALIZATION_ZORLEN["DeadlyPoisonII"] = "Poison mortel II"
	LOCALIZATION_ZORLEN["DeadlyPoisonIII"] = "Poison mortel III"
	LOCALIZATION_ZORLEN["DeadlyPoisonIV"] = "Poison mortel IV"
	LOCALIZATION_ZORLEN["DeadlyPoisonV"] = "Poison mortel V"
	LOCALIZATION_ZORLEN["InstantPoison"] = "Poison instantan\195\169"
	LOCALIZATION_ZORLEN["InstantPoisonII"] = "Poison instantan\195\169 II"
	LOCALIZATION_ZORLEN["InstantPoisonIII"] = "Poison instantan\195\169 III"
	LOCALIZATION_ZORLEN["InstantPoisonIV"] = "Poison instantan\195\169 IV"
	LOCALIZATION_ZORLEN["InstantPoisonV"] = "Poison instantan\195\169 V"
	LOCALIZATION_ZORLEN["InstantPoisonVI"] = "Poison instantan\195\169 VI"
	LOCALIZATION_ZORLEN["MindnumbingPoison"] = "Poison de distraction mentale"
	LOCALIZATION_ZORLEN["MindnumbingPoisonII"] = "Poison de distraction mentale II"
	LOCALIZATION_ZORLEN["MindnumbingPoisonIII"] = "Poison de distraction mentale III"
	LOCALIZATION_ZORLEN["WoundPoison"] = "Poison douloureux"
	LOCALIZATION_ZORLEN["WoundPoisonII"] = "Poison douloureux II"
	LOCALIZATION_ZORLEN["WoundPoisonIII"] = "Poison douloureux III"
	LOCALIZATION_ZORLEN["WoundPoisonIV"] = "Poison douloureux IV"
	LOCALIZATION_ZORLEN["AdrenalineRush"] = "Adrenaline Rush"
	LOCALIZATION_ZORLEN["Ambush"] = "Embuscade"
	LOCALIZATION_ZORLEN["Backstab"] = "Attaque sournoise"
	LOCALIZATION_ZORLEN["BladeFlurry"] = "D\195\169luge de lames"
	LOCALIZATION_ZORLEN["Blind"] = "C\195\169cit\195\169"
	LOCALIZATION_ZORLEN["BlindingPowder"] = "Poudre aveuglante"
	LOCALIZATION_ZORLEN["CheapShot"] = "Coup bas"
	LOCALIZATION_ZORLEN["ColdBlood"] = "Sang froid"
	LOCALIZATION_ZORLEN["DetectTraps"] = "D\195\169tection des pi\195\168ges"
	LOCALIZATION_ZORLEN["DisarmTrap"] = "D\195\169sarmement de pi\195\168ge"
	LOCALIZATION_ZORLEN["Distract"] = "Distraction"
	LOCALIZATION_ZORLEN["Evasion"] = "Evasion"
	LOCALIZATION_ZORLEN["Eviscerate"] = "Evisc\195\169ration"
	LOCALIZATION_ZORLEN["ExposeArmor"] = "Exposer l'armure"
	LOCALIZATION_ZORLEN["Feint"] = "Feinte"
	LOCALIZATION_ZORLEN["Garrote"] = "Garrot"
	LOCALIZATION_ZORLEN["GhostlyStrike"] = "Frappe fantomatique"
	LOCALIZATION_ZORLEN["Gouge"] = "Suriner"
	LOCALIZATION_ZORLEN["Hemorrhage"] = "H\195\169morragie"
	LOCALIZATION_ZORLEN["Kick"] = "Coup de pied"
	LOCALIZATION_ZORLEN["KidneyShot"] = "Aiguillon perfide"
	LOCALIZATION_ZORLEN["PickLock"] = "Crochetage"
	LOCALIZATION_ZORLEN["PickPocket"] = "Vol \195\160 la tire"
	LOCALIZATION_ZORLEN["Premeditation"] = "Pr\195\169m\195\169ditation"
	LOCALIZATION_ZORLEN["Preparation"] = "Pr\195\169paration"
	LOCALIZATION_ZORLEN["RelentlessStrikes"] = "Frappes implacables"
	LOCALIZATION_ZORLEN["Riposte"] = "Riposte"
	LOCALIZATION_ZORLEN["Rupture"] = "Rupture"
	LOCALIZATION_ZORLEN["Sap"] = "Assommer"
	LOCALIZATION_ZORLEN["SinisterStrike"] = "Attaque pernicieuse"
	LOCALIZATION_ZORLEN["SliceAndDice"] = "D\195\169biter"
	LOCALIZATION_ZORLEN["Sprint"] = "Sprint"
	LOCALIZATION_ZORLEN["Stealth"] = "Camouflage"
	LOCALIZATION_ZORLEN["Vanish"] = "Disparition"



-- Zorlen_Shaman.lua file Localization
	LOCALIZATION_ZORLEN["DiseaseCleansingTotem"] = "Totem de Purification des maladies"
	LOCALIZATION_ZORLEN["EarthbindTotem"] = "Totem de lien terrestre"
	LOCALIZATION_ZORLEN["FireNovaTotem"] = "Totem Nova de feu"
	LOCALIZATION_ZORLEN["FireResistanceTotem"] = "Totem de r\195\169sistance au feu"
	LOCALIZATION_ZORLEN["FlametongueTotem"] = "Totem Langue de feu"
	LOCALIZATION_ZORLEN["FrostResistanceTotem"] = "Totem de r\195\169sistance au Givre"
	LOCALIZATION_ZORLEN["GraceOfAirTotem"] = "Totem de Gr\195\162ce a\195\169rienne"
	LOCALIZATION_ZORLEN["GroundingTotem"] = "Totem de Gl\195\168be"
	LOCALIZATION_ZORLEN["HealingStreamTotem"] = "Totem gu\195\169risseur"
	LOCALIZATION_ZORLEN["MagmaTotem"] = "Totem de Magma"
	LOCALIZATION_ZORLEN["ManaSpringTotem"] = "Totem Fontaine de mana"
	LOCALIZATION_ZORLEN["ManaTideTotem"] = "Totem de Vague de mana"
	LOCALIZATION_ZORLEN["NatureResistanceTotem"] = "Totem de r\195\169sistance \195\160 la Nature"
	LOCALIZATION_ZORLEN["PoisonCleansingTotem"] = "Totem de Purification du poison"
	LOCALIZATION_ZORLEN["SearingTotem"] = "Totem incendiaire"
	LOCALIZATION_ZORLEN["SentryTotem"] = "Totem Sentinelle"
	LOCALIZATION_ZORLEN["StoneclawTotem"] = "Totem de Griffes de pierre"
	LOCALIZATION_ZORLEN["StoneskinTotem"] = "Totem de Peau de pierre"
	LOCALIZATION_ZORLEN["StrengthOfEarthTotem"] = "Totem de Force de la Terre"
	LOCALIZATION_ZORLEN["TremorTotem"] = "Totem de S\195\169isme"
	LOCALIZATION_ZORLEN["WindfuryTotem"] = "Totem Furie-des-vents"
	LOCALIZATION_ZORLEN["WindwallTotem"] = "Totem de Mur des vents"
	LOCALIZATION_ZORLEN["EarthShock"] = "Horion de terre"
	LOCALIZATION_ZORLEN["FlameShock"] = "Horion de flammes"
	LOCALIZATION_ZORLEN["FrostShock"] = "Horion de givre"
	LOCALIZATION_ZORLEN["FlametongueWeapon"] = "Arme Langue de feu"
	LOCALIZATION_ZORLEN["FrostbrandWeapon"] = "Arme de givre"
	LOCALIZATION_ZORLEN["RockbiterWeapon"] = "Arme Croque-roc"
	LOCALIZATION_ZORLEN["WindfuryWeapon"] = "Arme Furie-des-vents"
	LOCALIZATION_ZORLEN["AncestralSpirit"] = "Esprit ancestral"
	LOCALIZATION_ZORLEN["AstralRecall"] = "Rappel astral"
	LOCALIZATION_ZORLEN["ChainHeal"] = "Salve de gu\195\169rison"
	LOCALIZATION_ZORLEN["ChainLightning"] = "Cha\195\174ne d'\195\169clairs"
	LOCALIZATION_ZORLEN["CureDisease"] = "Gu\195\169rison des maladies"
	LOCALIZATION_ZORLEN["CurePoison"] = "Gu\195\169rison du poison"
	LOCALIZATION_ZORLEN["ElementalFocus"] = "Focalisation \195\169l\195\169mentaire"
	LOCALIZATION_ZORLEN["ElementalMastery"] = "Ma\195\174trise \195\169l\195\169mentaire"
	LOCALIZATION_ZORLEN["FarSight"] = "Double vue"
	LOCALIZATION_ZORLEN["GhostWolf"] = "Loup fant\195\180me"
	LOCALIZATION_ZORLEN["LesserHealingWave"] = "Vague de soins inf\195\169rieurs"
	LOCALIZATION_ZORLEN["HealingWave"] = "Vague de soins"
	LOCALIZATION_ZORLEN["LightningBolt"] = "Eclair"
	LOCALIZATION_ZORLEN["LightningShield"] = "Bouclier de foudre"
	LOCALIZATION_ZORLEN["NaturesSwiftness"] = "Rapidit\195\169 de la nature"
	LOCALIZATION_ZORLEN["Purge"] = "Expiation"
	LOCALIZATION_ZORLEN["Reincarnation"] = "R\195\169incarnation"
	LOCALIZATION_ZORLEN["Stormstrike"] = "Courroux naturel"
	LOCALIZATION_ZORLEN["WaterBreathing"] = "Respiration aquatique"
	LOCALIZATION_ZORLEN["WaterWalking"] = "Marcher sur l\226\128\153eau"



-- Zorlen_Warrior.lua file Localization
	--LOCALIZATION_ZORLEN["Devastate"] = ""
	--LOCALIZATION_ZORLEN["ImprovedWhirlwind"] = ""
	--LOCALIZATION_ZORLEN["FocusedRage"] = ""
	--LOCALIZATION_ZORLEN["CommandingShout"] = ""
	--LOCALIZATION_ZORLEN["SpellReflection"] = ""
	--LOCALIZATION_ZORLEN["Intervene"] = ""
	--LOCALIZATION_ZORLEN["VictoryRush"] = ""
	--LOCALIZATION_ZORLEN["EndlessRage"] = ""
	--LOCALIZATION_ZORLEN["Rampage"] = ""
	
	LOCALIZATION_ZORLEN["ImprovedBloodrage"] = "Rage sanguinaire am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["ImprovedOverpower"] = "Fulgurance am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["ImprovedBerserkerRage"] = "Rage berserker am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["ImprovedExecute"] = "Ex\195\169cution am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["Execute"] = "Ex\195\169cution"
	LOCALIZATION_ZORLEN["ImprovedHeroicStrike"] = "Frappe h\195\169ro\195\175que am\195\169lior\195\169e"
	LOCALIZATION_ZORLEN["HeroicStrike"] = "Frappe h\195\169ro\195\175que"
	LOCALIZATION_ZORLEN["ImprovedSunderArmor"] = "Fracasser armure am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["SunderArmor"] = "Fracasser armure"
	LOCALIZATION_ZORLEN["ImprovedThunderClap"] = "Coup de tonnerre am\195\169lior\195\169"
	LOCALIZATION_ZORLEN["ThunderClap"] = "Coup de tonnerre"
	LOCALIZATION_ZORLEN["MortalStrike"] = "Frappe mortelle"
	LOCALIZATION_ZORLEN["Bloodthirst"] = "Sanguinaire"
	LOCALIZATION_ZORLEN["ShieldSlam"] = "Heurt de bouclier"
	LOCALIZATION_ZORLEN["Charge"] = "Charge"
	LOCALIZATION_ZORLEN["Taunt"] = "Provocation"
	LOCALIZATION_ZORLEN["Intercept"] = "Interception"
	LOCALIZATION_ZORLEN["Overpower"] = "Fulgurance"
	LOCALIZATION_ZORLEN["Revenge"] = "Vengeance"
	LOCALIZATION_ZORLEN["Rend"] = "Pourfendre"
	LOCALIZATION_ZORLEN["Hamstring"] = "Brise-genou"
	LOCALIZATION_ZORLEN["ShieldBash"] = "Coup de bouclier"
	LOCALIZATION_ZORLEN["Pummel"] = "Vol\195\169e de coups"
	LOCALIZATION_ZORLEN["ShieldBlock"] = "Ma\195\174trise du blocage"
	LOCALIZATION_ZORLEN["DemoralizingShout"] = "Cri d\195\169moralisant"
	LOCALIZATION_ZORLEN["BattleShout"] = "Cri de guerre"
	LOCALIZATION_ZORLEN["BerserkerRage"] = "Rage berserker"
	LOCALIZATION_ZORLEN["Enrage"] = "Enrager"
	LOCALIZATION_ZORLEN["DefensiveStance"] = "Posture d\195\169fensive"
	LOCALIZATION_ZORLEN["BattleStance"] = "Posture de combat"
	LOCALIZATION_ZORLEN["BerserkerStance"] = "Posture berserker"
	LOCALIZATION_ZORLEN["AngerManagement"] = "Ma\195\174trise de la Rage"
	LOCALIZATION_ZORLEN["Bloodrage"] = "Rage sanguinaire"
	LOCALIZATION_ZORLEN["ChallengingShout"] = "Cri de d\195\169fi"
	LOCALIZATION_ZORLEN["Cleave"] = "Encha\195\174nement"
	LOCALIZATION_ZORLEN["ConcussionBlow"] = "Bourrasque"
	LOCALIZATION_ZORLEN["DeathWish"] = "Souhait mortel"
	LOCALIZATION_ZORLEN["Disarm"] = "D\195\169sarmement"
	LOCALIZATION_ZORLEN["IntimidatingShout"] = "Cri d'intimidation"
	LOCALIZATION_ZORLEN["LastStand"] = "Dernier rempart"
	LOCALIZATION_ZORLEN["MockingBlow"] = "Coup railleur"
	LOCALIZATION_ZORLEN["PiercingHowl"] = "Hurlement per\195\167ant"
	LOCALIZATION_ZORLEN["Recklessness"] = "T\195\169m\195\169rit\195\169"
	LOCALIZATION_ZORLEN["Retaliation"] = "Repr\195\169sailles"
	LOCALIZATION_ZORLEN["ShieldWall"] = "Mur protecteur"
	LOCALIZATION_ZORLEN["Slam"] = "Heurtoir"
	LOCALIZATION_ZORLEN["SweepingStrikes"] = "Attaques circulaires"
	LOCALIZATION_ZORLEN["Whirlwind"] = "Tourbillon"
	LOCALIZATION_ZORLEN["TacticalMastery"] = "Ma\195\174trise tactique"



-- Fire Immune MOB's
 -- Molten Core
	LOCALIZATION_ZORLEN["Firelord"] = "Seigneur du feu"
	LOCALIZATION_ZORLEN["Firewalker"] = "Marchefeu"
	LOCALIZATION_ZORLEN["Flameguard"] = "Garde des flammes"
	LOCALIZATION_ZORLEN["LavaSpawn"] = "El\195\169mentaire de lave"
	LOCALIZATION_ZORLEN["BaronGeddon"] = "Baron Geddon"
	LOCALIZATION_ZORLEN["Ragnaros"] = "Ragnaros"
 -- Upper Blackrock Spire
	LOCALIZATION_ZORLEN["PyroguardEmberseer"] = "Pyrogarde Proph\195\168te ardent"
 -- Blackrock Depths
	LOCALIZATION_ZORLEN["Fireguard"] = "Garde du feu"
	LOCALIZATION_ZORLEN["FireguardDestroyer"] = "Destructeur garde du feu"
	LOCALIZATION_ZORLEN["BlazingFireguard"] = "Garde du feu flamboyant"
	LOCALIZATION_ZORLEN["AmbassadorFlamelash"] = "Ambassadeur Flamelash"
	LOCALIZATION_ZORLEN["LordIncendius"] = "Seigneur Incendius"
 --Searing Gorge
	LOCALIZATION_ZORLEN["BlazingElemental"] = "El\195\169mentaire flamboyant"
	LOCALIZATION_ZORLEN["InfernoElemental"] = "El\195\169mentaire infernal"
 --Un'Goro Crater
	--LOCALIZATION_ZORLEN["ScorchingElemental"] = ""
	--LOCALIZATION_ZORLEN["LivingBlaze"] = ""
	--LOCALIZATION_ZORLEN["Blazerunner"] = ""

-- Drain Life Immune MOB's
 -- Blackrock Depths
	LOCALIZATION_ZORLEN["MoltenWarGolem"] = "Golem de lave de guerre"
	LOCALIZATION_ZORLEN["PanzorTheInvincible"] = "Panzor l'Invincible"
 --Searing Gorge
	LOCALIZATION_ZORLEN["HeavyWarGolem"] = "Golem de guerre lourd"
	LOCALIZATION_ZORLEN["FaultyWarGolem"] = "Golem de guerre d\195\169faillant"
	LOCALIZATION_ZORLEN["TemperedWarGolem"] = "Golem de guerre"
	LOCALIZATION_ZORLEN["RagereaverGolem"] = "Golem ravageur enrag\195\169"
