
Zorlen_EN_FileBuildNumber = 687

-- English Translation
-- If you want to translate this to another language, make sure the names of buffs and abilities are *EXACTLY* the same as in-game. Spelling, punctuation, upper/lowercase letters, etc. MUST BE EXACT. Also, any 'foreign' characters must be converted to UNICODE.
-- Unicode resource:
-- http://www.utf8-chartable.de/unicode-utf8-table.pl?start=128&number=1024&utf8=dec
-- http://home.tiscali.nl/t876506/utf8tbl.html
-- http://www.allegro-c.de/unicode/zcodes.htm
-- You will need to use the UTF-8 decimal numbers with a back slash in front of them in the same way that Å is represented by: \195\133


-- To lower the upkeep we will not be adding Localization for english words that do not break compatibility in other game clients.
-- This Localization is only added for compatibility so that it may work in non english game clients and not as a translation.

LOCALIZATION_ZORLEN = {}

-- All file Localization
	LOCALIZATION_ZORLEN["EatMacroName"] = "Zorlen Eat"
	LOCALIZATION_ZORLEN["DrinkMacroName"] = "Zorlen Drink"
	LOCALIZATION_ZORLEN["Conjured"] = "Conjured"
	LOCALIZATION_ZORLEN["Water"] = "Water"
	LOCALIZATION_ZORLEN["AllConjuredWater"] = "Conjured.*Water"
	LOCALIZATION_ZORLEN["well_fed"] = "well fed"
	LOCALIZATION_ZORLEN["HitsOrCritsArray"] = {"Your (.+) hits (.*) for (%d+)", "Your (.+) crits (.*) for (%d+)"}
	LOCALIZATION_ZORLEN["EnemyDies"] = "^(.*) dies%.$"
	LOCALIZATION_ZORLEN["Rank"] = "Rank"
	LOCALIZATION_ZORLEN["sit"] = "sit"
	LOCALIZATION_ZORLEN["You_dodge"] = "^(.*) attacks. You dodge%.$"
	LOCALIZATION_ZORLEN["ImmuneArray"] = {"Your (.+) failed. (.*) is immune."}
	LOCALIZATION_ZORLEN["no_weapons_equipped"] = "You fail to perform (.+): Target has no weapons equipped."
	LOCALIZATION_ZORLEN["dodged"] = "Your (.+) was dodged by (.*)."
	LOCALIZATION_ZORLEN["dodges"] = "You attack. (.*) dodges."
	LOCALIZATION_ZORLEN["pet_is_not_dead"] = "Your pet is not dead"
	LOCALIZATION_ZORLEN["pet_is_dead"] = "Your pet is dead"
	LOCALIZATION_ZORLEN["You fail to perform (.+): A more powerful spell is already active."] = "You fail to perform (.+): A more powerful spell is already active."
	LOCALIZATION_ZORLEN["Asleep"] = "Asleep"
	LOCALIZATION_ZORLEN["RequiresLevel"] = "Requires Level"
	
	LOCALIZATION_ZORLEN["GreaterHealingWard"] = "Greater Healing Ward"
	LOCALIZATION_ZORLEN["LavaSpoutTotem"] = "Lava Spout Totem"
	
	LOCALIZATION_ZORLEN["HealingBonusWordsArray"] = {"Healing", "Healing Spells", "Increases Healing"}
	LOCALIZATION_ZORLEN["HealingBonusPhraseArray"] = {"Increases healing done by spells and effects by up to (%d+)%."}
	
	LOCALIZATION_ZORLEN["SpellDamageAndHealingBonusWordsArray"] = {"Healing and Spell Damage", "Damage and Healing Spells", "Spell Damage and Healing"}
	LOCALIZATION_ZORLEN["SpellDamageAndHealingBonusPhraseArray"] = {"Increases damage and healing done by magical spells and effects by up to (%d+)%."}
	
	LOCALIZATION_ZORLEN["SpellDamageBonusWordsArray"] = {"Spell Damage"}
	LOCALIZATION_ZORLEN["SpellDamageBonusPhraseArray"] = {"Increases damage done by magical spells and effects by up to (%d+)%."}
	LOCALIZATION_ZORLEN["BrilliantWizardOil"] = "Brilliant Wizard Oil" -- 36 Spell Damage
	LOCALIZATION_ZORLEN["WizardOil"] = "Wizard Oil" -- 24 Spell Damage
	LOCALIZATION_ZORLEN["LesserWizardOil"] = "Lesser Wizard Oil" -- 16 Spell Damage
	LOCALIZATION_ZORLEN["MinorWizardOil"] = "Minor Wizard Oil" -- 8 Spell Damage
	LOCALIZATION_ZORLEN["SupremePower"] = "Supreme Power" -- 150 Spell Damage
	LOCALIZATION_ZORLEN["GreaterArcaneElixir"] = "Greater Arcane Elixir" -- 35 Spell Damage
	LOCALIZATION_ZORLEN["ArcaneElixir"] = "Arcane Elixir" -- 20 Spell Damage
	
	LOCALIZATION_ZORLEN["ShadowDamageBonusWordsArray"] = {"Shadow Damage"}
	LOCALIZATION_ZORLEN["ShadowDamageBonusPhraseArray"] = {"Increases damage done by Shadow spells and effects by up to (%d+)%."}
	LOCALIZATION_ZORLEN["ShadowPower"] = "Shadow Power" -- 40 Shadow Damage
	
-- Battleground Names
	LOCALIZATION_ZORLEN["WarsongGulch"] = "Warsong Gulch"
	LOCALIZATION_ZORLEN["AlteracValley"] = "Alterac Valley"
	LOCALIZATION_ZORLEN["ArathiBasin"] = "Arathi Basin"
	
-- Raid Target Names
	LOCALIZATION_ZORLEN["WhiteSkull"] = "White Skull"
	LOCALIZATION_ZORLEN["RedX"] = "Red X"
	LOCALIZATION_ZORLEN["BlueSquare"] = "Blue Square"
	LOCALIZATION_ZORLEN["WhiteCrescentMoon"] = "White Crescent Moon"
	LOCALIZATION_ZORLEN["GreenTriangle"] = "Green Triangle"
	LOCALIZATION_ZORLEN["PurpleDiamond"] = "Purple Diamond"
	LOCALIZATION_ZORLEN["OrangeCircle"] = "Orange Circle"
	LOCALIZATION_ZORLEN["YellowStar"] = "Yellow Star"

-- Example: /script Zorlen_GiveName_OffHandType()
-- The example above will give the name required for ["Shields
-- You must have a shield equipped to get the correct name.
-- You can also get the correct name from the auction house filters under the Armor section.
	LOCALIZATION_ZORLEN["Shields"] = "Shields"
	
-- Example: /script Zorlen_GiveName_MainHandType()
-- The example above will give the name required for the weapons below.
-- You must have the weapon equipped to get the correct name.
-- You can also get the correct names from the auction house filters under the Weapon section.
	LOCALIZATION_ZORLEN["Daggers"] = "Daggers"
	LOCALIZATION_ZORLEN["One-Handed Swords"] = "One-Handed Swords"
	LOCALIZATION_ZORLEN["Two-Handed Swords"] = "Two-Handed Swords"
	LOCALIZATION_ZORLEN["One-Handed Axes"] = "One-Handed Axes"
	LOCALIZATION_ZORLEN["Two-Handed Axes"] = "Two-Handed Axes"
	LOCALIZATION_ZORLEN["One-Handed Maces"] = "One-Handed Maces"
	LOCALIZATION_ZORLEN["Two-Handed Maces"] = "Two-Handed Maces"
	LOCALIZATION_ZORLEN["Polearms"] = "Polearms"
	LOCALIZATION_ZORLEN["Staves"] = "Staves"
	LOCALIZATION_ZORLEN["Fist Weapons"] = "Fist Weapons"
	LOCALIZATION_ZORLEN["Fishing Pole"] = "Fishing Pole"

-- Item Sub Types:
	LOCALIZATION_ZORLEN["Bag"] = "Bag"
	LOCALIZATION_ZORLEN["Soul Bag"] = "Soul Bag"


-- Food Item Tool Tip Text:
	LOCALIZATION_ZORLEN["FoodToolTipTextAny"] = "Use: Restores.*(%d+).*health.*(%d+) sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText3180"] = "Use: Restores 3180 health over 30 sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText2148"] = "Use: Restores 2148 health over 30 sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText1392"] = "Use: Restores 1392 health over 30 sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText874"] = "Use: Restores 874 health over 27 sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText552"] = "Use: Restores 552 health over 24 sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText243"] = "Use: Restores 243 health over 21 sec.*eating"
	LOCALIZATION_ZORLEN["FoodToolTipText61"] = "Use: Restores 61 health over 18 sec.*eating"
-- Drink Item Tool Tip Text:
	LOCALIZATION_ZORLEN["DrinkToolTipTextAny"] = "Use: Restores.*(%d+).*mana.*(%d+) sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText4200"] = "Use: Restores 4200 mana over 30 sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText2934"] = "Use: Restores 2934 mana over 30 sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText1992"] = "Use: Restores 1992 mana over 30 sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText1344"] = "Use: Restores 1344 mana over 27 sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText835"] = "Use: Restores 835 mana over 24 sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText436"] = "Use: Restores 436 mana over 21 sec.*drinking"
	LOCALIZATION_ZORLEN["DrinkToolTipText151"] = "Use: Restores 151 mana over 18 sec.*drinking"



-- Zorlen_Other.lua file Localization
	LOCALIZATION_ZORLEN["Attack"] = "Attack"
	LOCALIZATION_ZORLEN["Throw"] = "Throw"
	LOCALIZATION_ZORLEN["ShootBow"] = "Shoot Bow"
	LOCALIZATION_ZORLEN["ShootCrossbow"] = "Shoot Crossbow"
	LOCALIZATION_ZORLEN["ShootGun"] = "Shoot Gun"
	LOCALIZATION_ZORLEN["Shoot"] = "Shoot"
-- Human Racial
	LOCALIZATION_ZORLEN["Perception"] = "Perception"
-- Dwarf Racial
	LOCALIZATION_ZORLEN["FindTreasure"] = "Find Treasure"
	LOCALIZATION_ZORLEN["Stoneform"] = "Stoneform"
-- Gnome Racial
	LOCALIZATION_ZORLEN["EscapeArtist"] = "Escape Artist"
-- Night Elf Racial
	LOCALIZATION_ZORLEN["Shadowmeld"] = "Shadowmeld"
-- Orc Racial
	LOCALIZATION_ZORLEN["BloodFury"] = "Blood Fury"
-- Undead Racial
	LOCALIZATION_ZORLEN["Cannibalize"] = "Cannibalize"
	LOCALIZATION_ZORLEN["WillOfTheForsaken"] = "Will of the Forsaken"
-- Tauren Racial
	LOCALIZATION_ZORLEN["WarStomp"] = "War Stomp"
-- Troll Racial
	LOCALIZATION_ZORLEN["Berserking"] = "Berserking"



-- Zorlen_Pets.lua file Localization
-- Hunter Pets
	LOCALIZATION_ZORLEN["Dash"] = "Dash"
	LOCALIZATION_ZORLEN["Dive"] = "Dive"
	LOCALIZATION_ZORLEN["Bite"] = "Bite"
	LOCALIZATION_ZORLEN["Claw"] = "Claw"
	LOCALIZATION_ZORLEN["Cower"] = "Cower"
	LOCALIZATION_ZORLEN["Growl"] = "Growl"
	LOCALIZATION_ZORLEN["Prowl"] = "Prowl"
	LOCALIZATION_ZORLEN["Charge"] = "Charge"
	LOCALIZATION_ZORLEN["Screech"] = "Screech"
	LOCALIZATION_ZORLEN["FuriousHowl"] = "Furious Howl"
	LOCALIZATION_ZORLEN["LightningBreath"] = "Lightning Breath"
	LOCALIZATION_ZORLEN["ShellShield"] = "Shell Shield"
	LOCALIZATION_ZORLEN["Thunderstomp"] = "Thunderstomp"
	LOCALIZATION_ZORLEN["ScorpidPoison"] = "Scorpid Poison"
-- Warlock Pets
	LOCALIZATION_ZORLEN["Felhunter"] = "Felhunter"
	LOCALIZATION_ZORLEN["Imp"] = "Imp"
	LOCALIZATION_ZORLEN["Succubus"] = "Succubus"
	LOCALIZATION_ZORLEN["Voidwalker"] = "Voidwalker"
	LOCALIZATION_ZORLEN["BloodPact"] = "Blood Pact"
	LOCALIZATION_ZORLEN["FireShield"] = "Fire Shield"
	LOCALIZATION_ZORLEN["Firebolt"] = "Firebolt"
	LOCALIZATION_ZORLEN["PhaseShift"] = "Phase Shift"
	LOCALIZATION_ZORLEN["ConsumeShadows"] = "Consume Shadows"
	LOCALIZATION_ZORLEN["Sacrifice"] = "Sacrifice"
	LOCALIZATION_ZORLEN["Suffering"] = "Suffering"
	LOCALIZATION_ZORLEN["Torment"] = "Torment"
	LOCALIZATION_ZORLEN["DevourMagic"] = "Devour Magic"
	LOCALIZATION_ZORLEN["Paranoia"] = "Paranoia"
	LOCALIZATION_ZORLEN["SpellLock"] = "Spell Lock"
	LOCALIZATION_ZORLEN["TaintedBlood"] = "Tainted Blood"
	LOCALIZATION_ZORLEN["LashOfPain"] = "Lash of Pain"
	LOCALIZATION_ZORLEN["Seduction"] = "Seduction"
	LOCALIZATION_ZORLEN["SoothingKiss"] = "Soothing Kiss"
	LOCALIZATION_ZORLEN["LesserInvisibility"] = "Lesser Invisibility"



-- Zorlen_Hunter.lua file Localization
	LOCALIZATION_ZORLEN["FeedPet"] = "Feed Pet"
	LOCALIZATION_ZORLEN["ImprovedAspectOfTheHawk"] = "Improved Aspect of the Hawk"
	LOCALIZATION_ZORLEN["ImprovedMendPet"] = "Improved Mend Pet"
	LOCALIZATION_ZORLEN["MendPet"] = "Mend Pet"
	LOCALIZATION_ZORLEN["CallPet"] = "Call Pet"
	LOCALIZATION_ZORLEN["RevivePet"] = "Revive Pet"
	LOCALIZATION_ZORLEN["DismissPet"] = "Dismiss Pet"
	LOCALIZATION_ZORLEN["AutoShot"] = "Auto Shot"
	LOCALIZATION_ZORLEN["MongooseBite"] = "Mongoose Bite"
	LOCALIZATION_ZORLEN["ArcaneShot"] = "Arcane Shot"
	LOCALIZATION_ZORLEN["ConcussiveShot"] = "Concussive Shot"
	LOCALIZATION_ZORLEN["RaptorStrike"] = "Raptor Strike"
	LOCALIZATION_ZORLEN["SerpentSting"] = "Serpent Sting"
	LOCALIZATION_ZORLEN["ViperSting"] = "Viper Sting"
	LOCALIZATION_ZORLEN["ScorpidSting"] = "Scorpid Sting"
	LOCALIZATION_ZORLEN["DistractingShot"] = "Distracting Shot"
	LOCALIZATION_ZORLEN["AimedShot"] = "Aimed Shot"
	LOCALIZATION_ZORLEN["HuntersMark"] = "Hunter's Mark"
	LOCALIZATION_ZORLEN["AspectOfTheHawk"] = "Aspect of the Hawk"
	LOCALIZATION_ZORLEN["AspectOfTheMonkey"] = "Aspect of the Monkey"
	LOCALIZATION_ZORLEN["AspectOfTheCheetah"] = "Aspect of the Cheetah"
	LOCALIZATION_ZORLEN["AspectOfThePack"] = "Aspect of the Pack"
	LOCALIZATION_ZORLEN["AspectOfTheWild"] = "Aspect of the Wild"
	LOCALIZATION_ZORLEN["AspectOfTheBeast"] = "Aspect of the Beast"
	LOCALIZATION_ZORLEN["WingClip"] = "Wing Clip"
	LOCALIZATION_ZORLEN["FreezingTrap"] = "Freezing Trap"
	LOCALIZATION_ZORLEN["FrostTrap"] = "Frost Trap"
	LOCALIZATION_ZORLEN["ExplosiveTrap"] = "Explosive Trap"
	LOCALIZATION_ZORLEN["ImmolationTrap"] = "Immolation Trap"
	LOCALIZATION_ZORLEN["FeignDeath"] = "Feign Death"
	LOCALIZATION_ZORLEN["Counterattack"] = "Counterattack"
	LOCALIZATION_ZORLEN["TranquilizingShot"] = "Tranquilizing Shot"
	LOCALIZATION_ZORLEN["Disengage"] = "Disengage"
	LOCALIZATION_ZORLEN["EyesOfTheBeast"] = "Eyes of the Beast"
	LOCALIZATION_ZORLEN["BeastLore"] = "Beast Lore"
	LOCALIZATION_ZORLEN["TrackBeasts"] = "Track Beasts"
	LOCALIZATION_ZORLEN["TrackDemons"] = "Track Demons"
	LOCALIZATION_ZORLEN["TrackDragonkin"] = "Track Dragonkin"
	LOCALIZATION_ZORLEN["TrackElementals"] = "Track Elementals"
	LOCALIZATION_ZORLEN["TrackGiants"] = "Track Giants"
	LOCALIZATION_ZORLEN["TrackHumanoids"] = "Track Humanoids"
	LOCALIZATION_ZORLEN["TrackUndead"] = "Track Undead"
	LOCALIZATION_ZORLEN["TrackHidden"] = "Track Hidden"
	LOCALIZATION_ZORLEN["BestialWrath"] = "Bestial Wrath"
	LOCALIZATION_ZORLEN["TrueshotAura"] = "Trueshot Aura"
	LOCALIZATION_ZORLEN["ScatterShot"] = "Scatter Shot"
	LOCALIZATION_ZORLEN["WyvernSting"] = "Wyvern Sting"
	LOCALIZATION_ZORLEN["Deterrence"] = "Deterrence"
	LOCALIZATION_ZORLEN["EagleEye"] = "Eagle Eye"
	LOCALIZATION_ZORLEN["RapidFire"] = "Rapid Fire"
	LOCALIZATION_ZORLEN["MultiShot"] = "Multi-Shot"
	LOCALIZATION_ZORLEN["Flare"] = "Flare"
	LOCALIZATION_ZORLEN["ScareBeast"] = "Scare Beast"
	LOCALIZATION_ZORLEN["Volley"] = "Volley"
	LOCALIZATION_ZORLEN["Intimidation"] = "Intimidation"



-- Zorlen_Warlock.lua file Localization
	LOCALIZATION_ZORLEN["SoulSiphon"] = "Soul Siphon"
	LOCALIZATION_ZORLEN["SeedOfCorruption"] = "Seed of Corruption"
	LOCALIZATION_ZORLEN["FelArmor"] = "Fel Armor"
	LOCALIZATION_ZORLEN["RitualOfSouls"] = "Ritual of Souls"
	LOCALIZATION_ZORLEN["Soulshatter"] = "Soulshatter"
	LOCALIZATION_ZORLEN["Incinerate"] = "Incinerate"
	LOCALIZATION_ZORLEN["UnstableAffliction"] = "Unstable Affliction"
	LOCALIZATION_ZORLEN["DemonicAegis"] = "Demonic Aegis"
	LOCALIZATION_ZORLEN["SummonFelGuard"] = "Summon Fel Guard"
	LOCALIZATION_ZORLEN["Shadowfury"] = "Shadowfury"
	
	LOCALIZATION_ZORLEN["Bane"] = "Bane"
	LOCALIZATION_ZORLEN["AmplifyCurse"] = "Amplify Curse"
	LOCALIZATION_ZORLEN["CurseOfAgony"] = "Curse of Agony"
	LOCALIZATION_ZORLEN["CurseOfDoom"] = "Curse of Doom"
	LOCALIZATION_ZORLEN["CurseOfShadow"] = "Curse of Shadow"
	LOCALIZATION_ZORLEN["CurseOfTheElements"] = "Curse of the Elements"
	LOCALIZATION_ZORLEN["CurseOfWeakness"] = "Curse of Weakness"
	LOCALIZATION_ZORLEN["CurseOfExhaustion"] = "Curse of Exhaustion"
	LOCALIZATION_ZORLEN["CurseOfRecklessness"] = "Curse of Recklessness"
	LOCALIZATION_ZORLEN["CurseOfTongues"] = "Curse of Tongues"
	LOCALIZATION_ZORLEN["Corruption"] = "Corruption"
	LOCALIZATION_ZORLEN["ImprovedCorruption"] = "Improved Corruption"
	LOCALIZATION_ZORLEN["Immolate"] = "Immolate"
	LOCALIZATION_ZORLEN["SiphonLife"] = "Siphon Life"
	LOCALIZATION_ZORLEN["DrainLife"] = "Drain Life"
	LOCALIZATION_ZORLEN["DrainMana"] = "Drain Mana"
	LOCALIZATION_ZORLEN["Hellfire"] = "Hellfire"
	LOCALIZATION_ZORLEN["RainOfFire"] = "Rain of Fire"
	LOCALIZATION_ZORLEN["DrainSoul"] = "Drain Soul"
	LOCALIZATION_ZORLEN["LifeTap"] = "Life Tap"
	LOCALIZATION_ZORLEN["ImprovedLifeTap"] = "Improved Life Tap"
	LOCALIZATION_ZORLEN["DarkPact"] = "Dark Pact"
	LOCALIZATION_ZORLEN["Nightfall"] = "Nightfall"
	LOCALIZATION_ZORLEN["ShadowBolt"] = "Shadow Bolt"
	LOCALIZATION_ZORLEN["Banish"] = "Banish"
	LOCALIZATION_ZORLEN["Conflagrate"] = "Conflagrate"
	LOCALIZATION_ZORLEN["CreateFirestoneLesser"] = "Create Firestone (Lesser)"
	LOCALIZATION_ZORLEN["CreateFirestone"] = "Create Firestone"
	LOCALIZATION_ZORLEN["CreateFirestoneGreater"] = "Create Firestone (Greater)"
	LOCALIZATION_ZORLEN["CreateFirestoneMajor"] = "Create Firestone (Major)"
	LOCALIZATION_ZORLEN["CreateHealthstoneMinor"] = "Create Healthstone (Minor)"
	LOCALIZATION_ZORLEN["CreateHealthstoneLesser"] = "Create Healthstone (Lesser)"
	LOCALIZATION_ZORLEN["CreateHealthstone"] = "Create Healthstone"
	LOCALIZATION_ZORLEN["CreateHealthstoneGreater"] = "Create Healthstone (Greater)"
	LOCALIZATION_ZORLEN["CreateHealthstoneMajor"] = "Create Healthstone (Major)"
	LOCALIZATION_ZORLEN["CreateSoulstoneMinor"] = "Create Soulstone (Minor)"
	LOCALIZATION_ZORLEN["CreateSoulstoneLesser"] = "Create Soulstone (Lesser)"
	LOCALIZATION_ZORLEN["CreateSoulstone"] = "Create Soulstone"
	LOCALIZATION_ZORLEN["CreateSoulstoneGreater"] = "Create Soulstone (Greater)"
	LOCALIZATION_ZORLEN["CreateSoulstoneMajor"] = "Create Soulstone (Major)"
	LOCALIZATION_ZORLEN["CreateSpellstone"] = "Create Spellstone"
	LOCALIZATION_ZORLEN["CreateSpellstoneGreater"] = "Create Spellstone (Greater)"
	LOCALIZATION_ZORLEN["CreateSpellstoneMajor"] = "Create Spellstone (Major)"
	LOCALIZATION_ZORLEN["DeathCoil"] = "Death Coil"
	LOCALIZATION_ZORLEN["DemonArmor"] = "Demon Armor"
	LOCALIZATION_ZORLEN["DemonSkin"] = "Demon Skin"
	LOCALIZATION_ZORLEN["DemonicSacrifice"] = "Demonic Sacrifice"
	LOCALIZATION_ZORLEN["DetectLesserInvisibility"] = "Detect Lesser Invisibility"
	LOCALIZATION_ZORLEN["DetectInvisibility"] = "Detect Invisibility"
	LOCALIZATION_ZORLEN["DetectGreaterInvisibility"] = "Detect Greater Invisibility"
	LOCALIZATION_ZORLEN["EnslaveDemon"] = "Enslave Demon"
	LOCALIZATION_ZORLEN["EyeOfKilrogg"] = "Eye of Kilrogg"
	LOCALIZATION_ZORLEN["Fear"] = "Fear"
	LOCALIZATION_ZORLEN["FelDomination"] = "Fel Domination"
	LOCALIZATION_ZORLEN["HealthFunnel"] = "Health Funnel"
	LOCALIZATION_ZORLEN["HowlOfTerror"] = "Howl of Terror"
	LOCALIZATION_ZORLEN["Inferno"] = "Inferno"
	LOCALIZATION_ZORLEN["RitualOfDoom"] = "Ritual of Doom"
	LOCALIZATION_ZORLEN["RitualOfSummoning"] = "Ritual of Summoning"
	LOCALIZATION_ZORLEN["SearingPain"] = "Searing Pain"
	LOCALIZATION_ZORLEN["SenseDemons"] = "Sense Demons"
	LOCALIZATION_ZORLEN["ShadowWard"] = "Shadow Ward"
	LOCALIZATION_ZORLEN["Shadowburn"] = "Shadowburn"
	LOCALIZATION_ZORLEN["SoulFire"] = "Soul Fire"
	LOCALIZATION_ZORLEN["SoulLink"] = "Soul Link"
	LOCALIZATION_ZORLEN["SummonDreadsteed"] = "Summon Dreadsteed"
	LOCALIZATION_ZORLEN["SummonFelhunter"] = "Summon Felhunter"
	LOCALIZATION_ZORLEN["SummonFelsteed"] = "Summon Felsteed"
	LOCALIZATION_ZORLEN["SummonImp"] = "Summon Imp"
	LOCALIZATION_ZORLEN["SummonSuccubus"] = "Summon Succubus"
	LOCALIZATION_ZORLEN["SummonVoidwalker"] = "Summon Voidwalker"
	LOCALIZATION_ZORLEN["UnendingBreath"] = "Unending Breath"
	LOCALIZATION_ZORLEN["FelConcentration"] = "Fel Concentration"



-- Zorlen_Druid.lua file Localization
	LOCALIZATION_ZORLEN["TravelForm"] = "Travel Form"
	LOCALIZATION_ZORLEN["MoonkinForm"] = "Moonkin Form"
	LOCALIZATION_ZORLEN["BearForm"] = "Bear Form"
	LOCALIZATION_ZORLEN["DireBearForm"] = "Dire Bear Form"
	LOCALIZATION_ZORLEN["CatForm"] = "Cat Form"
	LOCALIZATION_ZORLEN["AquaticForm"] = "Aquatic Form"
	LOCALIZATION_ZORLEN["ChallengingRoar"] = "Challenging Roar"
	LOCALIZATION_ZORLEN["DemoralizingRoar"] = "Demoralizing Roar"
	LOCALIZATION_ZORLEN["AbolishPoison"] = "Abolish Poison"
	LOCALIZATION_ZORLEN["Barkskin"] = "Barkskin"
	LOCALIZATION_ZORLEN["Bash"] = "Bash"
	LOCALIZATION_ZORLEN["Claw"] = "Claw"
	LOCALIZATION_ZORLEN["Cower"] = "Cower"
	LOCALIZATION_ZORLEN["Dash"] = "Dash"
	LOCALIZATION_ZORLEN["Enrage"] = "Enrage"
	LOCALIZATION_ZORLEN["EntanglingRoots"] = "Entangling Roots"
	LOCALIZATION_ZORLEN["FaerieFire"] = "Faerie Fire"
	LOCALIZATION_ZORLEN["FaerieFireFeral"] = "Faerie Fire (Feral)"
	LOCALIZATION_ZORLEN["FeralCharge"] = "Feral Charge"
	LOCALIZATION_ZORLEN["FerociousBite"] = "Ferocious Bite"
	LOCALIZATION_ZORLEN["FrenziedRegeneration"] = "Frenzied Regeneration"
	LOCALIZATION_ZORLEN["GiftOfTheWild"] = "Gift of the Wild"
	LOCALIZATION_ZORLEN["HealingTouch"] = "Healing Touch"
	LOCALIZATION_ZORLEN["Hibernate"] = "Hibernate"
	LOCALIZATION_ZORLEN["Hurricane"] = "Hurricane"
	LOCALIZATION_ZORLEN["Innervate"] = "Innervate"
	LOCALIZATION_ZORLEN["InsectSwarm"] = "Insect Swarm"
	LOCALIZATION_ZORLEN["LeaderOfThePack"] = "Leader of the Pack"
	LOCALIZATION_ZORLEN["MarkOfTheWild"] = "Mark of the Wild"
	LOCALIZATION_ZORLEN["Maul"] = "Maul"
	LOCALIZATION_ZORLEN["Moonfire"] = "Moonfire"
	LOCALIZATION_ZORLEN["NaturesGrasp"] = "Nature's Grasp"
	LOCALIZATION_ZORLEN["NaturesSwiftness"] = "Nature's Swiftness"
	LOCALIZATION_ZORLEN["OmenOfClarity"] = "Omen of Clarity"
	LOCALIZATION_ZORLEN["Pounce"] = "Pounce"
	LOCALIZATION_ZORLEN["Prowl"] = "Prowl"
	LOCALIZATION_ZORLEN["Rake"] = "Rake"
	LOCALIZATION_ZORLEN["Ravage"] = "Ravage"
	LOCALIZATION_ZORLEN["Rebirth"] = "Rebirth"
	LOCALIZATION_ZORLEN["Regrowth"] = "Regrowth"
	LOCALIZATION_ZORLEN["Rejuvenation"] = "Rejuvenation"
	LOCALIZATION_ZORLEN["RemoveCurse"] = "Remove Curse"
	LOCALIZATION_ZORLEN["Rip"] = "Rip"
	LOCALIZATION_ZORLEN["Shred"] = "Shred"
	LOCALIZATION_ZORLEN["SootheAnimal"] = "Soothe Animal"
	LOCALIZATION_ZORLEN["Starfire"] = "Starfire"
	LOCALIZATION_ZORLEN["Swipe"] = "Swipe"
	LOCALIZATION_ZORLEN["Thorns"] = "Thorns"
	LOCALIZATION_ZORLEN["TigersFury"] = "Tiger's Fury"
	LOCALIZATION_ZORLEN["TrackHumanoids"] = "Track Humanoids"
	LOCALIZATION_ZORLEN["Tranquility"] = "Tranquility"
	LOCALIZATION_ZORLEN["Wrath"] = "Wrath"
	LOCALIZATION_ZORLEN["ImprovedWrath"] = "Improved Wrath"
	LOCALIZATION_ZORLEN["ImprovedNaturesGrasp"] = "Improved Nature's Grasp"
	LOCALIZATION_ZORLEN["ImprovedEntanglingRoots"] = "Improved Entangling Roots"
	LOCALIZATION_ZORLEN["ImprovedMoonfire"] = "Improved Moonfire"
	LOCALIZATION_ZORLEN["NaturalWeapons"] = "Natural Weapons"
	LOCALIZATION_ZORLEN["NaturalShapeshifter"] = "Natural Shapeshifter"
	LOCALIZATION_ZORLEN["ImprovedThorns"] = "Improved Thorns"
	LOCALIZATION_ZORLEN["NaturesReach"] = "Nature's Reach"
	LOCALIZATION_ZORLEN["Vengeance"] = "Vengeance"
	LOCALIZATION_ZORLEN["ImprovedStarfire"] = "Improved Starfire"
	LOCALIZATION_ZORLEN["NaturesGrace"] = "Nature's Grace"
	LOCALIZATION_ZORLEN["Moonglow"] = "Moonglow"
	LOCALIZATION_ZORLEN["Moonfury"] = "Moonfury"
	LOCALIZATION_ZORLEN["Ferocity"] = "Ferocity"
	LOCALIZATION_ZORLEN["FeralAggression"] = "Feral Aggression"
	LOCALIZATION_ZORLEN["FeralInstinct"] = "Feral Instinct"
	LOCALIZATION_ZORLEN["BrutalImpact"] = "Brutal Impact"
	LOCALIZATION_ZORLEN["ThickHide"] = "Thick Hide"
	LOCALIZATION_ZORLEN["FelineSwiftness"] = "Feline Swiftness"
	LOCALIZATION_ZORLEN["SharpenedClaws"] = "Sharpened Claws"
	LOCALIZATION_ZORLEN["ImprovedShred"] = "Improved Shred"
	LOCALIZATION_ZORLEN["PredatoryStrikes"] = "Predatory Strikes"
	LOCALIZATION_ZORLEN["BloodFrenzy"] = "Blood Frenzy"
	LOCALIZATION_ZORLEN["PrimalFury"] = "Primal Fury"
	LOCALIZATION_ZORLEN["SavageFury"] = "Savage Fury"
	LOCALIZATION_ZORLEN["HeartOfTheWild"] = "Heart of the Wild"
	LOCALIZATION_ZORLEN["ImprovedMarkOfTheWild"] = "Improved Mark of the Wild"
	LOCALIZATION_ZORLEN["Furor"] = "Furor"
	LOCALIZATION_ZORLEN["ImprovedHealingTouch"] = "Improved Healing Touch"
	LOCALIZATION_ZORLEN["NaturesFocus"] = "Nature's Focus"
	LOCALIZATION_ZORLEN["ImprovedEnrage"] = "Improved Enrage"
	LOCALIZATION_ZORLEN["Reflection"] = "Reflection"
	LOCALIZATION_ZORLEN["Subtlety"] = "Subtlety"
	LOCALIZATION_ZORLEN["TranquilSpirit"] = "Tranquil Spirit"
	LOCALIZATION_ZORLEN["ImprovedRejuvenation"] = "Improved Rejuvenation"
	LOCALIZATION_ZORLEN["GiftOfNature"] = "Gift of Nature"
	LOCALIZATION_ZORLEN["ImprovedTranquility"] = "Improved Tranquility"
	LOCALIZATION_ZORLEN["ImprovedRegrowth"] = "Improved Regrowth"
	LOCALIZATION_ZORLEN["Swiftmend"] = "Swiftmend"



-- Zorlen_Mage.lua file Localization
	LOCALIZATION_ZORLEN["ConjuredCinnamonRoll"] = "Conjured Cinnamon Roll"
	LOCALIZATION_ZORLEN["ConjuredSweetRoll"] = "Conjured Sweet Roll"
	LOCALIZATION_ZORLEN["ConjuredSourdough"] = "Conjured Sourdough"
	LOCALIZATION_ZORLEN["ConjuredPumpernickel"] = "Conjured Pumpernickel"
	LOCALIZATION_ZORLEN["ConjuredRye"] = "Conjured Rye"
	LOCALIZATION_ZORLEN["ConjuredBread"] = "Conjured Bread"
	LOCALIZATION_ZORLEN["ConjuredMuffin"] = "Conjured Muffin"
	LOCALIZATION_ZORLEN["ConjuredCrystalWater"] = "Conjured Crystal Water"
	LOCALIZATION_ZORLEN["ConjuredSparklingWater"] = "Conjured Sparkling Water"
	LOCALIZATION_ZORLEN["ConjuredMineralWater"] = "Conjured Mineral Water"
	LOCALIZATION_ZORLEN["ConjuredSpringWater"] = "Conjured Spring Water"
	LOCALIZATION_ZORLEN["ConjuredPurifiedWater"] = "Conjured Purified Water"
	LOCALIZATION_ZORLEN["ConjuredFreshWater"] = "Conjured Fresh Water"
	LOCALIZATION_ZORLEN["ConjuredWater"] = "Conjured Water"
	LOCALIZATION_ZORLEN["AmplifyMagic"] = "Amplify Magic"
	LOCALIZATION_ZORLEN["ArcaneBrilliance"] = "Arcane Brilliance"
	LOCALIZATION_ZORLEN["ArcaneExplosion"] = "Arcane Explosion"
	LOCALIZATION_ZORLEN["ArcaneIntellect"] = "Arcane Intellect"
	LOCALIZATION_ZORLEN["ArcaneMissiles"] = "Arcane Missiles"
	LOCALIZATION_ZORLEN["ArcanePower"] = "Arcane Power"
	LOCALIZATION_ZORLEN["BlastWave"] = "Blast Wave"
	LOCALIZATION_ZORLEN["Blink"] = "Blink"
	LOCALIZATION_ZORLEN["Blizzard"] = "Blizzard"
	LOCALIZATION_ZORLEN["ColdSnap"] = "Cold Snap"
	LOCALIZATION_ZORLEN["Combustion"] = "Combustion"
	LOCALIZATION_ZORLEN["ConeOfCold"] = "Cone of Cold"
	LOCALIZATION_ZORLEN["ConjureFood"] = "Conjure Food"
	LOCALIZATION_ZORLEN["ConjureManaAgate"] = "Conjure Mana Agate"
	LOCALIZATION_ZORLEN["ConjureManaJade"] = "Conjure Mana Jade"
	LOCALIZATION_ZORLEN["ConjureManaCitrine"] = "Conjure Mana Citrine"
	LOCALIZATION_ZORLEN["ConjureManaRuby"] = "Conjure Mana Ruby"
	LOCALIZATION_ZORLEN["ConjureWater"] = "Conjure Water"
	LOCALIZATION_ZORLEN["Counterspell"] = "Counterspell"
	LOCALIZATION_ZORLEN["DampenMagic"] = "Dampen Magic"
	LOCALIZATION_ZORLEN["DetectMagic"] = "Detect Magic"
	LOCALIZATION_ZORLEN["Evocation"] = "Evocation"
	LOCALIZATION_ZORLEN["FireBlast"] = "Fire Blast"
	LOCALIZATION_ZORLEN["FireWard"] = "Fire Ward"
	LOCALIZATION_ZORLEN["Fireball"] = "Fireball"
	LOCALIZATION_ZORLEN["Flamestrike"] = "Flamestrike"
	LOCALIZATION_ZORLEN["FrostArmor"] = "Frost Armor"
	LOCALIZATION_ZORLEN["FrostNova"] = "Frost Nova"
	LOCALIZATION_ZORLEN["FrostWard"] = "Frost Ward"
	LOCALIZATION_ZORLEN["Frostbolt"] = "Frostbolt"
	LOCALIZATION_ZORLEN["IceArmor"] = "Ice Armor"
	LOCALIZATION_ZORLEN["IceBarrier"] = "Ice Barrier"
	LOCALIZATION_ZORLEN["IceBlock"] = "Ice Block"
	LOCALIZATION_ZORLEN["MageArmor"] = "Mage Armor"
	LOCALIZATION_ZORLEN["ManaShield"] = "Mana Shield"
	LOCALIZATION_ZORLEN["Polymorph"] = "Polymorph"
	LOCALIZATION_ZORLEN["PortalDarnassus"] = "Portal: Darnassus"
	LOCALIZATION_ZORLEN["PortalIronforge"] = "Portal: Ironforge"
	LOCALIZATION_ZORLEN["PortalOrgrimmar"] = "Portal: Orgrimmar"
	LOCALIZATION_ZORLEN["PortalStormwind"] = "Portal: Stormwind"
	LOCALIZATION_ZORLEN["PortalThunderBluff"] = "Portal: Thunder Bluff"
	LOCALIZATION_ZORLEN["PortalUndercity"] = "Portal: Undercity"
	LOCALIZATION_ZORLEN["TeleportDarnassus"] = "Teleport: Darnassus"
	LOCALIZATION_ZORLEN["TeleportIronforge"] = "Teleport: Ironforge"
	LOCALIZATION_ZORLEN["TeleportOrgrimmar"] = "Teleport: Orgrimmar"
	LOCALIZATION_ZORLEN["TeleportStormwind"] = "Teleport: Stormwind"
	LOCALIZATION_ZORLEN["TeleportThunderBluff"] = "Teleport: Thunder Bluff"
	LOCALIZATION_ZORLEN["TeleportUndercity"] = "Teleport: Undercity"
	LOCALIZATION_ZORLEN["PresenceOfMind"] = "Presence of Mind"
	LOCALIZATION_ZORLEN["Pyroblast"] = "Pyroblast"
	LOCALIZATION_ZORLEN["RemoveLesserCurse"] = "Remove Lesser Curse"
	LOCALIZATION_ZORLEN["Scorch"] = "Scorch"
	LOCALIZATION_ZORLEN["SlowFall"] = "Slow Fall"



-- Zorlen_Paladin.lua file Localization
	LOCALIZATION_ZORLEN["BlessingOfFreedom"] = "Blessing of Freedom"
	LOCALIZATION_ZORLEN["BlessingOfKings"] = "Blessing of Kings"
	LOCALIZATION_ZORLEN["BlessingOfLight"] = "Blessing of Light"
	LOCALIZATION_ZORLEN["BlessingOfMight"] = "Blessing of Might"
	LOCALIZATION_ZORLEN["BlessingOfProtection"] = "Blessing of Protection"
	LOCALIZATION_ZORLEN["BlessingOfSacrifice"] = "Blessing of Sacrifice"
	LOCALIZATION_ZORLEN["BlessingOfSalvation"] = "Blessing of Salvation"
	LOCALIZATION_ZORLEN["BlessingOfSanctuary"] = "Blessing of Sanctuary"
	LOCALIZATION_ZORLEN["BlessingOfWisdom"] = "Blessing of Wisdom"
	LOCALIZATION_ZORLEN["Cleanse"] = "Cleanse"
	LOCALIZATION_ZORLEN["ConcentrationAura"] = "Concentration Aura"
	LOCALIZATION_ZORLEN["Consecration"] = "Consecration"
	LOCALIZATION_ZORLEN["DevotionAura"] = "Devotion Aura"
	LOCALIZATION_ZORLEN["DivineFavor"] = "Divine Favor"
	LOCALIZATION_ZORLEN["DivineIntervention"] = "Divine Intervention"
	LOCALIZATION_ZORLEN["DivineProtection"] = "Divine Protection"
	LOCALIZATION_ZORLEN["DivineShield"] = "Divine Shield"
	LOCALIZATION_ZORLEN["Exorcism"] = "Exorcism"
	LOCALIZATION_ZORLEN["FireResistanceAura"] = "Fire Resistance Aura"
	LOCALIZATION_ZORLEN["FlashOfLight"] = "Flash of Light"
	LOCALIZATION_ZORLEN["FrostResistanceAura"] = "Frost Resistance Aura"
	LOCALIZATION_ZORLEN["GreaterBlessingOfKings"] = "Greater Blessing of Kings"
	LOCALIZATION_ZORLEN["GreaterBlessingOfLight"] = "Greater Blessing of Light"
	LOCALIZATION_ZORLEN["GreaterBlessingOfMight"] = "Greater Blessing of Might"
	LOCALIZATION_ZORLEN["GreaterBlessingOfSalvation"] = "Greater Blessing of Salvation"
	LOCALIZATION_ZORLEN["GreaterBlessingOfSanctuary"] = "Greater Blessing of Sanctuary"
	LOCALIZATION_ZORLEN["GreaterBlessingOfWisdom"] = "Greater Blessing of Wisdom"
	LOCALIZATION_ZORLEN["HammerOfJustice"] = "Hammer of Justice"
	LOCALIZATION_ZORLEN["HammerOfWrath"] = "Hammer of Wrath"
	LOCALIZATION_ZORLEN["HolyLight"] = "Holy Light"
	LOCALIZATION_ZORLEN["HolyShield"] = "Holy Shield"
	LOCALIZATION_ZORLEN["HolyShock"] = "Holy Shock"
	LOCALIZATION_ZORLEN["HolyWrath"] = "Holy Wrath"
	LOCALIZATION_ZORLEN["Judgement"] = "Judgement"
	LOCALIZATION_ZORLEN["LayOnHands"] = "Lay on Hands"
	LOCALIZATION_ZORLEN["Purify"] = "Purify"
	LOCALIZATION_ZORLEN["Redemption"] = "Redemption"
	LOCALIZATION_ZORLEN["Repentance"] = "Repentance"
	LOCALIZATION_ZORLEN["RetributionAura"] = "Retribution Aura"
	LOCALIZATION_ZORLEN["RighteousFury"] = "Righteous Fury"
	LOCALIZATION_ZORLEN["SanctityAura"] = "Sanctity Aura"
	LOCALIZATION_ZORLEN["SealOfCommand"] = "Seal of Command"
	LOCALIZATION_ZORLEN["SealOfJustice"] = "Seal of Justice"
	LOCALIZATION_ZORLEN["SealOfLight"] = "Seal of Light"
	LOCALIZATION_ZORLEN["SealOfRighteousness"] = "Seal of Righteousness"
	LOCALIZATION_ZORLEN["SealOfWisdom"] = "Seal of Wisdom"
	LOCALIZATION_ZORLEN["SealOfTheCrusader"] = "Seal of the Crusader"
	LOCALIZATION_ZORLEN["SenseUndead"] = "Sense Undead"
	LOCALIZATION_ZORLEN["ShadowResistanceAura"] = "Shadow Resistance Aura"
	LOCALIZATION_ZORLEN["SummonCharger"] = "Summon Charger"
	LOCALIZATION_ZORLEN["SummonWarhorse"] = "Summon Warhorse"
	LOCALIZATION_ZORLEN["TurnUndead"] = "Turn Undead"



-- Zorlen_Priest.lua file Localization
	LOCALIZATION_ZORLEN["PowerInfusion"] = "Power Infusion"
	LOCALIZATION_ZORLEN["Lightwell"] = "Lightwell"
	LOCALIZATION_ZORLEN["AbolishDisease"] = "Abolish Disease"
	LOCALIZATION_ZORLEN["CureDisease"] = "Cure Disease"
	LOCALIZATION_ZORLEN["DesperatePrayer"] = "Desperate Prayer"
	LOCALIZATION_ZORLEN["DevouringPlague"] = "Devouring Plague"
	LOCALIZATION_ZORLEN["DispelMagic"] = "Dispel Magic"
	LOCALIZATION_ZORLEN["DivineSpirit"] = "Divine Spirit"
	LOCALIZATION_ZORLEN["ElunesGrace"] = "Elune's Grace"
	LOCALIZATION_ZORLEN["Fade"] = "Fade"
	LOCALIZATION_ZORLEN["FearWard"] = "Fear Ward"
	LOCALIZATION_ZORLEN["Feedback"] = "Feedback"
	LOCALIZATION_ZORLEN["FlashHeal"] = "Flash Heal"
	LOCALIZATION_ZORLEN["FocusedCasting"] = "Focused Casting"
	LOCALIZATION_ZORLEN["LesserHeal"] = "Lesser Heal"
	LOCALIZATION_ZORLEN["Heal"] = "Heal"
	LOCALIZATION_ZORLEN["GreaterHeal"] = "Greater Heal"
	LOCALIZATION_ZORLEN["HexOfWeakness"] = "Hex of Weakness"
	LOCALIZATION_ZORLEN["HolyFire"] = "Holy Fire"
	LOCALIZATION_ZORLEN["HolyNova"] = "Holy Nova"
	LOCALIZATION_ZORLEN["InnerFire"] = "Inner Fire"
	LOCALIZATION_ZORLEN["InnerFocus"] = "Inner Focus"
	LOCALIZATION_ZORLEN["Levitate"] = "Levitate"
	LOCALIZATION_ZORLEN["ManaBurn"] = "Mana Burn"
	LOCALIZATION_ZORLEN["MindBlast"] = "Mind Blast"
	LOCALIZATION_ZORLEN["MindControl"] = "Mind Control"
	LOCALIZATION_ZORLEN["MindFlay"] = "Mind Flay"
	LOCALIZATION_ZORLEN["MindSoothe"] = "Mind Soothe"
	LOCALIZATION_ZORLEN["MindVision"] = "Mind Vision"
	LOCALIZATION_ZORLEN["PowerWordFortitude"] = "Power Word: Fortitude"
	LOCALIZATION_ZORLEN["PowerWordShield"] = "Power Word: Shield"
	LOCALIZATION_ZORLEN["PrayerOfFortitude"] = "Prayer of Fortitude"
	LOCALIZATION_ZORLEN["PrayerOfHealing"] = "Prayer of Healing"
	LOCALIZATION_ZORLEN["PsychicScream"] = "Psychic Scream"
	LOCALIZATION_ZORLEN["Renew"] = "Renew"
	LOCALIZATION_ZORLEN["Resurrection"] = "Resurrection"
	LOCALIZATION_ZORLEN["ShackleUndead"] = "Shackle Undead"
	LOCALIZATION_ZORLEN["ShadowProtection"] = "Shadow Protection"
	LOCALIZATION_ZORLEN["ShadowWordPain"] = "Shadow Word: Pain"
	LOCALIZATION_ZORLEN["Shadowform"] = "Shadowform"
	LOCALIZATION_ZORLEN["Shadowguard"] = "Shadowguard"
	LOCALIZATION_ZORLEN["Silence"] = "Silence"
	LOCALIZATION_ZORLEN["Smite"] = "Smite"
	LOCALIZATION_ZORLEN["SpiritOfRedemption"] = "Spirit of Redemption"
	LOCALIZATION_ZORLEN["Starshards"] = "Starshards"
	LOCALIZATION_ZORLEN["TouchOfWeakness"] = "Touch of Weakness"
	LOCALIZATION_ZORLEN["VampiricEmbrace"] = "Vampiric Embrace"



-- Zorlen_Rogue.lua file Localization
	LOCALIZATION_ZORLEN["DirtyDeeds"] = "Dirty Deeds"
	LOCALIZATION_ZORLEN["ImprovedSinisterStrike"] = "Improved Sinister Strike"
	LOCALIZATION_ZORLEN["CripplingPoison"] = "Crippling Poison"
	LOCALIZATION_ZORLEN["CripplingPoisonII"] = "Crippling Poison II"
	LOCALIZATION_ZORLEN["DeadlyPoison"] = "Deadly Poison"
	LOCALIZATION_ZORLEN["DeadlyPoisonII"] = "Deadly Poison II"
	LOCALIZATION_ZORLEN["DeadlyPoisonIII"] = "Deadly Poison III"
	LOCALIZATION_ZORLEN["DeadlyPoisonIV"] = "Deadly Poison IV"
	LOCALIZATION_ZORLEN["DeadlyPoisonV"] = "Deadly Poison V"
	LOCALIZATION_ZORLEN["InstantPoison"] = "Instant Poison"
	LOCALIZATION_ZORLEN["InstantPoisonII"] = "Instant Poison II"
	LOCALIZATION_ZORLEN["InstantPoisonIII"] = "Instant Poison III"
	LOCALIZATION_ZORLEN["InstantPoisonIV"] = "Instant Poison IV"
	LOCALIZATION_ZORLEN["InstantPoisonV"] = "Instant Poison V"
	LOCALIZATION_ZORLEN["InstantPoisonVI"] = "Instant Poison VI"
	LOCALIZATION_ZORLEN["MindnumbingPoison"] = "Mind-numbing Poison"
	LOCALIZATION_ZORLEN["MindnumbingPoisonII"] = "Mind-numbing Poison II"
	LOCALIZATION_ZORLEN["MindnumbingPoisonIII"] = "Mind-numbing Poison III"
	LOCALIZATION_ZORLEN["WoundPoison"] = "Wound Poison"
	LOCALIZATION_ZORLEN["WoundPoisonII"] = "Wound Poison II"
	LOCALIZATION_ZORLEN["WoundPoisonIII"] = "Wound Poison III"
	LOCALIZATION_ZORLEN["WoundPoisonIV"] = "Wound Poison IV"
	LOCALIZATION_ZORLEN["AdrenalineRush"] = "Adrenaline Rush"
	LOCALIZATION_ZORLEN["Ambush"] = "Ambush"
	LOCALIZATION_ZORLEN["Backstab"] = "Backstab"
	LOCALIZATION_ZORLEN["BladeFlurry"] = "Blade Flurry"
	LOCALIZATION_ZORLEN["Blind"] = "Blind"
	LOCALIZATION_ZORLEN["BlindingPowder"] = "Blinding Powder"
	LOCALIZATION_ZORLEN["CheapShot"] = "Cheap Shot"
	LOCALIZATION_ZORLEN["ColdBlood"] = "Cold Blood"
	LOCALIZATION_ZORLEN["DetectTraps"] = "Detect Traps"
	LOCALIZATION_ZORLEN["DisarmTrap"] = "Disarm Trap"
	LOCALIZATION_ZORLEN["Distract"] = "Distract"
	LOCALIZATION_ZORLEN["Evasion"] = "Evasion"
	LOCALIZATION_ZORLEN["Eviscerate"] = "Eviscerate"
	LOCALIZATION_ZORLEN["ExposeArmor"] = "Expose Armor"
	LOCALIZATION_ZORLEN["Feint"] = "Feint"
	LOCALIZATION_ZORLEN["Garrote"] = "Garrote"
	LOCALIZATION_ZORLEN["GhostlyStrike"] = "Ghostly Strike"
	LOCALIZATION_ZORLEN["Gouge"] = "Gouge"
	LOCALIZATION_ZORLEN["Hemorrhage"] = "Hemorrhage"
	LOCALIZATION_ZORLEN["Kick"] = "Kick"
	LOCALIZATION_ZORLEN["KidneyShot"] = "Kidney Shot"
	LOCALIZATION_ZORLEN["PickLock"] = "Pick Lock"
	LOCALIZATION_ZORLEN["PickPocket"] = "Pick Pocket"
	LOCALIZATION_ZORLEN["Premeditation"] = "Premeditation"
	LOCALIZATION_ZORLEN["Preparation"] = "Preparation"
	LOCALIZATION_ZORLEN["RelentlessStrikes"] = "Relentless Strikes"
	LOCALIZATION_ZORLEN["Riposte"] = "Riposte"
	LOCALIZATION_ZORLEN["Rupture"] = "Rupture"
	LOCALIZATION_ZORLEN["Sap"] = "Sap"
	LOCALIZATION_ZORLEN["SinisterStrike"] = "Sinister Strike"
	LOCALIZATION_ZORLEN["SliceAndDice"] = "Slice and Dice"
	LOCALIZATION_ZORLEN["Sprint"] = "Sprint"
	LOCALIZATION_ZORLEN["Stealth"] = "Stealth"
	LOCALIZATION_ZORLEN["Vanish"] = "Vanish"



-- Zorlen_Shaman.lua file Localization
	LOCALIZATION_ZORLEN["DiseaseCleansingTotem"] = "Disease Cleansing Totem"
	LOCALIZATION_ZORLEN["EarthbindTotem"] = "Earthbind Totem"
	LOCALIZATION_ZORLEN["FireNovaTotem"] = "Fire Nova Totem"
	LOCALIZATION_ZORLEN["FireResistanceTotem"] = "Fire Resistance Totem"
	LOCALIZATION_ZORLEN["FlametongueTotem"] = "Flametongue Totem"
	LOCALIZATION_ZORLEN["FrostResistanceTotem"] = "Frost Resistance Totem"
	LOCALIZATION_ZORLEN["GraceOfAirTotem"] = "Grace of Air Totem"
	LOCALIZATION_ZORLEN["GroundingTotem"] = "Grounding Totem"
	LOCALIZATION_ZORLEN["HealingStreamTotem"] = "Healing Stream Totem"
	LOCALIZATION_ZORLEN["MagmaTotem"] = "Magma Totem"
	LOCALIZATION_ZORLEN["ManaSpringTotem"] = "Mana Spring Totem"
	LOCALIZATION_ZORLEN["ManaTideTotem"] = "Mana Tide Totem"
	LOCALIZATION_ZORLEN["NatureResistanceTotem"] = "Nature Resistance Totem"
	LOCALIZATION_ZORLEN["PoisonCleansingTotem"] = "Poison Cleansing Totem"
	LOCALIZATION_ZORLEN["SearingTotem"] = "Searing Totem"
	LOCALIZATION_ZORLEN["SentryTotem"] = "Sentry Totem"
	LOCALIZATION_ZORLEN["StoneclawTotem"] = "Stoneclaw Totem"
	LOCALIZATION_ZORLEN["StoneskinTotem"] = "Stoneskin Totem"
	LOCALIZATION_ZORLEN["StrengthOfEarthTotem"] = "Strength of Earth Totem"
	LOCALIZATION_ZORLEN["TremorTotem"] = "Tremor Totem"
	LOCALIZATION_ZORLEN["WindfuryTotem"] = "Windfury Totem"
	LOCALIZATION_ZORLEN["WindwallTotem"] = "Windwall Totem"
	LOCALIZATION_ZORLEN["EarthShock"] = "Earth Shock"
	LOCALIZATION_ZORLEN["FlameShock"] = "Flame Shock"
	LOCALIZATION_ZORLEN["FrostShock"] = "Frost Shock"
	LOCALIZATION_ZORLEN["FlametongueWeapon"] = "Flametongue Weapon"
	LOCALIZATION_ZORLEN["FrostbrandWeapon"] = "Frostbrand Weapon"
	LOCALIZATION_ZORLEN["RockbiterWeapon"] = "Rockbiter Weapon"
	LOCALIZATION_ZORLEN["WindfuryWeapon"] = "Windfury Weapon"
	LOCALIZATION_ZORLEN["AncestralSpirit"] = "Ancestral Spirit"
	LOCALIZATION_ZORLEN["AstralRecall"] = "Astral Recall"
	LOCALIZATION_ZORLEN["ChainHeal"] = "Chain Heal"
	LOCALIZATION_ZORLEN["ChainLightning"] = "Chain Lightning"
	LOCALIZATION_ZORLEN["CureDisease"] = "Cure Disease"
	LOCALIZATION_ZORLEN["CurePoison"] = "Cure Poison"
	LOCALIZATION_ZORLEN["ElementalFocus"] = "Elemental Focus"
	LOCALIZATION_ZORLEN["ElementalMastery"] = "Elemental Mastery"
	LOCALIZATION_ZORLEN["FarSight"] = "Far Sight"
	LOCALIZATION_ZORLEN["GhostWolf"] = "Ghost Wolf"
	LOCALIZATION_ZORLEN["LesserHealingWave"] = "Lesser Healing Wave"
	LOCALIZATION_ZORLEN["HealingWave"] = "Healing Wave"
	LOCALIZATION_ZORLEN["LightningBolt"] = "Lightning Bolt"
	LOCALIZATION_ZORLEN["LightningShield"] = "Lightning Shield"
	LOCALIZATION_ZORLEN["NaturesSwiftness"] = "Nature's Swiftness"
	LOCALIZATION_ZORLEN["Purge"] = "Purge"
	LOCALIZATION_ZORLEN["Reincarnation"] = "Reincarnation"
	LOCALIZATION_ZORLEN["Stormstrike"] = "Stormstrike"
	LOCALIZATION_ZORLEN["WaterBreathing"] = "Water Breathing"
	LOCALIZATION_ZORLEN["WaterWalking"] = "Water Walking"



-- Zorlen_Warrior.lua file Localization
	LOCALIZATION_ZORLEN["Devastate"] = "Devastate"
	LOCALIZATION_ZORLEN["ImprovedWhirlwind"] = "Improved Whirlwind"
	LOCALIZATION_ZORLEN["FocusedRage"] = "Focused Rage"
	LOCALIZATION_ZORLEN["CommandingShout"] = "Commanding Shout"
	LOCALIZATION_ZORLEN["SpellReflection"] = "Spell Reflection"
	LOCALIZATION_ZORLEN["Intervene"] = "Intervene"
	LOCALIZATION_ZORLEN["VictoryRush"] = "Victory Rush"
	LOCALIZATION_ZORLEN["EndlessRage"] = "Endless Rage"
	LOCALIZATION_ZORLEN["Rampage"] = "Rampage"
	
	LOCALIZATION_ZORLEN["ImprovedBloodrage"] = "Improved Bloodrage"
	LOCALIZATION_ZORLEN["ImprovedOverpower"] = "Improved Overpower"
	LOCALIZATION_ZORLEN["ImprovedBerserkerRage"] = "Improved Berserker Rage"
	LOCALIZATION_ZORLEN["ImprovedExecute"] = "Improved Execute"
	LOCALIZATION_ZORLEN["Execute"] = "Execute"
	LOCALIZATION_ZORLEN["ImprovedHeroicStrike"] = "Improved Heroic Strike"
	LOCALIZATION_ZORLEN["HeroicStrike"] = "Heroic Strike"
	LOCALIZATION_ZORLEN["ImprovedSunderArmor"] = "Improved Sunder Armor"
	LOCALIZATION_ZORLEN["SunderArmor"] = "Sunder Armor"
	LOCALIZATION_ZORLEN["ImprovedThunderClap"] = "Improved Thunder Clap"
	LOCALIZATION_ZORLEN["ThunderClap"] = "Thunder Clap"
	LOCALIZATION_ZORLEN["MortalStrike"] = "Mortal Strike"
	LOCALIZATION_ZORLEN["Bloodthirst"] = "Bloodthirst"
	LOCALIZATION_ZORLEN["ShieldSlam"] = "Shield Slam"
	LOCALIZATION_ZORLEN["Charge"] = "Charge"
	LOCALIZATION_ZORLEN["Taunt"] = "Taunt"
	LOCALIZATION_ZORLEN["Intercept"] = "Intercept"
	LOCALIZATION_ZORLEN["Overpower"] = "Overpower"
	LOCALIZATION_ZORLEN["Revenge"] = "Revenge"
	LOCALIZATION_ZORLEN["Rend"] = "Rend"
	LOCALIZATION_ZORLEN["Hamstring"] = "Hamstring"
	LOCALIZATION_ZORLEN["ShieldBash"] = "Shield Bash"
	LOCALIZATION_ZORLEN["Pummel"] = "Pummel"
	LOCALIZATION_ZORLEN["ShieldBlock"] = "Shield Block"
	LOCALIZATION_ZORLEN["DemoralizingShout"] = "Demoralizing Shout"
	LOCALIZATION_ZORLEN["BattleShout"] = "Battle Shout"
	LOCALIZATION_ZORLEN["BerserkerRage"] = "Berserker Rage"
	LOCALIZATION_ZORLEN["Enrage"] = "Enrage"
	LOCALIZATION_ZORLEN["DefensiveStance"] = "Defensive Stance"
	LOCALIZATION_ZORLEN["BattleStance"] = "Battle Stance"
	LOCALIZATION_ZORLEN["BerserkerStance"] = "Berserker Stance"
	LOCALIZATION_ZORLEN["AngerManagement"] = "Anger Management"
	LOCALIZATION_ZORLEN["Bloodrage"] = "Bloodrage"
	LOCALIZATION_ZORLEN["ChallengingShout"] = "Challenging Shout"
	LOCALIZATION_ZORLEN["Cleave"] = "Cleave"
	LOCALIZATION_ZORLEN["ConcussionBlow"] = "Concussion Blow"
	LOCALIZATION_ZORLEN["DeathWish"] = "Death Wish"
	LOCALIZATION_ZORLEN["Disarm"] = "Disarm"
	LOCALIZATION_ZORLEN["IntimidatingShout"] = "Intimidating Shout"
	LOCALIZATION_ZORLEN["LastStand"] = "Last Stand"
	LOCALIZATION_ZORLEN["MockingBlow"] = "Mocking Blow"
	LOCALIZATION_ZORLEN["PiercingHowl"] = "Piercing Howl"
	LOCALIZATION_ZORLEN["Recklessness"] = "Recklessness"
	LOCALIZATION_ZORLEN["Retaliation"] = "Retaliation"
	LOCALIZATION_ZORLEN["ShieldWall"] = "Shield Wall"
	LOCALIZATION_ZORLEN["Slam"] = "Slam"
	LOCALIZATION_ZORLEN["SweepingStrikes"] = "Sweeping Strikes"
	LOCALIZATION_ZORLEN["Whirlwind"] = "Whirlwind"
	LOCALIZATION_ZORLEN["TacticalMastery"] = "Tactical Mastery"



-- Fire Immune MOB's
 -- Molten Core
	LOCALIZATION_ZORLEN["Firelord"] = "Firelord"
	LOCALIZATION_ZORLEN["Firewalker"] = "Firewalker"
	LOCALIZATION_ZORLEN["Flameguard"] = "Flameguard"
	LOCALIZATION_ZORLEN["LavaSpawn"] = "Lava Spawn"
	LOCALIZATION_ZORLEN["BaronGeddon"] = "Baron Geddon"
	LOCALIZATION_ZORLEN["Ragnaros"] = "Ragnaros"
 -- Upper Blackrock Spire
	LOCALIZATION_ZORLEN["PyroguardEmberseer"] = "Pyroguard Emberseer"
 -- Blackrock Depths
	LOCALIZATION_ZORLEN["Fireguard"] = "Fireguard"
	LOCALIZATION_ZORLEN["FireguardDestroyer"] = "Fireguard Destroyer"
	LOCALIZATION_ZORLEN["BlazingFireguard"] = "Blazing Fireguard"
	LOCALIZATION_ZORLEN["AmbassadorFlamelash"] = "Ambassador Flamelash"
	LOCALIZATION_ZORLEN["LordIncendius"] = "Lord Incendius"
 --Searing Gorge
	LOCALIZATION_ZORLEN["BlazingElemental"] = "Blazing Elemental"
	LOCALIZATION_ZORLEN["InfernoElemental"] = "Inferno Elemental"
 --Un'Goro Crater
	LOCALIZATION_ZORLEN["ScorchingElemental"] = "Scorching Elemental"
	LOCALIZATION_ZORLEN["LivingBlaze"] = "Living Blaze"
	LOCALIZATION_ZORLEN["Blazerunner"] = "Blazerunner"

-- Drain Life Immune MOB's
 -- Blackrock Depths
	LOCALIZATION_ZORLEN["MoltenWarGolem"] = "Molten War Golem"
	LOCALIZATION_ZORLEN["PanzorTheInvincible"] = "Panzor the Invincible"
 --Searing Gorge
	LOCALIZATION_ZORLEN["HeavyWarGolem"] = "Heavy War Golem"
	LOCALIZATION_ZORLEN["FaultyWarGolem"] = "Faulty War Golem"
	LOCALIZATION_ZORLEN["TemperedWarGolem"] = "Tempered War Golem"
	LOCALIZATION_ZORLEN["RagereaverGolem"] = "Ragereaver Golem"
