local L = AceLibrary("AceLocale-2.0"):new("PerfectRaid")

L:RegisterTranslations("zhCN", function()
	return {	
		-- main status
		["Dead"] = "死亡",
		["Ghost"] = "灵魂",
		["Offline"] = "离线",
		["ImpDying"] = "天使",
		["Feign"] = "假死",

		["STATTEXT_Curse"] 		= "诅",
		["STATTEXT_Magic"] 		= "魔",
		["STATTEXT_Poison"] 		= "毒",
		["STATTEXT_Disease"] 		= "病",
		["STATTEXT_LowMana"] 		= "低魔",
		["STATTEXT_FeignDeath"]		= "假死",
		["STATTEXT_Soulstone"]		= "灵魂",
		["STATTEXT_Innervate"]		= "激活",
		["STATTEXT_PowerInfusion"]	= "能量",
		["STATTEXT_Fortitude"]		= "韧",
		["STATTEXT_ShadowProtection"]	= "暗抗",
		["STATTEXT_Spirit"]		= "精",
		["STATTEXT_Shield"]		= "盾",
		["STATTEXT_WeakenedSoul"]	= "盾",
		["STATTEXT_MarkOfWild"]		= "爪",
		["STATTEXT_Intellect"] 		= "智",

		["STATTEXT_Renew"]		= "恢",
		["STATTEXT_Regrowth"]		= "愈",
		["STATTEXT_Rejuvenation"]	= "春",

		["STATTEXT_BoMight"] 		= "力量",
		["STATTEXT_BoWisdom"] 		= "智慧",
		["STATTEXT_BoSalvation"] 	= "拯救",
		["STATTEXT_BoLight"] 		= "光明",
		["STATTEXT_BoSanctuary"]	= "庇护",
		["STATTEXT_BoKings"] 		= "王者",

		["Show Group Numbers"] = "显示团员所在小组",
        
	        ["Low Mana Threshold"] = "低魔法阀值%",
		["Sets the level which we show Low Mana"] = "低魔法阀值%",
        
	        ["Config Options"] = "设置选项",
		["Open Configuration UI"] = "打开设置界面",
        
	        ["Filter Debuffs"] = "debuff滤器",
		["Only show debuffs that you can cure"] = "只显示你可以解除的debuff",
        
	        ["Show tooltips"] = "显示提示",
		["Show/Hide mouseover tooltips"] = "显示/不显示鼠标提示",

		-- Buffs
		["Renew"] = "恢复",
		["Show units who have Renew"] = "显示有恢复的单位",
		["Rejuvenation"] = "回春术",
		["Show units who have Rejuvenation"] = "显示有回春术的单位",
		["Regrowth"] = "愈合",
		["Show units who have Regrowth"] = "显示有愈合的单位",
		
		["Columns"] = "排数",
		["Set number of columns"] = "设定排列为几排",
		["Horizontal Frame Alignment"] = "排间间距",
		["Change the horizontal offset between the columns"] = "设定排与排之间的间距",
		["Shift Players"] = "移动玩家",
		["Shift players between columns"] = "在排之间移动玩家",
		["Buff"] = "Buff选项",
		["Show/Hide some buffs"] = "显示/隐藏一些buff",
		["Fortitude"] = "真言术：韧",
		["Show units who need Power Word:Fortitude"] = "显示需要真言术：韧的单位",
		["ShadowProtection"] = "防护暗影",
		["Show units who need Shadow Protection"] = "显示需要防护暗影的单位",
		["Spirit"] = "神圣之灵",
		["Show units who need Divine Spirit"] = "显示需要神圣之灵的单位",
		["Intellect"] = "奥术智慧",
		["Show units who need Arcane Intellect"] = "显示需要奥术智慧的单位",
		["Mark of the Wild"] = "野性印记",
		["Show units who need Mark of the Wild"] = "显示需要野性印记的单位",
		["Blessing of Might"] = "力量祝福",
		["Show units who need Blessing of Might"] = "显示需要力量祝福的单位",
		["Blessing of Wisdom"] = "智慧祝福",
		["Show units who need Blessing of Wisdom"] = "显示需要智慧祝福的单位",
		["Blessing of Salvation"] = "拯救祝福",
		["Show units who need Blessing of Salvation"] = "显示需要拯救祝福的单位",
		["Blessing of Light"] = "光明祝福",
		["Show units who need Blessing of Light"] = "显示需要光明祝福的单位",
		["Blessing of Sanctuary"] = "庇护祝福",
		["Show units who need Blessing of Sanctuary"] = "显示需要庇护祝福的单位",
		["Blessing of Kings"] = "王者祝福",
		["Show units who need Blessing of Kings"] = "显示需要王者祝福的单位",
		["Debuff Indicator"] = "Debuff 指示器",
		["Show/Hide the debuff texture"] = "显示/隐藏debuff指示器",
        
		["Raid Simulation"] = "团队预测",
		["Frame Alignment"] = "框体水平顺序",
		["Horizontal aligmment of frames"] = "框体水平顺序",
		["Vertical Alignment"] = "框体竖直顺序",
		["Vertical Alignment of frames"] = "框体竖直顺序",
		["Mouseover Highlighting"] = "高亮点选目标",
		["Show/Hide the mouseover texture"] = "高亮点选目标",
		["Proximity detection"] = "暗淡超出距离范围的目标",
		["Dim frames that are out of your range"] = "暗淡超出距离范围的目标",
		["Name Truncation"] = "截短玩家姓名",
		["Truncate player names"] = "截短玩家姓名",
		["Scale"] = "框体缩放",
		["Set PerfectRaid's Scale"] = "框体缩放",
		["Group Separator"] = "组间间距",
		["Set the height of the separator"] = "组间间距",
		["Inverse Bars"] = "翻转状态条",
		["Show depletion bars"] = "翻转状态条",
		["Show Health Deficit"] = "显示血量减少具体数值",
		["Show health deficit"] = "显示血量减少具体数值",
		["Bar Texture"] = "状态条材质",
		["Change the status bar texture"] = "状态条材质",
		["Lock"] = "锁定",
		["Lock/Unlock PerfectRaid"] = "锁定/解锁PerfectRaid",
		["Sort"] = "PerfectRaid框体分组",
		["Sort the PerfectRaid frames"] = "PerfectRaid框体分组",
		["ManaBars"] = "魔法条",
		["Toggle mana bar overlays"] = "魔法条",
	}
end)
