
DART_CUSTOM_SETTINGS = {
		[1] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = -2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["xoffset"] = {
				[1] = 375,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["bgalpha"] = 1,
			["color"] = {
				["r"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["b"] = 0.4117647058823529,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["attachto"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 276,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Texture 2",
			["scale"] = 1.25,
			["height"] = 138,
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -548.5999862670899,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[2] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 1.25,
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["scripts"] = {
			},
			["texture"] = "Interface\\Glues\\Credits\\Parchment3",
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["xoffset"] = {
				[1] = 109,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["color"] = {
				["r"] = 0.4117647058823529,
				["g"] = 0.4117647058823529,
				["b"] = 0.4117647058823529,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["width"] = 276,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 2",
			["parent"] = "UIParent",
			["height"] = 138,
			["padding"] = 5,
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -548.5999862670899,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[3] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\leftframe1",
			["xoffset"] = {
				[1] = -512.9999856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["scale"] = 0.75,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 3",
			["parent"] = "UIParent",
			["height"] = 266,
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -362.4999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[4] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\rightframe1",
			["xoffset"] = {
				[1] = 511.5000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["scale"] = 0.75,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 4",
			["parent"] = "UIParent",
			["height"] = 266,
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = -363.2499885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[5] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 5,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["xoffset"] = {
				[1] = -168.4299856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["scale"] = 0.75,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 522,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 5",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["height"] = 138,
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\middelleft1",
			["yoffset"] = {
				[1] = -336.9099885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[6] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0.3,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["hidebg"] = true,
			["xoffset"] = {
				[1] = 248.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["bgalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 522,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 6",
			["parent"] = "UIParent",
			["height"] = 138,
			["padding"] = 5,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\middelright1",
			["yoffset"] = {
				[1] = -333.4999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[7] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 10,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["xoffset"] = {
				[1] = -1.999985694885254,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["bgalpha"] = 1,
			["scale"] = 0.75,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 74,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 7",
			["parent"] = "UIParent",
			["height"] = 138,
			["padding"] = 5,
			["scripts"] = {
			},
			["yoffset"] = {
				[1] = -437.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[8] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 1,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopleft1",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["xoffset"] = {
				[1] = 198,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["highlightalpha"] = 0,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 1,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 600,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 8",
			["scale"] = 0.75,
			["height"] = 139,
			["padding"] = 5,
			["parent"] = "UIParent",
			["yoffset"] = {
				[1] = -903.4999771118164,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[9] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 0.9372549019607843,
				["g"] = 0.9686274509803922,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 12,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chattopright1",
			["bgalpha"] = 1,
			["hidebg"] = true,
			["xoffset"] = {
				[1] = 349.0000143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["highlightalpha"] = 0.3,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 580,
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["name"] = "Texture 9",
			["scale"] = 0.76,
			["height"] = 106,
			["padding"] = -10,
			["parent"] = "UIParent",
			["yoffset"] = {
				[1] = -453.2499885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[10] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 5,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["highlightalpha"] = 0,
			["scripts"] = {
			},
			["hidebg"] = 1,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chatbleft1",
			["xoffset"] = {
				[1] = 135.2500143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 266,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["name"] = "Texture 10",
			["parent"] = "UIParent",
			["height"] = 266,
			["padding"] = 5,
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["yoffset"] = {
				[1] = -507.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[11] = {
			["strata"] = "LOW",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 5,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\chatbright1",
			["xoffset"] = {
				[1] = 41.7500143051148,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["parent"] = "UIParent",
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["width"] = 266,
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Texture 11",
			["scale"] = 0.75,
			["height"] = 266,
			["padding"] = 5,
			["highlightalpha"] = 0.3,
			["yoffset"] = {
				[1] = -508.2499885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[12] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 0,
			["scale"] = 0.75,
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["highlightalpha"] = 1,
			["bgalpha"] = 1,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topmiddel1v2",
			["xoffset"] = {
				[1] = 13.76654918670658,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["parent"] = "UIParent",
			["highlightcolor"] = {
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["width"] = 266,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Texture 12",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["height"] = 138,
			["padding"] = 5,
			["hidebg"] = 1,
			["yoffset"] = {
				[1] = 423.0013460159302,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[13] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 0,
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bgalpha"] = 0,
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topleft1v2",
			["xoffset"] = {
				[1] = -370.4134508132934,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["scale"] = 0.75,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 522,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Texture 13",
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["height"] = 74,
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = 455.0013460159302,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[14] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topright1v2",
			["xoffset"] = {
				[1] = 373.9965491867066,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["bgalpha"] = 1,
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["width"] = 522,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["name"] = "Texture 14",
			["scale"] = 0.75,
			["height"] = 74,
			["padding"] = 5,
			["parent"] = "UIParent",
			["yoffset"] = {
				[1] = 455.0013460159302,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[15] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topright1v2extra",
			["xoffset"] = {
				[1] = 585.9965491867066,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["width"] = 266,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Texture 15",
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["height"] = 74,
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = 455.0013460159302,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[16] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["bgalpha"] = 1,
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 2,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\topleft1v2extra",
			["xoffset"] = {
				[1] = -512.0034508132934,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["parent"] = "UIParent",
			["highlightalpha"] = 0.3,
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["width"] = 266,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["name"] = "Texture 16",
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["height"] = 74,
			["padding"] = 5,
			["hidebg"] = true,
			["yoffset"] = {
				[1] = 455.0013460159302,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[17] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["scale"] = 0.75,
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 113.9968275507291,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\castingbar",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["alpha"] = 1,
			["width"] = 522,
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["name"] = "Texture 17",
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["height"] = 74,
			["padding"] = 5,
			["hide"] = true,
			["yoffset"] = {
				[1] = -368.9967779596647,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[18] = {
			["strata"] = "HIGH",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 15,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\skull2",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["xoffset"] = {
				[1] = -1.999985694885254,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["hidebg"] = true,
			["parent"] = "UIParent",
			["bgalpha"] = 1,
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["width"] = 74,
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["alpha"] = 1,
			["name"] = "Texture 18",
			["scale"] = 0.75,
			["height"] = 138,
			["padding"] = 5,
			["hide"] = true,
			["yoffset"] = {
				[1] = -437.9999885559082,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[19] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = -1,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["scripts"] = {
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = -511.9999856948853,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframeleft",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["width"] = 266,
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["name"] = "Texture 19",
			["scale"] = 0.75,
			["height"] = 522,
			["padding"] = 5,
			["hide"] = true,
			["yoffset"] = {
				[1] = 28.0000114440918,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		[20] = {
			["strata"] = "BACKGROUND",
			["bgcolor"] = {
				["r"] = 0,
				["g"] = 0,
				["b"] = 0,
			},
			["borderalpha"] = 1,
			["color"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["coords"] = {
				[1] = 0,
				[2] = 1,
				[3] = 0,
				[4] = 1,
			},
			["attachframe"] = {
				[1] = "UIParent",
			},
			["framelevel"] = 0,
			["bgtexture"] = "Interface\\AddOns\\DiscordLibrary\\PlainBackdrop",
			["scripts"] = {
			},
			["attachto"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["hidebg"] = true,
			["bgalpha"] = 1,
			["xoffset"] = {
				[1] = 573,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
			["texture"] = "Interface\\AddOns\\DiscordArt\\CustomTextures\\new\\raidframelright",
			["parent"] = "UIParent",
			["attachpoint"] = {
				[1] = 5,
				[2] = 5,
				[3] = 5,
				[4] = 5,
			},
			["highlightalpha"] = 0.3,
			["bordertexture"] = "Interface\\Tooltips\\UI-Tooltip-Border",
			["Backdrop"] = {
				["top"] = 5,
				["edgeSize"] = 16,
				["tileSize"] = 16,
				["tile"] = true,
				["right"] = 5,
				["left"] = 5,
				["bottom"] = 5,
			},
			["bordercolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 1,
			},
			["alpha"] = 1,
			["width"] = 266,
			["text"] = {
				["hide"] = true,
				["color"] = {
					["r"] = 1,
					["g"] = 1,
					["b"] = 1,
				},
				["text"] = "",
				["justifyV"] = 5,
				["width"] = 100,
				["attachpoint"] = 2,
				["xoffset"] = 0,
				["fontsize"] = 16,
				["attachto"] = 2,
				["height"] = 20,
				["justifyH"] = 5,
				["alpha"] = 1,
				["yoffset"] = 0,
			},
			["highlightcolor"] = {
				["r"] = 1,
				["g"] = 1,
				["b"] = 0,
			},
			["name"] = "Texture 20",
			["scale"] = 0.75,
			["height"] = 522,
			["padding"] = 5,
			["hide"] = true,
			["yoffset"] = {
				[1] = 28.0000114440918,
				[2] = 0,
				[3] = 0,
				[4] = 0,
			},
		},
		["updatespeed"] = 60,
		["INITIALIZED1.0d"] = true,
		["optionsscale"] = 0.6,
		["autolock"] = 1,
		["INITIALIZED1.1"] = true,
	}
