FeralSkills_Localization = {};

FeralSkills_Localization.enUS = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.frFR = {
	SKILL_GROWL = "Grogner";
	SKILL_FERALCHARGE = "Charge farouche";
	SKILL_SWIPE = "Balayage";
	SKILL_ENRAGE = "Enrager";
	SKILL_FAERIEFIREFERAL = "Lucioles (farouche)";
	SKILL_DEMORALIZINGROAR = "Grognement d'intimidation";
	SKILL_MAUL = "Mutiler";
	SKILL_RIP = "Déchirure";
	SKILL_FEROCIOUSBITE = "Morsure Féroce";
	SKILL_RAKE = "Griffure";
	SKILL_COWER = "Se Recroqueviller";
	SKILL_CLAW = "Griffe";
	SKILL_TIGERSFURY = "Furie féline";
	SKILL_POUNCE = "Traquenard";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Lambeau";
	SKILL_CATFORM = "Forme de Félin";
	SKILL_BEARFORM = "Forme d’ours";
	SKILL_DIREBEARFORM = "Forme d'ours sinistre";
	SKILL_TRAVELFORM = "Forme de voyage";
	SKILL_AQUATICFORM = "Forme aquatique";
	SKILL_PROWL = "Rôder";
	ENERGYCOSTDETECTIONTEXT = "d'énergie";
	MOUNTDETECTIONTEXT = "Augmente la vitesse de mouvement";
}

FeralSkills_Localization.deDE = {
	SKILL_GROWL = "Knurren";
	SKILL_FERALCHARGE = "Wilde Attacke";
	SKILL_SWIPE = "Prankenhieb";
	SKILL_ENRAGE = "Wutanfall";
	SKILL_FAERIEFIREFERAL = "Feenfeuer (Tiergestalt)";
	SKILL_DEMORALIZINGROAR = "Demoralisierendes Gebr\195\188ll";
	SKILL_MAUL = "Zermalmen";
	SKILL_RIP = "Zerfetzen";
	SKILL_FEROCIOUSBITE = "Wilder Biss";
	SKILL_RAKE = "Krallenhieb";
	SKILL_COWER = "Ducken";
	SKILL_CLAW = "Klaue";
	SKILL_TIGERSFURY = "Tigerfuror";
	SKILL_POUNCE = "Anspringen";
	SKILL_RAVAGE = "Verheeren";
	SKILL_SHRED = "Schreddern";
	SKILL_CATFORM = "Katzengestalt";
	SKILL_BEARFORM = "B\195\164rengestalt";
	SKILL_DIREBEARFORM = "Terrorb\195\164rengestalt";
	SKILL_TRAVELFORM = "Reisegestalt";
	SKILL_AQUATICFORM = "Wassergestalt";
	SKILL_PROWL = "Schleichen";
	ENERGYCOSTDETECTIONTEXT = "Energie";
	MOUNTDETECTIONTEXT = "Erh\195\182hte Geschwindigkeit";
}

FeralSkills_Localization.enGB = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.koKR = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.zhCN = {
	SKILL_GROWL = "??";
	SKILL_FERALCHARGE = "????";
	SKILL_SWIPE = "??";
	SKILL_ENRAGE = "??";
	SKILL_FAERIEFIREFERAL = "???? (??)";
	SKILL_DEMORALIZINGROAR = "????";
	SKILL_MAUL = "??";
	SKILL_RIP = "??";
	SKILL_FEROCIOUSBITE = "????";
	SKILL_RAKE = "??";
	SKILL_COWER = "??";
	SKILL_CLAW = "??";
	SKILL_TIGERSFURY = "????";
	SKILL_POUNCE = "??";
	SKILL_RAVAGE = "??";
	SKILL_SHRED = "??";
	SKILL_CATFORM = "????";
	SKILL_BEARFORM = "???";
	SKILL_DIREBEARFORM = "????";
	SKILL_TRAVELFORM = "????";
	SKILL_AQUATICFORM = "????";
	SKILL_PROWL = "??";
	ENERGYCOSTDETECTIONTEXT = "??";
	MOUNTDETECTIONTEXT = "????";
}

FeralSkills_Localization.zhTW = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

FeralSkills_Localization.ruRU = {
	SKILL_GROWL = "Growl";
	SKILL_FERALCHARGE = "Feral Charge";
	SKILL_SWIPE = "Swipe";
	SKILL_ENRAGE = "Enrage";
	SKILL_FAERIEFIREFERAL = "Faerie Fire (Feral)";
	SKILL_DEMORALIZINGROAR = "Demoralizing Roar";
	SKILL_MAUL = "Maul";
	SKILL_RIP = "Rip";
	SKILL_FEROCIOUSBITE = "Ferocious Bite";
	SKILL_RAKE = "Rake";
	SKILL_COWER = "Cower";
	SKILL_CLAW = "Claw";
	SKILL_TIGERSFURY = "Tiger's Fury";
	SKILL_POUNCE = "Pounce";
	SKILL_RAVAGE = "Ravage";
	SKILL_SHRED = "Shred";
	SKILL_CATFORM = "Cat Form";
	SKILL_BEARFORM = "Bear Form";
	SKILL_DIREBEARFORM = "Dire Bear Form";
	SKILL_TRAVELFORM = "Travel Form";
	SKILL_AQUATICFORM = "Aquatic Form";
	SKILL_PROWL = "Prowl";
	ENERGYCOSTDETECTIONTEXT = "Energy";
	MOUNTDETECTIONTEXT = "Increases speed";
}

