
-- localization for TargetUnique
TUQ_STRING_BINDING_NAME_TUQ_TOGGLETARGET = "Start/Stop target acquisition"
TUQ_STRING_BINDING_NAME_TUQ_OPENCONFIG = "Open/close configuration panel"
TUQ_STRING_BINDING_NAME_TUQ_NEARESTUNIQUE = "Target nearest unique target"
TUQ_STRING_BINDING_NAME_TUQ_PAINT = "Toggle target painting"
TUQ_STRING_BINDING_NAME_TUQ_ERASE = "Toggle target marker erasure"
TUQ_STRING_STOPPING_ACQUISITION = "TargetUnique: Stopping target acquisition"
TUQ_STRING_STARTING_ACQUISITION = "TargetUnique: Acquiring target..."
TUQ_STRING_STOPPING_PAINTING = "TargetUnique: Stopping target painting"
TUQ_STRING_STARTING_PAINTING = "TargetUnique: Starting target painting"
TUQ_STRING_STOPPING_ERASING = "TargetUnique: Stopping target marker erasure"
TUQ_STRING_STARTING_ERASING = "TargetUnique: Starting target marker erasure"
TUQ_STRING_LOGGING_DISABLED = "TargetUnique: Logging Disabled"
TUQ_STRING_LOGGING_ENABLED = "TargetUnique: Logging Enabled"
TUQ_STRING_NOW_CHECKING_ENTIRE_RAID = "TargetUnique: Will now check the entire raid"
TUQ_STRING_NOW_CHECKING_ONLY_TANK_LIST = "TargetUnique: Will now only check the CTRA tank list"
TUQ_STRING_HELP_1 = "TargetUnique: targets mobs no one in your group/raid is targeting"
TUQ_STRING_HELP_2 = "/tuq or /targetunique: prints this message"
TUQ_STRING_HELP_3 = "/tuq target targets the next unique target you mouse over"
TUQ_STRING_HELP_4 = "/tuq config displays the configuration panel"
TUQ_STRING_CHECKING_ONLY_TANKS = "TargetUnique: Currently checking only tanks"
TUQ_STRING_CHECKING_ENTIRE_RAID = "TargetUnique: Currently checking entire raid"
TUQ_STRING_ACQUIRED = "TargetUnique: Acquired target: "
TUQ_CONFIG_FRAME_CTRA_TANKS_ONLY = "In CTRA, just check tanks"
TUQ_CONFIG_FRAME_CHECK_BY_CLASS = "Check by Class"
if (GetLocale() ~= "enGB" and GetLocale() ~= "enUS") then
   TUQ_STRING_BINDING_NAME_TUQ_TOGGLETARGET = GetLocale() .. " needed: Start/Stop target acquisition"
   TUQ_STRING_BINDING_NAME_TUQ_OPENCONFIG = GetLocale() .. " needed: Open/close configuration panel"
   TUQ_STRING_BINDING_NAME_TUQ_NEARESTUNIQUE = GetLocale() .. " needed: TargetNearest Unique Target"
   TUQ_STRING_STOPPING_ACQUISITION = GetLocale() .. " needed; TargetUnique: Stopping target acquisition"
   TUQ_STRING_STARTING_ACQUISITION = GetLocale() .. " needed; TargetUnique: Acquiring target..."
   TUQ_STRING_LOGGING_DISABLED = GetLocale() .. " needed; TargetUnique: Logging Disabled"
   TUQ_STRING_LOGGING_ENABLED = GetLocale() .. " needed; TargetUnique: Logging Enabled"
   TUQ_STRING_NOW_CHECKING_ENTIRE_RAID = GetLocale() .. " needed; TargetUnique: Will now check the entire raid"
   TUQ_STRING_NOW_CHECKING_ONLY_TANK_LIST = GetLocale() .. " needed; TargetUnique: Will now only check the CTRA tank list"
   TUQ_STRING_HELP_1 = GetLocale() .. " needed; TargetUnique: targets mobs no one in your group/raid is targeting"
   TUQ_STRING_HELP_2 = GetLocale() .. " needed; /tuq or /targetunique: prints this message"
   TUQ_STRING_HELP_3 = GetLocale() .. " needed; /tuq target targets the next unique target you mouse over"
   TUQ_STRING_HELP_4 = GetLocale() .. " needed; /tuq config displays the configuration panel"
   TUQ_STRING_CHECKING_ONLY_TANKS = GetLocale() .. " needed; TargetUnique: Currently checking only tanks"
   TUQ_STRING_CHECKING_ENTIRE_RAID = GetLocale() .. " needed; TargetUnique: Currently checking entire raid"
   TUQ_STRING_ACQUIRED = GetLocale() .. " needed; TargetUnique: Acquired target: "
   TUQ_CONFIG_FRAME_CTRA_TANKS_ONLY = GetLocale() .. " needed; In CTRA, just check tanks"
   TUQ_CONFIG_FRAME_CHECK_BY_CLASS = GetLocale() .. " needed; Check by Class"
end
